mdn/browser-compat-data

- browsers/edge.json
Edge 108 is available. Here is an update to the edge.json file.
> New Edge 108 version

- javascript/builtins/AsyncFunction.json
- javascript/builtins/AsyncGeneratorFunction.json
- javascript/builtins/GeneratorFunction.json
In sync with https://github.com/mdn/content/pull/22778. This simply copies the data from the root object.
> Split (Async)?(Generator)?Function class and ctor pages

- webextensions/api/omnibox.json
This PR adds compat data for SuggestResult.deletable and omnibox.onDeleteSuggestion in Firefox and Chrome. It also improves the accuracy of version_added for Chrome.
https://web.archive.org/web/20140317025403if_/https://developer.chrome.com/extensions/whats_new#9
https://web.archive.org/web/20110426141833/http://code.google.com/chrome/extensions/omnibox.html
https://developer.chrome.com/docs/extensions/reference/omnibox/
https://bugzilla.mozilla.org/show_bug.cgi?id=1478095
> Add deletable, onDeleteSuggestion, improve accuracy of version_added

- webextensions/api/omnibox.json
- webextensions/api/webRequest.json
Add compatibility info for the SecurityInfo.secretKeyLength property. 
https://bugzilla.mozilla.org/show_bug.cgi?id=1778473
> Add compat info for SecurityInfo.secretKeyLength

- api/Element.json
Page is created in https://github.com/mdn/content/pull/22846
> Add mdn_url for Element.elementTiming

- .github/workflows/auto-merge.yml
This PR adds a new workflow to automatically merge PRs made by Dependabot that update a dependency to its latest minor/patch version and successfully pass CI tests.
> Add workflow to auto-merge dependency updates

- html/elements/a.json
Adding BCD for the [Text fragments](https://web.dev/text-fragments/) feature. There's not much in this PR, as most of the required features were already present.
See my [research document](https://docs.google.com/document/d/1QnAfM06JS_OJ1iLKWJv9FuNE9s0vUJIJAOQz9AxkgLg/edit#heading=h.oieqm2j8cv9l) for more information on what data is needed.
> add data for text fragments

- api/Document.json
- api/FragmentDirective.json
When reviewing https://github.com/mdn/content/pull/22905, @Elchi3 noticed that I'd missed some URLs out of the corresponding BCD. This PR adds them in.
> Add missing fragment directive URLs to data

- javascript/builtins/Object.json
update __proto__ spec URL to match the appropriate one
> update __proto__ spec URL

- package-lock.json
This PR runs `npm update` to update all dependencies.
> Update all packages

- api/Document.json
Relates to https://github.com/mdn/content/pull/22809#issuecomment-1347488879
> Add note for document.domain on Chrome

- browsers/opera.json
Hello all!
Updating opera browsers with new release versions.
😉
> Updates opera browser release versions

- api/FileSystemHandle.json
This PR adds data for the new `FileSystemHandle.remove()` method. See my [research document](https://docs.google.com/document/d/1ymUjOxI8yL2krSrR3Mn3ZEAGhfQ1S592qQzPV89VSyg/edit#) for more information.
> Add data for FileSystemHandle.remove()

- .github/workflows/ping-other-repos.yml
Fixes https://github.com/mdn/browser-compat-data/issues/18565
> [gh-actions] Ignore dependabot for ping-other-repos workflow

- api/GamepadHapticActuator.json
When #16206 was merged, it appears that git handled the merge in an odd way, changing different lines than what was supposed to be changed.  This PR fixes these errors.
> Fix bad merge from #16206

- browsers/chrome.json
- browsers/chrome_android.json
- browsers/webview_android.json
This PR marks Chrome 109 as the current version of Chrome.
> Chrome 109 is released

- api/Navigator.json
Needed for https://github.com/mdn/content/pull/23575
Please advise if required for these minimal changes. 
Relates to https://github.com/mdn/content/pull/23575
> Adding spec url for Navigator unregisterProtocolHandler

- css/properties/content-visibility.json
Added the version_added value for Firefox
Tested in Nightly
[MDN Content PR](https://github.com/mdn/content/pull/23555)
[Firefox 109 Release notes PR](https://github.com/mdn/content/pull/23556)
> added firefox version_added for content-visibility

- webextensions/manifest/optional_permissions.json
- webextensions/manifest/permissions.json
Details of the `"webRequestfilterResponse"` and `"webRequestFilterResponse.serviceWorkerScript"` API permissions.
Address of the BCD requirements of [Bug 1809235](https://bugzilla.mozilla.org/show_bug.cgi?id=1809235).
PR for related content changes: https://github.com/mdn/content/pull/23699
> webRequestFilterResponse Permission

- browsers/firefox.json
- browsers/firefox_android.json
Hello!
Updating firefox browsers to version 109.
> Updates firefox browser to version 109

- webextensions/manifest/optional_permissions.json
Fixes incorrect presentation of webRequestFilterResponse.serviceWorkerScript made in #18665
> Fixed to webRequestFilterResponse.serviceWorkerScript

- css/properties/background-image.json
> Mirror data to `css.properties.background-image.image-set` from `css.types.image.image-set`

- webextensions/api/find.json
Add details of the `matchDiacritics` property in the Find API that mirrors the find UI and enables find to match on diacritics.
Addresses the documentation requirements for [Bug 1680606](https://bugzilla.mozilla.org/show_bug.cgi?id=1680606)
PR for content: https://github.com/mdn/content/pull/23775
> Find API option to match diacritics

- http/headers/Content-Security-Policy.json
Supporting details are in/linked from https://github.com/mdn/content/issues/23768.
> Remove require-sri-for

- api/XRFrame.json
- api/XRHand.json
- api/XRInputSource.json
- api/XRJointPose.json
- api/XRJointSpace.json
See https://learn.microsoft.com/en-us/windows/mixed-reality/develop/javascript/webxr-overview
> WebXR Hand Input is in Edge 93 (Hololens 2)

- html/global_attributes.json
Updated global_attributes.json since Opera supports Inert global attributes.
https://chromestatus.com/feature/5703266176335872
Fixes #18819
> Update support version for inert global attribute in Opera

- css/properties/initial-letter.json
See: https://chromestatus.com/feature/5167442033115136
> Add chrome initial-letter support

- scripts/diff-features.ts
This PR fixes the call to `enumerate-features` within the `diff-features` script, fixing the artifacts workflow.
> Fix enumerate-features call in diff-features script

- .github/ISSUE_TEMPLATE/data-problem.yml
This PR should help cut down on the spam/junk issues a little bit more.
> Update required fields for "Data problem" template

- api/SpeechSynthesisEvent.json
The page is created at mdn/content#24480
> Add mdn_url for SpeechSynthesisEvent.charLength

- browsers/firefox.json
- browsers/firefox_android.json
Hello!
Updating firefox browsers to version 110.
> Updates firefox browser to version 110

- browsers/chrome.json
- browsers/chrome_android.json
- browsers/webview_android.json
Hello! 👋
Including release notes for chrome desktop and updates chrome for android.
> Updates chrome for android and include release notes

- webextensions/api/browsingData.json
Mark a WebExtensions as supported on Firefox for Android since it was implemented with the other APIs in https://bugzilla.mozilla.org/show_bug.cgi?id=1625233
> browser.browsingData.removePasswords() is supported on Firefox for Android

- webextensions/api/action.json
All `browser.action` methods have been added in Firefox 101.
> Fix Firefox versions for `browser.action`

- javascript/builtins/Error.json
Updated Error.json since Error.cause was supported by Opera.
https://chromestatus.com/feature/5727099325251584
Fixes #18930
> Add support for Error cause in Opera

- webextensions/api/runtime.json
See: https://bugzilla.mozilla.org/show_bug.cgi?id=1518843
> Fix `browser.runtime` for Firefox for Android

- css/properties/visibility.json
> Update spec url

- api/OES_draw_buffers_indexed.json
I wrote the MDN content in https://github.com/mdn/content/pull/24707
> Add mdn_urls for OES_draw_buffers_indexed

- package-lock.json
This PR runs `npm update` to update all the dependencies that Dependabot doesn't.
> Run npm update to update all dependencies

- javascript/builtins/Function.json
Add new data before I send a content PR. These are copied from `Symbol.hasInstance`.
> Data for Function.p[@@hasInstance] feature

- css/at-rules/container.json
Adds a section for style container queries for custom properties.
In Chrome 111 (current beta, stable Mar 1) tested in the beta.
https://chromestatus.com/feature/5076875399921664
> adds style container queries

- webextensions/api/browsingData.json
All these properties have been supported since Firefox 85, see:
https://bugzilla.mozilla.org/show_bug.cgi?id=1625233
> Fix `browser.browsingData` for Firefox for Android

- webextensions/api/webRequest.json
Add compat info for new SecurityInfo fields. 
See https://github.com/mdn/content/pull/24455
> Add compat data for new SecurityInfo fields.

- package-lock.json
- package.json
- tsconfig.json
This PR switches our use of the slow `tsc` to the speedy `swc` when running scripts.  This greatly improves the performance of our scripts so we don't have to sit around for as long waiting for scripts to run.
> Switch from tsc to swc to improve performance

- html/elements/applet.json
Fix https://github.com/mdn/browser-compat-data/issues/17956
Fix https://github.com/mdn/browser-compat-data/issues/18851
> Safari 14.1 removed <applet>

- webextensions/api/pageAction.json
See: https://bugzilla.mozilla.org/show_bug.cgi?id=1530402
> Fix `browser.pageAction` for Firefox for Android

- html/elements/link.json
> Remove deprecated flag from disabled subfeature

- api/AudioProcessingEvent.json
We are in the process of documenting these.
> Add missing spec_url and mdn_url fields for AudioProcessingEvent.*

- api/ServiceWorkerGlobalScope.json
See https://github.com/mdn/content/pull/25302.
> Add spec URL and MDN URL for background fetch events

- browsers/edge.json
Hello,
Updating edge browser to version 111.
> Updates edge browser to version 111

- .github/ISSUE_TEMPLATE/data-problem.yml
Requested by @estelle to help reduce confusion.
> Explicitly use the word "example" in issue template

- api/File.json
This PR updates and corrects version values for Firefox and Firefox Android for the `webkitRelativePath` member of the `File` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v8.1.2).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/File/webkitRelativePath
> Update Firefox data for api.File.webkitRelativePath

- api/CSSFontPaletteValuesRule.json
Add the missing `mdn_url` entries for `CSSFontPaletteValuesRule.*`
We are adding these pages in mdn/content#25476.
> Add mdn_url for CSSFontPaletteValuesRule.*

- api/ByteLengthQueuingStrategy.json
- api/CountQueuingStrategy.json
The MDN pages just got added in https://github.com/mdn/content/pull/25503
> Add mdn-url for (Count|ByteLength)QueuingStrategy.highWaterMark

- api/Window.json
We documented this long time ago.
> Add missing mdn_url for Window.captureEvents()

- api/CSSFontFeatureValuesRule.json
We are creating these two pages in: https://github.com/mdn/content/pull/25570
> Add missing mdn_url in CSSFontFeatureValuesRule

- api/MediaDeviceInfo.json
This MDN page was added earlier this Quarter.
> Add missing mdn_url MediaDeviceInfo.json

- api/ServiceWorker.json
> Add mssing mdn_url in ServiceWorker.json

- api/SVGElement.json
The PR adding this page is in review.
> Adding missing mdn_url in SVGElement.json

- api/SVGMaskElement.json
These pages were added last week.
> Add missing mdn_url for SVGMaskElement.json

- api/SVGClipPathElement.json
These pages got added last week.
> Add missing mdn_url for SVGClipPathElement.json

- api/CryptoKey.json
Specific pages got created this Quarter, so mdn_url became wrong. Fixing it.
> Fix mdn_url in CryptoKey.json

- api/XMLSerializer.json
We are adding this page in mdn/content#25619
> Add missing mdn_url for XMLSerializer()

- api/SpeechSynthesisErrorEvent.json
- api/SpeechSynthesisEvent.json
We added the pages in mdn/content#25617
> Add mdn_url for SpeechSynthesis*Event ctors

- api/XPathEvaluator.json
We are adding this page on MDN in: mdn/content#25620
> Add mdn_url for XPathEvaluator()

- api/FileReaderSync.json
We added this page in mdn/content#25621
> Add mdn_url and spec_url for FileReaderSync()

- api/WebGLContextEvent.json
We add this page in mdn/content#25622
> Add missing mdn_url for WebGLContextEvent()

- api/ShadowRoot.json
We added this page in mdn/content#25649
> Add missing mdn_url in ShadowRoot.json

- api/HashChangeEvent.json
This page has been added in mdn/content#25730.
> Add missing mdn_url for HashChangeEvent()

- api/PageTransitionEvent.json
The page has been added in mdn/content#25731
> Add missing mdn_url for PageTransitionEvent()

- javascript/builtins/String.json
Spec: https://tc39.es/proposal-is-usv-string/#sec-string.prototype.towellformed
Safari 16.4: https://tc39.es/proposal-is-usv-string/#sec-string.prototype.towellformed
Chrome 111: https://chromestatus.com/feature/5200195346759680
> Add String.prototype.isWellFormed and toWellFormed

- api/Navigator.json
Fix https://github.com/mdn/browser-compat-data/issues/19248
> Safari iOS 16.4 supports Badging API

- api/MediaCapabilities.json
> Add Firefox note (the value `webrtc` is called `transmission`)

- javascript/builtins/ArrayBuffer.json
- javascript/builtins/SharedArrayBuffer.json
https://webkit.org/blog/13966/webkit-features-in-safari-16-4/
> Safari 16.4 supports resizable ArrayBuffer / growable SAB

- javascript/operators/import_meta.json
https://github.com/WebKit/WebKit/commit/78c6d6d7b596a5953915f8066a5e75d19eda8411
https://webkit.org/blog/13966/webkit-features-in-safari-16-4/
> Safari 16.4 supports import.meta.resolve()

- javascript/builtins/FinalizationRegistry.json
- javascript/builtins/WeakMap.json
- javascript/builtins/WeakRef.json
- javascript/builtins/WeakSet.json
Safari 16.4 https://webkit.org/blog/13966/webkit-features-in-safari-16-4/
Chrome 108: https://groups.google.com/a/chromium.org/g/blink-dev/c/E6pDZP_TiBA/m/ZcXLwiz8AAAJ
Firefox: Not yet: https://bugzilla.mozilla.org/show_bug.cgi?id=1710433
> Symbols in WeakMap, WeakSet, WeakRef, FinalizationRegistry

- api/PaintWorkletGlobalScope.json
Noticed this while trying to fix the bogus docs
> Fix mdn_url for PaintWorkletGlobalScope 

- javascript/builtins/AsyncIterator.json
- javascript/builtins/Iterator.json
I am documenting these objects in https://github.com/mdn/content/pull/25892 and I'm totally surprised that BCD data already exists. The only thing lacking is spec URL.
> Add spec URLs for Iterator/AsyncIterator

- api/GPUPipelineError.json
In my [WebGPU work](https://github.com/mdn/content/pull/24202), I forgot to include the BCD for [`GPUPipelineError`](https://gpuweb.github.io/gpuweb/#gpupipelineerror). This PR adds it in.
> Add GPUPipelineError data

- javascript/builtins/Promise.json
- javascript/builtins/SharedArrayBuffer.json
The pages have existed for a while, but there's no data yet.
> Data for {Promise,SharedArrayBuffer}[@@species]

- javascript/builtins/AggregateError.json
Content PR is merged; need corresponding BCD
> Data for AggregateError#errors

- javascript/builtins/Array.json
- javascript/builtins/TypedArray.json
See https://github.com/mdn/content/pull/25488
> Data for change-array-by-copy

- browsers/firefox.json
- browsers/firefox_android.json
Hello! 👋
Updating firefox to version 112.
> Updating firefox browser to version 112

- css/properties/animation-timeline.json
This should be using the unversioned spec URL
> Update scroll-animations spec URL

- browsers/edge.json
Hello! 👋
Updating edge browser to version 112.
> Updates edge browser to version 112

- javascript/builtins/Intl/Locale.json
See https://github.com/mdn/content/issues/26288
Continuation of https://github.com/mdn/browser-compat-data/pull/19392
> Intl.Locale info APIs are now methods

- api/Magnetometer.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `Magnetometer` API. Other
> Update Chromium data for Magnetometer API

- webextensions/api/declarativeNetRequest.json
- webextensions/manifest/declarative_net_request.json
- webextensions/manifest/optional_permissions.json
- webextensions/manifest/permissions.json
Update for the availability of `declarative_net_request` in Firefox 113
> declarative_net_request availability

- api/ValidityState.json
Missing pages are getting added in mdn/content#26431
> Add missing mdn_url for ValidityState members

- javascript/builtins/Intl.json
- javascript/builtins/Intl/NumberFormat.json
- javascript/builtins/Intl/PluralRules.json
> Update spec URLs that are now in the main spec

- browsers/deno.json
Add Deno version 1.33
https://deno.com/blog/v1.33#v8-114
> add Deno version 1.33

- webextensions/api/management.json
> management.getSelf available in Opera

- api/WebTransport.json
- api/WebTransportBidirectionalStream.json
- api/WebTransportDatagramDuplexStream.json
- api/WebTransportError.json
- api/WebTransportReceiveStream.json
FF114 is shipping WebTransport and friends in https://bugzilla.mozilla.org/show_bug.cgi?id=1831073. This updates the release and fixes up features that are no longer experimental.
Other docs work can be tracked in https://github.com/mdn/content/issues/26684
> FF114 WebTransport - shipping

- api/Element.json
- api/HTMLElement.json
Fix https://github.com/mdn/browser-compat-data/issues/19594
> Move error_event from Element to HTMLElement

- webextensions/api/downloads.json
> downloads.drag removed from Chromium

- api/HTMLButtonElement.json
- api/HTMLElement.json
- api/HTMLInputElement.json
- api/ToggleEvent.json
- css/selectors/backdrop.json
- css/selectors/popover-open.json
- html/global_attributes.json
Fixes https://github.com/mdn/browser-compat-data/issues/19641
Closes https://github.com/mdn/browser-compat-data/pull/19432
> Popover API is in Safari preview

- api/ScreenOrientation.json
Fix https://github.com/mdn/browser-compat-data/issues/19355
> lock in screen.orientation isnt supported in Safari

- html/elements/link.json
- html/elements/script.json
- html/elements/style.json
Fix https://github.com/mdn/browser-compat-data/issues/19869
Data taken from the API counterparts.
> HTML: add blocking attr to link, style, script

- webextensions/manifest/action.json
- webextensions/manifest/browser_action.json
- webextensions/manifest/options_ui.json
- webextensions/manifest/page_action.json
- webextensions/manifest/sidebar_action.json
Provides documentation for [Bug 1827910](https://bugzilla.mozilla.org/show_bug.cgi?id=1827910) "Deprecate browser_style in MV3"
> Deprecate browser_style in MV3

- api/CanvasFilter.json
Follow-up to https://github.com/mdn/browser-compat-data/pull/19916
> Update CanvasFilter status

- svg/elements/desc.json
- svg/elements/feBlend.json
- svg/elements/feColorMatrix.json
- svg/elements/feComponentTransfer.json
- svg/elements/feComposite.json
- svg/elements/feConvolveMatrix.json
- svg/elements/feDiffuseLighting.json
- svg/elements/feDisplacementMap.json
- svg/elements/feDistantLight.json
- svg/elements/feDropShadow.json
- svg/elements/feFlood.json
- svg/elements/feFuncA.json
- svg/elements/feFuncB.json
- svg/elements/feFuncG.json
- svg/elements/feFuncR.json
- svg/elements/feGaussianBlur.json
- svg/elements/feImage.json
- svg/elements/feMerge.json
- svg/elements/feMergeNode.json
- svg/elements/feMorphology.json
- svg/elements/feOffset.json
- svg/elements/fePointLight.json
- svg/elements/feSpecularLighting.json
- svg/elements/feSpotLight.json
- svg/elements/feTile.json
- svg/elements/feTurbulence.json
This PR mirrors the data from the interface counterparts to the "FE" SVG elements.
> Mirror interface data to FE* SVG elements

- webextensions/api/tabs.json
Complementary change to Rename tabs.onUpdated extraParameters [#21524](https://github.com/mdn/content/pull/21524)
> Rename tabs.onUpdated extraParameters to filter

- api/OffscreenCanvasRenderingContext2D.json
Fix https://github.com/mdn/browser-compat-data/issues/19929
> Chromium doesn't support OffscreenCanvas.commit

- api/WEBGL_debug_shaders.json
See https://bugzilla.mozilla.org/show_bug.cgi?id=1377974
> Firefox 56 ships WebGL_debug_shaders everywhere

- browsers/deno.json
Add Deno version 1.34
https://deno.com/blog/v1.34#v8-115-and-typescript-504
> add Deno version 1.34

- README.md
This PR updates the readme to include examples of importing BCD using dynamic imports.
> Add examples of dynamic import to readme

- browsers/chrome.json
- browsers/chrome_android.json
As per the [Chrome roadmap](https://chromestatus.com/roadmap), some of the Chrome version release dates have changed. This PR updates those.
> Update Chrome release versions

- api/WEBGL_compressed_texture_pvrtc.json
See https://github.com/WebKit/WebKit/commit/78ef21e2214016e8641a6e188f2a97c368d4dfe9
> Safari 7 implemented WEBGL_compressed_texture_pvrtc

- docs/data-guidelines/api.md
Fixes https://github.com/mdn/browser-compat-data/issues/16613
Requesting approval from multiple BCD owners.
> Add a guideline for static API members

- browsers/firefox.json
- browsers/firefox_android.json
Hello!
This PR updates firefox browser version.
> Update firefox browser to latest version 114

- api/MediaDevices.json
This is the accompanying PR for the content change at https://github.com/mdn/content/pull/24279. It would be good to review the two as a set.
> Add getdisplaymedia option default values

- api/Navigator.json
In preparation for documenting `Navigator.getInstalledRelatedApps()`, I'm using this PR to update the compat data. 
The source for the new data is https://web.dev/get-installed-related-apps/.
> Update getInstalledRelatedApps() compat data

- javascript/builtins/Atomics.json
- javascript/builtins/String.json
This PR updates spec URLs for proposals that got advanced and integrated in the May tc39 meeting.
> Update stage-4 proposal spec URLs

- api/Document.json
- api/Element.json
Updated Element.json and Document.json since scrollend event is now supported by Chromium Based Browsers.
https://chromestatus.com/feature/5186382643855360
#20103
> fix support version for scrollend event in chromium-based-browsers

- css/properties/font-synthesis-small-caps.json
- css/properties/font-synthesis-style.json
- css/properties/font-synthesis-weight.json
Added the 'mdn-url' key to the font-synthesis-* properties.
Content PR that adds these pages: https://github.com/mdn/content/pull/27413
> Add "mdn_urls" to font-synthesis-* properties

- css/at-rules/font-face.json
Content PR that adds the new page for `font-feature-settings` descriptor: https://github.com/mdn/content/pull/27513
This PR adds the MDN and spec URLs to the existing BCD for `font-feature-settings`.
>  Add "mdn_url" and "spec_url" to font-feature-settings descriptor of @font-face

- api/HTMLImageElement.json
Corrects the link to the specification for the `src` attribute on HTMLImageElement.
> Update link to HTMLImageElement img src attribute

- api/Navigator.json
Fix https://github.com/mdn/browser-compat-data/issues/15357
> Remove title param from Navigator.registerProtocolHandler

- api/Worker.json
Fix https://github.com/mdn/browser-compat-data/issues/20065
> Firefox 114 supports api.Worker.Worker.options_type_parameter

- api/ScrollTimeline.json
- api/ViewTimeline.json
- css/at-rules/keyframes.json
- css/properties/animation-range-end.json
- css/properties/animation-range-start.json
- css/properties/animation-range.json
- css/properties/animation-timeline.json
- css/properties/timeline-scope.json
- css/properties/view-timeline-axis.json
- css/properties/view-timeline-inset.json
- css/properties/view-timeline-name.json
- css/properties/view-timeline.json
These should all be using the unversioned spec URLs at drafts.csswg.org
> Fix scroll-animations spec URL

- javascript/builtins/Intl/NumberFormat.json
- javascript/builtins/Intl/PluralRules.json
Fix https://github.com/mdn/browser-compat-data/issues/20258
Fix https://github.com/mdn/browser-compat-data/issues/18447
Chrome 106: https://chromestatus.com/feature/5707621009981440
Nodejs 19.0.0 https://nodejs.org/en/blog/release/v19.0.0#v8-10.7
Safari 15.4 https://developer.apple.com/documentation/safari-release-notes/safari-15_4-release-notes#JavaScript
Safari 16.4 https://developer.apple.com/documentation/safari-release-notes/safari-16_4-release-notes#JavaScript
Firefox 116: https://bugzilla.mozilla.org/show_bug.cgi?id=1795756
> Update Intl.NumberFormat v3 data

- webextensions/api/runtime.json
Fixes error in removed version.
> Correct version removed for setUninstallURL length change

- mathml/elements/mtd.json
Add mtd@columnspan/rowspan support for Chromium 117.
These attributes will be supported in Chromium 117:
https://chromiumdash.appspot.com/commit/9c37b228a168a020e49a51461a1defed82e5de23 https://chromestatus.com/feature/5157467960377344
N/A
> [mathml] Update mtd@columnspan/rowspan support for Chromium 117

- webextensions/api/runtime.json
as a part of https://github.com/mdn/content/pull/28192, moving to BCD [per request](https://github.com/mdn/content/pull/27483#issuecomment-1631738728)
> Update getManifest information to improve browser nuances

- browsers/samsunginternet_android.json
Source https://en.wikipedia.org/wiki/Samsung_Internet
(I don't know if the Chromium version is correct.)
Needed for https://github.com/mdn/browser-compat-data/pull/20213
> Add Samsung Internet 22

- css/properties/text-combine-upright.json
Fix https://github.com/mdn/browser-compat-data/issues/20224
> Edge supports text-combine-upright

- browsers/edge.json
I'm updating some of the information in the `edge.json` file to match actual releases, dates, and release note links.
N/A.
N/A.
> Updates to Edge version information

- api/ContactAddress.json
- api/ContactsManager.json
- api/Navigator.json
Fix https://github.com/mdn/browser-compat-data/issues/19998
> Samsung Internet doesn't support Contact Picker API

- css/properties/mask-origin.json
Fixes #20406
Also see
https://github.com/mdn/content/pull/28157
https://github.com/web-platform-tests/wpt/pull/41279
> Remove margin-box from css.properties.mask-origin

- javascript/builtins/Set.json
Adds data for https://github.com/tc39/proposal-set-methods.
> Data for stage 3 set-methods

- javascript/regular_expressions.json
Adds data for https://github.com/tc39/proposal-duplicate-named-capturing-groups.
> Data for stage 3 duplicate-named-capturing-groups

- api/PerformanceNavigationTiming.json
Chrome info is from https://chromestatus.com/feature/5140317616996352
> Add PerformanceNavigationTiming.criticalCHRestart

- api/PerformanceResourceTiming.json
Chrome info is from https://chromestatus.com/feature/6347141115543552
> Add PerformanceResourceTiming.deliveryType

- api/PerformanceResourceTiming.json
Chrome info comes from https://chromestatus.com/feature/5086730938482688
> Add PerformanceResourceTiming.firstInterimResponseStart

- css/properties/text-wrap.json
`text-wrap: pretty` is in Chrome 117.
https://chromestatus.com/feature/5145771917180928
> text-wrap: pretty

- css/types/ratio.json
This clarifies the description.
No testing done; description change only.
Fixes #20571.
> Clarify css.types.ratio.number_value description

- RELEASE_NOTES.md
- package-lock.json
- package.json
> Release v5.3.13

- RELEASE_NOTES.md
- package-lock.json
- package.json
> Release v5.3.14

- browsers/edge.json
Updating the edge.json file to reflect new versions.
N/A.
N/A.
> New Edge versions

- css/at-rules/page.json
Fixes https://github.com/mdn/browser-compat-data/issues/20596
> Firefox 95 ships page sizes

- RELEASE_NOTES.md
- package-lock.json
- package.json
> Release v5.3.15

- RELEASE_NOTES.md
- package-lock.json
- package.json
> Release v5.3.16

- RELEASE_NOTES.md
- package-lock.json
- package.json
> Release v5.3.17

- RELEASE_NOTES.md
- package-lock.json
- package.json
> Release v5.3.18

- RELEASE_NOTES.md
- package-lock.json
- package.json
> Release v5.3.19

- browsers/opera.json
Added some missing previous Opera versions and corrected some further data.
> docs: added missing Opera releases

- webextensions/api/cookies.json
Expands cookies.SameSiteStatus details to include the values this type takes with details of support and variations.
BCD update for https://github.com/mdn/content/pull/28721
> cookies.SameSiteStatus update

- css/selectors/subsequent-sibling.json
- related to https://github.com/mdn/content/pull/29394
> fix(css): rename 'Genearal sibling' to 'Subsequent-sibling'

- RELEASE_NOTES.md
- package-lock.json
- package.json
> Release v5.3.20

- browsers/opera.json
Updated current Operas browser data, as version 103 has been release on 3rd of October:
- https://blogs.opera.com/desktop/2023/10/introducing-opera-103/
And _Opera Beta_ currently already provides the upcoming version 104 with _Chromium-Version_ `118.0.5993.11`
> docs(opera): updated current browsers release

- RELEASE_NOTES.md
- package-lock.json
- package.json
> Release v5.3.21

- RELEASE_NOTES.md
- package-lock.json
- package.json
> Release v5.3.22

- css/at-rules/supports.json
Update support for @supports font-format in Safari 17
Release notes: https://developer.apple.com/documentation/safari-release-notes/safari-17-release-notes#CSS
Added in PR: https://github.com/WebKit/WebKit/pull/12133
> Safari 17 adds support for @supports font-format

- css/at-rules/font-face.json
Added in Safari 17: https://developer.apple.com/documentation/safari-release-notes/safari-17-release-notes#CSS
Update safari support for the @font-face size-adjust descriptor
Added in Safari 17: https://developer.apple.com/documentation/safari-release-notes/safari-17-release-notes#CSS
> Update safari support for @font-face size-adjust

- api/BeforeUnloadEvent.json
- api/Window.json
Reverts mdn/browser-compat-data#20942.
> Revert "Update Chrome beforeunload dialog control behavior"

- RELEASE_NOTES.md
- package-lock.json
- package.json
> Release v5.3.23

- css/properties/offset-path.json
This PR makes a tiny update of `<url()>` to `<url>` to match the [Formal syntax](https://developer.mozilla.org/en-US/docs/Web/CSS/offset-path#formal_syntax) and [content update](https://github.com/mdn/content/pull/29141#discussion_r1331935260).
Also added a few more words to the description - "Support for"
> Update url syntax in offset-path

- RELEASE_NOTES.md
- package-lock.json
- package.json
> Release v5.3.24

- RELEASE_NOTES.md
- package-lock.json
- package.json
> Release v5.3.25

- RELEASE_NOTES.md
- package-lock.json
- package.json
> Release v5.3.26

- RELEASE_NOTES.md
- package-lock.json
- package.json
> Release v5.3.27

- browsers/firefox.json
- browsers/firefox_android.json
Update Firefox versions statuses
> Firefox 119 release

- .github/workflows/close-incomplete-issues.yml
This PR switches the invalid issue closer to my own fork, as had been suggested in a thread with Daniel on Slack.
> Switch invalid issue closer to queengooborg fork

- webextensions/api/runtime.json
> runtime.sendNativeMessage in Firefox for Android

- RELEASE_NOTES.md
- package-lock.json
- package.json
> Release v5.3.28

- api/Navigator.json
maybe need to wait for https://github.com/mdn/content/pull/29976 to be merged
> add `mdn_url` to some members of `Navigator` interface

- api/Window.json
> add missing mdn_url members in `Window` interface

- api/ReadableStream.json
Fixes #21152
Supporting information for this change in that issue.
> ReadableStream.from_static - deno/nodejs support

- api/Screen.json
see https://developer.mozilla.org/en-US/docs/Web/API/Screen and https://developer.mozilla.org/en-US/docs/Web/API/Window_Management_API
> add mdn_url in new items in `Screen` interface

- api/WorkerNavigator.json
see https://github.com/mdn/content/pull/30060
> add mdn_url for navigator.usb

- RELEASE_NOTES.md
- package-lock.json
- package.json
> Release v5.3.29

- api/Navigator.json
the documentation for `Navigator.bluetooth` will be added via https://github.com/mdn/content/pull/30150
> add mdn link for `Navigator.bluetooth`

- RELEASE_NOTES.md
- package-lock.json
- package.json
> Release v5.3.30

- api/CustomElementRegistry.json
> Add Safari note to CustomElementRegistry.get

- api/Window.json
Related with https://github.com/mdn/content/pull/29719 and https://github.com/mdn/content/pull/30008, which were recently added
> add mdn link of `Window` interface

- browsers/safari_ios.json
Followup to https://github.com/mdn/browser-compat-data/pull/21236.
> Update Safari iOS 17.1 and add iOS 17.2

- css/selectors/dir.json
https://chromestatus.com/feature/5751531651465216
https://chromiumdash.appspot.com/commit/e43705eacbfc57205193d918861a155c2f92a1bb
> Mark `:dir()` as shipping in Chrome 120

- api/CustomElementRegistry.json
See https://github.com/WebKit/WebKit/commit/e2748d7c56a29d295d71552e3d999d7b51ca037e and https://developer.apple.com/documentation/safari-release-notes/safari-17-release-notes
> Update Safari value for CustomElementRegistry.getName

- RELEASE_NOTES.md
- package-lock.json
- package.json
> Release v5.4.0

- javascript/builtins/Intl.json
- javascript/builtins/Map.json
The MDN pages are redirects and I think we should be consistent and decide to not have these Symbols in the data. These two were the only places.
> Remove @@toStringTag

- api/TaskSignal.json
the page is adding via https://github.com/mdn/content/pull/30314
> add mdn_url for `TaskSignal.any`

- api/Navigator.json
- api/NavigatorManagedData.json
The collector found this new API.
Chromestatus confirms 119: https://chromestatus.com/feature/5694001745231872
> Add Managed Device API

- RELEASE_NOTES.md
- package-lock.json
- package.json
> Release v5.4.1

- css/types/basic-shape.json
Typo in mdn_url (the page does exist)
> Update mdn_url for xywh() inbasic-shape.json

- javascript/builtins/Promise.json
Found by the Open Web Docs BCD Collector.
Chrome 119 confirmed by https://chromestatus.com/feature/5810984110784512
Firefox 121 confirmed by https://bugzilla.mozilla.org/show_bug.cgi?id=1845586
> Add Promise.withResolvers

- browsers/opera_android.json
Add latest opera android versions
https://forums.opera.com/topic/62482/opera-for-android-75?_=1701269694242&lang=en-GB
https://forums.opera.com/topic/63567/opera-for-android-76?_=1701269694246&lang=en-GB
https://forums.opera.com/topic/65830/opera-for-android-77?lang=en-GB
https://forums.opera.com/topic/67255/opera-for-android-78?lang=en-GB
> Add opera android versions

- api/Window.json
As suggested by @wbamberg here: https://github.com/mdn/content/pull/30610#issuecomment-1832228822
> resize_event: better spec_url

- api/WorkerNavigator.json
the documentation of `WorkerNavigator.deviceMemory` has been added via https://github.com/mdn/content/pull/30538
> add mdn_url for `WorkerNavigator.deviceMemory`

- RELEASE_NOTES.md
- package-lock.json
- package.json
> Release v5.4.3

- api/Navigator.json
add a description key
fix the issue below
> Fix a description of Secure context required of `Navigator.userAgentData`

- .github/labeler.yml
This PR upgrades the labeler config to the v5 structure.
> Update labeler config to new structure

- .github/labeler.yml
- .github/workflows/labeler.yml
- Revert "Update labeler config to new structure (#21476)"
- Revert "Bump actions/labeler from 4 to 5 (#21461)"
> Revert "Bump actions/labeler from 4 to 5"

- RELEASE_NOTES.md
- package-lock.json
- package.json
> Release v5.4.4

- .github/workflows/update-browser-releases.yml
- docs/matching-browser-releases/index.md
- schemas/browsers-schema.md
- scripts/diff-features.ts
- scripts/fix/browser-order.ts
- scripts/fix/index.ts
- scripts/fix/mirror.ts
- scripts/update-browser-releases/utils.ts
The PR pulls following code change:
- update deprecated values
- some trivial code simplification
- updates markdown code fence languages
> Fix typos/broken links; improve code

- RELEASE_NOTES.md
- package-lock.json
- package.json
> Release v5.4.5

- html/elements/script.json
see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script
> update `description` key of `<script>` element `type` attribute values

- browsers/opera_android.json
Add latest Opera Android version
<https://forums.opera.com/topic/68490/opera-for-android-79>
> docs: add new stable opera android version

- .eslintrc.json
- scripts/diff.ts
- scripts/lib/git.ts
- scripts/lib/stringify-and-order-properties.ts
- scripts/migrations/002-remove-webview-flags.ts
- scripts/release/build.ts
- scripts/release/changes.ts
- scripts/release/stats.ts
- scripts/remove-redundant-flags.ts
- scripts/statistics.ts
- scripts/update-browser-releases/firefox.ts
- test/linter/test-consistency.ts
- test/linter/test-descriptions.ts
- test/linter/test-links.ts
- test/linter/test-status.ts
- test/linter/test-versions.ts
- test/utils.ts
- utils/walk.ts
This PR adds the `@typescript-eslint/stylistic` configuration to ESLint, which is recommended by the package.
> Use stylistic typescript-eslint configuration

- api/HTMLButtonElement.json
- api/HTMLFieldSetElement.json
- api/HTMLInputElement.json
- api/HTMLObjectElement.json
- api/HTMLOutputElement.json
- api/HTMLSelectElement.json
- api/HTMLTextAreaElement.json
Will fix failing `main`.
(I merged an old PR that wasn't complying to this lint yet.)
> Fix bug links according to linter

- test/linter/test-browsers-presence.ts
This PR fixes the messages and behavior of the browser presence linter.
> Fix browser presence linter

- http/headers/Content-Security-Policy.json
see firefox release https://github.com/mdn/content/blob/main/files/en-us/mozilla/firefox/releases/63/index.md?plain=1#L127
> Update Firefox data for `Content-Security-Policy` `report-sample` value

- css/properties/column-gap.json
- css/properties/gap.json
- css/properties/row-gap.json
Tag the features needed for flexbox's additional gap features.
Specifically, these features:
- `css.properties.column-gap.flex_context`
- `css.properties.gap.flex_context`
- `css.properties.row-gap.flex_context`
https://github.com/web-platform-dx/web-features/pull/494
> Tag `flexbox-gap` features

- api/MediaSession.json
these documentations have been added via https://github.com/mdn/content/pull/18528 for more than one year
see https://developer.mozilla.org/en-US/docs/Web/API/MediaSession
> Add mdn_url for `MediaSession.setCameraActive()` and `MediaSession.setMicrophoneActive()`

- html/global_attributes.json
its document has been written yet
> Add mdn_url for `virtualkeyboardpolicy` global attribute

- schemas/compat-data-schema.md
Fix links to data guidelines from schema docs.
N/A, no actual browser-compat-data changes.
N/A
> fix references to data guidelines

- webassembly/threads-and-atomics.json
See https://chromestatus.com/feature/5724132452859904
> Update wasm threads and atomics compat data

- css/properties/mix-blend-mode.json
just turns the keyword "plus-lighter" into code
> Update mix-blend-mode - add code around keyword

- RELEASE_NOTES.md
- package-lock.json
- package.json
> Release v5.5.1

- scripts/update-browser-releases/firefox.ts
This error prevented #21685 from being merged.
> update-browser-releases: planned must be a String

- css/properties/scrollbar-gutter.json
fix: https://github.com/mdn/browser-compat-data/issues/21693
> Update CSS scrollbar-gutter

- html/elements/a.json
Matches `api.HTMLAnchorElement.coords` and `api.HTMLAnchorElement.shape`.
> Update Chrome for <a> coords & shape attributes

- api/Document.json
see https://wicg.github.io/page-lifecycle/spec.html
> Add spec-url for Page Lifecycle API

- api/Document.json
its documentation has been added via https://github.com/mdn/content/pull/30654
see also https://developer.mozilla.org/en-US/docs/Web/API/Document
> Add mdn_url for `Document.requestStorageAccessFor()`

- api/KeyboardEvent.json
the page has already been written yet, see https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent
> Add mdn_url for `KeyboardEvent.initKeyboardEvent()`

- html/elements/track.json
See https://github.com/mdn/browser-compat-data/issues/21698
> Add data for <track kind='descriptions'>

- RELEASE_NOTES.md
- package-lock.json
- package.json
> Release v5.5.2

- api/MediaRecorder.json
the documentation has been added via https://github.com/mdn/content/pull/31231
> add mdn_url for `MediaRecorder.audioBitrateMode`

- api/PaymentManager.json
the `PaymentManager.enableDelegations` has been added to spec
see https://w3c.github.io/payment-handler/#dom-paymentmanager-enabledelegations
> mark as standard and add its spec_url

- api/PointerEvent.json
these documentations has been written yet, see https://developer.mozilla.org/en-US/docs/Web/API/PointerEvent
also see https://github.com/mdn/content/pull/30589
> add mdn_url for some members in `PointerEvent`

- webextensions/api/contextualIdentities.json
BCD for [Bug 1333395](https://bugzilla.mozilla.org/show_bug.cgi?id=1333395) Consider support for containers sort order.
> Adding data for contextualIdentities.move

- css/at-rules/font-feature-values.json
The @ is not correct in the path.
> Fix mdn-urls inside font-feature-values

- api/WorkletGlobalScope.json
its documentation has been written
> add mdn_url for `WorkletGlobalScope`

- api/ServiceWorkerGlobalScope.json
the page has been added via https://github.com/mdn/content/pull/30933
> add mdn_url for `ServiceWorkerGlobalScope.cookiechange_event`

- RELEASE_NOTES.md
- package-lock.json
- package.json
> Release v5.5.3

- api/_globals/trustedTypes.json
the docs has been added via https://github.com/mdn/content/pull/31386
> add mdn_url for `trustedTypes`

- api/Ink.json
- api/InkPresenter.json
> add mdn_url for lnk apis

- api/LaunchParams.json
- api/LaunchQueue.json
> Add mdn_url for Launch Handler APIs

- api/HTMLInputElement.json
> Add mdn_url for HTMLInputElement.disabled

- api/MathMLElement.json
also reference to `SVGElement` and `HTMLElement`
> add spec-url for `MathMLElement`

- api/HTMLLinkElement.json
This page is being added in mdn/content#31462
> Add missing mdn_url for HTMLLinkElement.href

- html/elements/area.json
the property is already a global attribute, and should not keep under a element
> remove html.elements.accesskey

- RELEASE_NOTES.md
- package-lock.json
- package.json
> Release v5.5.4

- api/Highlight.json
- api/HighlightRegistry.json
those pages' documentation has been written yet
> add mdn_urls for `Highlight` and `HighlightRegistry`

- api/HTMLElement.json
the docs has been added via https://github.com/mdn/content/pull/31338
> add mdn_url for `HTMLElement.autofocus`

- api/HTMLElement.json
the docs has been added via https://github.com/mdn/content/pull/31367
> add mdn_url for `HTMLElement.virtualKeyboardPolicy`

- README.md
This PR is primarily intended to add the link to https://a11ysupport.io/, but I feel that having this section would help serve sort of as a FAQ to users.
> Add a section stating what BCD doesn't track

- api/HTMLScriptElement.json
the documentation has been added via https://github.com/mdn/content/pull/31529
> add mdn_url for `HTMLScriptElement.crossOrigin`

- api/HTMLElement.json
the documentation has been added via https://github.com/mdn/content/pull/31442
> add mdn_url for `HTMLElement.translate`

- RELEASE_NOTES.md
- package-lock.json
- package.json
> Release v5.5.5

- css/at-rules/container.json
Adapted missing `impl_url` URLs out of https://github.com/Fyrd/caniuse/blob/main/features-json/css-container-queries-style.json
> docs: added `impl_url` URLs

- api/PaintRenderingContext2D.json
- api/PaintSize.json
spec https://drafts.css-houdini.org/css-paint-api/ and https://html.spec.whatwg.org/multipage/canvas.html
> add spec_urls for `PaintSize` and `PaintRenderingContext2D`

- html/elements/head.json
This PR updates and corrects version values for all browsers for the `profile` member of the `head` HTML element. This mirrors the data from the API counterpart.
> Update all browsers data for html.elements.head.profile

- api/Element.json
- api/ElementInternals.json
This PR adds the missing features of the `Element` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.7.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/Element
> Add missing features for Element API

- api/SyncManager.json
the spec define that `SyncManager` is available in both window and worker
spec link https://wicg.github.io/background-sync/spec/
> mark `SyncManager` worker support as standard

- RELEASE_NOTES.md
- package-lock.json
- package.json
> Release v5.5.7

- api/HTMLCanvasElement.json
see [firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=745025) and [firefox feature blog](https://blog.mozilla.org/labs/2012/09/a-new-way-to-control-printing-output/)
> Add data for api.HTMLCanvasElement.mozPrintCallback

- css/properties/animation.json
- css/properties/clip-path.json
- css/properties/display.json
- css/properties/filter.json
- css/properties/letter-spacing.json
- css/properties/mix-blend-mode.json
- css/properties/offset-path.json
- css/properties/text-decoration.json
- css/properties/transform-origin.json
- css/properties/transition.json
- css/properties/white-space.json
- css/properties/width.json
- css/properties/word-spacing.json
- javascript/builtins/Array.json
This PR renames a number of features and updates their descriptions to better represent what they mean, and that they aren't property values.
> Rename numerous features

- api/HTMLAnchorElement.json
- api/HTMLAreaElement.json
https://github.com/mdn/content/pull/31904
https://github.com/mdn/content/pull/31905
> add mdn urls for ping property

- api/HTMLIFrameElement.json
the documentation has been added via https://github.com/mdn/content/pull/31861
> Add mdn_url for `HTMLIFrameElement.allowFullscreen`

- api/CookieChangeEvent.json
- api/CookieStore.json
- api/CookieStoreManager.json
the api has implements by chrome, and has been released for more than three years
see the data guideline https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines/index.md#setting-experimental
> mark Cookie Store API as not experimental

- api/HTMLIFrameElement.json
these pages has been added yet
> Add `mdn_url`s for `HTMLIFrameElement`

- api/HTMLMetaElement.json
these documentation of members in `HTMLMetaElement` has been added yet
> Add mdn_urls for `HTMLMetaElement`

- api/WorkerNavigator.json
This PR updates and corrects version values for Opera and Opera Android for the `userAgentData` member of the `WorkerNavigator` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.7.1).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/WorkerNavigator/userAgentData
> Update Opera data for api.WorkerNavigator.userAgentData

- webextensions/manifest/optional_permissions.json
Various updates for feedback on [Chrome optional permissions update #22034 ](https://github.com/mdn/browser-compat-data/pull/22034#pullrequestreview-1848457914)
> Updating optional_permissions based on feedback to #22034

- html/elements/a.json
- html/elements/area.json
- html/elements/link.json
the link https://developer.mozilla.org/docs/Web/HTML/Link_types does not existed now and will redirect to https://developer.mozilla.org/docs/Web/HTML/Attributes/rel
> Fix redirect links

- api/HTMLInputElement.json
- api/HTMLTextAreaElement.json
Related PR's
https://github.com/mdn/content/pull/32021
https://github.com/mdn/content/pull/32023
> add mdn urls for `type` property

- .github/ISSUE_TEMPLATE/config.yml
Caught a typo in my editor spellchecker, sending in the fix
> fic(typo): Issue template typo

- html/elements/link.json
the data of html.elements.link.as is taken from api.HTMLLinkElement.as, since the two share the same test, so assume the data is correct and reuse
> Add data for html.elements.link.as

- html/elements/link.json
- html/elements/style.json
compared and confirmed that there is no conflict existed between the data under global attributes and the two elements
part of the #21810
> Remove data of `title` attribute that duplicate with `title` global attributes

- html/elements/head.json
> Add spec_url for `<head>` elements

- html/elements/meta.json
the `scheme` is not a valid value of the `name` attribute of the `<meta>` element
in fact, `scheme` should be the `scheme` attribute of the `<meta>` element
> Move `scheme` attribute to correct position in `<meta>` element

- api/HTMLInputElement.json
- html/elements/input.json
See https://github.com/web-platform-dx/web-features/pull/551
> Rename media-capture group to html-media-capture

- api/External.json
> Add missing spec_url for `External` interface

- html/elements/q.json
the data is mainly taken from html.elements.q, also reference to html.elements.blockquote, html.elements.blockquote.cite, api.HTMLQuoteElement and api.HTMLQuoteElement.cite
> Add data of html.elements.q.cite

- html/elements/script.json
the `text` is a property of the `HTMLScriptElement` interface, it gets and sets the text content of the <script> element, it is not an available HTML attribute of `<script>` element
> Remove data of html.elements.script.text

- api/PasswordCredential.json
the `PasswordCredential()` constructor has two formats, currently only one format is linked to
> Update spec_url for `PasswordCredential()` constructor

- webextensions/manifest/dictionaries.json
Add compatibility data for the `dictionaries` manifest key.
Fixes #13866
> Add dictionaries manifest key

- RELEASE_NOTES.md
- package-lock.json
- package.json
> Release v5.5.10

- api/HTMLInputElement.json
add pages form PR https://github.com/mdn/content/pull/32202
> add mdn urls for properties

- GOVERNANCE.md
Reinstate me as a peer, following the discussion and non-objection in recent BCD calls.
@Rumyra already gave me the associated privileges on the repo.
> Reinstate ddbeck to governance as a peer

- api/HTMLSourceElement.json
documentations has been added in https://github.com/mdn/content/pull/32106
> Add mdn_url for `HTMLSourceElement.{height,width}`

- browsers/chrome.json
- browsers/chrome_android.json
Update old chrome release notes
> Fix old chrome release notes

- html/elements/ul.json
> Add spec_url for `<ul>`

- api/Document.json
- api/Element.json
- api/HTMLIFrameElement.json
- api/ShadowRoot.json
- css/selectors/fullscreen.json
- html/elements/iframe.json
Update Fullscreen API data for Safari with version 17.4.
https://developer.apple.com/documentation/safari-release-notes/safari-17_4-release-notes#Web-API
> Update Safari Fullscreen API data

- .husky/pre-commit
- package.json
- porting the change from content repo https://github.com/mdn/content/pull/31964
> fix(ci): migrate to husky v9

- RELEASE_NOTES.md
- package-lock.json
- package.json
> Release v5.5.12

- RELEASE_NOTES.md
- package-lock.json
- package.json
> Release v5.5.13

- api/Window.json
- css/properties/-moz-user-focus.json
Proof:
- https://html.spec.whatwg.org/multipage/interaction.html#dom-window-blur
- https://developer.mozilla.org/en-US/docs/Web/API/Window/setResizable
- https://developer.mozilla.org/en-US/docs/Web/CSS/-moz-user-focus
> Update features marked deprecated in mdn/content

- css/properties/will-change.json
This PR adds the missing features of the `will-change` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/will-change
> Add missing features for will-change CSS property

- css/selectors/backdrop.json
_(👋 Hi, Chrome DevRel here)_
In #22217 I screwed up the link to the WebKit bug. This PR fixes it.
> Fix WebKit link

- css/properties/hanging-punctuation.json
- resolves https://github.com/mdn/content/pull/32594#discussion_r1515532229
> Fix a bug in `hanging-punctuation` property status

- RELEASE_NOTES.md
- package-lock.json
- package.json
> Release v5.5.15

- RELEASE_NOTES.md
- package-lock.json
- package.json
> Release v5.5.17

- css/properties/text-wrap-style.json
This PR updates and corrects the metadata (spec URLs, descriptions, statuses, etc.) for the `text-wrap-style` CSS property.
> Update metadata for text-wrap-style CSS property

- api/CSS.json
- css/types/length.json
This is to fix https://github.com/web-platform-dx/web-features/issues/730.
> Tag cap/ic/lh units for web-features

- api/Permissions.json
- http/headers/Permissions-Policy.json
- Ran `npm test`
- https://chromestatus.com/feature/6439287120723968
**Depends on:** https://github.com/mdn/content/pull/32552
> Add `bluetooth` Permission Policy directive compat data

- RELEASE_NOTES.md
- package-lock.json
- package.json
> Release v5.5.18

- .github/labeler.yml
> Update auto-labeler configuration

- api/Element.json
Element: focusout event: Browser compatibility example is wrong
Fixes #22636
> Update example in description for focusout event

- RELEASE_NOTES.md
- package-lock.json
- package.json
> Release v5.5.19

- webextensions/api/windows.json
Add details for webextensions.api.windows.onBoundsChanged
Fixes  #15039
MDN update in https://github.com/mdn/content/pull/32114
> Chrome feature webextensions.api.windows.onBoundsChanged

- webextensions/api/devtools.json
Adds data for setPage & setHeight in devtools.panels.ExtensionSidebarPane
Fixes #17643
PR for the addition of setHeight to MDN: TBA
> Data for setPage & setHeight in devtools.panels.ExtensionSidebarPane

- api/AudioTrack.json
Reverts mdn/browser-compat-data#21192
> Revert "Update Safari data for AudioTrack API"

- browsers/deno.json
- javascript/builtins/Iterator.json
- javascript/builtins/Set.json
Update `Set` and `Iterator` compat tables for Deno v1.42.0
https://deno.com/blog/v1.42
n/a
> Deno 1.42.0

- api/Element.json
- css/at-rules/font-face.json
- css/selectors/read-only.json
- css/selectors/read-write.json
https://github.com/web-platform-dx/web-features/pull/697
https://github.com/web-platform-dx/web-features/pull/698
https://github.com/web-platform-dx/web-features/pull/777
> Update tags for renamed web-features

- RELEASE_NOTES.md
- package-lock.json
- package.json
> Release v5.5.20

- RELEASE_NOTES.md
- package-lock.json
- package.json
> Release v5.5.21

- html/elements/base.json
> Add spec_url for `<base>` element

- api/PerformanceNavigation.json
- api/PerformanceTiming.json
> Add missing spec_url for `PerformanceNavigation` & `PerformanceTiming`

- css/properties/content-visibility.json
This is to match the display property:
https://github.com/mdn/browser-compat-data/blob/d1d6eb30ec8c2ae2dfa19de2d7f6053c4c016857/css/properties/display.json#L498-L501
> Rename subfeature to content-visibility animation

- api/PushManager.json
- api/PushSubscription.json
see also https://w3c.github.io/push-api/
> Mark some members (has been removed from standard) as non-standard

- javascript/builtins/ArrayBuffer.json
https://github.com/fwqaaq/demo/actions/runs/8673874015/job/23785599518
```bash
deno 1.33.0 (release, x86_64-unknown-linux-gnu)
v8 11.4.183.1
typescript 5.0.3
------------------ArrayBuffer------------------
---{
"constructor": {
"writable": true,
"enumerable": false,
"configurable": true
},
"byteLength": {
"enumerable": false,
"configurable": true
},
"slice": {
"writable": true,
"enumerable": false,
"configurable": true
},
"maxByteLength": {
"enumerable": false,
"configurable": true
},
"resizable": {
"enumerable": false,
"configurable": true
},
"resize": {
"writable": true,
"enumerable": false,
"configurable": true
},
"transfer": {
"writable": true,
"enumerable": false,
"configurable": true
},
"transferToFixedLength": {
"writable": true,
"enumerable": false,
"configurable": true
}, …
```
> Update ArrayBuffer.json for Deno

- RELEASE_NOTES.md
- package-lock.json
- package.json
> Release v5.5.22

- browsers/opera.json
Updates opera release data
https://blogs.opera.com/desktop/2024/03/opera-108/
https://blogs.opera.com/desktop/2024/03/opera-109/
https://blogs.opera.com/desktop/2024/04/opera-110-beta/
> Add latest opera releases

- browsers/opera_android.json
Adds Android Opera 81
https://forums.opera.com/topic/70511/opera-for-android-81?_=1713362110377&lang=en-GB
> Add latest opera android releases

- api/Element.json
- api/ShadowRoot.json
Add data for new getHTML method
https://groups.google.com/a/chromium.org/g/blink-dev/c/T4jcCXRkwB8/m/zRxgrvQlAAAJ
https://chromestatus.com/feature/5102952270528512?gate=5177496192679936
See https://github.com/mdn/content/issues/32731
> Add data for getHTML method

- api/Element.json
Update spec_url for outerHTML property to point to HTML spec instead of DOMParsing spec.
I've recently upstreamed the specification for this property.
> Update spec url for outerHTML property

- api/HTMLFrameElement.json
> Add spec_url for `HTMLFrameElement`

- api/HTMLScriptElement.json
mdn documentation has been added in https://github.com/mdn/content/pull/33150
> Add mdn_url for `HTMLScriptElement.type`

- api/Element.json
- api/ShadowRoot.json
Update spec_url for innerHTML properties to point to HTML spec instead of DOMParsing spec.
I've recently upstreamed the specification for this property.
> Update spec_url for innerHTML properties

- api/HTMLScriptElement.json
docs has been added via https://github.com/mdn/content/pull/33201
> Add mdn_url for `HTMLScriptElement.noModule`

- api/HTMLLinkElement.json
docs has been added via https://github.com/mdn/content/pull/33210
> Add mdn_url for `HTMLLinkElement.type`

- api/HTMLScriptElement.json
docs has been added via https://github.com/mdn/content/pull/33209
> Add mdn_url for `HTMLScriptElement.fetchPriority`

- api/HTMLIFrameElement.json
docs has been added via https://github.com/mdn/content/pull/31980
> Add mdn_url for `HTMLIFrameElement.sandbox`

- css/properties/perspective-origin.json
These ranged versions were added in https://github.com/mdn/browser-compat-data/pull/22440.
> Update perspective-origin subfeatures to match initial support

- api/HTMLScriptElement.json
docs has been added in https://github.com/mdn/content/pull/33255
> Add mdn_url for `HTMLScriptElement.src`

- api/HTMLTemplateElement.json
- api/ShadowRoot.json
- api/ViewTransition.json
- api/ViewTransitionTypeSet.json
- css/properties/view-transition-class.json
- css/types/mod.json
- css/types/rem.json
- css/types/round.json
The [Open Web Docs BCD collector](https://github.com/openwebdocs/mdn-bcd-collector) v10.10.5 found new features shipping in Chrome 125 beta which was released last week. Currently, the collector covers about 90% of BCD, so the following list might not be exhaustive. Also, if a feature is in Chrome Canary/behind origin trials/enrollment, it is not considered here.
Not everything is included in this PR this time around. We have a few things submitted separately:
- https://github.com/mdn/browser-compat-data/pull/22813
- https://github.com/mdn/browser-compat-data/pull/22687
- https://github.com/mdn/browser-compat-data/pull/22866
Taking into account all PRs, BCD considers the following 194 features as shipping in Chrome 125:
- api.CSSPositionTryDescriptors
- …
> Updates for Chrome 125 beta

- css/types/length.json
Matches https://github.com/web-platform-dx/web-features/pull/959.
> Match viewport units rename in web-features

- api/CSSStyleSheet.json
This will make it easier to deal with in web-features.
> Split CSSStyleSheet baseURL parameter into a subfeature

- api/HTMLScriptElement.json
docs is adding via https://github.com/mdn/content/pull/33286
> Add mdn_url for `HTMLScriptElement.async` and `HTMLScriptElement.defer`

- api/Element.json
- api/ElementInternals.json
STP 191 added support for `ariaBrailleLabel` and `ariaBrailleRoleDescription`.
[Release Notes](https://webkit.org/blog/15243/release-notes-for-safari-technology-preview-191/)
[Commit](https://github.com/WebKit/WebKit/commit/263042a5d0c6b67380c99c44f2da65f35fdfb886)
> Update ElementInternals.json - STP 191 added support for `ariaBrailleLabel` and `ariaBrailleRoleDescription`

- RELEASE_NOTES.md
- package-lock.json
- package.json
> Release v5.5.24

- api/Document.json
- package-lock.json
hasUnpartitionedCookieAccess is a renaming of hasStorageAccess intended to provide more clarity around what storage is actually accessible. This is important as Chrome now supports requesting unpartitioned storage access with or without unpartitioned cookies.
This only launched in Chrome: https://chromestatus.com/feature/5175585823522816
Relates to https://github.com/mdn/content/pull/33329 and https://github.com/mdn/mdn/issues/543
> Add hasUnpartitionedCookieAccess

- RELEASE_NOTES.md
- package-lock.json
- package.json
> Release v5.5.25

- api/Window.json
found when working on https://github.com/mdn/content/pull/33414
> Add missing spec_url for `Window.sharedStorage`

- api/HTMLLinkElement.json
- api/HTMLScriptElement.json
docs is adding via https://github.com/mdn/content/pull/33355
> Add mdn_url for `HTMLLinkElement.integrity` and `HTMLScriptElement.integrity`

- api/Document.json
- api/FragmentDirective.json
- css/selectors/target-text.json
See https://github.com/web-platform-dx/web-features/pull/1007.
> Revisit tags for text fragments in web-features

- api/HTMLLinkElement.json
- api/HTMLScriptElement.json
- api/HTMLStyleElement.json
docs is adding via https://github.com/mdn/content/pull/33468/
> Add mdn docs link for `{HTMLLinkElement,HTMLScriptElement,HTMLStyleElement}.blocking`

- css/selectors/-moz-first-node.json
- css/selectors/-moz-focus-inner.json
- css/selectors/-moz-last-node.json
- css/selectors/-moz-list-bullet.json
- css/selectors/-moz-list-number.json
- css/selectors/-moz-progress-bar.json
see at https://github.com/mdn/content/tree/main/files/en-us/web/css
fix description and add mdn_url for some Mozilla pseudo-class and pseudo-element
relates to https://github.com/mdn/content/pull/33476
> Fix description and add mdn_url for some Mozilla pseudo-class and pseudo-element

- browsers/opera_android.json
Add Opera Android 82
https://forums.opera.com/topic/71513/opera-for-android-82
> Add latest opera android release

- browsers/opera.json
Add opera 111 nightly
https://blogs.opera.com/desktop/changelog-for-111/
> Add opera 111 nightly

- RELEASE_NOTES.md
- package-lock.json
- package.json
> Release v5.5.27

- api/HTMLIFrameElement.json
docs has been added via https://github.com/mdn/content/pull/31979
> Add mdn_url for `HTMLIFrameElement.allow`

- api/ElementInternals.json
This is a new part of the API, or perhaps part of form-assoicated custom
elements.
Matches the change in https://github.com/web-platform-dx/web-features/pull/1062.
> Remove constraint validation tags from ElementInternals

- css/types/calc-constant.json
- css/types/color.json
- css/types/dimension.json
- css/types/filter-function.json
- css/types/line-style.json
- css/types/number.json
- css/types/ratio.json
- css/types/resolution.json
- css/types/string.json
- css/types/time-percentage.json
- css/types/time.json
> Add & update description key for CSS types and functions

- api/RTCRtpTransceiver.json
This PR adds the spec URLs for the features added in #22872.
> Add spec URLs for RTP header extension controls

- css/selectors/closed.json
- css/selectors/open.json
> Fix description for webkit specific selectors

- RELEASE_NOTES.md
- package-lock.json
- package.json
> Release v5.5.28

- api/CustomElementRegistry.json
- api/Window.json
- css/selectors/defined.json
- css/selectors/host-context.json
- css/selectors/host.json
- css/selectors/part.json
This should match https://github.com/web-platform-dx/web-features/pull/1089.
> Update web-features tags for custom elements

- api/HTMLLinkElement.json
docs is adding via https://github.com/mdn/content/pull/33637
> Add mdn_url for `HTMLLinkElement.disabled`

- RELEASE_NOTES.md
- package-lock.json
- package.json
> Release v5.5.29

- RELEASE_NOTES.md
- package-lock.json
- package.json
> Release v5.5.30

- api/SVGScriptElement.json
- svg/elements/script.json
I've moved to drop this non-feature in https://github.com/web-platform-dx/web-features/pull/1145.
https://github.com/web-platform-dx/web-features/issues/963
> Remove `web-features:svg2-script-html-equivalence` tag

- api/Clipboard.json
See https://github.com/mdn/browser-compat-data/commit/a3d5ec47459a8600ca737d29509cc62fbe415def#r142483010
> Change back to Fx125 for Clipboard.readText

- browsers/chrome.json
- html/elements/script.json
Add an integrity subsection to importmap script type.
> Add importmap integrity subsection

- RELEASE_NOTES.md
- package-lock.json
- package.json
> Release v5.5.31

- browsers/deno.json
This PR updates the release data for Deno.
> Update Deno release data

- javascript/builtins/Uint32Array.json
Matches https://github.com/web-platform-dx/web-features/pull/1056.
> Tag Uint32Array as typed arrays

- api/HTMLSlotElement.json
- api/ShadowRoot.json
Matches https://github.com/web-platform-dx/web-features/pull/880.
> Tag slot assignment feature

- RELEASE_NOTES.md
- package-lock.json
- package.json
> Release v5.5.33

- css/properties/background-image.json
- css/types/image.json
A feature was removed and another was added:
https://github.com/web-platform-dx/web-features/pull/957
https://github.com/web-platform-dx/web-features/pull/1017
> Update tags for gradient features

- css/properties/font-palette.json
- css/properties/font-size-adjust.json
- css/properties/font-synthesis-position.json
- css/properties/font-synthesis-small-caps.json
- css/properties/font-synthesis-style.json
- css/properties/font-synthesis-weight.json
- css/properties/font-synthesis.json
Matches https://github.com/web-platform-dx/web-features/pull/970.
> Update tags for CSS font-*

- RELEASE_NOTES.md
- package-lock.json
- package.json
> Release v5.5.34

- svg/global_attributes.json
This PR updates and corrects version values for all browsers for various SVG global attributes feature. This mirrors the support data from the HTML global attributes.
> Update all browsers data for SVG global attributes

- css/properties/overflow-clip-margin.json
Chromium 104: https://chromestatus.com/feature/5082351989161984
Firefox: no support, https://bugzilla.mozilla.org/show_bug.cgi?id=1661582
Safari: no support, https://bugs.webkit.org/show_bug.cgi?id=236153
> Chrome 104 supports visual-box values on overflow-clip-margin

- api/WorkerGlobalScope.json
Add missing compat data for
- https://developer.mozilla.org/en-US/docs/Web/API/WorkerGlobalScope/rejectionhandled_event
- https://developer.mozilla.org/en-US/docs/Web/API/WorkerGlobalScope/unhandledrejection_event
Data from the same events on Window.
https://chromestatus.com/feature/4805872211460096
> Add WorkerGlobalScope.unhandledrejection/rejectionhandled events

- api/PerformanceNavigation.json
- api/SVGGraphicsElement.json
- webextensions/api/devtools.json
> Update notes for resolved bugs

- RELEASE_NOTES.md
- package-lock.json
- package.json
> Release v5.5.35

- svg/global_attributes.json
Gone for about 10 years according to https://github.com/w3c/svgwg/issues/80#issuecomment-206636850
https://svgwg.org/svg2-draft/single-page.html#text-KerningProperty
> Remove SVG kerning attribute

- api/Navigator.json
> Fix misspelling of "ethereum"

- svg/global_attributes.json
I thinking that this is probably supported since SVG SMIL support. https://caniuse.com/svg-smil
> Update support for SVG class animatable

- html/elements/link.json
See https://bugs.webkit.org/show_bug.cgi?id=20690 and https://github.com/WebKit/WebKit/commit/da4e94d595f5b3c1bd48c774e194c6ecff05e333
> Update Safari data for rel=dns-prefetch

- RELEASE_NOTES.md
- package-lock.json
- package.json
> Release v5.5.36

- css/properties/contain.json
Matches https://github.com/web-platform-dx/web-features/pull/1290.
> Remove container-queries tag from contain property

- lint/linter/test-schema.ts
- lint/linter/test-spec-urls.ts
- package.json
- scripts/bulk-editor/tags/index.ts
- scripts/bulk-editor/utils.ts
- scripts/update-browser-releases/safari.ts
This PR fixes all of the warnings thrown by ESLint and TypeScript.
> Fix linter and TypeScript warnings

- browsers/opera.json
- browsers/opera_android.json
This PR updates the data for the Opera browser, based upon release notes from the Opera blog.
> Update Opera browser data

- RELEASE_NOTES.md
- package-lock.json
- package.json
> Release v5.5.38

- http/headers/Authorization.json
- http/headers/WWW-Authenticate.json
Source: https://en.wikipedia.org/wiki/Digest_access_authentication#Browser_implementation
> Update Digest authentication

- mathml/elements/math.json
- mathml/elements/mfrac.json
- mathml/elements/mo.json
- mathml/elements/mover.json
- mathml/elements/mpadded.json
- mathml/elements/mspace.json
- mathml/elements/mtd.json
- mathml/elements/munder.json
- mathml/elements/munderover.json
Some spec_urls for standardized MathML features.
> Add spec_urls for MathML

- webdriver/commands/CreateVirtualSensor.json
- webdriver/commands/DeleteVirtualSensor.json
- webdriver/commands/GetVirtualSensorInformation.json
- webdriver/commands/UpdateVirtualSensorReading.json
Spec: https://w3c.github.io/sensors/#automation
Chrome: https://chromestatus.com/feature/5173284500406272
> Add virtual sensor WebDriver commands

- RELEASE_NOTES.md
- package-lock.json
- package.json
> Release v5.5.41

- RELEASE_NOTES.md
- package-lock.json
- package.json
Note: the previous attempt to release this version, along with the following version, was not completed.
> Release v5.5.40

- .husky/post-merge
- package-lock.json
- package.json
This PR bumps all of the dependencies by running `npm update`.
Note: the Husky script was updated in this PR as well, as it was updated when running `npm install`.
> Update all dependencies

- RELEASE_NOTES.md
- package-lock.json
- package.json
> Release v5.5.42

- javascript/builtins/Intl/Segments.json
- javascript/builtins/Object.json
- javascript/builtins/Set.json
- webassembly/api/Tag.json
- webassembly/mutable-globals.json
Outcome of the validation in https://github.com/mdn/browser-compat-data/pull/23958
> Correct some JavaScript and WebAssembly spec_urls

- api/BeforeUnloadEvent.json
- api/BluetoothDevice.json
- api/CSSPageDescriptors.json
- api/CSSPageRule.json
- api/CSSStyleDeclaration.json
- api/CSSStyleRule.json
- api/ContactAddress.json
- api/CredentialsContainer.json
- api/DedicatedWorkerGlobalScope.json
- api/Element.json
- api/FontFace.json
- api/FontFaceSet.json
- api/GPUAdapter.json
- api/GPUCommandEncoder.json
- api/GamepadHapticActuator.json
- api/HTMLMediaElement.json
- api/HTMLMetaElement.json
- api/HTMLParamElement.json
Found via validation in https://github.com/mdn/browser-compat-data/pull/23958
> Fix broken spec_urls for APIs (A-M); set some features to non-standard

- api/MediaKeyMessageEvent.json
- api/MimeType.json
- api/MimeTypeArray.json
- api/Navigator.json
- api/PaymentInstruments.json
- api/Plugin.json
- api/PluginArray.json
- api/RTCEncodedAudioFrame.json
- api/RTCEncodedVideoFrame.json
- api/RTCStatsReport.json
- api/Range.json
- api/Sanitizer.json
- api/ToggleEvent.json
- api/VideoEncoder.json
- api/XRCubeLayer.json
- api/XRCylinderLayer.json
- api/XREquirectLayer.json
- api/XRQuadLayer.json
Found via validation in https://github.com/mdn/browser-compat-data/pull/23958
Part 1: https://github.com/mdn/browser-compat-data/pull/23982
> Fix broken spec_urls for APIs (M-X); set some features to non-standard

- html/elements/script.json
- html/manifest/share_target.json
Found via https://github.com/mdn/browser-compat-data/pull/23958
> Fix two spec_urls in html/

- api/CSSPositionTryDescriptors.json
See https://github.com/mdn/content/issues/34893 
(also discovered due to broken spec_url link)
> Rename CSSPositionTryDescriptors.insetArea -> positionArea

- RELEASE_NOTES.md
- package-lock.json
- package.json
> Release v5.5.43

- css/at-rules/media.json
- css/properties/content-visibility.json
- css/properties/font-variant-east-asian.json
- css/properties/font-variant-numeric.json
- css/properties/font-variant-position.json
- css/properties/font-weight.json
- css/properties/grid-template-columns.json
- css/properties/grid-template-rows.json
- css/properties/list-style-position.json
- css/properties/overflow-x.json
- css/properties/text-wrap.json
- css/types/color.json
Fix more CSS spec_url issues found thanks to https://github.com/mdn/browser-compat-data/pull/23958
> Fix various CSS spec_urls

- RELEASE_NOTES.md
- package-lock.json
- package.json
> Release v5.5.44

- RELEASE_NOTES.md
- package-lock.json
- package.json
> Release v5.5.45

- RELEASE_NOTES.md
- package-lock.json
- package.json
> Release v5.5.46

- api/MutationEvent.json
Edge removed mutation events since v127.
https://learn.microsoft.com/en-us/microsoft-edge/web-platform/site-impacting-changes?tabs=latest
> Update Edge data for mutation events

- html/manifest/description.json
- html/manifest/display.json
- html/manifest/icons.json
- html/manifest/name.json
- html/manifest/note_taking.json
- html/manifest/orientation.json
- html/manifest/prefer_related_applications.json
- html/manifest/related_applications.json
- html/manifest/scope.json
- html/manifest/short_name.json
- html/manifest/start_url.json
- lint/linter/test-versions.ts
Mirror all the Operas, Samsung Internet and WebView manifest.json features.
Require real values for the html/ folder.
> Mirror manifest data and require real values for html/

- css/properties/position-area.json
- css/properties/position-try-fallbacks.json
See https://github.com/mdn/content/issues/34893
Followup to https://github.com/mdn/browser-compat-data/pull/23981
> Rename CSS inset-area property to position-area

- javascript/builtins/Array.json
- javascript/builtins/BigInt.json
- javascript/builtins/TypedArray.json
As outlined in https://github.com/web-platform-dx/web-features/pull/1601, I want to record these keys in an "Intl" web-feature. In order for that to happen I think I need to remove the tags first.
> Untag toLocaleString (move to Intl feature)

- css/selectors/-webkit-meter-bar.json
> deprecate webkit meter bar

- css/properties/animation-timing-function.json
- part of https://github.com/mdn/content/issues/35187
> css.properties.animation-timing-function: add level 2 easing spec

- javascript/statements.json
Import attributes now has an MDN page.
> Add mdn_url and spec_url for import_attributes

- RELEASE_NOTES.md
- package-lock.json
- package.json
> Release v5.5.48

- RELEASE_NOTES.md
- package-lock.json
- package.json
> Release v5.5.49

- RELEASE_NOTES.md
- package-lock.json
- package.json
> Release v5.5.50

- css/selectors/active-view-transition-type.json
> :active-view-transition-type() is in STP 202

- css/properties/ruby-align.json
> ruby-align is in STP 202

- css/properties/view-transition-class.json
https://view-transitions.netlify.app/cards/spa/
> view-transition-class is in STP 202

- css/properties/scrollbar-width.json
> scrollbar-width is in STP 202

- css/at-rules/page.json
> @page jis-b4/jis-b5 sizes now supported in STP 202

- css/selectors/target-text.json
> ::target-text is now supported in STP 202

- api/PointerEvent.json
> New PointerEvent APIs in STP 202

- css/properties/ruby-position.json
> Unprefixed ruby-position is in STP 202

- html/elements/meta.json
- http/headers/Refresh.json
In combination with https://github.com/mdn/content/pull/35709
> Add data for HTTP Refresh header

- api/IDBFactory.json
- http/headers/Refresh.json
This PR fixes a recently introduced linter error.
> Fix linter errors

- RELEASE_NOTES.md
- package-lock.json
- package.json
> Release v5.5.51

- css/at-rules/custom-media.json
* Spec: https://www.w3.org/TR/mediaqueries-5/
* Definition: https://www.w3.org/TR/mediaqueries-5/#custom-mq
* Chrome Bug: https://issues.chromium.org/issues/40781325
* WebKit Bug: https://bugs.webkit.org/show_bug.cgi?id=233820
* FireFox bog: https://bugzilla.mozilla.org/show_bug.cgi?id=1744292
> feat(css): Add browser compatibility data for the CSS `@custom-media` at-rule

- browsers/opera.json
Add missing opera releases, mark 113 as current, add missing release date and notes for 112 and add 114 and 115
https://blogs.opera.com/desktop/2024/07/opera-112/
https://blogs.opera.com/desktop/2024/08/opera-113/
> Update opera releases to latest

- browsers/opera_android.json
Add Opera Android 84
https://forums.opera.com/topic/73545/opera-for-android-84
> Add Opera Android 84

- css/properties/scrollbar-gutter.json
Mark scrollbar-gutter as supported in Safari TP
See https://webkit.org/blog/15860/release-notes-for-safari-technology-preview-203/#:~:text=Added%20support%20for-,scrollbar%2Dgutter,-.%20(282662%40main
> Mark scrollbar-gutter as supported in Safari TP

- css/types/basic-shape.json
> shape() is now in STP 202

- api/ViewTransitionTypeSet.json
> ViewTransitionTypeSet is now in STP 202

- api/Document.json
Forgot this in https://github.com/mdn/browser-compat-data/pull/24405
Fixes CI in main.
> Add missing webview_ios to caretPositionFromPoint options_param

- api/ViewTransition.json
> types in ViewTransition is supported in STP 202

- api/UserActivation.json
> Fix mdn_url of api.UserActivation.hasBeenActive

- RELEASE_NOTES.md
- package-lock.json
- package.json
> Release v5.6.0

- RELEASE_NOTES.md
- package-lock.json
- package.json
> Release v5.6.1

- RELEASE_NOTES.md
- package-lock.json
- package.json
> Release v5.6.2

- css/properties/ruby-overhang.json
In STP 203: https://webkit.org/blog/15860/release-notes-for-safari-technology-preview-203/
Spec: https://drafts.csswg.org/css-ruby/#ruby-overhang
> Add ruby-overhang

- webextensions/manifest/theme.json
PR #22216 is blocked by the linter because the PR is adding and removing features more than 2 years old. To unblock, this PR add the afeatures
> Addition portion of PR #22216

- html/elements/meta.json
This PR updates and corrects the metadata (spec URLs, descriptions, statuses, etc.) for the `http-equiv.content-type` member of the `meta` HTML element.
> Update metadata for html.elements.meta.http-equiv.content-type

- RELEASE_NOTES.md
- package-lock.json
- package.json
> Release v5.6.3

- RELEASE_NOTES.md
- package-lock.json
- package.json
> Release v5.6.4

- api/BarcodeDetector.json
Fixes https://github.com/mdn/browser-compat-data/issues/24602
> Add impl_url for `BarcodeDetector`

- api/InstallEvent.json
it has been adding back to specification via https://github.com/w3c/ServiceWorker/pull/1729
see https://w3c.github.io/ServiceWorker/#dom-installevent-installevent
> Add spec_url for `InstallEvent` constructor

- svg/global_attributes.json
this is a data-* property, using `data` might be a little conflict
so using the same format as html.global_attributes.data_attributes
> Rename svg.global_attributes.{data => data_attributes}

- css/selectors/after.json
- css/selectors/before.json
Make the `css.selectors.{before,after}.animation_and_transition_support` data make sense.
https://github.com/mdn/browser-compat-data/issues/18109 but primarily the linked CSS-Tricks article: https://css-tricks.com/transitions-and-animations-on-css-generated-content/
Fixes https://github.com/mdn/browser-compat-data/issues/18109
Discovered via https://github.com/web-platform-dx/web-features/pull/1869
> `css.selectors.{before,after}`: make animation data consistent

- css/at-rules/view-transition.json
https://webkit.org/blog/15978/release-notes-for-safari-technology-preview-204/
> `@view-transition` is supported in STP 204

- RELEASE_NOTES.md
- package-lock.json
- package.json
> Release v5.6.5

- http/headers/Cross-Origin-Opener-Policy.json
This adds the Cross-Origin-Opener-Policy: noopener-allow-popups feature
https://chromium-review.googlesource.com/c/chromium/src/+/5872914
https://chromestatus.com/feature/5163293877731328
> Add COOP noopener-allow-popups

- api/GravitySensor.json
- api/HTMLCanvasElement.json
Sync web-feature names that changes in [web-features v2.0.0](https://github.com/web-platform-dx/web-features/releases/tag/v2.0.0).
> chore(web-features): sync names with v2

- api/EyeDropper.json
see https://crbug.com/1249967, note it only mentions webview
and it seems no existing issues for chrome android
see also https://github.com/mdn/browser-compat-data/issues/24690
> Add impl_url for EyeDropper API in webview

- scripts/build/index.ts
Makes the `build` script a bit more verbose, listing the files that are being written.
Before:
```
Data bundle is ready
```
After:
```
Wrote: build/LICENSE
Wrote: build/legacynode.mjs (wrapper for old NodeJS versions)
Wrote: build/package.json (manifest)
Wrote: build/require.d.ts (CommonJS types)
Wrote: build/README.md
Wrote: build/import.d.mts (ESM types)
Wrote: build/data.json (data)
Wrote: build/types.d.ts (data types)
Data bundle is ready
```
> enhance(build): print output paths

- api/CookieChangeEvent.json
- api/CookieStore.json
- api/ServiceWorkerGlobalScope.json
- api/Window.json
A subset of the [Cookie Store API](https://developer.mozilla.org/en-US/docs/Web/API/Cookie_Store_API) is enabled in Firefox Nightly only, as of Firefox 132. This includes:
- The [`CookieStore`](https://developer.mozilla.org/en-US/docs/Web/API/CookieStore) interface, but not `partitioned` in return values.
- The [`CookieChangeEvent`](https://developer.mozilla.org/en-US/docs/Web/API/CookieChangeEvent) interface, excluding `partitioned` properties.
- [`Window.cookieStore`](https://developer.mozilla.org/en-US/docs/Web/API/Window/cookieStore)
- [`ServiceWorkerGlobalScope.cookieStore`](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerGlobalScope/cookieStore)
It doesn't include:
- The [`CookieStoreManager`](https://developer.mozilla.org/en-US/docs/Web/API/CookieStoreManager) …
> Firefox Nightly supports Cookie Store API

- RELEASE_NOTES.md
- package-lock.json
- package.json
> Release v5.6.7

- GOVERNANCE.md
As discussed a few BCD calls ago.
> Update Peer list

- api/Navigator.json
- api/Presentation.json
- api/PresentationAvailability.json
- api/PresentationConnection.json
- api/PresentationConnectionAvailableEvent.json
- api/PresentationConnectionCloseEvent.json
- api/PresentationConnectionList.json
- api/PresentationReceiver.json
- api/PresentationRequest.json
> Add Safari impl_url for Presentation API

- api/Navigator.json
- api/Presentation.json
- api/PresentationAvailability.json
- api/PresentationConnection.json
- api/PresentationConnectionAvailableEvent.json
- api/PresentationConnectionCloseEvent.json
- api/PresentationConnectionList.json
- api/PresentationReceiver.json
- api/PresentationRequest.json
same as title
https://crbug.com/521319
https://w3c.github.io/presentation-api/
> Add WebView `impl_url`s for Presentation API

- api/MediaMetadata.json
- api/MediaSession.json
- api/Navigator.json
same as title
https://crbug.com/925997
> Add WebView impl_url for Media Session API

- api/Navigator.json
> Add Webview impl_url for Share API

- api/NavigateEvent.json
- api/Navigation.json
- api/NavigationActivation.json
- api/NavigationCurrentEntryChangeEvent.json
- api/NavigationDestination.json
- api/NavigationHistoryEntry.json
- api/NavigationTransition.json
same as title
see also https://github.com/whatwg/html/pull/8502 and https://github.com/whatwg/html/pull/9856
> Add Safari impl_url for Navigation API

- api/Navigator.json
> Add Chrome Android impl_url for `registerProtocolHandler`

- api/DataTransferItem.json
- api/Window.json
> Add Chrome Android impl_url for File System Access API

- RELEASE_NOTES.md
- package-lock.json
- package.json
> Release v5.6.8

- api/MediaDevices.json
> Add Chrome impl_url for `MediaDevices.selectAudioOutput()`

- .github/workflows/update-mdn-urls.yml
Fixes the new `update-mdn-url` workflow, which wasn't setup properly, and prevented checks from running after pushing to the inventory PR.
Extracted from https://github.com/mdn/browser-compat-data/pull/24823.
> fix(update-mdn-url): checkout with mdn-bot token

- http/headers/Clear-Site-Data.json
Fixes https://github.com/mdn/browser-compat-data/issues/18525
Chromestatus: https://chromestatus.com/feature/5074132743487488
> Chrome 117 supports Clear-Site-Data wildcard

- api/ServiceWorkerContainer.json
- mathml/elements/maction.json
> Remove two obsolete features

- api/URLPattern.json
> Add Firefox impl_url for `URLPattern`

- api/Navigator.json
- api/Serial.json
- api/SerialPort.json
- api/WorkerNavigator.json
> Add Webview impl_url for Web Serial API

- api/HID.json
- api/HIDConnectionEvent.json
- api/HIDDevice.json
- api/HIDInputReportEvent.json
- api/Navigator.json
- api/WorkerNavigator.json
> Add Chrome Android & Webview impl_url for WebHID API

- api/RTCDataChannel.json
See #24680 for details
Fixes #24680
> Chromium 130 supports transferable `RTCDataChannel`

- api/PaymentManager.json
- api/PaymentRequestUpdateEvent.json
see detail at #24731 
yes, test it when firing the browser issue
also see the test by chromium's people
Fixes #24731
> Chromium 122 stopped exposing {PaymentManager,PaymentRequestUpdateEvent} in insecure context

- .github/workflows/update-mdn-urls.yml
Attempt to fix the failing update-mdn-urls workflow (see https://github.com/mdn/browser-compat-data/pull/24857).
> fix(update-mdn-urls): run on pull_request_target, not push

- .github/workflows/update-mdn-urls.yml
Fixes up the previous PR (https://github.com/mdn/browser-compat-data/pull/24860) to resolve the issue with the `update-mdn-urls` check.
> fixup! fix(update-mdn-urls): run on pull_request_target, not push

- api/Navigator.json
- api/WindowControlsOverlay.json
- api/WindowControlsOverlayGeometryChangeEvent.json
> Add safari impl_url for Window Controls Overlay API

- http/headers/Clear-Site-Data.json
https://bugzil.la/1838506
https://bugzil.la/1635189
> Add Clear-Site-Data impl_urls for Firefox

- api/HTMLMediaElement.json
- api/MediaDevices.json
- html/elements/iframe.json
- http/headers/Permissions-Policy.json
> Add Safari impl_url for Speech Selection API

- api/HTMLElement.json
- api/Navigator.json
- api/VirtualKeyboard.json
- html/global_attributes.json
https://w3c.github.io/virtual-keyboard/
> Add Firefox & Webkit impl_url for VirtualKeyboard API

- api/AudioTrack.json
- api/MediaSource.json
- api/SourceBuffer.json
- api/SourceBufferList.json
- api/TextTrack.json
- api/VideoTrack.json
https://w3c.github.io/media-source/
> Add IPhone Safari impl_url for Media Source Extension API

- api/PeriodicSyncEvent.json
- api/PeriodicSyncManager.json
- api/ServiceWorkerGlobalScope.json
- api/ServiceWorkerRegistration.json
see also https://github.com/mdn/browser-compat-data/issues/24690
> Add Webview impl_url for Periodic Sync API

- api/FontData.json
- api/Permissions.json
- api/Window.json
- html/elements/iframe.json
- http/headers/Permissions-Policy.json
> Add Chrome Android impl_url for Local Font Access API

- api/CommandEvent.json
- addresses https://github.com/mdn/content/pull/36498/files#r1817897962
The interface is experimental, so members need to be experimental as well.
> api.CommandEvent.command and source: mark experimental

- api/File.json
- browsers/nodejs.json
see https://nodejs.org/api/buffer.html#class-file
Fixes #22786
> Add nodejs data for `File`

- .github/workflows/release-pr.yml
- .github/workflows/release.yml
1. Adds new `release-pr` workflow that creates (or updates) the release PR on every push to `main`. (It can also be run manually, if necessary.)
2. Updates the existing `release` workflow to automatically create the release when the release PR is merged.
⚠️ **Do not merge** before https://github.com/mdn/browser-compat-data/pull/24807 was merged (or this workflow will create a new release PR on every push to `main`).
> enhance(release): manage automatic release PR + draft release on merge

- docs/data-guidelines/tags.md
- schemas/compat-data-schema.md
the link has changed to https://github.com/web-platform-dx/web-features/blob/main/features/README.md that landed in https://github.com/web-platform-dx/web-features/pull/1022
> Update link of web-platform-dx/web-features

- .github/workflows/update-mdn-urls.yml
Another attempt to fix the `update-mdn-urls` workflow, which is not working as expected yet.
> fix(update-mdn-urls): refine run criteria

- api/VisibilityStateEntry.json
> Add Firefox & Safari impl_url for `VisibilityStateEntry`

- api/Permissions.json
- http/headers/Permissions-Policy.json
some are missing when adding impl_url in previous PRs
see https://github.com/mdn/browser-compat-data/pull/24732, https://github.com/mdn/browser-compat-data/pull/24765, https://github.com/mdn/browser-compat-data/pull/24767 and https://github.com/mdn/browser-compat-data/pull/24749
> Add Chrome/Webview Android impl_url for Permissions API & Permissions Policy

- api/AbortController.json
- api/AbortSignal.json
- browsers/nodejs.json
see https://nodejs.org/docs/latest/api/globals.html#class-abortcontroller and https://nodejs.org/docs/latest/api/globals.html#class-abortsignal
see also https://github.com/mdn/browser-compat-data/issues/24899
> Update nodejs data for `AbortController` and `AbortSignal`

- api/BroadcastChannel.json
- api/MessageChannel.json
- api/MessagePort.json
- browsers/nodejs.json
https://nodejs.org/docs/latest/api/globals.html#broadcastchannel
https://nodejs.org/docs/latest/api/worker_threads.html#class-broadcastchannel-extends-eventtarget
https://nodejs.org/docs/latest/api/globals.html#messagechannel
https://nodejs.org/docs/latest/api/worker_threads.html#class-messagechannel
https://nodejs.org/docs/latest/api/globals.html#messageport
https://nodejs.org/docs/latest/api/worker_threads.html#class-messageport
> Update nodejs data for `BroadcastChannel`, `MessageChannel`, `MessagePort`

- api/HTMLMediaElement.json
see https://w3c.github.io/media-source/
> Update spec_url for Media Source Extensions API related DOM features

- scripts/release/index.ts
Reduce noise of release PR by creating it as draft.
(Action item from BCD call on 2024-11-05.)
> chore(scripts/release): create PR as draft

- api/ReadableStreamBYOBReader.json
- browsers/nodejs.json
see https://github.com/whatwg/streams/pull/1145
the feature has shipped in [node](https://github.com/nodejs/node/issues/50706), and done in [deno](https://github.com/denoland/deno/pull/20849) though seems to be not released, also, [firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1864406) has implemented it and seems to be shipped in M134
also see https://github.com/mdn/mdn/issues/478
> Add data for the new `options.min` parameter of `ReadableStreamBYOBReader.read()`

- api/CloseEvent.json
- browsers/nodejs.json
see https://nodejs.org/docs/latest/api/globals.html#closeevent
> Add nodejs data for `CloseEvent`

- api/DOMException.json
see https://nodejs.org/docs/latest/api/globals.html#domexception
also, the data first add in https://github.com/mdn/browser-compat-data/pull/16403 and then update in https://github.com/mdn/browser-compat-data/pull/23125
test in local node (v22.11.0):
> Add nodejs data for `DOMException.code`

- .github/workflows/update-mdn-urls.yml
Yet another attempt to fix the `update-mdn-urls` workflow.
> fix(update-mdn-urls): checkout + push to PR branch

- .github/workflows/release.yml
Follow-up of https://github.com/mdn/browser-compat-data/pull/24805.
Resolves three minor issues with the automatic release creation:
1. The tag was missing the "v" prefix (expected: `v5.6.13`, actual: `5.6.13`).
2. The release was missing a title (expected: `"v5.6.13"`, actual: `""`).
3. The release description included the initial paragraph from the release notes with the date.
> enhance(workflow/release): refine release creation

- api/TextDecoder.json
- api/TextEncoder.json
no bcd data change
https://nodejs.org/docs/latest/api/globals.html#textdecoder
https://nodejs.org/docs/latest/api/globals.html#textencoder
https://nodejs.org/docs/latest/api/util.html#class-utiltextdecoder
https://nodejs.org/docs/latest/api/util.html#class-utiltextencoder
> Format nodejs data for Encoding API

- html/global_attributes.json
I think this is a useful information
> add csswg spec for style attr

- api/FormData.json
https://nodejs.org/docs/latest/api/globals.html#class-formdata
> Add nodejs data for `FormData`

- html/global_attributes.json
Reverts mdn/browser-compat-data#24992
> Revert "add csswg spec for style attr"

- .github/workflows/release.yml
When merging the release PR, create a release directly without drafting it first.
(It is now working well, both the tag and the release description are fine.)
> chore(workflows/release): create non-draft release

- README.md
Update the "Projects using the data", mainly to add more notable projects.
(Part of Mozilla-internal [MP-1659](https://mozilla-hub.atlassian.net/browse/MP-1659) ticket.)
> docs(README): update "Projects using the data" section

- api/Navigator.json
- api/StorageBucket.json
- api/StorageBucketManager.json
- api/WorkerNavigator.json
> Add Firefox impl_url for Storage Bucket API

- .github/workflows/release.yml
Make sure that the created GitHub release is marked as latest.
> fix(workflows/release): create latest release

- .github/workflows/release.yml
Creates the GitHub release as @mdn-bot, instead of as github-actions bot. Hopefully this ensures that the release triggers the release published event.
> fix(workflows/release): release as mdn-bot

- api/Permissions.json
- api/ServiceWorkerGlobalScope.json
- api/ServiceWorkerRegistration.json
- api/SyncEvent.json
- api/SyncManager.json
> Add Safari impl_url for Background Sync API

- api/CanMakePaymentEvent.json
- api/PaymentManager.json
- api/PaymentRequestEvent.json
- api/Permissions.json
- api/ServiceWorkerGlobalScope.json
- api/ServiceWorkerRegistration.json
> Add Firefox impl_url for Payment Handler API

- api/FederatedCredential.json
- api/PasswordCredential.json
> Add Firefox & Safari impl_url for rest Credential Management API feaures

- .github/issue-regex-labeler.yml
- .github/workflows/issue-regex-labeler.yml
Automatically labels issues according to keywords in the description.
Based on mdn/content:
- Workflow: https://github.com/mdn/content/blob/main/.github/workflows/issue-regex-labeler.yml
- Rules: https://github.com/mdn/content/blob/main/.github/issue-regex-labeler.yml
> enhance(triage): add issue-regex-labeler workflow

- css/properties/text-rendering.json
the two values are in [spec](https://svgwg.org/svg2-draft/painting.html#TextRenderingProperty)
note as the two valued seems not to have direct link to it, so no *spec_url* added
> Mark `text-rendering` values `auto` + `geometricPrecision` as standard

- css/selectors/user-invalid.json
- css/selectors/user-valid.json
the impl_url refer's feature has implemented and shipped in stable version of chrome, and the impl_url itself has marked as fixed now
> Remove outdated impl_url of `:user-valid` and `:user-invalid`

- api/Navigator.json
- api/WorkerNavigator.json
- http/headers/Sec-GPC.json
Thanks to https://github.com/w3c/browser-specs/pull/1581
> Add spec for Global Privacy Control (GPC)

- package-lock.json
Fixes "1 high severity vulnerability" that `npm install` warns about.
> chore: run `npm audit fix`

- lint/linter/test-spec-urls.ts
- webassembly/exceptionsFinal.json
- webassembly/typedFunctionReferences.json
Discovered by the OWD collector v10.12.6 (which gets WASM data via https://github.com/GoogleChromeLabs/wasm-feature-detect)
> Add two new wasm features: exceptionsFinal, typedFunctionReferences

- api/IDBFactory.json
Attempt to unblock https://github.com/web-platform-dx/web-features/pull/2346
> IDBFactory.open: Showstopper bug in Safari 14

- .github/dependabot.yml
Remove emojis from Dependabot labels.
Follow-up of https://github.com/mdn/browser-compat-data/pull/25144.
> fix(labels): remove emojis from Dependabot labels

- css/selectors/details-content.json
Mirror support for ::details-content to chrome android.
Tested using https://wpt.live/html/rendering/the-details-element/details-pseudo-elements-001.html on my phone.
> Chrome Android also supports ::details-content

- svg/elements/style.json
https://svgwg.org/svg2-draft/styling.html#StyleElement
> Add spec_url for svg `<style>` element attributes `title` and `type`

- api/MutationEvent.json
See https://github.com/w3c/uievents/pull/381
> MutationEvent has no spec anymore

- api/ReadableStreamBYOBReader.json
see https://github.com/denoland/deno/releases/tag/v1.39.0 and https://github.com/denoland/deno/pull/20849
> Deno 1.39 supports `api.ReadableStreamBYOBReader.read.options_min_parameter`

- css/at-rules/import.json
- css/properties/list-style.json
- css/types/easing-function.json
> Update description for some CSS functions

- api/Navigator.json
- api/NavigatorLogin.json
- http/headers/Set-Login.json
See https://github.com/w3c/browser-specs/issues/1608 
Discovered by https://github.com/mdn/browser-compat-data/pull/23958
> Update spec urls for Login Status API

- .github/workflows/close-incomplete-issues.yml
This fixes an issue that is causing the issue closer to crash.
> Update auto-issue closer

- api/Navigator.json
- api/ProtectedAudience.json
Version numbers come from the collector project (v10.12.6)
> Chrome 127/128 adds ProtectedAudience (interest group based ads) support

- api/AudioSession.json
- api/Navigator.json
> Add Firefox impl_url for Audio Session API

- api/Request.json
see spec proposal link https://github.com/whatwg/fetch/pull/1493
> Add Firefox/Safari impl_url for `Request.duplex`

- api/Request.json
- browsers/nodejs.json
add to node.js in https://github.com/nodejs/node/commit/20af3a63e2653211702a44326ed1f71752b8b551 (https://github.com/nodejs/node/pull/45634)
per https://github.com/denoland/deno/issues/16032, deno seems that does not support this feature
see also the spec proposal PR https://github.com/whatwg/fetch/pull/1493
> Add Deno/Node data for `Request.duplex`

- css/at-rules/container.json
the mdn_url is duplicate with the mdn_url of `@container`
> Remove unnecessary mdn_url for `@container` subfeature

- api/SVGStringList.json
> Add spec urls for `SVGStringList` subfeatures

- api/SVGNumberList.json
> Add spec urls for `SVGNumberList` subfeatures

- api/SVGSVGElement.json
same as title
Fixes https://github.com/mdn/browser-compat-data/issues/25517
> Add spec urls for `SVGSVGElement` subfeatures

- api/SVGLengthList.json
> Add spec urls for `SVGLengthList` subfeatures

- css/selectors/buffering.json
- css/selectors/has-slotted.json
- css/selectors/muted.json
- css/selectors/seeking.json
- css/selectors/stalled.json
- css/selectors/volume-locked.json
those features' mdn_url seems not to be automatically added
> Add missing mdn_url for css selectors

- css/properties/white-space.json
the definition of `white-space` property has been updated in CSS Text Module Level 4
this update will better reflect the current spec definition of `white-space` property
> Update spec link for `white-space`

- css/at-rules/media.json
the https://drafts.csswg.org/mediaqueries/ and https://drafts.csswg.org/mediaqueries-4/ refers to the same documentation, so it is fine to only keep one of them
> Remove duplicate spec link for some media query features

- javascript/operators/import.json
the data should be the same as `import`
> Node.js supports `import` operator in workers

- svg/elements/script.json
https://svgwg.org/svg2-draft/interact.html#ScriptElement
> Add spec link for svg `<script>` element subfeatures

- .github/workflows/close-incomplete-issues.yml
Now that we know the spam issue closer is working properly, let's automatically lock spam issues.
> Auto-lock known spam issues

- api/PointerEvent.json
https://developer.apple.com/documentation/safari-release-notes/safari-18_2-release-notes
> Safari 18.2 supports PointerEventInit angle options

- css/properties/alignment-baseline.json
- css/properties/baseline-shift.json
- css/properties/clip-path.json
- css/properties/clip-rule.json
- css/properties/color-interpolation-filters.json
- css/properties/color-interpolation.json
- css/properties/color.json
- css/properties/direction.json
- css/properties/display.json
- css/properties/dominant-baseline.json
- css/properties/flood-color.json
- css/properties/flood-opacity.json
- css/properties/font-variant.json
- css/properties/image-rendering.json
- css/properties/letter-spacing.json
- css/properties/lighting-color.json
- css/properties/marker-end.json
- css/properties/marker-mid.json
- css/properties/marker-start.json
- svg/global_attributes.json
this is similar to https://github.com/mdn/browser-compat-data/pull/25632
but from a-n
> Update spec link for CSS/SVG presentation attribute properties [a-n]

- css/properties/opacity.json
- css/properties/overflow.json
- css/properties/paint-order.json
- css/properties/text-anchor.json
- css/properties/text-decoration.json
- css/properties/text-overflow.json
- css/properties/transform.json
- css/properties/visibility.json
- css/properties/white-space.json
- css/properties/word-spacing.json
- css/properties/writing-mode.json
- svg/global_attributes.json
these are from o-z
as for css properties, add a svg spec link if not existed
as for svg attibutes, add a css spec link if existed and necessary
if possible, make their spec link to be consistent
> Update spec link for CSS/SVG presentation attribute properties [o-z]

- css/properties/list-style-type.json
this also takes the same structural as other css functions, including `list-style:symbols()`
> Add description field for `list-style-type:symbols()`

- css/types/counter.json
- css/types/counters.json
similar to `list-counter-style`, also link to the css-counter-styles module for extended values
> Update spec link for extended styles of counter function

- css/properties/page-break-after.json
- css/properties/page-break-before.json
- css/properties/page-break-inside.json
> Add spec link for legacy alias info for page-break-* values

- svg/elements/foreignObject.json
see https://svgwg.org/svg2-draft/embedded.html#ForeignObjectElement
> Add spec link for svg `<foreignObject>` element

- svg/elements/image.json
see https://svgwg.org/svg2-draft/embedded.html#ImageElement
> Add spec link for svg `<image>` element

- .github/workflows/update-web-features.yml
- package.json
- scripts/tag-web-features.ts
This PR adds a GitHub Actions workflow that updates the web-features tags on a schedule.
> Add action to update web-features tags

- api/Permissions.json
Support for `top-level-storage-access' was added in [m113](https://chromiumdash.appspot.com/commit/20badfdf1ab35986655a091e96602a9dbcc48c56). Updating the file to reflect this.
- [Commit](https://chromiumdash.appspot.com/commit/20badfdf1ab35986655a091e96602a9dbcc48c56) in chromium that added support for the permission.
Follow up to [mdn/content PR# 37831](https://github.com/mdn/content/pull/37831) that updates the code on the documentation page.
> Chrome 113 supports top-level-storage-access permission

- css/properties/max-height.json
- css/properties/max-width.json
- css/properties/min-height.json
- css/properties/min-width.json
- css/properties/width.json
found when working with https://github.com/mdn/data/pull/914
> Add spec link for css `fit-content()` function

- browsers/opera.json
- browsers/opera_android.json
Adds two browser releases:
- Opera 116
- Opera Android 87
> Update Opera releases

- javascript/statements.json
There is no spec yet...
https://github.com/tc39/ecma262/pull/3000
Fixes https://github.com/mdn/browser-compat-data/issues/25873
> Chrome 134 supports new `using` keyword

- css/properties/inset-block-end.json
- css/properties/inset-block-start.json
- css/properties/inset-block.json
- css/properties/inset-inline-end.json
- css/properties/inset-inline-start.json
- css/properties/inset-inline.json
- css/properties/inset.json
https://drafts.csswg.org/css-position/
https://drafts.csswg.org/css-logical/
> Add spec link for inset-* properties of css positioned layout module

- package-lock.json
This PR bumps all of the dependencies to their latest versions using `npm update`.
> Bump all dependencies

- javascript/builtins/AsyncDisposableStack.json
- javascript/builtins/DisposableStack.json
- javascript/builtins/SuppressedError.json
- javascript/builtins/Symbol.json
See https://github.com/mdn/mdn/issues/633
> Chrome 134 supports javascript builtins for explicit resource management

- api/WebTransport.json
- api/WebTransportBidirectionalStream.json
- api/WebTransportDatagramDuplexStream.json
- api/WebTransportError.json
- api/WebTransportReceiveStream.json
- api/WebTransportSendStream.json
- browsers/deno.json
Updates for `WebTransport` related APIs for upcoming Deno 2.2 release
https://github.com/denoland/deno/pull/27431
n/a
> Updates for Deno v2.2

- api/CommandEvent.json
- api/HTMLButtonElement.json
- html/elements/button.json
Add spec URLs for commandfor, command, commandForElement and CommandEvent
> Add spec URLs for Command Invokers

- javascript/builtins/Error.json
See https://github.com/mdn/content/pull/38251 for the content work. 
Support data confirmed using the OWD BCD collector.
> Add Error.isError

- api/CommandEvent.json
- api/HTMLButtonElement.json
- api/HTMLElement.json
- html/elements/button.json
Mark Invoker Commands as shipped in Chromium 135
See https://chromium-review.googlesource.com/c/chromium/src/+/6281568
> Chrome 135 ships Invoker Commands

- index.ts
- lint/fix.ts
- lint/lint.ts
- lint/linter/test-obsolete.ts
- scripts/bulk-editor/utils.ts
- scripts/lib/data-folders.ts
- scripts/migrations/002-remove-webview-flags.ts
- scripts/migrations/007-experimental-false.ts
- scripts/migrations/010-set-oculus-to-mirror.ts
- scripts/migrations/011-set-webview-ios-to-mirror.ts
- scripts/migrations/012-descriptions-to-md.ts
- scripts/traverse.ts
- utils/walk.test.ts
In various places throughout our code, we re-define the list of data folders many times over.  This PR fixes that by using an exported variable.
> refactor: Move list of data folders to its own file

- .github/workflows/pr-reviewdog.yml
Resolves two CodeQL issues with changes introduced in https://github.com/mdn/browser-compat-data/pull/26136, by safely merging a subset of the PR head into the base.
> fix(workflows/pr-reviewdog): resolve CodeQL issues

- scripts/update-browser-releases/firefox.ts
Prevents the `update-browser-releases` script from adding a second Firefox Nightly.
(On release day, Nightly advances before the previous version is promoted to Beta.)
See:
- https://github.com/mdn/browser-compat-data/actions/runs/13646330369/job/38186828532#step:5:29
- https://github.com/mdn/browser-compat-data/pull/26067/commits/965a57aefab84a17829e228c40831a2d8d501d55#diff-c2a0f418fa397fb364d0da53da206c964bac88aae6b2289789c538067e7d5e4bR994
Tested locally by setting the `planned` release to `nightly`, and the script fixes it.
> fix(scripts/update-browser-releases): avoid duplicate Firefox Nightly

- css/selectors/scroll-marker-group.json
- css/selectors/scroll-marker.json
- css/selectors/target-current.json
This makes it to be consistent with other pseudo classes and elements
> Add description fields for new css selectors

- css/properties/interpolate-size.json
> Add Firefox impl_url for CSS `interpolate-size`

- api/ServiceWorker.json
> Add Firefox impl_url for ServiceWorker modules

- css/types/color.json
- css/types/text-edge.json
this will improve the readability of BCD tables
> Update description field for some css types

- css/selectors/fullscreen.json
> Update spec link for `:fullscreen`

- browsers/nodejs.json
- javascript/builtins/Symbol.json
See https://github.com/mdn/browser-compat-data/issues/26216#issuecomment-2780219815 for test evidence
> Update nodejs data for `Symbol.{dispose,asyncDispose}`

- javascript/builtins/Symbol.json
see https://github.com/mdn/browser-compat-data/issues/26216#issuecomment-2780645677 for manually test
part of the https://github.com/mdn/browser-compat-data/issues/26216
> Add deno data for `Symbol.{dispose,asyncDispose}`

- api/FetchLaterResult.json
- api/Window.json
- http/headers/Permissions-Policy.json
Updates fetchLater data added in #26135 with:
- Bug links
- Two permission policy headers for this feature
In prep for adding docs in https://github.com/mdn/content/pull/39016
Explainer: https://github.com/WICG/pending-beacon/blob/main/docs/fetch-later-api.md
Spec PR (not merged yet): https://github.com/whatwg/fetch/pull/1647 
Docs PR: https://github.com/mdn/content/pull/39016
> fetchLater updates

- html/elements/iframe.json
- http/headers/Permissions-Policy.json
see https://github.com/mdn/browser-compat-data/issues/25571
Fixes https://github.com/mdn/browser-compat-data/issues/25571
> Chrome Android 105 supports `picture-in-picture` permission

- html/elements/iframe.json
- http/headers/Permissions-Policy.json
the version should be v69, to be the same as other PIP features
see https://github.com/mdn/browser-compat-data/issues/25571
Relates to https://github.com/mdn/browser-compat-data/issues/25571
> Chrome 69 supports `picture-in-picture` permission

- css/types/attr.json
update firefox impl link to a more specified one
update safari's impl link as the original one is marked as duplicate of the updated one
https://developer.mozilla.org/en-US/docs/Web/CSS/attr
https://drafts.csswg.org/css-values-5/#funcdef-attr
https://bugzilla.mozilla.org/show_bug.cgi?id=435426
https://bugs.webkit.org/show_bug.cgi?id=26609
> Update impl link for `attr()` CSS type

- webextensions/manifest/permissions.json
Replaces 27 Chrome ranges in `webextensions.api.permissions.*`.
See individual commits for links to evidence.
> Replace Chrome ranges in `webextensions.api.permissions`

- webextensions/api/tabGroups.json
- webextensions/manifest/optional_permissions.json
- webextensions/manifest/permissions.json
Adds data for the `webextensions.api.tabGroups` API and updates the `permissions` and `optional_permissions` key data for the introduction of the `tabGroups` permission.
- Related MDN content updates: https://github.com/mdn/content/pull/39370
> Add `webextensions.api.tabGroups` API

- api/Document.json
- api/Element.json
- api/MouseEvent.json
- api/ShadowRoot.json
- html/elements/iframe.json
Updates Chrome Android data for Pointer Lock API features.
- Fixes https://github.com/mdn/browser-compat-data/issues/19829.
> Chrome Android doesn't support Pointer Lock API

- webassembly/api.json
> Node.js 18.1.0 added `WebAssembly.compileStreaming()`

- api/HTMLElement.json
- html/global_attributes.json
Adds Firefox bug for popover hint.
> Add Firefox impl url for popover hint

- css/properties/align-content.json
- css/properties/column-gap.json
- css/properties/gap.json
- css/properties/row-gap.json
More missing CSS values. The "normal" value is initial/default values here, so support is the same as the property itself.
None.
> Add CSS `{align-content,column-gap,gap,row-gap}: normal`

- html/elements/script.json
See https://github.com/mdn/mdn/issues/672
> Add Firefox impl_url for Multiple import maps

- .github/workflows/update-webdriver-bidi-data.yml
- scripts/split.ts
Updates the `update-webdriver-bidi-data` workflow to split up the `webdriver/bidi.json` file into multiple `webdriver/bidi/<module>.json`.
This avoids a huge file, and makes it easier to review changes.
Test run succeeded:
- https://github.com/mdn/browser-compat-data/actions/runs/15210175533/job/42782265516#step:6:25
- https://github.com/mdn/browser-compat-data/pull/26888
> ci(update-webdriver-bidi-data): split into modules

- GOVERNANCE.md
Moves WebExtension people to BCD peers:
- @rpl 
- @Rob--W 
- @dotproto 
- @zombie 
- @willdurand 
Everyone has confirmed to me that they have read the [BCD peers section](https://github.com/mdn/browser-compat-data/blob/main/GOVERNANCE.md#peers).
> Add WebExtension BCD peers

- webextensions/api/storage.json
Fixes a typo in a Firefox bug.
See: https://bugzil.la/1385832"
> Fix typo in Firefox bug

- api/CreateMonitor.json
- api/LanguageDetector.json
- api/Summarizer.json
- api/Translator.json
We have had reports that the [Translator and Language Detector APIs](https://developer.mozilla.org/en-US/docs/Web/API/Translator_and_Language_Detector_APIs) and the [Summarizer API](https://developer.mozilla.org/en-US/docs/Web/API/Summarizer_API) are disabled in some geographical locations.
This PR therefore adds a note to the affected APIs to inform readers, which may help them if they notice any unusual behavior.
> Chrome AI APIs are subject to geographical restrictions

- api/SubtleCrypto.json
Chrome 137+ supports Ed25519 in web crypto; see https://chromestatus.com/feature/4913922408710144.
This PR updates the relevant data points to include this data.
> Chrome 137 adds Ed25519 in Web Crypto

- .github/workflows/pr-rebase-needed.yml
Cancels concurrent runs of the `pr-rebase-needed` workflow.
- Same as: https://github.com/mdn/content/pull/37954
> ci(pr-rebase-needed): cancel concurrent jobs

- api/HTMLButtonElement.json
Shipped in Chrome 139
Shipped in Safari Tech Preview
https://chromiumdash.appspot.com/commit/c9f641b44670bbc9c810d22aa6523c3b07558332
Safari TP was manually tested.
> Update support for request-close command

- html/elements/input/color.json
Add impl url for color input on Firefox Android
> Add impl url for color input on Firefox Android

- .github/workflows/system-file-changes.yml
> ci(system-file-changes): improve is_admin_or_owner() 

- api/CSSFunctionDeclarations.json
- api/CSSFunctionDescriptors.json
- api/CSSFunctionRule.json
- api/IdentityCredentialError.json
- api/PaymentRequest.json
- api/SpeechGrammarList.json
- api/SpeechRecognition.json
- api/SpeechRecognitionEvent.json
- api/XRDepthInformation.json
- api/XRSession.json
- css/properties/corner-block-end-shape.json
- css/properties/corner-block-start-shape.json
- css/properties/corner-bottom-left-shape.json
- css/properties/corner-bottom-right-shape.json
- css/properties/corner-bottom-shape.json
- css/properties/corner-end-end-shape.json
- css/properties/corner-end-start-shape.json
- css/properties/corner-inline-end-shape.json
- css/properties/corner-inline-start-shape.json
- css/properties/corner-left-shape.json
- css/properties/corner-right-shape.json
- css/properties/corner-shape.json
- css/properties/corner-start-end-shape.json
- css/properties/corner-start-start-shape.json
- css/properties/corner-top-left-shape.json
- css/properties/corner-top-right-shape.json
- css/properties/corner-top-shape.json
The @openwebdocs [BCD collector project](https://github.com/openwebdocs/mdn-bcd-collector) v10.13.3 found new features shipping in Chrome 139 beta which was released last week. Currently, the collector covers about 90% of BCD, so the following list might not be exhaustive. Also, if a feature is in Chrome Canary/behind origin trials/enrollment, it is not considered here.
With this PR, BCD considers the following 47 features as shipping in Chrome 139:
- api.CSSFunctionDeclarations
- api.CSSFunctionDeclarations.style
- api.CSSFunctionDescriptors
- api.CSSFunctionDescriptors.result
- api.CSSFunctionRule
- api.CSSFunctionRule.getParameters
- api.CSSFunctionRule.name
- api.CSSFunctionRule.returnType
- api.HTMLButtonElement.command.request-close
- api.IdentityCredentialError
- …
> Updates for Chrome 139 beta

- http/headers/No-Vary-Search.json
Lists the Bugzilla ticket for `No-Vary-Search` in Firefox compat data.
N/A
N/A
> Add FF bug for No-Vary-Search

- GOVERNANCE.md
Updated MDN Staff link on the Governance.md page, linking to the new about page.
> Update MDN Staff link

- api/FetchLaterResult.json
- api/Window.json
- http/headers/Feature-Policy.json
- http/headers/Permissions-Policy.json
Add `fetchLater` spec URLs now they've been merged into the fetch spec:
https://github.com/whatwg/fetch/pull/1647
N/A, just spec URL updates
See https://github.com/whatwg/fetch/pull/1647
> Add fetchLater spec URLs

- css/properties/align-self.json
- css/properties/justify-content.json
- css/properties/justify-items.json
- css/properties/justify-self.json
The mdn-bcd-collector found these for a while already. These are default values (or values shipped with the initial implementation). Adding them for completeness.
> Add missing sub features for CSS flexbox/grid properties

- api/QuotaExceededError.json
Spec change: https://github.com/whatwg/webidl/pull/1465
Chromestatus: https://chromestatus.com/feature/6194847180128256
> Chrome 138 adds QuotaExceededError interface
