- api/Document.json
- api/HTMLVideoElement.json
- api/PictureInPictureEvent.json
- api/PictureInPictureWindow.json
This PR updates and corrects version values for WebView Android for the `pictureInPicture` members of the `Document` and `HTMLVideoElement` APIs, based upon results from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v7.1.2).  The collector obtains results based upon the latest WebView version (to determine if it is supported), then version numbers are copied from Chrome Android.
Tests Used:
https://mdn-bcd-collector.gooborg.com/tests/api/Document/exitPictureInPicture
https://mdn-bcd-collector.gooborg.com/tests/api/Document/pictureInPictureElement
https://mdn-bcd-collector.gooborg.com/tests/api/Document/pictureInPictureEnabled
> Update WebView versions for api.Document/HTMLVideoElement.pictureInPicture*

- api/MediaStreamTrackAudioSourceNode.json
This PR removes the irrelevant `mediaStreamTrack` member of the `MediaStreamTrackAudioSourceNode` API as per the corresponding [data guidelines](https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines.md#removal-of-irrelevant-features). The lack of current support has been confirmed by the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v7.1.2), even if the current BCD suggests support.
> Remove api.MediaStreamTrackAudioSourceNode.mediaStreamTrack from BCD

- api/HTMLMediaElement.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `sinkId` member of the `HTMLMediaElement` API, based upon results from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v7.1.2).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/HTMLMediaElement/sinkId
> Update Chromium versions for api.HTMLMediaElement.sinkId

- api/IDBIndex.json
This PR adds the missing flag data for Firefox for the `locale` and `isAutoLocale` properties of the `IDBIndex` API, as mentioned in https://github.com/mdn/browser-compat-data/pull/18560#pullrequestreview-1240592712.
> Add flag data for api.IDBIndex.[isAuto]locale

- api/DOMPoint.json
This PR updates and corrects version values for Firefox and Firefox Android for the `fromPoint` member of the `DOMPoint` API, based upon results from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v7.1.3).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/DOMPoint/fromPoint
> Update Firefox versions for api.DOMPoint.fromPoint

- api/DedicatedWorkerGlobalScope.json
This PR updates and corrects version values for Firefox and Firefox Android for the `cancelAnimationFrame` and `requestAnimationFrame` members of the `DedicatedWorkerGlobalScope` API, based upon results from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v7.1.3).
Tests Used:
https://mdn-bcd-collector.gooborg.com/tests/api/DedicatedWorkerGlobalScope/cancelAnimationFrame
https://mdn-bcd-collector.gooborg.com/tests/api/DedicatedWorkerGlobalScope/requestAnimationFrame
> Update Firefox versions for api.DedicatedWorkerGlobalScope.animationFrame

- api/ExtendableEvent.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `ExtendableEvent` member of the `ExtendableEvent` API, based upon results from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v7.1.3).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/ExtendableEvent/ExtendableEvent
> Update Chromium versions for api.ExtendableEvent.ExtendableEvent

- api/FetchEvent.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `FetchEvent` member of the `FetchEvent` API, based upon results from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v7.1.3).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/FetchEvent/FetchEvent
> Update Chromium versions for api.FetchEvent.FetchEvent

- api/HTMLInputElement.json
This PR updates and corrects version values for WebView Android for the `webkitEntries` member of the `HTMLInputElement` API, based upon results from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v7.1.3).  The collector obtains results based upon the latest WebView version (to determine if it is supported), then version numbers are copied from Chrome Android.
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/HTMLInputElement/webkitEntries
> Update WebView versions for api.HTMLInputElement.webkitEntries

- api/IDBFactory.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `databases` member of the `IDBFactory` API, based upon results from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v7.1.3).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/IDBFactory/databases
> Update Chromium versions for api.IDBFactory.databases

- api/MediaDeviceInfo.json
This PR updates and corrects version values for Microsoft Edge for the `MediaDeviceInfo` API, based upon results from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v7.1.3).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/MediaDeviceInfo
> Update Edge versions for MediaDeviceInfo API

- api/MediaStreamTrackEvent.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `MediaStreamTrackEvent` member of the `MediaStreamTrackEvent` API, based upon results from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v7.1.3).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/MediaStreamTrackEvent/MediaStreamTrackEvent
> Update Chromium versions for api.MediaStreamTrackEvent.MediaStreamTrackEvent

- api/Notification.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `image` member of the `Notification` API, based upon results from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v7.1.3).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/Notification/image
> Update Chromium versions for api.Notification.image

- api/PeriodicSyncEvent.json
This PR updates and corrects version values for WebView Android for the `PeriodicSyncEvent` API, based upon results from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v7.1.3).  The collector obtains results based upon the latest WebView version (to determine if it is supported), then version numbers are copied from Chrome Android.
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/PeriodicSyncEvent
> Update WebView versions for PeriodicSyncEvent API

- api/PeriodicSyncManager.json
This PR updates and corrects version values for WebView Android for the `PeriodicSyncManager` API, based upon results from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v7.1.3).  The collector obtains results based upon the latest WebView version (to determine if it is supported), then version numbers are copied from Chrome Android.
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/PeriodicSyncManager
> Update WebView versions for PeriodicSyncManager API

- css/types/rem.json
Firefox 109 added support for CSS `rem()` function.
Ref: https://bugzilla.mozilla.org/show_bug.cgi?id=1785117
> feat(css): Update CSS Values Level 4 `rem()` compatibility data

- css/at-rules/media.json
I have run [test](https://codepen.io/NiedziolkaMichal/pen/YzjPGRr) on Chrome, Firefox, and Safari. Only firefox has this feature working.
[Chromium issue](https://bugs.chromium.org/p/chromium/issues/detail?id=1224711&q=video-dynamic-range&can=2)
[Webkit issue](https://bugs.webkit.org/show_bug.cgi?id=249678)
> Remove support for video-dynamic-range

- package-lock.json
- package.json
- test/linter/test-spec-urls.ts
See https://github.com/w3c/browser-specs/pull/817#issuecomment-1377207689
It would be better for us to use web-specs.
I will have a follow-up PR to clean our exception list.
Closes https://github.com/mdn/browser-compat-data/pull/18612
> Replace browser-specs with web-specs

- webextensions/api/tabs.json
On every build I see: 
```
Mirroring - 7 problems (0 errors, 7 warnings):
[27](https://github.com/mdn/browser-compat-data/actions/runs/3883926419/jobs/6625808535#step:5:28)
✖ webextensions.api.tabs.ZoomSettings - Warning → Data for edge can be automatically mirrored, use "edge": "mirror" instead
[28](https://github.com/mdn/browser-compat-data/actions/runs/3883926419/jobs/6625808535#step:5:29)
◆ Tip: Run npm run fix to fix this problem automatically
[29](https://github.com/mdn/browser-compat-data/actions/runs/3883926419/jobs/6625808535#step:5:30)
✖ webextensions.api.tabs.ZoomSettings.defaultZoomFactor - Warning → Data for edge can be automatically mirrored, use "edge": "mirror" instead
[30](https://github.com/mdn/browser-compat-data/actions/runs/3883926419/jobs/6625808535#step:5:31)
◆ Tip: …
```
> Fix WebExtension mirroring warnings

- http/headers/Digest.json
- http/headers/Expect-CT.json
- http/headers/Want-Digest.json
- test/linter/test-spec-urls.ts
This PR updates BCD's exception list for specs that aren't in browser-specs or web-specs.
See https://github.com/w3c/browser-specs/pull/817#issuecomment-1377207689 for details
> Update spec exception list

- api/HTMLAnchorElement.json
- api/HTMLAreaElement.json
- api/HTMLIFrameElement.json
- api/HTMLImageElement.json
- api/SVGAElement.json
This reverts #17421 for all interfaces other than SVGAElement, based upon results from mdn-bcd-collector v7.1.3.  See the linked PR for more details.
> Partially revert Firefox versions for referrerPolicy property

- api/NavigatorUAData.json
This PR updates and corrects version values for Samsung Internet for the `NavigatorUAData` API, based upon results from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v7.1.3).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/NavigatorUAData
> Update Samsung Internet versions for NavigatorUAData API

- api/Permissions.json
This prefixes rather than suffixes permission keys with `permission_` so that they will be grouped. Otherwise you end up with the case we have now where the permissions are interleaved with methods - see https://developer.mozilla.org/en-US/docs/Web/API/Permissions_API#browser_compatibility
This is first part of work on https://github.com/mdn/content/issues/13003. We should also add spec links for each of these permissions, as they are defined in their own specs, but will leave that as a follow up.
> Permissions - reorder permission strings together

- api/ClipboardItem.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `ClipboardItem` API, based upon results from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v7.1.3).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/ClipboardItem
> Update Chromium versions for ClipboardItem API

- test/linter/test-mirror.ts
This PR converts the "mirrorable data" warning into an error as suggested in https://github.com/mdn/browser-compat-data/pull/18617#issuecomment-1378381044.
> Make mirroring linter an error vs. a warning

- css/types/length.json
- test/linter/test-obsolete.ts
Enable the css length unit "lh" for chrome. Referenced bug is also close (Nov 2022) and tested in chromium 109. 
Bug was fixed https://crbug.com/937104
Implementation tested in chromium 109 (Did not work before in 108)
> Enable css lenght type lh for chrome

- api/TextTrack.json
This PR updates and corrects version values for Microsoft Edge for the `id` member of the `TextTrack` API, based upon results from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v7.1.3).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/TextTrack/id
> Update Edge versions for api.TextTrack.id

- api/UserActivation.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `isActive` member of the `UserActivation` API, based upon results from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v7.1.3).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/UserActivation/isActive
> Update Chromium versions for api.UserActivation.isActive

- api/TransitionEvent.json
This PR updates and corrects version values for Edge for the `TransitionEvent` member of the `TransitionEvent` API, based upon results from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v7.1.3).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/TransitionEvent/TransitionEvent
> Update Edge versions for api.TransitionEvent.TransitionEvent

- api/WEBGL_compressed_texture_astc.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `WEBGL_compressed_texture_astc` API, based upon results from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v7.1.3).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/WEBGL_compressed_texture_astc
> Update Safari versions for WEBGL_compressed_texture_astc API

- api/WEBGL_compressed_texture_etc.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `WEBGL_compressed_texture_etc` API, based upon results from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v7.1.3).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/WEBGL_compressed_texture_etc
> Update Safari versions for WEBGL_compressed_texture_etc API

- api/Window.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `originAgentCluster` member of the `Window` API, based upon results from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v7.1.3).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/Window/originAgentCluster
> Update Chromium versions for api.Window.originAgentCluster

- browsers/edge.json
Edge 109 was released yesterday. This PR contains the necessary changes to update the edge.json file on the repo.
> New edge 109 browser data

- api/XRSession.json
It's part of the AR module, so 81 is correct
https://chromestatus.com/feature/5450241148977152
> XRSession.environmentBlendMode shipped in Chromium 81

- css/selectors/picture-in-picture.json
According to the Chrome roadmap (https://chromestatus.com/roadmap), `:picture-in-picture` pseudo class will be added in Chrome v110, but MDN states that it has already been added in Chrome v76.
Correct support data to Chrome v110 in line with the Chrome roadmap.
https://chromestatus.com/feature/6259534815297536
Fixes #18550
> Fix support data for picture-in-picture in chromium-based-browsers

- api/WebTransport.json
- api/WebTransportBidirectionalStream.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `WebTransport` API, based upon results from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v7.1.3).
Tests Used:
https://mdn-bcd-collector.gooborg.com/tests/api/WebTransport
https://mdn-bcd-collector.gooborg.com/tests/api/WebTransportBidirectionalStream
---
Note: the alternative names were removed from the data because I could not find any evidence of them in Chrome 97.  This data was added in #18209 but the author mentioned the data wasn't quite definitive.
> Update Chromium versions for WebTransport API

- api/XRSystem.json
See https://bugs.chromium.org/p/chromium/issues/detail?id=1050600 and https://chromium.googlesource.com/chromium/src/+/d7a0292ca39f93d358b68ee703b0eb4fb4901022
I guess the same happened to Samsung so I think we should mirror. At least I don't see why not.
> Chromium renamed XR to XRSystem in 83

- api/_globals/fetch.json
The keepalive parameter to the Fetch (and Request) API is [still not supported by Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1342484) and this is likely to catch people out.
This PR grabs the fetch param data from the Request API to make this clearer (located in api/Request.json).
Symlinked build dir into mdn/content and checked build.
> Add fetch keepalive compat data

- api/Document.json
This PR removes the irrelevant `registerElement` member of the `Document` API as per the corresponding [data guidelines](https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines.md#removal-of-irrelevant-features). The lack of current support has been confirmed by the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v7.1.3), even if the current BCD suggests support.
> Remove api.Document.registerElement from BCD

- test/linter/test-prefix.ts
This PR updates the linter to ensure that an `alternative_name` cannot simply be a `prefix`.  For example, if a statement has `"alternative_name": "webkitfoobar"`, the linter will require `"prefix": "webkit"` in its place.
> Ensure that `alternative_name` can't just be `prefix`ed

- css/types/length.json
- test/linter/test-obsolete.ts
'lh' and 'rlh' are part of the CSS Values and Units Module Level 4 draft just like small, large, and dynamic viewport units.
They should therefor also be marked as following the standard track
Both lengths were added as [supported in Chromium 109 in a previous PR](https://github.com/mdn/browser-compat-data/pull/18624)
https://www.w3.org/TR/css-values-4/#lh
https://www.w3.org/TR/css-values-4/#rlh
> Mark 'lh' and 'rlh' units as standard compliant

- mathml/elements/mo.json
Add compat data for the form and largeop attributes of the mo element.
It is assumed that largeop/form were in Gecko's MathML implementation before the initial release of Firefox.
largeop in chrome 88: https://chromiumdash.appspot.com/commit/128f42798a9b4a38af0c4091eeba10257f983050
largeop in Safari 8:
https://searchfox.org/wubkat/commit/2564e621dafa47d3a8d4efe12eb625e15a549311
form in chrome 87:
https://chromiumdash.appspot.com/commit/ebf91dd9f79a57164d54485cbd5434ca81d609f5
form in Safari 8:
https://searchfox.org/wubkat/commit/6beac8063b0254b04afbc1f464c425879d76ad5d
https://github.com/mdn/content/issues/23669
https://github.com/mdn/content/pull/23769
> Add compat data for the form and largeop attributes of the mo element

- api/WEBGL_compressed_texture_pvrtc.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `WEBGL_compressed_texture_pvrtc` API, based upon results from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v7.1.3).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/WEBGL_compressed_texture_pvrtc
Fixes #18692.
> Update Safari versions for WEBGL_compressed_texture_pvrtc API

- api/Element.json
This PR adds real values for Opera and Opera Android for the `requestFullscreen.returns_promise` member of the `Element` API.  This should have been mirrored but wasn't, probably due to Chrome getting an update that introduced this change but Opera had not yet updated at the time.
Fixes #18420.
> Add Opera versions for api.Element.requestFullscreen.returns_promise

- api/HTMLFormElement.json
This PR corrects the values for Firefox Android for the `formdata_event` member of the `HTMLFormElement` API.  This was a case of Firefox Android not updated when version 79 was released.
Fixes #18695.
> Update Firefox Android versions for api.HTMLFormElement.formdata_event

- css/types/image.json
This PR fixes #18674 by pointing to the Level 4 spec rather than the Level 3 spec.
> Fix spec URL for css.types.image.linear-gradient

- webextensions/manifest/manifest_version.json
This PR adds real values for Firefox and Firefox Android for the `v3` member of the `manifest/manifest_version` Webextensions feature.  This fixes #18702, which is where the data comes from.
> Add Firefox versions for webextensions.manifest/manifest_version.v3

- css/selectors/user-invalid.json
- css/selectors/user-valid.json
This PR updates the versions for the `:user-valid` and `:user-invalid` selectors based on manual testing.  This fixes #18656.
> Update Safari versions for css.selectors.user-valid/user-invalid

- mathml/elements/mi.json
- mathml/elements/mn.json
- mathml/elements/mo.json
- mathml/elements/mphantom.json
- mathml/elements/mroot.json
- mathml/elements/mrow.json
- mathml/elements/msqrt.json
- mathml/elements/mtable.json
- mathml/elements/mtd.json
- mathml/elements/mtext.json
- mathml/elements/mtr.json
MathML-related features mentioned on https://people.igalia.com/fwang/blink-on-17/public/analyze-browser-compat-data.html ; use `mirror` for Safari iOS instead of `version_added`: `false`.
Safari iOS has the same MathML implementation as Safari, so it is safe to just mirror them. Safari and Safari iOS have not followed the same release schedule, so it might be possible that the version number for the first release of a mathml feature is not accurate, but it's still closer to reality that claiming the feature has never been supported.
N/A
> Mirror MathML features for Safari iOS

- api/MediaDevices.json
- api/MediaStreamTrack.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `setCaptureHandleConfig` member of the `MediaDevices` API, based upon results from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v7.1.2).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/MediaDevices/setCaptureHandleConfig
> Update Chromium versions for api.MediaDevices.setCaptureHandleConfig

- webextensions/manifest/optional_permissions.json
- webextensions/manifest/permissions.json
Corrects release version for webRequestFilterResponse.serviceWorkerScript
See the content update in https://github.com/mdn/content/pull/23699
> Correct release version for webRequestFilterResponse.serviceWorkerScript

- javascript/operators/nullish_coalescing_assignment.json
This PR fixes the name for the `logical nullish assignment` operator and changes it to the `nullish coalescing assignment` operator following the content change.  Fixes #18558.
> Rename "logical nullish assignment" to "nullish coalescing assignment"

- api/StorageManager.json
FF supports OPFS by default in nightly from FF110 - see https://bugzilla.mozilla.org/show_bug.cgi?id=1785123. In practice this means that the `navigator.storage.getDirectory()` method is implemented, hence this change.
The preference for the feature was actually introduced in FF97 (tested using browserstack).
Other docs work for the feature can be tracked in https://github.com/mdn/content/issues/23688
> FF110 Nightly supports StorageManager.getDirectory() - OPFS

- api/Permissions.json
FF110 adds support for querying the Permissions API midi permission in https://bugzilla.mozilla.org/show_bug.cgi?id=1437171.
This allows users to query for midi permission support using code like: `navigator.permissions.query({ name: "midi" })` or `navigator.permissions.query({ name: "midi", sysex: true })`, where previously an exception would be thrown.
This PR just adds the supported version and sets this as no-longer experimental. I also added spec link, though this is not yet shown anywhere on MDN. 
Other docs work for this can be tracked in https://github.com/mdn/content/issues/23680
> FF110 Permission API midi permission

- browsers/safari.json
- browsers/safari_ios.json
This PR adds Safari 16.3 to BCD following its release yesterday.
> Safari 16.3 is released

- css/properties/align-content.json
- css/properties/align-items.json
- css/properties/align-self.json
- css/properties/justify-content.json
Add support for `start` and `end` on `align-items` for Safari 16. 
Navigate to https://developer.mozilla.org/en-US/docs/Web/CSS/align-items in Chrome (107.0.5304.110) and Safari (16). Visually compare behavior of Results section.
Compared values:
- `normal`
- `flex-start`
- `flex-end`
- `start`
- `end`
Screenshot of Safari 16 with one of the aforementioned values:
As for existing bug reports, I didn't find anything specific to `align-items` -- I will admit I am not acquainted with searching for bugs in webkit. A [a comment in a similar report](https://bugs.webkit.org/show_bug.cgi?id=157070#c6) mentions that many flexbox bugs were fixed by Feb 2022. 
Fixes #16049
> Safari supports `start` and `end`

- api/CSS.json
This PR is a part of a project to add missing interfaces and interface features to BCD that are from an active spec (including WICG specs) and is supported in at least one browser.  This particular PR adds the missing `sv*` members of the CSS API, populating the results using data from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v7.1.4).
Tests Used:
https://mdn-bcd-collector.gooborg.com/tests/api/CSS/svb
https://mdn-bcd-collector.gooborg.com/tests/api/CSS/svh
https://mdn-bcd-collector.gooborg.com/tests/api/CSS/svi
https://mdn-bcd-collector.gooborg.com/tests/api/CSS/svmax
https://mdn-bcd-collector.gooborg.com/tests/api/CSS/svmin
https://mdn-bcd-collector.gooborg.com/tests/api/CSS/svw
_Check out the [collector's guide on how to review this …
> Add missing api.CSS.sv* features

- api/CSSKeyframesRule.json
This PR is a part of a project to add missing interfaces and interface features to BCD that are from an active spec (including WICG specs) and is supported in at least one browser.  This particular PR adds the missing `length` member of the CSSKeyframesRule API, populating the results using data from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v7.1.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/CSSKeyframesRule/length
> Add missing api.CSSKeyframesRule.length feature

- browsers/opera_android.json
This PR adds Opera Android 73 and marks it as the current Opera Android release.  Release date comes from UpToDown, engine version comes from user agent string.
> Opera Android 73 is released

- api/MathMLElement.json
This PR is a part of a project to add missing interfaces and interface features to BCD that are from an active spec (including WICG specs) and is supported in at least one browser.  This particular PR adds the missing `attributeStyleMap` member of the MathMLElement API, populating the results using data from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v7.1.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/MathMLElement/attributeStyleMap
> Add missing api.MathMLElement.attributeStyleMap feature

- api/XRHand.json
This PR is a part of a project to add missing interfaces and interface features to BCD that are from an active spec (including WICG specs) and is supported in at least one browser.  This particular PR adds the missing features of the XRHand API, populating the results using data from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v7.1.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/XRHand
> Add missing features for XRHand API

- webextensions/manifest/icons.json
Since SVG icons are [not supported in Chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=29683) they are not supported in derivatives like Edge and Opera.
I was asked to update these browsers data to "mirror" in change request to corresponding MDN page update: https://github.com/mdn/content/pull/22845
Unfortunatelly I did not tested my changes.
It is related to https://github.com/mdn/content/pull/22845
> icons.json: mirrored Opera and Edge to Chrome

- api/CSPViolationReportBody.json
Reverts mdn/browser-compat-data#18557
For more information, see https://github.com/mdn/browser-compat-data/issues/18710
> Revert "releases(108): Fx 108 support for 'effective-directive' and 'status-code' props"

- http/headers/Content-Security-Policy.json
Fx 110 enables `'unsafe-hashes'` which allows for hashing event handlers, style attributes and `javascript:` navigations (`<a href="javascript:alert('Hello!')"></a>`)
__Parent issue:__
__Related pull requests:__
__Bugzilla bugs:__
- https://bugzilla.mozilla.org/show_bug.cgi?id=1343950
> Fx(110): 'unsafe-hashes' CSP keyword is enabled

- http/headers/Link.json
Support was added to Gecko 0.9 (predates Firefox) by [bug 3248](https://bugzilla.mozilla.org/show_bug.cgi?id=3248).
> Fix Firefox compatibility data for the Link HTTP header

- http/headers/Content-Security-Policy.json
`'unsafe-hashes'` enabled in 109, see https://github.com/mdn/browser-compat-data/pull/18759#issuecomment-1407372232
CCing @evilpie
> Fx(109): 'unsafe-hashes' CSP keyword is enabled

- api/CSS.json
- api/Highlight.json
- api/HighlightRegistry.json
- css/selectors/highlight.json
* Marked API as non-experimental: the API shipped on-by-default in Chromium-based browsers. I don't believe we're in the experimental phase anymore where browsers are waiting for feedback (although the API is still off-by-default in Safari).
* Added the missing `::highlight()` pseudo-element, which comes with this API.
* Changed the spec URLs to use the www.w3.org server instead.
> CSS Custom Highlight API follow-ups

- api/CSSImportRule.json
This missing page is being created in the following mdn/content PR: https://github.com/mdn/content/pull/24014
> CSSImportRule.layerName: add link to MDN

- javascript/builtins/Temporal/Calendar.json
- javascript/builtins/Temporal/Duration.json
- javascript/builtins/Temporal/Instant.json
- javascript/builtins/Temporal/PlainDate.json
- javascript/builtins/Temporal/PlainDateTime.json
- javascript/builtins/Temporal/PlainMonthDay.json
- javascript/builtins/Temporal/PlainTime.json
- javascript/builtins/Temporal/PlainYearMonth.json
- javascript/builtins/Temporal/TimeZone.json
- javascript/builtins/Temporal/ZonedDateTime.json
This PR fixes the names of the constructor features for the Temporal JavaScript API.  These were inappropriately named `constructor`.
> Fix names of constructor features for Temporal API objects

- api/EXT_texture_norm16.json
Edge seems to support the WebGL Extension EXT_texture_norm16 just like Chrome does.
I tested via https://webglreport.com/?v=2 on (Edge Version 109).
Thanks a lot @Elchi3 for suggesting the "mirror" approach for this fix.
> Add support of EXT_texture_norm16 WebGL Extension for Edge

- api/MIDIOutputMap.json
This PR is a part of a project to add missing interfaces and interface features to BCD that are from an active spec (including WICG specs) and is supported in at least one browser.  This particular PR adds the missing `@@iterator` member of the MIDIOutputMap API, populating the results using data from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v7.1.5).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/MIDIOutputMap/@@iterator
> Add missing api.MIDIOutputMap.@@iterator feature

- api/PaymentRequestEvent.json
This PR is a part of a project to add missing interfaces and interface features to BCD that are from an active spec (including WICG specs) and is supported in at least one browser.  This particular PR adds the missing features of the PaymentRequestEvent API, populating the results using data from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v7.1.5).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/PaymentRequestEvent
> Add missing features for PaymentRequestEvent API

- api/Element.json
Record that `Element.animate()`'s `pseudoElement` option is supported in Chrome as of version 84.
This was part of the [Web Animations API feature](https://chromestatus.com/feature/5126405660606464), listed as shipping in Chrome 84.
According to the [tracking bug](https://bugs.chromium.org/p/chromium/issues/detail?id=978551), support was enabled by default in [9cdcb10](https://chromium.googlesource.com/chromium/src/+/9cdcb106b0bcfee75cf3e94576fd48c055cc4bd6), which landed in [84.0.4129.0](https://storage.googleapis.com/chromium-find-releases-static/9cd.html#9cdcb106b0bcfee75cf3e94576fd48c055cc4bd6).
I don't have a chromium 84 install, but this feature definitely works in chromium 109, if that's worth anything; and @rururux [reported it working in chrome …
> Update Chromium, Safari versions for `Element.animate()` `options.pseudoElement`

- api/Element.json
Adds support data for the `timeline` property of the `options` parameter of `Element.animate()`.
Firefox does not support this option. Chromium does, likely since version 85. Safari likely does, since version 16.
Manually tested in Firefox 111 and Chromium 109. A simple test case is:
```js
console.assert(
document.body.animate([], { timeline: new DocumentTimeline() }).timeline !== document.timeline
);
```
Chromium support was added in [d393163](https://chromium.googlesource.com/chromium/src/+/d3931637492464d7781d2699c3c549c8f845aec6), which released in [Chromium 85](https://storage.googleapis.com/chromium-find-releases-static/d39.html#d3931637492464d7781d2699c3c549c8f845aec6).
Safari support was added in https://github.com/WebKit/WebKit/commit/1a2775d4de27be9e08d6c54a5d7ae03abc315168, …
> Add data for `Element.animate()` `options.timeline`

- api/BarProp.json
This PR adds real values for Opera and Opera Android for the `visible.returns_popup` member of the `BarProp` API.  I'm guessing that Opera was set to `false` because a corresponding Opera release wasn't out when the data was added, so this PR sets it to mirror from Chrome.
> Add Opera versions for api.BarProp.visible.returns_popup

- api/CanMakePaymentEvent.json
This PR adds real values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `modifiers` member of the `CanMakePaymentEvent` API.  The other Chromium browsers should be mirrored, but are not for whatever reason.  This corrects it by setting the other browsers to mirror.
> Add Chromium versions for api.CanMakePaymentEvent.modifiers

- api/MediaSource.json
This PR removes the redundant `worker_support` subfeatures applied to all of the MediaSource subfeatures, and adds a top-level `worker_support` feature in their place.
> Remove redundant worker_support from each MediaSource subfeature

- api/Element.json
This PR adds real values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `scrollLeft` member of the `Element` API, based upon manual testing.
Test Code Used: https://jsfiddle.net/gh9wycov/
This fixes #18465.
> Add Chromium versions for api.Element.scrollLeft

- api/CanvasRenderingContext2D.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `drawImage.ImageBitmap_source_image` member of the `CanvasRenderingContext2D` API, based upon results from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v7.1.5).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/CanvasRenderingContext2D/drawImage.ImageBitmap_source_image
---
Note: I don't actually have a Safari 15 VM to test with, but the collector found support in 14.1> ≤15.1.  Since `ImageBitmap` was implemented in Safari 15, I went with "15" as the version number for this.
> Update Safari versions for api.CanvasRenderingContext2D.drawImage.ImageBitmap_source_image

- api/SVGGlyphRefElement.json
This PR is a part of a project to add missing interfaces and interface features to BCD that are from an active spec (including WICG specs) and is supported in at least one browser.  This particular PR adds the missing `href` member of the SVGGlyphRefElement API, populating the results using data from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v7.1.5).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/SVGGlyphRefElement/href
> Add missing api.SVGGlyphRefElement.href feature

- api/SVGAltGlyphElement.json
This PR is a part of a project to add missing interfaces and interface features to BCD that are from an active spec (including WICG specs) and is supported in at least one browser.  This particular PR adds the missing `href` member of the SVGAltGlyphElement API, populating the results using data from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v7.1.5).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/SVGAltGlyphElement/href
> Add missing api.SVGAltGlyphElement.href feature

- api/GestureEvent.json
This PR is a part of a project to add missing interfaces and interface features to BCD that ~~are from an active spec (including WICG specs) and~~ is supported in at least one browser.  This particular PR adds the missing features of the GestureEvent API, populating the results using data from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v7.1.5).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/GestureEvent
> Add missing features for GestureEvent API

- api/Window.json
This PR is a part of a project to add missing interfaces and interface features to BCD that are from an active spec (including WICG specs) and is supported in at least one browser.  This particular PR adds the missing `getDigitalGoodsService` member of the Window API, populating the results using data from ChromeStatus at https://chromestatus.com/feature/5339955595313152.
> Add missing api.Window.getDigitalGoodsService feature

- browsers/opera.json
Update Opera release to 95, released on Feb 1st using chromium 109, see https://blogs.opera.com/desktop/2023/02/opera-95-stable/
Also increment beta/nighly versions, although I'm not sure when they are actually released/provided (https://www.opera.com/download still provides 95 and 96 for beta and developer versions respectively).
Reading the blog post.
Android version was updated in https://github.com/mdn/browser-compat-data/pull/18746
> Update Opera release version to 95

- css/at-rules/container.json
- css/properties/container-name.json
- css/properties/container-type.json
- css/properties/container.json
- css/types/length.json
CSS (size) container queries enabled by default in Fx 110.
- Parent issue https://github.com/mdn/content/issues/23683
> relnote(Fx110): CSS container queries enabled by default in Fx110

- api/ContentVisibilityAutoStateChangedEvent.json
- api/Element.json
FF110 adds support for `ContentVisibilityAutoStateChangedEvent` object and the associated event `contentvisibilityautostatechanged_event` in https://bugzilla.mozilla.org/show_bug.cgi?id=1798485
As this means two browsers support the feature, it is also no longer experimental.
Other docs work can be tracked in https://github.com/mdn/content/issues/23687
> FF110 supports ContentVisibilityAutoStateChangedEvent

- css/properties/align-items.json
- css/properties/align-self.json
The `last baseline` alignment value is now implemented in all three engines. The data was a bit unwieldy as it represented the fact that for a time the value was parsed but didn't do anything in Chrome and Safari. I have just removed that information, but let me know if you want it back.
I've tested this: https://codepen.io/rachelandrew/pen/MWBKPrR/1ec83980993b3d01d160f9438fbfca4e 
- Safari release notes: https://developer.apple.com/documentation/safari-release-notes/safari-16_2-release-notes
- Chrome Status: https://chromestatus.com/feature/5093352798683136
> last baseline data

- css/types/color.json
`color-mix()` and `color()` are in Chrome 111.
https://chromestatus.com/feature/5147752829288448
> Chrome color functions

- api/RTCRtpEncodingParameters.json
`RTCRtpEncodingParameters` fixes
- `dtx` is marked as standard track, but is not in the standard.
-  `rid` had a note indicating "standard version in `RTCRtpCodecParameters`. Actually this is just in an undocumented parent class `RTCRtpCodingParameters`. That class has no independent existence so doesn't need docs, and this note isn't needed.
- This is also "standard" so marked it as such.
`fec`, `rtx`, `srcc` are all correctly marked as "non-standard". No docs on them, so not sure what value they add.
This is part of cleanup for https://github.com/mdn/content/issues/23677
> RTCRtpEncodingParameters.rid note is wrong

- api/RTCPeerConnection.json
- api/RTCRtpEncodingParameters.json
FF110 was brought up to spec around setting/getting parameters in https://bugzilla.mozilla.org/show_bug.cgi?id=1401592,  I'm splitting into bits because the code is a little complicated to review.
This PR covers:
- `RTCRtpEncodingParameters.active` 
- `RTCPeerConnection.addTransceiver()` supports `sendEncodings()` in init
Other docs work can be tracked in #23677
> FF110 RTCRtpEncodingParameters.active and RTCPeerConnection.addTransceiver() with sendEncodings

- api/ReadableStream.json
FF110 makes [ReadableStream](https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream) an async iterable in https://bugzilla.mozilla.org/show_bug.cgi?id=1734244. 
This means that you can iterate over a stream using the following construct:
```js
for await (const chunk of stream.values({ preventCancel: true })) { ... }
```
This is not supported in [chrome](https://bugs.chromium.org/p/chromium/issues/detail?id=929585) or [safari](https://bugs.webkit.org/show_bug.cgi?id=194379). Something similar appears to be in Nodejs and Deno, but not clear if that is "spec compliant". For now putting false.
Other docs for this can be tracked in https://github.com/mdn/content/issues/23678
> FF110 ReadableStream is Async Iterable

- browsers/chrome.json
See: https://developer.chrome.com/blog/early-stable/ and https://chromestatus.com/roadmap
> Update Chrome version

- css/at-rules/media.json
Support for @media query's color-gamut has been added in Firefox 110 via https://bugzilla.mozilla.org/show_bug.cgi?id=1422237
MDN page: https://developer.mozilla.org/en-US/docs/Web/CSS/@media/color-gamut
Doc issue tracker: https://github.com/mdn/content/issues/23681
> color-gamut is supported in FF110

- css/selectors/nth-child.json
_(👋 Hi, Chrome DevRel here!)_
Chrome 111 supports the “of S” syntax in `:nth-child`
- Chrome Platform Status: https://chromestatus.com/feature/5144225077788672
- Tracking Bug: https://bugs.chromium.org/p/chromium/issues/detail?id=304163
- Intent To Ship: https://groups.google.com/a/chromium.org/g/blink-dev/c/6zLouMDG4Eg
Note that the Chrome Platform Status currently reads “In developer trial (Behind a flag)”. This is incorrect and will get updated once the owner of the feature gets online. The last commit mentioned in the bug at https://bugs.chromium.org/p/chromium/issues/detail?id=304163#c40 confirms the feature is enabled by default. See https://chromium.googlesource.com/chromium/src/+/2fe97d46718cd42384ac6f3d507e33fb4b0f3045%5E%21/#F0 for the actual commit contents.
> Chrome 111 supports the “of S” syntax in `:nth-child`

- browsers/edge.json
Edge 110 is out since yesterday. Here is the corresponding change to the edge.json file.
> New Edge 110 release information

- html/elements/form.json
This PR is a reprise of #9130. Since then, all major browsers started supporting `<form rel>` attribute.
Tested with Safari for iOS 15.4, Firefox 111a1, Chrome 110.
* Safari
* https://github.com/WebKit/WebKit/commit/a644f4f84dbfc94edf09759b1fd8619941dd41e8 
* https://github.com/WebKit/WebKit/commit/82c4eeb93f2e140bf710266110410c66e9bc817d
* Firefox 
* https://bugzilla.mozilla.org/show_bug.cgi?id=1509346 
* https://www.mozilla.org/en-US/firefox/111.0a1/releasenotes/
* Chrome 
* https://chromestatus.com/feature/5139812343349248
* https://developer.chrome.com/blog/new-in-chrome-107/
See more details at #9130.
> Add <form rel> browser support data

- css/types/acos.json
- css/types/asin.json
- css/types/atan.json
- css/types/atan2.json
- css/types/cos.json
- css/types/sin.json
- css/types/tan.json
_(👋 Hi, Chrome DevRel here!)_
Chrome 111 supports the CSS trig functions `sin()`, `cos()`, `tan()`, `asin()`, `acos()`, `atan()`, and `atan2()`
- ChromeStatus: https://chromestatus.com/feature/5165381072191488
- Intent to Ship: https://groups.google.com/a/chromium.org/g/blink-dev/c/UiUVU722BbU/m/vQJy-qdpDAAJ
- Tracking Bug: https://bugs.chromium.org/p/chromium/issues/detail?id=1190444
> Chrome 111 supports the CSS trig functions

- browsers/nodejs.json
This PR adds NodeJS v12.6.0 to the browser data.  This will unblock #18737.
> Add NodeJS v12.6.0 to browser data

- .github/workflows/ping-other-repos.yml
This PR updates the `ping-other-repos` workflow to include comments and formatting just like what `mdn/content` has.
> Update ping-other-repos workflow

- webextensions/api/scripting.json
The first release with support for the scripting API is 102, not 101. This PR fixes that.
The first release with support for the scripting API is 102 - by https://bugzilla.mozilla.org/show_bug.cgi?id=1766615
The implementations landed before, but restricted to MV3, whose support was not enabled until Firefox 109 -
https://bugzilla.mozilla.org/show_bug.cgi?id=1801291
Also fixed the compat note for the persistAcrossSessions flag, whose implementation completed in
https://bugzilla.mozilla.org/show_bug.cgi?id=1751436
I already used the correct Firefox version in missing properties documented in #18878 .
> Correct supported Firefox versions of scripting API

- webextensions/api/scripting.json
Fixes the incorrect and incomplete BCD for the "world" parameter of the scripting.executeScript API.
References:
- "world" support introduced in Chrome 102 per https://chromium.googlesource.com/chromium/src/+/e5ad3451c17b21341b0b9019b074801c44c92c9f
- "world" + "ISOLATED" introduced in Firefox per https://bugzilla.mozilla.org/show_bug.cgi?id=1759932 While that bug was fixed in 100, the underlying feature was not available until it was enabled in MV2 - https://bugzilla.mozilla.org/show_bug.cgi?id=1766615
"MAIN" not supported yet in Firefox, part of https://bugzilla.mozilla.org/show_bug.cgi?id=1736575
Related to https://github.com/mdn/content/pull/24316 and https://github.com/mdn/content/issues/22493
> Add compatibility data for scripting.ExecutionWorld

- .github/workflows/ping-other-repos.yml
We should ping another repo when push commits to main branch of this repo, not mdn/content.
> fix(workflows): correct the target repo

- css/types/color.json
We moved it last year as part of our INTEROP2022 work.
> Fix MDN URL for keyword transparent

- api/FetchEvent.json
`Fetch.handled` is added to MDN in https://github.com/mdn/content/pull/24479
> Add mdn_url for FetchEvent.handled

- api/DocumentFragment.json
We are adding this missing page in mdn/content#24449.
This links it from bcd.
> Add mdn_url for DocumentFragment.getElementById

- javascript/builtins/ArrayBuffer.json
- javascript/builtins/SharedArrayBuffer.json
This PR adds the new features related to the [Resizable ArrayBuffer and growable SharedArrayBuffer](https://tc39.es/proposal-resizablearraybuffer/) Stage 3 draft, which was implemented in Chrome 111+.
See my [research document](https://docs.google.com/document/d/1qMC0URMTqhf5EeAuVwvYhe9pQ_SbooHVI0XcDsyYdFU/edit#) for exact details of what has been added, and other required work.
> Add new features for resizable ArrayBuffer and growable sab

- html/elements/input/color.json
Support for `list` attribute of `<input type="color">` element has been added in Firefox 110 via https://bugzilla.mozilla.org/show_bug.cgi?id=960984.
However, this fix only adds support in Firefox on Windows and Linux.
The implementation on Android and macOS is still pending (https://bugzilla.mozilla.org/show_bug.cgi?id=1805397).
This pull request makes the following changes:
- For the ["type_color.list" entry in the BCD table](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#browser_compatibility):
- adds partial implementation flag with link to the bug 960984 for "firefox". The note also calls out the current support in Windows and Linux only.
- replaces `"mirror"` with `"version_added": false` for "firefox_android" and adds link to the related bug (1805397).
I am hoping …
> Add partial support for input type color list attribute in FF110

- api/StorageManager.json
FF111 turns on the `dom.fs.enabled` preference in https://bugzilla.mozilla.org/show_bug.cgi?id=1811001 (in FF110 this was added in #18723)
Other docs work for this can be tracked in #24388
FYI @queengooborg Dunno if you want to hold off on merging this since FF110 just came out, and FF111 isn't released until next month.
> FF111 OPFS Released

- api/RTCRtpContributingSource.json
- api/RTCRtpSynchronizationSource.json
FF99 lost the config option `media.peerconnection.rtpsourcesapi.enable` https://bugzilla.mozilla.org/show_bug.cgi?id=1749802 
But I bisected and this showed that this was ALWAYS set true - ie. the preference was pointless. Checked later and earlier versions.
Discovered while looking into https://github.com/mdn/content/issues/24397
> FF99 Remove pref media.peerconnection.rtpsourcesapi.enable

- api/Navigator.json
This PR updates the data for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `share` member of the `Navigator` API.  I had run some tests in Linux, macOS and Windows on both Chrome and Edge, and determined that non-Windows support for `navigator.share` is still not available.  (See https://crbug.com/770595 for confirmation.)  It appears that this data was updated in #14871,, but it turns out thaat macOS support is only available on Edge, not standard Chrome.  This fixes #16823, fixes #18340, fixes #18806, fixes #18168, fixes #11388.
> Update Chromium versions for api.Navigator.share

- api/WebGLRenderingContext.json
This PR adds real values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `canvas` member of the `WebGLRenderingContext` API, based upon manual testing.
Test Code Used: https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/canvas#offscreen_canvas
Fixes #18752.
> Add Chromium versions for api.WebGLRenderingContext.canvas

- svg/elements/title.json
This PR adds real values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `tooltip_display` member of the `title` SVG element, based upon manual testing.
Test Code Used: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/title
Fixes #5893.
> Add Chromium versions for svg.elements.title.tooltip_display

- css/properties/hyphens.json
This PR updates the subfeatures for the `hyphens` CSS property in two ways:
- Adds an `auto_value` property, moving the data from notes to this property (fixes #8809)
- Prefixes all languages with `language_` to keep them together in sorting whilst adding a bit more description to the keys
> Update subfeatures for css.properties.hyphens

- api/MediaDevices.json
This PR updates the notes for `MediaDevices.getDisplayMedia()` to better reflect the history of the method on Android, should we ever use automated testing to determine their support.  Fixes #8821.
> Update notes for api.MediaDevices.getDisplayMedia

- html/elements/input/range.json
This PR adds real values for Safari (Desktop and iOS/iPadOS) for the `type_range.tick_marks` member of the `input` HTML element, based upon manual testing.
Test Code Used: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/range#adding_tick_marks
FIxes #9867.
> Add Safari versions for html.elements.input.type_range.tick_marks

- css/types/image.json
This PR adds real values for Safari (Desktop and iOS/iPadOS) for the `gradient.radial-gradient.at` member of the `image` CSS type, based upon manual testing.
Test Code Used: `background: radial-gradient(ellipse at top, #e66465, transparent), radial-gradient(ellipse at bottom, #4d9f0c, transparent);`
Fixes #10015.
> Add Safari versions for css.types.image.gradient.radial-gradient.at

- javascript/builtins/WebAssembly/Memory.json
This PR adds real values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `shared` member of the `WebAssembly.Memory` JavaScript builtin.  This fixes #10543, which is where the data comes from.
> Add Chromium versions for javascript.builtins.WebAssembly.Memory.shared

- css/properties/tab-size.json
This PR adds real values for Safari (Desktop and iOS/iPadOS) for the `length` member of the `tab-size` CSS property.  The data comes from https://caniuse.com/css3-tabsize.  Fixes #10642.
> Add Safari versions for css.properties.tab-size.length

- css/properties/list-style-type.json
This PR adds real values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `disclosure-closed/disclosure-open` members of the `list-style-type` CSS property.  This fixes #11131, which is where the data comes from.
> Add Chromium versions for css.properties.list-style-type.disclosure-closed/disclosure-open

- api/KeyboardEvent.json
This PR adds a note stating that the Windows key is no longer treated as the meta key starting with Firefox 48.  Fixes #11537.
> Add note regarding Windows key not being meta key in KeyboardEvent

- css/properties/gap.json
This PR adds real values for Safari (Desktop and iOS/iPadOS) for the `multicol_context` member of the `gap` CSS property.  This PR fixes #11165, which is where the data comes from.
> Add Safari versions for css.properties.gap.multicol_context

- api/ContentVisibilityAutoStateChangeEvent.json
- api/Element.json
- css/properties/content-visibility.json
Fixes #18849
This updates `content-visibility` and the associated change event behind the preference `layout.css.content-visibility.enabled`, as reported in #18849 (and tested).
That makes the APIs experimental too, as are only implemented in Chromium on release builds by default.
This affects:
- https://github.com/mdn/content/issues/23687
- https://github.com/mdn/content/issues/22736
- #18848
> FF CSS content-visibility behind pref

- webextensions/api/tabs.json
A few apis are missing correct values for the `version_added` field.
https://web.archive.org/web/20090918121259/http://code.google.com/chrome/extensions/tabs.html
https://web.archive.org/web/20160701175838if_/https://developer.chrome.com/extensions/tabs#type-MutedInfo
https://web.archive.org/web/20160701175838if_/https://developer.chrome.com/extensions/tabs#properties
https://web.archive.org/web/20160701175838if_/https://developer.chrome.com/extensions/tabs#property-Tab-active
https://web.archive.org/web/20160701175838if_/https://developer.chrome.com/extensions/tabs#property-Tab-highlighted
https://web.archive.org/web/20160701175838if_/https://developer.chrome.com/extensions/tabs#method-duplicate
https://web.archive.org/web/20180706052022/https://developer.chrome.com/extensions/whats_new …
> Add more Chrome & Firefox version numbers for tabs webextensions API

- api/ContentVisibilityAutoStateChangeEvent.json
- api/Element.json
This is a followup for https://github.com/mdn/browser-compat-data/pull/18848
The CSSWG updaed the css-contain-2 editors' draft to incorporate name change I raised
https://github.com/mdn/browser-compat-data/issues/18847
https://github.com/w3c/csswg-drafts/pull/8413
The TR/contain-2 version updates less than Editors' drafts on GH. So I switched to the GH Pages link.
> update spec link for `contentvisibilityautostatechange` event to refer to W3C specs mirror on GitHub Pages

- api/ContentVisibilityAutoStateChangeEvent.json
This is a followup for https://github.com/mdn/browser-compat-data/pull/18848
Now MDN has updated their pages to use the past tense event names.
https://github.com/mdn/content/pull/24263
This updates links to those "d"-less pages.
> update link to MDN `ContentVisibilityAutoStateChangeEvent` pages

- html/elements/thead.json
This PR adds a note regarding backgrounds applied to `<thead>` elements.  Fixes #5753.
> Add a note regarding backgrounds applied to `<thead>` elements

- svg/attributes/presentation.json
This PR adds real values for Chrome, Safari and Firefox for the `vector-effect` member of the `presentation` SVG attributes.  The data comes from https://caniuse.com/vector-effect, and the Chrome version was guesstimated based upon engine version.  (I don't have access to my older VMs at the moment.)  Fixes #6022.
> Add versions for svg.attributes.presentation.vector-effect

- css/properties/background-clip.json
This PR fixes #18884 by removing an incorrect note.  The note claims that text decorations and shadows aren't accounted by the property, but the blog it links to says the _exact opposite._
> Remove erroneous note from css.properties.background-clip.text

- html/elements/template.json
In Chrome 111 the `shadowroot` attribute for `<template>` has been renamed to `shadowrootmode` to match the updated spec.
I've updated BCD here, making `shadowroot` an alternative name, and I'll add updating the docs to our worklist.
https://chromestatus.com/feature/5161240576393216
> shadowroot to shadowrootmode

- api/AudioContext.json
This PR updates and corrects version values for Firefox and Firefox Android for the `AudioContext.options_latencyHint_parameter` member of the `AudioContext` API, based upon results from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v8.0.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/AudioContext/AudioContext.options_latencyHint_parameter
> Update Firefox versions for api.AudioContext.AudioContext.options_latencyHint_parameter

- api/AudioContext.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `AudioContext.options_latencyHint_parameter` member of the `AudioContext` API, based upon results from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v8.0.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/AudioContext/AudioContext.options_latencyHint_parameter
---
Note: "14.1" is guesstimated from the collector's report of "13.1> ≤14.1", as I don't have access to Safari 14.0 at the moment.
> Update Safari versions for api.AudioContext.AudioContext.options_latencyHint_parameter

- browsers/safari.json
- browsers/safari_ios.json
Per @queengooborg's request, split from #18963.
> Add Safari 16.4 for macOS and iOS as browsers

- webextensions/api/webRequest.json
This PR adds the missing features for the `webRequest.ResourceType` webextensions API.  Fixes #1655.
(Note: all version numbers are speculative and are not confirmed.)
> Add missing subfeatures to webextensions.api.webRequest.ResourceType

- api/Document.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `securitypolicyviolation_event` member of the `Document` API, based upon results from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v8.0.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/Document/securitypolicyviolation_event
> Update Safari versions for api.Document.securitypolicyviolation_event

- webextensions/api/runtime.json
runtime.onSuspend was implemented in Firefox 100.
See [Bug 1753850](https://bugzilla.mozilla.org/show_bug.cgi?id=1753850)
> runtime.onSuspend implemented in Firefox

- browsers/samsunginternet_android.json
This PR marks Samsung Internet 20.0 as the current version of Samsung Internet.  The date comes from [UpToDown](https://internet.en.uptodown.com/android), whereas the Chrome version comes from the user agent string.
> Samsung Internet 20.0 is released

- webextensions/api/dom.json
See: https://github.com/mdn/browser-compat-data/pull/17707#discussion_r963972701
> Firefox does not expose `browser.dom`

- webextensions/api/browsingData.json
[Bug 1363010](https://bugzilla.mozilla.org/show_bug.cgi?id=1363010) was closed as a duplicate of [Bug 1625233](https://bugzilla.mozilla.org/show_bug.cgi?id=1625233), which added Android support for the `browsingData` APIs in Firefox 85.
> Fix `browsingData.removeHistory()` for Firefox for Android

- api/Element.json
Adds compat data describing whether `click`, `auxclick`, and `contextmenu` events are `MouseEvent`s or `PointerEvent`s.
The spec changed the type of these events from `MouseEvent` to `PointerEvent` in w3c/pointerevents#317.
[Chromium feature page](https://chromestatus.com/feature/5670732015075328).
[Webkit tracking bug](https://webkit.org/b/218665).
[Firefox tracking bug](https://bugzil.la/1675847).
> Add subfeature for the type of `click`, `auxclick`, `contextmenu` events

- webextensions/api/browsingData.json
While the option might not be doing much, it is definitely a supported property in `RemovalOptions` (and it might be already working with private browsing mode).
> RemovalOptions.cookieStoreId is supported on Firefox for Android

- api/Document.json
- api/ViewTransition.json
- css/properties/view-transition-name.json
- css/selectors/view-transition-group.json
- css/selectors/view-transition-image-pair.json
- css/selectors/view-transition-new.json
- css/selectors/view-transition-old.json
- css/selectors/view-transition.json
This PR adds compat data for the [View Transitions Module Level 1](https://www.w3.org/TR/css-view-transitions-1/), which is available in Chrome 111+.
See my [research document](https://docs.google.com/document/d/1EtWDm0UAvEu4qIO0sPd035I9mbRDYV39fTti04FxvtI/edit#) for more information on exactly what this work entails.
> Add data for the View Transitions API Level 1

- test/linter/test-versions.ts
This PR adds ranged values of ≤15 and ≤37 to Chrome.  These are the lowest versions available on BrowserStack and SauceLabs.
> Add ranged values for Chrome

- api/HTMLElement.json
This PR removes the irrelevant `contextMenu` member of the `HTMLElement` API as per the corresponding [data guidelines](https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines.md#removal-of-irrelevant-features). The lack of current support has been confirmed by the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v8.0.0), even if the current BCD suggests support.
> Remove api.HTMLElement.contextMenu from BCD

- api/Element.json
This PR removes the irrelevant `show_event` member of the `Element` API as per the corresponding [data guidelines](https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines.md#removal-of-irrelevant-features). The lack of current support has been confirmed by the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v8.0.0), even if the current BCD suggests support.
> Remove api.Element.show_event from BCD

- api/HTMLElement.json
- html/global_attributes.json
`autocapitalize` attribute is fully supported in FF111
Bug tracker: https://bugzilla.mozilla.org/show_bug.cgi?id=1692007
MDN page: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/autocapitalize#browser_compatibility
Doc issue tracker: https://github.com/mdn/content/issues/24401
`translate` attribute attribute is supported in FF111
Bug tracker: https://bugzilla.mozilla.org/show_bug.cgi?id=1418449
MDN page: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/translate#browser_compatibility
Doc issue tracker: https://github.com/mdn/content/issues/24394
> autocapitalize and translate attributes are supported in FF111

- svg/attributes/presentation.json
__Background:__
SVG elements can use `stroke="context-stroke" fill="context-fill"` in Fx 111
__Related issues and bugs:__
__Bugzilla:__
- https://bugzilla.mozilla.org/show_bug.cgi?id=752638
> relnote(Fx111): context-fill and context-stroke values supported in SVG fill and stroke attribs

- css/types/color.json
CSS color functions enabled behind a pref (`layout.css.more_color_4.enabled`) in Fx 111
__Additions:__
* color() 
* lab()
* lch()
* oklab()
* oklch() 
- Parent issue https://github.com/mdn/content/issues/24395
__Bugzilla:__
- `color()` https://bugzilla.mozilla.org/show_bug.cgi?id=1128204
- `lab()`, `lch()`, `oklab()`, `oklch()` https://bugzilla.mozilla.org/show_bug.cgi?id=1352757
> relnote(Fx111): color(), lab(), lch(), oklab(), oklch() support

- webextensions/api/browserSettings.json
All but `closeTabsByDoubleClick` are supported in Android since they have been implemented at the same time as Desktop.
> Fix browser.browserSettings for Firefox for Android

- api/CSSTransition.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `CSSTransition` API, based upon results from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v7.1.3).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/CSSTransition
---
This data was originally set to "78" in #6372.  This data had come from reading through the IDL and using commit history to determine when the feature was implemented (see https://github.com/mdn/browser-compat-data/pull/6372#discussion_r459623074).  Since Edge was set to "84" in #9190, it makes less sense to keep Chrome at "78".
> Update Chromium versions for CSSTransition API

- webextensions/manifest/background.json
Adds the `"type"` property to the `"background"` manifest key.
Addresses the documentation requirements for [Bug 1811443](https://bugzilla.mozilla.org/show_bug.cgi?id=1811443).
Related MDN in changes in https://github.com/mdn/content/pull/25094.
> Add type to the manifest background key

- api/_globals/fetch.json
FF111 strips the `Authorization` header added by developers from cross-origin redirects - see https://bugzilla.mozilla.org/show_bug.cgi?id=1802086. This adds a feature to the `fetch()` entry.
This was tested with https://wpt.live/fetch/api/credentials/authentication-redirection.any.worker.htm - the first test should show that the header is not stripped from a normal response, the second that it is not stripped from a same-origin redirect, and the third that it is from a cross-origin redirect.
Note that Safari is "accidentally" compliant in 15.4 because it strips the authorization header in both cases. Safari 16.1 on browserstack does the "right thing" for all cases. So I have indicated Safari 16.1 because it more closely reflects the expected behaviour with this header on redirect.
I …
> FF111 fetch() remove Authorization header on cross origin redirects

- api/Worker.json
- javascript/statements.json
FF111 supports module loading from workers in https://bugzilla.mozilla.org/show_bug.cgi?id=1247687
This updates the existing support statements. 
Other docs work for this can be tracked in https://github.com/mdn/content/issues/24402
> Ff111 implements workers modules

- css/types/color.json
Chrome 111 implements CSS Color 4 with `oklch()`, `oklab()`, `lch()`, and `lab()`. [Changelog](https://developer.chrome.com/blog/new-in-chrome-111/#css-color-level4)
I also removed `Experimental` flag because CI [told me](https://github.com/mdn/browser-compat-data/actions/runs/4359619533/jobs/7621601320).
[WPT results](https://wpt.fyi/results/css/css-color?label=master&label=experimental&aligned=&view=subtest&q=oklch)
Fixes #19067
> Chrome 111: Add oklch(), oklab(), lch(), lab() support

- http/headers/X-Frame-Options.json
Spec link for the X-Frame-Options HTTP header is wrong (outdated). I have fixed the link.
Cf. [the current link target](https://html.spec.whatwg.org/multipage/browsing-the-web.html#the-x-frame-options-header) and the [updated target](https://html.spec.whatwg.org/multipage/document-lifecycle.html#the-x-frame-options-header)
> Update X-Frame-Options spec link

- api/SVGStyleElement.json
The Safari value got changed in #18963, but not the iOS value. This is an oversight.
This attribute got added in https://github.com/WebKit/WebKit/commit/737ccae0f4676feb85291509f4691a2235658104.
Its prior, incorrect documentation, dates from the big _mixins removal, which was wrong as WebKit didn't previously implement this as a mixin.
> Update api.SVGStyleElement.sheet on iOS

- api/_globals/fetch.json
- browsers/chrome.json
- browsers/chrome_android.json
- browsers/webview_android.json
Hi all! 
This PR updates Chrome to version 111.
And according to https://chromiumdash.appspot.com/schedule, also includes the new release dates.
> Updates chrome to version 111

- browsers/opera.json
This PR marks Opera 96 as the current version of Opera Desktop.
> Opera 96 is released

- api/Clients.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `matchAll.options_includeUncontrolled_parameter` member of the `Clients` API, based upon results from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v8.0.1).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/Clients/matchAll/options_includeUncontrolled_parameter
> Update Chromium versions for api.Clients.matchAll.options_includeUncontrolled_parameter

- api/AudioContext.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `AudioContext.options_latencyHint_parameter` member of the `AudioContext` API, based upon results from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v8.0.1).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/AudioContext/AudioContext.options_latencyHint_parameter
> Update Chromium versions for api.AudioContext.AudioContext.options_latencyHint_parameter

- api/EXT_texture_compression_bptc.json
This PR updates and corrects version values for Safari iOS/iPadOS for the `EXT_texture_compression_bptc` API, based upon results from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v8.0.1).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/EXT_texture_compression_bptc
> Update Safari iOS versions for EXT_texture_compression_bptc API

- api/FontFace.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `display` member of the `FontFace` API, based upon results from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v7.1.5).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/FontFace/display
> Update Safari versions for api.FontFace.display

- api/HTMLMenuElement.json
This PR removes the irrelevant `label` member of the `HTMLMenuElement` API as per the corresponding [data guidelines](https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines.md#removal-of-irrelevant-features). The lack of current support has been confirmed by the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v8.0.0), even if the current BCD suggests support.
> Remove api.HTMLMenuElement.label from BCD

- api/AudioContext.json
- api/MediaStreamAudioDestinationNode.json
This PR corrects the data for both `AudioContext.createMediaStream*` methods, as well as `MediaStreamAudioDestinationNode`, based upon results from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v7.1.5).
> Correct data for AudioContext.createMediaStream* and MediaStreamAudioDestinationNode

- api/Worker.json
- javascript/statements.json
There is a note in [`Worker`](https://developer.mozilla.org/en-US/docs/Web/API/Worker):
Following the bug you start to see support for nested workers in 15.5 - https://webkit.org/blog/13338/release-notes-for-safari-technology-preview-155/ and in 16.4 it looks like there were some other fixes that are relevant: https://developer.apple.com/documentation/safari-release-notes/safari-16_4-release-notes
There _might_ be more, but they are definitely supported in 15.5 and looks like it might be pretty much full support now.
Anyway, I have added this information as notes. Not sure if this is "correct enough". Should I make the original entry a partial implementation and have a separate "full support" entry at 15.5?
FYI @queengooborg 
This fell out of work in …
> Add compatibility note about Safari's support for nested workers

- api/XRSession.json
This PR is a part of a project to add missing interfaces and interface features to BCD that are from an active spec (including WICG specs) and is supported in at least one browser.  This particular PR adds the missing `enabledFeatures` member of the XRSession API, populating the results using data from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v8.1.1).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/XRSession/enabledFeatures
> Add missing api.XRSession.enabledFeatures feature

- api/MutationEvent.json
We add these missing pages in mdn/content#25251. This PR adds the missing `mdn_url` field.
> Add mdn_url for members of MutationEvent

- api/FileSystemDirectoryHandle.json
- api/FileSystemFileHandle.json
- api/FileSystemHandle.json
- api/FileSystemSyncAccessHandle.json
- api/FileSystemWritableFileStream.json
FF111 added support for OPFS in https://bugzilla.mozilla.org/show_bug.cgi?id=1811001. I added the main API in #18907 but it never occurred to me that the rest of the file system around this was not supported. So as per https://bugzilla.mozilla.org/show_bug.cgi?id=1811001#c11 this updates the interfaces in the File System Access API to indicate they are also supported.
- FileSystemWritableFileStream
- FileSystemDirectoryHandle
- FileSystemFileHandle
- FileSystemFileHandle
- FileSystemSyncAccessHandle
Note, WritableStream is already marked as  supported from FF100
@saschanaz Can you confirm this issue delivers full support for the API / that this is the right set of things to mark as supported in FF111?
> Ff111 More OPFS related updaes

- api/SVGElement.json
This PR adds real values for Firefox and Firefox Android for the `autofocus` member of the `SVGElement` API.  This fixes #18843.
> Add Firefox versions for api.SVGElement.autofocus

- api/FormData.json
Add data for the new submitter parameter to the FormData constructor (FF 111, Chrome 112, Safari 16.4)
Here's what it looks like on the FormData constructor MDN page (goes with [this PR](https://github.com/mdn/content/pull/23950)):
Although it's experimental as of 2023-03-12, it will be live in Firefox on 2023-03-14 and Chrome on 2023-04-04.
Spec: https://xhr.spec.whatwg.org/#interface-formdata
Firefox: [Issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1812696), [Implementation](https://phabricator.services.mozilla.com/D167576)
Chrome: [Issue](https://bugs.chromium.org/p/chromium/issues/detail?id=1410542), [Implementation](https://chromium.googlesource.com/chromium/src/+/df5176aa228dc06e693a799d595ee95d68dcab0d), [Feature entry](https://chromestatus.com/feature/5066604734316544) …
> Add FormData constructor submitter parameter

- api/CSSContainerRule.json
This PR is a part of a project to add missing interfaces and interface features to BCD that are from an active spec (including WICG specs) and is supported in at least one browser.  This particular PR adds the missing features of the CSSContainerRule API, populating the results using data from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v8.1.1).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/CSSContainerRule
> Add missing features for CSSContainerRule API

- api/CSSFontFeatureValuesRule.json
This PR is a part of a project to add missing interfaces and interface features to BCD that are from an active spec (including WICG specs) and is supported in at least one browser.  This particular PR adds the missing features of the CSSFontFeatureValuesRule API, populating the results using data from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v8.1.1).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/CSSFontFeatureValuesRule
> Add missing features for CSSFontFeatureValuesRule API

- javascript/operators/import.json
Firefox does not support dynamic module imports in workers - see https://bugzilla.mozilla.org/show_bug.cgi?id=1540913 (and discussion in  https://github.com/mdn/browser-compat-data/pull/19044 ).
This adds a worker support feature to `import()` and sets FF to false with a bug link.
EDITED The rest was copied from the worker support for static imports. 
Can you advise on a WPT test that I run to test dynamic import support for the other platforms (and are you aware of any others that do not have this support)?
This follows on from work in https://github.com/mdn/content/issues/24402
> FF does not support dynamic module import in workers

- css/properties/border-end-end-radius.json
- css/properties/border-end-start-radius.json
- css/properties/border-start-end-radius.json
- css/properties/border-start-start-radius.json
Opera Android supports `border-start-start-radius`, `border-start-end-radius`, `border-end-start-radius` and `border-end-end-radius` starting with version 63 (chromium 89)
> Fix Opera Android version of border-radius properties

- webextensions/api/scripting.json
Adds Safari 16.4 support for RegisteredContentScripts.
See [Safari 16.4 Beta Release Notes](https://developer.apple.com/documentation/safari-release-notes/safari-16_4-release-notes#Safari-Extensions).
> Add Safari 16.4 support for RegisteredContentScripts

- api/FileSystemFileHandle.json
- api/FileSystemHandle.json
- browsers/opera_android.json
- mathml/elements/math.json
This PR marks Opera Android 74 as released.  Release date comes from the Play Store, and Chrome version comes from the user agent string.
> Opera Android 74 is released

- browsers/edge.json
Edge 111 is out, and the edge.json was just updated in BCD. This PR is a quick follow-up to fix the 108 release note links. Release note links get updated when releases are too old (they move to an archive page instead).
> Fixed edge 108 release notes (now archived)

- api/CSSFontFeatureValuesRule.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `CSSFontFeatureValuesRule` API, based upon results from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v8.1.1).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/CSSFontFeatureValuesRule
> Update Chromium versions for CSSFontFeatureValuesRule API

- api/DOMTokenList.json
This PR is a part of a project to add missing interfaces and interface features to BCD that are from an active spec (including WICG specs) and is supported in at least one browser.  This particular PR adds the missing `toString` member of the DOMTokenList API, populating the results using data from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v8.1.1).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/DOMTokenList/toString
> Add missing api.DOMTokenList.toString feature

- api/XMLHttpRequest.json
- http/headers/Authorization.json
FF111 strips the `Authorization` header added by developers from cross-origin redirects in fetch(), XMLHttpRequest, and more generally theHTTP channel - see: https://bugzilla.mozilla.org/show_bug.cgi?id=1802086. 
The `fetch()` changes were done in #19064 . This duplicates the exactly the same info for XMLHttpRequest and `Authorization`. That makes sense because these build on fetch(), as per response in https://github.com/mdn/content/issues/22533#issuecomment-1458256595
.
Other docs work for this can be tracked in https://github.com/mdn/content/issues/22533
> FF111 XMLHttpRequest/HTTP channel - strip Authorization  on cross-origin redirect

- api/CSPViolationReportBody.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `toJSON` member of the `CSPViolationReportBody` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v8.1.2).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/CSPViolationReportBody/toJSON
> Update Chromium data for api.CSPViolationReportBody.toJSON

- docs/data-guidelines/api.md
Requested by https://github.com/mdn/browser-compat-data/pull/19093#discussion_r1134751582.  This PR adds documentation on what to do when a `stringifier` attribute is found.
> Document what to do with stringifier attributes

- api/NodeList.json
[`NodeList.forEach`](https://developer.mozilla.org/en-US/docs/Web/API/NodeList/forEach#specifications) has no spec, which is a bit ugly in the docs. The reason is that `forEach` and `@@iterator` are implied because NodeList is and iterable.
There is literally nowhere to link to in NodeList in the spec https://dom.spec.whatwg.org/#nodelist to point to iterable. We could link to NodeList itself but that would look like a typo.
So my proposal is that we link to the Web IDL spec for both of these: https://webidl.spec.whatwg.org/#idl-iterable - see the text:
> n the ECMAScript language binding, an interface that is iterable will have entries, forEach, keys, values, and [@@iterator](https://tc39.es/ecma262/#sec-well-known-symbols) properties on its [interface prototype …
> NodeList - spec link for forEach and @@iterator

- api/SVGAnimateElement.json
- api/SVGAnimateTransformElement.json
- api/SVGAnimatedBoolean.json
- api/SVGAnimatedInteger.json
- api/SVGAnimatedNumberList.json
- api/SVGAnimationElement.json
- api/SVGNumberList.json
- api/SVGSVGElement.json
- api/SVGSetElement.json
- svg/elements/set.json
I recently overhauled all of my Chrome VMs to replace the Chromium builds with official Chrome releases, which affects Chrome 1-15 results submitted to the collector. This PR is a cherry-pick of #19145 that updates the SVG element interfaces.
Note: the data for the `<set>` SVG element was originally copied over from the API data (see #9510).  It has been re-copied in this PR.
> Fix Chrome 1-15 data for SVG element APIs

- api/Clients.json
This PR updates and corrects version values for Firefox and Firefox Android for the `matchAll.options_includeUncontrolled_parameter` member of the `Clients` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v8.1.2).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/Clients/matchAll/options_includeUncontrolled_parameter
Additional Notes: This also removes the note included for the feature as it has no purpose.
> Update Firefox data for api.Clients.matchAll.options_includeUncontrolled_parameter

- api/CSSPageRule.json
This PR updates and corrects version values for Firefox and Firefox Android for the `selectorText` member of the `CSSPageRule` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v8.1.2).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/CSSPageRule/selectorText
> Update Firefox data for api.CSSPageRule.selectorText

- api/CanvasRenderingContext2D.json
This PR updates and corrects version values for Microsoft Edge for the `CanvasRenderingContext2D` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v8.1.2).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/CanvasRenderingContext2D
> Update Edge data for CanvasRenderingContext2D API

- api/Clients.json
This PR updates and corrects version values for Microsoft Edge for the `matchAll.options_includeUncontrolled_parameter` member of the `Clients` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v8.1.2).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/Clients/matchAll/options_includeUncontrolled_parameter
> Update Edge data for api.Clients.matchAll.options_includeUncontrolled_parameter

- api/HTMLCanvasElement.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `getContext.bitmaprenderer_context` member of the `HTMLCanvasElement` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v8.1.2).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/HTMLCanvasElement/getContext/bitmaprenderer_context
> Update Safari data for api.HTMLCanvasElement.getContext.bitmaprenderer_context

- api/Element.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `requestFullscreen.returns_promise` member of the `Element` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v8.1.2).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/Element/requestFullscreen/returns_promise
> Update Chromium data for api.Element.requestFullscreen.returns_promise

- api/CSSKeyframesRule.json
This PR updates and corrects version values for Firefox and Firefox Android for the `appendRule` member of the `CSSKeyframesRule` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v8.1.2).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/CSSKeyframesRule/appendRule
> Update Firefox data for api.CSSKeyframesRule.appendRule

- api/CSSPageRule.json
This PR updates and corrects version values for Firefox and Firefox Android for the `CSSPageRule` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v8.1.2).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/CSSPageRule
Additional Notes: The `@page` rule itself (at `css.at-rules.page`) states Firefox 19 as well, so Firefox 1 and 12 doesn't seem accurate.
> Update Firefox data for CSSPageRule API

- api/Element.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `scrollIntoView.options_parameter` member of the `Element` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v8.1.2).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/Element/scrollIntoView/options_parameter
Additional Notes: "14" was guesstimated from "13.1> ≤14.1", as I don't currently have access to Safari 14.
> Update Safari data for api.Element.scrollIntoView.options_parameter

- svg/elements/animateMotion.json
- svg/elements/animateTransform.json
- svg/elements/set.json
This copies some version numbers from the corresponding SVG*Element
interfaces. It's always possible the markup was supported before the
APIs, but this is too far back in time to warrant investigation.
> Update SVG element data from the corresponding APIs

- browsers/firefox.json
- browsers/firefox_android.json
This PR updates Firefox to version 111
* https://www.mozilla.org/en-US/firefox/111.0/releasenotes/
* https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/111
> Update firefox to version 111

- api/HTMLCanvasElement.json
- api/ImageBitmapRenderingContext.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `getContext.bitmaprenderer_context` member of the `HTMLCanvasElement` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v8.1.2).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/HTMLCanvasElement/getContext/bitmaprenderer_context
> Update Chromium data for api.HTMLCanvasElement.getContext.bitmaprenderer_context

- api/Navigator.json
This PR adds a note about `navigator.doNotTrack` behaving differently than the specification in Firefox.
See discussion in: https://github.com/mdn/content/pull/25310#discussion_r1136345176
Related PR in `mdn/content`: https://github.com/mdn/content/pull/25446
> Add note about `navigator.doNotTrack` return value in Firefox

- api/CSSContainerRule.json
Ran `CSSContainerRule` test code and found that edge 111 does appear to mirror the containerQuery and containerName properties of `CSSContainerRule`.
BUT, only in the 111 latest on browserstack - the beta and dev do not show these values. This also works on my local testing.
However opera in 96/97 with corresponding engine 96=111 does not appear to support this feature. I have no idea why it would not though!
FYI @queengooborg 
Related docs work in https://github.com/mdn/content/issues/25398
> CSSContainerRule - chromiums appear to mirror - edge 111

- api/Document.json
- api/PerformanceNavigationTiming.json
This PR is a part of a project to add missing interfaces and interface features to BCD that are from an active spec (including WICG specs) and is supported in at least one browser.  This particular PR adds the missing `prerendering` and `prerenderingchange_event` members of the Document API, as well as the `activationStart` member of the PerformanceNavigationTiming API, populating the results using data from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v7.1.4).
Tests Used:
https://mdn-bcd-collector.gooborg.com/tests/api/Document/prerendering
https://mdn-bcd-collector.gooborg.com/tests/api/Document/prerenderingchange_event
https://mdn-bcd-collector.gooborg.com/tests/api/PerformanceNavigationTiming/activationStart
_Check out the [collector's guide on how to review …
> Add missing Prerendering Revamped spec features

- css/properties/scroll-timeline-axis.json
- css/properties/scroll-timeline-name.json
- css/properties/scroll-timeline.json
The shorthand and longhand properties, [scroll-timeline](https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-timeline), [scroll-timeline-name](https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-timeline-name),
[scroll-timeline-axis](https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-timeline-axis), are still behind a preference but the flag name was changed in Fx110 because of the change in spec. 
Flag name before: `layout.css.scroll-linked-animations.enabled`
Flag name now: `layout.css.scroll-driven-animations.enabled`
via https://bugzilla.mozilla.org/show_bug.cgi?id=1807685
(The flag name was changed in Fx110 but other changes requiring content updates happened in Fx111.)
- Fx111 Doc issue tracker: https://github.com/mdn/content/issues/24396 (bugzilla: …
> Fx110: flag name change for scroll-timeline shorthand and longhand properties

- api/CanvasRenderingContext2D.json
- api/OffscreenCanvasRenderingContext2D.json
- api/Path2D.json
FF112 supports [CanvasRenderingContext2D/roundRect()](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/roundRect#result) in https://bugzilla.mozilla.org/show_bug.cgi?id=1756175
This applies to the same method in OffscreenCanvas2d and path2D. The offscreen support wasn't obvious from the issue (to me) but is obvious when you run the offscreen path roundrect tests in FF111 vs FF112 http://wpt.live/html/canvas/offscreen/path-objects/
Other docs work can be tracked in https://github.com/mdn/content/issues/25359
> FF112 supports roundRect() on Canvas2D

- api/Navigator.json
FF112 enables `navigator.getAutoplayPolicy()` by default in https://bugzilla.mozilla.org/show_bug.cgi?id=1812189
This removes the pref and changes the preview version to 112.
Related docs work can be tracked in https://github.com/mdn/content/issues/25362
> FF112 navigator.getAutoplayPolicy() enabled on release

- api/HTMLElement.json
- html/global_attributes.json
Added the version added for the inert Global_attribute and HTMLElement Web API
N/A
[Bugzilla bug 1764263](https://bugzilla.mozilla.org/show_bug.cgi?id=1764263)
[Content Issue 25356](https://github.com/mdn/content/issues/25356)
Content PR - Coming soon
Release Notes PR - Coming soon
> added the version added for inert for Firefox 112

- api/CSSLayerBlockRule.json
We added these two pages on MDN earlier this Quarter.
> Add missing mdn_url in CSSLayerBlockRule.json

- api/CSSLayerStatementRule.json
We created these two pages on MDN earlier this Quarter.
> Add missing mdn_url entries in CSSLayerStatementRule.json

- api/PaymentResponse.json
This missing page got added earlier this Quarter.
> Add missing mdn_url in PaymentResponse.json

- api/PerformanceTiming.json
There was one missing in this interface.
> Add missing mdn_url in PerformanceTiming.json

- api/CSSContainerRule.json
Hamish added them in https://github.com/mdn/content/pull/25493.
> Add missing mdn_urls in CSSContainerRule.json

- api/XSLTProcessor.json
This page got added on MDN yesterday.
> Add missing mdn_url in XSLTProcessor.json

- css/properties/list-style-type.json
Fix #19200
Note the ID is correct! Only the description had the typo.
> amaric -> amharic

- api/CSSContainerRule.json
This PR updates and corrects version values for WebView Android for the `CSSContainerRule` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v8.2.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/CSSContainerRule
Additional Notes: In #19089, this interface was added with WebView set to `false`.  I believe this was simply an error due to not having WebView 111 data and it should have been mirrored anyways.
> Update WebView data for CSSContainerRule API

- api/Clipboard.json
This PR updates and corrects version values for Firefox and Firefox Android for the `readText` member of the `Clipboard` API. Other
> Update Firefox data for api.Clipboard.readText

- api/FileSystemDirectoryEntry.json
- api/FileSystemDirectoryHandle.json
- api/FileSystemDirectoryReader.json
- api/FileSystemEntry.json
- api/FileSystemFileEntry.json
- api/FileSystemFileHandle.json
- api/FileSystemHandle.json
This PR updates and corrects version values for Opera Android for the `FileSystem*` APIs. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v8.2.0).
Tests Used:
https://mdn-bcd-collector.gooborg.com/tests/api/FileSystemDirectoryEntry
https://mdn-bcd-collector.gooborg.com/tests/api/FileSystemDirectoryHandle
https://mdn-bcd-collector.gooborg.com/tests/api/FileSystemDirectoryReader
https://mdn-bcd-collector.gooborg.com/tests/api/FileSystemEntry
https://mdn-bcd-collector.gooborg.com/tests/api/FileSystemFileEntry
https://mdn-bcd-collector.gooborg.com/tests/api/FileSystemFileHandle …
> Update Opera Android data for FileSystem APIs

- css/properties/animation-composition.json
_(Hi, Chrome DevRel here! 👋)_
Chrome 112 supports `animation-composition`.
- ChromeStatus: https://chromestatus.com/feature/5599641280708608
- Tracking Bug: https://crbug.com/1342699
> Chrome 112 supports animation-composition

- api/ShadowRoot.json
-  `ShadowRoot.elementFromPoint()` and `ShadowRoot.elementsFromPoint()` were added to the collector as custom, non-standard IDL in response to https://github.com/w3c/csswg-drafts/issues/5886.
In that PR, GitHub user @Haprog links to the old version of the W3C Shadow DOM spec, which contains these methods defined on a DocumentOrShadowRoot interface mixin: https://www.w3.org/TR/2017/WD-shadow-dom-20170905/#extensions-to-the-documentorshadowroot-mixin
- The very next version now just says “Shadow DOM specification is being incorporated into to the DOM specification, HTML specification, CSS Scoping Module Level 1, UI Events specification, and other relevant specifications.”
- It seems that these features were moved over to the CSSOM View spec at first glance… …
> Remove spec_urls for ShadowRoot.element(s)FromPoint

- api/Window.json
Not documented on MDN + removed from any implementation for 2 years.
> Remove Window.devicelight_event

- api/Document.json
This page exists for a long time.
> Add missing mdn_url for Document.rootElement

- javascript/operators/import.json
FF113 adds support for dynamic import behind pref - see https://bugzilla.mozilla.org/show_bug.cgi?id=1540913#c37
Note that this is the same pref as support for static import in workers, so all should ship at the same time.
> FF113 supports dynamic import behind pref

- browsers/safari.json
- browsers/safari_ios.json
This PR updates Safari to version 16.4
* https://webkit.org/blog/13966/webkit-features-in-safari-16-4/
* https://developer.apple.com/documentation/safari-release-notes/safari-16_4-release-notes
> Update Safari to version 16.4

- api/PopStateEvent.json
The `PopStateEvent()` is been added in mdn/content#25702
> Add missing mdn_url for PopStateEvent()

- css/at-rules/media.json
Firefox 113 now supports the scripting media feature (`@media(scripting)`), updated data accordingly.
Bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1166581
Intent to ship (and prototype): https://groups.google.com/a/mozilla.org/g/dev-platform/c/BU3zzial8lE/m/NzJhLV0MAgAJ
> Firefox 113 supports the scripting media feature

- css/selectors/user-invalid.json
- css/selectors/user-valid.json
Safari just added support for user-invalid and user-valid, I updated the compatibility data to reflect it
https://webkit.org/blog/13966/webkit-features-in-safari-16-4/#css
> Update support for user-[in]valid in safari

- css/at-rules/media.json
Added data for the `prefers-reduced-transparency` media query as Firefox now supports in 113 behind a pref.
New WPT tests: https://github.com/web-platform-tests/wpt/blob/master/css/mediaqueries/prefers-reduced-transparency.html
Gecko bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1736914
WebKit bug: https://bugs.webkit.org/show_bug.cgi?id=175497 (unimplemented)
Blink bug: Does not exist currently
> Add data for prefers-reduced-transparency media query

- api/ErrorEvent.json
This is the closest link in the spec (the link of the keyword _constructor_ is useless)
> Add missing spec_url for ErrorEvent()

- http/headers/Sec-GPC.json
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Sec-GPC doesn't have a link to the specification, and it appears to say that this is how to add one.
I haven't tested this change.
> Add a spec_url for Sec-GPC

- api/Notification.json
- api/NotificationEvent.json
- api/PushEvent.json
- api/PushManager.json
- api/PushMessageData.json
- api/PushSubscription.json
- api/PushSubscriptionChangeEvent.json
- api/PushSubscriptionOptions.json
- api/ServiceWorkerRegistration.json
This data comes from mdn-bcd-collector, albeit modified to run under as a Home Screen web app. This essentially extends what https://github.com/mdn/browser-compat-data/pull/18963 already did.
This follows the precedent set by #19278, documenting Home Screen web app specific features as Safari for iOS features.
> Document WebKit for iOS 16.4 Home Screen web app specific features

- css/properties/overflow-x.json
- css/properties/overflow-y.json
- css/properties/overflow.json
From Fx112, `overlay` will be recognized as a value for the `overflow` property.
- This PR adds the FX support for `overlay` value to `overflow` property and also updates `deprecated` to `false`.
- This PR also adds the `overlay` value row to browser compat tables for the longhand properties `overflow-x` and `overflow-y`.
- Tested in browserstack
- Bug tracker: https://bugzilla.mozilla.org/show_bug.cgi?id=1817189
Doc issue tracker: https://github.com/mdn/content/issues/25355
Related content update: https://github.com/mdn/content/pull/25749
Spec: https://w3c.github.io/csswg-drafts/css-overflow/#overflow-control
> Firefox 112 adds support for overlay value for overflow property

- css/at-rules/media.json
Add correct data for Firefox and Safari in `css.at-rules.media.range_syntax` 
I've tested with `window.matchMedia('(1px < width < 99999px)')` in every Firefox version until landing on 102.
Relevant WPT tests : https://wpt.fyi/results/css/mediaqueries?label=master&label=experimental&aligned
Release notes for Firefox do not mention this change : https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/102
Release notes for Safari : https://webkit.org/blog/13966/webkit-features-in-safari-16-4/#:~:text=Media%20Queries%20Syntax,width%20or%20height.
Fixes https://github.com/mdn/browser-compat-data/issues/14593#issuecomment-1491436872
> css.at-rules.media.range_syntax : correct data for Firefox and Safari

- css/at-rules/media.json
The media query range syntax (`@media (width > 800px)` is supported in Edge
I tested https://codepen.io/preethi-dev/pen/rNvQPeg (which is a demo using this range syntax built for https://css-tricks.com/the-new-css-media-query-range-syntax/) in Edge.
> Mark the media query range syntax as supported in Edge and Opera

- javascript/builtins/Array.json
Spec: https://tc39.es/proposal-array-from-async/#sec-array.fromAsync
Ships in Safari 16.4: https://webkit.org/blog/13966/webkit-features-in-safari-16-4/
> Add Array.fromAsync

- http/headers/X-XSS-Protection.json
Safari 15.4 removed support for the X-XSS-Protection header both for Mac and iOS.
- https://developer.apple.com/documentation/safari-release-notes/safari-15_4-release-notes
- https://webkit.org/blog/12445/new-webkit-features-in-safari-15-4/#security
I also tested the X-XSS-Protection header in a recent version of Safari and can confirm that it no longer has any effect.
Fixes #16627
> Safari 15.4 removed support for X-XSS-Protection

- javascript/builtins/Atomics.json
https://webkit.org/blog/13966/webkit-features-in-safari-16-4/
> Safari 16.4 supports Atomics.waitAsync

- html/elements/script.json
https://github.com/WebKit/WebKit/commit/6c1996aea8b85babf563135acc2d05def8aca3cb
https://webkit.org/blog/13966/webkit-features-in-safari-16-4/
Fixes https://github.com/mdn/browser-compat-data/issues/19291
> Safari 16.4 supports importmap

- api/ReadableStream.json
This PR is a part of a project to add missing interfaces and interface features to BCD that are from an active spec (including WICG specs) and is supported in at least one browser.  This particular PR adds the missing features of the ReadableStream API, populating the results using data from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v8.1.1).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/ReadableStream
> Add missing features for ReadableStream API

- css/types/image.json
Chrome 113 ships `image-set()` unprefixed.
https://chromestatus.com/feature/5109745420075008
> unprefix image-set in Chrome 113

- api/ServiceWorkerContainer.json
The `error_event` was removed from Firefox in version 106.
Tested using a local build of MDN.
Release number sourced from https://bugzil.la/1714533.
N/A
> Add version_removed to Firefox on ServiceWorkerContainer error_event

- api/ReadableStream.json
This PR updates and corrects the real values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `ReadableStream` API, based upon results from the [mdn-bcd-collector](https://mdn-bcd-collector.appspot.com) project (v6.1.0).
Tests Used: https://mdn-bcd-collector.appspot.com/tests/api/ReadableStream
> Update Chromium versions for ReadableStream API

- api/AudioNode.json
This PR updates and corrects the real values for Safari (Desktop and iOS/iPadOS) for the `AudioNode` API, based upon results from the [mdn-bcd-collector](https://mdn-bcd-collector.appspot.com) project (v6.2.6).
Tests Used: https://mdn-bcd-collector.appspot.com/tests/api/AudioNode
> Update Safari versions for AudioNode API

- api/MediaStreamTrackProcessor.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `MediaStreamTrackProcessor` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v8.2.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/MediaStreamTrackProcessor
Additional Notes: This follows the recommendation in #18555 to set Chrome to partial implementation, following an incorrect exposure of the interface.
> Update Chromium data for MediaStreamTrackProcessor API

- browsers/chrome.json
- browsers/chrome_android.json
- browsers/webview_android.json
Hi all! 👋
This PR updates Chrome to version 112.
And according to https://chromiumdash.appspot.com/schedule, it also includes Chrome 114 release date.
> Updates chrome to version 112

- css/at-rules/property.json
From changelog: https://webkit.org/blog/13966/webkit-features-in-safari-16-4/
> Safari 16.4 adds support for CSS Properties and Values API with support for the @property at-rule. It greatly extends the capabilities of CSS variables by allowing developers to specify the syntax of the variable, the inheritance behavior, and the variable initial value — similar to how browser engines define CSS properties.
> Safari added support for @property in version 16.4

- html/elements/template.json
Safari shipped the `shadowrootmode` attribute for Declarative Shadow DOM in version 16.4. Release notes here: https://developer.apple.com/documentation/safari-release-notes/safari-16_4-release-notes
A prior blog post that shows the Technology Preview version it first shipped in: https://webkit.org/blog/13851/declarative-shadow-dom/
> Safari shipped shadowrootmode in 16.4

- api/ServiceWorkerContainer.json
- Adds full support to Safari from 16.4.
- Removes the MDN link as the page doesn't seem to exist on MDN.
Get the commit revision from the [WebKit bug](https://bugs.webkit.org/show_bug.cgi?id=171216): https://commits.webkit.org/256896@main
```
$ git tag --contains 5e2beb55a112f682aff66e5646e77ce9e079054c | grep Safari
releases/Apple/Safari-16.4-iOS-16.4
releases/Apple/Safari-16.4-iOS-16.4-iPadOS
releases/Apple/Safari-16.4-macOS-13.3
```
N/A
> Update ServiceWorkerContainer messageerror event

- docs/matching-browser-releases/index.md
This details finding a Safari release through the WebKit repository using a revision number. I found it particularly useful for #19330, so I thought I'd write it up for the docs.
N/A
N/A
> Add docs on finding a Safari release through a revision number

- javascript/builtins/Atomics.json
This PR re-adds a note regarding Atomics being gated behind COOP and COEP in Safari in older versions.  This reverts its removal in #16047.
> Mention COOP/COEP requirement for Atomics for Safari

- webextensions/api/storage.json
Adds support for session.storage for Safari 16.4 with a note about a 10MB maximum.
See [Safari 16.4 Beta Release Notes](https://developer.apple.com/documentation/safari-release-notes/safari-16_4-release-notes#Safari-Extensions).
> Add session.storage support for Safari 16.4

- api/OffscreenCanvas.json
- css/selectors/dir.json
- css/types/length-percentage.json
- css/types/length.json
- html/elements/a.json
- svg/attributes/presentation.json
- webextensions/api/declarativeNetRequest.json
- webextensions/api/scripting.json
- webextensions/api/storage.json
- webextensions/manifest/icons.json
Although the community has done a great job adding Safari 16.4 features, there are still several notable features that need updated:
- `:dir()`
- `lh` and `rlh` units
- `font-size-adjust` support for SVG
- Safari Web Extensions
- `storage.session`
- declarativeNetRequest `MAX_NUMBER_OF_DYNAMIC_AND_SESSION_RULES`
- `scripting.registerContentScript`
- `scripting.getRegisteredContentScripts`
- `scripting.unregisterContentScripts`
- `scripting.updateContentScripts`
- SVG icons
This also includes a correction for text fragment support which shipped in Safari 16.1 and `modifyHeaders` action in `declarativeNetRequest` which shipped in Safari 16.4.
[Safari 16.4 Release Notes](https://developer.apple.com/documentation/safari-release-notes/safari-16_4-release-notes)
> Updated Safari 16.4 features

- css/properties/pointer-events.json
This PR changes the spec link for the CSS property [`pointer-events`](https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events) to [CSS Basic User Interface Module](https://w3c.github.io/csswg-drafts/css-ui/#pointer-events-control).
The current link points to [Scalable Vector Graphics (SVG) 2](https://svgwg.org/svg2-draft/interact.html#PointerEventsProperty), which seems to be a confusion with the SVG presentational attribute [pointer-events](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/pointer-events).
> Correct the spec link for `pointer-events`

- css/selectors/backdrop.json
Fixes #19367 where the spec editor notified us that the definition moved from the original spec to the new one.
> Fix spec_url for ::backdrop

- api/BeforeUnloadEvent.json
- api/Document.json
- api/HashChangeEvent.json
- api/History.json
- api/Location.json
- api/PageTransitionEvent.json
- api/PopStateEvent.json
- api/Window.json
The multipage HTML spec recently dropped the former `history.html` file and added a new `nav-history-apis.html` file, which includes parts of what had been in the `browsing-the-web.html` file and the `history.html` file.  So, a number of the fragments in BCD spec URLs have moved to the new `nav-history-apis.html` file.
> Update some HTML spec URLs to new nav-history-apis.html filename

- api/Element.json
- api/WorkerGlobalScope.json
The normative definition for the `securitypolicyviolation` event is now in the CSP spec.
> Update spec URL for securitypolicyviolation event

- api/SVGClipPathElement.json
- api/SVGMaskElement.json
> Update css-masking spec URLs

- api/ContentVisibilityAutoStateChangeEvent.json
- api/Element.json
> Update css-contain spec URLs

- api/Document.json
- api/ViewTransition.json
- css/properties/view-transition-name.json
- css/selectors/view-transition-group.json
- css/selectors/view-transition-image-pair.json
- css/selectors/view-transition-new.json
- css/selectors/view-transition-old.json
- css/selectors/view-transition.json
> Update css-view-transitions spec URLs

- api/CSSFontFeatureValuesRule.json
- api/CSSFontPaletteValuesRule.json
> Update css-fonts spec URLs

- api/CSS.json
- api/Highlight.json
- api/HighlightRegistry.json
- css/selectors/highlight.json
> Update css-highlight-api spec URLs

- css/properties/baseline-source.json
This should be using the unversioned spec URL
> Update css-inline spec URL

- api/ContactAddress.json
- api/ContactsManager.json
- api/Navigator.json
https://w3c.github.io/contact-picker/spec redirects to https://w3c.github.io/contact-picker — so, let’s use that rather than everybody needing to run into the redirect unnecessarily.
> Update contact-picker spec URLs (avoid redirect)

- html/manifest/file_handlers.json
This should omit the index.html filename part (as other existing spec URLs do)
> Update manifest-incubations spec URL

- api/RTCRtpEncodingParameters.json
This should be using the URL for the current spec (as the other existing spec URLs do), rather than the URL for the static W3C TR version.
> Update webrtc-priority spec URL

- css/properties/-webkit-line-clamp.json
Note also: This property is documented only in the versioned css-overflow-4 (level 4) spec — but in the unversioned spec (which is currently level 3)
> Fix webkit-line-clamp spec URL

- css/properties/overflow-block.json
- css/properties/overflow-inline.json
These just had the wrong spec URL (with non-existent fragment)
> Fix overflow-block and overflow-inline spec URLs

- html/elements/link.json
https://github.com/whatwg/html/pull/8996 dropped `rel=prerender` from the HTML spec.
> Drop spec URL for rel=prerender

- http/headers/Feature-Policy.json
https://github.com/whatwg/html/commit/d7ae2a6 dropped the `document-domain` permissions policy from the HTML spec.
> Drop spec URL for document-domain permissions policy

- javascript/builtins/Intl/Locale.json
The spec URLs removed in this change are for `Intl.Locale.prototype` properties that were apparently once part of the spec (and implemented in some browsers) but that aren’t in the current spec (presumably because they were intentionally removed from the spec).
> Drop spec URLs for Intl.Locale.prototype properties no longer in spec

- http/headers/Content-Security-Policy.json
https://github.com/w3c/webappsec-csp/pull/582 dropped `prefetch-src` from the CSP spec.
> Deprecate CSP prefetch-src

- api/Window.json
FF113 supports Window.print() on android in https://bugzilla.mozilla.org/show_bug.cgi?id=1809922
This updates the BCD. 
Other docs in https://github.com/mdn/content/issues/26152
> FF113 supports Window.print() in Android

- api/CanvasRenderingContext2D.json
- api/OffscreenCanvasRenderingContext2D.json
FF113 adds support for [`CanvasRenderingContext2D.reset()`](https://developer.mozilla.org/en-US/en-US/docs/Web/API/CanvasRenderingContext2D/reset) and [`OffscreenCanvasRenderingContext2D.reset()`](https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvasRenderingContext2D#canvasrenderingcontext2d.reset) in https://bugzilla.mozilla.org/show_bug.cgi?id=1709347
This updates the two features, and removes the experimental flag.
Other docs work for this can be tracked in https://github.com/mdn/content/issues/26148
> FF113 supports CanvasRenderingContext2D/OffscreenCanvasRenderingContext2D.reset() 

- http/headers/Sec-Fetch-Dest.json
- http/headers/Sec-Fetch-Mode.json
- http/headers/Sec-Fetch-Site.json
- http/headers/Sec-Fetch-User.json
Safari 16.4 added Fetch Metadata Request Headers.
I tested by viewing request headers in Safari 16.4 on macOS. I also used browser stack to ensure that the headers were not present on Safari 16.3. Lastly, this aligns with the release notes and upstream bug.
- https://developer.apple.com/documentation/safari-release-notes/safari-16_4-release-notes
> Added support for Fetch Metadata Request Headers.
- https://bugs.webkit.org/show_bug.cgi?id=238265
Fixes #19389
> Fetch Metadata Req Headers: Safari 16.4+ support

- api/XRCompositionLayer.json
<s>Alternatively, we could just completely remove `chromaticAberrationCorrection` from BCD. Oculus is the only browser that implemented it, and in MDN we anyway don’t expose compat data for Oculus.</s>
Related MDN change https://github.com/mdn/content/pull/26277
> Remove XRCompositionLayer»chromaticAberrationCorrection

- api/HTMLVideoElement.json
https://github.com/w3c/picture-in-picture/pull/216 removed `HTMLVideoElement`»`autoPictureInPicture` from the spec, and while the current BCD data indicates it was implemented in Safari, that’s not strictly true.
https://github.com/w3c/picture-in-picture/pull/216#issuecomment-1339792930 explains:
> autoPictureInPicture is in WebKit but doesn't actually do anything. See https://github.com/search?q=repo%3AWebKit%2FWebKit+autoPictureInPicture&type=code
So it won’t ever actually do anything in Safari, and won’t ever be implemented in other browsers; so we should remove it from BCD rather than just it hanging around — because it’s not something that web developers will ever be able to actually use, anywhere.
Related MDN change: https://github.com/mdn/content/pull/26278
> Remove HTMLVideoElement»autoPictureInPicture

- http/headers/Set-Cookie.json
https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite redirects to https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie#samesitesamesite-value — so let’s use the redirected destination URL instead.
> Update spec URL for SameSite param of Set-Cookie header

- css/properties/offset-path.json
- css/types/ray.json
- `ray()` already has a row in `offset-path` BCD table https://developer.mozilla.org/en-US/docs/Web/CSS/offset-path#browser_compatibility, which needs to be updated for Fx112.
- A new `ray()` function page is being created (https://github.com/mdn/content/pull/26266) and a new BCD table needs to be created for this. The new `ray.json` file also adds the spec link.
- I have picked most of the `ray()` info for the new table from the `offset-path` BCD table.
- Firefox: `ray()` is still behind the flag `layout.css.motion-path-ray.enabled`. In Fx112, support is added for spec's updated syntax. 
- Chrome:
- The BCD table on [offset-path](https://developer.mozilla.org/en-US/docs/Web/CSS/offset-path#browser_compatibility)[ page](https://developer.mozilla.org/en-US/docs/Web/CSS/offset-path#browser_c …
> (fx112) Add file for ray function and update ray() in offset-path

- css/types/exp.json
- css/types/hypot.json
- css/types/log.json
- css/types/pow.json
- css/types/sqrt.json
Added version added for CSS exponential functions for Firefox and set experimental to false as multiple browsers now support
Tested in Firefox Nightly:
- pow() - https://codepen.io/CodeRedDigital/pen/dygYoYP 
- sqrt() - https://codepen.io/CodeRedDigital/pen/gOBabja 
- hypot() - https://codepen.io/CodeRedDigital/pen/poxjJeZ 
- log() - https://codepen.io/CodeRedDigital/pen/VwEvLXK 
- exp() - https://codepen.io/CodeRedDigital/pen/KKGdpJJ 
Also information from this bug [1814469](https://bugzilla.mozilla.org/show_bug.cgi?id=1814469)
- [Content](https://github.com/mdn/content/pull/26187)
- [Firefox Release](https://github.com/mdn/content/pull/26203)
> Firefox supports exponential functions

- css/selectors/nesting.json
This should be the URL for the latest spec, rather than the TR version.
> Fix CSS Nesting spec URL

- css/selectors/popover-open.json
This compat data for the `:popover-open` psuedo selector.
This is available in the specification: https://developer.mozilla.org/docs/Web/CSS/:popover-open
https://github.com/mdn/content/issues/25125
> add popover-open selector

- browsers/nodejs.json
https://nodejs.org/en/blog/announcements/v20-release-announce
> Add release of Node.js 20.0.0

- api/WindowClient.json
Fixes https://github.com/mdn/content/issues/26264
I tested using https://googlechrome.github.io/samples/service-worker/windowclient-navigate/ on browserstack. All works in 16.3 but not on 15.6. It is possible it appeared in 16.2 of course. No information about this in the release notes.
> Safari 16.3 supports WindowClient.navigate()

- css/properties/content-visibility.json
Fx bug https://bugzilla.mozilla.org/show_bug.cgi?id=1820058 enables `content-visibility` on Nightly by default.
Tested on Firefox Nightly and confirmed support without enabling `layout.css.content-visibility.enabled`.
Doc issue: https://github.com/mdn/content/issues/26155
> (fx112) content-visibility: nightly support in firefox

- javascript/builtins/Array.json
- javascript/builtins/TypedArray.json
Node.js 20.0.0 was recently released and [includes V8 version 11.3.244.4](https://nodejs.org/en/download/releases).
I was not sure how or whether to test this.
The change is noted in the [Node 20 changelog](https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V20.md#20.0.0) and the relevant [Chrome release](https://chromestatus.com/feature/5068609911521280).
I did ensure that the methods all worked in a terminal.
> Node 20 supports new Array methods toSorted, toReversed, toSpliced, and with

- javascript/builtins/Array.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `Array` JavaScript builtin. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.0.2).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/javascript/builtins/Array
> Update Safari data for Array JavaScript builtin

- javascript/builtins/SharedArrayBuffer.json
This PR updates and corrects version values for Firefox and Firefox Android for the `SharedArrayBuffer` JavaScript builtin. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.0.2).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/javascript/builtins/SharedArrayBuffer
> Update Firefox data for SharedArrayBuffer JavaScript builtin

- html/elements/iframe.json
This PR organizes the `sandbox` attribute values of the `iframe` HTML element, as well as adds the missing attribute values.  Fixes #1208.
> Organize sandbox attribute values; add missing sandbox values

- api/DataTransferItem.json
This PR updates and corrects version values for WebView Android for the `webkitGetAsEntry` member of the `DataTransferItem` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.0.2).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/DataTransferItem/webkitGetAsEntry
> Update WebView data for api.DataTransferItem.webkitGetAsEntry

- api/DataTransferItem.json
This PR updates and corrects version values for Firefox Android for the `webkitGetAsEntry` member of the `DataTransferItem` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.0.2).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/DataTransferItem/webkitGetAsEntry
> Update Firefox Android data for api.DataTransferItem.webkitGetAsEntry

- browsers/deno.json
Update deno versions 1.29 through 1.32
I'm not sure how to see the engine version in the repo. I've relied on their release notes https://deno.com/blog/v1.31#v8-110 and https://deno.com/blog/v1.32#v8-112
This should unblock #19447 and #19448
> Update deno versions

- browsers/edge.json
Every time Edge gets released, a release note comes out. The page where the release notes are located does not contain all versions though. Older versions gets moved to an archive page.
This little PR updates one of the release note links for an older release.
> Update archived edge release note in edge.json

- api/Headers.json
This PR updates and corrects version values for Firefox and Firefox Android for the `getSetCookie` member of the `Headers` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.0.2).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/Headers/getSetCookie
> Update Firefox data for api.Headers.getSetCookie

- api/HTMLTextAreaElement.json
This PR updates and corrects version values for Firefox and Firefox Android for the `autocapitalize` member of the `HTMLTextAreaElement` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.0.2).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/HTMLTextAreaElement/autocapitalize
> Update Firefox data for api.HTMLTextAreaElement.autocapitalize

- api/VideoPlaybackQuality.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `totalFrameDelay` member of the `VideoPlaybackQuality` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.0.2).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/VideoPlaybackQuality/totalFrameDelay
> Update Chromium data for api.VideoPlaybackQuality.totalFrameDelay

- api/RTCIceTransport.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `RTCIceTransport` member of the `RTCIceTransport` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.0.2).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/RTCIceTransport/RTCIceTransport
> Update Chromium data for api.RTCIceTransport.RTCIceTransport

- css/properties/overflow-clip-box.json
We don't have documentation for this (`overflow-clip-box`) and the URL mentioned was incorrect anyway.
> Remove bogus mdn_url for overflow-clip-box

- css/properties/overflow-clip-box-block.json
We don't have documentation for this (`overflow-clip-box-block`) and the URL mentioned was incorrect anyway.
> Remove bogus mdn_url for overflow-clip-box-block

- css/properties/offset-path.json
- css/types/ray.json
This is a follow up to https://github.com/mdn/browser-compat-data/pull/19421.
This PR creates a separate row in the `ray()` BCD table to call out the difference in implementation of the `<ray_size>` parameter across browsers.
This PR also makes some minor updates to description text in [`offset-path` BCD table](https://developer.mozilla.org/en-US/docs/Web/CSS/offset-path#browser_compatibility).
- Firefox 112 behind the flag `layout.css.motion-path-ray.enabled`: `<ray_size>` is optional
- Chrome Canary with #enable-experimental-web-platform-features: `<ray_size>` is optional - but we don't indicate this in the BCD table
- Chrome 112 with or without #enable-experimental-web-platform-features: `<ray_size>` is required
- Safari TP: `<ray_size>` is required
Doc issue tracker: …
> (fx112) ray() - create separate entry for <ray_size> parameter

- api/CanvasRenderingContext2D.json
See https://github.com/mdn/content/pull/22363 - when gradients are created using [`CanvasRenderingContext2D.createConicGradient()`](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/createConicGradient) Firefox and Safari start the gradient at 12 o'clock, but the standard now expects them to start at 3 o'clock, like the other Canvas APIs.
2 questions:
- I'm not sure the wording here is the best. Maybe "12 o'clock" would be better?
- per https://github.com/mdn/content/pull/22363#issuecomment-1324388656, it looks like Safari has updated to the standard, but AFAICT this isn't in a released version yet. But I'm hoping someone can tell me if I have to do something else here.
> Document Firefox and Safari behavior wrt createConicGradient

- css/properties/scroll-timeline-axis.json
- css/properties/scroll-timeline-name.json
- css/properties/scroll-timeline.json
This pull request is a follow up to https://github.com/mdn/browser-compat-data/pull/19148 for adding to the browser compat table chrome versions in which support was added for `scroll-timeline` shorthand and longhand properties.
Accordingly, this pull request also makes minor updates to the Firefox entries to add notes to explain the changes that  happened in those versions.
All the properties in both Chrome and Firefox are still behind the experimental flag/preference.
Source for information for Chrome versions: https://github.com/mdn/content/pull/25105#issuecomment-1472584987
version 111: https://bugs.chromium.org/p/chromium/issues/detail?id=1357795
version 107: https://bugs.chromium.org/p/chromium/issues/detail?id=1317765
version 88: …
> Update Chrome versions for scroll-timeline shorthand and longhand properties

- html/global_attributes.json
As part of my work on the WebAuthn API, I was asked to add details of the `autocomplete="webauthn"` value. This PR adds the corresponding BCD.
I was told that the Chrome version it was added was 108 by the Chrome engineers.
> Add data for autocomplete="webauthn"

- css/properties/text-underline-position.json
This PR updates and corrects version values for all browsers for the `text-underline-position` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.0.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/text-underline-position
> Update all browsers data for text-underline-position CSS property

- css/properties/text-underline-offset.json
This PR updates and corrects version values for all browsers for the `text-underline-offset` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.0.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/text-underline-offset
> Update all browsers data for text-underline-offset CSS property

- css/properties/text-emphasis.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `text-emphasis` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.0.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/text-emphasis
> Update Chromium data for text-emphasis CSS property

- css/properties/text-emphasis-style.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `text-emphasis-style` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.0.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/text-emphasis-style
> Update Chromium data for text-emphasis-style CSS property

- css/properties/font-synthesis-small-caps.json
This PR updates and corrects version values for all browsers for the `font-synthesis-small-caps` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.0.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/font-synthesis-small-caps
> Update all browsers data for font-synthesis-small-caps CSS property

- css/properties/font-size.json
This PR updates and corrects version values for all browsers for the `xxx-large` member of the `font-size` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.0.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/font-size/xxx-large
> Update all browsers data for css.properties.font-size.xxx-large

- css/properties/font-synthesis-style.json
This PR updates and corrects version values for all browsers for the `font-synthesis-style` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.0.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/font-synthesis-style
> Update all browsers data for font-synthesis-style CSS property

- css/properties/font-synthesis-weight.json
This PR updates and corrects version values for all browsers for the `font-synthesis-weight` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.0.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/font-synthesis-weight
> Update all browsers data for font-synthesis-weight CSS property

- css/properties/font-synthesis.json
This PR updates and corrects version values for Opera and Opera Android for the `font-synthesis` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.0.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/font-synthesis
> Update Opera data for font-synthesis CSS property

- css/properties/forced-color-adjust.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `forced-color-adjust` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.0.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/forced-color-adjust
> Update Chromium data for forced-color-adjust CSS property

- css/properties/height.json
This PR updates and corrects version values for Firefox and Firefox Android for the `fit-content` member of the `height` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.0.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/height/fit-content
> Update Firefox data for css.properties.height.fit-content

- css/properties/image-orientation.json
This PR updates and corrects version values for Opera and Opera Android for the `image-orientation` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.0.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/image-orientation
> Update Opera data for image-orientation CSS property

- css/properties/inline-size.json
This PR updates and corrects version values for Firefox and Firefox Android for the `fit-content` member of the `inline-size` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.0.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/inline-size/fit-content
> Update Firefox data for css.properties.inline-size.fit-content

- css/properties/list-style-type.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `list-style-type` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.0.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/list-style-type
> Update Chromium data for list-style-type CSS property

- css/properties/list-style.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `symbols` member of the `list-style` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.0.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/list-style/symbols
> Update Chromium data for css.properties.list-style.symbols

- css/properties/mask-origin.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `non_standard_values` member of the `mask-origin` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.0.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/mask-origin/non_standard_values
> Update Safari data for css.properties.mask-origin.non_standard_values

- css/properties/max-block-size.json
This PR updates and corrects version values for Firefox and Firefox Android for the `fit-content` member of the `max-block-size` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.0.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/max-block-size/fit-content
> Update Firefox data for css.properties.max-block-size.fit-content

- css/properties/max-inline-size.json
This PR updates and corrects version values for Firefox and Firefox Android for the `fit-content` member of the `max-inline-size` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.0.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/max-inline-size/fit-content
> Update Firefox data for css.properties.max-inline-size.fit-content

- css/properties/min-block-size.json
This PR updates and corrects version values for Firefox and Firefox Android for the `fit-content` member of the `min-block-size` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.0.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/min-block-size/fit-content
> Update Firefox data for css.properties.min-block-size.fit-content

- css/properties/min-inline-size.json
This PR updates and corrects version values for Firefox and Firefox Android for the `fit-content` member of the `min-inline-size` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.0.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/min-inline-size/fit-content
> Update Firefox data for css.properties.min-inline-size.fit-content

- css/properties/min-width.json
This PR updates and corrects version values for Firefox and Firefox Android for the `fit-content` member of the `min-width` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.0.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/min-width/fit-content
> Update Firefox data for css.properties.min-width.fit-content

- css/properties/offset-distance.json
This PR updates and corrects version values for Firefox Android for the `offset-distance` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.0.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/offset-distance
> Update Firefox Android data for offset-distance CSS property

- css/properties/offset-rotate.json
This PR updates and corrects version values for Firefox Android for the `offset-rotate` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.0.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/offset-rotate
> Update Firefox Android data for offset-rotate CSS property

- css/properties/offset.json
This PR updates and corrects version values for Firefox Android for the `offset` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.0.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/offset
> Update Firefox Android data for offset CSS property

- css/properties/opacity.json
This PR updates and corrects version values for Firefox and Firefox Android for the `percentages` member of the `opacity` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.0.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/opacity/percentages
> Update Firefox data for css.properties.opacity.percentages

- css/properties/-moz-image-region.json
This PR updates and corrects version values for Firefox and Firefox Android for the `-moz-image-region` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.0.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/-moz-image-region
> Update Firefox data for -moz-image-region CSS property

- css/properties/block-size.json
This PR updates and corrects version values for Firefox and Firefox Android for the `fit-content` member of the `block-size` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.0.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/block-size/fit-content
> Update Firefox data for css.properties.block-size.fit-content

- css/properties/clip-path.json
This PR updates and corrects version values for Opera and Opera Android for the `path` member of the `clip-path` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.0.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/clip-path/path
> Update Opera data for css.properties.clip-path.path

- css/properties/color-scheme.json
This PR updates and corrects version values for all browsers for the `color-scheme` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.0.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/color-scheme
> Update all browsers data for color-scheme CSS property

- css/properties/flex-basis.json
This PR updates and corrects version values for Opera and Opera Android for the `flex-basis` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.0.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/flex-basis
> Update Opera data for flex-basis CSS property

- css/properties/display.json
This PR updates and corrects version values for Firefox Android for the `multi-keyword_values` member of the `display` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.0.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/display/multi-keyword_values
> Update Firefox Android data for css.properties.display.multi-keyword_values

- css/properties/font-optical-sizing.json
This PR updates and corrects version values for Opera and Opera Android for the `font-optical-sizing` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.0.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/font-optical-sizing
> Update Opera data for font-optical-sizing CSS property

- css/properties/flex-basis.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `content` member of the `flex-basis` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.0.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/flex-basis/content
> Update Safari data for css.properties.flex-basis.content

- css/properties/white-space.json
This PR updates and corrects version values for Firefox Android for the `break-spaces` member of the `white-space` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.0.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/white-space/break-spaces
> Update Firefox Android data for css.properties.white-space.break-spaces

- css/properties/text-decoration-thickness.json
This PR updates and corrects version values for Firefox Android for the `text-decoration-thickness` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.0.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/text-decoration-thickness
> Update Firefox Android data for text-decoration-thickness CSS property

- css/properties/quotes.json
This PR updates and corrects version values for Opera and Opera Android for the `quotes_auto` member of the `quotes` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.0.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/quotes/quotes_auto
> Update Opera data for css.properties.quotes.quotes_auto

- css/properties/opacity.json
This PR updates and corrects version values for Opera and Opera Android for the `percentages` member of the `opacity` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.0.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/opacity/percentages
> Update Opera data for css.properties.opacity.percentages

- css/properties/overflow-anchor.json
This PR updates and corrects version values for Firefox Android for the `overflow-anchor` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.0.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/overflow-anchor
> Update Firefox Android data for overflow-anchor CSS property

- css/properties/overflow-block.json
This PR updates and corrects version values for Firefox Android for the `overflow-block` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.0.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/overflow-block
> Update Firefox Android data for overflow-block CSS property

- css/properties/overflow-inline.json
This PR updates and corrects version values for Firefox Android for the `overflow-inline` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.0.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/overflow-inline
> Update Firefox Android data for overflow-inline CSS property

- api/CSSContainerRule.json
This PR updates and corrects version values for Opera and Opera Android for the `CSSContainerRule` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.0.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/CSSContainerRule
> Update Opera data for CSSContainerRule API

- api/CSSFontFeatureValuesRule.json
This PR updates and corrects version values for Opera and Opera Android for the `CSSFontFeatureValuesRule` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.0.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/CSSFontFeatureValuesRule
> Update Opera data for CSSFontFeatureValuesRule API

- css/properties/overflow-wrap.json
This PR updates and corrects version values for Opera and Opera Android for the `anywhere` member of the `overflow-wrap` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.0.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/overflow-wrap/anywhere
> Update Opera data for css.properties.overflow-wrap.anywhere

- css/properties/overflow-y.json
This PR updates and corrects version values for Opera and Opera Android for the `overflow-y` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.0.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/overflow-y
> Update Opera data for overflow-y CSS property

- css/properties/overflow-x.json
This PR updates and corrects version values for Opera and Opera Android for the `clip` member of the `overflow-x` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.0.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/overflow-x/clip
> Update Opera data for css.properties.overflow-x.clip

- css/properties/overscroll-behavior-block.json
This PR updates and corrects version values for Firefox Android for the `overscroll-behavior-block` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.0.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/overscroll-behavior-block
> Update Firefox Android data for overscroll-behavior-block CSS property

- css/properties/overflow.json
This PR updates and corrects version values for Opera and Opera Android for the `clip` member of the `overflow` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.0.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/overflow/clip
> Update Opera data for css.properties.overflow.clip

- css/properties/text-decoration-skip-ink.json
This PR updates and corrects version values for Firefox Android for the `text-decoration-skip-ink` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.0.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/text-decoration-skip-ink
> Update Firefox Android data for text-decoration-skip-ink CSS property

- css/properties/shape-image-threshold.json
This PR updates and corrects version values for all browsers for the `percentages` member of the `shape-image-threshold` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.0.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/shape-image-threshold/percentages
> Update all browsers data for css.properties.shape-image-threshold.percentages

- css/properties/quotes.json
This PR updates and corrects version values for Firefox Android for the `quotes_auto` member of the `quotes` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.0.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/quotes/quotes_auto
> Update Firefox Android data for css.properties.quotes.quotes_auto

- css/properties/overscroll-behavior-inline.json
This PR updates and corrects version values for Firefox Android for the `overscroll-behavior-inline` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.0.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/overscroll-behavior-inline
> Update Firefox Android data for overscroll-behavior-inline CSS property

- css/properties/text-decoration-skip-ink.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `all` member of the `text-decoration-skip-ink` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.0.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/text-decoration-skip-ink/all
> Update Safari data for css.properties.text-decoration-skip-ink.all

- css/properties/text-decoration-thickness.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `percentage` member of the `text-decoration-thickness` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.0.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/text-decoration-thickness/percentage
> Update Chromium data for css.properties.text-decoration-thickness.percentage

- css/properties/text-emphasis-color.json
This PR updates and corrects version values for all browsers for the `text-emphasis-color` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.0.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/text-emphasis-color
> Update all browsers data for text-emphasis-color CSS property

- javascript/builtins/SharedArrayBuffer.json
This PR updates and corrects version values for WebView Android for the `SharedArrayBuffer` JavaScript builtin. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.0.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/javascript/builtins/SharedArrayBuffer
> Update WebView data for SharedArrayBuffer JavaScript builtin

- api/BaseAudioContext.json
This PR updates and corrects version values for Firefox and Firefox Android for the `createPeriodicWave.constraints_disableNormalization_parameter` member of the `BaseAudioContext` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.0.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/BaseAudioContext/createPeriodicWave/constraints_disableNormalization_parameter
> Update Firefox data for api.BaseAudioContext.createPeriodicWave.constraints_disableNormalization_parameter

- css/properties/max-width.json
This PR updates and corrects version values for Firefox and Firefox Android for the `fit-content` member of the `max-width` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.0.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/max-width/fit-content
> Update Firefox data for css.properties.max-width.fit-content

- css/properties/max-height.json
This PR updates and corrects version values for Firefox and Firefox Android for the `fit-content` member of the `max-height` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.0.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/max-height/fit-content
> Update Firefox data for css.properties.max-height.fit-content

- css/properties/font-variant-alternates.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `font-variant-alternates` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.0.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/font-variant-alternates
> Update Chromium data for font-variant-alternates CSS property

- css/properties/forced-color-adjust.json
- css/types/color.json
Four preferences are flipped to `true` by default in 113, specifically:
* `layout.css.more_color_4.enabled` (for functional notations `lab()` etc.)
* `layout.css.forced-color-adjust.enabled` (for `forced-color-adjust` prop)
* `layout.css.color-mix.enabled` and `layout.css.color-mix.color-spaces.enabled` (for `color-mix()` functional notation)
- Parent issue https://github.com/mdn/content/issues/26147
__Bugzilla:__
- Tracking bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1352753
- Bugs for individual flags:
- `more_color_4`: https://bugzilla.mozilla.org/show_bug.cgi?id=1813497
- `forced-color-adjust`: https://bugzilla.mozilla.org/show_bug.cgi?id=1818819
- `color-mix` and `color-mix.color-spaces`: https://bugzilla.mozilla.org/show_bug.cgi?id=1824526
> relnote(Fx113): CSS Color lvl 4 features are enabled by default

- css/properties/block-size.json
This PR updates and corrects version values for Samsung Internet for the `fit-content` member of the `block-size` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.0.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/block-size/fit-content
> Update Samsung Internet data for css.properties.block-size.fit-content

- api/RTCStatsReport.json
These should all be using the URL for the current spec, rather than the W3C TR version.
> Update RTCStatsReport spec URLs

- api/AudioListener.json
This PR removes the `dopplerFactor` member of the `AudioListener` API from BCD. Per the [data guidelines](https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines/index.md#removal-of-irrelevant-features), this feature can be considered irrelevant and may be removed from BCD accordingly. Even if the current data suggests that the feature is supported, lack of support has been confirmed by the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.0.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/AudioListener/dopplerFactor
> Remove api.AudioListener.dopplerFactor from BCD

- api/RTCStatsReport.json
This PR removes the `[inbound/outbound]-rtp.qpSum` member of the `RTCStatsReport` API from BCD. Per the [data guidelines](https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines/index.md#removal-of-irrelevant-features), this feature can be considered irrelevant and may be removed from BCD accordingly. Even if the current data suggests that the feature is supported, lack of support has been confirmed by the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.0.4).
Tests Used:
https://mdn-bcd-collector.gooborg.com/tests/api/RTCStatsReport/inbound-rtp/qpSum
https://mdn-bcd-collector.gooborg.com/tests/api/RTCStatsReport/outbound-rtp/qpSum
> Remove api.RTCStatsReport.[inbound/outbound]-rtp.qpSum from BCD

- api/CSSImportRule.json
Added data for the new `supportsText` property of `CSSImportRule`.
See last 2 subtests of WPT test: https://wpt.fyi/results/css/cssom/cssimportrule.html
> Add CSSImportRule supportsText property

- GOVERNANCE.md
This PR re-adds Estelle as a peer to BCD, as discussed during the last BCD meeting.  Welcome back, @estelle!
> Re-add Estelle as a peer

- api/EXT_texture_compression_bptc.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `EXT_texture_compression_bptc` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.1.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/EXT_texture_compression_bptc
Additional Notes: This was changed from 16.0 to 16.1 in #18310.  However, I manually tested the WebGL extension and confirmed support in Safari 16.0.
> Update Safari data for EXT_texture_compression_bptc API

- api/Document.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `exitFullscreen.returns_promise` member of the `Document` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.1.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/Document/exitFullscreen/returns_promise
Additional Notes: While the collector only tests with the non-prefixed version of the method, running `document.webkitExitFullscreen()` in Safari 16.3 does not return a promise.
> Update Safari data for api.Document.exitFullscreen.returns_promise

- api/HTMLHeadElement.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `profile` member of the `HTMLHeadElement` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.1.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/HTMLHeadElement/profile
> Update Safari data for api.HTMLHeadElement.profile

- api/SVGAltGlyphDefElement.json
- api/SVGAltGlyphElement.json
- api/SVGAltGlyphItemElement.json
- api/SVGFontElement.json
- api/SVGFontFaceElement.json
- api/SVGFontFaceFormatElement.json
- api/SVGFontFaceNameElement.json
- api/SVGFontFaceSrcElement.json
- api/SVGFontFaceUriElement.json
- api/SVGGlyphElement.json
- api/SVGGlyphRefElement.json
- api/SVGHKernElement.json
- api/SVGMissingGlyphElement.json
- api/SVGTRefElement.json
- api/SVGVKernElement.json
- svg/elements/altGlyph.json
- svg/elements/altGlyphDef.json
- svg/elements/altGlyphItem.json
- svg/elements/font-face-format.json
- svg/elements/font-face-name.json
- svg/elements/font-face-src.json
- svg/elements/font-face-uri.json
- svg/elements/font-face.json
- svg/elements/font.json
- svg/elements/glyph.json
- svg/elements/glyphRef.json
- svg/elements/hkern.json
- svg/elements/missing-glyph.json
- svg/elements/tref.json
- svg/elements/vkern.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the SVG element APIs. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.1.0).
Tests Used:
https://mdn-bcd-collector.gooborg.com/tests/api/SVGAltGlyphDefElement
https://mdn-bcd-collector.gooborg.com/tests/api/SVGAltGlyphElement
https://mdn-bcd-collector.gooborg.com/tests/api/SVGAltGlyphItemElement
https://mdn-bcd-collector.gooborg.com/tests/api/SVGFontElement
https://mdn-bcd-collector.gooborg.com/tests/api/SVGFontFaceElement
https://mdn-bcd-collector.gooborg.com/tests/api/SVGFontFaceFormatElement …
> Update Safari data for SVG*Element API

- api/Request.json
- api/_globals/fetch.json
43 looks like an off-by-10 human error in https://github.com/mdn/browser-compat-data/pull/1351.
At the time, Opera was 13 versions behind Chrome, but 23 was used instead.
> Mirror Opera data for fetch keepalive

- api/Request.json
- api/_globals/fetch.json
In the spec, this is the RequestInit dictionary's priority member, and
that's used both in fetch() and the Request() constructor.
Chrome 101 is from the chromestatus.com entry:
https://chromestatus.com/feature/5273474901737472
It also matches html.elements.img.fetchpriority and related entries.
> Add fetch() and Request() constructor priority parameters

- api/Window.json
Window.print() in FF Android deferred from 113 to 114 as mentioned in https://bugzilla.mozilla.org/show_bug.cgi?id=1809922#c8
> FF114 Android Window.print() update

- css/properties/clear.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `flow_relative_values` member of the `clear` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.1.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/clear/flow_relative_values
Additional Notes: As I don't have access to Safari 15 itself, this data is a bit of a guess.
> Update Safari data for css.properties.clear.flow_relative_values

- css/properties/float.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `flow_relative_values` member of the `float` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.1.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/float/flow_relative_values
Additional Notes: Safari 15 is a complete guesstimate as I don't have access to 15.0, only 14.1 and 15.1.
> Update Safari data for css.properties.float.flow_relative_values

- css/properties/list-style-type.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `list-style-type` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.1.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/list-style-type
Additional Notes: Safari 15 is a complete guesstimate as I don't have access to 15.0, only 14.1 and 15.1.
> Update Safari data for list-style-type CSS property

- css/properties/border-image-width.json
- css/properties/border-image.json
Note [bug 767352](https://bugs.chromium.org/p/chromium/issues/detail?id=767352) for `border-image` and `border-image-width`.
This was notable issue for Interop 2022. See https://github.com/web-platform-tests/interop/issues/146.
- https://github.com/web-platform-dx/feature-set/pull/160
> `border-image-width`: add notes about interop bug

- css/properties/text-combine-upright.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `text-combine-upright` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.1.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/text-combine-upright
> Update Safari data for text-combine-upright CSS property

- css/properties/quotes.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `quotes_auto` member of the `quotes` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.1.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/quotes/quotes_auto
Additional Notes: The note refers to behavior before the feature was supported, and doesn't seem appropriate to retain.
> Update Safari data for css.properties.quotes.quotes_auto

- api/WebTransport.json
- api/WebTransportBidirectionalStream.json
- api/WebTransportDatagramDuplexStream.json
- api/WebTransportError.json
FF113 nightly adds support for WebTransport and friends in https://bugzilla.mozilla.org/show_bug.cgi?id=1818754 (and behind pref in 109). 
The spec has several additions since the BCD before this revision. Tests indicate that Chrome does not implement those additions.
FF appears to fully follow the spec based on its IDL.
I have made updates to this all, along with adding MDN links.
FYI @queengooborg The BCD collector probably a bit out of date here:
WebTransport - 
- constructor - has some new options - a test on existence is not enough.
- allowPooling
- requireUnreliable
- serverCertificateHashes
- congestionControl
- createBidirectionalStream - takes option
- createUnidirectionalStream - take option
Other docs work for this can be tracked in https://github.com/mdn/content/issues/26153
> FF113 Web Transport API updates

- api/CompressionStream.json
- api/DecompressionStream.json
Fx113 adds support for CompressionStream, constructor and co
__tests:__
Manually ran through examples with nightly:
```js
// constructor
let stream = new CompressionStream("gzip");
console.log(stream);
// CompressionStream { readable: ReadableStream, writable: WritableStream } ...
console.log(stream.writable);
// WritableStream { locked: false }
console.log(stream.readable)
// ReadableStream { locked: false }
new CompressionStream("deflate")
// CompressionStream { readable: ReadableStream, writable: WritableStream }
new CompressionStream("deflate-raw")
// CompressionStream { readable: ReadableStream, writable: WritableStream }
```
Same for Decompression stream:
```js
// constructor
let dcstream = new DecompressionStream("gzip");
console.log(dcstream);
// DecompressionStream { readable: …
```
> relnote(Fx113): CompressionStream and sub-features supported by default

- css/properties/min-height.json
This PR updates and corrects version values for Firefox and Firefox Android for the `fit-content` member of the `min-height` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.0.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/min-height/fit-content
> Update Firefox data for css.properties.min-height.fit-content

- css/properties/rotate.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `x_y_z_angle` member of the `rotate` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.1.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/rotate/x_y_z_angle
> Update Safari data for css.properties.rotate.x_y_z_angle

- css/properties/scroll-margin-block-end.json
- css/properties/scroll-margin-block-start.json
- css/properties/scroll-margin-block.json
- css/properties/scroll-margin-inline-end.json
- css/properties/scroll-margin-inline-start.json
- css/properties/scroll-margin-inline.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `scroll-margin-*` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.1.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/scroll-margin-*
Additional Notes: Safari 15 is a complete guesstimate as I don't have access to 15.0, only 14.1 and 15.1.
> Update Safari data for scroll-margin-* CSS property

- css/properties/text-emphasis-position.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `text-emphasis-position` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.0.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/text-emphasis-position
> Update Chromium data for text-emphasis-position CSS property

- api/RTCPeerConnection.json
- api/RTCSctpTransport.json
FF113 supports `RTCSctpTransport` and `RTCPeerConnection.sctp` in https://bugzilla.mozilla.org/show_bug.cgi?id=1278299.
This updates the records. 
Other docs work can be tracked in https://github.com/mdn/content/issues/26146
> FF113 supports RTCSctpTransport and RTCPeerConnection.sctp

- api/RTCPeerConnection.json
FF113 supports `RTCPeerConnection.connectionState` and `changestatechange` event in https://bugzilla.mozilla.org/show_bug.cgi?id=1265827
Tested using https://mdn-bcd-collector.gooborg.com/tests/api/RTCPeerConnection/connectionState (and by inspection for the event)
Other docs work can be tracked in https://github.com/mdn/content/issues/26146
> FF113 RTCPeerConnection.connectionState and changestatechange event

- api/WebTransportReceiveStream.json
FF113 nightly adds support for WebTransport and friends in https://bugzilla.mozilla.org/show_bug.cgi?id=1818754 (and behind pref in 109). 
When doing docs discovered another object that is relevant `WebTransportReceiveStream` - object not in Chrome but shows up in FF.
This is a follow on from #19605
Other docs work for this can be tracked in https://github.com/mdn/content/issues/26153
> FF113 WebTransportReceiveStream - in nightly

- api/ScreenOrientation.json
FF111 adds support for `ScreenOrientation.lock()` in nightly in https://bugzilla.mozilla.org/show_bug.cgi?id=1767449
This is also behind a preference from FF97.
This adds the BCD entry. Related to https://github.com/mdn/content/pull/26444
> FF111 ScreenOrientation.lock() enabled preview (flag FF97)

- api/RTCRtpSender.json
FF113 adds support for `RTCRTPSender.getCapabilities()` and `RTCRTPSender.setStreams()` in https://bugzilla.mozilla.org/show_bug.cgi?id=1531460 and https://bugzilla.mozilla.org/show_bug.cgi?id=1510802 respectively. This just records the support.
@queengooborg FYI, the `getCapabilities` returns a [`RTCRtpCapabilities`](https://developer.mozilla.org/en-US/docs/Web/API/RTCRtpCapabilities). My assumption is that we don't need to have subfeatures for the returned object - i.e. it is treated like a parameter, in that you only create a subfeature if you know there is a compatibility issue.
Other docs work for this can be tracked in https://github.com/mdn/content/issues/26146
> FF113 RTCRTPSender.getCapabilities() and setStreams()

- webextensions/api/userScripts.json
BCD for `cookieStoreId` was added incorrectly and should have been included under `register`. 
Fixes #19164
> Correct cookieStoreId in userScript

- docs/data-guidelines/api.md
This PR adds a guideline for what to do regarding IDL dictionaries and enums.  As we are working to remove these from BCD, it should be explicitly stated that we do not want them documented separately from the interfaces that utilize them.
> Add data guideline for dictionaries/enums

- browsers/firefox.json
- browsers/firefox_android.json
Firefox 113 is now released.  This PR marks it as the current release version.  Additionally, this marks the current ESR release as retired, as 113 is the new ESR as well (confirmed by attempting to download Firefox ESR and checking the filename -- "Firefox Setup 113.*").
> Firefox 113 is released

- api/CookieStore.json
- http/headers/Set-Cookie.json
Cookies Having Independent State (CHIPS) was [documented on MDN](https://developer.mozilla.org/en-US/docs/Web/Privacy/Partitioned_cookies#browser_compatibility) a while ago, but the release then kept slipping, and it was hard to pinpoint where it was going to land.
Moving on a few months, CHIPs was officially released in [Chrome 114 beta](https://developer.chrome.com/blog/chrome-114-beta/#cookies-having-independent-partitioned-state-chips). This PR updates the compat data to reflect that.
> Correcting CHIPS data

- svg/elements/image.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Opera and Opera Android for the `image` SVG element. This sets Opera Android to mirror from upstream.
> Add Opera versions for image SVG element

- svg/elements/linearGradient.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Opera and Opera Android for the `linearGradient` SVG element. This sets Opera Android to mirror from upstream.
> Add Opera versions for linearGradient SVG element

- http/headers/Alt-Svc.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Safari (Desktop and iOS/iPadOS) for the `Alt-Svc` HTTP header. This fixes #19856, which is where the data comes from.
> Add Safari versions for Alt-Svc HTTP header

- svg/elements/use.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Chrome Android for the `use` SVG element. This sets Chrome Android to mirror from upstream.
> Add Chrome Android versions for use SVG element

- svg/elements/tspan.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Chrome Android for the `tspan` SVG element. This sets Chrome Android and Opera Android to mirror from upstream.
> Add Chrome Android versions for tspan SVG element

- svg/elements/tref.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Opera and Opera Android for the `tref` SVG element. This sets Opera Android to mirror from upstream.
> Add Opera versions for tref SVG element

- svg/elements/title.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Chrome Android for the `title` SVG element. This sets Chrome Android to mirror from upstream.
> Add Chrome Android versions for title SVG element

- svg/elements/textPath.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Opera and Opera Android for the `textPath` SVG element. This sets Opera to mirror from upstream.
> Add Opera versions for textPath SVG element

- svg/elements/text.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Chrome Android for the `text` SVG element. This sets both Chrome Android and Opera Android to mirror from upstream.
> Add Chrome Android versions for text SVG element

- svg/elements/symbol.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Opera and Opera Android for the `symbol` SVG element. This mirrors Opera to Opera Android.
> Add Opera versions for symbol SVG element

- svg/elements/svg.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Chrome Android for the `svg` SVG element. This mirrors Chrome to Chrome Android, and Opera to Opera Android.
> Add Chrome Android versions for svg SVG element

- svg/elements/switch.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Opera and Opera Android for the `switch` SVG element. This mirrors Opera to Opera Android.
> Add Opera versions for switch SVG element

- svg/elements/script.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Opera and Opera Android for the `script` SVG element. This mirrors Opera desktop to Opera Android.
> Add Opera versions for script SVG element

- svg/elements/stop.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Opera and Opera Android for the `stop` SVG element. This mirrors Opera desktop to Opera Android.
> Add Opera versions for stop SVG element

- svg/elements/rect.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `rect` SVG element. This sets derivative browsers to mirror from upstream.
> Add Chromium versions for rect SVG element

- svg/elements/radialGradient.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Opera and Opera Android for the `radialGradient` SVG element. This sets Opera Android to mirror from upstream.
> Add Opera versions for radialGradient SVG element

- svg/elements/polyline.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Chrome Android for the `polyline` SVG element. This sets Chrome Android to mirror from upstream.
> Add Chrome Android versions for polyline SVG element

- svg/elements/polygon.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Chrome Android for the `polygon` SVG element. This sets Chrome Android to mirror from upstream.
> Add Chrome Android versions for polygon SVG element

- svg/elements/pattern.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Microsoft Edge for the `href` member of the `pattern` SVG element. This sets Edge to mirror from upstream.
> Add Edge versions for svg.elements.pattern.href

- svg/elements/path.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Chrome Android for the `path` SVG element. This sets Chrome Android to mirror from upstream.
> Add Chrome Android versions for path SVG element

- svg/elements/metadata.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Chrome Android for the `metadata` SVG element. This sets Chrome Android to mirror from upstream.
> Add Chrome Android versions for metadata SVG element

- svg/elements/marker.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Chrome Android for the `marker` SVG element. This sets Chrome Android to mirror from upstream.
> Add Chrome Android versions for marker SVG element

- api/RTCStatsReport.json
The peer connection stats and audio and video stats in media-source are now dictionaries. Where I can, I have linked to the correct MDN places.
@queengooborg FYI This mismatch is a bit of a pain for links to MDN since you have something `kind` and `id` that appears in multiple places on MDN. I have fixed the ones that have a distinct link? Do you think it is better to have no link, or link to the RTCStatsReport if there is no better option.
Either way, this should be good to merge now.
> RTCStatsReport - stats - update links to corresponding dicts for peerconnection and some audio

- html/elements/a.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for all browsers for the `a` HTML element. This mirrors the data from the interface counterpart.
> Add all browsers versions for a HTML element

- html/elements/abbr.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `abbr` HTML element. This sets Chrome derivatives to mirror from upstream.
> Add Chromium versions for abbr HTML element

- html/elements/address.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Chrome and Safari for the `address` HTML element. This mirrors Safari to Chrome and Safari iOS.
> Add Chrome/Safari versions for address HTML element

- html/elements/area.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for all browsers for the `area` HTML element. This mirrors the data from the interface counterpart.
> Add all browsers versions for area HTML element

- html/elements/article.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `article` HTML element. This sets Chrome Android to mirror from upstream.
> Add Chromium versions for article HTML element

- html/elements/aside.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `aside` HTML element. This sets Chrome Android to mirror from upstream.
> Add Chromium versions for aside HTML element

- html/elements/audio.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Opera and Opera Android for the `audio` HTML element. This mirrors Opera to Opera Android.
> Add Opera versions for audio HTML element

- html/elements/b.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Chrome and Safari for the `b` HTML element. The data comes from manual testing, running test code through BrowserStack, SauceLabs and custom VMs.
Test Code:
```
<p>Hello <b>world</b>!</p>
```
> Add Chrome/Safari versions for b HTML element

- html/elements/base.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Chrome and Safari for the `base` HTML element. This mirrors the data from the interface counterpart.
> Add Chrome/Safari versions for base HTML element

- html/elements/bdo.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Chrome and Safari for the `bdo` HTML element. The data comes from manual testing, running test code through BrowserStack, SauceLabs and custom VMs.
Test Code: https://developer.mozilla.org/docs/Web/HTML/Element/bdo
> Add Chrome/Safari versions for bdo HTML element

- html/elements/big.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Chrome and Safari for the `big` HTML element. The data comes from manual testing, running test code through BrowserStack, SauceLabs and custom VMs.
Test Code:
```
<p>Hello <big>world!</big></p>
```
> Add Chrome/Safari versions for big HTML element

- html/elements/body.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Chrome and Safari for the `body` HTML element. This data comes from lots and lots of prior testing.
> Add Chrome/Safari versions for body HTML element

- html/elements/br.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Chrome and Safari for the `br` HTML element. Chromium derivatives are set to mirror from upstream, and Safari is mirrored from Chrome.
> Add Chrome/Safari versions for br HTML element

- html/elements/center.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for all browsers for the `center` HTML element. The data comes from manual testing, running test code through BrowserStack, SauceLabs and custom VMs.
Test Code:
```
<center>Hello world!</center>
```
> Add all browsers versions for center HTML element

- html/elements/code.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Chrome and Safari for the `code` HTML element. Chromium derivatives are set to mirror from upstream, and Safari is mirrored from Chrome.
> Add Chrome/Safari versions for code HTML element

- html/elements/col.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Chrome and Safari for the `col` HTML element. Chromium derivatives are set to mirror from upstream, and Safari is mirrored from Chrome.
> Add Chrome/Safari versions for col HTML element

- html/elements/colgroup.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Chrome and Safari for the `colgroup` HTML element. Chromium derivatives are set to mirror from upstream, and Safari is mirrored from Chrome.
> Add Chrome/Safari versions for colgroup HTML element

- html/elements/dd.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Chrome and Safari for the `dd` HTML element. The data comes from manual testing, running test code through BrowserStack, SauceLabs and custom VMs.
Test Code: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dd
> Add Chrome/Safari versions for dd HTML element

- html/elements/dt.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Chrome and Safari for the `dt` HTML element. The data comes from manual testing, running test code through BrowserStack, SauceLabs and custom VMs.
Test Code: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dd
> Add Chrome/Safari versions for dt HTML element

- html/elements/dl.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Chrome and Safari for the `dl` HTML element. The data comes from manual testing, running test code through BrowserStack, SauceLabs and custom VMs.
Test Code: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dd
> Add Chrome/Safari versions for dl HTML element

- html/elements/del.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Chrome and Safari for the `del` HTML element. The data comes from manual testing, running test code through BrowserStack, SauceLabs and custom VMs.
Test Code:
```
<blockquote>There is <del>nothing</del> <ins>no code</ins> either good or bad, but <del>thinking</del> <ins>running it</ins> makes it so.</blockquote>
```
> Add Chrome/Safari versions for del HTML element

- html/elements/dfn.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Chrome and Safari for the `dfn` HTML element. The data comes from manual testing, running test code through BrowserStack, SauceLabs and custom VMs.
Test Code:
```
<p>A <dfn id="def-validator">validator</dfn> is a program that checks for syntax errors in code or documents.</p>
```
> Add Chrome/Safari versions for dfn HTML element

- html/elements/div.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Chrome and Safari for the `div` HTML element. This data comes from lots and lots of previous testing.
> Add Chrome/Safari versions for div HTML element

- html/elements/em.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Chrome and Safari for the `em` HTML element. The data comes from manual testing, running test code through BrowserStack, SauceLabs and custom VMs.
Test Code:
```
<p>Hello <em>world</em>!</p>
```
> Add Chrome/Safari versions for em HTML element

- html/elements/fieldset.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Chrome and Safari for the `fieldset` HTML element. The data comes from manual testing, running test code through BrowserStack, SauceLabs and custom VMs.
Test Code: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/fieldset
> Add Chrome/Safari versions for fieldset HTML element

- html/elements/figcaption.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `figcaption` HTML element. This sets Chrome Android to mirror from upstream.
> Add Chromium versions for figcaption HTML element

- html/elements/figure.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `figure` HTML element. This sets Chrome Android to mirror from upstream.
> Add Chromium versions for figure HTML element

- html/elements/font.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for all browsers for the `font` HTML element. The data comes from manual testing, running test code through BrowserStack, SauceLabs and custom VMs.
Test Code:
```
<p>Hello <font color="red" face="monospace" size="16pt">world!</font></p>
```
> Add all browsers versions for font HTML element

- html/elements/form.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for all browsers for the `form` HTML element. This data comes from lots and lots of prior testing; the mdn-bcd-collector uses a `form` element as a critical component, and would not function without it.
> Add all browsers versions for form HTML element

- html/elements/footer.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `footer` HTML element. This sets Chrome Android to mirror from upstream.
> Add Chromium versions for footer HTML element

- html/elements/head.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Chrome and Safari for the `head` HTML element. This mirrors data from the interface counterpart.
> Add Chrome/Safari versions for head HTML element

- html/elements/hgroup.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `hgroup` HTML element. This sets Chrome Android to mirror from upstream.
> Add Chromium versions for hgroup HTML element

- html/elements/html.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for all browsers for the `html` HTML element. This comes from lots and lots of previous tests.
> Add all browsers versions for html HTML element

- html/elements/i.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Chrome and Safari for the `i` HTML element. The data comes from manual testing, running test code through BrowserStack, SauceLabs and custom VMs.
Test Code:
```
<p>Hello <i>world!</i></p>
```
> Add Chrome/Safari versions for i HTML element

- html/elements/image.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for all browsers for the `image` HTML element. The data comes from manual testing, running test code through BrowserStack, SauceLabs and custom VMs.
Test Code:
```
<image src="/static/images/background.jpg" />
```
> Add all browsers versions for image HTML element

- html/elements/img.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for all browsers for the `img` HTML element. The data comes from manual testing, running test code through BrowserStack, SauceLabs and custom VMs.
Test Code:
```
```
> Add all browsers versions for img HTML element

- html/elements/input.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `input` HTML element. The data is mirrored from the interface counterpart.
> Add Chromium versions for input HTML element

- html/elements/link.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for all browsers for the `link` HTML element. Chromium derivatives are set to mirror from upstream, and Safari is mirrored from Chrome.
> Add all browsers versions for link HTML element

- html/elements/main.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `main` HTML element. This sets Chrome Android to mirror from upstream.
> Add Chromium versions for main HTML element

- html/elements/map.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Chrome and Safari for the `map` HTML element. Chromium derivatives are set to mirror from upstream, and Safari is mirrored from Chrome.
> Add Chrome/Safari versions for map HTML element

- html/elements/mark.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Chrome and Safari for the `mark` HTML element. The data comes from manual testing, running test code through BrowserStack, SauceLabs and custom VMs.
Test Code:
```
<p>Several species of <mark>salamander</mark> inhabit the temperate rainforest of the Pacific Northwest.</p>
```
> Add Chrome/Safari versions for mark HTML element

- html/elements/nav.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `nav` HTML element. Chrome Android is set to mirror from upstream.
> Add Chromium versions for nav HTML element

- html/elements/nobr.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for all browsers for the `nobr` HTML element. The data comes from manual testing, running test code through BrowserStack, SauceLabs and custom VMs.
Test Code:
```
<nobr>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</nobr>
```
> Add all browsers versions for nobr HTML element

- html/elements/ol.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Chrome and Safari for the `ol` HTML element. The data comes from manual testing, running test code through BrowserStack, SauceLabs and custom VMs.
Test Code: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ol
> Add Chrome/Safari versions for ol HTML element

- html/elements/ul.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Chrome and Safari for the `ul` HTML element. The data comes from manual testing, running test code through BrowserStack, SauceLabs and custom VMs.
Test Code: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ul
> Add Chrome/Safari versions for ul HTML element

- html/elements/optgroup.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Chrome and Safari for the `optgroup` HTML element. Chromium derivatives are set to mirror from upstream, and Safari is mirrored from Chrome.
> Add Chrome/Safari versions for optgroup HTML element

- html/elements/option.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Chrome and Safari for the `option` HTML element.  Chromium derivatives are set to mirror from upstream, and Safari is mirrored from Chrome.
> Add Chrome/Safari versions for option HTML element

- html/elements/output.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Chrome and Safari for the `output` HTML element. Chromium derivatives are set to mirror, and Safari is mirrored from Chrome.
> Add Chrome/Safari versions for output HTML element

- html/elements/p.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Chrome and Safari for the `p` HTML element. This data comes from loads and loads of prior tests with this element included.
> Add Chrome/Safari versions for p HTML element

- html/elements/param.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Chrome and Safari for the `param` HTML element. This sets all Chromium forks to mirror from upstream, and Safari is mirrored from Chrome.
> Add Chrome/Safari versions for param HTML element

- html/elements/pre.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Chrome and Safari for the `pre` HTML element. The data comes from manual testing, running test code through BrowserStack, SauceLabs and custom VMs.
Test Code: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/pre
> Add Chrome/Safari versions for pre HTML element

- html/elements/progress.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `progress` HTML element. This sets Chrome Android to mirror from upstream.
> Add Chromium versions for progress HTML element

- html/elements/q.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Chrome and Safari for the `q` HTML element. This data is mirrored from the interface counterpart.
> Add Chrome/Safari versions for q HTML element

- html/elements/rb.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Chrome and Safari for the `rb` HTML element. This sets derivative browsers to mirror from upstream.
> Add Chrome/Safari versions for rb HTML element

- html/elements/rp.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Chrome and Safari for the `rp` HTML element. This sets derivative browsers to mirror from upstream.
> Add Chrome/Safari versions for rp HTML element

- html/elements/rt.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Chrome and Safari for the `rt` HTML element. This sets derivative browsers to mirror from upstream.
> Add Chrome/Safari versions for rt HTML element

- html/elements/ruby.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Chrome and Safari for the `ruby` HTML element. This sets derivative browsers to mirror from upstream.
> Add Chrome/Safari versions for ruby HTML element

- html/elements/s.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Chrome and Safari for the `s` HTML element. The data comes from manual testing, running test code through BrowserStack, SauceLabs and custom VMs.
Test Code:
```
<p><s>There will be a few tickets available at the box office tonight.</s></p>
```
> Add Chrome/Safari versions for s HTML element

- html/elements/samp.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Chrome and Safari for the `samp` HTML element. The data comes from manual testing, running test code through BrowserStack, SauceLabs and custom VMs.
Test Code:
```
<p><samp>Keyboard not found <br>Press F1 to continue</samp></p>
```
> Add Chrome/Safari versions for samp HTML element

- html/elements/script.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Chrome and Safari for the `script` HTML element. The primary data is mirrored from the interface counterpart.  Derivatives are set to mirror from upstream, and Safari mirrors from Chrome.
> Add Chrome/Safari versions for script HTML element

- html/elements/section.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `section` HTML element. This sets Chrome Android to mirror from upstream.
> Add Chromium versions for section HTML element

- html/elements/select.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Chrome and Safari for the `select` HTML element. All data is mirrored from the interface counterpart.
> Add Chrome/Safari versions for select HTML element

- html/elements/small.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Chrome and Safari for the `small` HTML element. This mirrors data from https://github.com/mdn/browser-compat-data/pull/19657 (it doesn't make sense for `<big>` to be supported and `<small>` not to be).
> Add Chrome/Safari versions for small HTML element

- html/elements/source.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Chrome and Safari for the `source` HTML element. This mirrors data from the interface counterpart.
> Add Chrome/Safari versions for source HTML element

- html/elements/span.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Chrome and Safari for the `span` HTML element. This data comes from loads and loads of prior tests.
> Add Chrome/Safari versions for span HTML element

- html/elements/strike.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for all browsers for the `strike` HTML element. <p><strike>There will be a few tickets available at the box office tonight.</strike></p>
> Add all browsers versions for strike HTML element

- html/elements/sub.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Chrome and Safari for the `sub` HTML element. The data comes from manual testing, running test code through BrowserStack, SauceLabs and custom VMs.
Test Code:
```
<p>Almost every developer's favorite molecule is C<sub>8</sub>H<sub>10</sub>N<sub>4</sub>O<sub>2</sub>, also known as "caffeine."<sup>[1]</sup></p>
```
> Add Chrome/Safari versions for sub HTML element

- html/elements/sup.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Chrome and Safari for the `sup` HTML element. The data comes from manual testing, running test code through BrowserStack, SauceLabs and custom VMs.
Test Code:
```
<p>Almost every developer's favorite molecule is C<sub>8</sub>H<sub>10</sub>N<sub>4</sub>O<sub>2</sub>, also known as "caffeine."<sup>[1]</sup></p>
```
> Add Chrome/Safari versions for sup HTML element

- html/elements/summary.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Chrome and Safari for the `summary` HTML element. This sets derivative browsers to mirror from upstream.
> Add Chrome/Safari versions for summary HTML element

- html/elements/table.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Chrome and Safari for the `table` HTML element. This data comes from lots and lots of prior testing.
> Add Chrome/Safari versions for table HTML element

- html/elements/tbody.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Chrome and Safari for the `tbody` HTML element. This data comes from lots and lots of prior testing.
> Add Chrome/Safari versions for tbody HTML element

- html/elements/td.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Chrome and Safari for the `td` HTML element. This data comes from lots and lots of prior testing.
> Add Chrome/Safari versions for td HTML element

- html/elements/template.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Opera and Opera Android for the `template` HTML element. This sets Opera to mirror from upstream.
> Add Opera versions for template HTML element

- html/elements/textarea.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for all browsers for the `textarea` HTML element. The data comes from manual testing, running test code through BrowserStack, SauceLabs and custom VMs.
Test Code: https://developer.mozilla.org/docs/Web/HTML/Element/textarea
> Add all browsers versions for textarea HTML element

- html/elements/tfoot.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Chrome and Safari for the `tfoot` HTML element. This data comes from lots and lots of prior testing.
> Add Chrome/Safari versions for tfoot HTML element

- html/elements/th.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Chrome and Safari for the `th` HTML element. This data comes from lots and lots of prior testing.
> Add Chrome/Safari versions for th HTML element

- html/elements/thead.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Chrome and Safari for the `thead` HTML element. This data comes from lots and lots of prior testing.
> Add Chrome/Safari versions for thead HTML element

- html/elements/title.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Chrome and Safari for the `title` HTML element. This sets derivatives to mirror from upstream.
> Add Chrome/Safari versions for title HTML element

- html/elements/tr.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Chrome and Safari for the `tr` HTML element. This data comes from lots and lots of prior testing.
> Add Chrome/Safari versions for tr HTML element

- html/elements/track.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Chrome and Safari for the `track` HTML element. This sets all derivative browsers to mirror from upstream.
> Add Chrome/Safari versions for track HTML element

- html/elements/tt.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for all browsers for the `tt` HTML element. The data comes from manual testing, running test code through BrowserStack, SauceLabs and custom VMs.
Test Code: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/tt#basic_example
> Add all browsers versions for tt HTML element

- html/elements/u.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Chrome and Safari for the `u` HTML element. The data comes from manual testing, running test code through BrowserStack, SauceLabs and custom VMs.
Test Code: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/u
> Add Chrome/Safari versions for u HTML element

- html/elements/var.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Chrome and Safari for the `var` HTML element. The data comes from manual testing, running test code through BrowserStack, SauceLabs and custom VMs.
Test Code: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/var
> Add Chrome/Safari versions for var HTML element

- html/elements/video.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `video` HTML element. This sets Chrome Android to mirror from upstream.
> Add Chromium versions for video HTML element

- html/elements/wbr.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Chrome and Safari for the `wbr` HTML element. This sets derivative browsers to mirror from upstream.
> Add Chrome/Safari versions for wbr HTML element

- html/elements/xmp.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Chrome and Safari for the `xmp` HTML element. The data comes from manual testing, running test code through BrowserStack, SauceLabs and custom VMs.
Test Code:
```
<xmp>
L          TE
A       A
C    V
R A
DOU
LOU
REUSE
QUE TU
PORTES
ET QUI T'
ORNE O CI
VILISÉ
OTE-  TU VEUX
LA    BIEN
SI      RESPI
RER       - Apollinaire
</xmp>
```
> Add Chrome/Safari versions for xmp HTML element

- css/properties/animation-timeline.json
_👋 Hi, Chrome DevRel here!_
Chromium supports `animation-timeline`, behind a flag, as of version 85.
CL: https://chromium-review.googlesource.com/c/chromium/src/+/2223950
Version Info for commit: https://chromiumdash.appspot.com/commit/cdc482ffdb53bfacb937b286b8a6f4bd91211026
> Update animation-timeline support

- css/properties/shape-outside.json
Fixes https://github.com/mdn/browser-compat-data/issues/19228
This is an extension of the fix in https://github.com/mdn/content/pull/25588.
The `path()` entry is missing in the browser compat table for the [`shape-outside`](https://developer.mozilla.org/en-US/docs/Web/CSS/shape-outside#browser_compatibility) property.
The information for `path()` is copied from the browser compat on the [basic-shape](https://developer.mozilla.org/en-US/docs/Web/CSS/basic-shape#browser_compatibility) page.
Source: https://github.com/mdn/browser-compat-data/blob/6b29afce285316f9ab233729777550898781d848/css/types/basic-shape.json#L177-L227).
https://github.com/mdn/content/issues/9703
> Add path() to browser compat table of shape-outside property

- svg/elements/a.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `a` SVG element. This sets Chrome Android to mirror from upstream.
> Add Chromium versions for a SVG element

- svg/elements/circle.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `circle` SVG element. This sets Chrome Android to mirror from upstream.
> Add Chromium versions for circle SVG element

- svg/elements/clipPath.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Chrome Android for the `clipPath` SVG element. This sets Chrome Android to mirror from upstream.
> Add Chrome Android versions for clipPath SVG element

- svg/elements/cursor.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Microsoft Edge for the `cursor` SVG element. This sets Edge to mirror from upstream.
> Add Edge versions for cursor SVG element

- svg/elements/defs.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Opera and Opera Android for the `defs` SVG element. This mirrors Opera Desktop to Opera Android.
> Add Opera versions for defs SVG element

- svg/elements/desc.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Opera and Opera Android for the `desc` SVG element. This mirrors Opera Desktop to Opera Android.
> Add Opera versions for desc SVG element

- svg/elements/ellipse.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Chrome Android for the `ellipse` SVG element. This sets Chrome Android to mirror from upstream.
> Add Chrome Android versions for ellipse SVG element

- svg/elements/feBlend.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for all browsers for the `feBlend` SVG element. This sets Firefox Android and Opera Android to mirror from upstream.
> Add all browsers versions for feBlend SVG element

- svg/elements/feColorMatrix.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Opera and Opera Android for the `feColorMatrix` SVG element. This sets Opera Android to mirror from upstream.
> Add Opera versions for feColorMatrix SVG element

- svg/elements/feComposite.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Chrome and Safari for the `feComposite` SVG element. This sets Chrome Android to mirror from upstream, and mirrors Chrome to Safari (given when the entire features was supported).
> Add Chrome/Safari versions for feComposite SVG element

- svg/elements/feConvolveMatrix.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Opera and Opera Android for the `feConvolveMatrix` SVG element. This sets Opera Android to mirror from upstream.
> Add Opera versions for feConvolveMatrix SVG element

- svg/elements/feDiffuseLighting.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Opera and Opera Android for the `feDiffuseLighting` SVG element. This sets Opera Android to mirror from upstream.
> Add Opera versions for feDiffuseLighting SVG element

- svg/elements/feDisplacementMap.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Opera and Opera Android for the `feDisplacementMap` SVG element. This sets Opera Android to mirror from upstream.
> Add Opera versions for feDisplacementMap SVG element

- svg/elements/feFlood.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Opera and Opera Android for the `feFlood` SVG element. svg.elements.feFlood
> Add Opera versions for feFlood SVG element

- svg/elements/feGaussianBlur.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Firefox Android for the `feGaussianBlur` SVG element. This sets Firefox Android to mirror from upstream.
> Add Firefox Android versions for feGaussianBlur SVG element

- svg/elements/feImage.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for all browsers for the `feImage` SVG element. This sets derivative browsers to mirror from upstream.
> Add all browsers versions for feImage SVG element

- svg/elements/feMerge.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for all browsers for the `feMerge` SVG element. This sets derivative browsers to mirror from upstream.
> Add all browsers versions for feMerge SVG element

- svg/elements/feMergeNode.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for all browsers for the `feMergeNode` SVG element. This sets derivative browsers to mirror from upstream.
> Add all browsers versions for feMergeNode SVG element

- svg/elements/feMorphology.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Opera and Opera Android for the `feMorphology` SVG element. This sets Opera Android to mirror from upstream.
> Add Opera versions for feMorphology SVG element

- svg/elements/feOffset.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for all browsers for the `feOffset` SVG element. This sets derivative browsers to mirror from upstream.
> Add all browsers versions for feOffset SVG element

- svg/elements/fePointLight.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for all browsers for the `fePointLight` SVG element. This sets derivative browsers to mirror from upstream.
> Add all browsers versions for fePointLight SVG element

- svg/elements/feSpotLight.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for all browsers for the `feSpotLight` SVG element. This sets derivative browsers to mirror from upstream.
> Add all browsers versions for feSpotLight SVG element

- api/HTMLImageElement.json
- api/HTMLLinkElement.json
- api/HTMLScriptElement.json
- html/elements/img.json
- html/elements/link.json
- html/elements/script.json
Safari Tech Preview no has support for fetchpriority (formally known as Priority Hints).
Tested locally, as per below screenshot
https://bugs.webkit.org/show_bug.cgi?id=252739
> Add Safari Tech Preview support for fetchpriority

- api/_globals/structuredClone.json
Mirror all Chromium-based browsers. Support in Opera 84 was confirmed
using https://mdn-bcd-collector.gooborg.com/tests/api/structuredClone.
Support in Safari 15.6 was confirmed using the same test, so assume
support goes back to 15.4.
> Update worker support for structuredClone()

- css/properties/text-wrap.json
- css/properties/white-space-collapse.json
- css/properties/white-space.json
Chrome 114 adds the `text-wrap` and `white-space-collapse` CSS properties, and updates the `white-space` property with new behavior — as well as taking its usual keywords, it can now act as a shorthand property for `text-wrap` and `white-space-collapse`. These items are specified in [CSS Text Level 4](https://www.w3.org/TR/css-text-4/).
This PR adds compat data for those items.
Note - there is another related property, `white-space-trim`, which is specced as being included in the `white-space` shorthand value, but this is not supported yet so I have not added it.
My [research document](https://docs.google.com/document/d/1de7T6UbSEcDvKKmyqz-yS3D2CS7XT67mxFjHhzKYlMc/edit#) provides additional details about this overall project and its required changes.
I used …
> Add text-wrap and white-space-collapse, and update white-space

- css/at-rules/container.json
This PR removes the redundant MDN URL from the specified feature, which just links to the page of its parent feature.  Fixes #19836.
> Remove poor mdn_url for css.at-rules.container.style_queries_for_custom_properties

- javascript/builtins/Intl/Locale.json
Similarly to [Release 99 Intl.Locale Chromium adds support for some new properties](https://github.com/mdn/browser-compat-data/pull/15505) Node.js shipped with V8 engine version 10.1 in release 18.0.0 with one of the highlights compared to the version included in Node.js 17.9.0 being(from [CHANGELOG_V18](https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V18.md)):
- Improvements to the [`Intl.Locale` API](https://v8.dev/blog/v8-release-99#intl.locale-extensions).
Changes are straightforward and same as Chrome support.
> Add Node 18.0.0 for new Intl.Locale properties

- api/CanvasRenderingContext2D.json
The prop `mozImageSmoothingEnabled` is deprecated for a long time and is now no longer supported in Fx. It looks like the other vendor prefixes for `CanvasRenderingContext2D.{prefix}ImageSmoothingEnabled` may also be removed if that makes sense in the interest of housekeeping.
__Bugzilla:__
- Tracking bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1228850
__Other resources:__
* Intent to Remove: CanvasRenderingContext2D.webkitImageSmoothingEnabled https://groups.google.com/a/chromium.org/g/blink-dev/c/qeFgqezm0cM/m/z708BVaGAAAJ
* https://chromestatus.com/metrics/feature/timeline/popularity/267
> docs(relnote): Fx114 - dropping mozImageSmoothingEnabled & other deprecated prefixes

- css/at-rules/media.json
Fx114 adds support for [`inverted-colors`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/inverted-colors) behind the` layout.css.inverted-colors.enabled` flag.
Tested on Firefox Nightly and Beta behind the flag. The documented [example](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/inverted-colors#examples) works as expected.
(On mac, Settings > Accessibility > Display > "Invert colors" option)
Doc issue: https://github.com/mdn/content/issues/26691
Bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1794628
Spec: https://drafts.csswg.org/mediaqueries-5/#inverted
> Fx114: inverted-colors is supported behind flag

- browsers/safari.json
- browsers/safari_ios.json
For https://github.com/mdn/browser-compat-data/pull/19831
https://developer.apple.com/documentation/safari-release-notes/safari-16_5-release-notes
> Add Safari 16.5 as a beta browser

- http/headers/Clear-Site-Data.json
FF114 removes this in https://bugzilla.mozilla.org/show_bug.cgi?id=1821651
Other docs work for this can be tracked in https://github.com/mdn/content/issues/26246
> FF114 remove cache directive from HTTP  Clear-Site-Data

- browsers/chrome.json
- browsers/chrome_android.json
- browsers/webview_android.json
Hi all! 👋
Updating Chrome to version 113.
And according to https://chromiumdash.appspot.com/schedule, it also includes Chrome 115 release date.
> Updates chrome browser to version 113

- css/types/image.json
This PR adds the links to a Mozilla bug for supporting `<color-interpolation-method>` and `<hue-interpolation-method>` in CSS gradient functions.
Mozilla Bug 1824041:
https://bugzilla.mozilla.org/show_bug.cgi?id=1824041
Relates to https://github.com/mdn/content/pull/26775.
> Update Firefox statuses related to color interpolation methods

- api/WEBGL_compressed_texture_etc1.json
Fix https://github.com/mdn/browser-compat-data/issues/19827
I've used the same version numbers as `_etc` (https://developer.mozilla.org/en-US/docs/Web/API/WEBGL_compressed_texture_etc) given https://bugs.webkit.org/show_bug.cgi?id=197900 mentions both.
> Update Safari versions for etc1 compressed textures

- api/WebTransport.json
Just found out in https://bugzilla.mozilla.org/show_bug.cgi?id=1818754#c15 that FF does not implement the server certificate option. This wasn't at all clear in IDL or anything else. I've asked about other things that might be omitted, but we should get this in now.
This is part of https://github.com/mdn/content/issues/26684
> WebTransport API - FF does not support server certificate option

- css/at-rules/import.json
This adds BCD data for the `@import` `supports()` option. It's behind a pref and enabled in nightly in https://bugzilla.mozilla.org/show_bug.cgi?id=1427715
I checked support in latest chrome/safari/FF using http://wpt.live/css/css-cascade/import-conditions.html
Other docs work for this can be tracked in https://github.com/mdn/content/issues/26692
> FF114 @import supports() is implemented

- html/elements/a.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Firefox and Firefox Android for the `coords` member of the `a` HTML element. This mirrors the version number from the interface counterpart.
> Add Firefox versions for html.elements.a.coords

- api/DataTransfer.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `items` member of the `DataTransfer` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.2.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/DataTransfer/items
> Update Chromium data for api.DataTransfer.items

- docs/contributing.md
This updates the URL that points to the collector's documentation on how to update BCD using its own tooling, following a documentation overhaul.
> Update collector doc URL

- scripts/release/mirror.ts
This PR updates the regex for notes replacement to prevent "ChromeOS" becoming "EdgeOS", "OperaOS" and similar.
> Prevent ChromeOS -> EdgeOS/OperaOS/etc.

- api/MerchantValidationEvent.json
This PR updates and corrects version values for Firefox and Firefox Android for the `MerchantValidationEvent` API. This replaces the version number with "preview" as it is only available in nightly builds of Firefox and should not have a version number associated accordingly.  Flag data is also propogated down to subfeatures as per our guidelines.
> Update Firefox data for MerchantValidationEvent API

- api/MouseEvent.json
This PR updates and corrects version values for Firefox and Firefox Android for the `region` member of the `MouseEvent` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.2.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/MouseEvent/region
> Update Firefox data for api.MouseEvent.region

- api/BeforeInstallPromptEvent.json
This came up in the course of https://github.com/mdn/content/pull/26828. 
The interface on which [`BeforeInstallPromptEvent.prompt()`](https://developer.mozilla.org/en-US/docs/Web/API/BeforeInstallPromptEvent/prompt) is defined is itself [marked non-standard](https://github.com/mdn/browser-compat-data/blob/main/api/BeforeInstallPromptEvent.json#L33), so it doesn't seem to make sense for its members to be standard track.
The Chromium implementation differs from the https://wicg.github.io/manifest-incubation spec in a few ways. It seems silly to document this spec that's (AFAIK) only implemented at all in Chromium, and then document all the ways the Chromium implementation differs from it.
So in my mdn/content PR I've documented this object according to the reality of what's in Chrome. This …
> BeforeInstallPromptEvent.prompt() is non-standard

- html/elements/a.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Chrome and Safari for the `href.href_top` member of the `a` HTML element. The data comes from manual testing, running test code through BrowserStack, SauceLabs and custom VMs.
Test Code:
```
<div style="height: 8000px"></div><a href="#top">Go to top!</a>
```
> Add Chrome/Safari versions for html.elements.a.href.href_top

- api/Performance.json
This PR updates and corrects version values for Firefox and Firefox Android for the `mark` member of the `Performance` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.2.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/Performance/mark
Additional Notes: These were originally set to 103 in https://github.com/mdn/browser-compat-data/pull/18229, but I think that the commit may have been pulled into an earlier branch.
> Update Firefox data for api.Performance.mark

- html/elements/a.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `download` member of the `a` HTML element. This sets derivative browsers of Chrome to mirror from upstream, and manually mirrors a note to Edge.
> Update Chromium data for html.elements.a.download

- css/properties/scrollbar-width.json
Chrome as of 115 Canary now supports the scrollbar-width CSS property behind the experimental flag.
https://chromium-review.googlesource.com/c/chromium/src/+/4536495 - Here's my merged chromium patch that moved this under experimental flag.
Can test in latest canary by running one of the WPT https://wpt.live/css/css-scrollbars/scrollbar-width-parsing.html
> Add flagged Chrome support for scrollbar-width

- css/properties/background-image.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `image-set` member of the `background-image` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.2.2).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/background-image/image-set
> Update Chromium data for css.properties.background-image.image-set

- api/WorkerNavigator.json
This PR updates and corrects version values for Firefox and Firefox Android for the `locks` member of the `WorkerNavigator` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.2.2).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/WorkerNavigator/locks
> Update Firefox data for api.WorkerNavigator.locks

- api/MathMLElement.json
This PR updates and corrects version values for Microsoft Edge for the `attributeStyleMap` member of the `MathMLElement` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.2.2).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/MathMLElement/attributeStyleMap
> Update Edge data for api.MathMLElement.attributeStyleMap

- api/InstallEvent.json
This PR updates and corrects version values for Firefox and Firefox Android for the `InstallEvent` member of the `InstallEvent` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.2.2).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/InstallEvent/InstallEvent
> Update Firefox data for api.InstallEvent.InstallEvent

- api/CSSStyleRule.json
This PR is a part of a project to add missing interfaces and interface features to BCD that are from an active spec (including WICG specs) and is supported in at least one browser. This particular PR adds the missing features of the `CSSStyleRule` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.2.2).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/CSSStyleRule
> Add missing features for CSSStyleRule API

- api/RTCRtpReceiver.json
This PR updates and corrects version values for Firefox and Firefox Android for the `getCapabilities` member of the `RTCRtpReceiver` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.2.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/RTCRtpReceiver/getCapabilities
> Update Firefox data for api.RTCRtpReceiver.getCapabilities

- api/RTCDtlsTransport.json
This PR updates and corrects version values for Firefox and Firefox Android for the `RTCDtlsTransport` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.2.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/RTCDtlsTransport
Additional Notes: The event data was guesstimated as the collector doesn't update event data.
> Update Firefox data for RTCDtlsTransport API

- webextensions/api/webNavigation.json
As noted in #10456, the BCD includes notes about supported features in Edge and Opera for releases prior to the switch of those browsers to Chromium. As the pre-Chromium releases are unlikely to be targets for web extension deployment, took the opportunity to "mirror" all.
Fixes #10456
> webNavigation support in Edge and Opera

- api/ServiceWorker.json
- api/SharedWorker.json
- api/Worker.json
- api/Worklet.json
- javascript/operators/import.json
- javascript/statements.json
FF114 ships support for worker modules (dynamic and static) in https://bugzilla.mozilla.org/show_bug.cgi?id=1812591
This replaces the preference with a release.
Other docs work for this can be tracked in https://github.com/mdn/content/issues/26695
Note, draft as I am checking if there are any other notes/compatibility or this is "full support" - I pretty much think it is, but no reason not to wait for answer to https://bugzilla.mozilla.org/show_bug.cgi?id=1812591#c11
> FF114 Module import in workers and worklets - dynamic/static

- api/CanvasFilter.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `CanvasFilter` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.2.2).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/CanvasFilter
> Update Chromium data for CanvasFilter API

- api/WebTransport.json
This was shipped in 114 as part of https://bugzilla.mozilla.org/show_bug.cgi?id=1831073 
I ran the collector for the other platforms to confirm not supported.
Omission noticed by @Elchi3  in  https://github.com/mdn/content/pull/26529#pullrequestreview-1434373382
Other docs work for this tracked in https://github.com/mdn/content/issues/26684
> FF114 WebTransport.reliability supported

- api/RTCStatsReport.json
This PR is a part of a project to add missing interfaces and interface features to BCD that are from an active spec (including WICG specs) and is supported in at least one browser. This particular PR adds the missing features of the `@@iterator` member of the `RTCStatsReport` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.2.2).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/RTCStatsReport/@@iterator
> Add missing features for api.RTCStatsReport.@@iterator

- api/SVGElement.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `focus.options_preventScroll_parameter` member of the `SVGElement` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.2.2).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/SVGElement/focus/options_preventScroll_parameter
Additional Notes: I don't have access to Safari 15.0, so it is a guesstimation.
> Update Safari data for api.SVGElement.focus.options_preventScroll_parameter

- html/global_attributes.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for all browsers for the `global_attributes` HTML feature. This data comes from a series of manual tests to check if the behavior is as expected.
> Add all browsers versions for global_attributes HTML feature

- css/selectors/nesting.json
Update Safari support for CSS nesting selector
https://webkit.org/blog/14154/webkit-features-in-safari-16-5/#:~:text=to%20Lockdown%20Mode.-,CSS%20Nesting,-Safari%2016.5%20includes
> Add Safari support for nesting

- api/Window.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `showModalDialog` member of the `Window` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.2.2).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/Window/showModalDialog
> Update Safari data for api.Window.showModalDialog

- http/headers/Cookie.json
- http/headers/Set-Cookie.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `Cookie` and `Set-Cookie` headers.
Tested using https://www.browserling.com/ Chrome on version 1 and Opera on version 10.
> Update Chromium and Opera versions for Cookie and Set-Cookie headers

- html/elements/embed.json
This PR replaces `true`/`null` values with exact version numbers (or `false`) for Chrome and Safari for the `embed` HTML element. Since the subfeatures are set to Chrome 1 and Safari ≤4, this is a non-trivial change.
> Add Chrome/Safari versions for embed HTML element

- api/HTMLButtonElement.json
- api/HTMLElement.json
- api/HTMLInputElement.json
- api/ToggleEvent.json
- css/selectors/backdrop.json
- css/selectors/popover-open.json
- html/global_attributes.json
FF114 supports popover Javascript API in https://bugzilla.mozilla.org/show_bug.cgi?id=1823757 behind the pref `dom.element.popover.enabled`
This includes:
- [`HTMLButtonElement.popoverTargetAction`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLButtonElement/popoverTargetAction)
- [`HTMLButtonElement.popoverTargetElement`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLButtonElement/popoverTargetElement)
- [`HTMLInputElement.popoverTargetElement`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/popoverTargetElement),
- [`HTMLInputElement.popoverTargetAction`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/popoverTargetAction) 
- [`HTMLElement.popover`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/popover) 
- …
> FF114 Popover API behind preference

- api/Window.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `orientation` member of the `Window` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.3.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/Window/orientation
> Update Safari data for api.Window.orientation

- api/WorkerGlobalScope.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `fonts` member of the `WorkerGlobalScope` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.3.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/WorkerGlobalScope/fonts
> Update Safari data for api.WorkerGlobalScope.fonts

- api/WritableStreamDefaultWriter.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `WritableStreamDefaultWriter` member of the `WritableStreamDefaultWriter` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.3.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/WritableStreamDefaultWriter/WritableStreamDefaultWriter
> Update Safari data for api.WritableStreamDefaultWriter.WritableStreamDefaultWriter

- api/WEBGL_multi_draw.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `WEBGL_multi_draw` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.3.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/WEBGL_multi_draw
> Update Safari data for WEBGL_multi_draw API

- api/StyleMedia.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `StyleMedia` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.3.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/StyleMedia
> Update Safari data for StyleMedia API

- api/HTMLCanvasElement.json
This PR updates and corrects version values for Firefox and Firefox Android for the `getContext.bitmaprenderer_context.options_alpha_parameter` member of the `HTMLCanvasElement` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.2.2).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/HTMLCanvasElement/getContext/bitmaprenderer_context/options_alpha_parameter
> Update Firefox data for api.HTMLCanvasElement.getContext.bitmaprenderer_context.options_alpha_parameter

- browsers/edge.json
Edge 113 was released at the beginning of this month, but the edge.json file hasn't been updated yet.
This PR adds Edge 113 to the file, and fixes a few URLs as usual.
> Update edge browser data file to version 113

- css/types/calc-constant.json
BCD for `infinity` and `NaN` inside the CSS `calc()` function.
Additionally, added chrome and safari support for `calc-constant` and sub-features
__Bugzilla:__
- Tracking bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1830759
__Resources:__
- WPT computed tests: http://wpt.live/css/css-values/calc-infinity-nan-computed.html
- WPT serialized tests: http://wpt.live/css/css-values/calc-infinity-nan-serialize-length.html
- Chrome support https://chromestatus.com/feature/5657825571241984
- Webkit 
- `calc-constant` (`e`, `pi` in conjunction with `<angle>` types) landed in [engine 613.1.3](https://github.com/WebKit/WebKit/blob/0897986c7f6083ff87823fb0822d170273fb8ea6/Source/WebCore/Configurations/Version.xcconfig) which is stable channel [version …
> docs(relnote): Fx114 - 'infinity' and 'NaN' supported in CSS calc()

- webextensions/api/commands.json
Add details for Firefox support of commands.onChanged in 115.
Addresses the dev-docs-needed requirement of [Bug 1801531](https://bugzilla.mozilla.org/show_bug.cgi?id=1801531) Implement browser.commands.onChanged
Related content changes in https://github.com/mdn/content/pull/26942
> Addition of commands.onChanged

- css/selectors/lang.json
Fx 114 supports (CSS Selectors Level 4) comma-separated values as params for the `:lang()` CSS pseudo. Additionally included is compliant string-based matching for language codes / subtags so that explicit wildcards `*-Latn` may be used, e.g.:
```css
:lang("nl", "de") {
color: green;
}
:lang("*-Latn") {
color: red;
}
```
__TODO:__
__Bugzilla:__
- Tracking bug: [BUG-1121792](https://bugzilla.mozilla.org/show_bug.cgi?id=1121792)
__Resources:__
- Spec https://drafts.csswg.org/selectors/#the-lang-pseudo
- codepen: https://codepen.io/bsmth/pen/xxyMwxa
- wpt-like tests: https://hg.mozilla.org/mozilla-central/rev/bc74ba399e3a
> docs(relnote): Fx114 - CSS :lang() pseudo accepts comma-separated language codes

- browsers/safari.json
- browsers/safari_ios.json
https://webkit.org/blog/14154/webkit-features-in-safari-16-5/
I don't know how to set the correct engine_version. Anyone has pointers?
> Safari 16.5 is released

- api/CSSStyleRule.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `CSSStyleRule` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.3.1).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/CSSStyleRule
> Update Safari data for CSSStyleRule API

- css/properties/animation-timeline.json
_👋 Hi, Chrome DevRel here!_
The `animation-timeline` property is enabled by default in Chrome 115, as part of Scroll-Driven Animations that are shipping with it.
- ChromeStatus: https://chromestatus.com/feature/6752840701706240
- CL that enabled the feature by default: https://chromium-review.googlesource.com/c/chromium/src/+/4522412
- Commit that enabled the feature by default: https://chromiumdash.appspot.com/commit/7f3389e42baa78fa4ffd4d6d03b442c0c2ed2279
In the CL link  you can find back that `animation-timeline` is added. In the commit link you can see that it is included in the 115.0.5768.0 build.
There’s more properties that this feature adds. I’ll file a separate PR to add those.
> animation-timeline is enabled by default in Chrome 115

- css/properties/scrollbar-color.json
Removed a note about macOS and Firefox.
This note is outdated overlay scrollbars are correctly themed in Firefox. I'm not aware of the exact version but I believe it was long enough ago to not worry about keeping the note for the appropriate version range.
Always:
Overflow (when scrolling):
fixes #19495
> Removed outdated Firefox note from scrollbar-color

- css/properties/animation-timeline.json
- css/properties/scroll-timeline-axis.json
- css/properties/scroll-timeline-name.json
- css/properties/scroll-timeline.json
Fixes https://github.com/mdn/content/issues/26994
In https://bugzilla.mozilla.org/show_bug.cgi?id=1807685 the pref `layout.css.scroll-linked-animations.enabled` was changed to `layout.css.scroll-driven-animations.enabled`.
This adds a new item for the new pref (if there isn't already a record) and makes the record with the the old pref as version removed. In some cases the old pref had different notes than the new pref, so I duplicated the note from the old pref to the new pref to make it clear the information still applies. 
Hopefully this will ship soon and we can remove all this detail.
> Name change for pref for scroll linked animations

- http/headers/Digest.json
- http/headers/Want-Digest.json
The last version of the spec in which they appear is https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-digest-headers-07
They have been replaced by Repr-Digest and Repr-Want-Digest.
No idea what versions they are supported in. 
Ths falls out of https://github.com/mdn/content/pull/26885
> HTTP Want-Digest and Digest are deprecated

- api/WebTransport.json
- api/WebTransportDatagramDuplexStream.json
WebTransport team finally got back to me with more detail on what FF supports and does not. The answers are kind of hand-wavy and this is not easy to test, so I may well not have it all. However I have tried to update the things I am clear on.
Specifically 
- FF does not support `WebTransport.sendOrder`, which means no one does, so I have removed that - this is planned in https://bugzilla.mozilla.org/show_bug.cgi?id=1816925
- FF implements `WebTransport.getStats` but can see in code it just throws: https://searchfox.org/mozilla-central/source/dom/webtransport/api/WebTransport.cpp#473-475
- FF does not support BYOB readers for datagrams, based on test here: https://wpt.fyi/results/webtransport/datagrams.https.any.html?label=experimental&label=master&aligned
Chrome does support it, but is …
> WebTransport FF114 - clarify support

- api/SVGFEImageElement.json
- api/SVGImageElement.json
- svg/elements/feImage.json
- svg/elements/image.json
Fx 114 supports `crossorigin` attribute on `<image>` and `<feimage>` elements which allow for specifying client behavior for cross-origin resource requests.
```html
<svg width="200" height="200" xmlns="http://www.w3.org/2000/svg">
<image
href="https://example.com/mdn_logo_dark.png"
height="200"
width="200"
crossorigin="use-credentials" />
</svg>
```
__Bugzilla:__
- [BUG-1240357](https://bugzilla.mozilla.org/show_bug.cgi?id=1240357)
__Resources:__
* WPT: https://wpt.live/svg/embedded/image-crossorigin.sub.html
* WPT overview: https://wpt.fyi/results/svg/embedded/image-crossorigin.sub.html?label=master&product=chrome%5Bstable%5D&product=edge%5Bstable%5D&product=firefox%5Bexperimental%5D&product=safari%5Bstable%5D&aligned
* specs
* …
> docs(relnote): Fx114 - crossorigin attribute for image and feImage elements

- api/WebGL2RenderingContext.json
- api/WebGLRenderingContext.json
As far as I can tell this is only a method of the OffscreenCanvasContext.
Spec https://html.spec.whatwg.org/multipage/canvas.html#offscreencontext-commit 
The collector also suggests false for Firefox
> WebGL contexts have no commit method

- javascript/builtins/ArrayBuffer.json
- javascript/builtins/SharedArrayBuffer.json
Fix https://github.com/mdn/browser-compat-data/issues/19974
Fix https://github.com/mdn/browser-compat-data/issues/19973
Release notes: https://nodejs.org/en/blog/announcements/v20-release-announce#v8-113
Edit: 20k BCD pull requests/issues !!!
> Node.js 20 supports resizable array buffers

- api/WEBGL_compressed_texture_s3tc_srgb.json
See https://github.com/WebKit/WebKit/commit/e9f97ba9db299ab74cedfc39eb86fa32811b9e61
> Safari 14.1 implements WEBGL_compressed_texture_s3tc_srgb

- scripts/release/mirror.test.ts
This PR adds a unittest to ensure that mirroring of notes doesn't change ChromeOS into EdgeOS/etc.
> Add unittest to ensure ChromeOS doesn't become EdgeOS/OperaOS

- api/WEBGL_compressed_texture_etc.json
- api/WEBGL_compressed_texture_etc1.json
This PR updates and corrects version values for Firefox and Firefox Android for the `WEBGL_compressed_texture_etc` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.3.1).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/WEBGL_compressed_texture_etc
Additional Notes: Testing this WebGL extension in macOS, Windows and Android, it turns out that the only platform that supports it is Android.
> Update Firefox data for WEBGL_compressed_texture_etc API

- api/CSSGroupingRule.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `CSSGroupingRule` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.3.1).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/CSSGroupingRule
Additional Notes: Additional manual testing was performed to narrow down the version number from ≤13.1 to 3.
> Update Safari data for CSSGroupingRule API

- api/RTCStatsReport.json
This PR updates and corrects version values for Firefox and Firefox Android for the `RTCStatsReport` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.3.1).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/RTCStatsReport
> Update Firefox data for RTCStatsReport API

- javascript/builtins/WebAssembly/Tag.json
This PR updates and corrects version values for all browsers for the `Tag.type` member of the `WebAssembly` JavaScript builtin. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.3.2).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/javascript/builtins/WebAssembly/Tag/type
> Update all browsers data for javascript.builtins.WebAssembly.Tag.type

- api/RTCStatsReport.json
RTCStatsReport is "maplike" - see https://w3c.github.io/webrtc-pc/#dom-rtcstatsreport - which means it adds entries, keys, iterator .... 
What this does is add a spec link for each of those maplike interfaces to https://w3c.github.io/webrtc-pc/#dom-rtcstatsreport and also a link to the MDN docs that are being added in https://github.com/mdn/content/pull/27028
> RTCStatsReport - add MDN links and speclinks for maplike

- css/properties/aspect-ratio.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `aspect-ratio` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.0.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/aspect-ratio
> Update Safari data for aspect-ratio CSS property

- api/WebGLQuery.json
- api/WebGLSampler.json
- api/WebGLSync.json
- api/WebGLVertexArrayObjectOES.json
Safari 15 shipped WebGL 2 and these interfaces belong to WebGL 2.
> Safari 15 supports WebGL2 interfaces

- css/properties/aspect-ratio.json
Reverts mdn/browser-compat-data#19570
> Revert "Update Safari data for aspect-ratio CSS property"

- css/properties/clip-path.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `fill_and_stroke_box` member of the `clip-path` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.4.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/clip-path/fill_and_stroke_box
> Update Safari data for css.properties.clip-path.fill_and_stroke_box

- css/properties/opacity.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `percentages` member of the `opacity` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.4.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/opacity/percentages
> Update Safari data for css.properties.opacity.percentages

- css/properties/overflow.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `multiple_keywords` member of the `overflow` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.4.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/overflow/multiple_keywords
> Update Safari data for css.properties.overflow.multiple_keywords
