webextensions/browser-compat-data.json
* a first pass at Android compat
* r? @matthewjwein
* also updated some chrome.downloads apis
=> update with android data

webextensions/browser-compat-data.json
Add compatibility information for tabs.removeCSS(), per bug 1247455.
=> Add tabs removeCSS

css/properties/background-attachment.json, css/properties/background-clip.json, css/properties/background-image.json, css/properties/background-origin.json, css/properties/background-position-x.json, css/properties/background-position-y.json, css/properties/background-position.json, css/properties/background-repeat.json, css/properties/background-size.json, css/properties/background.json
Needed as a contributor updated it on MDN before we changed the macro.
=> Update background(-*)? compat info with Edge (Mobile)

css/properties/background-origin.json
@Elchi3 There was a big error in the background-origin we landed the other day. This fix it.
=> Fix property name for background-origin

.travis.yml
Just noticed travis is not going through css/**/*.json files :-(
=> Update travis to also validate json in css/ directory

http/headers/referrer-policy.json
Status https://www.chromestatus.com/feature/5680800376815616
=> Supported on Chrome 56 and Opera 43

webextensions/browser-compat-data.json
https://bugzilla.mozilla.org/show_bug.cgi?id=1238314
=> Mark openerTabId as not supported

api/WebGL2RenderingContext.json, api/WebGLQuery.json, api/WebGLRenderingContext.json, api/WebGLSampler.json, api/WebGLSync.json, api/WebGLTransformFeedback.json, api/WebGLVertexArrayObject.json
https://www.chromestatus.com/features/6694359164518400
=> WebGL2 is supported in Chrome 56 and Opera 43

.travis.yml, css/properties/background-attachment.json, css/properties/background-clip.json, css/properties/background-color.json, css/properties/background-image.json, css/properties/background-origin.json, css/properties/background-position-x.json, css/properties/background-position-y.json, css/properties/background-position.json, css/properties/background-repeat.json, css/properties/background-size.json, css/properties/background.json, css/properties/text-align-last.json, css/pseudo-classes/any-link.json
This will need a rebase when the schema is actually committed.
The travis-ci may need to be updated at that moment, too.
=> Update CSS entries to new schema

.travis.yml, css/properties/background-attachment.json, css/properties/background-clip.json, css/properties/background-color.json, css/properties/background-image.json
Two things:
- Always test the test scripts
- additionalProperties: false is amazing
:)
=> Fix invalid css data

webextensions/javascript-apis.json
Updating compat tables with latest Edge extension support.
=> Updating Edge support for extensions

README.md
=> Fix link name for CSS

webextensions/javascript-apis.json
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/proxy
https://bugzilla.mozilla.org/show_bug.cgi?id=1295807
=> Add data for the proxy API

.npmignore, .travis.yml, test/sample-data.json
I used this test data for developing the `{{compat("my.feature.here")}}` macro and I think it is useful to look at and maybe to use for further testing purposes. We can add more special cases as we identify them
=> Add sample data

webextensions/manifest-keys.json
See:
https://bugzilla.mozilla.org/show_bug.cgi?id=1275287
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/options_ui#Syntax
=> Add subfeature for options_ui.browser_style

webextensions/manifest-keys.json
See:
https://github.com/mozilla/addons-linter/issues/1170
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/incognito
=> Add data for the 'incognito' key

webextensions/javascript-apis.json
-> https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/proxy?document_saved=true#Communicating_with_PAC_files
=> Add subfeature for options.toProxyScript

webextensions/manifest-keys.json
See https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Interact_with_the_clipboard
=> Add data for clipboardRead and clipboardWrite permissions

webextensions/manifest-keys.json
See:
http://searchfox.org/mozilla-central/source/mobile/android/components/extensions/schemas/browser_action.json
=> Add data for browser_action support on Firefox for Android

webextensions/javascript-apis.json
https://bugzilla.mozilla.org/show_bug.cgi?id=1364975
=> Add privacy.network.peerconnectionEnabled

webextensions/javascript-apis.json
https://bugzilla.mozilla.org/show_bug.cgi?id=1349896
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/devtools.panels/themeName
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/devtools.panels/onThemeChanged
=> Add themeName and onThemeChanged to devtools.panels

webextensions/manifest-keys.json
https://developer.chrome.com/extensions/permissions
https://bugzilla.mozilla.org/show_bug.cgi?id=1369581#c7
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/optional_permissions
=> Add data for optional_permissions

webextensions/javascript-apis.json
See:
https://developer.chrome.com/extensions/permissions
https://bugzilla.mozilla.org/show_bug.cgi?id=1369581#c7
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/permissions
https://bugzilla.mozilla.org/show_bug.cgi?id=1369776
=> Add data for the permissions API

webextensions/javascript-apis.json
See: https://bugzilla.mozilla.org/show_bug.cgi?id=1197420#c70
=> Remove note about silent permission-granting

webextensions/javascript-apis.json
See https://bugzilla.mozilla.org/show_bug.cgi?id=1336908.
=> Add data for management.getAll and management.setEnabled

webextensions/javascript-apis.json
Sorry, I somehow missed this one: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/permissions/Permissions
=> Add data for permissions.Permissions

webextensions/javascript-apis.json
-> https://bugzilla.mozilla.org/show_bug.cgi?id=1349896#c60
=> devtools.panels.themeName is supported in Chrome

api/IntersectionObserver.json, api/IntersectionObserverEntry.json
Adds the interfaces for Intersection Observer API.
=> Bug 1321865: Add Intersection Observer API

webextensions/manifest-keys.json
I tried to add this property but got an error in chrome.
=> Remove developer for chrome

webextensions/javascript-apis.json
See https://docs.microsoft.com/en-us/microsoft-edge/extensions/api-support/supported-apis#runtime.
=> Added notes about bugs in the messaging API on Microsoft Edge

api/IntersectionObserver.json, api/IntersectionObserverEntry.json
- https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/13407852-intersectionobserver
- https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API
=> Specify Edge version that supports IntersectionObserver

webextensions/javascript-apis.json
For evidence, screenshots taken on build 15063 (Creators Update):
=> The Tab's and Window's "incognito" property is called "inPrivate" on Microsoft Edge

javascript/builtins/String.json
See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String and 51 sub pages.
=> Add JS String data

webextensions/manifest-keys.json
See:
https://bugzilla.mozilla.org/show_bug.cgi?id=1330369
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/sidebar_action
=> Add compat data for sidebar_action.browser_style

javascript/builtins/String.json
Just tested it using the sample code in MDN. :) https://codepen.io/anon/pen/zzWLZK
=> Edge does support iterator.

webextensions/javascript-apis.json
This is to reflect Luca's feedback in https://bugzilla.mozilla.org/show_bug.cgi?id=1190687#c56.
=> Add compat notes for webNavigation.onCreatedNavigationTarget

webextensions/javascript-apis.json
See Rob's comment here: https://bugzilla.mozilla.org/show_bug.cgi?id=1318948#c11.
=> Add compat notes for cookies API functions

webextensions/manifest-keys.json
=> Naming convention changes add-ons -> extensions

webextensions/javascript-apis.json, webextensions/manifest-keys.json
Sorry Will, realized on checking the pages that I'd missed theme.Theme
=> Addition of theme.Theme to compatibility data

webextensions/javascript-apis.json
re: #3204Bug 1348911 — add lastAccessed to tabs.Tab
=> Updated for details of tabs.Tab lastAccessed support

webextensions/javascript-apis.json
See https://bugzilla.mozilla.org/show_bug.cgi?id=1386805
=> Note that saveAsPDF doesn't work on OS X

.travis.yml, package.json
`npm run travis` is useful? I doubt it.
=> simplify travis configuration

api/Gamepad.json, api/VRDisplay.json, api/VRDisplayCapabilities.json, api/VRDisplayEvent.json, api/VREyeParameters.json, api/VRFieldOfView.json, api/VRFrameData.json, api/VRLayerInit.json, api/VRPose.json, api/VRStageParameters.json, compat-data-schema.md, css/properties/background-clip.json, html/elements/link.json, http/headers/cache-control.json, http/headers/content-security-policy.json, http/headers/public-key-pins-report-only.json, http/headers/public-key-pins.json, http/headers/referrer-policy.json, http/headers/retry-after.json, http/headers/set-cookie.json, http/headers/upgrade-insecure-requests.json, javascript/builtins/Date.json, test/lint.js, webextensions/javascript-apis.json
This pull request is based on #313, if needs, I can change it.
I think these changes improve the JSONs readability.
=> Refine format

html/elements/del.json, html/elements/ins.json
Add &lt;del&gt; and &lt;ins&gt; compat data
=> Add browser compat for HTML Demarcating edits elements

html/elements/canvas.json, html/elements/noscript.json, html/elements/script.json
Add &lt;noscript&gt;, &lt;script&gt; & &lt;canvas&gt; browser compat.
=> Add browser compat for HTML scripting elements

webextensions/javascript-apis.json
See https://bugzilla.mozilla.org/show_bug.cgi?id=1300811.
=> From Fennec 56, pageAction.show and hide work properly

javascript/builtins/Array.json
=> Add JavaScript Array compat data

CONTRIBUTING.md, README.md, compat-data-schema.md
Better diff (without whitespace) https://github.com/mdn/browser-compat-data/compare/doc-updates?expand=1&w=1
=> Update docs for PR #304

webextensions/javascript-apis.json
See:
https://bugzilla.mozilla.org/show_bug.cgi?id=1373850
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/theme/reset
=> Add data for theme.reset()

webextensions/javascript-apis.json
See https://bugzilla.mozilla.org/show_bug.cgi?id=1397396.
=> Update compat notes for tabs.captureVisibleTab

webextensions/javascript-apis.json
As per [Bug 1252871 comment 45](https://bugzilla.mozilla.org/show_bug.cgi?id=1252871#c45) and the final patch.
> > Can we just call this "browser_update"
>Sgtm.
=> Note for runtime.OnInstalledReason browser_update

webextensions/javascript-apis.json
https://bugzilla.mozilla.org/show_bug.cgi?id=1377733
=> Tab.discarded state added by bugzilla #1377733

webextensions/javascript-apis.json
A new PR to replace https://github.com/mdn/browser-compat-data/pull/367.
=> Rename contextmenus 2

html/elements/iframe.json
This element is a bit more complex, it deserves its separate PR.
=> Add <iframe> browser compat data

html/elements/embed.json, html/elements/object.json, html/elements/param.json, html/elements/source.json
Browser compat: &lt;object&gt;, &lt;param&gt;, &lt;source&gt;, &lt;embed&gt;.
=> Add HTML embedded content elements browser compat

html/elements/a.json
This is an important element, it deserves its own PR :-)
=> Add browser compat for <a> element

css/properties/border-bottom-left-radius.json, css/properties/border-bottom-right-radius.json, css/properties/border-radius.json, css/properties/border-top-left-radius.json, css/properties/border-top-right-radius.json
Let me know if you want to see any changes! Thanks!
=> Add remaining `border-radius` CSS compat data

webextensions/javascript-apis.json
Screenshot taken on Microsoft Edge as of Windows Creator Update:
=> MAX_HANDLER_BEHAVIOR_CHANGED_CALLS_PER_10_MINUTES is supported by Microsoft Edge

html/elements/base.json
Fix issue #403. Reported to Bugzilla as [bug 1401216](https://bugzilla.mozilla.org/show_bug.cgi?id=1401216).
Created using GitHub web interface!
=> Fix #403 - Remove extra ">" in note

webextensions/javascript-apis.json
For reference: https://discourse.mozilla.org/t/moz-extension-not-allowed-in-tabs-query/12793
=> Added note about moz-extension://  URLs in tabs.query()

compat-data.schema.json, html/elements/rp.json, html/elements/s.json, javascript/builtins/RegExp.json
Fixes https://github.com/mdn/browser-compat-data/issues/399
=> Validate mdn_urls

javascript/builtins/Symbol.json
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol and subpages
=> Add JS Symbol compat data

webextensions/javascript-apis.json
See: https://bugzilla.mozilla.org/show_bug.cgi?id=1344519
I haven't written the docs yet.
=> Add data for contextualIdentities events

webextensions/javascript-apis.json
See:
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/browserSettings/allowPopupsForUserEvents
https://bugzilla.mozilla.org/show_bug.cgi?id=1339550
=> Add data for allowPopupsForUserEvents

javascript/builtins/Map.json, javascript/builtins/Set.json, javascript/builtins/WeakMap.json, javascript/builtins/WeakSet.json
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet
=> Add JS Map/Set/WeakMap/WeakSet compat data

javascript/functions.json
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions and sub pages
=> Add JS Functions compat data

javascript/builtins/DataView.json, javascript/builtins/TypedArray.json
Two things got wrong
- getUInt* -> getUint*
- Some mdn_urls should be set* instead get* (copy-pasting mistake)
- subArray -> subarray
=> Fix DataView and TypedArray data

javascript/statements.json
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements and subpages.
=> Add JS statements compat data

webextensions/javascript-apis.json
See:
https://bugzilla.mozilla.org/show_bug.cgi?id=1345158
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/privacy/websites
=> Add data for privacy.websites.trackingProtectionMode

webextensions/javascript-apis.json
See: https://bugzilla.mozilla.org/show_bug.cgi?id=1332144, and the very helpful draft devdocs: https://bug1332144.bmoattachments.org/attachment.cgi?id=8905651.
I haven't written docs pages for this API yet.
=> Add data for find API

webextensions/javascript-apis.json
https://bugzilla.mozilla.org/show_bug.cgi?id=1341305 and https://bugzilla.mozilla.org/show_bug.cgi?id=1398729 add the following new APIs:
```
devtools.panels.ElementsPanel.createSidebarPane
devtools.panels.ExtensionSidebarPane
.setExpression
.setObject
.onShown
.onHidden
```
=> Add data for new devtools APIs in Firefox 57

api/WebGL2RenderingContext.json, api/WebGLQuery.json, api/WebGLRenderingContext.json, api/WebGLSampler.json, api/WebGLSync.json, api/WebGLTransformFeedback.json, api/WebGLVertexArrayObject.json
Issue #148 lists value needed for WebGL2. This is the PR for these.
=> Add mobile compatibility for WebGL2

api/AbortController.json, api/AbortSignal.json
* AbortSignal
* AbortController
=> adding abort api to bcd

html/elements/abbr.json, html/elements/address.json, html/elements/blink.json, html/elements/map.json, html/elements/script.json, html/elements/title.json, html/elements/wbr.json, http/data-url.json, http/headers/x-content-type-options.json, http/headers/x-frame-options.json, javascript/builtins/Object.json, javascript/operators/object_initializer.json
=> Fix invalid Opera versions

api/AudioNode.json, api/AudioParam.json, api/AudioProcessingEvent.json
* AudioNode
* AudioParam
* AudioProcessingEvent
=> Next batch of Web Audio API BCD

css/properties/flex-basis.json, css/properties/flex.json
We need to land the browser version testing, then this would have been caught :speak_no_evil:
=> Fix Opera version 12.10 -> 12.1

api/PointerEvent.json
This PR should fix the issue #490.
=> PointerEvents: Remove parentheses and add mdn_urls #490

api/AudioBufferSourceNode.json, api/AudioContext.json
Changes made as a result of the comments left in the tracking spreadsheet
=> Misc web audio api

api/BiquadFilterNode.json
Changes made as a result of the comments left in the tracking spreadsheet
=> Adding BiquadfilterNode

api/ChannelMergerNode.json
Changes made as a result of the comments left in the tracking spreadsheet
=> Adding ChannelMergerNode

css/properties/column-rule-width.json, css/properties/column-width.json, css/properties/font-family.json
We should really land #439 :grinning:
=> Fix invalid versions

webextensions/api/webRequest.json
As per: https://bugzilla.mozilla.org/show_bug.cgi?id=1388289#c16.
=> Fix note for onAuthRequired

api/WebGL2RenderingContext.json, api/WebGLRenderingContext.json
https://codereview.chromium.org/2815793002
=> Add SharedArrayBuffer support to certain WebGL interfaces.

webextensions/api/webRequest.json
https://bugzilla.mozilla.org/show_bug.cgi?id=1255894 added the ability to monitor and modify HTTP responses using a thing called a [`StreamFilter`](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/webRequest/StreamFilter).
=> Add data for webRequest.StreamFilter

css/at-rules/font-face.json
See rendering here 
https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face#Browser_compatibility
=> Fix font-face at-rule URL and descriptors

html/elements/body.json, html/elements/image.json
We missed these two elements. Here they are.
=> Add compat data for image and body elements.

webextensions/api/devtools.json
See: https://bugzilla.mozilla.org/show_bug.cgi?id=1341305#c30.
=> Added compat notes for ExtensionSidebarPane

webextensions/api/browsingData.json
See: https://bugzilla.mozilla.org/show_bug.cgi?id=1401681#c7.
=> Note that removing history also remove service workers

webextensions/api/tabs.json
Fixed version of https://github.com/mdn/browser-compat-data/pull/568.
=> Add reader mode for Firefox 58

http/headers/content-security-policy.json
https://bugzilla.mozilla.org/show_bug.cgi?id=1302667
=> CSP: worker-src implemented in Firefox 58

javascript/builtins/Object.json
https://bugzilla.mozilla.org/show_bug.cgi?id=638054
=> Firefox removed Object.watch/unwatch in version 58

javascript/builtins/Intl.json
* Supported in Firefox, see bug 1386146
=> Add hourCycle to Intl.DateTimeFormat

compat-data-schema.md
This will complete all examples for compat data schema.
=> Editorial: Add example for Status information

compat-data-schema.md
References:
- https://github.com/mdn/browser-compat-data/pull/623#discussion_r150401700
=> Editorial: Update browser identifier declaration instructions

javascript/builtins/WebAssembly.json
Luke Wagner informs me that Edge does not have these features yet.
=> Fix Edge support for WebAssembly new streaming features

css/properties/backface-visibility.json, css/properties/perspective-origin.json, css/properties/perspective.json
This PR adds the following CSS properties:
* [`backface-visibility`](https://developer.mozilla.org/en-US/docs/Web/CSS/backface-visibility)
* [`perspective`](https://developer.mozilla.org/en-US/docs/Web/CSS/perspective)
* [`perspective-origin`](https://developer.mozilla.org/en-US/docs/Web/CSS/perspective-origin)
=> Add compat data for some CSS transform properties

browsers/browsers.json
Fixes https://github.com/mdn/browser-compat-data/issues/638
=> Add current and future Firefox releases

.gitignore, webextensions/manifest/chrome_url_overrides.json
Browser compatibility update for chrome_url_overrides in Opera
=> chrome_url_overrides update for Opera

api/WebGL2RenderingContext.json
Sorry for just entering null. I don't have any sources of information on these.
=> Add missing compat entries to SharedArrayBuffer_as_param.

css/properties/text-decoration-skip-ink.json, css/properties/text-decoration-skip.json
Adding data for these two, which seemed to be missing
=> adding compat data for text-decoration-skip/text-decoration-skip-ink

package.json
As discussed in https://github.com/mdn/browser-compat-data/pull/521
=> Add 'show-errors' shortcut

webextensions/api/menus.json
https://bugzilla.mozilla.org/show_bug.cgi?id=1339416 added support for `menus.OnClickData.frameId` in Firefox 55 (desktop only).
I don't know if it's supported on Edge.
=> menus.OnClickData.frameId

compat-data-schema.md, compat-data.schema.json, css/properties/animation.json, css/properties/grid-area.json, css/properties/grid-auto-columns.json, css/properties/grid-auto-flow.json, css/properties/grid-auto-rows.json, css/properties/grid-gap.json, css/properties/grid-template-areas.json, css/properties/grid-template-columns.json, css/properties/grid-template-rows.json, css/properties/grid-template.json, css/properties/grid.json, html/elements/audio.json
Fixes https://github.com/mdn/browser-compat-data/issues/654
=> Require at least two items when using array statements

javascript/builtins/Promise.json
https://bugzilla.mozilla.org/show_bug.cgi?id=1019116
https://www.chromestatus.com/features/5704570235781120
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/finally
=> Add Promise.prototype.finally

javascript/builtins/Intl.json
https://bugzilla.mozilla.org/show_bug.cgi?id=1403318
https://www.chromestatus.com/features/5653874773852160
=> Add Intl.PluralRules

javascript/statements.json
Replaces https://github.com/mdn/browser-compat-data/pull/585
=> Update import/export data for Edge 16

webextensions/manifest/applications.json, webextensions/manifest/author.json, webextensions/manifest/background.json, webextensions/manifest/browser_action.json, webextensions/manifest/chrome_settings_overrides.json, webextensions/manifest/chrome_url_overrides.json, webextensions/manifest/commands.json, webextensions/manifest/content_scripts.json, webextensions/manifest/content_security_policy.json, webextensions/manifest/default_locale.json, webextensions/manifest/description.json, webextensions/manifest/developer.json, webextensions/manifest/devtools_page.json, webextensions/manifest/homepage_url.json, webextensions/manifest/icons.json, webextensions/manifest/incognito.json, webextensions/manifest/manifest_version.json, webextensions/manifest/name.json, webextensions/manifest/omnibox.json, webextensions/manifest/optional_permissions.json, webextensions/manifest/options_ui.json, webextensions/manifest/page_action.json, webextensions/manifest/permissions.json, webextensions/manifest/protocol_handlers.json, webextensions/manifest/short_name.json, webextensions/manifest/sidebar_action.json, webextensions/manifest/theme.json, webextensions/manifest/version.json, webextensions/manifest/web_accessible_resources.json
=> Added mdn_url to WebExtension manifest keys

javascript/builtins/Intl.json
Replaces https://github.com/mdn/browser-compat-data/pull/612
=> Update status for {DateTime,Number}Format.formatToParts

http/headers/content-security-policy.json
Reported in https://bugzilla.mozilla.org/show_bug.cgi?id=1422909
DDN wasn't set in https://bugzilla.mozilla.org/show_bug.cgi?id=1279420
=> require-sri is behind a flag per bug 1422909

css/properties/cursor.json
This PR migrates the data for the [`cursor`](https://developer.mozilla.org/docs/Web/CSS/cursor). It has many features because of the many keyword values. Where possible I've tried to group the values (e.g., grab and zoom cursors), but there's still a lot to review here. Let me know if you want to see any changes. Thanks!
=> Add cursor CSS property

css/at-rules/media.json
This PR migrates the data for the [`@media`](https://developer.mozilla.org/en-US/docs/Web/CSS/%40media#Browser_compatibility) CSS at rule. Let me know if you want to see any changes. Thanks!
=> Add @media CSS at-rule

html/elements/data.json
https://www.chromestatus.com/features/5701891585474560
=> Correct compat for data element.

http/headers/expect-ct.json
https://www.chromestatus.com/features/5677171733430272
=> Add compat data for Expect-CT header.

http/headers/referrer-policy.json
https://www.chromestatus.com/features/5696724538490880
=> Correct referrer policy support data.

browsers/browsers.json
https://en.wikipedia.org/wiki/Microsoft_Edge#Release_history
=> Add Edge version 17

webextensions/manifest/options_ui.json
Tested on Firefox Android Nightly 59.
=> options_ui supported since Firefox Android 57

javascript/functions.json, javascript/operators/function.json, javascript/operators/function_star.json, javascript/statements.json
https://www.chromestatus.com/features/5656834660630528
https://github.com/mdn/browser-compat-data/pull/817
=> Add rest of trailing comma data.

api/CanvasCaptureMediaStream.json
First PR here. Hope I'm doing it right :)
=> Add compat data for CanvasCaptureMediaStream

css/at-rules/font-face.json
=> Add data for Samsung Internet to font-face.json

api/ReadableStream.json
https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream
=> Add ReadableStream compat data

http/data-url.json
Note added for Fx support as per https://bugzilla.mozilla.org/show_bug.cgi?id=1401895
=> Add note related to Data URLs

api/WritableStream.json
https://developer.mozilla.org/en-US/docs/Web/API/WritableStream
https://www.chromestatus.com/features/5928498656968704
https://developer.microsoft.com/en-us/microsoft-edge/platform/status/streamsapiwritablestream
=> Add WritableStream compat data

http/headers/x-frame-options.json
As per https://bugzilla.mozilla.org/show_bug.cgi?id=725490
=> added note to Fx support info about SAMEORIGIN now cheking all ancestors

api/EventTarget.json
I was documenting the new constructor anyway, so I thought "might as well" ;-)
=> Add EventTarget compat data

api/CSSNamespaceRule.json
Thought I might as well, as we just implemented its properties; see https://bugzilla.mozilla.org/show_bug.cgi?id=1326514
=> adding CSSNamespaceRule

webextensions/api/browserAction.json, webextensions/api/pageAction.json, webextensions/api/sidebarAction.json
Added in https://bugzilla.mozilla.org/show_bug.cgi?id=1427431
=> Add compat data for isEnabled, isShown and isOpen webext APIs

webextensions/api/pageAction.json, webextensions/api/sidebarAction.json
=> Firefox 59 allows pageAction and sidebarAction set* methods to accept null

css/properties/user-select.json
This PR migrates the data for [`user-select`](https://developer.mozilla.org/docs/Web/CSS/user-select). Let me know if you want to see any changes. Thanks!
=> Add compat data for user-select CSS property

css/properties/shape-image-threshold.json
=> Update shape-image-threshold for firefox (behind a flag)

api/CanvasRenderingContext2D.json
Phew! That was tough going. I hope I've nested the data correctly, when it comes to multiple rows in the compat data - eg https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/addHitRegion
=> Add compat data for CanvasRenderingContext2D

css/properties/-moz-border-bottom-colors.json, css/properties/-moz-border-left-colors.json, css/properties/-moz-border-right-colors copy.json, css/properties/-moz-border-top-colors.json
I've included a note as per https://bugzilla.mozilla.org/show_bug.cgi?id=1417200
=> Add the -moz-border-*-colors properties

html/elements/script.json
…script element type attribute
=> Add support removal of Firefox-only 'version' parameter in 'type' attribute of <script>

css/properties/overscroll-behavior-x.json, css/properties/overscroll-behavior-y.json, css/properties/overscroll-behavior.json
As per https://bugzilla.mozilla.org/show_bug.cgi?id=951793 and https://bugzilla.mozilla.org/show_bug.cgi?id=1428879
=> Add overscroll-behavior(-[xy])? properties

css/types/calc.json
=> Add strange note about media query support disabling between Fx57-59

api/SecurityPolicyViolationEvent.json
See https://bugzilla.mozilla.org/show_bug.cgi?id=1037335
=> Add compat data for SecurityPolicyViolationEvent

javascript/statements.json
Node supports the import statement behind a flag.
=> nodejs ES module support flag info

css/properties/display.json
As per https://bugzilla.mozilla.org/show_bug.cgi?id=1427292
=> Add special behavior of display:contents for unusual elements

api/AbstractWorker.json
[https://developer.mozilla.org/en-US/docs/Web/API/AbstractWorker](https://developer.mozilla.org/en-US/docs/Web/API/AbstractWorker)
=> Add compat data for AbstractWorker (Worker API)

api/FetchEvent.json
I'm not sure I represented [`respondWith`](https://developer.mozilla.org/en-US/docs/Web/API/FetchEvent/respondWith) correctly. Please feel free to suggest a better way - thanks! :)
=> Add compat data for FetchEvent (Fetch API)

css/properties/animation-name.json
=> `animation-name` is supported since Edge 12

javascript/builtins/String.json
=> Change ordering for String.prototype.includes

webextensions/api/browserSettings.json
Bug 1425535 added a new setting to the [`browserSettings`](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/browserSettings) API, `proxyConfig`:
https://bugzilla.mozilla.org/show_bug.cgi?id=1425535
I've not written the docs page yet...
=> Add browserSettings.proxyConfig

api/RTCConfiguration.json
New branch in an attempt to fix previous rebase issue. 
https://developer.mozilla.org/docs/Web/API/RTCConfiguration
=> Adding compat data for RTCConfiguration

browsers/opera.json
https://dev.opera.com/blog/opera-51/ also lists a few features we might have in our data. If anyone wants to double-check these, it would be awesome!
=> Add Opera 51 release

api/Request.json
[https://developer.mozilla.org/en-US/docs/Web/API/Request](https://developer.mozilla.org/en-US/docs/Web/API/Request)
Note the `Body` methods and properties linked to from `Request` are here: [https://github.com/mdn/browser-compat-data/pull/916](https://github.com/mdn/browser-compat-data/pull/916)
Not sure what to do about the following linting error:
```File : /Users/markb/Sites/browser-compat-data/api/Request.json
Style – Error on line #397
Actual:                 "version_added": "15"
Expected:               "version_added": true
```
=> Add compat data for Request (Fetch API)

javascript/builtins/Array.json, javascript/builtins/Map.json, javascript/builtins/Set.json, javascript/builtins/String.json, javascript/builtins/TypedArray.json
Fixes https://github.com/mdn/browser-compat-data/issues/950 and normalizes all @@iterator data.
=> Normalize Firefox @@iterator compat data

api/DedicatedWorkerGlobalScope.json
https://developer.mozilla.org/en-US/docs/Web/API/DedicatedWorkerGlobalScope
=> Add compat data for DedicatedWorkerGlobalScope (Worker API)

api/SharedWorker.json
[https://developer.mozilla.org/en-US/docs/Web/API/SharedWorker](https://developer.mozilla.org/en-US/docs/Web/API/SharedWorker)
Not sure whether `Constructor name option` here [https://developer.mozilla.org/en-US/docs/Web/API/SharedWorker](https://developer.mozilla.org/en-US/docs/Web/API/SharedWorker) 
is the same as `name option` defined here [https://developer.mozilla.org/en-US/docs/Web/API/SharedWorker/SharedWorker](https://developer.mozilla.org/en-US/docs/Web/API/SharedWorker/SharedWorker)
=> Add compat data for SharedWorker (Worker API)

api/RTCDTMFSender.json, api/RTCDTMFToneChangeEvent.json, api/RTCDataChannel.json, api/RTCDataChannelEvent.json, api/RTCIceCandidate.json
Adding compat data for https://developer.mozilla.org/docs/Web/API/RTCDTMFSender
=> Add compat data for RTCDTMFSender, RTCFTToneChangeEvent, and RTCDataChannel

api/RTCPeerConnectionIceEvent.json
https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnectionIceEvent
=> Add compat data RTCPeerConnectionIceEvent

api/RTCSctpTransport.json
https://developer.mozilla.org/en-US/docs/Web/API/RTCSctpTransport
=> Add compat data RTCSctpTransport

javascript/builtins/String.json
https://www.chromestatus.com/feature/5694172086403072
=> Add Chromium values for padStart/padEnd.

http/headers/referrer-policy.json
This is my first PR here, I may have made lots of process mistakes.
Please tell me so if that's the case
Link to standard justifying the change: https://www.w3.org/TR/referrer-policy/#referrer-policies
=> Update referrer policy compat data to note some values as standard

api/BlobEvent.json
Hey all,
Here's another one! Hopefully up to par 👍
=> Add compat data for BlobEvent

api/ChildNode.json
=> add compat data for ChildNode

api/CustomElementRegistry.json
=> Add support of 'Customized built-in elements' to the CustomElementRegistry in Chromia BCD (and minor other tweaks)

api/RTCSessionDescription.json
https://developer.mozilla.org/en-US/docs/Web/API/RTCSessionDescription
=> Add compat data for RTCSessionDescription

api/BudgetService.json, api/BudgetState.json
=> add compat data for BudgetService and BudgetState

api/Client.json
https://developer.mozilla.org/en-US/docs/Web/API/Client
as per #1002 notes on ESR status might need editing.
=> Add compat data for Client

api/BasicCardRequest.json
https://developer.mozilla.org/en-US/docs/Web/API/BasicCardRequest
=> Add compat data for BasicCardRequest

api/SyncEvent.json
https://developer.mozilla.org/en-US/docs/Web/API/SyncEvent
=> Add compat data for SyncEvent

api/BasicCardResponse.json
https://developer.mozilla.org/en-US/docs/Web/API/BasicCardResponse
=> Add compat data for BasicCardResponse

api/PaymentResponse.json
https://developer.mozilla.org/en-US/docs/Web/API/PaymentResponse
=> Add compat data for PaymentResponse

api/PaymentAddress.json
https://developer.mozilla.org/en-US/docs/Web/API/PaymentAddress
=> Add compat data for PaymentAddress

api/SyncManager.json
https://developer.mozilla.org/en-US/docs/Web/API/SyncManager
=> Add compat data for SyncManager

api/RTCStatsReport.json
https://developer.mozilla.org/en-US/docs/Web/API/RTCStatsReport
=> Add compat data RTCStatsReport

api/SyncManager.json
https://www.chromestatus.com/features/5703688089763840
=> Correct version number for SyncManager.

api/RTCSessionDescriptionCallback.json
https://developer.mozilla.org/en-US/docs/Web/API/RTCSessionDescriptionCallback
=> Add compat data for RTCSessionDescriptionCallback

api/Response.json
Wrong hierarchy here as well. Sorry for not catching it in the review.
=> Fix nesting of Response members

api/ServiceWorkerContainer.json
https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerContainer
as #1002 notes on ESR might need editing.
=> Add compat data for ServiceWorkerContainer

api/InstallEvent.json
https://developer.mozilla.org/en-US/docs/Web/API/InstallEvent
as per #1002 notes on ESR might need editing
=> Add compat data for InstallEvent

api/ExtendableEvent.json
https://developer.mozilla.org/en-US/docs/Web/API/ExtendableEvent
as per #1002 notes on ESR may need editing
=> Add compat data for ExtendableEvent

api/RTCRtpSender.json
https://developer.mozilla.org/en-US/docs/Web/API/RTCRtpSender
=> Add compat data for RTCRtpSender

api/BroadcastChannel.json
Fixes #971  
It's my first contribution to this compat data repo. Let me know if I missed anything. 
There were a few missing browsers on the documentation itself. Not sure what the process is in that case? 
Also edited the https://developer.mozilla.org/en-US/docs/MDN/Contribute/Structures/Compatibility_tables documentation for some dead link to the advanced schema MD file.
=> Add comp data for BroadcastChannel

api/ServiceWorkerRegistration.json
https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerRegistration
as in #1002 notes on ESR might need editing.
=> Add compat data for ServiceWorkerRegistration

api/File.json
Hey all,
Here's another one. There's a lot of proprietary, obsolete methods and properties for this object, which seem to lack compatibility tables to translate. Should I ignore these?
=> Add compat data for File

api/FileEntrySync.json
Hey all,
So sorry to inundate this poor repository, but I've been on a roll with these File APIs.
=> Add compat data for FileEntrySync

api/SVGAElement.json
https://developer.mozilla.org/en-US/docs/Web/API/SVGAElement
=> Add compat data for SVGAElement

api/FileEntrySync.json
I can't find a definitive answer on this. I'm more comfortable with `null` than with `false`.
=> Change FileEntrySync.

api/ExtendableEvent.json
Needs to below the the waitUntil method
=> Fix async waitUntil nesting

api/Animation.json
[Mozilla bug 1436659](https://bugzilla.mozilla.org/show_bug.cgi?id=1436659).
=> Add Animation.updatePlaybackRate

api/ServiceWorkerGlobalScope.json
https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerGlobalScope
as in #1002 notes for ESR might need editing.
=> Add compat data for ServiceWorkerGlobalScope

api/Clients.json
https://developer.mozilla.org/en-US/docs/Web/API/Clients
as per #1002 note on ESR may need editing
=> Add compat data for Clients

api/WindowClient.json
https://developer.mozilla.org/en-US/docs/Web/API/WindowClient
as in #1002 notes on ESR might need editing.
=> Add compat data for WindowClient

webextensions/api/tabs.json
More Firefox-only APIs:
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/hide
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/show
https://bugzilla.mozilla.org/show_bug.cgi?id=1423725
=> Added data for tabs.hide and tabs.show

api/NotificationEvent.json
https://developer.mozilla.org/en-US/docs/Web/API/NotificationEvent
as per #1002 notes on ESR might need editing
=> Add compat data for NotificationEvent

javascript/builtins/Object.json
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/entries
Check compatibility on [node.green](http://node.green/#ES2017-features-Object-static-methods-Object-entries)
=> Add nodejs compat for Object.entries()

api/PushRegistrationManager.json
https://developer.mozilla.org/en-US/docs/Web/API/PushRegistrationManager
=> Add compat data for PushRegistrationManager

css/properties/break-after.json, css/properties/break-before.json, css/properties/break-inside.json
According to https://caniuse.com/#feat=multicolumn
Some proofs that feature has implemented:
https://bugs.chromium.org/p/chromium/issues/detail?id=492297
https://bugs.webkit.org/attachment.cgi?id=270225&action=review
=> Correct support for css `break-` properties

javascript/builtins/Object.json
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/getOwnPropertyDescriptors
Check compatibility on [node.green](http://node.green/#ES2017-features-Object-static-methods-Object-getOwnPropertyDescriptors)
=> Add nodejs compat for Object.getOwnPropertyDescriptors()

javascript/statements.json
https://bugzilla.mozilla.org/show_bug.cgi?id=1380881
https://www.chromestatus.com/features/5810795665424384
=> Add optional catch binding

javascript/statements.json
See https://bugzilla.mozilla.org/show_bug.cgi?id=1228841
=> Conditional catch expressions have been removed from Fx59

webextensions/manifest/optional_permissions.json, webextensions/manifest/permissions.json
Changes to:
* add a complete list of available permissions to permissions.json
* correct Firefox for Android support details for bookmarks and history permissions in optional_permissions.json
=> Updates to manifest.json permissions and optional permissions compatibility data

api/DocumentTimeline.json
As per https://bugzilla.mozilla.org/show_bug.cgi?id=1267510
=> Updating the DocumentTimeline() constructor support data, now Fx supports it

api/HTMLDivElement.json
https://developer.mozilla.org/en-US/docs/Web/API/HTMLDivElement
=> Add compat data for HTMLDivElement

api/WorkerGlobalScope.json
https://developer.mozilla.org/docs/Web/API/WorkerGlobalScope
Note I did not yet add properties and methods that came under `WindowOrWorkerGlobalScope` (https://developer.mozilla.org/docs/Web/API/WindowOrWorkerGlobalScope). Although happy to do that :)
=> Add compat data for WorkerGlobalScope (Worker API)

api/AnimationPlaybackEvent.json
=> Adds compat data for AnimationPlaybackEvent

api/WorkerLocation.json
https://developer.mozilla.org/en-US/docs/Web/API/WorkerLocation
Assume the properties listed will come under `URLUtilsReadOnly`.
=> Add compat data for WorkerLocation (Worker API)

api/WorkerNavigator.json
https://developer.mozilla.org/en-US/docs/Web/API/WorkerNavigator
=> Add compat data for WorkerNavigator (Worker API)

api/HTMLBaseElement.json
https://developer.mozilla.org/en-US/docs/Web/API/HTMLBaseElement
=> Add compat data for HTMLBaseElement

api/PushEvent.json
https://developer.mozilla.org/en-US/docs/Web/API/PushEvent
=> Add compat data for PushEvent

api/PushMessageData.json
https://developer.mozilla.org/en-US/docs/Web/API/PushMessageData
=> Add compat data for PushMessageData

api/PushSubscription.json
https://developer.mozilla.org/en-US/docs/Web/API/PushSubscription
=> Add compat data for PushSubscription

api/Crypto.json
https://developer.mozilla.org/en-US/docs/Web/API/Crypto
=> Add compat data for Crypto

api/CryptoKey.json
https://developer.mozilla.org/en-US/docs/Web/API/CryptoKey
=> Add compat data for CryptoKey

api/RandomSource.json
https://developer.mozilla.org/en-US/docs/Web/API/RandomSource
=> Add compat data for RandomSource

css/properties/paint-order.json
As per https://bugzilla.mozilla.org/show_bug.cgi?id=1426146
=> Add experimental paint-order property BCD

api/PushRegistrationManager.json
=> Correct PushRegistrationManager

css/properties/align-content.json, css/properties/justify-content.json, css/properties/place-content.json
As per https://bugzilla.mozilla.org/show_bug.cgi?id=1430817.
I'm not sure if all this data has been represented in the best possible way — it is a little messy, but I've basically followed the form of the data that's already there.
=> Update BCD for justify-content, align-content, and place-content

api/SharedWorkerGlobalScope.json
https://developer.mozilla.org/en-US/docs/Web/API/SharedWorkerGlobalScope
=> Add compat data for SharedWorkerGlobalScope (Worker API)

api/Worker.json
https://developer.mozilla.org/en-US/docs/Web/API/Worker
=> Add compat data for Worker (Worker API)

css/properties/paint-order.json
As per https://bugzilla.mozilla.org/show_bug.cgi?id=1435684
=> removing pref information, as paint-order is on by default

api/PerformanceNavigationTiming.json
This adds the browser compatibility table data for the [`PerformanceNavigationTiming` API](https://developer.mozilla.org/docs/Web/API/PerformanceNavigationTiming).
=> Add PerformanceNavigationTiming

api/HTMLHRElement.json
[https://developer.mozilla.org/en-US/docs/Web/API/HTMLHRElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLHRElement)
=> adding compat data for HTMLHRElement

css/properties/rotate.json, css/properties/scale.json, css/properties/translate.json
As per https://bugzilla.mozilla.org/show_bug.cgi?id=1207734
=> Add BCD for CSS scale, rotate, and translate properties

api/IDBEnvironment.json
https://developer.mozilla.org/en-US/docs/Web/API/IDBEnvironment
=> Add compat data for IDBEnvironment

api/Console.json
Adding compat data for the Console API (https://developer.mozilla.org/docs/Web/API/Console)
=> Add compat data for Console

css/at-rules/font-face.json, css/properties/font-variation-settings.json
As per https://bugzilla.mozilla.org/show_bug.cgi?id=1435984
=> Add font-variation-settings descriptor and fix font-variation-settings property

api/WorkerGlobalScope.json
This is a limited PR, correcting only things that I have been specifically made aware of. If I haven't touched something in this API, assume it's because I can't find reliable information on it.
=> Tweaks to WorkerGlobalScope.json.

api/NodeIterator.json
https://developer.mozilla.org/en-US/docs/Web/API/NodeIterator
=> Add compat data for NodeIterator

api/IDBLocaleAwareKeyRange.json
https://developer.mozilla.org/en-US/docs/Web/API/IDBLocaleAwareKeyRange
=> Add compat data for IDBLocaleAwareKeyRange

api/MediaKeyMessageEvent.json
https://developer.mozilla.org/en-US/docs/Web/API/MediaKeyMessageEvent
=> Add compat data for MediaKeyMessageEvent

api/MediaKeySession.json
https://developer.mozilla.org/en-US/docs/Web/API/MediaKeySession
=> Add compat data for MediaKeySession

api/MediaKeySystemAccess.json
https://developer.mozilla.org/en-US/docs/Web/API/MediaKeySystemAccess
=> Add compat data for MediaKeySystemAccess

api/MediaKeySystemConfiguration.json
https://developer.mozilla.org/en-US/docs/Web/API/MediaKeySystemConfiguration
=> Add compat data for MediaKeySystemConfiguration

api/MediaKeys.json
https://developer.mozilla.org/en-US/docs/Web/API/MediaKeys
=> Add compat data for MediaKeys

html/elements/global_attributes.json, html/global_attributes.json
https://github.com/mdn/browser-compat-data/issues/914
=> adding compat data for HTML global attributes

api/HTMLBRElement.json
https://developer.mozilla.org/en-US/docs/Web/API/HTMLBRElement
=> Add compat data for HTMLBRElement

api/HTMLBaseFontElement.json
https://developer.mozilla.org/en-US/docs/Web/API/HTMLBaseFontElement
=> Add compat data for HTMLBaseFontElement

api/HTMLBodyElement.json
https://developer.mozilla.org/en-US/docs/Web/API/HTMLBodyElement
=> Add compat data for HTMLBodyElement

README.md
Announced at https://discourse.mozilla.org/t/bcd-use-in-the-wild-compat-tester-on-npm/25924
=> Add SphinxKnight's compat-tester to Projects

api/HTMLButtonElement.json
https://developer.mozilla.org/en-US/docs/Web/API/HTMLButtonElement
=> Add compat data for HTMLButtonElement

api/AudioContext.json
=> Correct AudioContest.outputLatency

api/DOMTokenList.json
Hello!
First time PR here, long time MDN docs fan. 
Adds the [DOMTokenList](https://developer.mozilla.org/en-US/docs/Web/API/DOMTokenList) compat data.
=> Adds DOMTokenList compat data

api/VideoPlaybackQuality.json
https://developer.mozilla.org/en-US/docs/Web/API/VideoPlaybackQuality
https://wicg.github.io/media-playback-quality/
=> add compat data for VideoPlaybackQuality

api/TextTrack.json
https://developer.mozilla.org/en-US/docs/Web/API/TextTrack
=> Add compat data for TextTrack

api/IDBVersionChangeRequest.json
https://developer.mozilla.org/en-US/docs/Web/API/IDBVersionChangeRequest
=> Add browser compat for IDBVersionChangeRequest

api/HTMLDListElement.json
https://developer.mozilla.org/en-US/docs/Web/API/HTMLDListElement
=> Add compat data for HTMLDListElement

api/HTMLDataElement.json
https://developer.mozilla.org/en-US/docs/Web/API/HTMLDataElement
=> Add compat data for HTMLDataElement

api/HTMLDialogElement.json
https://developer.mozilla.org/en-US/docs/Web/API/HTMLDialogElement
=> Add compat data for HTMLDialogElement

api/DocumentFragment.json
https://developer.mozilla.org/en-US/docs/Web/API/DocumentFragment
=> Add compat data for DocumentFragment

api/ServiceWorkerRegistration.json
This makes some corrections to the browser compatibility table data for the [`ServiceWorkerRegistration` API](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerRegistration).
=> Correct ServiceWorkerRegistration

api/Worker.json
This makes some corrections to the browser compatibility table data for the [`Worker` API](https://developer.mozilla.org/en-US/docs/Web/API/Worker).
=> Correct Worker

api/MediaError.json
https://developer.mozilla.org/en-US/docs/Web/API/MediaError
=> add compat data for MediaError

api/SpeechGrammar.json, package-lock.json
This is my first PR for this project, but wanted to update the tables for the new format. I'm happy to do the other APIs once I know this format is all clear!
=> SpeechGrammar API

api/IDBDatabaseException.json
https://developer.mozilla.org/en-US/docs/Web/API/IDBDatabaseException
Note: considered obsolete.
=> Add compat data for IDBDatabaseException

api/MediaKeyStatusMap.json
https://developer.mozilla.org/en-US/docs/Web/API/MediaKeyStatusMap
=> Add compat data for MediaKeyStatusMap

html/elements/link.json
As per conversation with Andreas Bovens in dev content coordination meeting.
=> adding correct compat data about link rel=preload

api/HTMLAudioElement.json
https://developer.mozilla.org/en-US/docs/Web/API/HTMLAudioElement
=> add compat data for HTMLAudioElement

api/HTMLVideoElement.json
https://developer.mozilla.org/en-US/docs/Web/API/HTMLVideoElement
=> Add compat data for HTMLVideoElement

api/MediaDeviceInfo.json
https://developer.mozilla.org/en-US/docs/Web/API/MediaDeviceInfo
=> add compat data for MediaDeviceInfo

api/NodeFilter.json
https://developer.mozilla.org/en-US/docs/Web/API/NodeFilter
=> Add compat data for NodeFilter

api/XSLTProcessor.json
https://developer.mozilla.org/en-US/docs/Web/API/XSLTProcessor
=> Add compat data for XSLTProcessor

api/XMLHttpRequestEventTarget.json
https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequestEventTarget
=> Add compat data for XMLHttpRequestEventTarget

api/HTMLFormElement.json
[https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement)
=> adding compat data for HTMLFormElement

api/MIDIAccess.json
https://developer.mozilla.org/en-US/docs/Web/API/MIDIAccess
=> Add compat data for MIDIAccess

api/MIDIInput.json
https://developer.mozilla.org/en-US/docs/Web/API/MIDIInput
=> Add compat data for MIDIInput

api/MIDIInputMap.json
https://developer.mozilla.org/en-US/docs/Web/API/MIDIInputMap
=> Add compat data for MIDIInputMap

api/MIDIOutputMap.json
https://developer.mozilla.org/en-US/docs/Web/API/MIDIOutputMap
=> Add compat data for MIDIOutputMap

api/AnimationEffectTimingProperties.json
=> add compat data for AnimationEffectTimingProperties

css/properties/display.json
Using the following sources:
- https://caniuse.com/#feat=css-display-contents
- https://www.chromestatus.com/feature/5663606012116992
- https://bugs.webkit.org/show_bug.cgi?id=157477
=> Update display: contents compat table

api/MediaStream.json
https://developer.mozilla.org/en-US/docs/Web/API/MediaStream
=> adding compat data for MediaStream

api/NavigatorConcurrentHardware.json
https://developer.mozilla.org/en-US/docs/Web/API/NavigatorConcurrentHardware
=> Add compat data for NavigatorConcurrentHardware

api/NavigatorGeolocation.json
https://developer.mozilla.org/en-US/docs/Web/API/NavigatorGeolocation
=> Add compat data for NavigatorGeolocation

api/NavigatorPlugins.json
https://developer.mozilla.org/en-US/docs/Web/API/NavigatorPlugins
=> Add compat data for NavigatorPlugins

api/MediaStreamConstraints.json
https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamConstraints
=> Add compat data for MediaStreamContraints

api/MediaStreamTrackEvent.json
https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrackEvent
=> Add compat data for MediaStreamTrackEvent

api/HTMLMeterElement.json, api/PerformanceNavigationTiming.json
https://developer.mozilla.org/docs/Web/API/HTMLMeterElement
=> add compat data for HTMLMeterElement

javascript/builtins/Object.json
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/values
Check compatibility on [node.green](http://node.green/#ES2017-features-Object-static-methods-Object-values)
=> Update nodejs compat for Object.values()

api/MediaStream.json
* fix standard track data
* fix incorrect values related to version_removed
https://discourse.mozilla.org/t/bug-in-new-compat-data/26398/6
=> Update compat data

api/HTMLUnknownElement.json
https://developer.mozilla.org/en-US/docs/Web/API/HTMLUnknownElement
=> add compat data for HTMLUnknownElement

api/MediaStreamTrack.json
https://www.chromestatus.com/feature/5145556682801152
=> Add version numbers for getCapabilities().

api/ImageBitmapRenderingContext.json
https://www.chromestatus.com/feature/5756043640438784
=> Correct Chrome version numbers.

api/Request.json
https://www.chromestatus.com/features/5760375567941632
=> Add keepalive property.

api/AbortController.json, api/AbortSignal.json
https://www.chromestatus.com/feature/5631483679080448
=> Add Chromium to Fetch AbortSignal and AbortController.

api/BlobBuilder.json, test/test-versions.js
=> Check for invalid combinations of `version_added` and `version_removed`

api/HTMLParamElement.json
https://developer.mozilla.org/en-US/docs/Web/API/HTMLParamElement
=> add compat data for HTMLParamElement

api/HTMLParagraphElement.json
https://developer.mozilla.org/en-US/docs/Web/API/HTMLParagraphElement
=> add compat data for HTMLParagraph Element

api/HTMLMetaElement.json
https://developer.mozilla.org/en-US/docs/Web/API/HTMLMetaElement
=> add compat data for HTMLMetaElement

api/HTMLModElement.json
https://developer.mozilla.org/en-US/docs/Web/API/HTMLModElement
=> add compat data for HTMLModElement

api/HTMLSpanElement.json
https://developer.mozilla.org/en-US/docs/Web/API/HTMLSpanElement
=> add compat data for HTMLSpanElement

api/HTMLOptGroupElement.json
https://developer.mozilla.org/en-US/docs/Web/API/HTMLOptGroupElement
=> add compat data for HTMLOptGroupElement

api/HTMLPreElement.json
https://developer.mozilla.org/en-US/docs/Web/API/HTMLPreElement
=> add compat data for HTMLPreElement

api/HTMLTableCaptionElement.json
https://developer.mozilla.org/en-US/docs/Web/API/HTMLTableCaptionElement
=> Add compat data for HTMLTableCaptionElement

api/HTMLHeadElement.json
[https://developer.mozilla.org/en-US/docs/Web/API/HTMLHeadElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLHeadElement)
=> adding compat data for api.HTMLHeadElement

api/HTMLPictureElement.json
https://developer.mozilla.org/en-US/docs/Web/API/HTMLPictureElement
=> add compat data for HTMLPictureElement

api/HTMLStyleElement.json
https://developer.mozilla.org/en-US/docs/Web/API/HTMLStyleElement
=> add compat data for HTMLStyleElement

api/HTMLOListElement.json
https://developer.mozilla.org/en-US/docs/Web/API/HTMLOListElement
=> add compat data for HTMLOListElement

api/HTMLOptionElement.json
https://developer.mozilla.org/en-US/docs/Web/API/HTMLOptionElement
=> add compat data for HTMLOptionElement

api/HTMLOptionsCollection.json
https://developer.mozilla.org/en-US/docs/Web/API/HTMLOptionsCollection
=> add compat data for HTMLOptionsCollection

api/HTMLOutputElement.json
https://developer.mozilla.org/en-US/docs/Web/API/HTMLOutputElement
=> add compat data for HTMLOutputElement

README.md, index.js, schemas/compat-data-schema.md, test/lint.js, webdriver/commands/Get_Element_Tag_Name.json
Adding webdriver directory, command subdirectory, and Get Element Tag Name data as a first example. Next step would be to get feedback on this addition, before continuing further.
=> WebDriver initial push

test/lint.js
=> Fixed Windows issue related to schema validation of browser info

svg/elements/circle.json
https://developer.mozilla.org/en-US/docs/Web/SVG/Element/circle
=> Add compat data for SVG <circle>

api/RTCCertificate.json, api/RTCDTMFSender.json, api/RTCDataChannel.json, api/RTCDtlsTransport.json, api/RTCErrorEvent.json, api/RTCIceCandidate.json, api/RTCIceTransport.json, api/RTCIdentityProviderGlobalScope.json, api/RTCIdentityProviderRegistrar.json, api/RTCPeerConnection.json, api/RTCPeerConnectionIceErrorEvent.json, api/RTCPeerConnectionIceEvent.json, api/RTCStatsEvent.json, api/RTCTrackEvent.json
Generated via https://github.com/dontcallmedom/webidl2mdnbcd
Both add missing files for some interfaces, and missing methods/properties for existing files
=> Update structure of BCD data for WebRTC interfaces

api/Request.json, api/Response.json
Generated via https://github.com/dontcallmedom/webidl2mdnbcd from https://fetch.spec.whatwg.org/
=> Update structure of BCD data for fetch interfaces

api/AudioBufferSourceNode.json, api/AudioWorkletGlobalScope.json, api/AudioWorkletNode.json, api/AudioWorkletProcessor.json, api/BaseAudioContext.json, api/MediaElementAudioSourceNode.json, api/MediaStreamTrackAudioSourceNode.json, api/ScriptProcessorNode.json
Generated via https://github.com/dontcallmedom/webidl2mdnbcd from https://webaudio.github.io/web-audio-api/
=> Update structure of BCD data for Web Audio interfaces

api/ExtendableMessageEvent.json, api/FetchEvent.json, api/Navigator.json, api/ServiceWorkerContainer.json, api/ServiceWorkerGlobalScope.json, api/ServiceWorkerRegistration.json, api/WindowClient.json
Generated via https://github.com/dontcallmedom/webidl2mdnbcd from https://w3c.github.io/ServiceWorker/
=> Update structure of BCD data for Service Worker interfaces

api/AnimationEffect.json, api/KeyframeEffect.json
Generated via https://github.com/dontcallmedom/webidl2mdnbcd from https://drafts.csswg.org/web-animations/
=> Update structure of BCD data for Web Animation interfaces

svg/elements/ellipse.json
https://developer.mozilla.org/en-US/docs/Web/SVG/Element/ellipse
=> Add compat data for SVG <ellipse>

api/Notification.json
Generated via https://github.com/dontcallmedom/webidl2mdnbcd from https://notifications.spec.whatwg.org/
=> Update structure of BCD data for Notifcations interfaces

api/StorageManager.json
Generated via https://github.com/dontcallmedom/webidl2mdnbcd from https://storage.spec.whatwg.org/
=> Update structure of BCD data for Storage interfaces

api/URL.json, api/URLSearchParams.json
Generated via https://github.com/dontcallmedom/webidl2mdnbcd from https://url.spec.whatwg.org/
=> Update structure of BCD data for URL interfaces

api/TextDecoder.json, api/TextEncoder.json
Generated via https://github.com/dontcallmedom/webidl2mdnbcd from https://encoding.spec.whatwg.org/
=> Update structure of BCD data for Encoding interfaces

svg/elements/missing-glyph.json
Link: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/missing-glyph
=> add compat data for svg <missing-glyph>

api/PushSubscriptionChangeEvent.json, api/PushSubscriptionOptions.json
Generated via https://github.com/dontcallmedom/webidl2mdnbcd from https://w3c.github.io/push-api/
=> Update structure of BCD data for Push API

svg/elements/solidcolor.json
Link: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/solidcolor
=> add compat data for SVG <solidcolor>

api/PaymentRequest.json, api/PaymentResponse.json
Generated via https://github.com/dontcallmedom/webidl2mdnbcd from https://w3c.github.io/payment-request/
=> Update structure of BCD data for Payment Request API

svg/elements/font-face-uri.json
Link: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/font-face-uri
=> add compat data for SVG <font-face-uri>

svg/elements/svg.json
https://developer.mozilla.org/en-US/docs/Web/SVG/Element/svg
=> Add compat data for SVG <svg>

api/MediaMetadata.json, api/MediaSession.json, api/Navigator.json
=> Migrate data from existing MDN compat data  for MediaSession

api/ProgressEvent.json, api/XMLHttpRequestEventTarget.json, api/XMLHttpRequestUpload.json
Generated via https://github.com/dontcallmedom/webidl2mdnbcd from https://xhr.spec.whatwg.org/
Skipping FormData since its addition is pending in #1487
=> Update structure of BCD data for XHR interfaces

api/CompositionEvent.json, api/FocusEvent.json, api/InputEvent.json, api/KeyboardEvent.json, api/MouseEvent.json, api/UIEvent.json, api/WheelEvent.json
=> Update structure of BCD data for UI Events

api/AudioTrack.json, api/TextTrack.json, api/VideoTrack.json
=>  Update structure of BCD data for Media Source Extension API 

svg/elements/use.json
https://developer.mozilla.org/en-US/docs/Web/SVG/Element/use
=> Add compat data for SVG <use>

api/HTMLLabelElement.json
I've ignored the note in the old-fashioned compat table, because realistically I think it is so subtle that it doesn't make any difference to web devs, and the notes also seems to contradict the property description, which seems to suggest that it is the same thing anyway. I think this will confuse more than it helps.
=> adding HTMLLabelElement data to BCD

api/HTMLMapElement.json
See https://developer.mozilla.org/en-US/docs/Web/API/HTMLMapElement
=> adding HTMLMapElement data to BCD

api/DeviceMotionEvent.json, api/DeviceOrientationEvent.json
Generated via https://github.com/dontcallmedom/webidl2mdnbcd from https://w3c.github.io/deviceorientation/spec-source-orientation.html
=> Update structure of BCD data for DeviceOrientation interfaces

svg/elements/line.json
https://developer.mozilla.org/en-US/docs/Web/SVG/Element/line
=> Add compat data for SVG <line>

svg/elements/marker.json
https://developer.mozilla.org/en-US/docs/Web/SVG/Element/marker
=> Add compat data for SVG <marker>

svg/elements/mask.json
https://developer.mozilla.org/en-US/docs/Web/SVG/Element/mask
=> Add compat data for SVG <mask>

svg/elements/path.json
https://developer.mozilla.org/en-US/docs/Web/SVG/Element/path
=> Add compat data for SVG <path>

svg/elements/polygon.json
https://developer.mozilla.org/en-US/docs/Web/SVG/Element/polygon
=> Add compat data for SVG <polygon>

svg/elements/polyline.json
https://developer.mozilla.org/en-US/docs/Web/SVG/Element/polyline
=> Add compat data for SVG <polyline>

svg/elements/text.json
https://developer.mozilla.org/en-US/docs/Web/SVG/Element/text
=> Add compat data for SVG <text>

api/Performance.json
Generated via https://github.com/dontcallmedom/webidl2mdnbcd from https://w3c.github.io/hr-time/
=> Update structure of BCD data for High resolution Time

api/Clipboard.json, api/ClipboardEvent.json
Generated via https://github.com/dontcallmedom/webidl2mdnbcd from https://w3c.github.io/clipboard-apis/
=> Update structure of BCD data for Clipboard API

api/PerformanceLongTaskTiming.json, api/TaskAttributionTiming.json
Generated via https://github.com/dontcallmedom/webidl2mdnbcd from https://w3c.github.io/longtasks/
=> Update structure of BCD data for Long Tasks API

api/Element.json
Generated via https://github.com/dontcallmedom/webidl2mdnbcd from http://dom.spec.whatwg.org/
Subset of #1418
=> Update structure of BCD data for Element interface

api/HTMLUListElement.json
https://developer.mozilla.org/en-US/docs/Web/API/HTMLUListElement
=> Adding HTMLUList data to BCD

svg/elements/feMerge.json
link: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feMerge
=> Add compat data for SVG <feMerge>

svg/elements/pattern.json
https://developer.mozilla.org/en-US/docs/Web/SVG/Element/pattern
=> Add compat data for SVG <pattern>

svg/elements/textpath.json
https://developer.mozilla.org/en-US/docs/Web/SVG/Element/textPath
=> Add compat data for SVG <textPath>

api/CSSStyleRule.json
Assumed identical compat for style property.
=> Add compat data for CSSStyleRule

svg/elements/feMergeNode.json
Link: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feMergeNode
=> Add compat data for SVG <feMergeNode>

svg/elements/vkern.json
Link: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/vkern
=> add compat data for SVG <vkern>

svg/elements/view.json
Link: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/view
=> add compat data for SVG <view>

svg/elements/tref.json
Link: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/tref
=> add compat data for SVG <tref>

svg/elements/switch.json
Link: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/switch
=> add compat data for SVG <switch>

svg/elements/mesh.json
Not yet documented on MDN as it's a very new SVG2 feature
=> Add compat data for SVG <mesh>

svg/elements/meshpatch.json
Not yet documented on MDN as it's a very new SVG2 feature
=> Add compat data for SVG <meshpatch>

svg/elements/clippath.json
https://developer.mozilla.org/en-US/docs/Web/SVG/Element/clipPath
=> Add compat data for SVG <clipPath>

svg/elements/metadata.json
https://developer.mozilla.org/docs/Web/SVG/Element/metadata
=> Add compat data for SVG <metadata>

svg/elements/title.json
https://developer.mozilla.org/docs/Web/SVG/Element/title
=> Add compat data for SVG <title>

svg/elements/tspan.json
https://developer.mozilla.org/en-US/docs/Web/SVG/Element/tspan
=> Add compat data for SVG <tspan>

api/HTMLFrameSetElement.json
[https://developer.mozilla.org/en-US/docs/Web/API/HTMLFrameSetElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFrameSetElement)
=> adding compat data for api.HTMLFrameSetElement

browsers/uc_android.json
Using script in https://github.com/mdn/browser-compat-data/commit/8dc7ef0f27bd965f59b44be8d0e0aa908cace425#diff-418c45cbb7084debcf7337df7d2928a0.
=> Add another UC international version

browsers/uc_chinese_android.json
Using the instructions in https://github.com/mdn/browser-compat-data/commit/d00712cf6653a10786d5ea42c951ba5cee995ce5#diff-8bad33a4e0606c9f463ec43c302317b5.
=> Add two versions of UC Chinese 11.9

svg/elements/feOffset.json
Link: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feOffset
=> Add compat data for SVG <feOffset>

svg/elements/meshgradient.json
Not yet documented on MDN as it's a very new SVG2 feature
=> Add compat data for SVG <meshgradient>

api/VRDisplay.json, api/VRDisplayCapabilities.json, api/VRDisplayEvent.json, api/VREyeParameters.json, api/VRFieldOfView.json, api/VRFrameData.json, api/VRPose.json
Please don't merge this yet. I want to get it sanity checked by someone at MS.
=> Add VR data for Edge.

svg/elements/fePointLight.json
Link: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/fePointLight
=> Add compat data for SVG <fePointLight>

svg/elements/feSpecularLighting.json
Link: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feSpecularLighting
=> Add compat data for SVG <feSpecularLighting>

svg/elements/feSpotLight.json
Link: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feSpotLight
=> Add compat data for SVG <feSpotLight>

api/PerformanceLongTaskTiming.json
Dropped browsers:
- Firefox OS
- IE phone
=> Adding compat data for PerformanceLongTaskTiming

svg/elements/solidcolor.json
=> Correct solidcolor.

webextensions/api/devtools.json
See:
https://bugzilla.mozilla.org/show_bug.cgi?id=1311171#c80
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/devtools.network/onRequestFinished
=> Add note for devtools.network.onRequestFinished

svg/elements/foreignObject.json
Link: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/foreignObject
=> add compat data for SVG <foreignObject>

svg/elements/symbol.json
Link: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/symbol
=> add compat data for SVG <symbol>

svg/elements/stop.json
Link: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/stop
=> add compat data for SVG <stop>

svg/elements/script.json
Link: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/script
=> Add compat data for SVG <script>

svg/elements/feMorphology.json
Link: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feMorphology
=> Add compat data for SVG <feMorphology>

api/CacheStorage.json
=> Add compat data for CacheStorage

api/DOMTokenList.json
see comment at https://github.com/mdn/browser-compat-data/pull/1121
=> api/DOMTokenList: updates data for Edge:

README.md
New contributors would like to know how long it will take for their changes to appear on MDN.
=> Document how MDN tables are updated

svg/elements/set.json
@JeremiePat 
I'm going to stop spamming you now. These are corrections of PRs that were merged while I was traveling. I'll get to everything that's in my inbox. I just don't know when. If there's anything in particular you have concerns about, just let me know.
=> Correct set.

README.md, index.js, mathml/elements/math.json, schemas/compat-data-schema.md, test/lint.js
This PR begins work on converting MathML data, which consists of a total of 37 elements.
---
P.S.: Can the emoji used in the label be ➗?
=> Begin work on converting MathML data

README.md
I don't think there's much that can be said about a one character PR, but I still will.
=> Typo: add missing }

api/HTMLSourceElement.json
https://developer.mozilla.org/en-US/docs/Web/API/HTMLSourceElement
=> Add compat  data for HTMLSourceElement

api/NavigatorID.json
https://developer.mozilla.org/en-US/docs/Web/API/NavigatorID
=> Add compat data for NavigatorID

api/Cache.json
@Elchi3 Here's my cache update.
=> Correct Cache API data.

api/NavigatorOnLine.json
https://developer.mozilla.org/en-US/docs/Web/API/NavigatorOnLine
=> Add compat data for NavigatorOnLine 

api/NavigatorStorage.json
https://developer.mozilla.org/en-US/docs/Web/API/NavigatorStorage
=> Add compat data for NavigatorStorage

api/LinkStyle.json
If the API is based on a CSSWG working draft spec but MDN page does not explicitly label it "experimental", is the API experimental?
=> Add compat data for LinkStyle

api/SVGAnimateTransformElement.json
https://developer.mozilla.org/en-US/docs/Web/API/SVGAnimateTransformElement
Set Safari and Safari IOS versions based on https://developer.apple.com/documentation/webkitjs/svganimatetransformelement
=> Add compat data for SVGAnimateTransformElement

api/FocusEvent.json
[FocusEvent](https://developer.mozilla.org/docs/Web/API/FocusEvent)
=> Add compat data for FocusEvent

api/ClipboardEvent.json
[ClipboardEvent](https://developer.mozilla.org/docs/Web/API/ClipboardEvent)
=> Add compat data for ClipboardEvent

svg/elements/feTurbulence.json
Link: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feTurbulence
=> Add compat data for SVG <feTurbulence>

svg/elements/hkern.json
Link: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/hkern
=> add compat data for SVG <hkern>

api/CSSCounterStyleRule.json
https://developer.mozilla.org/en-US/docs/Web/API/CSSCounterStyleRule
=> adding compat data for CSSCounterStyleRule

webextensions/api/devtools.json
See https://bugzilla.mozilla.org/show_bug.cgi?id=1311177#c40.
=> Add note about getHAR

api/HTMLTitleElement.json
https://developer.mozilla.org/en-US/docs/Web/API/HTMLTitleElement
=> Add compat data for HTMLTitleElement

api/HTMLHeadingElement.json
https://developer.mozilla.org/en-US/docs/Web/API/HTMLHeadingElement
=> Add compat data for HTMLHeadingElement

api/HTMLProgressElement.json
https://developer.mozilla.org/en-US/docs/Web/API/HTMLProgressElement
=> Add compat data for HTMLProgressElement

api/HTMLLinkElement.json
Ignored older info from child property "as" and "referrerPolicy"
=> Add compat data for HTMLLinkElement

api/HTMLTableSectionElement.json
https://developer.mozilla.org/en-US/docs/Web/API/HTMLTableSectionElement
=> Adding HTMLTableSectionElement data to BCD

api/HTMLFieldSetElement.json
https://developer.mozilla.org/en-US/docs/Web/API/HTMLFieldSetElement
=> Add compat data for HTMLFieldSetElement

api/HTMLScriptElement.json
https://developer.mozilla.org/en-US/docs/Web/API/HTMLScriptElement
=> Add compat data for HTMLScriptElement

api/HTMLTrackElement.json
https://developer.mozilla.org/en-US/docs/Web/API/HTMLTrackElement
=> adding HTMLTrackElement data to BCD

api/HTMLTableCellElement.json
https://developer.mozilla.org/en-US/docs/Web/API/HTMLTableCellElement
=> adding HTMLTableCellElement data to BCD

api/ConstrainBoolean.json
https://developer.mozilla.org/en-US/docs/Web/API/ConstrainBoolean
=> Add compat data for ConstrainBoolean (Media Streams API)

api/LocalMediaStream.json
https://developer.mozilla.org/en-US/docs/Web/API/LocalMediaStream
=> Add compat data for LocalMediaStream (Media Streams API)

api/SpeechSynthesisUtterance.json
https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesisUtterance
=> Add compat data for SpeechSynthesisUtterance

api/Console.json
Add substitution strings support for IE10
=> Add compat data for string substitution support in IE

api/SVGRect.json
Link: https://developer.mozilla.org/en-US/docs/Web/API/SVGRect
@jpmedley : mismatching Chrome/Opera version numbers, could you have a look?
=> Add compat data for SVGRect

api/SVGCircleElement.json
Link: https://developer.mozilla.org/en-US/docs/Web/API/SVGCircleElement
=> add compat data for SVGCircleElement

api/SVGEllipseElement.json
Link: https://developer.mozilla.org/en-US/docs/Web/API/SVGEllipseElement
=> add compat data for SVGEllipseElement

api/SVGGElement.json
Link: https://developer.mozilla.org/en-US/docs/Web/API/SVGGElement
=> add compat data for SVGGElement

api/SVGGraphicsElement.json
Link: https://developer.mozilla.org/en-US/docs/Web/API/SVGGraphicsElement
=> add compat data for SVGGraphicsElement

api/SVGLineElement.json
Link: https://developer.mozilla.org/en-US/docs/Web/API/SVGLineElement
=> add compat data for SVGLineElement

api/SVGMaskElement.json
Link: https://developer.mozilla.org/en-US/docs/Web/API/SVGMaskElement
=> Add compat data for SVGMaskElement

api/SVGGeometryElement.json
Link: https://developer.mozilla.org/en-US/docs/Web/API/SVGGeometryElement
=> add compat data for SVGGeometryElement

api/SVGElement.json
Link: https://developer.mozilla.org/en-US/docs/Web/API/SVGElement
=> add compat data for SVGElement

svg/elements/font-face.json
Link: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/font-face
=> add compat data for SVG <font-face>

api/SVGPatternElement.json
Link: https://developer.mozilla.org/en-US/docs/Web/API/SVGPatternElement
=> Add compat data for SVGPatternElement

api/SVGPolylineElement.json
Link: https://developer.mozilla.org/en-US/docs/Web/API/SVGPolylineElement
=> Add compat data for SVGPolylineElement

api/SVGRectElement.json
Link: https://developer.mozilla.org/en-US/docs/Web/API/SVGRectElement
=> Add compat data for SVGRectElement

api/SVGTextElement.json
Link: https://developer.mozilla.org/en-US/docs/Web/API/SVGTextElement
=> Add compat data for SVGTextElement

api/SVGTextContentElement.json
Link: https://developer.mozilla.org/en-US/docs/Web/API/SVGTextContentElement
=> Add compat data for SVGTextContentElement

api/SVGTextPathElement.json
Link: https://developer.mozilla.org/en-US/docs/Web/API/SVGTextPathElement
=> Add compat data for SVGTextPathElement

api/SVGTextPositioningElement.json
Link: https://developer.mozilla.org/en-US/docs/Web/API/SVGTextPositioningElement
=> Add compat data for SVGTextPositioningElement

api/SVGTSpanElement.json
Link: https://developer.mozilla.org/en-US/docs/Web/API/SVGTSpanElement
=> Add compat data for SVGTSpanElement

api/SVGUseElement.json
Link: https://developer.mozilla.org/en-US/docs/Web/API/SVGUseElement
=> Add compat data for SVGUseElement

api/SVGPolygonElement.json
Link: https://developer.mozilla.org/en-US/docs/Web/API/SVGPolygonElement
=> Add compat data for SVGPolygonElement

api/SVGPathElement.json
Link: https://developer.mozilla.org/en-US/docs/Web/API/SVGPathElement
File is sooo long!
=> Add compat data for SVGPathElement

svg/elements/desc.json
Link: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/desc
=> add compat data for SVG <desc>

svg/elements/font-face-format.json
Link: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/font-face-format
=> add compat data for SVG <font-face-format>

svg/elements/font-face-name.json
Link: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/font-face-name
=> add compat data for SVG <font-face-name>

svg/elements/mpath.json
Link: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/mpath
=> Add compat data for SVG <mpath>

svg/elements/discard.json
Link: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/discard
=> add compat data for SVG <discard>

svg/elements/hatchpath.json
Link: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/hatchpath
=> add compat data for SVG <hatchpath>

svg/elements/cursor.json
Link: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/cursor
=> add compat data for SVG <cursor>

svg/elements/animateTransform.json
https://developer.mozilla.org/docs/Web/SVG/Element/animateTransform
=> Add compat data for SVG <animateTransform>

svg/elements/color-profile.json
Link: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/color-profile
=> add compat data for SVG <color-profile>

svg/elements/animateMotion.json
https://developer.mozilla.org/docs/Web/SVG/Element/animateMotion
=> Add compat data for SVG <animateMotion>

svg/elements/animate.json
https://developer.mozilla.org/docs/Web/SVG/Element/animate
=> Add compat data for SVG <animate>

svg/elements/font.json
Link: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/font
=> add compat data for SVG <font>

svg/elements/image.json
Link: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/image
=> Add compat data for SVG <image>

svg/elements/hatch.json
Link: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/hatch
=> add compat data for SVG <hatch>

svg/elements/linearGradient.json
Link: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/linearGradient
=> Add compat data for SVG <linearGradient>

svg/elements/radialGradient.json
Link: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/radialGradient
=> Add compat data for SVG <radialGradient>

svg/elements/altGlyph.json
Link: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/altGlyph
=> add compat data for SVG <altGlyph>

svg/elements/glyph.json
Link: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/glyph
=> add compat data for SVG <glyph>

api/Clipboard.json
[Clipboard](https://developer.mozilla.org/docs/Web/API/Clipboard)
=> Web APIs: update Clipboard with MDN compat data

api/PerformanceFrameTiming.json
Dropped browsers:
- Firefox OS
- IE phone
=> Add compat data for PerformanceFrameTiming

api/DOMHighResTimestamp.json
https://developer.mozilla.org/en-US/docs/Web/API/DOMHighResTimeStamp
=> add compat data for DOMHighResTimestamp

api/PhotoCapabilities.json
https://developer.mozilla.org/en-US/docs/Web/API/PhotoCapabilities
=> adding compat data for PhotoCapabilities

api/BluetoothRemoteGATTDescriptor.json
https://developer.mozilla.org/en-US/docs/Web/API/BluetoothRemoteGATTDescriptor
=> adding compat data for BluetoothRemoteGATTDescriptor

api/BluetoothCharacteristicProperties.json
https://developer.mozilla.org/en-US/docs/Web/API/BluetoothCharacteristicProperties
=> adding compat data for BluetoothCharacteristicProperties

api/BluetoothAdvertisingData.json
https://developer.mozilla.org/en-US/docs/Web/API/BluetoothAdvertisingData
=> adding compat data for BluetoothAdvertisingData

browsers/safari.json
Release date according to https://webkit.org/blog/8216/new-webkit-features-in-safari-11-1/
=> update safari compat data

api/WindowEventHandlers.json
https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers
=> Add compat data for WindowEventHandlers

api/SVGAltGlyphItemElement.json
https://developer.mozilla.org/en-US/docs/Web/API/SVGAltGlyphItemElement
=> Add compat data for SVGAltGlyphItemElement

api/SVGAngle.json
https://developer.mozilla.org/en-US/docs/Web/API/SVGAngle
=> Add compat data for SVGAngle

api/SVGAnimateColorElement.json
https://developer.mozilla.org/en-US/docs/Web/API/SVGAnimateColorElement
=> Add compat data for SVGAnimateColorElement

api/SVGAnimatedBoolean.json
https://developer.mozilla.org/en-US/docs/Web/API/SVGAnimatedBoolean
=> Add compat data for SVGAnimatedBoolean

api/SVGAnimatedEnumeration.json
https://developer.mozilla.org/en-US/docs/Web/API/SVGAnimatedEnumeration
=> Add compat data for SVGAnimatedEnumeration

api/SVGAnimatedPoints.json
https://developer.mozilla.org/en-US/docs/Web/API/SVGAnimatedPoints
=> Add compat data for SVGAnimatedPoints

api/SVGAnimatedLengthList.json
https://developer.mozilla.org/en-US/docs/Web/API/SVGAnimatedLengthList
=> Add compat data for SVGAnimatedLengthList

api/SVGAnimatedNumber.json
https://developer.mozilla.org/en-US/docs/Web/API/SVGAnimatedNumber
=> Add compat data for SVGAnimatedNumber

api/SVGAnimatedNumberList.json
https://developer.mozilla.org/en-US/docs/Web/API/SVGAnimatedNumberList
=> Add browser compat data for SVGAnimatedNumberList

api/SVGAnimatedString.json
https://developer.mozilla.org/en-US/docs/Web/API/SVGAnimatedString
=> Add compat data for SVGAnimatedString

api/SVGColorProfileElement.json
https://developer.mozilla.org/en-US/docs/Web/API/SVGColorProfileElement
=> Add compat data for SVGColorProfileElement

api/SVGComponentTransferFunctionElement.json
https://developer.mozilla.org/en-US/docs/Web/API/SVGComponentTransferFunctionElement
=> Add compat data for SVGComponentTransferFunctionElement

api/SVGCursorElement.json
https://developer.mozilla.org/en-US/docs/Web/API/SVGCursorElement
=> Add compat data for SVGCursorElement

api/SVGDefsElement.json
https://developer.mozilla.org/en-US/docs/Web/API/SVGDefsElement
=> Add compat data for SVGDefsElement

api/SVGDescElement.json
https://developer.mozilla.org/en-US/docs/Web/API/SVGDescElement
=> Add compat data for SVGDescElement

api/SVGExternalResourcesRequired.json
https://developer.mozilla.org/en-US/docs/Web/API/SVGExternalResourcesRequired
=> Add compat data for SVGExternalResourcesRequired

api/KeyboardEvent.json
[KeyboardEvent API](https://developer.mozilla.org/docs/Web/API/KeyboardEvent). I would usually put the same implementation version for desktop and mobile, but given that it's for the keyboard I was not sure and therefore copied verbatim.
=> Add compat data for KeyboardEvent

api/Element.json
Note this is my first shot at this, hope I did all right :)
=> Transfer of data for Web/API/Element/matches

api/CaretPosition.json
[CaretPosition](https://developer.mozilla.org/docs/Web/API/CaretPosition#Browser_compatibility)
=> Web APIs: add CaretPosition

api/SVGFEDiffuseLightingElement.json
https://developer.mozilla.org/en-US/docs/Web/API/SVGFEDiffuseLightingElement
=> add compat data for SVGFEDiffuseLightingElement

api/SVGFEFuncBElement.json
https://developer.mozilla.org/en-US/docs/Web/API/SVGFEFuncBElement
=> add compat data for SVGFEFuncBElement

api/SVGFEFuncGElement.json
https://developer.mozilla.org/en-US/docs/Web/API/SVGFEFuncGElement
=> add compat data for SVGFEFuncGElement

api/SVGFEFuncRElement.json
https://developer.mozilla.org/en-US/docs/Web/API/SVGFEFuncRElement
=> add compat data for SVGFEFuncRElement

api/SVGFEGaussianBlurElement.json
https://developer.mozilla.org/en-US/docs/Web/API/SVGFEGaussianBlurElement
=> add compat data for SVGFEGaussianBlurElement

api/SVGFEImageElement.json
https://developer.mozilla.org/en-US/docs/Web/API/SVGFEImageElement
=> add compat data for SVGFEImageElement

api/SVGFEMergeElement.json
https://developer.mozilla.org/en-US/docs/Web/API/SVGFEMergeElement
=> Add compat data for SVGFEMergeElement

api/SVGFEMergeNodeElement.json
https://developer.mozilla.org/en-US/docs/Web/API/SVGFEMergeNodeElement
=> Add compat data for SVGFEMergeNodeElement

api/SVGFEMorphologyElement.json
https://developer.mozilla.org/en-US/docs/Web/API/SVGFEMorphologyElement
=> Add compat data SVGFEMorphologyElement

api/SVGFEPointLightElement.json
https://developer.mozilla.org/en-US/docs/Web/API/SVGFEPointLightElement
=> Add compat data for SVGFEPointLightElement

api/SVGFEOffsetElement.json
https://developer.mozilla.org/en-US/docs/Web/API/SVGFEOffsetElement
=> Add compat data for SVGFEOffsetElement

api/SVGFEComponentTransferElement.json
https://developer.mozilla.org/en-US/docs/Web/API/SVGFEComponentTransferElement
=> Add compat data for SVGFEComponentTransferElement

api/SVGFETurbulenceElement.json
https://developer.mozilla.org/en-US/docs/Web/API/SVGFETurbulenceElement
=> Add compat data for SVGFETurbulenceElement

api/SVGFilterPrimitiveStandardAttributes.json
https://developer.mozilla.org/en-US/docs/Web/API/SVGFilterPrimitiveStandardAttributes
=> Add compat data for SVGFilterPrimitiveStandardAttributes

api/SVGFontElement.json
https://developer.mozilla.org/en-US/docs/Web/API/SVGFontElement
=> Add compat data for SVGFontElement

api/SVGFontFaceElement.json
https://developer.mozilla.org/en-US/docs/Web/API/SVGFontFaceElement
=> Add compat data for SVGFontFaceElement

api/SVGFilterElement.json
https://developer.mozilla.org/en-US/docs/Web/API/SVGFilterElement
=> Add compat data for SVGFilterElement

browsers/opera.json
Looks like Opera released a new major version :)
https://blogs.opera.com/mobile/2018/04/opera-introduces-opera-touch-a-cool-new-mobile-browser/?utm_medium=sm&utm_source=twitter&utm_campaign=brand_touch_1_250418_gl
=> update Opera version

api/SVGGeometryElement.json
I reviewed this because of [this PR](https://github.com/mdn/browser-compat-data/pull/1566). Unfortunately, I wasn't able to get an answer to maboa's question.
=> Improvements to SVGGeometryElement data.

svg/elements/textpath.json
See ddn bugs:
- support for side: https://bugzilla.mozilla.org/show_bug.cgi?id=1446650
- support for path: https://bugzilla.mozilla.org/show_bug.cgi?id=1446617
=> Add support for side and path in Firefox

api/SVGFontFaceFormatElement.json
https://developer.mozilla.org/en-US/docs/Web/API/SVGFontFaceFormatElement
=> Add compat data for SVGFontFaceFormatElement

api/SVGFontFaceSrcElement.json
https://developer.mozilla.org/en-US/docs/Web/API/SVGFontFaceSrcElement
=> Add compat data for SVGFontFaceSrcElement

api/SVGForeignObjectElement.json
https://developer.mozilla.org/en-US/docs/Web/API/SVGForeignObjectElement
=> Add compat data for SVGForeignObjectElement

api/SVGFontFaceUriElement.json
https://developer.mozilla.org/en-US/docs/Web/API/SVGFontFaceUriElement
=> Add compat data for SVGFontFaceUriElement

api/SVGGradientElement.json
https://developer.mozilla.org/en-US/docs/Web/API/SVGGradientElement
=> Add compat data for SVGGradientElement

api/SVGGlyphElement.json
https://developer.mozilla.org/en-US/docs/Web/API/SVGGlyphElement
=> Add compat data for SVGGlyphElement

api/SVGGlyphRefElement.json
https://developer.mozilla.org/en-US/docs/Web/API/SVGGlyphRefElement
=> Add compat data for SVGGlyphRefElement

api/SVGLength.json
https://developer.mozilla.org/en-US/docs/Web/API/SVGLength
=> Add compat data for SVGLength

api/SVGLengthList.json
https://developer.mozilla.org/en-US/docs/Web/API/SVGLengthList
=> Add compat data for SVGLengthList

api/SVGHKernElement.json
https://developer.mozilla.org/en-US/docs/Web/API/SVGHKernElement
=> Add compat data for SVGHKernElement

api/SVGLinearGradientElement.json
https://developer.mozilla.org/en-US/docs/Web/API/SVGLinearGradientElement
=> Add compat data for SVGLinearGradientElement

api/SVGMPathElement.json
https://developer.mozilla.org/en-US/docs/Web/API/SVGMPathElement
=> Add compat data for SVGMPathElement

api/SVGMeshElement.json
https://developer.mozilla.org/en-US/docs/Web/API/SVGMeshElement
=> Add compat data for SVGMeshElement

api/SVGMetadataElement.json
https://developer.mozilla.org/en-US/docs/Web/API/SVGMetadataElement
=> Add compat data for SVGMetadataElement

api/SVGMatrix.json
https://developer.mozilla.org/en-US/docs/Web/API/SVGMatrix
=> Add compat data for SVGMatrix

api/SVGScriptElement.json
https://developer.mozilla.org/en-US/docs/Web/API/SVGScriptElement
=> Add compat data for SVGScriptElement

api/SVGSetElement.json
https://developer.mozilla.org/en-US/docs/Web/API/SVGSetElement
=> Add compat data for SVGSetElement

api/SVGStopElement.json
https://developer.mozilla.org/en-US/docs/Web/API/SVGStopElement
=> Add compat data for SVGStopElement

api/SVGSolidcolorElement.json
https://developer.mozilla.org/en-US/docs/Web/API/SVGSolidcolorElement
=> Add compat data for SVGSolidcolorElement

api/SVGStylable.json
https://developer.mozilla.org/en-US/docs/Web/API/SVGStylable
=> Add compat data for SVGStylable

api/SVGStringList.json
https://developer.mozilla.org/en-US/docs/Web/API/SVGStringList
=> Add compat data for SVGStringList

api/SVGSwitchElement.json
https://developer.mozilla.org/en-US/docs/Web/API/SVGSwitchElement
=> Add compat data for SVGSwitchElement

api/SVGSymbolElement.json
https://developer.mozilla.org/en-US/docs/Web/API/SVGSymbolElement
=> Add compat data for SVGSymbolElement

api/SVGTRefElement.json
https://developer.mozilla.org/en-US/docs/Web/API/SVGTRefElement
=> Add compat data for SVGTRefElement

api/SVGTitleElement.json
https://developer.mozilla.org/en-US/docs/Web/API/SVGTitleElement
=> Add compat data for SVGTitleElement

api/SVGTransform.json
https://developer.mozilla.org/en-US/docs/Web/API/SVGTransform
=> Add compat data for SVGTransform

api/SVGTests.json
https://developer.mozilla.org/en-US/docs/Web/API/SVGTests
=> Add compat data for SVGTests

api/SVGTransformable.json
https://developer.mozilla.org/en-US/docs/Web/API/SVGTransformable
=> Add compat data for SVGTransformable

api/SVGURIReference.json
https://developer.mozilla.org/en-US/docs/Web/API/SVGURIReference
=> Add compat data for SVGURIReference

api/SVGTransformList.json
https://developer.mozilla.org/en-US/docs/Web/API/SVGTransformList
=> Add compat data for SVGTransformList

api/SVGUnitTypes.json
https://developer.mozilla.org/en-US/docs/Web/API/SVGUnitTypes
=> Add compat data for SVGUnitTypes

api/SVGVKernElement.json
https://developer.mozilla.org/en-US/docs/Web/API/SVGVKernElement
=> Add compat data for SVGVKernElement

api/Comment.json
I missed this when reviewing. This is more consistent with the rest.
=> Correct Comment constructor data

api/SVGViewElement.json
https://developer.mozilla.org/en-US/docs/Web/API/SVGViewElement
=> Add compat data for SVGViewElement

api/SVGStyleElement.json
https://developer.mozilla.org/en-US/docs/Web/API/SVGStyleElement
=> Add compat data for SVGStyleElement

api/SVGAnimationElement.json
https://developer.mozilla.org/en-US/docs/Web/API/SVGAnimationElement
=> Add compat data for SVGAnimationElement

api/HTMLFormControlsCollection.json
[https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormControlsCollection](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormControlsCollection)
=> adding compat data for api.HTMLFormControlsCollection

api/DOMError.json
https://developer.mozilla.org/en-US/docs/Web/API/DOMError
=> Add compat data for DOMError

css/at-rules/font-face.json
In addition it updates Chrome and Opera to match the versions from font-variation-settings property.
=> Correct Samsung Internet font-variation-settings,

README.md
Link to https://github.com/connorshea/mdn-compat-data-explorer from the "Projects using the data" section.
=> Add Browser Compatibility Data Explorer to README

browsers/uc_chinese_android.json
To match filename. This was just a copy+paste error.
=> Rename the browser name in uc_chinese_android.json

browsers/edge.json, browsers/edge_mobile.json
#1966
Updated the browser compat data to reflect the Edge 17 release
=> MS Edge 17 release

api/ParentNode.json
Hi all,
append() function has been added to Edge 17 which has been released two days ago.
Cheers
midzer
=> enable append() for edge browser

api/NodeIterator.json, api/Notification.json
Adding a few updates for the Edge release (Windows 10 April 2018 Update) that shipped this week. A couple more PRs from others on my team to follow...
=> EdgeHTML 17 updates (part 1)

api/OES_vertex_array_object.json, api/PerformanceResourceTiming.json, api/SVGElement.json, api/SourceBuffer.json, api/URL.json, api/URLSearchParams.json, api/WEBGL_color_buffer_float.json, api/WEBGL_draw_buffers.json, api/WEBGL_lose_context.json, api/WebGLVertexArrayObjectOES.json, api/WorkerGlobalScope.json, webextensions/api/extension.json, webextensions/api/notifications.json, webextensions/api/tabs.json, webextensions/manifest/incognito.json
A few more APIs from the Edge release (Windows 10 April 2018 Update).
=> EdgeHTML 17 updates (part 2)

api/HTMLScriptElement.json
Oversight in https://github.com/mdn/browser-compat-data/pull/1667
=> JS modules are enabled in Fx60

webextensions/api/sidebarAction.json
=> Firefox 61 allows a windowId parameter in sidebarAction methods

css/properties/font-optical-sizing.json
See https://bugzilla.mozilla.org/show_bug.cgi?id=1435692 for implementation bug
=> add font-optical-sizing property

api/HTMLIFrameElement.json
=> Add HTMLIFrame element

api/Range.json
https://developer.mozilla.org/en-US/docs/Web/API/Range
=> Add compat data for Range (Element)

webextensions/api/browserSettings.json
Firefox 61 exposes this pref: https://bugzilla.mozilla.org/show_bug.cgi?id=1432645
No docs page yet.
=> Add browserSettings.openUrlbarResultsInNewTabs

api/FormData.json
This improves a few consistency things that I missed while reviewing PR #1487:
- descriptions for methods (not strictly required, but nice to have)
- "workers" consistency
I'll get better at this, I promise. 😄
=> Style changes for FormData data

browsers/firefox.json, browsers/firefox_android.json
Firefox released version 60!
https://developer.mozilla.org/en-US/Firefox/Releases/60
=> Update firefox version

webextensions/api/tabs.json
This is an attempt to capture this: https://bugzilla.mozilla.org/show_bug.cgi?id=1445316#c52
@Loirooriol , please let me know if this works for you.
=> Notes for tabs.query support details

mathml/elements/mtable.json
https://developer.mozilla.org/en-US/docs/Web/MathML/Element/mtable
=> Add compat data for mtable (MathML)

mathml/elements/mtd.json
https://developer.mozilla.org/en-US/docs/Web/MathML/Element/mtd
=> Add compat data for mtd (MathML)

mathml/elements/mtr.json
https://developer.mozilla.org/en-US/docs/Web/MathML/Element/mtr
=> Add compat data for mtr (MathML)

mathml/elements/maction.json
https://developer.mozilla.org/en-US/docs/Web/MathML/Element/maction
=> Add compat data for maction (MathML)

api/SpeechSynthesis.json
https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesis
=> Add compat data for SpeechSynthesis

api/SpeechGrammarList.json
https://developer.mozilla.org/en-US/docs/Web/API/SpeechGrammarList
=> Add compat data for SpeechGrammarList

api/SpeechRecognitionAlternative.json
https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognitionAlternative
=> Add compat data for SpeechRecognitionAlternative

api/SpeechRecognitionError.json
https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognitionError
=> Add compat data for SpeechRecognitionError

api/SpeechRecognitionEvent.json
https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognitionEvent
=> Add compat data for SpeechRecognitionEvent

api/SpeechRecognitionResult.json
https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognitionResult
=> Add compat data for SpeechRecognitionResult

api/SpeechRecognitionResultList.json
https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognitionResultList
=> Add compat data for SpeechRecognitionResultList

api/SpeechRecognition.json
https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognition
Note: many of these tables are the same.
=> Add compat data for SpeechRecognition

mathml/elements/merror.json
https://developer.mozilla.org/en-US/docs/Web/MathML/Element/merror
=> Add compat data for merror (MathML)

mathml/elements/merror.json, mathml/elements/mfrac.json
https://developer.mozilla.org/en-US/docs/Web/MathML/Element/mfrac
=> Add compat data for mfrac (MathML)

mathml/elements/mglyph.json
https://developer.mozilla.org/en-US/docs/Web/MathML/Element/mglyph
=> Add compat data for mglyph (MathML)

mathml/elements/mi.json
https://developer.mozilla.org/en-US/docs/Web/MathML/Element/mi
=> Add compat data for mi (MathML)

api/Window.json
[Window Methods](https://developer.mozilla.org/en-US/docs/Web/API/Window#Methods)
Done
=> Add compat data for Window Methods g to z

mathml/elements/mmultiscripts.json
https://developer.mozilla.org/en-US/docs/Web/MathML/Element/mmultiscripts
=> Add compat data for mmultiscripts (MathML)

mathml/elements/mo.json
https://developer.mozilla.org/en-US/docs/Web/MathML/Element/mo
=> Add compat data for mo (MathML)

mathml/elements/mover.json
https://developer.mozilla.org/en-US/docs/Web/MathML/Element/mover
=> Add compat data for mover (MathML)

mathml/elements/mphantom.json
https://developer.mozilla.org/en-US/docs/Web/MathML/Element/mphantom
=> Add compat data for mphantom (MathML)

mathml/elements/mroot.json
https://developer.mozilla.org/en-US/docs/Web/MathML/Element/mroot
=> Add compat data for mroot (MathML)

mathml/elements/mrow.json
https://developer.mozilla.org/en-US/docs/Web/MathML/Element/mrow
=> Add compat data for mrow (MathML)

mathml/elements/ms.json
https://developer.mozilla.org/en-US/docs/Web/MathML/Element/ms
=> Add compat data for ms (MathML)

mathml/elements/mspace.json
https://developer.mozilla.org/en-US/docs/Web/MathML/Element/mspace
=> Add compat data for mspace (MathML)

mathml/elements/msqrt.json
https://developer.mozilla.org/en-US/docs/Web/MathML/Element/msqrt
=> Add compat data for msqrt (MathML)

mathml/elements/msub.json
https://developer.mozilla.org/en-US/docs/Web/MathML/Element/msub
=> Add compat data for msub (MathML)

mathml/elements/msubsup.json
https://developer.mozilla.org/en-US/docs/Web/MathML/Element/msubsup
=> Add compat data for msubsup (MathML)

mathml/elements/mtext.json
https://developer.mozilla.org/en-US/docs/Web/MathML/Element/mtext
=> Add compat data for mtext (MathML)

mathml/elements/msup.json
https://developer.mozilla.org/en-US/docs/Web/MathML/Element/msup
=> Add compat data for msup (MathML)

api/SpeechSynthesis.json, api/SpeechSynthesisErrorEvent.json, api/SpeechSynthesisEvent.json, api/SpeechSynthesisUtterance.json, api/SpeechSynthesisVoice.json
See
https://bugzilla.mozilla.org/show_bug.cgi?id=1184142
https://bugzilla.mozilla.org/show_bug.cgi?id=1463496
=> Update SpeechSynthesis data for Firefox Android

api/Window.json
[Window Properties](https://developer.mozilla.org/en-US/docs/Web/API/Window#Properties)
Done
=> Add compat data for Window Properties g to z

webextensions/manifest/page_action.json
- https://groups.google.com/a/chromium.org/d/msg/chromium-extensions/7As9MKhav5E/dNiZDoSCCQAJ
=> Chrome 49 and newer displays page actions on the toolbar

browsers/chrome.json
Update based on the following :)
https://www.chromestatus.com/features/schedule
=> update to chrome 67

api/ExtendableEvent.json
Microsoft Edge 17 now supports extendable events and waitUntil
=> Add comapt data for Edge

api/Credential.json
https://developer.mozilla.org/en-US/docs/Web/API/Credential/name
^^ this also needs to be added to the root article
https://developer.mozilla.org/en-US/docs/Web/API/Credential
=> Edit Credential with Samsung & .name

api/DeviceRotationRate.json
[DeviceRotationRate](https://developer.mozilla.org/en-US/docs/Web/API/DeviceRotationRate)
=> Add compat data for api.DeviceRotationRate

api/DeviceProximityEvent.json
[DeviceProximityEvent](https://developer.mozilla.org/en-US/docs/Web/API/DeviceProximityEvent)
=> Add compat data for api.DeviceProximityEvent

api/DeviceMotionEvent.json
[DeviceMotionEvent](https://developer.mozilla.org/en-US/docs/Web/API/DeviceMotionEvent)
=> Add compat data for api.DeviceMotionEvent

api/DeviceLightEvent.json
[DeviceLightEvent](https://developer.mozilla.org/en-US/docs/Web/API/DeviceLightEvent)
=> Add compat data for api.DeviceLightEvent

api/BeforeInstallPromptEvent.json
[BeforeInstallPromptEvent](https://developer.mozilla.org/en-US/docs/Web/API/BeforeInstallPromptEvent)
=> Add compat data for api.BeforeInstallPromptEvent
