css/properties/text-underline-position.json

This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `from-font` member of the `text-underline-position` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.4.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/text-underline-position/from-font

Update Safari data for css.properties.text-underline-position.from-font

---

css/properties/mask-origin.json

This PR updates and corrects version values for Firefox and Firefox Android for the `mask-origin` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.4.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/mask-origin

Update Firefox data for mask-origin CSS property

---

docs/data-guidelines/api.md

This PR adds a guideline on what to do regarding namespaces in IDL.

Add guideline for namespace documentation

---

api/SVGImageElement.json
svg/elements/image.json

The `decoding` attribute has been supported for quite some time, for SVG and HTML images. I noticed that we were missing the `decoding` attribute from the SVG `<image>` element. This PR adds that.

Add decoding attribute to SVG <image>

---

css/properties/font-style.json

This PR updates and corrects version values for Chrome and Safari for the `oblique-angle` member of the `font-style` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.4.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/font-style/oblique-angle

Update Chrome/Safari data for css.properties.font-style.oblique-angle

---

api/XRSession.json

This PR updates and corrects version values for Microsoft Edge for the `enabledFeatures` member of the `XRSession` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.4.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/XRSession/enabledFeatures

Update Edge data for api.XRSession.enabledFeatures

---

scripts/release/mirror.ts

This PR fixes an issue with mirroring a ranged value from Safari to Safari iOS.  The mirroring script was programmed to handle ranges like a special case, and when we increased the number of ranged values available, this code never got updated.

Fix mirroring ranges from Safari to Safari iOS

---

api/ImageBitmapRenderingContext.json

This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `ImageBitmapRenderingContext` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.4.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/ImageBitmapRenderingContext
Additional Notes: This also synchronizes data with api.HTMLCanvasElement.getContext.bitmaprenderer_context.

Update Safari data for ImageBitmapRenderingContext API

---

api/Response.json

This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `Response.body_parameter_optional` member of the `Response` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.4.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/Response/Response/body_parameter_optional

Update Safari data for api.Response.Response.body_parameter_optional

---

css/properties/text-justify.json

This PR updates and corrects version values for Microsoft Edge for the `text-justify` CSS property. This mirrors the data from Chrome.

Update Edge data for text-justify CSS property

---

css/properties/text-orientation.json

This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `sideways` member of the `text-orientation` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.4.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/text-orientation/sideways

Update Chromium data for css.properties.text-orientation.sideways

---

html/manifest/shortcuts.json

Compatibility data for `shortcuts` property for app manifests seems to have been unintentionally removed in #18427. This change readds the file, along with the update that Chrome [now supports](https://chromestatus.com/feature/5706099464339456) shortcuts on non-Windows platforms after version 96.
Fixes #18829

Add back manifest shortcuts compat data

---

css/at-rules/media.json

The [scripting](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/scripting) media feature is currently supported only in [Firefox](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/scripting#browser_compatibility). This PR updates the value of `experimental` key.
Content PR: https://github.com/mdn/content/pull/27192

fix: Update experimental value for media feature `scripting`

---

html/global_attributes.json

This PR removes the three non-standard and unsupported `contenteditable` attribute values.  These may have been supported at one point, but they are not supported in modern browser versions, nor are they defined in the specification.

Remove non-standard, unsupported contenteditable types

---

api/InstallEvent.json

This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `InstallEvent` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.4.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/InstallEvent

Update Safari data for InstallEvent API

---

api/Event.json

This PR updates and corrects version values for Firefox and Firefox Android for the `returnValue` member of the `Event` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.4.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/Event/returnValue

Update Firefox data for api.Event.returnValue

---

html/elements/iframe.json

This PR updates and corrects version values for all browsers for the `sandbox` member of the `iframe` HTML element. The data comes from manual testing, running test code through BrowserStack, SauceLabs and custom VMs.
Test Code:
```html
<!DOCTYPE html>
<html>
<head>
<style id="persistent-style">
/* Persistent styling */
body {
background-color: black;
color: white;
margin: 0;
padding: 0;
}
canvas {
background-color: white;
}
#test {
min-height: 100vh;
}
</style>
<style id="test-style">
.true {
color: lime;
}
.false {
color: red;
}
</style>
</head>
<body>
<div id="test">
</div>
<script>
var el = document.createElement('iframe');
var output = document.getElementById('test');
function getResult(name) {
var supported = null;
if (el.sandbox instanceof DOMTokenList && 'supports' in el.sandbox) …
```

Update all browsers data for html.elements.iframe.sandbox

---

api/TransitionEvent.json

This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `TransitionEvent` member of the `TransitionEvent` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.4.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/TransitionEvent/TransitionEvent

Update Safari data for api.TransitionEvent.TransitionEvent

---

css/properties/text-decoration.json

This PR updates and corrects version values for Chrome and Safari for the `blink` member of the `text-decoration` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.4.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/text-decoration/blink

Remove css.properties.text-decoration.blink

---

api/IDBObjectStore.json

This PR updates and corrects version values for Firefox and Firefox Android for the `openKeyCursor` member of the `IDBObjectStore` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.4.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/IDBObjectStore/openKeyCursor
Additional Notes: The indicated flag is required for _prior_ Firefox versions, not Firefox 44 and newer.

Update Firefox data for api.IDBObjectStore.openKeyCursor

---

api/ScreenOrientation.json

This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `ScreenOrientation` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.4.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/ScreenOrientation

Update Safari data for ScreenOrientation API

---

javascript/builtins/Array.json

FF115 ships support for `Array.fromAsync()` in https://bugzilla.mozilla.org/show_bug.cgi?id=1795816
Since Safari has this too, it is no longer experimental. 
Other docs work can be tracked in https://github.com/mdn/content/issues/22145
FYI @queengooborg 
**WARNING: Still at stage 3 - does that change our rule for marking as experimental?**

FF115 Array.fromAsync() supported

---

api/XRFrame.json
api/XRHand.json
api/XRInputSource.json
api/XRJointPose.json
api/XRJointSpace.json
api/XRSession.json

This PR updates and corrects version values for Microsoft Edge for the `XR*` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.2.2).
Tests Used:
https://mdn-bcd-collector.gooborg.com/tests/api/XRFrame
https://mdn-bcd-collector.gooborg.com/tests/api/XRHand
https://mdn-bcd-collector.gooborg.com/tests/api/XRInputSource
https://mdn-bcd-collector.gooborg.com/tests/api/XRJointPose
https://mdn-bcd-collector.gooborg.com/tests/api/XRJointSpace
https://mdn-bcd-collector.gooborg.com/tests/api/XRSession

Update Edge data for XR* API

---

css/properties/grid-template-columns.json
css/properties/grid-template-rows.json

A patch has landed in the Blink source that enables the subgrid functionality if experimental features are turned on.
This makes the feature available under the 'experimental web platform features' flag in Chrome et al.
I've also changed the note to the new `impl_url` format.
Corresponding commit: https://chromium.googlesource.com/chromium/src.git/+/f7d47ed18bd6ed25c2b07c7919a32c67c1a7b73f
N/A

Blink subgrid support graduated from 'test' to 'experimental'

---

webextensions/api/storage.json

Update to note that support for `session.storage` was provided in Firefox 115. See  [Bug 1823713](https://bugzilla.mozilla.org/show_bug.cgi?id=1823713) Implement storage.session in extension process.

Details of support for sessions.storage

---

css/types/image.json

It supported it from the moment `radial-gradient` was unprefixed, not sure why it was marked as not supported. In fact, the relevant examples on the MDN page with `at` work fine in Safari.
This is the bug where support was added: https://bugs.webkit.org/show_bug.cgi?id=67166

Fix Safari support for `at` in `radial-gradient`

---

css/properties/background-image.json

This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `image-set` member of the `background-image` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.3.2).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/background-image/image-set

Update Safari data for css.properties.background-image.image-set

---

api/Response.json

FF115 adds support for [`Response: json()` static method](https://developer.mozilla.org/en-US/docs/Web/API/Response/json_static) in https://bugzilla.mozilla.org/show_bug.cgi?id=1758943
This adds a BCD entry for the whole method. I use this WPT test to check the browser versions: http://wpt.live/fetch/api/response/response-static-json.any.html
For deno I found info in the release notes: https://deno.com/blog/v1.22#new-responsejson-static-method
This is part of docs for https://github.com/mdn/content/issues/27169

FF115 Response.json() static supported

---

api/VideoPlaybackQuality.json

This PR updates and corrects version values for Microsoft Edge for the `totalFrameDelay` member of the `VideoPlaybackQuality` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.4.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/VideoPlaybackQuality/totalFrameDelay

Update Edge data for api.VideoPlaybackQuality.totalFrameDelay

---

api/HTMLCanvasElement.json

This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `HTMLCanvasElement` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.4.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/HTMLCanvasElement

Update Safari data for HTMLCanvasElement API

---

http/headers/Access-Control-Allow-Headers.json

The spec states that if [`Access-Control-Allow-Headers`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Headers) specifies a wildcard, that does not automatically include the `Authorization` header. Browsers were wildcarding the `Authorization` header but are not preparing to deprecate that behaviour.
FF115 does so behind a preference in https://bugzilla.mozilla.org/show_bug.cgi?id=1687364. Chrome was planning to to this in M116 but is waiting on others to catch up: see https://chromestatus.com/feature/5742041264816128 and https://groups.google.com/a/chromium.org/g/blink-dev/c/yXxYCo3ytQU/m/Z6woo8enAgAJ
This adds the FF information. 
Note, I have not been able to test this because the relevant WPT live test appears to fail this for other reasons: …

FF115 Access-Control-Allow-Headers - wildcard not include Authorization header

---

api/SharedWorker.json
api/Worker.json
api/WorkerGlobalScope.json

Safari 16.0+ has enabled strict MIME type checks for all worker scripts + their imports.
[Test results for MIME checks on `Worker` and `SharedWorker` scripts.](https://wpt.fyi/results/workers/Worker_script_mimetype.htm?label=master&product=safari-16.0%20%2817614.1.25.9.10%29&product=safari-15.6.1%20%2817613.3.9.1.16%29)
[Test results for MIME checks on imported scripts in `Worker`.](https://wpt.fyi/results/workers/importscripts_mime.any.worker.html?label=master&product=safari-16.0%20%2817614.1.25.9.10%29&product=safari-15.6.1%20%2817613.3.9.1.16%29)
[Test results for MIME checks on imported scripts in `SharedWorker`.](https://wpt.fyi/results/workers/importscripts_mime.any.sharedworker.html?label=master&product=safari-16.0%20%2817614.1.25.9.10%29&product=safari-15.6.1%20%2817613.3.9.1.16%29 …

Safari enabled strict mime checks for workers

---

javascript/builtins/RegExp.json

This adds support data for the new `unicodeSets` regex flag :)
The link to the spec will work properly when https://github.com/tc39/ecma262/pull/2418 is merged.
I manually tested all major browsers, and checked that my results were consistent with the following documentation. I have not run any advanced tests to ensure that the browsers follow the spec correctly.
Added in Chrome 112:
https://chromestatus.com/feature/5144156542861312
Added in Safari 17:
https://developer.apple.com/documentation/safari-release-notes/safari-17-release-notes
Added in Firefox 116:
https://bugzilla.mozilla.org/show_bug.cgi?id=1826574

Track support for regex unicodeSets flag

---

css/properties/grid-template-columns.json
css/properties/grid-template-rows.json
css/properties/masonry-auto-flow.json

Masonry layout is now supported and enabled by default in Safari Technology Preview
https://developer.apple.com/videos/play/wwdc2023/10121

Update masonry support on Safari TP

---

schemas/collector-report.md
schemas/collector-report.schema.json

- Add a mdn-bcd-results schema
This schema validates the reports created by `mdn-bcd-collector` and stored in `mdn-bcd-results`.
All reports in mdn-bcd-results validate without error with this schema using `ajv-cli`.
https://github.com/mdn/browser-compat-data/issues/19868
https://github.com/mdn/browser-compat-data/issues/18514

Add collector report schema

---

api/URL.json

FF, safari, node, deno all support new URL.canParse() static method. This adds a feature for the method.
- FF115: https://bugzilla.mozilla.org/show_bug.cgi?id=1823354
- Node 19.9 (closest is 20) https://nodejs.org/en/blog/release/v19.9.0
- Safari 17: https://developer.apple.com/documentation/safari-release-notes/safari-17-release-notes
- Deno 1.33 : https://deno.land/api@v1.33.0?s=URL&p=canParse
FYI @queengooborg 
Related docs work can be tracked in https://github.com/mdn/content/issues/27170

FF115 URL.canParse() static method

---

api/HTMLMediaElement.json

FF115 disables [HTMLMediaElement.mozPreservesPitch](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/preservesPitch) behind a preference by default in https://bugzilla.mozilla.org/show_bug.cgi?id=1831205.
This is in preparation for eventual removal.
Related docs work in https://github.com/mdn/content/issues/27181

FF115 HTMLMediaElement.mozPreservesPitch disabled by default

---

api/HTMLInputElement.json
api/HTMLTextAreaElement.json
html/elements/input.json
html/elements/textarea.json

Update data for the `dirname` attribute on `input` and `textarea` elements, as firefox supports this from version 116.0a1 onwards.
- `npm test` ran successfully
- Release Notes under "Developer" [116.0a1](https://www.mozilla.org/en-US/firefox/116.0a1/releasenotes/)

Update browser data for dirname on firefox

---

api/OffscreenCanvasRenderingContext2D.json

This PR updates and corrects version values for Firefox and Firefox Android for the `OffscreenCanvasRenderingContext2D` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.4.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/OffscreenCanvasRenderingContext2D

Update Firefox data for OffscreenCanvasRenderingContext2D API

---

RELEASE_NOTES.md

This PR adds a notable change regarding the `_static` suffixes to the release notes.

Add a notable change regarding the latest release

---

api/GPU.json
api/WGSLLanguageFeatures.json

Chrome 115 adds the [`WGSLLanguageFeatures`](https://gpuweb.github.io/gpuweb/#gpuwgsllanguagefeatures) feature of WebGPU. See https://chromestatus.com/feature/5149681044160512.
This includes:
* The `GPU.wgslLanguageFeatures` property
* The `WGSLLanguageFeatures` class
This PR adds BCD for these new items.

Add WGSLLanguageFeatures data

---

api/ReadableStreamDefaultController.json

This PR updates and corrects version values for Chrome and Safari for the `ReadableStreamDefaultController` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.0.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/ReadableStreamDefaultController

Update Chrome/Safari data for ReadableStreamDefaultController API

---

api/ReadableStreamDefaultReader.json

This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `ReadableStreamDefaultReader` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.0.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/ReadableStreamDefaultReader

Update Safari data for ReadableStreamDefaultReader API

---

api/Element.json

This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `animate.options_id_parameter` member of the `Element` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.0.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/Element/animate/options_id_parameter

Update Safari data for api.Element.animate.options_id_parameter

---

api/PannerNode.json

This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `PannerNode` API. This removes the prefix data from the interface, as it is only for internal naming and has no effect on accessing the interface.  (The constructor was added in Safari 14.1 when the prefix was removed, and I have confirmed neither a `webkit` or `WebKit` prefix is supported; the interface was not exposed before then.)

Update Safari data for PannerNode API

---

api/FileSystemHandle.json

The `move` method is not documented.
This method is currently supported only in Firefox. The [FileSystemHandle BCD table](https://developer.mozilla.org/en-US/docs/Web/API/FileSystemHandle#browser_compatibility) also has the icon for "Non-standard" next to `move`.
For now, removing the MDN URL from the BCD table to avoid a 404.
- In the [spec](https://wicg.github.io/file-system-access/#api-filesystemhandle) linked for `queryPermission()` and `requestPermission()` methods of the `FileSystemHandle` interface, there's no mention of `move` and `remove` methods.
- There's no spec linked on [`remove`](https://developer.mozilla.org/en-US/docs/Web/API/FileSystemHandle/remove#specifications) method page. Like `move`, this method is non-standard and experimental.

Remove mdn url for non-existent page (move method of FileSystemHandle interface)

---

api/XRSystem.json

This PR removes the alternative name data for the XRSystem API.  Because this has no constructor and is only accessed via `navigator.xr`, the underlying interface name is irrelevant.

Remove alt. name on XRSystem

---

api/InstallEvent.json

This PR removes the `activeWorker` member of the `InstallEvent` API from BCD. Per the [data guidelines](https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines/index.md#removal-of-irrelevant-features), this feature can be considered irrelevant and may be removed from BCD accordingly. Even if the current data suggests that the feature is supported, lack of support has been confirmed by the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.0.1).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/InstallEvent/activeWorker
Additional Notes: I looked through Firefox's IDL and couldn't find any evidence that this was supported any longer.

Remove api.InstallEvent.activeWorker from BCD

---

css/properties/font-variant-emoji.json

This PR updates and corrects version values for Firefox and Firefox Android for the `font-variant-emoji` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.0.1).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/font-variant-emoji
Additional Notes: This is a follow-up to #18381, which set Firefox as supported but did not include the required flag data (which Dipika later pointed out).

Update Firefox data for font-variant-emoji CSS property

---

css/properties/line-height.json

This PR removes the `-moz-block-height` member of the `line-height` CSS property from BCD. Per the [data guidelines](https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines/index.md#removal-of-irrelevant-features), this feature can be considered irrelevant and may be removed from BCD accordingly. Even if the current data suggests that the feature is supported, lack of support has been confirmed by the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.0.1).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/line-height/-moz-block-height

Remove css.properties.line-height.-moz-block-height from BCD

---

browsers/chrome.json
browsers/chrome_android.json
browsers/webview_android.json

This PR adds data for Chrome/CxA 116.
@Elchi3, can you have a look at this one? As soon as this is merged, I'll go over to https://github.com/mdn/browser-compat-data/pull/20158 and remove it from there.

Add Chrome 116

---

css/properties/image-rendering.json

This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `image-rendering` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.0.1).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/image-rendering

Update Chromium data for image-rendering CSS property

---

api/ApplicationCache.json

ApplicationCache was disabled in release in FF84 behind a preference - but I missed the ApplicationCache entry back then in https://github.com/mdn/browser-compat-data/pull/7481. In FF115 it was fully removed.
My thinking is that this should simply marked as removed in FF84. BUT, given how long ago that was, should we simply purge this whole record? Note that it is not linked on MDN.
Other docs work can be tracked in https://github.com/mdn/content/issues/27176

FF84 ApplicationCache disabled - FF115 removed

---

javascript/builtins/Array.json
javascript/builtins/TypedArray.json

FF115 supports the Array/TypedArray "change array by copy" methods in https://bugzilla.mozilla.org/show_bug.cgi?id=1811057.
This adds the relevant version to:
- Array.toReversed()
- Array.toSorted(compareFn) -> Array
- Array.toSpliced(start, deleteCount, ...items) -> Array
- Array.with(index, value)
- TypedArrays.toReversed
- TypedArrays.toSorted
- TypedArrays.with()
Related docs work can be tracked in  https://github.com/mdn/content/issues/27175

FF115 supports change array by copy methods

---

css/at-rules/page.json

I found that there was a duplicate entry for the `page` property in the `@page` at-rule data.  This, however, is unconventional to BCD and shouldn't be placed in the at-rules data.

Remove duplicate entry for page property in page at-rule

---

css/properties/text-align.json

This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `match-parent` member of the `text-align` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.0.3).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/text-align/match-parent
Additional Notes: After seeing the collector reports no support from this property, I tested it in Chrome and found that it is supported with a prefix.

Update Chromium data for css.properties.text-align.match-parent

---

css/at-rules/page.json
css/properties/page.json

This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `page` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.0.1).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/page

Update Safari data for page CSS property

---

api/Plugin.json

This PR removes the `version` member of the `Plugin` API from BCD. Per the [data guidelines](https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines/index.md#removal-of-irrelevant-features), this feature can be considered irrelevant and may be removed from BCD accordingly. Even if the current data suggests that the feature is supported, lack of support has been confirmed by the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.0.3).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/Plugin/version
Additional Notes: The collector states this property is no longer supported.

Remove api.Plugin.version from BCD

---

css/properties/width.json

This PR removes the `fill` member of the `width` CSS property from BCD. Per the [data guidelines](https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines/index.md#removal-of-irrelevant-features), this feature can be considered irrelevant and may be removed from BCD accordingly. Even if the current data suggests that the feature is supported, lack of support has been confirmed by the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.0.3).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/width/fill

Remove css.properties.width.fill from BCD

---

css/properties/text-underline-position.json

This PR removes the `auto-pos` member of the `text-underline-position` CSS property from BCD. Per the [data guidelines](https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines/index.md#removal-of-irrelevant-features), this feature can be considered irrelevant and may be removed from BCD accordingly. Even if the current data suggests that the feature is supported, lack of support has been confirmed by the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.0.3).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/text-underline-position/auto-pos

Remove css.properties.text-underline-position.auto-pos from BCD

---

api/SpeechSynthesisVoice.json

This PR updates and corrects version values for Firefox and Firefox Android for the `SpeechSynthesisVoice` API. This bug was discovered when writing tests for the mdn-bcd-collector. This adds a note mentioning this bug and recommending a solution based on https://github.com/GooborgStudios/mdn-bcd-collector/commit/365ad25c361516fc26340f3946884ff90c85f342.

Update Firefox data for SpeechSynthesisVoice API

---

api/WebTransport.json

This PR removes the `draining` member of the `WebTransport` API from BCD. Per the [data guidelines](https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines/index.md#removal-of-irrelevant-features), this feature can be considered irrelevant and may be removed from BCD accordingly. Even if the current data suggests that the feature is supported, lack of support has been confirmed by the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.0.3).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/WebTransport/draining
Note: the collector shows that Firefox does not actually support this property.

Remove api.WebTransport.draining from BCD

---

api/RTCRtpSender.json

This PR updates and corrects version values for Firefox and Firefox Android for the `transport` member of the `RTCRtpSender` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.0.3).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/RTCRtpSender/transport
Additional Notes: The original data comes from the wiki migration, so I have little trust in it.

Update Firefox data for api.RTCRtpSender.transport

---

api/RTCStatsReport.json

This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `RTCStatsReport` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.0.3).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/RTCStatsReport

Update Chromium data for RTCStatsReport API

---

api/OVR_multiview2.json

This PR updates and corrects version values for Firefox and Firefox Android for the `OVR_multiview2` API. This marks Firefox as partial_implementation as the interface is only supported on certain OSes.
Additional Notes: Additionally, this updates the Chrome note to specify Linux isn't supported either.

Update Firefox data for OVR_multiview2 API

---

api/WEBGL_compressed_texture_etc.json
api/WEBGL_compressed_texture_etc1.json

This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `WEBGL_compressed_texture_etc` API. The data comes from a commit in the browser's source code, mapped to a version number using available tooling or via the commit timestamp.
Commit: https://github.com/WebKit/WebKit/commit/e992b6b77baf88e2a99248cb091cefcf12d9b7f1

Update Safari data for WEBGL_compressed_texture_etc API

---

api/HTMLCanvasElement.json

Based on results from the mdn-bcd-collector project and manual testing, it was determined that Microsoft Edge supported the `desynchronized` parameter when creating a rendering context since Edge 79.

Edge supports desynchronized parameter since first Chromium

---

css/properties/list-style-type.json

This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `ethiopic-halehame-am` member of the `list-style-type` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.0.3).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/list-style-type/ethiopic-halehame-am

Update Safari data for css.properties.list-style-type.ethiopic-halehame-am

---

api/WEBGL_compressed_texture_astc.json

This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `WEBGL_compressed_texture_astc` API. The data comes from a commit in the browser's source code, mapped to a version number using available tooling or via the commit timestamp.
Commit: https://github.com/WebKit/WebKit/commit/6d5219cebd6cf31fb1761f97edba5bbf265d0935

Update Safari data for WEBGL_compressed_texture_astc API

---

api/SpeechSynthesisEvent.json

This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `charLength` member of the `SpeechSynthesisEvent` API. The data comes from a commit in the browser's source code, mapped to a version number using available tooling or via the commit timestamp.
Commit: https://github.com/WebKit/WebKit/commit/c8a7a8619b280e32eff4e077992d5a7c67e31a5c

Update Safari data for api.SpeechSynthesisEvent.charLength

---

api/Touch.json
api/TouchList.json

This PR updates and corrects version values for Firefox and Firefox Android for the `Touch` API. During testing, it was found that this interface is only available if there is hardware touch support (as per `dom.w3c_touch_events.enabled` being set to `2` (auto-detect) in Windows and Linux).

Update Firefox data for Touch API

---

css/properties/appearance.json

This PR updates the list of values for the `<compat-auto>` type for the `appearance` CSS property, following #20203.

Update list of values for css.properties.appearance.compat-auto

---

api/TouchList.json

This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `TouchList` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.0.3).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/TouchList
Additional Notes: (Discussed during a 1-on-1 call with Florian.  The original data comes from Apple's developer docs which has incorrect version numbers.  Also, the Touch interface itself isn't supported in Safari Desktop.

Update Safari data for TouchList API

---

api/RTCStatsReport.json

This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `type_codec.sdpFmtpLine` member of the `RTCStatsReport` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.0.3).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/RTCStatsReport/type_codec/sdpFmtpLine

Update Safari data for api.RTCStatsReport.type_codec.sdpFmtpLine

---

api/CacheStorage.json
api/_globals/caches.json

This PR updates and corrects version value for Deno for `caches` object and `CacheStorage` interface. The data comes from the [Deno Runtime APIs document][deno-doc].
I couldn't make the test on Deno `1.26.0`. But I've tested the `caches` object and methods from `CacheStorage` interface in Deno `1.34.4` and can confirm it does work.
- [Deno Runtime APIs document][deno-doc]
None
[deno-doc]: https://deno.land/api@v1.26.0?s=Cache

Update deno data for Cache API

---

css/properties/display.json

Add support for multi-keyword syntax on CSS `display` property in Chrome 115. 
[Chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=995106)
[Announcement in Chrome Dev Blog](https://developer.chrome.com/blog/chrome-115-beta/)

CSS display property multi-keyword support in Chrome 115

---

css/properties/background-clip.json

This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `background-clip` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.3.2).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/background-clip

Update Safari data for background-clip CSS property

---

css/properties/align-content.json
css/properties/align-items.json
css/properties/align-self.json
css/properties/justify-content.json

Chrome recently added support for the `safe`/`unsafe` alignment keywords in flexbox layouts. It's currently in Chrome Beta, or version 115.
`npm run test` passed 👍 
* Chromium bug: https://bugs.chromium.org/p/chromium/issues/detail?id=1121601
* WPT results for `align-content`, `justify-content`, and `align-items` (pictured above): https://wpt.fyi/results/css/css-flexbox/flexbox-safe-overflow-position-001.html
* WPT results for `align-self`: https://wpt.fyi/results/css/css-align/self-alignment/self-align-safe-unsafe-flex-001.html
None that I could find

Chrome support for safe/unsafe alignment in flexbox

---

http/headers/Sec-Purpose.json

FF115 adds support for `Sec-Purpose` header in https://bugzilla.mozilla.org/show_bug.cgi?id=1836328.
The other browsers are not supported according to https://wpt.fyi/results/preload/prefetch-headers.https.html?label=experimental&label=master&aligned in Chrome 116, Safari 172. 
`Sec-Purpose: prefetch` is the new way to indicate a request is a prefetch request. In Firefox it replaces `X-moz: prefetch` and in Chromium it will replace `Purpose: prefetch`, though it has not been implemented yet.
I want to avoid adding data for  `X-moz: prefetch`  and `Purpose: prefetch` as both are effectively non-standard, and it is difficult enough to capture what is happening with `Sec-Purpose`. 
Related docs work can be tracked in https://github.com/mdn/content/issues/27171

FF115 Add Sec-Purpose HTTP header

---

api/RTCPeerConnection.json

This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `RTCPeerConnection.configuration_peerIdentity_parameter` member of the `RTCPeerConnection` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.0.5).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/RTCPeerConnection/RTCPeerConnection/configuration_peerIdentity_parameter
Additional Notes: In the IDL in Chrome, the parameter is commented out with TODO: https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/modules/peerconnection/rtc_configuration.idl;l=39; …

Update Chromium data for api.RTCPeerConnection.RTCPeerConnection.configuration_peerIdentity_parameter

---

api/RTCPeerConnection.json

This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `RTCPeerConnection.configuration_peerIdentity_parameter` member of the `RTCPeerConnection` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.0.5).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/RTCPeerConnection/RTCPeerConnection/configuration_peerIdentity_parameter
Additional Notes: In WebKit's source code, the property is commented out as a TODO: https://github.com/WebKit/WebKit/blob/7cc365707c03970445cec23ec9a2c2be6a80eedd/Source/WebCore/Modules/mediastream/RTCConfiguration.idl#L63

Update Safari data for api.RTCPeerConnection.RTCPeerConnection.configuration_peerIdentity_parameter

---

api/RTCPeerConnection.json

This PR updates and corrects version values for Firefox and Firefox Android for the `createDTMFSender` member of the `RTCPeerConnection` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.0.5).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/RTCPeerConnection/createDTMFSender
Additional Notes: Searching through the source code reveals that this property is not implemented.

Update Firefox data for api.RTCPeerConnection.createDTMFSender

---

css/properties/list-style-type.json

This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `upper-greek` member of the `list-style-type` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.0.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/list-style-type/upper-greek

Update Chromium data for css.properties.list-style-type.upper-greek

---

browsers/nodejs.json
docs/testing.md

This PR fixes a few URLs that still refer to the `master` branch even though the repositories have already renamed them to `main`.  Note: the ESLint governance doc is the only URL referencing `master` left, but that is because the repository has been archived.

Fix URLs that point to old "master" branch

---

README.md
index.ts
schemas/compat-data.schema.json
scripts/fix/index.ts
scripts/generate-types.ts
scripts/migrations/002-remove-webview-flags.ts
scripts/migrations/007-experimental-false.ts
scripts/migrations/010-set-oculus-to-mirror.ts
scripts/remove-redundant-flags.ts
scripts/traverse.ts
test/lint.ts
test/linter/test-obsolete.ts
test/linter/test-spec-urls.ts
test/linter/test-versions.ts
utils/walk.test.ts
webassembly/BigInt-to-i64-integration.json
webassembly/bulk-memory-operations.json
webassembly/exception-handling.json
webassembly/extended-constant-expressions.json
webassembly/fixed-width-SIMD.json
webassembly/multi-value.json
webassembly/mutable-globals.json
webassembly/non-trapping-float-to-int-conversions.json
webassembly/reference-types.json
webassembly/sign-extension-operations.json
webassembly/tail-calls.json
webassembly/threads-and-atomics.json

This PR adds a brand new category for WebAssembly features -- that is, features within the WebAssembly code itself rather than just the JavaScript API.  The results were collected by the mdn-bcd-collector project (v10.0.0).
CC @MendyBerger

Add WebAssembly features as a new category

---

api/Request.json

This PR removes the `Request.navigate_mode` member of the `Request` API from BCD. No browser supports construction of a request when `mode` is set to `navigate`.
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/Request/Request/navigate_mode

Remove api.Request.Request.navigate_mode from BCD

---

scripts/release/index.ts

This PR fixes the release script to stage all files _after_ the user makes modifications to `RELEASE_NOTES.md`, to ensure that the modifications are included in the PR.

Stage files during release script after user makes modifications

---

css/properties/list-style-type.json

This PR updates and corrects version values for Firefox and Firefox Android for the `upper-greek` member of the `list-style-type` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.0.5).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/list-style-type/upper-greek
Additional Notes: There are very few results in SearchFox for `upper-greek`: https://searchfox.org/mozilla-central/search?q=upper-greek&path=&case=false&regexp=false

Update Firefox data for css.properties.list-style-type.upper-greek

---

api/SpeechRecognitionErrorEvent.json

This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `SpeechRecognitionErrorEvent` API. This sets Chromium derivatives to mirror from upstream.

Update Chromium data for SpeechRecognitionErrorEvent API

---

api/Element.json

This PR updates and corrects version values for Chrome and Safari for the `animate.options_composite_parameter` member of the `Element` API. This mirrors the values from api.KeyframeEffect.composite

Update Chrome/Safari data for api.Element.animate.options_composite_parameter

---

api/PushManager.json

This PR updates and corrects version values for Firefox and Firefox Android for the `supportedContentEncodings_static` member of the `PushManager` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.0.5).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/PushManager/supportedContentEncodings_static

Update Firefox data for api.PushManager.supportedContentEncodings_static

---

api/PushSubscription.json

This PR updates and corrects version values for Microsoft Edge for the `subscriptionId` member of the `PushSubscription` API. This is honestly a guess, but it seems likely that this feature was supported since the entire interface was supported.

Update Edge data for api.PushSubscription.subscriptionId

---

css/properties/caption-side.json

Fixes https://github.com/mdn/content/issues/22271
As discussed on the issue page, we need both the spec URLs to cover all the values.

fix: add a specs URL to css.properties.caption-side to cover all values

---

webextensions/manifest/optional_permissions.json
webextensions/manifest/permissions.json

Addresses the documentation needs of [Bug 1606862](https://bugzilla.mozilla.org/show_bug.cgi?id=1606862) Make devtools an optional permission.
No reference found to this permission in the Chrome documentation e.g. https://developer.chrome.com/docs/extensions/mv3/declare_permissions/#permissions or https://developer.chrome.com/docs/extensions/reference/devtools_inspectedWindow/
Confirmed as included in Safari on this page: https://developer.apple.com/documentation/safariservices/safari_web_extensions/adding_a_web_development_tool_to_safari_web_inspector#3966899

devtools as optional permission

---

javascript/builtins/String.json

Nightly provides the pref `javascript.options.experimental.well_formed_unicode_strings` set to false (disabled) by default.
This allows for using the following methods:
- [`String.prototype.isWellFormed()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/isWellFormed)
- [`String.prototype.toWellFormed()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/toWellFormed)
__Bugzilla:__
- [BUG-1825005](https://bugzilla.mozilla.org/show_bug.cgi?id=1825005)

relnote(Fx115): isWellFormed and toWellFormed behind pref in 115

---

javascript/builtins/ArrayBuffer.json
javascript/builtins/SharedArrayBuffer.json

Update ArrayBuffer data to reflect Deno's support for `resize()` method, `resizable` property, etc.
https://deno.com/blog/v1.33
Closes #20208

Update: Deno supports resizable ArrayBuffers since 1.33

---

browsers/chrome.json
browsers/chrome_android.json
browsers/edge.json
browsers/webview_android.json

See https://chromiumdash.appspot.com/schedule and https://learn.microsoft.com/en-us/deployedge/microsoft-edge-release-schedule
For the dates, I'm using "Stable Release" and not "Early Stable Release".

Update Chromium-based browser release data

---

html/elements/link.json

FF115 supports `<link>` elements with [`rel="modulepreload"`](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel/modulepreload) in https://bugzilla.mozilla.org/show_bug.cgi?id=1425310
Other docs work for this can be tracked in https://github.com/mdn/content/issues/27177

FF115 link element supports rel=modulepreload

---

api/CSS.json
api/CSSMathClamp.json
api/MathMLElement.json

These should all be using the unversioned URLs

Fix css-typed-om spec URLs

---

api/Element.json
api/ScrollTimeline.json
api/ViewTimeline.json
css/at-rules/keyframes.json
css/properties/animation-range-end.json
css/properties/animation-range-start.json
css/properties/animation-range.json
css/properties/animation-timeline.json
css/properties/view-timeline-axis.json
css/properties/view-timeline-inset.json
css/properties/view-timeline-name.json
css/properties/view-timeline.json
css/types/line-style.json
css/types/overflow.json

These should all now (once again) be using the drafts.csswg.org URLs

Fix various CSS spec URLs

---

api/GPU.json
api/GPURenderBundleEncoder.json
api/GPURenderPassEncoder.json

There are a few changes in Chrome's WebGPU implementation between 113 and 115. See @beaufortfrancois 's update articles at https://developer.chrome.com/tags/new-in-webgpu/. The ones that need compat data additions, IMO, are:
- https://developer.chrome.com/blog/new-in-webgpu-115/#unset-vertex-buffer
- https://developer.chrome.com/blog/new-in-webgpu-115/#get-discrete-gpu-by-default-on-ac-power
I'll make changes in the docs for these as well.

New WebGPU support items Chrome 113-115

---

webextensions/api/declarativeNetRequest.json

I've added browser compatibility data for isUrlFilterCaseSensitive
Version data was taken from this comment
https://github.com/mdn/content/pull/26908#pullrequestreview-1468579425
Chrome version information was taken from this message
https://groups.google.com/a/chromium.org/g/chromium-extensions/c/TXYUmvDHUlw/m/9JdxXG2cAgAJ
This PR is related to this PR https://github.com/mdn/content/pull/26908

Add BCD for isUrlFilterCaseSensitive field

---

css/selectors/view-transition-image-pair.json

Flubbed this one in an earlier commit. This cleans it up.

Fix view-transition-image-pair.json spec URLs

---

css/properties/animation-timeline.json

Added the version added to firefox for `view()` and the associated feature flag
- [bugzilla 1808410](https://bugzilla.mozilla.org/show_bug.cgi?id=1808410)
- Associated MDN Content issues: [26685](https://github.com/mdn/content/issues/26685) & [26687](https://github.com/mdn/content/issues/26687)
- Associated MDN Content PR - [27075](https://github.com/mdn/content/pull/27075)

added the release and flag for view() in firefox

---

api/URL.json

Fix the description of `URL.canParse()` from "`canParse_static`" to "`canParse()` static method", matching the other static methods of the `URL`.

Fix description of `URL.canParse()`

---

api/CanvasCaptureMediaStreamTrack.json

Firefox has supported this feature since v43
https://bugzilla.mozilla.org/show_bug.cgi?id=1177276

Firefox supports CanvasCaptureMediaStreamTrack

---

javascript/statements.json

Fix https://github.com/mdn/browser-compat-data/issues/20219
Putting Safari 15 because https://github.com/WebKit/WebKit/commit/2433e3b41df9c903a64aa8a017541d80ec72d888 is tagged with "releases/Apple/Safari-15-iOS-15.0" as the earliest release.

Safari supports module import syntax in service workers

---

css/types/length.json

Fix https://github.com/mdn/browser-compat-data/issues/20261
> Done in: https://trac.webkit.org/changeset/251662/webkit
> This revision was part of Safari 13.1 and later (See also GitHub's tag inclusion history [WebKit/WebKit@f158f1c](https://github.com/WebKit/WebKit/commit/f158f1c46209e61ab185d7729aa9146e322d03fb) )

Safari 13.1 supports CSS Q unit

---

test/linter/test-versions.ts

This PR fixes a bug found in https://github.com/mdn/browser-compat-data/actions/runs/5458481317/jobs/9933610824?pr=20295 where the keys of the browser object are listed off, rather than all the version numbers.

Fix message displayed when invalid browser version found

---

api/Headers.json
api/URLSearchParams.json
browsers/deno.json

Update `Headers.getSetCookie`, `URLSearchParams.delete` and `URLSearchParams.has` for Deno v1.35.
https://deno.com/blog/v1.35

Update for Deno v1.35

---

browsers/firefox.json
browsers/firefox_android.json

Firefox 115 should have `engine_version` 115. Think this was a copy/paste error

fix firefox 115 engine_version

---

browsers/firefox.json
browsers/firefox_android.json

Firefox 115 got released
Release Notes: https://www.mozilla.org/en-US/firefox/115.0/releasenotes/

release firefox 115

---

api/HTMLMediaElement.json
api/MediaDevices.json
http/headers/Feature-Policy.json
http/headers/Permissions-Policy.json

FF116 supports the audio output API in https://bugzilla.mozilla.org/show_bug.cgi?id=1498512 - by enabling `media.setsinkid.enabled` by default, except on Android. On android there is a bug which means it might not be implementable https://bugzilla.mozilla.org/show_bug.cgi?id=1473346
This finds all instances of the preference, sets the release version to match the old preview, removes preferenced version, sets firefox-android to false with a Note/bug link.
This is part of work in https://github.com/mdn/content/issues/27748

FF116 supports audio output API

---

css/properties/view-timeline-axis.json
css/properties/view-timeline.json

Updated the notes for firefox for the `view-timeline-axis` so that it shows support for `x` & `y`.
[codepen](https://codepen.io/CodeRedDigital/pen/KKGOXqQ?editors=1100) showing:
- `view-timeline-axis: y;`
- `view-timeline-axis: vertical;`
- [bugzilla 1737920](https://bugzilla.mozilla.org/show_bug.cgi?id=1737920)
- Associated MDN Content issues: [26685](https://github.com/mdn/content/issues/26685) & [26687](https://github.com/mdn/content/issues/26687)
- Associated MDN Content PR - [27075](https://github.com/mdn/content/pull/27075)

updated the view-timeline-axis values for firefox

---

api/Notification.json

This PR updates and corrects version values for Safari iOS/iPadOS for the `tag` member of the `Notification` API. The data comes from a bug in the web browser's bug tracker.
Bug: https://webkit.org/b/258922
Additional Notes: Fixes #20305.

Update Safari iOS data for api.Notification.tag

---

docs/contributing.md

This PR fixes a header within the contributing documentation.  The header talks about opening issues and pull requests, but the content is only about opening pull requests.

Fix header in documentation

---

api/CSS.json
api/CSSPropertyRule.json
css/at-rules/property.json

The pref `layout.css.properties-and-values.enabled` is set to true (enabled) on Nightly in 116. This allows for using the following APIs:
- [`CSSPropertyRule`](https://developer.mozilla.org/en-US/docs/Web/API/CSSPropertyRule)
- [`CSSPropertyRule.inherits`](https://developer.mozilla.org/en-US/docs/Web/API/CSSPropertyRule/inherits)
- [`CSSPropertyRule.initialvalue`](https://developer.mozilla.org/en-US/docs/Web/API/CSSPropertyRule/initialvalue)
- [`CSSPropertyRule.name`](https://developer.mozilla.org/en-US/docs/Web/API/CSSPropertyRule/name)
- [`CSSPropertyRule.syntax`](https://developer.mozilla.org/en-US/docs/Web/API/CSSPropertyRule/syntax)
- [`registerProperty()`](https://developer.mozilla.org/en-US/docs/Web/API/CSS/registerProperty_static)
And the following CSS syntax:
```css
@property …
```

relnote(116): CSSPropertyRule enabled in Fx nightly by default

---

api/Window.json

This PR updates and corrects version values for Firefox and Firefox Android for the `prompt` member of the `Window` API. This fixes #10994 by adding a note regarding Firefox's behavior regarding newlines.

Update Firefox data for api.Window.prompt

---

javascript/builtins/WebAssembly.json
javascript/builtins/WebAssembly/CompileError.json
javascript/builtins/WebAssembly/Exception.json
javascript/builtins/WebAssembly/Global.json
javascript/builtins/WebAssembly/Instance.json
javascript/builtins/WebAssembly/LinkError.json
javascript/builtins/WebAssembly/Memory.json
javascript/builtins/WebAssembly/Module.json
javascript/builtins/WebAssembly/RuntimeError.json
javascript/builtins/WebAssembly/Table.json
javascript/builtins/WebAssembly/Tag.json

This PR fixes the MDN URLs for the WebAssembly JavaScript API to match the URLs that you are redirected to when going to the old URLs.

Fix MDN URLs for WebAssembly JS API

---

api/HTMLDialogElement.json

Updated HTMLDialogElement.json because HTMLDialogElement.close_event is already supported in Chrome Android v37.
https://chromestatus.com/feature/5770237022568448
Fixes #20351

Add support for HTMLDialogElement.close_event in Chrome Android

---

javascript/builtins/Temporal/Now.json

This PR corrects the capitalization of `Temporal.Now` to match the capitalization defined in the spec.

Temporal.now -> Temporal.Now

---

http/headers/Content-Security-Policy.json

FF116 supports the CSP3 feature of allowing hash source expressions to match external scripts, rather than just inline scripts, in https://bugzilla.mozilla.org/show_bug.cgi?id=1409200. This adds the entry.
I've also modified the description  for the feature because "external scripts" wasn't sufficient to be able to work out what the feature is for. Even knowing what it was "probably" for I wasn't certain until I found https://chromestatus.com/feature/4626666856906752 which had a matching release number.
Not just me - lots of questions about why this does not work on the net, so clearly people did not see it on the page as "not supported"
Other docs work for this can be tracked in https://github.com/mdn/content/issues/27749

FF116 CSP script-src support external file with hash

---

api/TextMetrics.json

FF116 supports [TextMetrics.fontBoundingBoxAscent](https://developer.mozilla.org/en-US/docs/Web/API/TextMetrics/fontBoundingBoxAscent) and [TextMetrics.fontBoundingBoxDescent](https://developer.mozilla.org/en-US/docs/Web/API/TextMetrics/fontBoundingBoxDescent) in https://bugzilla.mozilla.org/show_bug.cgi?id=1801198
This updates the two records. 
Other docs work can be tracked in https://github.com/mdn/content/issues/27758

FF116 TextMetrics.fontBoundingBoxAscent/Descent supported

---

css/at-rules/media.json

Add flagged Chrome support for prefers-reduced-transparency
Also add link to WebKit bug tracking its implementation
https://chromium-review.googlesource.com/c/chromium/src/+/4671150 - Here's my merged Chromium patch that adds this media query behind the experimental web platform features flag.
https://goose.icu/prefers-reduced-transparency in latest canary should show this as supported

Add flagged Chrome support for prefers-reduced-transparency

---

api/GPUAdapter.json
api/GPUDevice.json
api/GPUPipelineError.json
api/GPUQueue.json

This PR adds some data points for [Chromium 116 WebGPU updates](https://pr-6763-static-dot-dcc-staging.uc.r.appspot.com/blog/new-in-webgpu-116), namely:
- `GPUDevice.importExternalTexture()` and `GPUQueue.copyExternalImageToTexture()` can now use a `VideoFrame` object as a source. Data point added for each.
- `GPUAdapter.requestDevice()` now returns a device that is immediately lost, if it has already been used to create a device (i.e. `requestDevice()` was already called.) rather than the promise being rejected with `null`. You can then get lost info from it via `GPUDevice.lost`. This needs to be added to the return value section. Data point added.
- `GPUPipelineError.GPUPipelineError()` message argument is now optional. Data point added.

WebGPU updates for Chrome 116

---

api/Navigator.json

Chrome for Android doesn't support the Badging API

Chrome for Android doesn't support the Badging API

---

api/FontFaceSet.json

This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `FontFaceSet` API. This fixes #7662 by adding a note as requested.

Update Chromium data for FontFaceSet API

---

api/Event.json

This PR updates and corrects version values for Firefox and Firefox Android for the `composed` member of the `Event` API. This adds a note that fixes #16770; details for testingand information in the linked issue.

Update Firefox data for api.Event.composed

---

api/IdleDetector.json

This PR updates and corrects version values for Microsoft Edge for the `IdleDetector` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.1.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/IdleDetector
Additional Notes: Fixes #20288.

Update Edge data for IdleDetector API

---

docs/data-guidelines/browsers.md
docs/data-guidelines/index.md

This PR adds documentation on how to add new browser versions to BCD.  More importantly, it also documents how we choose which Node.js version we should use.
This fixes #4492.

Document how to add a new browser version to BCD

---

css/properties/offset-position.json

1. Firefox 115 now supports the [`offset-position`](https://developer.mozilla.org/en-US/docs/Web/CSS/offset-position) property behind the flag `layout.css.motion-path-offset-position.enabled`. I am working on creating the content PR to reflect the syntax changes on the property page.
Bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1559232
2. The syntax for `offset-position` property has changed.
A new keyword (`normal`) has been added: https://drafts.fxtf.org/motion/#offset-position-property.
- Firefox supports the new syntax
- Chrome seems to support the `offset-position` property now but the new keyword is not yet supported.
1. Screenshots
<details>
<summary>In Firefox 115 beta, behind the flag</summary>
</details>
<details>
<summary>In Chrome beta (Version 115.0.5790.56 (Official …

CSS "offset-position": Update support in Firefox116 and Chrome

---

api/ImageCapture.json

This PR updates and corrects version values for Firefox and Firefox Android for the `ImageCapture` API. This fixes #9720 by updating the data based on the bug (https://bugzil.la/916643) and the source code (https://searchfox.org/mozilla-central/source/dom/webidl/ImageCapture.webidl#21).

Update Firefox data for ImageCapture API

---

api/Headers.json

This PR updates and corrects version values for Firefox Android for the `Headers` API. This sets Firefox Android to mirror from upstream, as it seems very, very unlikely that FxA support came later.  Fixes #9880.

Update Firefox Android data for Headers API

---

css/at-rules/media.json

Add Safari 17 support for overflow-block/inline media queries
Tested with https://mq5.goose.icu/ on iPadOS 17
Fixes #20320

Add Safari 17 support for overflow-block/inline media queries

---

css/at-rules/media.json

Add Chrome 98 flagged support for video-dynamic-range media query
This Chrome patch moved it under a different flag from the "dynamic-range" query. https://chromium.googlesource.com/chromium/src/+/055410a19d8631f3343146e712a784edf68aa5e6
And https://storage.googleapis.com/chromium-find-releases-static/055.html#055410a19d8631f3343146e712a784edf68aa5e6 shows that was launched in 98.
It may have been available in earlier versions but the exact version is unimportant that many releases ago.

Add Chrome 98 flagged support for video-dynamic-range media query

---

css/at-rules/media.json

Add Safari 17 support for scripting media query
https://github.com/WebKit/WebKit/pull/15076 - is the PR where it was added. And i manually tested using https://mq5.goose.icu/ on iPadOS 17
Fixes #20318

Add Safari 17 support for scripting media query

---

css/at-rules/media.json

Add Safari 17 support for update media query
https://github.com/WebKit/WebKit/pull/15074 - is the PR where it was added. And i manually tested using https://mq5.goose.icu/ on iPadOS 17
Fixes #20319

Add Safari 17 support for update media query

---

css/at-rules/media.json

This PR updates and corrects version values for Firefox Android for the `display-mode` member of the `media` CSS at-rule. This adds a note which fixes #10540.

Update Firefox Android data for css.at-rules.media.display-mode

---

html/elements/fieldset.json

This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `fieldset` HTML element. This fixes #10530 by updating the note accordingly.

Update Chromium data for fieldset HTML element

---

api/ServiceWorkerRegistration.json

This PR updates and corrects version values for Chrome Android for the `showNotification` member of the `ServiceWorkerRegistration` API. This PR fixes #10407 by setting Chrome Android to `false`, and adds a note explaining that it has no effect.

Update Chrome Android data for api.ServiceWorkerRegistration.showNotification

---

api/SpeechSynthesisUtterance.json

This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `boundary_event` member of the `SpeechSynthesisUtterance` API. This fixes #10303 by copying the note from Chrome Android to Chrome Desktop.

Update Chromium data for api.SpeechSynthesisUtterance.boundary_event

---

css/properties/grid-template-columns.json
css/properties/grid-template-rows.json

This PR updates and corrects version values for Firefox and Firefox Android for the `css.grid-template.fit-content` feature. This fixes #10171 by mirroring the prefix data from `width: fit-content;`.

Update Firefox data for css.grid-template.fit-content feature

---

browsers/chrome.json
browsers/chrome_android.json
browsers/webview_android.json

Hello!
Updating chrome browser to version 115.
Chrome for Android was released on July 21.

Update chrome browser to version 115

---

css/properties/font-size.json
css/properties/math-depth.json

math-depth and font-size: math are supported in Firefox 117. They are supported in Chrome 109, so make them non-experimental features.
See https://bugzilla.mozilla.org/show_bug.cgi?id=1667090#c11
N/A

[mathml] Update compat data for math-depth and font-size: math

---

css/properties/outline.json

The caveat on CSS `outline` support for Safari no longer applies: it follows `border-radius` as of 16.4!
* [Closed WebKit bug](https://bugs.webkit.org/show_bug.cgi?id=20807)
* [WPT results](https://wpt.fyi/results/css/css-ui/outline-005.html?label=experimental&label=master&aligned)
* [Safari beta announcement blog post here](https://webkit.org/blog/13966/webkit-features-in-safari-16-4/#outline-border-radius)
Related to: https://github.com/mdn/browser-compat-data/pull/17598, https://github.com/mdn/browser-compat-data/issues/12760, https://github.com/Fyrd/caniuse/issues/6099

Update Safari `outline` support to full

---

css/properties/math-style.json

Indicate math-style is supported for Firefox 117.
https://groups.google.com/a/mozilla.org/g/dev-platform/c/Uk39hvO910w/m/rBwWIfmLCAAJ
https://bugzilla.mozilla.org/show_bug.cgi?id=1845516
math-depth/font-size already handled in https://github.com/mdn/browser-compat-data/pull/20417

Update Firefox support for math-style

---

css/properties/background-image.json
css/types/image.json

Fix https://github.com/mdn/browser-compat-data/issues/20246
See https://bugs.webkit.org/show_bug.cgi?id=160934 and which https://github.com/WebKit/WebKit/commit/52692677632e50f8d0e3a4b0f62c94e5520a47d9 which is tagged with Safari 14 as the earliest release.

Update image-set() data for Safari

---

javascript/builtins/Intl/NumberFormat.json
javascript/builtins/Intl/PluralRules.json

This updates the
- `NumberFormat.resolvedOptions()` to reflect all the changes to options, not just the `useGrouping` option.
- `PluralRules` - constructor and `resolvedOptions()` to add the NumberFormat v3 updates.
Follow on from #20262
Related docs work can be tracked in https://github.com/mdn/content/issues/27746

FF116 Intl NumberFormat and PluralRules NumberFormat v3 updates

---

api/HTMLInputElement.json

Chrome & Safari has supported input `cancel` event.
test: add a `cancel` event listener on the input element and print a log.
https://codesandbox.io/s/file-cancel-event-2qwspv
| Browser | version | test result | release notes or docs |
|--------|--------|--------|--------|
| Chrome | 113.0.5672.163 |   ✅  | https://chromiumdash.appspot.com/commits?commit=3cee6dd4bef608ab05a8b6a69fee5c00204b85ef&platform=Android |
| Safari | 16.4 |  ✅  | https://developer.apple.com/documentation/safari-release-notes/safari-16_4-release-notes#Forms | 
Fixes #20342

Add Chrome/Safari versions for api.HTMLInputElement.cancel_event

---

css/at-rules/media.json

Add Safari 16 support for forced-colors
Also clean up non-mirrored data that should be mirrored
The commit where it was added to WebKit: https://github.com/WebKit/WebKit/commit/46513cc172ce079baedb34e890803058b9158b35
The release notes where it was added to Safari TP 153: https://webkit.org/blog/13148/release-notes-for-safari-technology-preview-153/
Based on the the timing I'm assuming it made it for 16.0.
It always equates to false so the exact version is arguably unimportant.
I've also tested Chrome for Android and it's supported so I believe the false data is just erroenous. So they're all made to mirror now.

Add Safari 16 support for forced-colors

---

api/NavigateEvent.json
api/Navigation.json
api/NavigationCurrentEntryChangeEvent.json
api/NavigationDestination.json
api/NavigationHistoryEntry.json
api/NavigationTransition.json
api/Window.json
test/linter/test-spec-urls.ts

The Navigation API is now part of the HTML specification and MDN pages exist.

Update mdn_urls and spec_urls for the Navigation API

---

api/HTMLElement.json

FF117 `HTMLElement.togglePopover()` returns `boolean` (behind pref) instead of None in https://bugzilla.mozilla.org/show_bug.cgi?id=1842845. This is due to a spec change.
Other browsers do not implement this yet, but it is worth adding the subfeature now - it will be needed when the pref is removed.
Related docs work can be tracked in https://github.com/mdn/content/issues/27417

FF117 HTMLElement.togglePopover() returns boolean behind pref

---

api/CSS.json
api/Highlight.json
api/HighlightRegistry.json
css/selectors/highlight.json

FF117 supports the [CSS Custom Highlight API](https://developer.mozilla.org/en-US/docs/Web/API/CSS_Custom_Highlight_API) in nightly in https://bugzilla.mozilla.org/show_bug.cgi?id=1840818 (behind  a pref `dom.customHighlightAPI.enabled` since FF111 and now enabled in nightly).
This adds "preview" to all parts of the API. As far as I can tell the created objects match the spec.
Decided not to add second entry that includes the preference since once something is in preview that is really the latest and greatest that you want people to try.
Other docs work associated with this can be tracked in https://github.com/mdn/content/issues/28291

FF117 Nightly CSS highlight API

---

browsers/safari.json
browsers/safari_ios.json

This PR adds Safari 16.6 to the browser data and marks it as the current version.  The release date comes from https://mrmacintosh.com/macos-ventura-13-full-installer-database-download-directly-from-apple/, and the engine version comes from Safari 16.6 itself.

Safari 16.6 is released

---

css/types/abs.json
css/types/sign.json

The `abs()` and `sign()` functions are supported in 117.
Docs:
- [`abs()`](https://developer.mozilla.org/en-US/docs/Web/CSS/abs)
- [`sign()`](https://developer.mozilla.org/en-US/docs/Web/CSS/sign)
__pen/demo:__
TODO
__Bugzilla:__
- [BUG-1814588](https://bugzilla.mozilla.org/show_bug.cgi?id=1814588)

relnote(117): sign() and abs() functions available

---

javascript/builtins/ArrayBuffer.json

FF117 adds support for the stage 3 [TC39 ArrayBuffer transfer proposal](https://github.com/tc39/proposal-arraybuffer-transfer) in nightly AND behind a preference in https://bugzilla.mozilla.org/show_bug.cgi?id=1841113. It is also supported in Chrome from 114 (see https://chromestatus.com/feature/5073244152922112 and tested). Testing indicates not in Safari. Also nothing to indicate in Deno or NodeJS.
I'm getting failure on the spec  links, such as https://tc39.es/proposal-arraybuffer-transfer/#sec-arraybuffer.prototype.transfertofixedlength - what's the best solution for this case? Put into MDN in the short term?
Related docs work is in https://github.com/mdn/content/issues/28285

JS ArrayBuffer Transfer proposal

---

css/types/abs.json
css/types/sign.json

My mistake, target branch for flipping the pref is Fx118 for these features. Currently these are nightly-only.
__prefs:__
- https://hg.mozilla.org/integration/autoland/file/tip/modules/libpref/init/StaticPrefList.yaml#l8186
- `layout.css.abs-sign.enabled`
__pen:__
https://codepen.io/bsmth/pen/KKrEMZr
__Amends:__
__Bugzilla:__
- (117) Sign-Related Functions: abs() and sign() https://bugzilla.mozilla.org/show_bug.cgi?id=1814588
- (118) Enable css-values-4 math functions by default https://bugzilla.mozilla.org/show_bug.cgi?id=1814589

relnote(117): sign() and abs() functions in nightly only (planned Fx118)

---

html/elements/link.json

This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `rel.alternate_stylesheet` member of the `link` HTML element. This fixes #14987 by setting all Chromium browsers to mirror from upstream.

Update Chromium data for html.elements.link.rel.alternate_stylesheet

---

javascript/statements.json

This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `for_await_of` member of the `statements` JavaScript feature. This fixes #14522.

Update Safari data for javascript.statements.for_await_of

---

api/_globals/console.json

This PR combines the "substitution strings" subfeatures of the Console API.  This fixes #12607.

Combine console "substitution strings" features

---

api/HTMLCanvasElement.json

This PR updates and corrects version values for Chrome Android for the `toBlob` member of the `HTMLCanvasElement` API. This fixes #12192 by setting Chrome Android to mirror.

Update Chrome Android data for api.HTMLCanvasElement.toBlob

---

css/properties/grid-template-columns.json

This PR updates and corrects version values for Firefox Android for the `subgrid` member of the `grid-template-columns` CSS property. This fixes #12128 by setting Firefox Android to mirror.

Update Firefox Android data for css.properties.grid-template-columns.subgrid

---

api/MediaRecorder.json

This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `MediaRecorder` API. This fixes #11998.

Update Safari data for MediaRecorder API

---

api/OES_texture_float_linear.json

This PR updates and corrects version values for Safari iOS/iPadOS for the `OES_texture_float_linear` API. The data comes from manual testing, running test code through BrowserStack, SauceLabs and custom VMs.
Test Code: https://mdn-bcd-collector.gooborg.com/tests/api/OES_texture_float_linear
Additional Notes: This fixes #11536.

Update Safari iOS data for OES_texture_float_linear API

---

api/KeyboardEvent.json

This PR updates and corrects version values for Firefox and Firefox Android for the `key.dead_key` member of the `KeyboardEvent` API. The data comes from a bug in the web browser's bug tracker.
Bug: https://bugzil.la/938987
Additional Notes: This fixes #11523.

Update Firefox data for api.KeyboardEvent.key.dead_key

---

html/elements/search.json

Also clean up non-mirrored data that should be mirrored
Add Safari and Firefox support for search element
https://groups.google.com/a/mozilla.org/g/dev-platform/c/1Eoh9zcTt08/m/xdir_heoAQAJ - Firefox Intent to Ship
Safari manually tested on latest 16.x version it's not supported, and 17 beta it is.

Add browser support for search element

---

api/CSSStyleSheet.json

See https://wpt.fyi/results/css/cssom/CSSStyleSheet-constructable-baseURL.tentative.html

CSSStyleSheet() constructor baseURL option not supported in Chrome

---

webextensions/manifest/action.json
webextensions/manifest/browser_action.json
webextensions/manifest/options_ui.json
webextensions/manifest/page_action.json
webextensions/manifest/sidebar_action.json

Updated relevant notes to indicate that 'browser_style:true' removed from MV3 in release 118.
Provide documentation for [Bug 1830711](https://bugzilla.mozilla.org/show_bug.cgi?id=1830711) Turn off support for browser_style:true in MV3
Content changes made in [#28415](https://github.com/mdn/content/pull/28415)

browser_style:true removed from MV3

---

webextensions/api/proxy.json

Documentation for the `proxy,register` and `proxy.unregister` functions removed as part of "proxy API compatibility details update" [#28276](https://github.com/mdn/content/pull/28276)

Remove anachronistic proxy details

---

webextensions/api/menus.json

This PR updates and corrects version values for Firefox and Firefox Android for the `OnClickData.srcUrl` member of the `menus` Web Extensions interface. This fixes #15848 by removing the separate statement for the note and instead simply combining it with the above statement.

Update Firefox data for webextensions.api.menus.OnClickData.srcUrl

---

html/global_attributes.json

This PR updates and corrects version values for Firefox Android for the `part` member of the `global_attributes` HTML feature. This fixes #20402 by setting FxA to mirror from upstream.

Update Firefox Android data for html.global_attributes.part

---

http/headers/Clear-Site-Data.json

The `Clear-Site-Data` HTTP header [`clientHints` data type](https://w3c.github.io/webappsec-clear-site-data/#grammardef-clienthints) will be supported in Chrome 117 (see [ChromeStatus entry](https://chromestatus.com/feature/5105030738214912)). This PR adds BCD for it.

Add data for Clear-Site-Data clientHints type

---

api/DocumentPictureInPicture.json
api/DocumentPictureInPictureEvent.json
api/Window.json

The [Document Picture-In-Picture API](https://wicg.github.io/document-picture-in-picture/) is supported in release Chrome version 116 (see [ChromeStatus entry](https://chromestatus.com/feature/5755179560337408)). This PR adds BCD for this API.
See my [research document](https://docs.google.com/document/d/1YGFqgYX8nqOQYAh8hgMfjmTJUrxBe932q4aicXdM8qo/edit) for more details of exactly what has been added.

Add BCD for Document Picture-In-Picture API

---

javascript/builtins/Map.json
javascript/builtins/Object.json

The [`Map.groupBy()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/groupBy) and [`Object.groupBy()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/groupBy) static methods are supported in Chrome 117 release (see [ChromeStatus entry](https://chromestatus.com/feature/5714791975878656); I also tested them in Canary 117).
This PR updates the BCD to suit.

Add Chrome support data for groupBy()

---

css/properties/scroll-timeline.json

This PR removes irrelevant flag data for  for the `scroll-timeline` CSS property as per the corresponding [data guidelines](https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines/index.md#removal-of-irrelevant-flag-data). This PR was created from results of the `remove-redundant-flags` script.
Additional Notes: This also fixes the notes that were incorrectly formatted with Markdown rather than HTML.

Remove irrelevant  flag data for scroll-timeline CSS property

---

css/properties/transition-behavior.json
css/properties/transition.json

Adding the `transition-behavior` property and updating the shorthand which also includes this property.
This is part of the [CSS Transitions 2 spec](https://drafts.csswg.org/css-transitions-2/#transition-behavior-property), and implemented in Chrome 117.

The transition-behavior property

---

api/CanvasRenderingContext2D.json
api/OffscreenCanvasRenderingContext2D.json

https://bugzilla.mozilla.org/show_bug.cgi?id=1778909
(Looks like part of interop2023)

Firefox 115 supports Canvas {letter,word}Spacing

---

css/selectors/indeterminate.json

See https://github.com/WebKit/WebKit/commit/e8eecf8527fbf9bc9f3984d7e42d9a2ad9dbf233
Fixes https://github.com/mdn/browser-compat-data/issues/20503

Safari 10 supports :indeterminate with <input type=radio>

---

css/properties/offset-path.json

In the `offset-path` property ([page being updated](https://pr28348.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/offset-path)), Fx116 adds support for `<basic-shape>` and `<coord-box>` behind the preferences `layout.css.motion-path-basic-shapes.enabled` and `layout.css.motion-path-coord-box.enabled`, respectively.
The new syntax:
`offset-path: none | <offset-path> || <coord-box>`
This PR:
- adds rows for `<basic-shape>` and `<coord-box>`.
- adds links to `path` and `ray()` pages in the existing path and ray rows.
- renames `<ray-size>` to `<size>`: (update in [content page](https://pr28348.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/ray#size)).
Codepen: https://codepen.io/dipikabh/pen/JjexYPo
- Fx116 stable version: Supported behind pref and are optional
- Chrome Canary: Supported …

CSS offset-path: Add rows for <basic-shape> and <coord-box> for Firefox 116

---

css/types/ray.json

Fx116 adds support for specifying initial starting position of the ray. The [`ray()`](https://developer.mozilla.org/en-US/docs/Web/CSS/ray) function itself is still available behind the preference `layout.css.motion-path-ray.enabled`.
The new syntax:
`ray( <angle> && <size>? && contain? && [at <position>]? )`
This PR:
- adds the feature row "position" for `at <position>`.
- renames the "size-support" row to "size" for `<ray-size>`.
- renames `<ray-size>` to `<size>`: (update in [content page](https://pr28348.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/ray#size))
Safari TP does not support `<ray-size>`, so removed the value for that feature row for Safari.
Codepen: updated ray syntax (https://codepen.io/dipikabh/pen/yLReQaZ)
- Fx116 stable version: `at <position>` is supported behind …

CSS ray() function: Add "at <position>" feature row for Firefox116

---

css/properties/contain-intrinsic-size.json

The declaration `contain-intrinsic-size: auto none` is now supported.
__Docs:__
- [`contain-intrinsic-size`](https://developer.mozilla.org/en-US/docs/Web/CSS/contain-intrinsic-size)
__Bugzilla:__
- https://bugzilla.mozilla.org/show_bug.cgi?id=1835813
__WPT:__
- https://wpt.fyi/results/css/css-sizing/contain-intrinsic-size/auto-014.html?label=experimental&label=master&aligned
__Resources:__
- https://phabricator.services.mozilla.com/D174583#inline-985747
- https://chromestatus.com/feature/6203168806928384
- https://wicg.github.io/display-locking/sample-code/contain-intrinsic-size-examples.html

relnote(117): 'auto none' allowed for 'contain-intrinsic-size' CSS prop

---

css/properties/scrollbar-color.json
css/properties/scrollbar-width.json

Update Chrome support data for CSS Scrollbars
https://chromium-review.googlesource.com/c/chromium/src/+/4777120?tab=checks - My patch to move scrollbar-color under experimental just merged so will be in 118 canary tomorrow.
Scrollbar width was moved to experimental in 115.

Update Chrome Support for CSS Scrollbars

---

html/elements/iframe.json

This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `allowpaymentrequest` member of the `iframe` HTML element. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.2.1).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/html/elements/iframe/allowpaymentrequest

Update Chromium data for html.elements.iframe.allowpaymentrequest

---

api/RTCRtpEncodingParameters.json

This PR updates and corrects version values for Microsoft Edge for the `scaleResolutionDownBy` member of the `RTCRtpEncodingParameters` API. This sets Edge to mirror, which fixes #20529.

Update Edge data for api.RTCRtpEncodingParameters.scaleResolutionDownBy

---

.github/workflows/add-push-artifacts.yml
package.json
scripts/diff-features.ts

This PR fixes #20464 by replacing all calls to the broken `ts-node` CLI with `node --loader=ts-node/esm`.

Support Node v20 by replacing ts-node CLI calls

---

css/properties/grid-template-columns.json
css/properties/grid-template-rows.json

The `subgrid` value for `grid-template-columns` and `grid-template-rows` is in Chrome 117. 
https://chromestatus.com/feature/5663795354533888

Subgrid support in Chrome

---

api/CredentialsContainer.json
api/IdentityProvider.json

Chrome 116 supports various [Fed CM API](https://developer.mozilla.org/en-US/docs/Web/API/FedCM_API) extensions (see [ChromeStatus entry](https://chromestatus.com/feature/5166718178033664))
See my [research document](https://docs.google.com/document/d/1cvLL7euxUeoLvQk6oLy5a6b7KlySmorJIqCYOngGPoA/edit) for more details of what the extensions are.

Add BCD for FedCM extensions

---

.github/labeler.yml

This PR updates the labeler config to automatically label WebAssembly pull requests.

Automatically label WASM pull requests

---

.github/workflows/update_bcd-utils_api.yml

- This is the other half of https://github.com/mdn/bcd-utils/pull/24 .
This PR creates a workflow that will trigger the API deployment workflow in `mdn/bcd-util` repo.
Note: this will need a special `secrets.DISPATCH_PAT` token to be created.

fix(ci): Trigger mdn/bcd-util API deployment after release

---

browsers/firefox.json
browsers/firefox_android.json

**Summary**
Firefox 116 got released
**Test results and supporting details**
Release Notes: https://www.mozilla.org/en-US/firefox/116.0/releasenotes/

Release Firefox 116

---

browsers/deno.json

This PR marks Deno 1.36 as released and adds it to our data.

Deno 1.36 is released

---

browsers/chrome.json
browsers/chrome_android.json
browsers/webview_android.json

This PR marks Chrome 116 as the current version of Chrome.

Chrome 116 is released

---

test/linter/test-browsers-presence.ts

This PR fixes the browser presence linter to allow server context browsers to be present in the WebAssembly category.

Fix linter to allow Deno/NodeJS in WASM category

---

api/FileSystemSyncAccessHandle.json

As detailed in https://github.com/mdn/content/issues/28647, the sync support data is misleading/wrong; the incorrect async versions of these methods are no longer supported in any modern browser. This PR improves the data as suggested.
Fixes https://github.com/mdn/content/issues/28647

Improve data about async versions of filesystemsyncaccesshandle methods

---

api/RTCEncodedAudioFrame.json
api/RTCEncodedVideoFrame.json

The specification links for RTCEncodedAudioFrame and RTCEncodedVideoFrame wasn't working. This tries a new link to the IDL section rather than nearest heading.
This is related to https://github.com/mdn/content/issues/28280

RTCEncodedAudioFrame / Video frame links

---

api/Notification.json

Windows notifications require user interaction (dismiss) by default via `dom.webnotifications.requireinteraction.enabled` pref
__Revision:__
- https://hg.mozilla.org/mozilla-central/rev/74f21a0ae212
__Bugzilla:__
- https://bugzilla.mozilla.org/show_bug.cgi?id=1794475

relnote(117): Windows notifications have requireInteraction set to true by default

---

html/elements/base.json

The `href` in the [`<base>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base) element disallows `data:` and `javascript:` URLs in a recent spec change. Note however that Chrome and Safari already obey this rule. FF does not - but will in https://bugzilla.mozilla.org/show_bug.cgi?id=1850967
This was tested using first test in http://wpt.live/html/semantics/document-metadata/the-base-element/base-javascript.html and http://wpt.live/html/semantics/document-metadata/the-base-element/base-data.html
Note that the dynamic case of using JavaScript to add a new base element is not yet supported by our browsers - this is the third test in the above tests (currently failing). This PR only applies to the HTML base element.
Associated docs: https://github.com/mdn/content/issues/28865

html base element - forbid href with data or javascript url

---

css/at-rules/media.json

This PR adds the "or" syntax to the `@media` at-rule.  This fixes #6033.  Test code used is in the issue.

Add "or" syntax to @media at-rule

---

http/headers/Sec-CH-Prefers-Reduced-Transparency.json

Adds data for the [Sec-CH-Prefers-Reduced-Transparency](https://wicg.github.io/user-preference-media-features-headers/#sec-ch-prefers-reduced-transparency) header
Here's my chrome patch that adds this: https://chromium-review.googlesource.com/c/chromium/src/+/4705483
Fixes #20392

Add Sec-CH-Prefers-Reduced-Transparency header

---

css/at-rules/media.json

Update Chrome support for scripting media query
https://chromium-review.googlesource.com/c/chromium/src/+/4827163: My patch to enable this feature by default got merged today so will be in Chrome 118

Update Chrome support for scripting media query

---

api/CanvasRenderingContext2D.json

This PR updates and corrects version values for Firefox and Firefox Android for the `textRendering` member of the `CanvasRenderingContext2D` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.2.3).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/CanvasRenderingContext2D/textRendering

Update Firefox data for api.CanvasRenderingContext2D.textRendering

---

css/types/abs.json
css/types/exp.json
css/types/hypot.json
css/types/log.json
css/types/mod.json
css/types/pow.json
css/types/rem.json
css/types/round.json
css/types/sign.json
css/types/sqrt.json

There are a few CSS math functions enabled by default in 118.
__Bugzilla:__
- https://bugzilla.mozilla.org/show_bug.cgi?id=1814589
__details:__
>Specifically enabling these prefs (previously nightly only):
> - layout.css.round.enabled
> - layout.css.mod-rem.enabled
> - layout.css.exp.enabled
> - layout.css.abs-sign.enabled
>Specifically these functions: round, mod, rem, pow, sqrt, hypot, log, exp, abs, sign
Revision: https://hg.mozilla.org/integration/autoland/rev/d84e836e47652db87a27a6f4b689c2a34c699685

relnote(118): CSS math functions enabled (CSS Values 4)

---

api/OffscreenCanvasRenderingContext2D.json

This PR updates and corrects version values for Firefox and Firefox Android for the `textRendering` member of the `OffscreenCanvasRenderingContext2D` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.2.3).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/OffscreenCanvasRenderingContext2D/textRendering

Update Firefox data for api.OffscreenCanvasRenderingContext2D.textRendering

---

css/properties/baseline-source.json

This PR updates and corrects version values for Firefox and Firefox Android for the `baseline-source` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.2.3).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/baseline-source

Update Firefox data for baseline-source CSS property

---

css/properties/offset-anchor.json
css/properties/offset-path.json
css/properties/offset-position.json
css/types/basic-shape.json
css/types/ray.json

Chrome 116 ships CSS Motion Path per https://chromestatus.com/feature/5124394449371136
https://github.com/web-platform-dx/web-features/pull/333 was useful to determine all features that belong to this group.
The path() function works also on clip-path since version 88, as confirmed by https://chromestatus.com/feature/5633533638868992 and the same data in css.properties.clip-path.path
Fixes https://github.com/mdn/browser-compat-data/issues/20628
Fixes https://github.com/mdn/browser-compat-data/issues/20653

Chrome 116 ships CSS Motion Path

---

api/TextMetrics.json

This PR updates and corrects version values for Firefox and Firefox Android for the `TextMetrics` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.2.3).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/TextMetrics

Update Firefox data for TextMetrics API

---

css/selectors/first.json

Fix https://github.com/mdn/browser-compat-data/issues/20595

Firefox 116 ships CSS :first selector

---

webextensions/api/devtools.json

Adds browser variation clarifications originally proposed in https://github.com/mdn/content/pull/20552

Clarify devtools.panels.create() path resolution

---

http/headers/Sec-CH-Prefers-Reduced-Transparency.json

Update Chrome support for Sec-CH-Prefers-Reduced-Transparency header to reflect it releasing in 118
https://chromium-review.googlesource.com/c/chromium/src/+/4846931 - is my patch to enable this by default which got merged into 118.

Update Chrome support for Sec-CH-Prefers-Reduced-Transparency header

---

api/Notification.json

This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `silent` member of the `Notification` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.2.3).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/Notification/silent

Update Safari data for api.Notification.silent

---

html/elements/link.json

As discussed in https://github.com/mdn/browser-compat-data/pull/20641#issuecomment-1711841688 we can make the `rel` attributes better on [the MDN link page](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link#browser_compatibility) with descriptions.
N/A
N/A
https://github.com/mdn/browser-compat-data/pull/20641#issuecomment-1711841688

Descriptions for link rel types

---

browsers/chrome.json
browsers/chrome_android.json
http/headers/Sec-CH-Prefers-Reduced-Transparency.json

Correct Chrome support for Sec-CH-Prefers-Reduced-Transparency header
In #20672 I incorrectly marked this as released in 118. However, it seems I just missed the cut off for 118 so it's in fact in 119. Apologies for this mistake here's the correction.

Correct Chrome support for Sec-CH-Prefers-Reduced-Transparency header

---

api/RTCRtpTransceiver.json

[`RTCRtpTransceiver.currentDirection`](https://developer.mozilla.org/en-US/docs/Web/API/RTCRtpTransceiver/currentDirection) and [`RTCRtpTransceiver.direction`](https://developer.mozilla.org/en-US/docs/Web/API/RTCRtpTransceiver/direction) now support a new value `stopped` in https://bugzilla.mozilla.org/show_bug.cgi?id=1568296. I also tested in Chrome and Safari using the last result in the first test of https://wpt.live/webrtc/RTCRtpTransceiver-stopping.https.html
Note, I call this "supports" not "returns" for the value because the `direction` also can be set with the value some circumstances, but I don't want to go into that level of detail in BCD.
Related docs work can be tracked in https://github.com/mdn/content/issues/28845

RTCRtpTranceiver - current/currentDirection support stopped value

---

api/TextMetrics.json

FF118 supports [`TextMetrics.emHeightDescent`](https://developer.mozilla.org/en-US/docs/Web/API/TextMetrics/emHeightDescent) and [`TextMetrics.emHeightDescent`](https://developer.mozilla.org/en-US/docs/Web/API/TextMetrics/emHeightDescent) in https://bugzilla.mozilla.org/show_bug.cgi?id=1841692
This adds a BCD entry, and that also makes this no longer experimental.
Note, this is also present in Chrome - which can be tested using these tests:
[2d.text.measure.emHeights-low-ascent.html](http://wpt.live/html/canvas/offscreen/text/2d.text.measure.emHeights-low-ascent.html)
[2d.text.measure.emHeights-low-ascent.worker.js](http://wpt.live/html/canvas/offscreen/text/2d.text.measure.emHeights-low-ascent.worker.js)
[2d.text.measure.emHeights-zero-descent.html](http://wpt.live/html/canvas/offscreen/t …

FF118 TextMetrics.emHeightAscent/Descent supported

---

api/TextMetrics.json

Fixes error injected in #20682

Chrome supports TextMetrics.emHeightAscent/Descent behind pref

---

css/properties/font-size-adjust.json

Fx118 adds support for `from-font` keyword in CSS [`font-size-adjust`](https://developer.mozilla.org/en-US/docs/Web/CSS/font-size-adjust#browser_compatibility) property.
https://codepen.io/dipikabh/pen/OJrpmBO
- Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1708240. Tested in Nightly 119 and 118 beta (browserstack).
- Safari TP: Tested in version 17
- Chromestatus: Still no support. Tested in 117 beta and supported there, so coming soon
- https://chromestatus.com/feature/5720910061371392
- https://chromestatus.com/feature/5170570175447040
Doc issue tracker: https://github.com/mdn/content/issues/28842
Content update PR: https://github.com/mdn/content/pull/29052

Firefox 118 supports "from-font" keyword in CSS "font-size-adjust" property

---

api/Window.json

Part of the fix for https://github.com/mdn/content/issues/23837: add a subfeature describing compat for browsers displaying a generic string in the confirmation dialog, rather than one under the site's control.

Fix issue 23837: compat data for generic string display

---

scripts/release/mirror.test.ts
scripts/release/mirror.ts

This PR fixes #20712 by catching "Google Chrome" in notes replacement, rather than just "Chrome".

Fix notes replacement in mirroring

---

api/Response.json

BCD side of https://github.com/mdn/content/issues/24453.
- Chromium shipped in 116: https://chromestatus.com/feature/5192003450568704
- Firefox shipped in 102: https://github.com/whatwg/fetch/issues/267#issuecomment-1350303670
- Safari apparently does not support this yet: https://bugs.webkit.org/show_bug.cgi?id=250549
- Deno apparently does not support this yet: https://github.com/denoland/deno/issues/17386

Fix content issue 24453: Response.body is a readable byte stream

---

html/elements/search.json

According to [chromestatus](https://chromestatus.com/roadmap), the [HTML `<search>` element](https://chromestatus.com/feature/5126108151808000) is shipping in Chrome 118.
https://github.com/mdn/browser-compat-data/pull/19357

HTML `<search>` element - Chrome 118 support

---

css/properties/clear.json
css/properties/float.json
css/properties/resize.json

Chrome 118 adds support for CSS logical flow-relative values.
Ref: https://chromestatus.com/feature/6237096230518784

Chrome 118 CSS logical flow-relative values

---

browsers/nodejs.json

This PR adds Node.js v18.1.0 to the browser data.

Add Node.js v18.1.0

---

api/RTCPeerConnection.json

FF118 - [`RTCPeerConnection.getTransceivers()`](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/getTransceivers) returns only non-stopped transceivers according to https://bugzilla.mozilla.org/show_bug.cgi?id=1568296#c3. I tested this using the test in http://wpt.live/webrtc/RTCRtpTransceiver-stop.html with text "If a transceiver is stopped, transceivers, senders and receivers should disappear after offer/answer", which further indicates (as does the spec) that the receivers/senders are also removed from the lists if a transceiver is stopped.
The test fails in FF117 and passes in FF118. I also tested on Safari and that fails in all cases. Chrome passes in all versions from the point at which it first supports `stop()` - which is Chrome 88.
Related to …

Transceivers, senders, receivers not included in returned arrays if stopped

---

html/elements/a.json

tested https://codepen.io/estelle/live/ExGXoGw on real devices and browser stack.
href="sms:5534234234234" only works in Firefox (android, mac, windows)
related to https://github.com/mdn/content/pull/29101
standard: https://html.spec.whatwg.org/#sms-protocol

add sms protocol to a element

---

javascript/builtins/WebAssembly.json

Run `node -p "[WebAssembly.compileStreaming, WebAssembly.instantiateStreaming]"` in Node.js 18.0 and 18.1.
Implemented in https://github.com/nodejs/node/pull/42701

Add data for `WebAssembly.*Streaming` in Node.js

---

api/FileSystemSyncAccessHandle.json

This PR updates and corrects version values for all browsers for the `FileSystemSyncAccessHandle` API. This effectively reverts #20621 first, and then fixes the data.  (Chrome supported the synchronous version since 108 without a flag, and Safari since 16.4.)

Update all browsers data for FileSystemSyncAccessHandle API

---

javascript/builtins/Intl/NumberFormat.json

This PR is a part of a project to add missing interfaces and interface features to BCD that are from an active spec (including WICG specs) and is supported in at least one browser. This particular PR adds the missing features of the `NumberFormat` member of the `Intl` JavaScript builtin. This fixes #6046 by adding the missing arguments.  Note: all data was simply mirrored from the main constructor's data, assuming they are all features that were supported since the constructor was introduced.

Add missing features for javascript.builtins.Intl.NumberFormat

---

html/elements/textarea.json

This PR is a part of a project to add missing interfaces and interface features to BCD that are from an active spec (including WICG specs) and is supported in at least one browser. This particular PR adds the missing features of the `wrap.hard` member of the `textarea` HTML element. The data comes from manual testing, running test code through BrowserStack, SauceLabs and custom VMs.
Test Code: http://wpt.live/html/semantics/forms/the-textarea-element/wrap-enumerated-ascii-case-insensitive.html
Additional Notes: This fixes #10164.  (In that PR, the attribute is inaccurately described as "unsupported", but it is just the `hard` value that is unsupported in Firefox and Safari.)

Add missing features for html.elements.textarea.wrap.hard

---

css/selectors/user-invalid.json
css/selectors/user-valid.json

This PR updates the versions for the :user-valid and :user-invalid selectors based on manual testing. This fixes https://github.com/mdn/browser-compat-data/issues/20727

update Chrome version for css.selectors.user-valid/user-invalid

---

api/IdentityProvider.json

This PR adds the `_static` suffix to the `getUserInfo` member of the `IdentityProvider` API.  Note: the MDN page doesn't exist so no content update is needed.

Add "_static" suffix to api.IdentityProvier.getUserInfo

---

api/GamepadHapticActuator.json

This PR is a part of a project to add missing interfaces and interface features to BCD that are from an active spec (including WICG specs) and is supported in at least one browser. This particular PR adds the missing features of the `canPlayEffectType` member of the `GamepadHapticActuator` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.2.3).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/GamepadHapticActuator/canPlayEffectType

Add missing features for api.GamepadHapticActuator.canPlayEffectType

---

api/AnimationTimeline.json

This PR is a part of a project to add missing interfaces and interface features to BCD that are from an active spec (including WICG specs) and is supported in at least one browser. This particular PR adds the missing features of the `duration` member of the `AnimationTimeline` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.2.3).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/AnimationTimeline/duration

Add missing features for api.AnimationTimeline.duration

---

api/CSSStyleRule.json

FF118 supports now matches spec so [`CSSStyleRule`](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleRule) inherits from [`CSSGroupingRule`](https://developer.mozilla.org/en-US/docs/Web/API/CSSGroupingRule) instead of directly from  [`CSSRule`](https://developer.mozilla.org/en-US/docs/Web/API/CSSRule). See https://bugzilla.mozilla.org/show_bug.cgi?id=1846251.
This means that `CSSStyleRule` now supports the cssRules property + deleteRule and insertRule from `CSSGroupingRule`.
I have checked these are supported in `CSSGroupingRule` on the bcd collector. Also manually showed they exist in FF119 nightly. 
This adds support from version 118 and also links to the MDN docs.
Other docs work can be tracked in https://github.com/mdn/content/issues/28853

FF118 CSSStyleRule inherits from CSSGroupingRule - add props

---

browsers/nodejs.json
javascript/operators/import_meta.json

Release notes documenting that this is now available without a flag: https://nodejs.org/en/blog/release/v20.6.0
Note that the experimental version became synchronous in v20.0.0 (still behind a flag at the time): https://nodejs.org/en/blog/release/v20.0.0

Mark (synchronous) `import.meta.resolve(…)` as implemented in `node` v20.6.0

---

css/properties/grid-template-columns.json
css/properties/grid-template-rows.json

Reverts mdn/browser-compat-data#20387.  Turns out, the original report was actually incorrect, and the collector confirms that the value works as intended.  Tested with the following code in Firefox 51 and 52:
```html
<style id="test-style">
.example-element {
border: 1px solid #c5c5c5;
display: grid;
grid-auto-rows: 40px;
grid-gap: 10px;
width: 200px
}
.example-element>div {
background-color: rgba(0,0,255,.2);
border: 3px solid #00f
}
</style>
<p>grid-template-columns: fit-content(100%);</p>
<div class="example-element" style="grid-template-columns: fit-content(100%);">
<div>One</div>
<div>Two</div>
<div>Three</div>
<div>Four</div>
<div>Five</div>
</div>
<p>grid-template-columns: -moz-fit-content(100%);</p>
<div class="example-element" style="grid-template-columns: …
```

Revert "Update Firefox data for css.grid-template.fit-content feature"

---

css/properties/timeline-scope.json

This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `timeline-scope` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.2.3).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/timeline-scope

Update Chromium data for timeline-scope CSS property

---

api/TaskSignal.json

This PR is a part of a project to add missing interfaces and interface features to BCD that are from an active spec (including WICG specs) and is supported in at least one browser. This particular PR adds the missing features of the `any_static` member of the `TaskSignal` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.2.3).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/TaskSignal/any_static

Add missing features for api.TaskSignal.any_static

---

api/VisibilityStateEntry.json

This PR is a part of a project to add missing interfaces and interface features to BCD that are from an active spec (including WICG specs) and is supported in at least one browser. This particular PR adds the missing features of the `VisibilityStateEntry` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.2.3).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/VisibilityStateEntry

Add missing features for VisibilityStateEntry API

---

browsers/firefox.json
browsers/firefox_android.json

The Firefox versions haven't been updated since 117 got released about 3 weeks ago. This PR updates all the current versions.
https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/117

Release Firefox 117

---

javascript/builtins/Set.json

Updated javascript.builtins.Set to reflect Safari's 17 support.
[WebKit Features in Safari 17.0](https://webkit.org/blog/14445/webkit-features-in-safari-17-0/) (search in page for "Set Operations")
Doesn't look like there was one.

Safari 17 shipped new Set methods

---

css/types/abs.json
css/types/exp.json
css/types/hypot.json
css/types/log.json
css/types/mod.json
css/types/pow.json
css/types/rem.json
css/types/round.json
css/types/sign.json
css/types/sqrt.json

Add [crbug.com](https://crbug.com/) URLs to different [CSS math functions](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Functions#math_functions).

CSS Math Functions: Add crbug.com URLs

---

css/properties/offset-path.json

The CSS `offset-path` property can use the `url()` function to specify the ID of the SVG shape element to be used as a path.
- Firefox - Tested in **118** (https://bugzilla.mozilla.org/show_bug.cgi?id=1598158).
Available behind the flag  `layout.css.motion-path-url.enabled`.
- Chrome - Tested in **116** (https://bugs.chromium.org/p/chromium/issues/detail?id=654666, https://chromestatus.com/feature/5124394449371136)
- Safari - Tested in TP version 17 (but also working in version 16.6, though I was not able to determine the exact version in which the feature support was added)
- Only have the link to this bug https://bugs.webkit.org/show_bug.cgi?id=139127
- Also, for reference: https://github.com/WebKit/WebKit/blob/47fbfbce93f42fd200567a124d8ffe7922b3331b/LayoutTests/imported/w3c/web-platfor …

CSS "offset-path" can use url() to specify reference to SVG shape (Fx118)

---

http/headers/Feature-Policy.json
http/headers/Permissions-Policy.json

The Permissions-Policy and Feature-Policy for FF confused me because it said partial support of the header and indicated 
> "Only supported through the <code>allow</code> attribute on <code>&lt;iframe&gt;</code> elements."
So the header isn't actually supported, just the functionality that the header provides. Someone who knows how this all works might not be confused, but I was. So what I have done is change the note text to:
> Header not sent but policy can be set through the <code>allow</code> attribute on <code>&lt;iframe&gt;</code> elements (see <a href='https://bugzil.la/1627890'>bug 1627890</a>)"
The bug links are different - for Feature-Policy I link to the bug where the header was disabled by default. For `Permissions-Policy` I link to the bug where the header is intended to be …

FF Clarify Feature-Policy header not sent

---

browsers/deno.json
javascript/builtins/Map.json
javascript/builtins/Object.json

Deno v1.37 has been released https://deno.com/blog/v1.37
Deno added support of `Object.groupBy` and `Map.groupBy` in version 1.37.0.
You can check the support in the specific version with the commands:
```sh
curl -fsSL https://deno.land/install.sh | sh -s v1.37.0
deno --version
deno eval -p "Object.groupBy" # Or any other JS expression to check
```
The result of the above commands:
```shellsession
$ curl -fsSL https://deno.land/install.sh | sh -s v1.37.0
######################################################################## 100.0%
Deno was installed successfully to /Users/kt3k/.deno/bin/deno
$ deno --version    
deno 1.37.0 (release, aarch64-apple-darwin)
v8 11.8.172.3
typescript 5.2.2
$ deno eval -p "Object.groupBy"
[Function: groupBy]
$ curl -fsSL https://deno.land/install.sh | sh -s …
```

Add Deno 1.37, add support data for groupBy()

---

css/selectors/blank.json

Added Chromium issue track implementation URL for `:blank` CSS selector feature.

chore(`:blank`): added chromium implementation url

---

api/Navigator.json
api/WorkerNavigator.json
http/headers/Sec-GPC.json

Back in FF95 global privacy control (https://globalprivacycontrol.org/) was implemented behind two prefs `privacy.globalprivacycontrol.functionality.enabled` and `privacy.globalprivacycontrol.enabled`.
FF118 has now enabled the preference `privacy.globalprivacycontrol.functionality.enabled` in nightly/preview in https://bugzilla.mozilla.org/show_bug.cgi?id=1830623 
- The newly turned on pref  `privacy.globalprivacycontrol.functionality.enabled` turns on [`Navigator.globalPrivacyControl`](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/globalPrivacyControl) and `WorkerNavigator.globalPrivacyControl`. 
- The second pref `privacy.globalprivacycontrol.enabled` causes FF to send the [Sec-GPC](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Sec-GPC) HTTP header with a value …

Ff118 Nightly enables globalprivacy

---

css/properties/math-depth.json
css/properties/math-style.json

This PR removes irrelevant flag data for the `layout.css.math-style.enabled` flag of Firefox and Firefox Android as per the corresponding [data guidelines](https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines/index.md#removal-of-irrelevant-flag-data). This PR was created from results of the `remove-redundant-flags` script.

Remove irrelevant `layout.css.math-style.enabled` flag in Firefox

---

api/Headers.json
api/Request.json
api/Response.json
api/_globals/fetch.json

This PR removes irrelevant flag data for the `--experimental-fetch` flag of NodeJS as per the corresponding [data guidelines](https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines/index.md#removal-of-irrelevant-flag-data). This PR was created from results of the `remove-redundant-flags` script.

Remove irrelevant `--experimental-fetch` flag in NodeJS

---

api/Worker.json

This PR removes irrelevant flag data for the `--experimental-worker` flag of NodeJS as per the corresponding [data guidelines](https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines/index.md#removal-of-irrelevant-flag-data). This PR was created from results of the `remove-redundant-flags` script.

Remove irrelevant `--experimental-worker` flag in NodeJS

---

javascript/grammar.json
javascript/operators/await.json
javascript/operators/import.json
javascript/operators/import_meta.json
javascript/statements.json

This PR removes irrelevant flag data for the `--experimental-*` flags of NodeJS as per the corresponding [data guidelines](https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines/index.md#removal-of-irrelevant-flag-data). This PR was created from results of the `remove-redundant-flags` script.

Remove irrelevant `--experimental-*` flag in NodeJS

---

api/URLPattern.json

This PR removes irrelevant flag data for the `--unstable` flag of Deno as per the corresponding [data guidelines](https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines/index.md#removal-of-irrelevant-flag-data). This PR was created from results of the `remove-redundant-flags` script.

Remove irrelevant `--unstable` flag in Deno

---

api/Window.json

This PR removes irrelevant flag data for Deno for the `localStorage` member of the `Window` API as per the corresponding [data guidelines](https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines/index.md#removal-of-irrelevant-flag-data). This PR was created from results of the `remove-redundant-flags` script.

Remove irrelevant Deno flag data for api.Window.localStorage

---

css/types/color.json

This PR removes irrelevant flag data for Safari (Desktop and iOS/iPadOS) for the `color-mix` member of the `color` CSS value type as per the corresponding [data guidelines](https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines/index.md#removal-of-irrelevant-flag-data). This PR was created from results of the `remove-redundant-flags` script.

Remove irrelevant Safari flag data for css.types.color.color-mix

---

javascript/operators/await.json

This PR removes irrelevant flag data for Opera and Opera Android for the `top_level` member of the `await` JavaScript operator as per the corresponding [data guidelines](https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines/index.md#removal-of-irrelevant-flag-data). This PR was created from results of the `remove-redundant-flags` script.

Remove irrelevant Opera flag data for javascript.operators.await.top_level

---

api/HTMLMediaElement.json

This PR removes irrelevant flag data for Firefox and Firefox Android for the `preservesPitch` member of the `HTMLMediaElement` API as per the corresponding [data guidelines](https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines/index.md#removal-of-irrelevant-flag-data). This PR was created from results of the `remove-redundant-flags` script.
Additional Notes: This fixes #20766 in the meantime.

Remove irrelevant Firefox flag data for api.HTMLMediaElement.preservesPitch

---

api/Element.json
api/Sanitizer.json
css/properties/animation-timeline.json
css/properties/scroll-timeline-axis.json
css/properties/scroll-timeline-name.json

This PR removes irrelevant flag data for the `enable-experimental-web-platform-features` flag of Chromium (Chrome, Opera, Samsung Internet, WebView Android) as per the corresponding [data guidelines](https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines/index.md#removal-of-irrelevant-flag-data). This PR was created from results of the `remove-redundant-flags` script.

Remove irrelevant `enable-experimental-web-platform-features` flag in Chromium

---

css/properties/hyphenate-character.json
css/properties/hyphens.json

> Supported in Safari with `-webkit-` prefixes since 2011, the `hyphens` and `hyphenate-character` properties are now supported in their unprefixed form.
Ref: https://webkit.org/blog/14445/webkit-features-in-safari-17-0/

Update CSS `hyphens` full support in Safari 17

---

html/global_attributes.json

Safari 17.0 adds support for the `popover`, `popovertarget` and `popovertargetaction` global attributes.
Ref: https://webkit.org/blog/14445/webkit-features-in-safari-17-0/
Update: With the release of Safari 17 on September 26, these 3 global attributes will longer be experimental features.

Add Safari 17 support for `popover`, `popovertarget` and `popovertargetaction` attributes

---

css/at-rules/counter-style.json

Add support of S17 for css.at-rules.counter-style.suffix
Fixes #20754

css.at-rules.counter-style.suffix supported in S17

---

http/headers/Feature-Policy.json
http/headers/Permissions-Policy.json

[`Permissions-Policy: publickey-credentials-get`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Permissions-Policy/publickey-credentials-get) is supported in FF118 in https://bugzilla.mozilla.org/show_bug.cgi?id=1460986 under Feature-Policy alternative name. This is also therefore not experimental.
Have followed same pattern as other entries.
Associated docs work can be tracked in https://github.com/mdn/content/issues/28848

Ff118 Permissions-Policy: publickey-credentials-get supported

---

browsers/firefox.json
browsers/firefox_android.json

Update Firefox version numbers since 118 was released

Firefox 118 release

---

webextensions/manifest/browser_specific_settings.json

`gecko_android` is only really used by Firefox for Android. It doesn't makes sense to consider it available on Firefox, it confuses addons-linter, which incorrectly warns about it depending on the Firefox version the extension is compatible with instead of just looking at Firefox for Android compatibility.

Mark the `gecko_android` webextensions property as android-specific

---

javascript/builtins/Map.json
javascript/builtins/Object.json

FF119 supports Object.groupBy and Map.groupBy in https://bugzilla.mozilla.org/show_bug.cgi?id=1792650
This removes the preference and updates to not being experimental.
Related docs work can be tracked in https://github.com/mdn/content/issues/29303

FF119 Object.groupBy and Map.groupBy

---

css/at-rules/scope.json

_👋 Hi, Chrome DevRel here!_
Chrome 118 will soon ship with support for `@scope`.
- Spec: https://drafts.csswg.org/css-cascade-6/#scoped-styles
- ChromeStatus: https://chromestatus.com/feature/5100672734199808
This PR adds this new at-rule.

Add css.at-rules.scope

---

api/CanvasRenderingContext2D.json

This PR updates and corrects version values for Firefox and Firefox Android for the `CanvasRenderingContext2D` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.2.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/CanvasRenderingContext2D

Update Firefox data for CanvasRenderingContext2D API

---

api/TaskSignal.json

This PR updates and corrects version values for Microsoft Edge for the `any_static` member of the `TaskSignal` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.2.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/TaskSignal/any_static

Update Edge data for api.TaskSignal.any_static

---

api/HTMLVideoElement.json

Fixes #20837 which was added as supported in https://bugzilla.mozilla.org/show_bug.cgi?id=1832154
Note that there is no bcd collector test and this fails the wpt test for me https://wpt.live/picture-in-picture/disable-picture-in-picture.html
But I assume I'm doing something wrong.

FF116 HTMLVideoElement.disablePictureInPicture supported

---

api/WebTransport.json

FF119 supports `options.sendOrder` as an option to the [`WebTransport.createBidirectionalStream()`](https://developer.mozilla.org/en-US/docs/Web/API/WebTransport/createBidirectionalStream) in 
https://bugzilla.mozilla.org/show_bug.cgi?id=1816925
Note that FF implements the returned stream as a `WritableStream` rather than `WebTransportReceiveStream` (as per spec) so there is no way to get the sendOrder out again. I'd document `WebTransportReceiveStream` except that no one has implemented it yet.
Related docs work can be tracked in https://github.com/mdn/content/issues/29300

FF119 createBidirectionalStream sendOrder option

---

javascript/builtins/String.json

FF119 Supports [`String.prototype.isWellFormed()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/isWellFormed) and [`String.prototype.toWellFormed()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/toWellFormed) in https://bugzilla.mozilla.org/show_bug.cgi?id=1850755
This updates the versions.
Related docs work can be tracked in https://github.com/mdn/content/issues/29301

FF119 JS String isWellFormed()/to WellFormed() methods

---

api/Window.json

FF119 removes support for [`Window.sidebar`](https://developer.mozilla.org/en-US/docs/Web/API/Window/sidebar), which is a Mozilla-specific version of `Windows.external` in https://bugzilla.mozilla.org/show_bug.cgi?id=1768486
Support was actually removed in 102, behind a pref. I've reduced this to one entry for each of desktop and android with 102 being the final entry.
Related docs work can be tracked in https://github.com/mdn/content/issues/29306

FF119 Window.sidebar (external) not supported

---

http/headers/Cross-Origin-Embedder-Policy.json

FF119 supports the HTTP [Cross-Origin-Embedder-Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cross-Origin-Embedder-Policy) header directive `credentialless` in https://bugzilla.mozilla.org/show_bug.cgi?id=1851467 on desktop.
It supports the option on android on nightly, but not allowed to set that option, so have set to `false`.
This is part of https://github.com/mdn/content/issues/29413

FF119 HTTP COEP header: credentialless supported on desktop

---

css/selectors/next-sibling.json

- related to content PR https://github.com/mdn/content/pull/29392
Reference https://drafts.csswg.org/selectors/#adjacent-sibling-combinators

fix(css): rename 'Adjacent sibling' combinator to 'Next-sibling' combinator

---

api/Notification.json

This PR updates and corrects version values for Firefox and Firefox Android for the `requireInteraction` member of the `Notification` API. The data regarding OS-specific support is not formatted properly, so this PR fixes it.

Update Firefox data for api.Notification.requireInteraction

---

api/Window.json

FF has supported `window.external` since version 2 - adds back information that was stripped out in #20856 
Note, in FF102 only the alternative name has been removed.

Window.external - fix up FF version

---

html/elements/tr.json

This PR updates and corrects version values for Firefox and Firefox Android for the `align` member of the `tr` HTML element. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.2.5).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/html/elements/tr/align

Update Firefox data for html.elements.tr.align

---

html/elements/thead.json

This PR updates and corrects version values for Firefox and Firefox Android for the `thead` HTML element. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.2.5).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/html/elements/thead

Update Firefox data for thead HTML element

---

html/elements/th.json

This PR updates and corrects version values for Firefox and Firefox Android for the `th` HTML element. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.2.5).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/html/elements/th

Update Firefox data for th HTML element

---

html/elements/tfoot.json

This PR updates and corrects version values for Firefox and Firefox Android for the `tfoot` HTML element. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.2.5).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/html/elements/tfoot

Update Firefox data for tfoot HTML element

---

html/elements/td.json

This PR updates and corrects version values for Firefox and Firefox Android for the `td` HTML element. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.2.5).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/html/elements/td

Update Firefox data for td HTML element

---

html/elements/tbody.json

This PR updates and corrects version values for Firefox and Firefox Android for the `tbody` HTML element. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.2.5).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/html/elements/tbody

Update Firefox data for tbody HTML element

---

api/EventTarget.json

The compatability data says Node doesn't support the `signal` property of `EventTarget.addEventListener`. However, this support was added in node v15.4.0.
[Node Changelog](https://nodejs.org/en/blog/release/v15.4.0)
[Node PR merge comment](https://github.com/nodejs/node/pull/36258#issuecomment-737280775)
Fixes #18883

Updated Node support for EventTarget

---

html/elements/colgroup.json

This PR updates and corrects version values for Firefox and Firefox Android for the `colgroup` HTML element. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.2.5).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/html/elements/colgroup

Update Firefox data for colgroup HTML element

---

html/elements/link.json

This PR updates and corrects version values for all browsers for the `sizes` member of the `link` HTML element. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.2.5).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/html/elements/link/sizes

Update all browsers data for html.elements.link.sizes

---

webextensions/api/permissions.json

GeckoView is ready but not Fenix so we cannot mark this API as compatible with Firefox for Android yet. The UI (and therefore the API) will be implemented soon, see: https://bugzilla.mozilla.org/show_bug.cgi?id=1810047

`permissions.request()` is not yet available on Firefox for Android

---

browsers/chrome.json

Chrome 117 (not 116) is the latest stable chrome release.
- https://chromestatus.com/roadmap
- https://chromiumdash.appspot.com/schedule

Browsers: update chrome

---

browsers/safari.json
browsers/safari_ios.json

Safari 17.1 is available https://developer.apple.com/documentation/safari-release-notes/safari-17_1-release-notes
Related: #20788

Browsers: Add Safari 17.1 beta release

---

api/Element.json
api/ElementInternals.json

- Reflects Firefox 119 support on `Element` and `ElementInternals` for various ARIA attributes
The browser is changing, and we must keep up!
https://bugzilla.mozilla.org/show_bug.cgi?id=1785412
Child of https://github.com/mdn/content/issues/29311
Should be merged along with https://github.com/mdn/content/pull/29521

Reflects FX119 support on `Element` and `ElementInternals` for various ARIA attributes

---

api/Window.json

This sets [`Window.setImmediate`](https://developer.mozilla.org/en-US/docs/Web/API/Window/setImmediate) and `clearImmediate` to deprecated.
The discussion in  #20917 suggests this should be non-standard and deprecated. The standard exists but is marked as no longer being worked on. Given it is a draft I think non-standard then makes sense. It never got adopted (other than by node) and never will be, so to me deprecated also makes sense.
Fixes #20917

Window.json - setImmediate/clearImmediate deprecated

---

api/CredentialsContainer.json

FF119 supports [`credProp` WebAuthn extension](https://developer.mozilla.org/en-US/docs/Web/API/Web_Authentication_API/WebAuthn_extensions#credprops) in https://bugzilla.mozilla.org/show_bug.cgi?id=1844437
This adds the version and MDN link to `CredentialsContainer`. 
Related docs work can be tracked in https://github.com/mdn/content/issues/29307

FF119 CredentialsContainer.credProps supported

---

html/elements/head.json

This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `profile` member of the `head` HTML element. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.2.5).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/html/elements/head/profile

Update Safari data for html.elements.head.profile

---

html/elements/input.json

Show `<input>`'s `mozactionhint` property as unsupported in all browsers, added to Firefox in v4, removed from Firefox in v119, deprecated, and never on the standards track.
Related to https://github.com/mdn/content/issues/29312
Specifically, this PR exists because of @hamishwillee's comment here: https://github.com/mdn/content/issues/29312#issuecomment-1749796455

Add `mozactionhint` to BCD under `<input>` as added, removed, and deprecated in FF

---

test/linter/test-spec-urls.ts

This is a follow-up to #20919 which removes the exception for the unlinked spec from BCD.

Remove exception for setImmediate/clearImmediate spec

---

css/properties/contain-intrinsic-size.json

Add Safari 17 "auto none" support in contain-intrinisic-size
See release notes: https://developer.apple.com/documentation/safari-release-notes/safari-17-release-notes#CSS
and PR where it was added: https://github.com/WebKit/WebKit/pull/15369,
and where it was fixed: https://github.com/WebKit/WebKit/pull/15812

 Add Safari 17 "auto none" support in contain-intrinisic-size

---

http/status.json

103 Early Hints for preconnect is now enabled by default in Safari 17:
With Safari as the second major browser engine now supporting this by default, the experimental flag can be dropped (also included in this PR).
https://developer.apple.com/documentation/safari-release-notes/safari-17-release-notes#New-Features

103 Early Hints available from Safari 17 and so no longer experimental

---

css/at-rules/media.json

There was a bug in Chrome's scripting implementation that meant it wasn't actually enabled in 118. It's now been fixed so will actually ship in 120.
https://chromium-review.googlesource.com/c/chromium/src/+/4926489 - My Change to fix the issue.

Update Chrome support data for scripting media query

---

css/properties/background-position-x.json

I noticed that there are some difference between to properties which I suspect should have a complete parallel :
- `background-position-y`
- `background-position-x`
- https://github.com/mdn/browser-compat-data/blob/main/css/properties/background-position-y.json
- https://github.com/mdn/browser-compat-data/blob/main/css/properties/background-position-x.json
This should an obvious bugfix, if I am mistaken about this, then the PR should be closed and I will open an issue instead.
N/A

Fix discrepancy between `background-position-y` and `background-position-x`

---

css/types/color.json

_👋 Hi, Chrome DevRel here_
Firefox 120 will ship with `light-dark()` support. This PR adds it.
Relevant links:
- Spec: https://drafts.csswg.org/css-color-5/#light-dark
- Chromium/Blink: https://bugs.chromium.org/p/chromium/issues/detail?id=1490618
- Firefox/Gecko: https://bugzilla.mozilla.org/show_bug.cgi?id=1856999
- Safari/WebKit: https://bugs.webkit.org/show_bug.cgi?id=262914
- Blog article with more info: https://www.bram.us/2023/10/09/the-future-of-css-easy-light-dark-mode-color-switching-with-light-dark/

Add light-dark()

---

css/at-rules/font-face.json
css/at-rules/supports.json

I added the Safari support for the tech function in font-face, as well as the related @support rule.
Added in safari 17: https://developer.apple.com/documentation/safari-release-notes/safari-17-release-notes#CSS

Update safari font tech() support

---

api/HTMLElement.json
css/selectors/backdrop.json
css/selectors/popover-open.json

Fixes Safari support data for various aspects of the Popover API. Now correctly marked as 17 not preview.
I've manually tested the `:popover-open` pseuedo class the return_boolean of togglePopover().
I'm assuming these are all just oversights when Safari 17 data was originally added.

Fix Safari data for popover APIs

---

api/DeviceMotionEvent.json

This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `DeviceMotionEvent` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.2.8).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/DeviceMotionEvent

Update Safari data for DeviceMotionEvent API

---

api/DeviceOrientationEvent.json

This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `DeviceOrientationEvent` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.2.8).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/DeviceOrientationEvent

Update Safari data for DeviceOrientationEvent API

---

api/VideoColorSpace.json

This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `VideoColorSpace` member of the `VideoColorSpace` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.2.8).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/VideoColorSpace/VideoColorSpace

Update Safari data for api.VideoColorSpace.VideoColorSpace

---

html/elements/script.json

This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `referrerpolicy` member of the `script` HTML element. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.2.5).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/html/elements/script/referrerpolicy

Update Safari data for html.elements.script.referrerpolicy

---

html/elements/link.json

This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `title` member of the `link` HTML element. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.2.5).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/html/elements/link/title

Update Safari data for html.elements.link.title

---

api/BeforeUnloadEvent.json
api/Window.json

https://github.com/mdn/browser-compat-data/pull/20942 added Chrome data changes for the [`beforeunload` event](https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeunload_event) (see https://chromestatus.com/feature/4968823574233088).
However, the aforementioned PR had to be reverted because the data included some HTML syntax characters in the note strings that would have caused rendering issues.
This PR resubmits the same changes but with the above issue fixed.

re-add Chrome beforeunload changes

---

api/Element.json
api/Permissions.json
api/ScreenDetailed.json
api/ScreenDetails.json

PR https://github.com/mdn/browser-compat-data/pull/20600 added support data for [Window Management API](https://w3c.github.io/window-management/) support in Chrome (see [ChromeStatus entry](https://chromestatus.com/feature/5252960583942144)). However, @michaelwasserman informs me that this API is not supported in Chrome Mobile.
This PR aims to rectify this mistake.

Window Management API features not supported in Chrome Mobile

---

GOVERNANCE.md

This PR marks Chris as a peer for BCD as nominated by three BCD owners (Florian, Philip and myself) during the BCD call today.

Mark Chris as a BCD peer

---

html/elements/html.json

This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `manifest` member of the `html` HTML element. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.2.5).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/html/elements/html/manifest

Update Safari data for html.elements.html.manifest

---

html/elements/rtc.json

This PR updates and corrects version values for Chrome and Safari for the `rtc` HTML element. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.2.5).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/html/elements/rtc

Update Chrome/Safari data for rtc HTML element

---

html/elements/source.json

This PR updates and corrects version values for Microsoft Edge for the `height` member of the `source` HTML element. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.2.5).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/html/elements/source/height

Update Edge data for html.elements.source.height

---

css/properties/font-variant.json

All versions of Internet Explorer only support the pre-CSS Fonts Module Level 3 syntax, meaning that it only recognises the `small-caps` and `normal` keywords. 
This is a stark difference compared to the other browsers listed, and non-obvious unless you know to cross-reference with the `font-variant` shorthand compat data and what the functional differences are between `font-variant` and `font-variant` (but shorthand). 
Although IE compat data is no longer actively maintained, flagging this difference (in an albeit high-level, not particularly nuanced way) could help avoid misunderstandings about IE's support for this property.
* IE 11 devtools only lists `small-caps` and `normal` keywords for autocompletion for `font-variant`. 
* No other `font-variant` values work in IE 11 or IE 10. (I …

Add note to IE support for `font-variant` CSS property

---

http/headers/Cross-Origin-Resource-Policy.json

This PR updates and corrects version values for Opera and Opera Android for the `Cross-Origin-Resource-Policy` HTTP header. This simply sets Opera to mirror.  This supersedes and closes #20643.

Update Opera data for Cross-Origin-Resource-Policy HTTP header

---

html/elements/col.json

This PR updates and corrects version values for Firefox and Firefox Android for the `col` HTML element. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.2.5).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/html/elements/col

Update Firefox data for col HTML element

---

css/properties/font-synthesis-small-caps.json

This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `font-synthesis-small-caps` CSS property. This removes a "resolved fixed" bug link in notes for the feature.
Additional Notes: 

Update Safari data for font-synthesis-small-caps CSS property

---

javascript/builtins/ArrayBuffer.json
javascript/builtins/SharedArrayBuffer.json

Will unblock https://github.com/mdn/browser-compat-data/pull/20459

Features for resizablearraybuffer are merged into main ECMA spec

---

api/Navigator.json
api/WorkerNavigator.json
http/headers/Sec-GPC.json

@hamishwillee was right all along in https://github.com/mdn/browser-compat-data/pull/20730. The GPC spec is still a pending spec.
BCD doesn't test for a 'good' spec standing yet, but it will do so once https://github.com/mdn/browser-compat-data/pull/20459 is merged. This PR blocks https://github.com/mdn/browser-compat-data/pull/20459 from passing.

GPC is still a pending spec

---

api/SubtleCrypto.json

FF119 allows [`SubtleCrypto.deriveKey()`](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/deriveKey) to support  HKDF as a `derivedKeyAlgorithm` in https://bugzilla.mozilla.org/show_bug.cgi?id=1851928
I have not fully tested all the support options, as even the engineer I asked wasn't sure what tests map to what features in http://wpt.live/WebCryptoAPI/derive_bits_keys/. However it was stated that this is supported in Chrome. What I have done is mapped the version here to the same as the parent for other browsers. Then checked where possible - e.g. I can find that in deno this is supported in that first version https://deno.land/api@v1.37.1?s=SubtleCrypto#method_deriveKey_13.
EDIT
There are at least 4 possible algorithms to `derivedKeyAlgorithm`: HMAC, PBKDF2, HKDF, and AES. …

FF119 SubtleCrypto.deriveKey() supports HKDF as a derivedKeyAlgorith option

---

html/elements/area.json

This PR removes the `name` member of the `area` HTML element from BCD. Per the [data guidelines](https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines/index.md#removal-of-irrelevant-features), this feature can be considered irrelevant and may be removed from BCD accordingly. Even if the current data suggests that the feature is supported, lack of support has been confirmed by the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.2.1).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/html/elements/area/name

Remove html.elements.area.name from BCD

---

html/elements/area.json

This PR removes the `hreflang` member of the `area` HTML element from BCD. Per the [data guidelines](https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines/index.md#removal-of-irrelevant-features), this feature can be considered irrelevant and may be removed from BCD accordingly. Even if the current data suggests that the feature is supported, lack of support has been confirmed by the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.2.1).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/html/elements/area/hreflang

Remove html.elements.area.hreflang from BCD

---

api/CSSStyleRule.json

This PR updates and corrects version values for Firefox and Firefox Android for the `CSSStyleRule` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.2.8).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/CSSStyleRule

Update Firefox data for CSSStyleRule API

---

api/HTMLInputElement.json

Correct safari data for input.showPicker()
Safari desktop supports file and color inputs. Safari for iOS supports file inputs.
Tested manually, using https://demo.lukewarlow.dev/showPicker/
I've been working on implementing the rest along with iOS support and will file follow ups to correct the data once they ship.

Correct safari data for input.showPicker()

---

api/Document.json

This PR is a part of a project to add missing interfaces and interface features to BCD that are from an active spec (including WICG specs) and is supported in at least one browser. This particular PR adds the missing `hasRedemptionRecord` member of the `Document` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.2.9).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/Document/hasRedemptionRecord

Add missing features for api.Document.hasRedemptionRecord

---

api/Navigator.json

This PR is a part of a project to add missing interfaces and interface features to BCD that are from an active spec (including WICG specs) and is supported in at least one browser. This particular PR adds the missing `audioSession` member of the `Navigator` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.2.9).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/Navigator/audioSession

Add missing api.Navigator.audioSession feature

---

api/NavigateEvent.json

This PR is a part of a project to add missing interfaces and interface features to BCD that are from an active spec (including WICG specs) and is supported in at least one browser. This particular PR adds the missing `hasUAVisualTransition` member of the `NavigateEvent` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.2.9).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/NavigateEvent/hasUAVisualTransition
Additional Notes: api.NavigateEvent.hasUAVisualTransition

Add missing api.NavigateEvent.hasUAVisualTransition feature

---

api/PopStateEvent.json

This PR is a part of a project to add missing interfaces and interface features to BCD that are from an active spec (including WICG specs) and is supported in at least one browser. This particular PR adds the missing `hasUAVisualTransition` member of the `PopStateEvent` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.2.9).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/PopStateEvent/hasUAVisualTransition

Add missing api.PopStateEvent.hasUAVisualTransition feature

---

api/HTMLIFrameElement.json

This PR is a part of a project to add missing interfaces and interface features to BCD that are from an active spec (including WICG specs) and is supported in at least one browser. This particular PR adds the missing `privateToken` member of the `HTMLIFrameElement` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.2.9).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/HTMLIFrameElement/privateToken

Add missing api.HTMLIFrameElement.privateToken feature

---

api/CSSScopeRule.json

This PR is a part of a project to add missing interfaces and interface features to BCD that are from an active spec (including WICG specs) and is supported in at least one browser. This particular PR adds the missing `CSSScopeRule` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.2.9).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/CSSScopeRule

Add missing CSSScopeRule API feature

---

api/Selection.json

This PR is a part of a project to add missing interfaces and interface features to BCD that are from an active spec (including WICG specs) and is supported in at least one browser. This particular PR adds the missing features of the `Selection` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.2.9).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/Selection

Add missing features for Selection API

---

api/XMLHttpRequest.json

This PR is a part of a project to add missing interfaces and interface features to BCD that are from an active spec (including WICG specs) and is supported in at least one browser. This particular PR adds the missing `XMLHttpRequest` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.2.9).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/XMLHttpRequest

Add missing XMLHttpRequest API feature

---

javascript/builtins/Intl/Locale.json

This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `Locale` member of the `Intl` JavaScript builtin. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.2.9).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/javascript/builtins/Intl/Locale

Update Safari data for javascript.builtins.Intl.Locale

---

api/SVGImageElement.json

This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `crossOrigin` member of the `SVGImageElement` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.2.9).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/SVGImageElement/crossOrigin

Update Chromium data for api.SVGImageElement.crossOrigin

---

api/_globals/createImageBitmap.json

This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `createImageBitmap` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.2.9).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/createImageBitmap
Additional Notes: Safari 15 was guesstimated as I do not have access to Safari 15.0, only 14.1 and 15.1.

Update Safari data for createImageBitmap API

---

css/properties/offset-anchor.json

This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `offset-anchor` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.2.9).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/offset-anchor

Update Safari data for offset-anchor CSS property

---

css/properties/offset-distance.json

This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `offset-distance` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.2.9).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/offset-distance

Update Safari data for offset-distance CSS property

---

css/properties/offset-position.json

This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `offset-position` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.2.9).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/offset-position

Update Safari data for offset-position CSS property

---

css/properties/offset-rotate.json

This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `offset-rotate` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.2.9).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/offset-rotate

Update Safari data for offset-rotate CSS property

---

api/Window.json

This PR corrects the changes made to the `beforeunload` event of the Window API, following #20964.
CC @chrisdavidmills

Correct data for Window.beforeunload_event

---

css/properties/text-emphasis-position.json

This PR is a part of a project to add missing interfaces and interface features to BCD that are from an active spec (including WICG specs) and is supported in at least one browser. This particular PR adds the missing features of the `text-emphasis-position` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.2.9).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/text-emphasis-position

Add missing features for text-emphasis-position CSS property

---

test/linter/test-spec-urls.ts
webassembly/relaxed-SIMD.json

This PR is a part of a project to add missing interfaces and interface features to BCD that are from an active spec (including WICG specs) and is supported in at least one browser. This particular PR adds the missing `webassemblyrelaxed-SIMD` feature. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.2.9).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/webassembly/relaxed-SIMD

Add missing webassemblyrelaxed-SIMD feature feature

---

css/properties/transform-box.json

This PR is a part of a project to add missing interfaces and interface features to BCD that are from an active spec (including WICG specs) and is supported in at least one browser. This particular PR adds the missing features of the `transform-box` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.2.9).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/transform-box

Add missing features for transform-box CSS property

---

api/Response.json

This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `json_static` member of the `Response` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.2.10).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/Response/json_static

Update Safari data for api.Response.json_static

---

scripts/update-browser-releases/firefox.ts
scripts/update-browser-releases/index.ts

This PR extends the `update-browser-releases` script to support Firefox browser.
Manually tested.
It added the following entries.
Note that it does support Firefox for Android too (on the same schedule than Firefox for Desktop)

Add script to update Firefox release info

---

scripts/update-browser-releases/firefox.ts

This PR fixes a TypeScript typedef issue in the Firefox browser update script, which is causing an issue with the mdn-bcd-collector (see https://github.com/openwebdocs/mdn-bcd-collector/actions/runs/6586954756/job/17896302875).
This will be self-merged as it is a critical bug fix.

Fix TypeScript issue in Firefox browser update script

---

javascript/builtins/WebAssembly/Exception.json

This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `Exception.stack` member of the `WebAssembly` JavaScript builtin. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.2.10).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/javascript/builtins/WebAssembly/Exception/stack
Additional Notes: This was set to Safari 15.2 in #15954, but I have not been able to confirm support.

Update Safari data for javascript.builtins.WebAssembly.Exception.stack

---

html/elements/iframe.json

This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `referrerpolicy` member of the `iframe` HTML element. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.2.10).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/html/elements/iframe/referrerpolicy
Additional Notes: This also mirrors the data to match api.HTMLIFrameElement.referrerPolicy.

Update Safari data for html.elements.iframe.referrerpolicy

---

html/elements/img.json

This PR updates and corrects version values for Chrome and Safari for the `onerror` member of the `img` HTML element. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.2.10).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/html/elements/img/onerror

Update Chrome/Safari data for html.elements.img.onerror

---

html/elements/form.json

This PR updates and corrects version values for all browsers for the `autocapitalize` member of the `form` HTML element. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.2.10).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/html/elements/form/autocapitalize

Update all browsers data for html.elements.form.autocapitalize

---

scripts/update-browser-releases/chrome.ts
scripts/update-browser-releases/firefox.ts
scripts/update-browser-releases/index.ts

There is a specificity in firefox.json. The latest ESR version is not tagged 'retired' but 'esr'. This fixes this problem. Note that if the current version is the ESR version, no entry is tagged 'esr'.
This PR also add a final CR at the end of the firefox.json and chrome.json files (also for android and webview), so that the files get closer to the manually edited ones in the past.
The only difference between files generated by the update script and manually edited ones is the ordering of the versions (lexicographic order vs "mathematical" order).
This will be fixed in a follow-up PR once the decision on the order has been taken.
Manually tested.

Add support for 'esr' in update script for firefox[_android].json

---

webextensions/api/tabs.json

This removes the nesting of `createProperties` object parameters to display the compatibility data documentation in the `tabs.create` API.
Fixes #20969

Remove unneeded `createProperties` object to display compat data

---

webextensions/api/runtime.json

Fixes https://github.com/mdn/content/issues/12041 by adding documentation for `origin` and `nativeApplication` properties and also capturing the more recently added `documentId` and `documentLifecycle`. Also completes the set of documented properties by adding `id` and `tab`.
Complementary content update in https://github.com/mdn/content/pull/29672.

Add missing and new chrome properties to runtime.MessageSender

---

webextensions/manifest/content_security_policy.json

Support for the `content_security_policy` manifest key is platform-independent, and support should be mirrored (i.e. supported) instead of marked as unsupported.
Some relevant Firefox-side unit tests (note that these tests are not skipped on Android): https://searchfox.org/mozilla-central/rev/10d0e01455559a433670bd718a3ecc0ece5d2cb9/toolkit/components/extensions/test/xpcshell/test_ext_content_security_policy.js and https://searchfox.org/mozilla-central/rev/10d0e01455559a433670bd718a3ecc0ece5d2cb9/toolkit/components/extensions/test/xpcshell/test_ext_wasm.js
The mistake was introduced in https://github.com/mdn/browser-compat-data/pull/5325/commits/2fd95ae8e7e5820aec7602a1b8d9f61f4f4007a1.

content_security_policy: support firefox_android

---

scripts/update-browser-releases/chrome.ts
scripts/update-browser-releases/edge.ts
scripts/update-browser-releases/firefox.ts
scripts/update-browser-releases/index.ts
scripts/update-browser-releases/utils.ts

The logs of `update-browser-versions` now:
- indicates the changes that have been made
- are colorful
- are compatible with MD.
This output will be used in the future PR that will be generated.
It also set up `sortStringify()` for Edge (no effect, but it guarantees the same order in the future.
In the shell:
Integrated inside a PR:
None

Improve logs for update-browser-versions

---

api/AuthenticatorAttestationResponse.json
api/Element.json
api/PublicKeyCredential.json

I've run the collector for the Firefox 119 release.
This PR sets the following features as shipping in 119:
- api.AuthenticatorAttestationResponse.getTransports (confirmed by https://bugzilla.mozilla.org/show_bug.cgi?id=1536155)
- api.ElementInternals.role (oversight in https://github.com/mdn/browser-compat-data/pull/20911?)
- api.PublicKeyCredential.isConditionalMediationAvailable_static (confirmed by https://bugzilla.mozilla.org/show_bug.cgi?id=1813778)
The following features are already marked as shipping in Firefox 119 in BCD:
- api.AuthenticatorAttestationResponse.getAuthenticatorData
- api.AuthenticatorAttestationResponse.getPublicKey
- api.AuthenticatorAttestationResponse.getPublicKeyAlgorithm
- api.CredentialsContainer.create.publicKey_option.extensions.credProps
- …

Collector results for Firefox 119

---

.github/workflows/update-browser-version.yml

This PR adds a workflow to run `update-browser-releases.ts` that updates Chrome, Firefox, and Edge JSON files containing version numbers and release dates.
Note: the workflow will run only on-demand now; we want to gather experience before adding a cron entry.
Note 2: I'm using GITHUB_TOKEN as the secret for the privileges. I have no access to the secrets on bcd, so I couldn't double check if it has the correct privileges (especially creation and modifications of PRs).
If not, the workflow will fail at the PR-creation step (but no havoc will be done). If this is the case, somebody with the proper privileges must add a secret with an adequate access token. Then we can use it (1 line change). There are already such secrets in use on bcd for other workflows.
@ddbeck @queengooborg, @caugner, …

Add workflow to run (on demand) the update-browser-releases script

---

api/Sanitizer.json

This PR updates and corrects version values for Opera and Opera Android for the `sanitize` member of the `Sanitizer` API. This sets the feature to mirror from Chrome, which unblocks #21080.

Update Opera data for api.Sanitizer.sanitize

---

.github/workflows/update-browser-releases.yml
.github/workflows/update-browser-version.yml

This PR fixes (well, _should_ fix) the new `update-browser-version.yml` workflow introduced in #21090 by adding pull request write permissions.  CC @teoli2003 @Elchi3

Fix update-browser-version.yml

---

html/elements/script.json

The speculation rules data was added by @chrisdavidmills in https://github.com/mdn/browser-compat-data/pull/20742 with a specific note that prefetch was added later. That's fine and correct but given we have a separate `prefetch` key we should also have a `prerender` key with the earlier versions to make this super clear.
https://chromestatus.com/feature/5355965538893824
https://chromestatus.com/feature/4899735257743360
https://github.com/mdn/browser-compat-data/pull/20742

Add speculation rules prerender key

---

webextensions/manifest/background.json

This PR updates and corrects version values for Microsoft Edge for the `persistent` member of the `background` Web Extensions manifest property. This fixes #12702.

Update Edge data for webextensions.manifest.background.persistent

---

webextensions/manifest/author.json

This PR corrects the requirement note for Microsoft Edge for the `author` property of webExtension manifest files.
Fixes https://github.com/mdn/browser-compat-data/issues/21101

Update Edge data for webextensions.manifest.author

---

schemas/browsers.schema.json
scripts/fix/index.ts
scripts/fix/property-order.ts
scripts/lib/stringify-and-order-properties.ts
scripts/update-browser-releases/chrome.ts
scripts/update-browser-releases/edge.ts
scripts/update-browser-releases/firefox.ts
scripts/update-browser-releases/utils.ts
test/linter/test-style.ts
test/utils.ts

This PR updates the property order enforcement so that it performs the following:
- Enforces property order within browser data
- The `sortStringify` function from the `update-browser-releases` script was taken and spliced in to enforce proper release sorting
- In turn, the `update-browser-releases` script were updated to use the new function
- Enforces property order for individual compatibility statements
This enforces the ordering performed in #21094.

Update property order enforcement

---

api/WebGLTimerQueryEXT.json

This PR is a part of a project to add missing interfaces and interface features to BCD that are from an active spec (including WICG specs) and is supported in at least one browser. This particular PR adds the missing `WebGLTimerQueryEXT` API. Support was confirmed with the mdn-bcd-collector projcet (v10.2.10) and was copied from api.EXT_disjoint_timer_query.createQueryEXT.

Add missing WebGLTimerQueryEXT API feature

---

api/CanvasCaptureMediaStreamTrack.json

This PR updates and corrects version values for Firefox and Firefox Android for the `CanvasCaptureMediaStreamTrack` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.2.10).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/CanvasCaptureMediaStreamTrack
Additional Notes: Until the most recent collector release, the test didn't check if the result was a CanvasCaptureMediaStreamTrack or a regular MediaStreamTrack.  CanvasCaptureMediaStreamTrack is not defined in Firefox IDL.  This fixes #20784.

Update Firefox data for CanvasCaptureMediaStreamTrack API

---

api/FontFaceSet.json

Safari does not emit FontFace loading events as of 2023-10-20 (Safari 16.6)
* Incorrect resource: https://caniuse.com/mdn-api_fontfaceset_loadingdone_event
* WebKit Issue: https://bugs.webkit.org/show_bug.cgi?id=154626
* Repro: https://codepen.io/alexkrolick/pen/QWYLRYE?editors=1001
```js
document.fonts.addEventListener("loading", (event) => {
console.log('loading', event) // never logged in Safari
});
```

FontFace loading events are not implemented in Safari

---

css/properties/-webkit-line-clamp.json

This PR is a part of a project to add missing interfaces and interface features to BCD that are from an active spec (including WICG specs) and is supported in at least one browser. This particular PR adds the missing `none` member of the `-webkit-line-clamp` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.2.9).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/-webkit-line-clamp/none

Add missing css.properties.-webkit-line-clamp.none feature

---

css/properties/clip-rule.json

This PR is a part of a project to add missing interfaces and interface features to BCD that are from an active spec (including WICG specs) and is supported in at least one browser. This particular PR adds the missing `clip-rule` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.2.10).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/clip-rule

Add missing clip-rule CSS property feature

---

css/properties/offset-path.json

This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `offset-path` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.2.10).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/offset-path
Additional Notes: I don't actually have access to Safari 15.2-16.0 right now, so 15.4 is guesstimated.

Update Safari data for offset-path CSS property

---

api/AnimationEvent.json
api/CSSKeyframeRule.json
api/CSSKeyframesRule.json
api/Gamepad.json
api/NamedNodeMap.json
api/ScreenOrientation.json
css/properties/background-attachment.json
css/properties/flex-direction.json
css/properties/mask.json
css/properties/scroll-snap-type.json
scripts/lib/compare-statements.test.ts
scripts/lib/compare-statements.ts
test/linter/test-style.ts

This PR updates the statement comparison lib to improve statement order.  The statement comparison now performs the following:
- Statements with `version_removed` are compared against each other in reverse chronological order, regardless of other factors
- If both statements have the same `version_removed`, other factors like prefixes and partial support will be considered
- Statements with partial implementation are now sorted underneath features with prefixes/alt. names, as it was intended to be

Update statement comparison for better readability and fixed sorting

---

html/elements/pre.json

This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `wrap` member of the `pre` HTML element. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.2.5).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/html/elements/pre/wrap

Update Safari data for html.elements.pre.wrap

---

api/RGBColor.json

This PR is a part of a project to add missing interfaces and interface features to BCD that are from an active spec (including WICG specs) and is supported in at least one browser. This particular PR adds the missing `RGBColor` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.2.10).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/RGBColor
Additional Notes: The data was copied from api.CSSPrimitiveValue.getRGBColorValue (see https://www.w3.org/TR/DOM-Level-2-Style/css.html#CSS-CSSPrimitiveValue-getRGBColorValue).

Add missing RGBColor API feature

---

api/Counter.json

This PR is a part of a project to add missing interfaces and interface features to BCD that are from an active spec (including WICG specs) and is supported in at least one browser. This particular PR adds the missing `Counter` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.2.10).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/Counter
Additional Notes: The data was copied from api.CSSPrimitiveValue.getCounterValue (see https://www.w3.org/TR/DOM-Level-2-Style/css.html#CSS-CSSPrimitiveValue-getCounterValue).

Add missing Counter API feature

---

api/Rect.json

This PR is a part of a project to add missing interfaces and interface features to BCD that are from an active spec (including WICG specs) and is supported in at least one browser. This particular PR adds the missing `Rect` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.2.10).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/Rect
Additional Notes: The data was copied from api.CSSPrimitiveValue.getRectValue (see https://www.w3.org/TR/DOM-Level-2-Style/css.html#CSS-CSSPrimitiveValue-getRectValue).

Add missing Rect API feature

---

api/MediaController.json

This PR is a part of a project to add missing interfaces and interface features to BCD that are from an active spec (including WICG specs) and is supported in at least one browser. This particular PR adds the missing `MediaController` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.2.10).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/MediaController
Additional Notes: While the feature was removed from the spec (see https://github.com/whatwg/html/pull/1225), we still currently document HTMLMediaElement.controller, which returns this interface, so I figured it would be sensible to add this to …

Add missing MediaController API feature

---

css/properties/font-variant.json

This PR is a part of a project to add missing interfaces and interface features to BCD that are from an active spec (including WICG specs) and is supported in at least one browser. This particular PR adds the missing features of the `font-variant` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.2.9).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/font-variant

Add missing features for font-variant CSS property

---

api/CredentialsContainer.json

FF120 supports the [minPinLength](https://developer.mozilla.org/en-US/docs/Web/API/Web_Authentication_API/WebAuthn_extensions#minpinlength) WebAuth extension in https://bugzilla.mozilla.org/show_bug.cgi?id=1844450.
This adds the version and MDN URL linking to existing docs. I didn't update the experimental flag to `false` as was (incorrectly) already set that way.
Related docs work can be tracked in https://github.com/mdn/content/issues/29783

FF120 CredentialsContainer.minPinLength extension

---

css/properties/block-size.json
css/properties/height.json
css/properties/inline-size.json
css/properties/max-block-size.json
css/properties/max-height.json
css/properties/max-inline-size.json
css/properties/max-width.json
css/properties/min-block-size.json
css/properties/min-height.json
css/properties/min-inline-size.json
css/properties/min-width.json
css/properties/width.json

- related to https://github.com/mdn/content/pull/29849
The PR adds new sizing values specs to the size properties.

fix(css): add 'fit-content' value spec to size properties

---

scripts/update-browser-releases/edge.ts
scripts/update-browser-releases/index.ts

After some time, Microsoft moved Edge release notes to an archive page.
This PR:
- detect that this move happened, and update the edge.json file accordingly
- make sure the release note page and the archived one are read only once.
Manually tested:

Handle archiving Edge release notes

---

.github/workflows/update-browser-releases.yml

We have been using `update-browser-releases` for some time, using the dispatch event.
This PR adds a schedule entry for 4.30am every weekday (UTC). This is 5.30am CET in winter and 6.30am CEST in summer (Europe).
GitHub doesn't guarantee a precise running time, but most of the time, it runs within 30 minutes from the scheduled time.
That way, we have it running every week day before 7am (Central Europe).
I tested it on the teoli2003 repo at 12.00pm, and it worked: it ran at 1.38pm (UTC+1, CET)

Add a cron entry to run automatically update-browser-releases

---

css/properties/zoom.json

Nightly for 120 enables CSS `zoom` property by flipping the pref `layout.css.zoom.enabled` to `true` for Nightly only by default.
Additionally, the `-moz-transform` prop is disabled in Nightly, not making additions here as this is likely going to be removed altogether. The non-prefixed `transform` prop is supported since Fx 16. There's already [a redirect from `-moz-transform` to `transform`](https://github.com/mdn/content/blame/main/files/en-us/_redirects.txt#L307).
__Revision:__
- https://hg.mozilla.org/integration/autoland/rev/facd9f92e1f5
__Bugzilla:__
- https://bugzilla.mozilla.org/show_bug.cgi?id=1855763
- https://bugzilla.mozilla.org/show_bug.cgi?id=390936

relnote(120): Fx nightly enables CSS zoom property by default

---

api/HTMLIFrameElement.json
html/elements/iframe.json

FF120 supports lazy loading of iframes in preview in https://bugzilla.mozilla.org/show_bug.cgi?id=1622090 (with expectation it will be supported by default in 121).
This updates the `loading` attribute in iframe tag and HTML element.
Related work can be tracked in https://github.com/mdn/content/issues/29780

FF120 iframe support lazy loading in nightly

---

css/properties/content-visibility.json

I'm not sure this is right, but the [presently linked specification](https://drafts.csswg.org/css-display-4/#display-animation) says nothing about `content-visibility`, only `display` and `visibility`. Meanwhile, CSS Containment Module Level 3 [does cover the animation of `content-visibility`](https://drafts.csswg.org/css-contain-3/#content-visibility-animation) (it was [previously specified as not animatable](https://drafts.csswg.org/css-contain-2/#content-visibility)).
That said, it's possible that the original author of this data intended for the subfeature to cover something else. Perhaps @chrisdavidmills could review this change?
This is a follow-up to changes made in https://github.com/mdn/browser-compat-data/pull/20671. 
Prompted by a review on …

Point content-visibility animation spec to css-contain-3

---

api/HTMLInputElement.json

Add Safari Tech preview support for input.showPicker() on the date and datetime-local inputs.
STP 182 docs: https://webkit.org/blog/14764/release-notes-for-safari-technology-preview-182/#:~:text=Added%20support%20for%20the%20showPicker()%20method%20for%20%3Cinput%20type%3D%22date%22%3E.
It says just date but it actually works on both date and datetime-local (I implemented this and verified in tech preview using https://demo.lukewarlow.dev/showPicker/)

Add Safari preview support for date showPicker()

---

api/Window.json

In the `Window.open()` BCD, there is an entry for "One `Window.open()` call per event". In other words, not only do browsers require a user gesture for `Window.open()` calls, they are also limited to one per event handler function by default, unless the user changes the browser settings. Any calls after the first one are blocked.
Safari's support for this was listed as `false`, but this isn't right. You can test this using my [simple test case](https://jsfiddle.net/chrisdavidmills/dry1k0q6/3/).
Historic Safari release notes seem hard to find, but looking at this [SO post](https://stackoverflow.com/questions/46381681/open-multiple-pop-up-windows-in-safari-11), it looks like it was introduced in Safari 11. Note that this page mentions Safari allowing multiple calls per event if you put a …

Correct Safari data for  window.open() one call per event behavior

---

javascript/builtins/Intl/DateTimeFormat.json

Source for:
Chrome 80 https://chromestatus.com/feature/5440249461211136
Firefox 76 https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/76 
NodeJs 14.0.0 https://raw.githubusercontent.com/nodejs/node/main/doc/changelogs/CHANGELOG_V14.md 
Safari 14 : supported added to Safari preview 105 https://webkit.org/blog/10428/release-notes-for-safari-technology-preview-105/, before cut for Safari 14 https://developer.apple.com/documentation/safari-release-notes/safari-14-release-notes

Add compatibility for `Intl.DateTimeFormatOptions.calendar` and `numberingSystem`

---

scripts/update-browser-releases/edge.ts

The Edge Stable version is released before the new Edge Beta version. During a few days, there is no Edge Beta version.
Manually tested:

Skip beta version if not yet released for edge.json

---

webextensions/api/runtime.json

Add a note to Firefox for Android clarifying that `connectNative` and `sendNativeMessage` are supported, but only in GeckoView.
I spoke with Firefox engineers about this issue and they confirmed the currently published information is inaccurate/incomplete. 
Messaging support for GeckoView was introduced in v68.
> Added messaging support for WebExtension. [setMessageDelegate](https://mozilla.github.io/geckoview/javadoc/mozilla-central/org/mozilla/geckoview/WebExtension.html#setMessageDelegate(org.mozilla.geckoview.WebExtension.MessageDelegate,java.lang.String)) allows embedders to listen to messages coming from a WebExtension. [Port](https://mozilla.github.io/geckoview/javadoc/mozilla-central/org/mozilla/geckoview/WebExtension.Port.html) allows bidirectional communication between the …

Clarifies native message support on Android

---

api/Screen.json
api/Window.json

The [Window Management API](https://w3c.github.io/window-management/) was implemented in Chrome 100 (see [ChromeStatus entry](https://chromestatus.com/feature/5252960583942144)). I originally submitted BCD updates for this in https://github.com/mdn/browser-compat-data/pull/20600.
However, during the tech review of my [docs additions for this API](https://github.com/mdn/content/pull/29719), I added some details of how the multi-screen origin concept introduced with this API affects the behavior of some existing related features. This was done on the instruction of the tech reviewer, @michaelwasserman.
In his editorial review, @wbamberg then rightly pointed out that this information belongs in the BCD. This PR adds the relevant information to BCD. The general pattern is:
* Chromium supports …

Add details of multi-screen origin support to relevant features

---

api/HTMLMediaElement.json
http/headers/Cache-Control.json

This PR converts a few notes that only have a bug URL into the `impl_url` property.

Convert basic bug links in notes to impl_url

---

css/properties/color-adjust.json

This PR is a part of a project to add missing interfaces and interface features to BCD that are from an active spec (including WICG specs) and is supported in at least one browser. This particular PR adds the missing `color-adjust` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.2.10).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/color-adjust

Add missing color-adjust CSS property feature

---

html/elements/source.json

This PR adds notes to indicate the evolution of support for `media` attribute in `<source>` element:
- `media` was initially supported in Firefox 15.
- In Firefox 53, its support was restricted to `<source>` elements with a `<picture>` parent.
- Now, with Firefox 120, the attribute is supported when `<source>` is a child of either `<audio>`, `<video>`, or `<picture>`, that is back to how it was originally implemented.
https://github.com/mdn/browser-compat-data/pull/21083
Doc issue tracker: https://github.com/mdn/content/issues/29788

Firefox 120: Add notes for `media` support in `<support>` across firefox releases

---

api/HTMLVideoElement.json

This PR updates and corrects version values for Firefox and Firefox Android for the `disablePictureInPicture` member of the `HTMLVideoElement` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.2.10).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/HTMLVideoElement/disablePictureInPicture
Additional Notes: This effectively reverts #20839.  While the flag mentioned in that PR is indeed enabled by default, the property is not (properly) defined in the WebIDL.

Update Firefox data for api.HTMLVideoElement.disablePictureInPicture

---

scripts/diff-features.ts
scripts/lib/stringify-and-order-properties.ts
test/utils.ts

This PR fixes ESLint's warnings related to the JSDoc comments.

Fix JSDoc warnings

---

api/AudioTrack.json

This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `AudioTrack` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.3.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/AudioTrack

Update Safari data for AudioTrack API

---

api/VideoTrack.json

This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `VideoTrack` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.3.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/VideoTrack

Update Safari data for VideoTrack API

---

css/properties/backface-visibility.json
css/properties/perspective-origin.json
css/properties/perspective.json
css/properties/transform-origin.json
css/properties/transform-style.json
css/properties/transform.json
css/properties/transition-delay.json
css/properties/transition-duration.json
css/properties/transition-property.json
css/properties/transition-timing-function.json
css/properties/transition.json

All of these vendor-prefixed props are removed in Nightly 120:
- `-moz-backface-visibility`
- `-moz-perspective-origin`
- `-moz-perspective`
- `-moz-transform-origin`
- `-moz-transform-style`
- `-moz-transform`
- `-moz-transition-delay`
- `-moz-transition-duration`
- `-moz-transition-property`
- `-moz-transition-timing-function`
- `-moz-transition`
See https://github.com/mdn/content/issues/29785

relnote(120): Mark prefixed transition and transform props as removed in Nightly

---

css/properties/grid-gap.json

This PR is a part of a project to add missing interfaces and interface features to BCD that are from an active spec (including WICG specs) and is supported in at least one browser. This particular PR adds the missing `grid-gap` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.2.10).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/grid-gap

Add missing grid-gap CSS property feature

---

css/properties/grid-column-gap.json

This PR is a part of a project to add missing interfaces and interface features to BCD that are from an active spec (including WICG specs) and is supported in at least one browser. This particular PR adds the missing `grid-column-gap` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.2.10).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/grid-column-gap

Add missing grid-column-gap CSS property feature

---

css/properties/grid-row-gap.json

This PR is a part of a project to add missing interfaces and interface features to BCD that are from an active spec (including WICG specs) and is supported in at least one browser. This particular PR adds the missing `grid-row-gap` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.2.10).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/grid-row-gap

Add missing grid-row-gap CSS property feature

---

css/properties/speak.json

This PR is a part of a project to add missing interfaces and interface features to BCD that are from an active spec (including WICG specs) and is supported in at least one browser. This particular PR adds the missing `speak` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.2.10).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/speak

Add missing speak CSS property feature

---

css/properties/lighting-color.json

This PR is a part of a project to add missing interfaces and interface features to BCD that are from an active spec (including WICG specs) and is supported in at least one browser. This particular PR adds the missing `lighting-color` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.2.10).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/lighting-color

Add missing lighting-color CSS property feature

---

css/properties/flood-opacity.json

This PR is a part of a project to add missing interfaces and interface features to BCD that are from an active spec (including WICG specs) and is supported in at least one browser. This particular PR adds the missing `flood-opacity` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.2.10).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/flood-opacity

Add missing flood-opacity CSS property feature

---

css/properties/flood-color.json

This PR is a part of a project to add missing interfaces and interface features to BCD that are from an active spec (including WICG specs) and is supported in at least one browser. This particular PR adds the missing `flood-color` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.2.10).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/flood-color

Add missing flood-color CSS property feature

---

css/selectors/host-context.json

This fixes the incorrect MDN URL for CSS `:host-context()`
If I understand correctly, this should fix the incorrect reference link on https://caniuse.com/?search=host-context
N/A

Fix CSS host-context mdn_url

---

css/properties/baseline-shift.json

This PR is a part of a project to add missing interfaces and interface features to BCD that are from an active spec (including WICG specs) and is supported in at least one browser. This particular PR adds the missing `baseline-shift` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.2.10).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/baseline-shift

Add missing baseline-shift CSS property feature

---

css/properties/alignment-baseline.json

This PR is a part of a project to add missing interfaces and interface features to BCD that are from an active spec (including WICG specs) and is supported in at least one browser. This particular PR adds the missing `alignment-baseline` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.2.10).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/alignment-baseline

Add missing alignment-baseline CSS property feature

---

css/properties/dominant-baseline.json

This PR is a part of a project to add missing interfaces and interface features to BCD that are from an active spec (including WICG specs) and is supported in at least one browser. This particular PR adds the missing `dominant-baseline` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.2.10).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/dominant-baseline

Add missing dominant-baseline CSS property feature

---

css/properties/break-inside.json

This PR is a part of a project to add missing interfaces and interface features to BCD that are from an active spec (including WICG specs) and is supported in at least one browser. This particular PR adds the missing features of the `break-inside` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.2.9).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/break-inside

Add missing features for break-inside CSS property

---

css/properties/color-interpolation.json
css/properties/cx.json
css/properties/cy.json
css/properties/d.json
css/properties/marker-end.json
css/properties/marker-mid.json
css/properties/marker-start.json
css/properties/marker.json
css/properties/r.json
css/properties/rx.json
css/properties/ry.json
css/properties/shape-rendering.json
css/properties/text-anchor.json
css/properties/vector-effect.json
css/properties/word-wrap.json
css/properties/x.json
css/properties/y.json

This PR adds missing CSS properties from the SVG 2.0 specification, using results from the mdn-bcd-collector project (v10.2.10).

Add missing CSS properties from SVG 2.0 spec

---

css/properties/stroke-color.json
css/properties/stroke-dasharray.json
css/properties/stroke-dashoffset.json
css/properties/stroke-linecap.json
css/properties/stroke-linejoin.json
css/properties/stroke-miterlimit.json
css/properties/stroke-opacity.json
css/properties/stroke-width.json
css/properties/stroke.json

This PR is a part of a project to add missing interfaces and interface features to BCD that are from an active spec (including WICG specs) and is supported in at least one browser. This particular PR adds the missing `stroke-*` CSS properties. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.2.10).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/stroke

Add missing stroke-* CSS property feature

---

css/properties/color-interpolation-filters.json

This PR is a part of a project to add missing interfaces and interface features to BCD that are from an active spec (including WICG specs) and is supported in at least one browser. This particular PR adds the missing `color-interpolation-filters` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.2.10).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/color-interpolation-filters

Add missing color-interpolation-filters CSS property feature

---

css/properties/fill.json

This PR is a part of a project to add missing interfaces and interface features to BCD that are from an active spec (including WICG specs) and is supported in at least one browser. This particular PR adds the missing `fill` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.2.10).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/fill

Add missing fill CSS property feature

---

css/properties/fill-rule.json

This PR is a part of a project to add missing interfaces and interface features to BCD that are from an active spec (including WICG specs) and is supported in at least one browser. This particular PR adds the missing `fill-rule` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.2.10).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/fill-rule

Add missing fill-rule CSS property feature

---

css/properties/fill-opacity.json

This PR is a part of a project to add missing interfaces and interface features to BCD that are from an active spec (including WICG specs) and is supported in at least one browser. This particular PR adds the missing `fill-opacity` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.2.10).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/fill-opacity

Add missing fill-opacity CSS property feature

---

css/properties/glyph-orientation-vertical.json

This PR is a part of a project to add missing interfaces and interface features to BCD that are from an active spec (including WICG specs) and is supported in at least one browser. This particular PR adds the missing `glyph-orientation-vertical` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.2.10).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/glyph-orientation-vertical

Add missing glyph-orientation-vertical CSS property feature

---

css/properties/break-after.json

This PR is a part of a project to add missing interfaces and interface features to BCD that are from an active spec (including WICG specs) and is supported in at least one browser. This particular PR adds the missing features of the `break-after` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.2.9).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/break-after

Add missing features for break-after CSS property

---

css/properties/break-before.json

This PR is a part of a project to add missing interfaces and interface features to BCD that are from an active spec (including WICG specs) and is supported in at least one browser. This particular PR adds the missing features of the `break-before` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.2.9).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/break-before

Add missing features for break-before CSS property

---

css/properties/text-underline-position.json

This PR is a part of a project to add missing interfaces and interface features to BCD that are from an active spec (including WICG specs) and is supported in at least one browser. This particular PR adds the missing features of the `text-underline-position` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.2.9).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/text-underline-position

Add missing features for text-underline-position CSS property

---

css/properties/image-rendering.json

This PR is a part of a project to add missing interfaces and interface features to BCD that are from an active spec (including WICG specs) and is supported in at least one browser. This particular PR adds the missing `smooth` member of the `image-rendering` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.2.9).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/image-rendering/smooth

Add missing css.properties.image-rendering.smooth feature

---

http/headers/WWW-Authenticate.json

Add HTTP Digest SHA256 for Chrome v117
https://chromestatus.com/feature/5139896267702272?context=myfeatures
None

Chrome added HTTP Digest SHA-256 in v117

---

css/types/basic-shape.json

Compat data about where `path()` can be used is outdated and inconsistent with other MDN pages, [especially `clip-path`](https://developer.mozilla.org/en-US/docs/Web/CSS/clip-path).
This PR aims to fix this and adds an additional row for every place where `path()` could or could not be used.
I tested that support for path in clip-path was indeed present for the three major browsers, see my comment in #20004.
There is a small mismatch in two version numbers with css.properties.offset-path vs css.types.basic-shape.path:
* `offset-path` with `path()` added in firefox version 72 vs 63
* `offset-path` with `path()` added in chrome version 64 vs 46
I haven't been able to find the truth.
[Git logs for chrome 64](https://chromium.googlesource.com/chromium/src/+log/63.0.3239.132..64.0.3282.119/?pre …

Fix incorrect information about path()

---

browsers/nodejs.json

New nodejs release.
Needed for https://github.com/mdn/browser-compat-data/pull/20949 to pass.

Add nodejs 21.0.0 release

---

css/properties/scrollbar-color.json
css/properties/scrollbar-width.json

Mark `scrollbar-width` and `scrollbar-color` as supported in Chrome 121.
But not Android WebView
Chrome Status Entry: https://chromestatus.com/feature/5665308343795712
This is explicitly not enabled on Android WebView.

Add CSS Scrollbars support in Chrome 121

---

README.md

- https://github.com/TimDaub/hexo-compat-report is not maintained any more
- 15,000 features, see latest BCD release

Update readme (stale link, update number of features)

---

api/Element.json
api/ElementInternals.json

This PR is a part of a project to add missing interfaces and interface features to BCD that are from an active spec (including WICG specs) and is supported in at least one browser. This particular PR adds the missing `ariaColIndexText` and `ariaRowIndexText` features of the `Element` and `ElementInternals` APIs. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.3.0).
Tests Used:
https://mdn-bcd-collector.gooborg.com/tests/api/Element/ariaColIndexText
https://mdn-bcd-collector.gooborg.com/tests/api/Element/ariaRowIndexText
https://mdn-bcd-collector.gooborg.com/tests/api/ElementInternals/ariaColIndexText …

Add missing `aria[Col/Row]IndexText` features for Element[Internals] API

---

api/HTMLInputElement.json

This leads to a broken link in https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement#browser_compatibility which I tried to follow.

Remove 404 indeterminate MDN link from HTMLInputElement

---

browsers/safari.json

Manually updated.
@jensimmons:
Is there a way to find the engine version without looking at Safari's "About" Window? And the release date I see in the [About the security content of Safari 17.1](https://support.apple.com/en-US/HT213986). Unfortunately, I can't "guess" this URL to extract the release date (not in the easy-to-guess release note page).
If we can have these two pieces of data (even on web pages that we could scrap), we could automate the creation of this PR! (Like we did for Firefox, Chrome, and Edge)

Update Safari version 17.1 (current) and 17.2 (beta)

---

browsers/samsunginternet_android.json

@matatk told me earlier today that Samsung 23.0 is stable!
It's based on Chromium 115 per https://medium.com/samsung-internet-dev/samsung-internet-v23-0-stable-coming-with-enhanced-security-and-convenience-1839a1af5dd3
I took the release date from Wikipedia: https://en.wikipedia.org/wiki/Samsung_Internet#Version_history

Add Samsung 23.0

---

api/WebKitPoint.json

Gone everywhere except WebKit.
WebKit proof: https://github.com/WebKit/WebKit/blob/main/Source/WebCore/page/WebKitPoint.idl
Found by Open Web Docs' [mdn-bcd-collector](https://github.com/openwebdocs/mdn-bcd-collector) 10.4.0.

Add constructor to WebKitPoint

---

html/elements/details.json

> HTML
> New Features
> Added support for the name attribute in the `<details>` element. (114677170)
https://developer.apple.com/documentation/safari-release-notes/safari-17_2-release-notes

Support for the name attribute for details is in Safari 17.2

---

css/properties/color-scheme.json

Support for the `only` keyword was shipped in Chrome 98:
https://chromiumdash.appspot.com/commit/3ef68395dfbc9df94714ddddd838e4e70866e599

Mark `color-scheme: only` supported since Chrome 98

---

css/selectors/nth-last-child.json

This was missed in https://github.com/mdn/browser-compat-data/pull/18852.

Chrome 111 also support "of" syntax in `:nth-last-child`

---

css/at-rules/font-feature-values.json

This was part of font-variant-alternates:
https://chromiumdash.appspot.com/commit/cf9e516503abc651d76a521d4fd76853af326f4a

Mark @font-feature-values supported since Chrome 111

---

api/HTMLSelectElement.json

Add data for HTMLSelectElement showPicker
Pull request for html spec: https://github.com/whatwg/html/pull/9754
Chrome Status Entry: https://chromestatus.com/feature/5111537299881984
Content PR: https://github.com/mdn/content/pull/29406

Add data for HTMLSelectElement showPicker

---

api/HTMLElement.json

Correct support for api.HTMLElement.nonce which was updated on a guess.
Internal records show that this was shipped in Safari 15.4.
- See https://github.com/mdn/browser-compat-data/pull/20994
- https://github.com/WebKit/WebKit/commit/76edb54f4cdb672dbcfcd78e3fcd5416e980f7df
- https://bugs.webkit.org/show_bug.cgi?id=179728

Fix Safari support for api.HTMLElement.nonce

---

api/HTMLInputElement.json

Update Safari `showPicker()` datalist support to show STP support.
https://webkit.org/blog/14769/release-notes-for-safari-technology-preview-183/#:~:text=Fixed%20showPicker()%20method%20to%20trigger%20suggestions%20from%20a%20datalist
Manually tested in latest release too.

Update Safari `showPicker()` datalist support

---

api/IdleDetector.json
docs/data-guidelines/index.md
docs/data-guidelines/tags.md
http/headers/Permissions-Policy.json
schemas/compat-data-schema.md
schemas/compat-data.schema.json
scripts/lib/stringify-and-order-properties.ts
scripts/traverse.ts
test/linter/index.ts
test/linter/test-tags.ts

This PR follows the experiment done in https://github.com/mdn/browser-compat-data/pull/21081 and introduces namespaced tags to BCD.
I've added: 
- Example tags ("web-features:idle-detection") to IdleDetector and its permission policy
- New data guideline documentation. Shamelessly stolen from @ddbeck (see https://github.com/web-platform-dx/web-features/blob/main/docs/readme.md). I think this is a good start, happy to add more.
- An addition to the compat schema and its docs (`tags` is a new schema property).
- An update to validating order (`tags` will always need to be provided at the top after `spec_urls`)
- An update to the traverse script to get lists of features that have been tagged with a specific tag. (so you can run `npm run traverse -- -t web-features:idle-detection`).
- A new …

Introduce namespaced tagging

---

css/at-rules/font-face.json

Safari added support for `font-feature-settings` in `@font-face`.
Internal records show this shipped with Safari 10 on iOS 10 and macOS 10.12.
- https://bugs.webkit.org/show_bug.cgi?id=63796
- https://bugs.webkit.org/show_bug.cgi?id=134332
- https://bugs.webkit.org/show_bug.cgi?id=147722

Fix Safari font-face.font-feature-settings support

---

api/CloseWatcher.json
api/GPUSupportedLimits.json
api/HTMLDetailsElement.json
api/IntersectionObserver.json
api/Navigator.json
api/NavigatorLogin.json
api/URL.json
css/properties/mask-clip.json
css/properties/mask-composite.json
css/properties/mask-image.json
css/properties/mask-mode.json
css/properties/mask-origin.json
css/properties/mask-position.json
css/properties/mask-repeat.json
css/properties/mask-size.json

This PR is an experiment. I've run Open Web Docs' BCD collector against Chrome 120 which reached beta yesterday. We believe that when there are beta versions of browsers available it is a good time to update BCD and ideally we should do so automatically with the help of tooling. So today is the day when such a PR would be created in the cycle. I'm creating this PR manually for the moment, but in the future we hope it can be generated from a workflow.
The collector found 21 new features shipping in Chrome 120:
- api.CredentialsContainer.create.publicKey_option.extensions.minPinLength
- api.GPUSupportedLimits.maxBindGroupsPlusVertexBuffers
- api.HTMLDetailsElement.name
- api.IntersectionObserver.scrollMargin
- api.URL.canParse_static
- css.at-rules.media.scripting
- css.properties.mask-clip …

Updates for Chrome 120 beta

---

webextensions/api/declarativeNetRequest.json

Fixes missing feature support for Safari 16.4 in declarativeNetRequest.
- Reported by internal engineering.
- See [Safari 16.4 Release Notes](https://developer.apple.com/documentation/safari-release-notes/safari-16_4-release-notes)

Fixed Safari 16.4 decalarativeNetRequest support

---

api/FileReader.json

deprecate `FileReader.readAsBinaryString()`, as the standard has suggest to use `FileReader.readAsArrayBuffer()` instead:
see https://w3c.github.io/FileAPI/#readAsBinaryString
also reference to [`FileReaderSync.readAsBinaryString()`](https://developer.mozilla.org/en-US/docs/Web/API/FileReaderSync/readAsBinaryString), which has already deprecate in #5353

Deprecate `FileReader.readAsBinaryString()`

---

browsers/opera.json

Updated current Operas browser data, as version 105 has been release on 14th of November:
https://blogs.opera.com/desktop/2023/11/opera-105-stable/
And Opera Beta currently already provides the upcoming version 106 with Chromium-Version 120

docs(opera): updated current browsers release

---

api/CompressionStream.json
api/DecompressionStream.json
browsers/nodejs.json

`deflate-raw` is now a  valid parameter for both `CompressionStream` and `DecompressionStream` constructors in node
node release notes
see: https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V21.md#21.2.0
node commit implementing the change:
https://github.com/nodejs/node/commit/91f37d1dc3

added support for web streams `deflate-raw` compression in node

---

.github/workflows/update-browser-releases.yml

This workflow runs on forks which is causing failed build notifications. Adding a check that only lets the job run if the repo is `mdn/browser-compat-data`.
* Failed runs: https://github.com/bsmth/browser-compat-data/actions/workflows/update-browser-releases.yml
* Example content config: https://github.com/mdn/content/blob/main/.github/workflows/pr-test.yml#L20
* https://github.com/mdn/content/pull/24626
* https://github.com/mdn/content/pull/21771

chore(ci): Do not run 'Update browser releases' workflow on forks

---

browsers/safari.json

The `engine_version` is 612.1.27 according to the official https://developer.apple.com/tutorials/data/documentation/safari-release-notes.json 
That's the only one that was incorrect.

Fix engine_version for Safari 15

---

http/headers/Clear-Site-Data.json

Fixes #21208
So from the above link we can see that Safari 17 adds support for **at least** `executionContext` and `clear`. This adds the top level feature version and also for `executionContext`. I left the others false because there is no evidence on support either way. Better than nothing IMO.

Clear-Site-Data - Safari 17

---

api/HTMLSelectElement.json

This follows on from #20852
Looking at the https://bugzilla.mozilla.org/show_bug.cgi?id=1854112 ,  `HTMLSelectElement` showPicker  was enabled on nightly, so this changes the release to "preview".
Related docs work in https://github.com/mdn/content/issues/30336

FF121 Showpicker in preview

---

api/CustomStateSet.json
api/ElementInternals.json

FF121 adds support for the [Custom State Pseudo Class](https://wicg.github.io/custom-state-pseudo-class) spec in https://bugzilla.mozilla.org/show_bug.cgi?id=1861466 behind a preference. 
This updates [`CustomStateSet`](https://developer.mozilla.org/en-US/docs/Web/API/CustomStateSet) with support info and MDN + spec links. It also updates [`ElementInternals.states`](https://developer.mozilla.org/en-US/docs/Web/API/ElementInternals/states) with the preference info.
There isn't any specific feature for the pseudo class itself - at least not obvious and not in the original updates to this #10976
Related docs work can be tracked in https://github.com/mdn/content/issues/30339

FF121 Custom State in Custom Elements

---

webextensions/manifest/permissions.json

- Adds the webRequestAuthProvider permission to the permissions manifest key.
- Add a note about support for webRequestBlocking permission in Chrome
Provide documentation for the Chrome permission.
Related content update in https://github.com/mdn/content/pull/30188
Fixes [#21586](https://github.com/mdn/content/issues/21586)

Support details for webRequestAuthProvider permission

---

javascript/builtins/Set.json

Given Set.keys has its own MDN page and is more like an alias to Set.values, I think it makes sense to have its own entry. (The collector proposed this and I agree)
I can send a PR to update https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/set/keys/index.md which currently added a manual spec url and queries the compat data from javascript.builtins.Set.values instead of javascript.builtins.Set.keys

Add Set.keys properly

---

api/HTMLIFrameElement.json
html/elements/iframe.json

FF121 supports [`<iframe>` `loading` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#loading) (and API version) in https://bugzilla.mozilla.org/show_bug.cgi?id=1860729. This just updates the two records appropriately. 
These went into preview in 120 (see #21126)
Related docs work can be tracked in https://github.com/mdn/content/issues/30340

FF121 iframe/HTMLIFrameElement supports loading property

---

webextensions/api/commands.json

Add support details for the `tab` property returned by `commands.onCommand`. 
To add details of this new Chrome feature
Fixes [#29555](https://github.com/mdn/content/issues/29555)
Related MDN update in https://github.com/mdn/content/pull/30387

commands.onCommand add tab

---

api/IdentityProvider.json

Seems to have come with the other Login-related APIs: https://source.chromium.org/search?q=FedCmIdpSigninStatus%20lang:idl&ss=chromium%2Fchromium%2Fsrc

Add IdentityProvider.close()

---

webassembly/api.json
webassembly/api/Module.json

The WebAssembly statics should follow the convention for static members: https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines/api.md#static-api-members
Needs a PR on the content side which I can open.

Correct WebAssembly statics

---

api/HTMLTemplateElement.json

Chrome 111 confirmed by https://chromestatus.com/feature/5161240576393216
Safari 16.4 confirmed by https://developer.apple.com/documentation/safari-release-notes/safari-16_4-release-notes
Follow-up to https://github.com/mdn/browser-compat-data/pull/19334 and https://github.com/mdn/browser-compat-data/pull/18855

Add HTMLTemplateElement.shadowRootMode

---

javascript/builtins/String.json

Unsupported everywhere for a long time and not mentioned in the docs.

Remove obsolete javascript.builtins.String.search.flags

---

test/linter/test-obsolete.ts
webextensions/api/downloads.json
webextensions/manifest/manifest_version.json
webextensions/manifest/theme.json

I didn't know the linter for our irrelevance check isn't running on all folders yet.
This PR removes features we consider irrelevant as they are gone everywhere for more than two years.
It enables the linter for the webextensions/ folder.
See https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines/index.md#removal-of-irrelevant-features for the BCD data rule.
Setting "needs content update" as this at least also makes the https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/downloads/drag page irrelevant.

Remove obsolete Webextension features; enable lint

---

webassembly/garbage-collection.json

Firefox 120 supports WasmGC
[Release notes](https://www.mozilla.org/en-US/firefox/120.0beta/releasenotes/#:~:text=WebAssembly%20GC%20is%20now%20enabled%20by%20default%2C%20which%20allows%20new%20languages%2C%20such%20as%20Dart%20or%20Kotlin%2C%20to%20run%20on%20Firefox.%20This%20makes%20it%20possible%20for%20reference%20cycles%20between%20the%20guest%20language%20and%20host%20browser%20to%20be%20collected.)

Firefox 120 supports WasmGC

---

css/properties/scroll-timeline.json
css/properties/view-timeline.json

_(👋 Hi, Chrome DevRel here)_
At one point in time the mentioned `scroll-timeline-attachment` and `view-timeline-attachment` properties were part of the spec but these have since been removed. The functionality got replaced by the `timeline-scope` property.
- Resolution to add `scroll/view-timeline-attachment`: https://github.com/w3c/csswg-drafts/issues/7759#issuecomment-1476312797
- Resolution to remove `scroll/view-timeline-attachment` and add `timeline-scope` instead: https://github.com/w3c/csswg-drafts/issues/7759#issuecomment-1551709286
This PR removes references to those properties. No browser ever shipped support for these `scroll/view-timeline-attachment` properties – they never made it past being part of an editor’s draft.

Remove scroll-timeline-attachment/view-timeline-attachment references

---

api/Document.json

The collector found this new method on Document.
I was unable to confirm version 118 on Chromestatus. There is no entry.
Maybe @chrisdavidmills knows more otherwise I would trust the collector and go with 118 here.

Add Document.requestStorageAccessFor()

---

css/properties/speak-as.json

The collector found that these are supported in Safari.
See https://bugs.webkit.org/show_bug.cgi?id=180361

Add speak-as property, update speak for Safari 11.1

---

api/Window.json

Found by the Open Web Docs BCD collector.
See https://bugzilla.mozilla.org/show_bug.cgi?id=1855348

Firefox 120 removed Window.sizeToContent

---

html/elements/img.json

This updates the decoding HTML attribute to match the mdn / spec links.

Update html.elements.img.decoding mdn_url / spec_url

---

scripts/update-browser-releases/chrome.ts
scripts/update-browser-releases/edge.ts
scripts/update-browser-releases/firefox.ts
scripts/update-browser-releases/index.ts
scripts/update-browser-releases/safari.ts
scripts/update-browser-releases/utils.ts

Add support to update 'safari.json' and 'safari_ios.json' based on the data given by Apple
Manually tested
Note:
- No warning message is raised for old Safari iOS version (≤15) if they don't exist, as discussed during the BCD meeting
- The way to calculate the next Firefox planned has been fixed (didn't work on release day, now it does).

Add support for Safari in update-browser-releases

---

api/BarcodeDetector.json
api/HTMLCanvasElement.json
api/MediaDevices.json
api/Navigator.json
api/NetworkInformation.json

This PR changes all instances where "Chrome OS" is mentioned to say "ChromeOS", as is the correct spelling per Google's webpages and documentation.  Fixes #21313 (indirectly).

Chrome OS -> ChromeOS

---

api/Navigator.json
api/NavigatorManagedData.json

This PR is a follow-up to #21294 that corrects the version numbers set for the Managed Configuration API for Chrome, as confirmed by the [mdn-bcd-collector project](https://mdn-bcd-collector.gooborg.com), v10.4.0.

Update Chrome support for Managed Configuration API

---

css/properties/clip-path.json

This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `fill_and_stroke_box` member of the `clip-path` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.4.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/clip-path/fill_and_stroke_box

Update Chromium data for css.properties.clip-path.fill_and_stroke_box

---

css/properties/font-variant.json

This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `font-variant` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.4.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/font-variant

Update Chromium data for font-variant CSS property

---

api/WebTransportSendStream.json

sendOrder is in Firefox 121 https://bugzilla.mozilla.org/show_bug.cgi?id=1853444

Add WebTransportSendStream interface

---

mathml/attribute_values.json
mathml/elements/maction.json
mathml/elements/mpadded.json
mathml/elements/mtable.json
test/linter/test-obsolete.ts

Enables our linter to check for irrelevant features for the `mathml/` folder. See the BCD data guideline about removal of features gone everywhere for more than two years: https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines/index.md#removal-of-irrelevant-features
This means complete removal of
- `mathml.elements.maction.actiontype.restyle`
- `mathml.elements.mtable.width.nonzero_unitless_values`
Drive-by updates to:
- `mathml.attribute_values.nonzero_unitless_values` to say removed in Fx70 (consistent with other data)
- `mathml.elements.mpadded.lspace.nonzero_unitless_values` to say removed in Fx70 (consistent with other data)
- `mathml.attribute_values.named_space` to add a description

Enable irrelevance linting for MathML

---

html/elements/iframe.json

By https://github.com/mdn/browser-compat-data/commit/7295c5639475f06bf0e51cb8dc231d3abebc5331, Firefox desktop updates allow attribute data. But this supports on Android too.
https://bugzilla.mozilla.org/show_bug.cgi?id=1617219.

Firefox 74+ for Android supports allow attribute.

---

css/selectors/has.json

Updated the version added for `:has()` selector in Firefox
Tested in Firefox Beta
- [[CSS] Enable :has on Release #30335](https://github.com/mdn/content/issues/30335)
- [Content PR](https://github.com/mdn/content/pull/30456)

updated firefox version added for :has()

---

css/properties/speak.json

This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `speak` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.4.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/speak

Update Safari data for speak CSS property

---

api/CSS.json
api/CSSPropertyRule.json
css/at-rules/property.json

This note might be useful to set expectations about this feature for now.
I am setting this at the following level which I think is most accurate:
- css.at-rules.property
- api.CSS.registerProperty_static
- api.CSSPropertyRule
- One person caught out by this here: https://github.com/mdn/browser-compat-data/pull/20346#issuecomment-1741439650
- Bug: https://bugzil.la/1846516
- Plans to ship: https://bugzilla.mozilla.org/show_bug.cgi?id=1864818

Add note about support for interpolation of registered custom properties in Fx

---

api/HTMLInputElement.json

showPicker for `<input type=time>` supports on Firefox/Android 101+
When I test showPicker implementation by https://wontfix.net/bugs/showpicker.html, Firefox/Android shows picker on `<input type="time">` since Firefox/Android has the picker for this type.
I verified on Firefox/Android 101.
- https://bugzilla.mozilla.org/show_bug.cgi?id=1745005

showPicker for <input type=time> supports on Firefox/Android

---

.github/workflows/close-incomplete-issues.yml

This PR updates the auto-close bot's text for better clarity about what the issue reporter needs to do if their issue was closed in error.

Update auto-issue-close text

---

api/Navigator.json
http/headers/Device-Memory.json

According to spec data, the `Navigator.deviceMemory` property and `Device-Memory` http header has been supported by Chrome and Opera without any flags or prefixes, so it is time to mark `experimental` as `false`
See also `WorkerNavigator.deviceMemory`, which mark `experimental` as `false`
Related With https://github.com/mdn/content/pull/30538

 mark experimental false of `Navigator.deviceMemory` and `Device-Memory`

---

webassembly/extended-constant-expressions.json

Found by the Open Web Docs BCD Collector.
Confirmed by https://chromestatus.com/feature/5131077456232448

Chrome 114 ships wasm extended-const

---

browsers/safari.json
browsers/safari_ios.json

This is the output of the updated Safari script in https://github.com/mdn/browser-compat-data/pull/21325

Update Safari releases according to Apple release notes

---

css/selectors/fullscreen.json

This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `fullscreen` CSS selector. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.5.1).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/selectors/fullscreen
Additional Notes: The collector produced the range of 15.6> ≤16.5 due to lack of testing capacity for Safari 16.x at the moment.  Safari 16.4 was guesstimated by mirroring from api.Element.requestFullscreen.

Update Safari data for fullscreen CSS selector

---

css/types/length-percentage.json

Safari has shipped a number of new units over the last two years, but it seems only length.json was updated. 
Safari does support percentages with all of these units.

Correcting Safari's support of length-percentage

---

api/MediaKeys.json

This PR is a part of a project to add missing interfaces and interface features to BCD that are from an active spec (including WICG specs) and is supported in at least one browser. This particular PR adds the missing `getStatusForPolicy` member of the `MediaKeys` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.5.1).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/MediaKeys/getStatusForPolicy

Add missing api.MediaKeys.getStatusForPolicy feature

---

api/HTMLVideoElement.json

`api.HTMLVideoElement.disablePictureInPicture` was added to FF116 but the entry was reverted in #21029 because the value is not in the WebIDL or testable. Apparently this is actually present:
From [the issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1832154#c9):
> As far as I can tell, we do intend to be passing this test. We'll file a separate bug to update the appropriate WebIDL, and I think that should take care of this.
> Note though that we provide an implementation of the attribute behavior that is deliberately not spec-compliant, and we have no plans to change that. I would assume that the compatibility data needs to reflect this fact.
AND the spec difference are:
> So, there's two things:
> - We implement the disablePictureInPicture attribute, but none of the rest of the PIP …

Restore FF116 HTMLVideoElement.disablePictureInPicture

---

css/selectors/past.json

This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `past` CSS selector. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.5.1).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/selectors/past

Update Chromium data for past CSS selector

---

css/selectors/future.json

This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `future` CSS selector. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.5.1).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/selectors/future

Update Chromium data for future CSS selector

---

api/WebTransportBidirectionalStream.json

This follows on from #21333 which added support for `WebTransportSendStream` in 114.
The  `WebTransportSendStream` interface is returned by `WebTransportBidirectionalStream.writable` in the spec, and `WebTransportReceiveStream` is returned by `WebTransportBidirectionalStream.readable`. You can see that `WebTransportSendStream` and `WebTransportSendStream` are supported by FF114 (nightly) using the BCD collectors - such as https://mdn-bcd-collector.gooborg.com/tests/api/WebTransportSendStream but are not supported in current Chrome.
What this does is update the `WebTransportBidirectionalStream` `readable` and `writable` features with a subfeature indicating the new return type.
Note that `WebTransportSendStream` should also be returned by  `createUnidirectionalStream()` but this is not …

FF121 Update WebTransportBidirectionalStream to use WebTransportSend/RecieveStream 

---

webextensions/api/webRequest.json

Add to the browser compatibility details to complement the documentation update in https://github.com/mdn/content/pull/29873
frameAncestors was added to onBeforeRequest in version 58, according to the release notes and BCD. Was also added to onHeadersReceived in version 58 according to the BCD. Cannot find any information to confirm when it is to onbeforesendheaders

webrequest.onbeforesendheaders frameAncestors

---

scripts/release/utils.ts

This PR swaps a call to `.replace()` with `.replaceAll()` in string sanitization, preventing potential issues.

Use .replaceAll() instead of .replace() in string sanitization

---

scripts/update-browser-releases/chrome.ts

The Chrome script assumes that the data would always have all channels. However, currently, the data has no info for canary... https://chromestatus.com/api/v0/channels
See the failed build: https://github.com/mdn/browser-compat-data/actions/runs/7028052289/job/19129489635
I've added two if conditions to first check if the data is there. line 92 and line 170. The rest is prettier indent.

Fix Chrome update script

---

css/selectors/picture-in-picture.json

This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `picture-in-picture` CSS selector. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.5.1).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/selectors/picture-in-picture

Update Safari data for picture-in-picture CSS selector

---

css/properties/grid-template-rows.json
css/properties/letter-spacing.json
css/properties/list-style-type.json
css/properties/word-spacing.json
css/selectors/marker.json
css/types/image.json

If you run `npm run traverse css -- -b firefox_android -f false` you find 8 features that are currently marked false:
Except for font-smooth (it says that it only works on macOS) and for -moz-window-inactive (not sure if it works in android), these features should all mirror the support from firefox desktop.
css.properties.font-smooth
css.properties.grid-template-rows.subgrid
css.properties.letter-spacing.svg
css.properties.list-style-type.tibetan
css.properties.word-spacing.svg
css.selectors.-moz-window-inactive
css.selectors.marker.animation_and_transition_support
css.types.image.image
btw, to see all CSS features that are not mirrored from Firefox Desktop, run: `npm run traverse css -- -b firefox_android -f nonmirror`. It spits out 95 features and upon spot checking these are legit as …

Firefox Android: Mirror a few more CSS features

---

api/HTMLInputElement.json
css/selectors/highlight.json

This is a followup to https://github.com/mdn/browser-compat-data/pull/21267.
The Open Web Docs BCD collector v10.5.2 can now detect compat data changes for events and CSS selectors. Running it again with Safari 17.2 beta revealed two more changes:
- `api.HTMLInputElement.serach_event` (removed in 17.2, belongs to the removal of `api.HTMLInputElement.incremental`)
- `css.selectors.highlight` (added in 17.2 and part of the CSS Custom Highlight API which is talked about in the [release notes](https://developer.apple.com/documentation/safari-release-notes/safari-17_2-release-notes).)
(cc @jdatapple)

Safari 17.2 supports :highlight; removes HTMLInputElement.search_event

---

webassembly/tail-calls.json

Found by the Open Web Docs BCD Collector.
Confirmed by https://bugzilla.mozilla.org/show_bug.cgi?id=1846789

Firefox 121 ships wasm tail calls

---

api/CookieStore.json
api/ServiceWorkerGlobalScope.json

mark `partitioned` option in `CookieStore` interface as standard, see spec https://wicg.github.io/cookie-store/ , as they have been added to spec yet
also mark `ServiceWorkerGlobalScope cookiechange event` as standard, which also added in spec yet, and add `apec_url` for it

mark `partitioned` option in `CookieStore` interface as standard

---

http/headers/Origin-Agent-Cluster.json

See also https://github.com/mdn/content/pull/30743, https://web.dev/articles/origin-agent-cluster.
Uses the same support data as for https://developer.mozilla.org/en-US/docs/Web/API/Window/originAgentCluster (https://github.com/mdn/browser-compat-data/commit/7aa11f1c73888260917eafae516192d11bf96caf).

Add Origin-Agent-Cluster HTTP header

---

http/headers/Sec-CH-UA.json

I have added buzgilla to `http.headers.Sec-CH-UA`.
test: N/A
tracker: [bugzilla.mozilla.org/show_bug.cgi?id=935216](https://bugzilla.mozilla.org/show_bug.cgi?id=935216)
Fixes #21354

http.sec-ch-ua(firefox): added tracking bugzilla

---

api/HTMLDialogElement.json

Correct a likely incorrect lack-of-mirroring divergence between Chrome and Chrome for Android.
> OK, so it's about the `cancel` event. https://mdn-bcd-collector.gooborg.com/tests/api/HTMLDialogElement doesn't have a test for that, I think because `oncancel` is on `GlobalEventHanders`.
> 
> I've checked the Chromium source and don't see anything special about the cancel event. I think BCD is wrong […]
_Originally posted by @foolip in https://github.com/web-platform-dx/web-features/pull/455#discussion_r1413518428_
- https://github.com/web-platform-dx/web-features/pull/455

`HTMLDialogElement`: correct `cancel` event for Chrome for Android

---

api/Document.json
api/Element.json
api/Performance.json
api/Screen.json
test/linter/test-prefix.ts

This PR fixes a bug with the prefix linter regarding alternative names that are just prefixes, as well as expands its capabilities to handle events, static methods and CSS selectors.

Fix prefix linter

---

javascript/builtins/Map.json
javascript/builtins/Object.json

With Node.js v21.0.0, the V8 engine [updated to v11.8](https://nodejs.org/en/blog/announcements/v21-release-announce#v8-118), this aligns with Chrome 118 and adds both [Map.groupBy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/groupBy) and [Object.groupBy()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/groupBy)
Fixes #21429

Add Node.js support data for groupBy() (#21429)

---

css/properties/hyphens.json

This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `hyphens` CSS property. The data comes from a commit in the browser's source code, mapped to a version number using available tooling or via the commit timestamp.
Commit: 
(Chrome 87; as, be, bg, bn, cu, cy, da, de-1901, de-1996, de-ch-1901, en-gb, en-us, es, et, eu, fr, ga, gu, hi, hr, hu, hy, kn, la, ml, mn-cyrl, mr, nb, nn, or, pa, pt, sl, ta, te, tk, und-ethi): https://chromiumdash.appspot.com/commit/6607bfa1ce9656569ea9330bb7f1fb3058aad920
(Chrome 112; af, am, cs, el, gl, it, ka, lt, lv, nl, ru, sk, sq, sv, uk, mul-ethi): https://chromiumdash.appspot.com/commit/0720c691bcdc16a9438e249642aeabbe498c2da4
Additional Notes: This fixes #18172, fixes #18987, fixes #21272.

Update Chromium data for hyphens CSS property

---

css/selectors/read-only.json
css/selectors/read-write.json

Turn on mirroring for `:read-write` and `:read-only` for Firefox for Android.
I tested this in the current release of Firefox for Android and it works fine.
This looks like an oversight from the time when Firefox for Android wasn't doing releases. It works in current releases and I can't find any evidence it was specifically unsupported in Firefox for Android.
Discovered in the course of https://github.com/web-platform-dx/web-features/pull/462.

`:read-write` and `:read-only`: fix unprefixed Firefox for Android support

---

.github/ISSUE_TEMPLATE/data-problem.yml
.github/ISSUE_TEMPLATE/enhancement.yml
.github/ISSUE_TEMPLATE/infra-problem.yml

This PR removes the automatic assigning of "needs triage" labels from BCD issues, as discussed in the last BCD call.
(Self-merging since it was already approved during the call.)

Don't apply "needs triage" labels by default

---

webextensions/manifest/manifest_version.json

This PR updates and corrects version values for Microsoft Edge for the `v3` member of the `manifest_version` Web Extensions manifest property. This fixes #14658, which contains the supporting evidence for this change.

Update Edge data for webextensions.manifest.manifest_version.v3

---

api/Permissions.json

This PR removes the `permission_speaker-selection` member of the `Permissions` API from BCD. Firefox, the only browser marked with support, doesn't actually support this.  This fixes #17033, which contains the supporting evidence.
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/Permissions/permission_speaker-selection

Remove api.Permissions.permission_speaker-selection from BCD

---

schemas/compat-data-schema.md

This PR fixes a quick typo in the schema docs.

Fix typo in compat-data schema explainer doc

---

docs/data-guidelines/index.md

This PR updates the guidelines for irrelevant feature removal to specify a feature can be removed if it's no longer available behind a flag in the latest stable browser release.

Mention flag support for irrelevant feature removal

---

css/properties/background-position-x.json
css/properties/background-position-y.json

This PR renames the `two_value_syntax` subfeature of the `background-position-x` and `background-position-y` CSS properties to `side-relative_values`, as discussed in https://github.com/mdn/content/pull/30858#issuecomment-1846800972.

Rename background-position-[x/y] two_value_syntax to side-relative_values

---

.prettierrc
api/HTMLAnchorElement.json
api/HTMLAreaElement.json
api/Location.json
schemas/browsers.schema.json
schemas/compat-data.schema.json

The PR replaces `http` with `https`. It's better to use `https` were ever possible.

fix: http -> https

---

api/URLSearchParams.json
browsers/nodejs.json

This PR updates and corrects version values for NodeJS for the `size` member of the `URLSearchParams` API. This fixes #20414.  Versions come from the Node.js docs: https://nodejs.org/api/url.html#urlsearchparamssize

Update NodeJS data for api.URLSearchParams.size

---

api/PushManager.json

This PR updates and corrects version values for Microsoft Edge for the `subscribe` member of the `PushManager` API. This copies the notes from Chrome.
Additional Notes: Fixes #21135.

Update Edge data for api.PushManager.subscribe

---

html/manifest/note_taking.json

This PR removes two broken links from BCD.  Fixes #20698, fixes #20699.

Remove broken links for html.manifest.note_taking

---

css/properties/paint-order.json

Browser support for CSS `paint-order` on HTML text differs between browsers. This is because as originally specified, the property had a restriction saying that it should only apply to SVG. That restriction has since been removed, see https://github.com/w3c/fxtf-drafts/issues/107
Support for `paint-order` on HTML text was included along with the initial support for `paint-order` in Firefox 60, see https://bugs.webkit.org/show_bug.cgi?id=168601
Support for `paint-order` on HTML text was added to WebKit in https://github.com/WebKit/WebKit/commit/73a116fe7ce0dffc4856bb8dc3986e49308df943 which was included in WebKit 604. According to browsers/safari.json, this corresponds to Safari 11.
Support for `paint-order` on HTML text in Chromium is still pending: …

Add stroked HTML text compatibility info for CSS `paint-order` property

---

css/types/easing-function.json

The linear function is supported in Safari 17.2, and in Safari Technology Preview 176+.

linear() is in Safari 17.2

---

html/elements/script.json

This PR updates and corrects version values for Firefox and Firefox Android for the `async` member of the `script` HTML element. This fixes #19633, which contains the supporting evidence for this change.

Update Firefox data for html.elements.script.async

---

api/Window.json

It was missing (likely because the spec was not in the w3c list at the time of creation of the original addition).

Add spec_url for Window.credentialless

---

webassembly/api.json

This PR updates and corrects version values for NodeJS for the `webassembly.api.instantiateStreaming_static` feature. This fixes #17150, which contains the supporting evidence for this change.

Update NodeJS data for webassembly.api.instantiateStreaming_static feature

---

api/URL.json

the spec-url of `URL` interface should be with hash `#url`, not `#api`
also normalize the spec-url of `URL.canParse()` and `URL()` to keep same with others

fix spec-url of `URL` interface

---

api/Document.json
api/Element.json
api/HTMLMediaElement.json
api/RTCStatsReport.json

This PR cleans up some more bug links, and replaces alt. names with prefixes where they're supposed to be.  Caught by the fixed linters in #21544.

Cleanup bug text and prefixes

---

schemas/compat-data-schema.md

This PR updates the compat data schema to perform a few tweaks, including mentioning the webassembly/ folder and fixing grammar.

Update compat data schema docs

---

css/selectors/nesting.json

This PR fixes the MDN URL for the Nesting selector.  This fixes Fyrd/caniuse#6917.

Fix MDN URL for Nesting selector

---

test/linter/test-browsers-presence.test.ts

This PR fixes the unittest for the browser presence linter.  Self-merging since this fixes a failing CI run.

Fix unittest for browser presence linter

---

http/headers/Sec-GPC.json

This PR updates and corrects version values for Firefox and Firefox Android for the `Sec-GPC` HTTP header. This is a follow-up to #21083, where the note was updated in the Navigator API, but not the HTTP header.

Update Firefox data for Sec-GPC HTTP header

---

api/HTMLInputElement.json

BCD says FF does not support week/month input types. However according to https://bugzilla.mozilla.org/show_bug.cgi?id=1853797#c18 it used to, and this has been restored in FF122. 
I am confirming that this applies to both Android and desktop
Fixes #21524.

FF122 HTMLInputElement inputs Week, Month supported

---

html/elements/link.json

Adding support data for `rel="modulepreload"` which is in Safari 17.
https://developer.apple.com/documentation/safari-release-notes/safari-17-release-notes

modulepreload is in Safari 17

---

css/properties/rx.json
css/properties/ry.json

Safari does not support these two properties in CSS.  Note the blue `<rect>` element in this codepen: https://codepen.io/sidewayss/pen/GRPgqvG
AFAICT all of the other SVG geometry CSS properties work in all the browsers except `rx` and `ry` in Safari. The codepen tests those two along with `x`, `y` and `r`, `cx`, and `cy` for `<circle>`.
caniuse.com:
https://caniuse.com/?search=rx
https://caniuse.com/?search=ry
There are no MDN docs pages for these as CSS properties, only as SVG attributes. Those pages ([here](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/rx) and [here](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/ry)) mention that in SVG 2 the CSS properties exist, but there is no browser support matrix on those pages.
Screenshots of desktop browsers (I tested …

CSS rx and ry not supported in Safari 17

---

css/types/color.json

[Chrome 119](https://chromestatus.com/feature/5205844613922816) and [Safari 16.4](https://webkit.org/blog/13966/webkit-features-in-safari-16-4/#color) add [relative color syntax](https://drafts.csswg.org/css-color-5/#relative-colors) for CSS `<color>` types.
This PR adds data for this new feature.
See my [research document](https://docs.google.com/document/d/1YjI97ZrRF2qtI5KUV_TiG3OVmyJQ2TBqosqKGxy1Dhw/edit) for more details of what this work entails.
Fixes https://github.com/mdn/browser-compat-data/issues/19855

Add relative <color> data

---

css/types/color.json

Add relative `color()` as it was overlooked in https://github.com/mdn/browser-compat-data/pull/21583
https://wpt.fyi/results/css/css-color/parsing/color-valid-relative-color.html?label=master&label=experimental&aligned&q=relative
see : https://github.com/mdn/browser-compat-data/pull/21583#issuecomment-1851661789

[css-color] add relative `color()`

---

html/global_attributes.json

This PR updates and corrects version values for Safari iOS/iPadOS for the `inputmode` member of the `global_attributes` HTML feature. The data comes from manual testing, running test code through BrowserStack, SauceLabs and custom VMs.
Test Code:
```
<input type="text" inputmode="none" />
```
This fixes #7186.

Update Safari iOS data for html.global_attributes.inputmode

---

api/Document.json
api/Permissions.json
css/selectors/future.json

https://github.com/mdn/browser-compat-data/pull/21336 updated the [Storage Access API](https://developer.mozilla.org/en-US/docs/Web/API/Storage_Access_API) compat data rather nicely. I created https://github.com/mdn/content/pull/30500 to update the SAA docs and introduce the concept of related website sets to MDN, and in doing so, I found a couple of details I thought worth including in the BCD.
So, here goes.

Small tweaks to the Storage Access API data

---

api/Element.json

This PR updates and corrects version values for Chrome Android for the `dblclick_event` member of the `Element` API. This fixes #8904, which contains the supporting evidence for this change.

Update Chrome Android data for api.Element.dblclick_event

---

api/OffscreenCanvas.json

This PR is a part of a project to add missing interfaces and interface features to BCD that are from an active spec (including WICG specs) and is supported in at least one browser. This particular PR adds the missing `getContext.webgpu_context` member of the `OffscreenCanvas` API. The data was mirrored from api.HTMLCanvasElement.getContext.webgpu_context.  This fixes #9815.

Add missing api.OffscreenCanvas.getContext.webgpu_context feature

---

http/headers/Access-Control-Expose-Headers.json

This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `wildcard` member of the `Access-Control-Expose-Headers` HTTP header. The data comes from a commit in the browser's source code, mapped to a version number using available tooling or via the commit timestamp.
Commit: https://github.com/WebKit/WebKit/commit/6e529bd3f615bbb4a9eab03069be705e623c7b6a
Additional Notes: Fixes #11232.

Update Safari data for http.headers.Access-Control-Expose-Headers.wildcard

---

api/KeyboardEvent.json

This PR renames the subfeatures of `api.KeyboardEvent.getModifierState` to reflect our usual conventions better, changing the current `<value>_parameter` to `key_parameter_<value>`.  This fixes #11295.

Rename all subfeatures for api.KeyboardEvent.getModifierState

---

api/HTMLButtonElement.json
api/HTMLFieldSetElement.json
api/HTMLInputElement.json
api/HTMLObjectElement.json
api/HTMLOutputElement.json
api/HTMLSelectElement.json
api/HTMLTextAreaElement.json

This PR fixes #11342 by adding a note about how `setCustomValidity()` does not change the tooltip on hover when called.

Add notes about tooltips in Chrome for setCustomValidity()

---

api/MediaDevices.json

This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `getDisplayMedia.audio_capture_support` member of the `MediaDevices` API. This fixes #11732 by updating the notes accordingly.

Update Chromium data for api.MediaDevices.getDisplayMedia.audio_capture_support

---

api/NavigatorManagedData.json

This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `managedconfigurationchange_event` member of the `NavigatorManagedData` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.5.2).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/NavigatorManagedData/managedconfigurationchange_event

Update Chromium data for api.NavigatorManagedData.managedconfigurationchange_event

---

browsers/nodejs.json

This PR updates the statuses for the Node.js releases.  Data comes from https://nodejs.org/en/about/previous-releases.

Update Node.js support statuses

---

javascript/builtins/WeakRef.json

This PR updates and corrects version values for NodeJS for the `symbol_as_target` member of the `WeakRef` JavaScript builtin. This fixes #20278, which contains the supporting evidence for this change.

Update NodeJS data for javascript.builtins.WeakRef.symbol_as_target

---

webextensions/api/dns.json

This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `resolve` member of the `dns` Web Extensions interface. This fixes #19912, which contains the supporting evidence for this change.

Update Chromium data for webextensions.api.dns.resolve

---

http/headers/Content-Security-Policy.json

This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `prefetch-src` member of the `Content-Security-Policy` HTTP header. This fixes #19400, which contains the supporting evidence for this change.

Update Safari data for http.headers.Content-Security-Policy.prefetch-src

---

api/RTCRtpSender.json

This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `setParameters.parameters_degradationPreference_parameter` member of the `RTCRtpSender` API. This fixes #19235, which contains the supporting evidence for this change.

Update Chromium data for api.RTCRtpSender.setParameters.parameters_degradationPreference_parameter

---

javascript/builtins/Error.json

This PR is a part of a project to add missing interfaces and interface features to BCD that are from an active spec (including WICG specs) and is supported in at least one browser. This particular PR adds the missing `cause.displayed_in_console` member of the `Error` JavaScript builtin. This fixes #19004, which contains the supporting evidence for this change.

Add missing javascript.builtins.Error.cause.displayed_in_console feature

---

api/Navigator.json

This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `setAppBadge` member of the `Navigator` API. This sets the note to be the same as clearAppBadge().

Update Safari data for api.Navigator.setAppBadge

---

css/properties/filter.json

This PR updates and corrects version values for Chrome and Safari for the `svg` member of the `filter` CSS property. This fixes #18917, which contains the supporting evidence for this change.

Update Chrome/Safari data for css.properties.filter.svg

---

http/headers/Content-Security-Policy.json

This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `script-src-elem` member of the `Content-Security-Policy` HTTP header. This fixes #18911, which contains the supporting evidence for this change.

Update Safari data for http.headers.Content-Security-Policy.script-src-elem

---

api/RTCPeerConnection.json

This PR updates and corrects version values for Opera and Opera Android for the `addTransceiver` member of the `RTCPeerConnection` API. This fixes #18958, which contains the supporting evidence for this change.

Update Opera data for api.RTCPeerConnection.addTransceiver

---

javascript/statements.json

This PR updates and corrects version values for WebView Android for the `export` member of the `statements` JavaScript feature. This fixes #18711, which contains the supporting evidence for this change.

Update WebView data for javascript.statements.export

---

api/MediaTrackSettings.json

This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `displaySurface` member of the `MediaTrackSettings` API. This fixes #18536, which contains the supporting evidence for this change.

Update Safari data for api.MediaTrackSettings.displaySurface

---

html/elements/select.json

This PR updates and corrects version values for Chrome and Safari for the `size` member of the `select` HTML element. This fixes #18513, which contains the supporting evidence for this change.
Additional Notes: This was checked manually in Chrome and Firefox on Android, and Safari on iOS.

Update Chrome/Safari data for html.elements.select.size

---

http/headers/Content-Security-Policy.json

This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `report-to` member of the `Content-Security-Policy` HTTP header. The data comes from a commit in the browser's source code, mapped to a version number using available tooling or via the commit timestamp.
Commit: https://github.com/WebKit/WebKit/commit/42f5a93823a7f087a800cd65c6bc0551dbeb55d3
Additional Notes: This fixes #18442.

Update Safari data for http.headers.Content-Security-Policy.report-to

---

html/global_attributes.json

This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `hidden.until-found_value` member of the `global_attributes` HTML feature. This fixes #18337, which contains the supporting evidence for this change.
Additional Notes: The Firefox bug was not added as was mentioned in the issue, because it has been unconfirmed since it was opened two years ago.

Update Safari data for html.global_attributes.hidden.until-found_value

---

css/selectors/before.json

This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `animation_and_transition_support` member of the `before` CSS selector. This fixes #18109, which contains the supporting evidence for this change.

Update Safari data for css.selectors.before.animation_and_transition_support

---

css/selectors/selection.json

This PR is a part of a project to add missing interfaces and interface features to BCD that are from an active spec (including WICG specs) and is supported in at least one browser. This particular PR adds the missing `text-decoration` member of the `selection` CSS selector. The data comes from manual testing, running test code through BrowserStack, SauceLabs and custom VMs.
Test Code:
```html
<style>
p::selection {
color: seagreen;
background-color: white;
text-decoration: underline;
}
</style>
<p>Lorem ipsum dolor sit amet</p>
```
Fixes #17817.

Add missing css.selectors.selection.text-decoration feature

---

css/properties/scroll-snap-type.json

This PR updates and corrects version values for Firefox and Firefox Android for the `scroll-snap-type` CSS property. This replaces the macOS version number with the formal name for consistency.

Update Firefox data for scroll-snap-type CSS property

---

api/SVGGeometryElement.json

This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `SVGGeometryElement` API. This fixes https://github.com/mdn/browser-compat-data/issues/16965, which contains the supporting evidence for this change.

Update Chromium data for SVGGeometryElement API

---

javascript/statements.json

This PR updates the data for the import assertions and import attributes features.  This renames `import_attribues_assert` back to `import_assertions` to better represent its previous name (and fix a typo in the process), as well as include the name "import assertions" in the description.  Additionally, this improves the descriptions of the subfeatures.

Update identifiers/descriptions for import attributes/assertions

---

api/EventTarget.json

This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `addEventListener.options_parameter.options_passive_parameter_default_true_touch` member of the `EventTarget` API. The data comes from a commit in the browser's source code, mapped to a version number using available tooling or via the commit timestamp.
Commit: https://github.com/WebKit/WebKit/commit/513e72181713132ad1147abb4866ce2d93257b4a
Additional Notes: Fixes #16835.

Update Safari data for api.EventTarget.addEventListener.options_parameter.options_passive_parameter_default_true_touch

---

api/CredentialsContainer.json

This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `preventSilentAccess` member of the `CredentialsContainer` API. This fixes #16794, which contains the supporting evidence for this change.

Update Safari data for api.CredentialsContainer.preventSilentAccess

---

html/global_attributes.json

This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `hidden` member of the `global_attributes` HTML feature. This fixes #16619, which contains the supporting evidence for this change.
Additional Notes: The reporter states this is an iOS issue, but it affects Safari Desktop as well.

Update Safari data for html.global_attributes.hidden

---

http/headers/Permissions-Policy.json

This PR updates and corrects version values for Firefox and Firefox Android for the `fullscreen` member of the `Permissions-Policy` HTTP header. This fixes #16537, which contains the supporting evidence for this change.

Update Firefox data for http.headers.Permissions-Policy.fullscreen

---

api/Document.json

This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `domain` member of the `Document` API. This updates the note introduced in #18500 to a) better explain the new behavior, b) fix the version number (see https://chromestatus.com/feature/5428079583297536), c) remove an empty link to a demo, and d) link to an MDN article explaining origin-keyed agent clusters, not a ChromeStatus page.
Additional Notes: This fixes #21221.

Update Chromium data for api.Document.domain

---

api/AudioContext.json

This PR updates and corrects version values for Firefox and Firefox Android for the `createMediaStreamSource` member of the `AudioContext` API. This fixes #16213, which contains the supporting evidence for this change.

Update Firefox data for api.AudioContext.createMediaStreamSource

---

api/SVGGeometryElement.json

This PR is a part of a project to add missing interfaces and interface features to BCD that are from an active spec (including WICG specs) and is supported in at least one browser. This particular PR adds the missing `isPointInFill.point_parameter_DOMPoint` member of the `SVGGeometryElement` API. The data comes from manual testing, running test code through BrowserStack, SauceLabs and custom VMs.
Test Code:
```
<svg
viewBox="0 0 100 100"
width="150"
height="150"
xmlns="http://www.w3.org/2000/svg">
<circle
id="circle"
cx="50"
cy="50"
r="45"
fill="white"
stroke="blue"
stroke-width="10" />
</svg>
<p id="usedSVGPoint"><code>DOMPoint()</code> failed and <code>SVGPoint</code> was used instead.</p>
<script>
var svg = document.getElementsByTagName("svg")[0];
var circle = …
```

Add missing api.SVGGeometryElement.isPointInFill.point_parameter_DOMPoint feature

---

javascript/builtins/Intl/DateTimeFormat.json

This PR renames the `options_timeZone_parameter_iana` subfeature deep within the data of the `DateTimeFormat()` constructor to `iana_time_zones`.  This is because it is a subfeature of `options_timeZone_parameter`, so it is redundant to re-specify the parent feature's name.

Rename DateTimeFormat().options_timeZone_parameter_iana feature

---

javascript/builtins/Intl/DateTimeFormat.json

This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `DateTimeFormat.DateTimeFormat.options_parameter.options_timeZoneName_parameter.extended_values` member of the `Intl` JavaScript builtin. This fixes #14586, which contains the supporting evidence for this change.
Additional Notes: This also renames the feature to better represent what it is (it's not IANA time zone names).  Also fixes #15396, fixes #18405.

Update Chromium data for javascript.builtins.Intl.DateTimeFormat.DateTimeFormat.options_parameter.options_timeZoneName_parameter.extended_values

---

api/Window.json

This PR updates and corrects version values for Firefox and Firefox Android for the `deviceorientationabsolute_event` member of the `Window` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.5.2).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/Window/deviceorientationabsolute_event
Additional Notes: This fixes #19988.

Update Firefox data for api.Window.deviceorientationabsolute_event

---

css/properties/caret-color.json

This PR updates and corrects version values for Safari iOS/iPadOS for the `caret-color` CSS property. This fixes #15128, which contains the supporting evidence for this change.
Additional Notes: The behavior described had not been seen in any version of Safari iOS I had tested.  Additionally, the commit that fixed the bug landed in iOS 11.3.

Update Safari iOS data for caret-color CSS property

---

html/elements/td.json

This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `rowspan.rowspan_zero` member of the `td` HTML element. The data comes from a commit in the browser's source code, mapped to a version number using available tooling or via the commit timestamp.
Commit: https://chromiumdash.appspot.com/commit/93609285fd2b0f7fef0d27ad1cf2eca4b9956fc8
Additional Notes: Fixes #14282.

Update Chromium data for html.elements.td.rowspan.rowspan_zero

---

svg/attributes/presentation.json

This PR replaces `true`/`null` values with exact version numbers (or `false`) for Firefox and Firefox Android for the `fill-rule` member of the `presentation` SVG attribute. This fixes #13385, which contains the supporting evidence for this change.

Add Firefox versions for svg.attributes.presentation.fill-rule

---

svg/attributes/presentation.json

This PR replaces `true`/`null` values with exact version numbers (or `false`) for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `fill-rule` member of the `presentation` SVG attribute. This fixes #13385, which contains the supporting evidence for this change.

Add Chromium versions for svg.attributes.presentation.fill-rule

---

css/properties/justify-content.json

This PR updates and corrects version values for Opera and Opera Android for the `flex_context.start_end` member of the `justify-content` CSS property. This sets Opera to mirror from Chrome.

Update Opera data for css.properties.justify-content.flex_context.start_end

---

css/properties/align-items.json

This PR updates and corrects version values for Opera and Opera Android for the `flex_context.start_end` member of the `align-items` CSS property. This sets Opera to mirror from Chrome.

Update Opera data for css.properties.align-items.flex_context.start_end

---

api/Window.json

This PR updates and corrects version values for Firefox and Firefox Android for the `unhandledrejection_event` member of the `Window` API. This fixes #12750, which contains the supporting evidence for this change.

Update Firefox data for api.Window.unhandledrejection_event

---

api/InputEvent.json

This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `InputEvent` member of the `InputEvent` API. This fixes #12163, which contains the supporting evidence for this change.

Update Safari data for api.InputEvent.InputEvent

---

api/HTMLInputElement.json

This PR updates and corrects version values for Safari iOS/iPadOS for the `webkitdirectory` member of the `HTMLInputElement` API. The data comes from manual testing, running test code through BrowserStack, SauceLabs and custom VMs.
Test Code: https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/webkitdirectory
Additional Notes: This fixes #11982.

Update Safari iOS data for api.HTMLInputElement.webkitdirectory

---

css/types/length.json

This PR is a part of a project to add missing interfaces and interface features to BCD that are from an active spec (including WICG specs) and is supported in at least one browser. This particular PR adds the missing `em` member of the `length` CSS value type. This mirrors the data from `rem` (which is probably accurate enough for our needs).  Fixes #15293.

Add missing css.types.length.em feature

---

html/elements/input/datetime-local.json

This PR updates and corrects version values for Firefox and Firefox Android for the `type_datetime-local` member of the `input` HTML element. This fixes #16138, which contains the supporting evidence for this change.

Update Firefox data for html.elements.input.type_datetime-local

---

html/elements/input/datetime-local.json

This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `type_datetime-local` member of the `input` HTML element. Related to #16138 (see https://github.com/mdn/browser-compat-data/issues/21103#issuecomment-1840599505).
Additional Notes: 

Update Safari data for html.elements.input.type_datetime-local

---

css/properties/-webkit-mask-composite.json
css/properties/mask-composite.json

This PR updates and corrects version values for Firefox and Firefox Android for the `mask-composite` CSS property. This fixes #11885, which contains the supporting evidence for this change.

Update Firefox data for mask-composite CSS property

---

api/HTMLLinkElement.json
html/elements/link.json

Responsive preloads (`imagesrcset` and `imagesizes`) was enabled in Safari 17.2 but was incorrectly marked as supported from Safari 13.
This was changed in #21267 due to this comment: https://github.com/mdn/browser-compat-data/pull/21267#issuecomment-1830521858 but I'm not sure what that is based upon. It was behind a flag for a while, but wasn't enabled by default until 17.2 and [MDN encourages removal of flag details after it goes to stable](https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines/index.md#removal-of-irrelevant-flag-data). @jdatapple  @Elchi3 any comments here?
WPT here shows it isn't enabled on stable (currently still 17.1): https://wpt.fyi/results/preload/link-header-preload-imagesrcset.html?label=stable&label=master&aligned
It is enabled in Safari …

Update Safari imagesrcset and imagesizes

---

css/properties/text-wrap.json

I updated the safari text-wrap css properties to "preview" because STP supports the text-wrap CSS properties as of STP 182 and STP 183.

STP supports all of the text-wrap properties, except "pretty"

---

css/properties/justify-items.json
css/properties/justify-self.json
css/properties/place-content.json
css/properties/place-items.json
css/properties/place-self.json

Tag missing features as being part of flexbox:
- `css.properties.justfiy-items.flex_content`
- `css.properties.justfiy-self.flex_content`
- `css.properties.place-content.flex_content`
- `css.properties.place-items.flex_content`
- `css.properties.place-self.flex_content`
These are closely related. See the enclosed table to see how all of these features appeared in a relatively short time and are thus related as a group.
<details>
<summary>Baseline calculation for <code>flexbox</code></summary
| Key                                                                                                                | Baseline | Low since date | Versions                                                                                                                    |
| …

`web-features:flexbox`: correct tag group

---

css/selectors/-moz-first-node.json
css/selectors/-moz-focus-inner.json
css/selectors/-moz-last-node.json
css/selectors/-moz-list-bullet.json
css/selectors/-moz-list-number.json
css/selectors/-moz-progress-bar.json

This PR adds the missing `-moz-*` CSS selector. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.6.3).
Tests Used:
https://mdn-bcd-collector.gooborg.com/tests/css/selectors/-moz-first-node
https://mdn-bcd-collector.gooborg.com/tests/css/selectors/-moz-focus-inner
https://mdn-bcd-collector.gooborg.com/tests/css/selectors/-moz-last-node
https://mdn-bcd-collector.gooborg.com/tests/css/selectors/-moz-list-bullet
https://mdn-bcd-collector.gooborg.com/tests/css/selectors/-moz-list-number
https://mdn-bcd-collector.gooborg.com/tests/css/selectors/-moz-progress-bar

Add missing non-standard -moz-* CSS selector feature

---

css/selectors/-webkit-slider-runnable-track.json
css/selectors/-webkit-slider-thumb.json

This PR adds the missing `-webkit-slider-*` CSS selector. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.6.3).
Tests Used:
https://mdn-bcd-collector.gooborg.com/tests/css/selectors/-webkit-slider-runnable-track
https://mdn-bcd-collector.gooborg.com/tests/css/selectors/-webkit-slider-thumb

Add missing non-standard -webkit-slider-* CSS selector feature

---

css/properties/word-break.json

Chrome 119 supports ``word-break: auto-phrase`` for Japanese text.
Announced on the Chrome developer blog here: https://developer.chrome.com/blog/css-i18n-features
None

Add word-break: auto-phrase as of Chrome 119

---

api/MediaDevices.json

Chrome 119 adds desktop-only support for the [`getDisplayMedia()`](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getDisplayMedia) `monitorTypeSurfaces` option (see https://chromestatus.com/feature/5558622137876480). This PR adds BCD for it.
Other useful links:
- See https://screen-sharing-controls.glitch.me/ for a demo.
- See https://developer.chrome.com/docs/web-platform/screen-sharing-controls/#monitorTypeSurfaces for an explanation of its purpose

Add data for getDisplayMedia() monitorTypeSurfaces option

---

css/properties/text-wrap.json

`text-wrap: balance` supported in chrome version 114, not 117.
- https://caniuse.com/css-text-wrap-balance
- https://developer.chrome.com/blog/css-text-wrap-balance
#21311

text-wrap: balance; supported in chrome version 114, not 117

---

api/VideoTrack.json

This reverts commit 78a3dc1f4b661806fdf70d61133a13ab404dea9a.
Running the mdn-bcd-collector (v10.6.3) manually, it is evident that this API is still fully supported in Safari.

Revert "Update Safari data for VideoTrack API (#21193)"

---

css/properties/font-variant.json

This PR removes the `font-variant-emoji` member of the `font-variant` CSS property from BCD. This is already tracked in a separate file, where it is supposed to be tracked since it is a separate CSS property.
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/font-variant/font-variant-emoji

Remove css.properties.font-variant.font-variant-emoji from BCD

---

css/properties/hyphens.json

This PR renames `css.properties.hyphens.auto_value` to `css.properties.hyphens.auto` to better follow our usual convention.

Rename css.properties.hyphens.auto_value -> auto

---

css/properties/text-wrap.json

This PR updates and corrects version values for all browsers for the `text-wrap` CSS property. This removes the notes and `partial_implementation` from the property, as the lack of support for specific values is documented in the subfeatures.

Update all browsers data for text-wrap CSS property

---

scripts/release/changes.ts

This PR sets the release change collection concurrency to 1, as it does not seem to be parallelizing well.

Release change concurrency is not working as expected

---

api/HTMLIFrameElement.json

This PR is a part of a project to add missing interfaces and interface features to BCD that are from an active spec (including WICG specs) and is supported in at least one browser. This particular PR adds the missing `credentialless` member of the `HTMLIFrameElement` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.6.3).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/HTMLIFrameElement/credentialless

Add missing api.HTMLIFrameElement.credentialless feature

---

scripts/lib/pluralize.test.ts

This PR removes a test for chalk formatting within the pluralize lib.  It seems that at some point, chalk formatting no longer applied within GitHub Actions workflows, so [this broke the latest release](https://github.com/mdn/browser-compat-data/actions/runs/7221747578/job/19683149509).  (I can't find a commit that could have changed this in our codebase, so I have a feeling it was a change in GitHub Actions itself.)

Remove test for useChalk in pluralize lib

---

.github/workflows/release.yml
scripts/lib/pluralize.test.ts

This PR restores the unittest that was removed in #21635.  This also ensures that the test will not fail when running unittests during the release process.

Restore chalk formatting test for pluralize lib

---

javascript/operators/import.json
javascript/statements.json

This PR updates and corrects version values for NodeJS for the `import` member of the `statements` JavaScript feature. This fixes #15123, which contains the supporting evidence for this change.

Update NodeJS data for javascript.statements.import

---

html/elements/img.json

the incorrect mdn_url of `<img>` element `loading` attribute
normally, the attribute of html element will not specific a mdn_url, and it should not specific to a page of performance

 Remove the incorrect mdn_url of `<img>` element `loading` attribute

---

html/elements/hr.json
html/elements/select.json

Fixes https://github.com/mdn/browser-compat-data/issues/21648

Add <hr> in <select>

---

api/CSSImportRule.json
api/CharacterBoundsUpdateEvent.json
api/EditContext.json
api/HTMLElement.json
api/TextFormat.json
api/TextFormatUpdateEvent.json
api/TextUpdateEvent.json
css/selectors/grammar-error.json
css/selectors/spelling-error.json
javascript/builtins/Array.json

The Open Web Docs BCD collector found new features shipping in Chrome 121 beta. Currently, the collector covers about 82% of BCD, so the following list might not be exhaustive. Certain APIs that use enrollment etc. might not have been found either. For comparison, the Chromestatus list for Chrome 121 is here: https://chromestatus.com/features#milestone%3D121.
<hr>
With this PR, BCD marks the following features as shipping in Chrome 121: cc @chrisdavidmills 
- api.CSSImportRule.supportsText
- api.CharacterBoundsUpdateEvent
- api.CharacterBoundsUpdateEvent.CharacterBoundsUpdateEvent
- api.CharacterBoundsUpdateEvent.rangeEnd
- api.CharacterBoundsUpdateEvent.rangeStart
- api.ClipboardItem.supports_static
- api.EditContext
- api.EditContext.EditContext
- api.EditContext.attachedElements
- …

Updates for Chrome 121 beta

---

api/VideoPlaybackQuality.json

Found by the Open Web Docs BCD collector v10.6.3.
This is not supported in Webview, thus setting to mirror.

Update webview support for VideoPlaybackQuality.totalFrameDelay

---

css/properties/paint-order.json

Fix https://github.com/mdn/browser-compat-data/issues/21649 by setting Edge to "mirror" from Chrome.

Update Edge support for CSS paint-order

---

api/MediaRecorder.json

see https://w3c.github.io/mediacapture-record/, the `MediaRecorder` `warning` event is not in standard yet (also it does not has a `spec-url` key)

mark `MediaRecorder` `warning` event as non-standard
