mdn/browser-compat-data

browsers/uc_android.json, browsers/uc_chinese_android.json
On http://wap.uc.cn/verlist/english_354/ucbrowser/145:
```JavaScript
function scrape() {
var pairs = [].map.call(document.querySelectorAll('.prolist li'), li => [
li.querySelector('.f17').textContent.replace(/^UC Browser/, ''),
li.querySelector('.f15').textContent
]);
var current_version = pairs[0][0];
pairs.reverse();
var releases = {};
for (var [version, date] of pairs) {
releases[version] = {
release_date: date,
status: version == current_version ? 'current' : 'retired'
};
}
var data = { browsers: { uc_android: { name: 'UC Browser', releases: releases } } };
return JSON.stringify(data, null, 2);
}
```
On http://wap.uc.cn/verlist/chinese_999/ucbrowser/145:
```JavaScript
function scrape() {
var pairs = [].map.call(document.querySelectorAll('.prolist li'), li => [ …
```
=> Update UC Browser releases

api/PerformanceNavigation.json
[PerformanceNavigation](https://developer.mozilla.org/docs/Web/API/PerformanceNavigation)
=> Add compat data for api.PerformanceNavigation

api/PerformanceMeasure.json
[PerformanceMeasure](https://developer.mozilla.org/docs/Web/API/PerformanceMeasure)
=> Add compat data for api.PerformanceMeasure

mathml/elements/semantics.json
https://developer.mozilla.org/en-US/docs/Web/MathML/Element/semantics
=> Add MathML <semantics> element

mathml/elements/munderover.json
https://developer.mozilla.org/en-US/docs/Web/MathML/Element/munderover
=> Add MathML <munderover> element

api/ValidityState.json
https://developer.mozilla.org/en-US/docs/Web/API/ValidityState
=> Add compat data for ValidityState

mathml/elements/munder.json
This adds the browser compatibility table data for the [`<munder>` MathML element](https://developer.mozilla.org/docs/Web/MathML/Element/munder).
=> Add <munder>

javascript/operators/arithmetic.json, javascript/operators/assignment.json
add compatibility information for Safari (source http://kangax.github.io/compat-table/es2016plus/)
=> add safari compatibility

css/at-rules/font-face.json
As per https://bugzilla.mozilla.org/show_bug.cgi?id=1436061
=> adding support details for new font-weight, font-style, and font-stretch descriptor syntax

api/DragEvent.json
[DragEvent](https://developer.mozilla.org/docs/Web/API/DragEvent)
=> Web APIs: add DragEvent

api/DOMImplementation.json
https://developer.mozilla.org/en-US/docs/Web/API/DOMImplementation
=> add compat data for DOMImplementation

css/at-rules/viewport.json
* [min-zoom](https://developer.mozilla.org/en-US/docs/Web/CSS/@viewport/min-zoom)
* [max-zoom](https://developer.mozilla.org/en-US/docs/Web/CSS/@viewport/max-zoom)
* [user-zoom](https://developer.mozilla.org/en-US/docs/Web/CSS/@viewport/user-zoom)
=> CSS/@viewport: add (min|max|user)-zoom

api/RTCRtpSender.json
Update replaceTrack API support information for chrome and safari
=> update replaceTrack API support version

api/HTMLCollection.json
[HTMLCollection](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCollection)
The MDN page doesn't contain legacy data, so I looked the implementations up in the Chrome & Firefox repositories.
=> Web APIs: add HTMLCollection

api/MediaSettingsRange.json
https://developer.mozilla.org/en-US/docs/Web/API/MediaSettingsRange
=> add compat data for MediaSettingsRange

api/DOMConfiguration.json
https://developer.mozilla.org/en-US/docs/Web/API/DOMConfiguration
=> adding DOMConfiguration data to BCD

api/DOMImplementationList.json
https://developer.mozilla.org/en-US/docs/Web/API/DOMImplementationList
=> Adding DOMIMplementationList data to BCD

package-lock.json, package.json
Incorporates circular embedding fix using `--bcd-module` CLI parameter in mdn-confluence's generate script.
=> Update npm-confluence dependency

api/DOMErrorHandler.json
https://developer.mozilla.org/en-US/docs/Web/API/DOMErrorHandler
=> Add compat data for DOMErrorHandler

api/DOMMatrix.json, api/DOMMatrixReadOnly.json
As seen at
* https://developer.mozilla.org/en-US/docs/Web/API/DOMMatrix
* https://developer.mozilla.org/en-US/docs/Web/API/DOMMatrixReadOnly
=> Adding DOMMatrix and DOMMatrixReadOnly data to BCD

api/PermissionStatus.json
https://developer.mozilla.org/docs/Web/API/PermissionStatus
=> add compat data for PermissionStatus

api/CSSStyleDeclaration.json
Sources:
1. CSS Object Model specification:
https://drafts.csswg.org/cssom/#the-cssstyledeclaration-interface
2. Chromium repository:
https://github.com/chromium/chromium/blob/1182c84d9849940a6f6be3ec22d8b244dc554a53/third_party/blink/renderer/core/css/css_style_declaration.idl
https://chromium.googlesource.com/chromium/src/+/ca8687a29947918259b06067dbc6b412582c4c3c%5E%21/third_party/WebKit/WebCore/css/CSSStyleDeclaration.idl
3. Firefox repository:
https://github.com/mozilla/gecko-dev/blob/04b9cbbc2be2137a37e158a5ebaf9c7bef2364f9/dom/webidl/CSSStyleDeclaration.webidl
https://github.com/mozilla/gecko-dev/commit/7cff1485c880669fcaa2041b81574c45e6392753#diff-3ba774067d5fc9b261902177c4a0aa0d
=> API: add CSSStyleDeclaration

api/Request.json, api/RequestDestination.json
Adds this plus RequestDestination for Firefox 61.
=> Bug 1402892 - Add Request.destination

api/DOMRect.json, api/DOMRectReadOnly.json
As seen at:
* https://developer.mozilla.org/en-US/docs/Web/API/DOMRect
* https://developer.mozilla.org/en-US/docs/Web/API/DOMRectReadOnly
=> adding DOMRect and DOMRectReadOnly data to BCD

api/PictureInPicture.json
I apologize for the repeat. This is why I don't like to submit feature data before stable.
=> Correct Picture-in-Picture.

webextensions/manifest/theme.json
Added support information for tab_background_separator as described in [#1459455](https://bugzilla.mozilla.org/show_bug.cgi?id=1459455)
=> Added support information for tab_background_separator

api/UserProximityEvent.json
https://developer.mozilla.org/en-US/docs/Web/API/UserProximityEvent
=> Add compat data for UserProximityEvent

html/elements/input/date.json
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date
=> Add compat data for input-date

html/elements/input/reset.json
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/reset
=> Add compat data for input-reset

html/elements/input/submit.json
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/submit
=> Add compat data for input-submit

html/elements/input/text.json
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/text
=> Add compat data for input-text

html/elements/input/url.json
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/url
=> Add compat data to input-url

api/Console.json, api/OffscreenCanvas.json, api/Response.json, api/WindowEventHandlers.json
Updates the following:
- `api/Console`
- `api/OffscreenCanvas`
- `api/Response`
- `api/WindowEventHandlers`
Part of #519.
=> Add missing status info for a few APIs.

api/CSSImageValue.json, api/CSSKeywordValue.json, api/CSSMathInvert.json, api/CSSMathMax.json, api/CSSMathMin.json, api/CSSMathNegate.json, api/CSSMathProduct.json
https://www.chromestatus.com/feature/5682491075592192
https://drafts.css-houdini.org/css-typed-om/
=> CSS Object Model (Houdini), Part I.

api/CSSMathSum.json, api/CSSMathValue.json, api/CSSMatrixComponent.json, api/CSSNumericArray.json, api/CSSNumericValue.json, api/CSSPerspective.json, api/CSSPositionValue.json
https://www.chromestatus.com/feature/5682491075592192
https://drafts.css-houdini.org/css-typed-om/
=> CSS Object Model (Houdini), Part II.

api/CanMakePaymentEvent.json, api/PaymentInstruments.json, api/PaymentManager.json
Apologies. This redoes some information I submitted yesterday. I made some mistakes in my interpretation of the code base.
=> Compat data for Payment Handler API.

api/Document.json
https://github.com/WICG/page-lifecycle
https://www.chromestatus.com/features/5644602711212032
=> Add 'Page Lifecycle' to Document.

api/CSS.json
https://developer.mozilla.org/en-US/docs/Web/API/CSS
=> Add compat data for CSS

api/RTCIceCandidateInit.json
Adds RTCIceCandidateInit.json for my work on finishing
documentation for RTCIceCandidate and its associated
types and such.
=> Add RTCIceCandidateInit dictionary

api/CSSRotate.json, api/CSSScale.json, api/CSSSkew.json, api/CSSSkewX.json, api/CSSSkewY.json, api/CSSStyleValue.json, api/CSSTransformComponent.json
https://www.chromestatus.com/feature/5682491075592192
https://drafts.css-houdini.org/css-typed-om/
=> CSS Object Model (Houdini), Part III.

api/CanvasCaptureMediaStreamTrack.json
Rename this interface which was originally mis-named in
our docs.
=> CanvasCaptureMediaStream -> CanvasCaptureMediaStreamTrack

api/PaymentDetailsBase.json, api/PaymentDetailsInit.json, api/PaymentDetailsUpdate.json
These are dictionaries for the Web Payments API.
=> Add PaymentDetailsBase and PaymentDetailsUpdate.

api/CanvasRenderingContext2D.json
Updated browser compatibility for this method.
=> isPointInStroke

browsers/firefox.json, browsers/firefox_android.json
=> Firefox 60 is ESR, not Retired

html/elements/input/email.json
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/email
=> Add compat data for input-email

html/elements/input/file.json
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file
=> Add compat data for input-file

html/elements/input/hidden.json
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/hidden
=> Add compat data for input-hidden

html/elements/input/number.json
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number
=> Add compat data for input-number

html/elements/input/image.json
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/image
=> Add compat data for input-image

html/elements/input/radio.json
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/radio
=> Add compat data for input-radio

html/elements/input/month.json
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/month
=> Add compat data for input-month

api/FormData.json
https://w3c-test.org/xhr/formdata.htm
https://w3c-test.org/xhr/formdata-set.htm
https://w3c-test.org/xhr/formdata-has.htm
https://w3c-test.org/xhr/formdata-get.htm
https://w3c-test.org/xhr/formdata-foreach.html
https://w3c-test.org/xhr/formdata-delete.htm
https://w3c-test.org/xhr/formdata-blob.htm
=> safari has more formdata support now

http/headers/server-timing.json
https://bugzilla.mozilla.org/show_bug.cgi?id=1413999
https://www.chromestatus.com/features/5695708376072192
=> Add Server-Timing header

api/TreeWalker.json
https://developer.mozilla.org/en-US/docs/Web/API/TreeWalker
=> Add compat data for TreeWalker (DOM)

schemas/compat-data-schema.md
OK this was kinda tough to actually spell out, but I figured we should give some kind guidance on how you're supposed to sort support statements, at least until we have some kind of automated check. Thanks!
=> Document strategy for sorting support statements

javascript/builtins/JSON.json
https://bugzilla.mozilla.org/show_bug.cgi?id=1435828
https://www.chromestatus.com/features/6102319234023424
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON#JavaScript_and_JSON_differences
=> Add JSON superset compat data

api/LocalFileSystemSync.json
https://developer.mozilla.org/en-US/docs/Web/API/LocalFileSystemSync
=> Add compat data for LocalFileSystemSync

api/LocalFileSystem.json
https://developer.mozilla.org/en-US/docs/Web/API/LocalFileSystem
=> Add browser compat data for LocalFileSystem

api/FileSystemSync.json
https://developer.mozilla.org/en-US/docs/Web/API/FileSystemSync
=> Add compat data for FileSystemSync

api/FileSystemFlags.json
https://developer.mozilla.org/en-US/docs/Web/API/FileSystemFlags
=> Add compat data for FileSystemFlags

api/FileSystemFileEntry.json
https://developer.mozilla.org/en-US/docs/Web/API/FileSystemFileEntry
=> Add compat data for FileSystemFileEntry

api/FileSystemDirectoryReader.json
https://developer.mozilla.org/en-US/docs/Web/API/FileSystemDirectoryReader
=> Add compat data for FileSystemDirectoryReader

api/FileSystemDirectoryEntry.json
https://developer.mozilla.org/en-US/docs/Web/API/FileSystemDirectoryEntry
=> Add compat data for FileSystemDirectoryEntry

api/FileSystem.json
https://developer.mozilla.org/en-US/docs/Web/API/FileSystem
=> Add compat data for FileSystem

api/FileReaderSync.json
https://developer.mozilla.org/en-US/docs/Web/API/FileReaderSync
=> Add compat data for FileReaderSync

api/FileReader.json
https://developer.mozilla.org/en-US/docs/Web/API/FileReader
=> Add compat data for FileReader

api/Notation.json
Sources:
1. DOM Level 3 Core specification:
https://www.w3.org/TR/DOM-Level-3-Core/core.html#ID-5431D1B9
2. MDN article:
https://developer.mozilla.org/en-US/docs/Web/API/Notation
=> API: add Notation

api/Navigator.json
[Navigator](https://developer.mozilla.org/en-US/docs/Web/API/Navigator)
Done
=> Add compat data for api.Navigator

api/Window.json
See https://bugzilla.mozilla.org/show_bug.cgi?id=1467722
=> Note getComputedStyle behavior

api/History.json
[History](https://developer.mozilla.org/docs/Web/API/History)
=> API: add History

api/TrackDefaultList.json
https://developer.mozilla.org/en-US/docs/Web/API/TrackDefaultList
=> Add compat data for TrackDefaultList

api/MediaTrackConstraints.json
https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackConstraints
=> Add compat data for MediaTrackConstraints

api/FormData.json
https://developer.mozilla.org/en-US/docs/Web/API/FormData/FormData
The constructor wasn't included in #1487.
=> Add missing FormData() constructor

README.md
- https://code.visualstudio.com
- https://code.visualstudio.com/updates/v1_25#_improved-accuracy-of-browser-compatibility-data
=> Add “Visual Studio Code” to “Projects using the data”

webextensions/api/browserSettings.json
See:
https://bugzilla.mozilla.org/show_bug.cgi?id=1344749
and
https://hg.mozilla.org/mozilla-central/diff/aee255d8336c/toolkit/components/extensions/schemas/browser_settings.json
and
https://bugzilla.mozilla.org/show_bug.cgi?id=1344749#c123
No docs page yet.
=> Add data for newTabPosition

api/XSLTProcessor.json
This completes the browser compatibility table data for the [`XSLTProcessor` API](https://developer.mozilla.org/docs/Web/API/XSLTProcessor).
=> Complete XSLTProcessor

api/SourceBuffer.json
Add BCD info for SourceBuffer methods appendBufferAsync()
and removeAsync().
=> Bug 1280613 - Async append/remove for SourceBuffer

api/TouchList.json
https://developer.mozilla.org/en-US/docs/Web/API/TouchList
=> Add compat data for TouchList

api/GeometryUtils.json
https://developer.mozilla.org/en-US/docs/Web/API/GeometryUtils
=> Add compat data for GeometryUtils

html/elements/input/range.json
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/range
=> Add compat data for input-range

http/headers/accept-ch-lifetime.json, http/headers/accept-ch.json, http/headers/content-dpr.json, http/headers/device-memory.json, http/headers/downlink.json, http/headers/dpr.json, http/headers/ect.json, http/headers/rtt.json, http/headers/save-data.json, http/headers/viewport-width.json, http/headers/width.json
https://www.chromestatus.com/features#client%20hints
=> Add client hint headers.

css/properties/text-align.json
See [Alignment and Justification](https://drafts.csswg.org/css-text-4/#alignment) in the CSS Text Module Level 4 specification.
=> Add text-align’s <string> value

.gitignore
Just adding this in a separate PR so as not to confuse PR's.
Added this to git so these project-settings aren't accidentally added by others in the future
=> chore(repo): Git ignore idea (intelliJ, webstorm etc) settings files

api/RTCPeerConnection.json
https://bugs.chromium.org/p/chromium/issues/detail?id=685727
=> Add note about default rtcpMuxPolicy in Chrome.

api/DOMStringMap.json
Sorry, couldn't run 'npm run lint' as it failed to execute the lint file on my system. Kindly do notify of any discrepancies and advice since this is my first open source commit. :)
=> DOMStringMap json file added

javascript/builtins/Reflect.json, javascript/functions.json, javascript/operators/yield.json, javascript/operators/yield_star.json, javascript/statements.json
See https://node.green/#ES2015-built-ins-Reflect
https://node.green/#ES2015-syntax-default-function-parameters-basic-functionality
https://node.green/#ES2015-functions-generators
=> nodejs data: Reflect, yield, default args

CONTRIBUTING.md
I will be on vacation from July 21 to August 6. I hope this helps @ddbeck and the MDN team to continue bcd releases during my holidays.
=> Add docs for publishing a new package version

api/Document.json
As encountered when exploring https://bugzilla.mozilla.org/show_bug.cgi?id=1473629
=> adding strange information about getElementsByName method

api/InputEvent.json
[InputEvent](https://developer.mozilla.org/docs/Web/API/InputEvent)
=> Add compat data for InputEvent

api/FileSystemEntry.json
https://developer.mozilla.org/en-US/docs/Web/API/FileSystemEntry
=> Add compat data for FileSystemEntry

http/headers/x-forwarded-for.json, http/headers/x-forwarded-host.json, http/headers/x-forwarded-proto.json
The headers are not part of any current specification
and it is unclear how to determine compatibility.
=> HTTP/Headers: add X-Forwarded-(For|Host|Proto)

http/headers/proxy-authenticate.json, http/headers/www-authenticate.json
Sources:
1. Chromium bug tracker:
https://crbug.com/2346
2. Chromium repository:
https://chromium.googlesource.com/chromium/src/+/c3b35c2100dba30c517116bc9a5a4e4149c3a8e5%5E%21/net/http/http_auth.cc
3. Firefox repository:
https://github.com/mozilla/gecko-dev/commit/199c44a73785c22c2b674184833d5c6ee085e9ae
=> HTTP/Headers: add (Proxy|WWW)-Authenticate

api/DOMPointInit.json
Used by DOMPoint and DOMPointReadOnly for both
fromPoint() and toJSSON().
=> Add DOMPointInit dictionary

api/DragEvent.json
Sources:
1. Chromium bug tracker:
https://crbug.com/498504
2. Chromium repository:
chromium/chromium@77fa733
3. Firefox repository:
mozilla/gecko-dev@a6d6c66
=> API/DragEvent: add Constructor + fix Chrome/Opera version_added

api/CSSKeyframeRule.json
https://developer.mozilla.org/en-US/docs/Web/API/CSSKeyframeRule
=> adding compat data for CSSKeyframeRule

api/RadioNodeList.json
https://developer.mozilla.org/en-US/docs/Web/API/RadioNodeList
=> Add compat data for RadioNodeList

api/CSSRuleList.json
Sources:
1. DOM Level 2 CSS specification:
https://www.w3.org/TR/DOM-Level-2-Style/css.html#CSS-CSSRuleList
2. Chromium repository:
https://github.com/chromium/chromium/blob/796fbec9d0a8b8b86c6b49266ee5856b440bf154/third_party/blink/renderer/core/css/css_rule_list.idl
https://chromium.googlesource.com/chromium/src/+/1a1a5db5f6244052b56b7172916053493ed89ffe%5E%21/third_party/WebKit/WebCore/css/CSSRuleList.idl
3. Firefox bug tracker:
https://bugzil.la/35610
https://bugzil.la/892489
4. Firefox repository:
https://github.com/mozilla/gecko-dev/blob/86897859913403b68829dbf9a154f5a87c4b0638/dom/webidl/CSSRuleList.webidl
https://github.com/mozilla/gecko-dev/commit/5264639fd4adeef65f4d2d36436a648a7fbf03d4
=> API: add CSSRuleList

api/CSSKeyframesRule.json
https://developer.mozilla.org/en-US/docs/Web/API/CSSKeyframesRule
Not to be confused with csskeyFRAMErule.
=> adding compat data for CSSKeyframesRule

api/CSSMatrix.json
https://developer.mozilla.org/en-US/docs/Web/API/CSSMatrix
=> adding compat data for CSSMatrix

api/CSSMediaRule.json
https://developer.mozilla.org/en-US/docs/Web/API/CSSMediaRule
=> adding compat data for CSSMediaRule

api/CloseEvent.json
[CloseEvent](https://developer.mozilla.org/en-US/docs/Web/API/CloseEvent#Browser_compatibility)
=> API: add CloseEvent

api/ProcessingInstruction.json
Sources:
1. DOM Living Standard:
https://dom.spec.whatwg.org/#processinginstruction
2. Chrome repository:
https://github.com/chromium/chromium/blob/40e856b910e02f7d0f2644b3ab5204568806706b/third_party/WebKit/WebCore/dom/ProcessingInstruction.idl
3. Firefox bug tracker:
https://bugzil.la/740069
4. Firefox repository:
https://github.com/mozilla/gecko-dev/blob/ed510d35069e2e48c5ec411d99e3dab89400f1b3/dom/webidl/ProcessingInstruction.webidl
=> API: add ProcessingInstruction

api/Document.json
As per https://bugzilla.mozilla.org/show_bug.cgi?id=819475
=> adding note about non-nullable document.domain

api/Navigator.json
https://developer.mozilla.org/en-US/docs/Web/API/Navigator/maxTouchPoints
This wasn't included in #2069. The data is a bit weird, but I think I represented it correctly here.
=> Add missing Navigator.maxTouchPoints subfeature

api/StorageManager.json
See https://chromium.googlesource.com/chromium/src/+/0b5bf0fd87c2dad9b2c7223a20f2b8b7756f3e57%5E%21/third_party/WebKit/Source/modules/quota/StorageManager.idl
=> fix typos in api/StorageManager.json

api/ProgressEvent.json
Sources:
- https://developer.mozilla.org/en-US/docs/Web/API/ProgressEvent
- https://developer.mozilla.org/en-US/docs/Web/API/ProgressEvent/lengthComputable
- https://developer.mozilla.org/en-US/docs/Web/API/ProgressEvent/loaded
- https://developer.mozilla.org/en-US/docs/Web/API/ProgressEvent/total
-  https://developer.mozilla.org/en-US/docs/Web/API/ProgressEvent/initProgressEvent
=> ProgressEvent: add MDN data + sub-features constructor & initProgressEvent

api/ProgressEvent.json
This fixes the failing CI on master.
=> ProgressEvent: fix constructor description

api/InputDeviceCapabilities.json
https://developer.mozilla.org/en-US/docs/Web/API/InputDeviceCapabilities
=> Add compat data for InputDeviceCapabilities

api/HTMLMenuElement.json
Sources:
1. HTML 5 Specifications:
https://dev.w3.org/html5/spec-LC/interactive-elements.html#the-menu-element
https://html.spec.whatwg.org/multipage/grouping-content.html#the-menu-element
2. Manual tests on:
- Chromium 66
- Firefox 59
- Opera 60
=> API: add HTMLMenuElement

api/Selection.json
https://developer.mozilla.org/en-US/docs/Web/API/Selection/toString
This was missed in #1738.
=> Add toString subfeature for Selection API.

http/headers/upgrade-insecure-requests.json
See https://caniuse.com/#feat=upgradeinsecurerequests & https://developer.microsoft.com/en-us/microsoft-edge/platform/status/cspupgradeinsecurerequestsdirective/
=> upgrade insecure requests was added in Edge 17

api/Request.json, api/RequestDestination.json
Source: https://www.chromestatus.com/feature/5629697845100544
=> Adding support for Request.destination in Chrome, Opera and Edge

api/HTMLFormElement.json
Adds the missing sub-features for [HTMLFormElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement).
=> HTMLFormElement: add sub-features

api/HTMLMenuItemElement.json
Sources:
1. HTML 5.1 Specification:
https://www.w3.org/TR/html51/interactive-elements.html#htmlmenuitemelement-htmlmenuitemelement
2. Manual tests on:
- Chromium 66
- Firefox 59
- Opera 60
=> API: add HTMLMenuItemElement

javascript/builtins/Array.json, javascript/builtins/ArrayBuffer.json, javascript/builtins/DataView.json, javascript/builtins/Float32Array.json, javascript/builtins/Float64Array.json, javascript/builtins/Int16Array.json, javascript/builtins/Int32Array.json, javascript/builtins/Int8Array.json, javascript/builtins/Map.json, javascript/builtins/Math.json, javascript/builtins/Number.json, javascript/builtins/Set.json, javascript/builtins/String.json, javascript/builtins/TypedArray.json, javascript/builtins/Uint16Array.json, javascript/builtins/Uint32Array.json, javascript/builtins/Uint8Array.json, javascript/builtins/Uint8ClampedArray.json, javascript/builtins/WeakMap.json, javascript/builtins/WeakSet.json, javascript/grammar.json
Data was copied from [node-compat-table](/williamkapke/node-compat-table) (the basis for [node.green](https://node.green/)) using [nct2bcd](/jcsahnwaldt/nct2bcd).
=> Node.js: lots of data copied from node-compat-table

.npmignore, .vscode/extensions.json, .vscode/settings.json
Since VisualStudio Code is listed among the projects using this data, and I use it to contribute to this repository and recommended it [a few times](https://github.com/mdn/browser-compat-data/pull/2439#issuecomment-403648306) to [some first time contributors](https://github.com/mdn/browser-compat-data/pull/2153#issuecomment-392289436), I decided to add [Workspace Extension Recommendations](https://code.visualstudio.com/docs/editor/extension-gallery#_workspace-recommended-extensions) and basic settings for some of those extensions.
- [ESLint](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint) – Integrates ESLint into VS Code to highlight issues in JavaScript files.
- [EditorConfig for VS Code](https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorCo …
=> Add VisualStudio Code extension recommendations and basic settings

javascript/builtins/Array.json
See https://github.com/mdn/browser-compat-data/pull/2534#discussion_r208582006 and https://github.com/mdn/browser-compat-data/pull/2486#discussion_r203349143
=> js/builtins/Array.json#values: better notes text

css/at-rules/media.json
https://bugzilla.mozilla.org/show_bug.cgi?id=1444139
This is a new pull request, as my previous PR had a few branch changes merged in.
=> removed flag requirement in FF63 for -webkit-dpr

css/properties/column-gap.json, css/properties/gap.json, css/properties/row-gap.json
Follow up to #2381, #2184 and #1990.
review?(@ddbeck, @Elchi3)
=> Fix `gap` and `row‑gap` support in Flex context

api/MimeTypeArray.json
https://developer.mozilla.org/en-US/docs/Web/API/MimeTypeArray
=> Add compat data for MimeTypeArray

webextensions/manifest/options_ui.json
Uplifted from #2154.
review?(@Elchi3, @wbamberg)
=> refactor(we.mf.options_ui): Merge `chrome_style` into `browser_style`

api/Document.json
=> feat(api.Document): Add `Document.registerElement(…)`

api/NamedNodeMap.json
https://developer.mozilla.org/en-US/docs/Web/API/NamedNodeMap
=> adding compat data for NamedNodeMap

api/BluetoothRemoteGATTServer.json
https://developer.mozilla.org/en-US/docs/Web/API/BluetoothRemoteGATTServer
=> adding compat data for BluetoothRemoteGATTServer

api/BluetoothRemoteGATTCharacteristic.json
https://developer.mozilla.org/en-US/docs/Web/API/BluetoothRemoteGATTCharacteristic
=> adding compat data for BluetoothRemoteGATTCharacteristic

api/TextDecoder.json
[TextDecoder](https://developer.mozilla.org/docs/Web/API/TextDecoder)
=> Add compat data for api.TextDecoder

api/MessageChannel.json
https://developer.mozilla.org/en-US/docs/Web/API/MessageChannel
=> Add compat data for MessageChannel

api/MessagePort.json
https://developer.mozilla.org/en-US/docs/Web/API/MessagePort
=> Add compat data for MessagePort

api/BluetoothRemoteGATTService.json
https://developer.mozilla.org/en-US/docs/Web/API/BluetoothRemoteGATTService
=> Add compat data for BluetoothRemoteGATTService

api/MimeType.json
https://developer.mozilla.org/en-US/docs/Web/API/MimeType
=> Add compat data for MimeType

api/Plugin.json
https://developer.mozilla.org/en-US/docs/Web/API/Plugin
=> Add compat data for Plugin

api/PluginArray.json
https://developer.mozilla.org/en-US/docs/Web/API/PluginArray
=> Add compat data for PluginArray

api/PageTransitionEvent.json
https://developer.mozilla.org/en-US/docs/Web/API/PageTransitionEvent
=> Add compat data for PageTransitionEvent

api/Metadata.json
https://developer.mozilla.org/en-US/docs/Web/API/Metadata
=> Add compat data for Metadata

api/Position.json
https://developer.mozilla.org/docs/Web/API/Position
=> add compat data for Position

api/PromiseRejectionEvent.json
https://developer.mozilla.org/en-US/docs/Web/API/PromiseRejectionEvent
=> Add compat data for PromiseRejectionEvent

webextensions/api/browserAction.json
=> Firefox 62 allows a windowId parameter in browserAction methods

webextensions/api/extension.json
References:
- https://bugzilla.mozilla.org/show_bug.cgi?id=1208596
- https://searchfox.org/mozilla-central/diff/6359cf10d62300a32d0c1aaddb2b57133939f6ad/toolkit/components/extensions/schemas/extension.json#34
=> Add "sidebar" to extension.ViewType

webextensions/manifest/browser_action.json
See https://docs.microsoft.com/en-us/microsoft-edge/extensions/api-support/supported-manifest-keys#recommended-keys and #2540 for more information.
=> Add Microsoft Edge notes to `browser_action.default_area`

api/ExtendableMessageEvent.json
[ExtendableMessageEvent](https://developer.mozilla.org/docs/Web/API/ExtendableMessageEvent)
=> Add compat data for ExtendableMessageEvent

api/Element.json
This was missed in #2495 because the page was created after the original PR. https://developer.mozilla.org/en-US/docs/Web/API/Element/toggleAttribute
=> Add Element.toggleAttribute subfeature.

api/RTCRtpTransceiverDirection.json
https://developer.mozilla.org/en-US/docs/Web/API/RTCRtpTransceiverDirection
Based on the table in the article.
=> Add compat data for RTCRtpTransceiverDirection

api/Bluetooth.json, api/BluetoothAdvertisingData.json, api/BluetoothCharacteristicProperties.json, api/BluetoothDevice.json, api/BluetoothRemoteGATTDescriptor.json, api/BluetoothRemoteGATTService.json
See #2609 and https://github.com/WebBluetoothCG/web-bluetooth/issues/406.
=> fix(api.Bluetooth): Complete Web Bluetooth API

api/DataTransfer.json
[DataTransfer](https://developer.mozilla.org/docs/Web/API/DataTransfer)
=> API: add DataTransfer

api/WheelEvent.json
[WheelEvent](https://developer.mozilla.org/docs/Web/API/WheelEvent)
=> Add compat data to api.WheelEvent

api/MSGestureEvent.json
I've omitted the nonstandard event types as I'm unsure what to add with no original table.
https://developer.mozilla.org/en-US/docs/Web/API/MSGestureEvent
=> Add compat data for MSGestureEvent

api/Navigator.json, api/ServiceWorker.json, api/ServiceWorkerContainer.json, api/ServiceWorkerMessageEvent.json, api/ServiceWorkerRegistration.json
=> fix(api.ServiceWorker): Fix Microsoft Edge compat data

api/DataTransferItem.json
[DataTransferItem](https://developer.mozilla.org/docs/Web/API/DataTransferItem)
(See also #1764 with the identical `__compat` data.)
=> API: add DataTransferItem

api/DataTransferItemList.json
[DataTransferItemList](https://developer.mozilla.org/docs/Web/API/DataTransferItemList)
(See also #1763 with the identical `__compat` data.)
=> API: add DataTransferItemList

api/RTCDataChannel.json
Add an "sctp-sdp-21" feature that indicates support for
the updated format.
Also rearranged a bunch of items to be roughly in
alphabetical order. I may have missed some but really,
it was beyond scope for this change anyway so I'd prefer
not to have to update more of them if I missed any. :)
=> Update RTCDataChannel for bug 1335206

api/EventSource.json
[EventSource page](https://developer.mozilla.org/docs/Web/API/EventSource)
=> Add compat data for EventSource

api/UIEvent.json
[UIEvent](https://developer.mozilla.org/docs/Web/API/UIEvent)
=> Add compat data for api.UIEvent

api/WebSocket.json
Sources:
1. MDN compat data (legacy table + inline boxes):
https://developer.mozilla.org/en-US/docs/Web/API/WebSocket
2. Firefox commit data:
https://github.com/mozilla/gecko-dev/
=> API: add WebSocket

api/Node.json
New pull request because of the [previously messed up rebase](https://github.com/mdn/browser-compat-data/pull/1666)
=> Add node methods

api/MouseScrollEvent.json, api/MouseWheelEvent.json
[MouseScrollEvent](https://developer.mozilla.org/docs/Web/API/MouseScrollEvent)
[MouseWheelEvent](https://developer.mozilla.org/docs/Web/API/MouseWheelEvent)
=> Add compat data for apis MouseScrollEvent and MouseWheelEvent

api/BluetoothDevice.json
https://developer.mozilla.org/en-US/docs/Web/API/BluetoothDevice
=> Fix BluetoothDevice URL

api/BluetoothRemoteGATTServer.json
https://developer.mozilla.org/en-US/docs/Web/API/BluetoothRemoteGATTServer/device
=> Correct devices -> device

api/Screen.json
https://developer.mozilla.org/en-US/docs/Web/API/Screen
=> Add compat data for Screen

api/HTMLHyperlinkElementUtils.json
https://developer.mozilla.org/en-US/docs/Web/API/HTMLHyperlinkElementUtils
=> HtmlHyperlinkElementUtils

api/HTMLImageElement.json
Did not include IE Mobile data as I could not find a row for it
=> Adding compatibility data for HTMLImageElement

api/Permissions.json
[Permissions](https://developer.mozilla.org/en-US/docs/Web/API/Permissions)
- https://developer.mozilla.org/en-US/docs/Web/API/Permissions
- https://w3c.github.io/permissions/
- https://cs.chromium.org/chromium/src/third_party/blink/renderer/modules/permissions/permissions.cc
- https://dxr.mozilla.org/mozilla-central/source/dom/permission/Permissions.cpp
- https://bugzilla.mozilla.org/show_bug.cgi?id=1105827
- https://bugzilla.mozilla.org/show_bug.cgi?id=1197461
=> API: add Permissions

api/GlobalEventHandlers.json
[GlobalEventHandlers](https://developer.mozilla.org/en-US/Web/API/GlobalEventHandlers)
=> Add compat data for GlobalEventHandlers

api/Document.json, api/HTMLIFrameElement.json, api/Policy.json
https://www.chromestatus.com/feature/5190687460950016
=> Add feature policy JS API.

http/headers/feature-policy.json
Sorry for the corrections. The feature policy stuff has some unusual aspects.
=> Correct sensor policies.

api/SecurityPolicyViolationEvent.json
See https://bugzilla.mozilla.org/show_bug.cgi?id=1472661
Updates https://developer.mozilla.org/en-US/docs/Web/API/SecurityPolicyViolationEvent (and sub pages)
=> Firefox 63 ships SecurityPolicyViolationEvent (bug 1472661)

html/elements/slot.json
=> fix(html.elements.slot): Firefox supports the [name] attribute

api/NonDocumentTypeChildNode.json
https://developer.mozilla.org/en-US/docs/Web/API/NonDocumentTypeChildNode
=> Fix mdn_url for NonDocumentTypeChildNode.nextElementSibling

api/URLSearchParams.json
https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/toString
=> Fix mdn_url for URLSearchParams.toString

css/selectors/type.json, css/selectors/universal.json
=> fix(css.selectors): Correct spelling mistakes in `Namespaces`

api/HTMLImageElement.json
https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/Image
=> Add HTMLImageElement.Image() constructor.

css/properties/align-content.json, css/properties/align-items.json, css/properties/align-self.json, css/properties/justify-content.json
Adding the data for the safe / unsafe keywords for the alignment properties in FLexbox
=> Safe unsafe keywords

api/Document.json
Add more `exitFullscreen` data. Based on https://caniuse.com/.
=> Add exitFullscreen data

css/at-rules/media.json
This is implemented in Firefox 63. I am about to add the page that it links to.
=> Adding prefers-reduced-motion media feature

css/properties/word-break.json
Source: https://caniuse.com/#feat=word-break
=> Update word-break for Edge

api/Element.json
https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/10119510-element-closest
=> Add Edge support version for Element.closest

javascript/builtins/Symbol.json
See https://bugzilla.mozilla.org/show_bug.cgi?id=1472170 and https://www.chromestatus.com/feature/5340787290144768
=> Add Symbol.description

javascript/builtins/Object.json
See https://bugzilla.mozilla.org/show_bug.cgi?id=1469019
=> Add Object.fromEntries

http/status.json
See https://bugzilla.mozilla.org/show_bug.cgi?id=1406908
=> Add HTTP 425 (Too Early)

javascript/builtins/Float32Array.json, javascript/builtins/Float64Array.json, javascript/builtins/Generator.json, javascript/builtins/Int32Array.json, javascript/builtins/Number.json, javascript/builtins/Object.json, javascript/builtins/RegExp.json, javascript/builtins/String.json, javascript/builtins/TypedArray.json, javascript/builtins/Uint16Array.json, javascript/builtins/Uint32Array.json
This was generated automatically using @jcsahnwaldt's tool and the corresponding PR where I updated some mappings: https://github.com/jcsahnwaldt/nct2bcd/pull/1
Could you review this PR maybe, too, @jcsahnwaldt ?
=> Update nodejs versions for some builtins

api/Worker.json
https://bugs.webkit.org/show_bug.cgi?id=188779
https://bugs.chromium.org/p/chromium/issues/detail?id=721219
https://www.chromestatus.com/features/4594144336936960
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/11993715/
=> Update compat data for Worker name option

css/properties/scrollbar-width.json
for https://bugzilla.mozilla.org/show_bug.cgi?id=1475033
=> Adding initial compat data for scrollbar-width

browsers/firefox.json, browsers/firefox_android.json
[https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/62](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/62)
Can someone confirm what "ESR" means? and whether I made good use of the value in here?
=> update firefox browser data for Firefox 62 release

api/Node.json
=> Edge supports innerText, obviously

api/HTMLImageElement.json, html/elements/img.json
As per https://bugzilla.mozilla.org/show_bug.cgi?id=1416328.
=> adding data for HTML img decoding attribute

css/properties/box-ordinal-group.json
Source: https://developer.mozilla.org/en-US/docs/Web/CSS/box-ordinal-group#Browser_compatibility
=> CSS/properties: add box-ordinal-group

css/properties/box-align.json
Source: https://developer.mozilla.org/en-US/docs/Web/CSS/box-align#Browser_compatibility
=> CSS/properties: add box-align

api/Worklet.json
To support docs work being done on https://bugzilla.mozilla.org/show_bug.cgi?id=1472324
=> adding data for the Worklet interface

api/VisualViewport.json, api/Window.json
As per https://bugzilla.mozilla.org/show_bug.cgi?id=1357785
=> Updating Firefox support data for the VisualViewport API

css/properties/align-content.json
Fixes https://github.com/mdn/browser-compat-data/issues/845
=> CSS properties: add partial-implementation to align-content

css/properties/font-smooth.json
Source: https://developer.mozilla.org/en-US/docs/Web/CSS/font-smooth#Browser_compatibility
=> CSS/properties: add font-smooth

css/selectors/-ms-reveal.json
https://developer.mozilla.org/en-US/docs/Web/CSS/::-ms-reveal
=> Add compat data for ::-ms-reveal pseudo-element.

css/selectors/-ms-browse.json
https://developer.mozilla.org/en-US/docs/Web/CSS/::-ms-browse
=> Add compat data for ::-ms-browse pseudo-element.

css/selectors/-moz-focusring.json
https://developer.mozilla.org/en-US/docs/Web/CSS/:-moz-focusring
=> Add compat data for :-moz-focusring pseudo-class.

css/selectors/-ms-check.json
https://developer.mozilla.org/en-US/docs/Web/CSS/::-ms-check
=> Add ::-ms-check CSS pseudo-element.

css/selectors/-ms-fill-lower.json, css/selectors/-ms-fill-upper.json, css/selectors/-ms-fill.json
This adds compat data for:
- [`::-ms-fill`](https://developer.mozilla.org/en-US/docs/Web/CSS/::-ms-fill)
- [`::-ms-fill-upper`](https://developer.mozilla.org/en-US/docs/Web/CSS/::-ms-fill-upper)
- [`::-ms-fill-lower`](https://developer.mozilla.org/en-US/docs/Web/CSS/::-ms-fill-lower)
=> Add -ms-fill, -ms-fill-lower, and -ms-fill-upper CSS selectors

javascript/statements.json
https://bugs.webkit.org/show_bug.cgi?id=166926
https://trac.webkit.org/changeset/211280/webkit
=> Add JavaScript dynamic import support for Safari and IE

css/selectors/-ms-clear.json
https://developer.mozilla.org/en-US/docs/Web/CSS/::-ms-clear
=> Add compat data for ::-ms-clear pseudo-element.

api/AbsoluteOrientationSensor.json, api/Accelerometer.json, api/AmbientLightSensor.json, api/Gyroscope.json, api/LinearAccelerationSensor.json, api/Magnetometer.json, api/OrientationSensor.json, api/RelativeOrientationSensor.json, api/Sensor.json, api/SensorErrorEvent.json
There are all candidate recommendations. Don't know what I was thinking before.
=> Fix value of 'experimental' member.

api/Event.json
It was [getting ridiculous](https://developer.mozilla.org/en-US/docs/Web/API/Event#Browser_compatibility).
=> Alphabetize members.

api/PaymentMethodChangeEvent.json, api/PaymentRequest.json
Support of this event and related interfaces for Firefox
63.
=> Bug 1468356 - paymentmethodchange event

css/properties/scrollbar-face-color.json, css/properties/scrollbar-track-color.json
Updating scrollbar-width to indicate it is behind a flag, adding data for scrollbar color properties.
=> Adding properties from CSS Scrollbars spec

webextensions/api/tabs.json
https://bugzilla.mozilla.org/show_bug.cgi?id=1378647
https://hg.mozilla.org/mozilla-central/diff/fb52c3f74edc/browser/components/extensions/schemas/tabs.json
=> Add compat data for "discarded" inside browser.tabs.create()

css/types/image.json
Opening on behalf of @teoli2003
=> Add browser compat data for linear-gradient()

api/RTCAnswerOptions.json, api/RTCOfferAnswerOptions.json, api/RTCOfferOptions.json
This actually covers RTCOfferAnswerOptions,
RTCOfferOptions, and RTCAnswerOptions. Adds all three
including data for Chrome and Firefox.
=> Bug 1399757  Document RTCAnswerOptions

css/properties/-moz-outline-radius.json
https://developer.mozilla.org/en-US/docs/Web/CSS/-moz-outline-radius
=> Add compat data for -moz-outline-radius property

api/Bluetooth.json, api/BluetoothCharacteristicProperties.json, api/BluetoothRemoteGATTCharacteristic.json, api/BluetoothRemoteGATTDescriptor.json, api/BluetoothRemoteGATTServer.json, api/BluetoothRemoteGATTService.json
https://www.chromestatus.com/features/5264933985976320
=> Update Bluetooth API support.

css/selectors/-moz-page-sequence.json, css/selectors/-moz-page.json, css/selectors/-moz-scrolled-page-sequence.json
- [`::-moz-page`](https://developer.mozilla.org/en-US/docs/Web/CSS/::-moz-page)
- [`::-moz-page-sequence`](https://developer.mozilla.org/en-US/docs/Web/CSS/::-moz-page-sequence)
- [`::-moz-scrolled-page-sequence`](https://developer.mozilla.org/en-US/docs/Web/CSS/::-moz-scrolled-page-sequence)
=> Add compat data for ::-moz-page and related psuedo-elements

css/properties/-moz-binding.json
https://developer.mozilla.org/en-US/docs/Web/CSS/-moz-binding
=> Add compat data for -moz-binding property.

css/selectors/-moz-range-progress.json, css/selectors/-moz-range-thumb.json, css/selectors/-moz-range-track.json
- [`::-moz-range-progress`](https://developer.mozilla.org/en-US/docs/Web/CSS/::-moz-range-progress)
- [`::-moz-range-track`](https://developer.mozilla.org/en-US/docs/Web/CSS/::-moz-range-track)
- [`::-moz-range-thumb`](https://developer.mozilla.org/en-US/docs/Web/CSS/::-moz-range-thumb)
=> Add compat data for ::-moz-range-* pseudo-elements

css/selectors/-moz-window-inactive.json
https://developer.mozilla.org/en-US/docs/Web/CSS/:-moz-window-inactive
=> Add compat data for :-moz-window-inactive pseudo-class.

css/selectors/-moz-full-screen-ancestor.json
https://developer.mozilla.org/en-US/docs/Web/CSS/:-moz-full-screen-ancestor
=> Add compat data for :-moz-full-screen-ancestor pseudo-class.

css/properties/-moz-orient.json
https://developer.mozilla.org/en-US/docs/Web/CSS/-moz-orient
=> Add compat data for -moz-orient property

css/properties/-moz-text-blink.json
https://developer.mozilla.org/en-US/docs/Web/CSS/-moz-text-blink
=> Add compat data for -moz-text-blink property.

api/NavigatorOnLine.json
Tested in Safari iOs and is functional
=> Updating browsers compatibility of navigator.onLine

css/properties/custom-property.json
https://developers.google.com/web/updates/2018/09/nic69#notch
=> Chrome 69 added support for env()

api/Document.json, api/DocumentOrShadowRoot.json, api/Element.json
See [bug&nbsp;1269276](https://bugzil.la/1269276) for details.
=> Bug 1269276: Enable unprefixed Fullscreen API

css/selectors/fullscreen.json
I knew I forgot something in #2861/#2879.
=> Bug 1269276: Enable unprefixed :fullscreen selector

css/properties/-moz-user-input.json
=> feat(css): Add `‑moz‑user‑input`

javascript/statements.json
https://www.chromestatus.com/features/5727385018171392
=> Add async iterators.

css/properties/azimuth.json
Source: https://developer.mozilla.org/en-US/docs/Web/CSS/azimuth#Browser_compatibility
=> CSS/properties: add azimuth

api/HTMLIFrameElement.json
Intended to check off the matching entry on the checklist on #2467.
=> Add HTMLIFrameElement.setNfcFocus();

api/AudioTrackList.json, api/VideoTrackList.json
Fixes https://github.com/mdn/browser-compat-data/issues/2855
=> Add AudioTrackList and VideoTrackList

css/properties/background-clip.json, css/properties/background-origin.json, css/properties/background-size.json
=> fix(css): Fix `background‑*` properties

api/HTMLMediaElement.json
Adds compatibility information for the load() method
on HTMLMediaElement.
=> Add load() data to HTMLMediaElement

javascript/builtins/Intl.json
Some features are still listed as unknown even though we currently have them because I am not sure which version introduced them :)
=> Update Intl compat table for Edge 18

css/properties/hyphens.json
=> Update CSS hyphens property

package-lock.json, package.json
=> Updating extend version pin to fix prototype injection vulnerability

api/Request.json
https://www.chromestatus.com/feature/4753419730419712
=> Request API: Add fragment support to url and sort file

webextensions/manifest/theme.json
Updated compatibility for new tab text and background colors in the theme manifest.
=> Added support for ntp_text and ntp_background for Firefox 63.

webextensions/manifest/page_action.json
See [bug&nbsp;1494135](https://bugzil.la/1494135) for details.
=> Bug 1494135: Add the `page_action.pinned` property

css/properties/overflow-anchor.json
It's in CSSWG: https://drafts.csswg.org/css-scroll-anchoring/
Chrome implementation: https://blog.chromium.org/2017/04/scroll-anchoring-for-web-developers.html
=> Add CSS overflow-anchor

webextensions/api/tabs.json
Modified support for the update values highlighted as of Firefox 63.
=> added information for update properties highlighted.

html/elements/a.json
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/7260192/
=> Edge 17 or older doesn't support custom filename for a[download]

css/properties/height.json, css/properties/max-height.json, css/properties/max-width.json, css/properties/min-height.json, css/properties/min-width.json, css/properties/width.json
=> Update Chrome versions for stretch value

css/properties/max-block-size.json
Crosses this property off of the list on #2684.
=> Add compat data for CSS property max-block-size

css/properties/all.json
I used the info on Can I Use: https://caniuse.com/#feat=css-all
=> Updated support of CSS 'all'

css/properties/display.json
See [bug&nbsp;1496961](https://bugzil.la/1496961) for details.
=> Bug 1496961: Unship `‑moz‑box` display values on release channels

webextensions/manifest/commands.json
https://bugzilla.mozilla.org/show_bug.cgi?id=1251795#c10
=> v57 provided MediaPlayPause support

css/selectors/cue.json
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/17128999/
=> Edge does not support the ::cue selector

css/at-rules/supports.json
See [bug&nbsp;1499386](https://bugzilla.mozilla.org/show_bug.cgi?id=1499386) and https://github.com/w3c/csswg-drafts/issues/3207 for details.
=> feat(css.at-rules): Add `@supports selector(…)`

css/at-rules/document.json
=> fix(css): The `@-moz-document regexp(…)` function isn’t prefixed

http/headers/content-encoding.json
https://caniuse.com/#feat=brotli
https://developer.microsoft.com/en-us/microsoft-edge/platform/status/brotlicompresseddataformat/
=> Add Edge version for Brotli compression

api/Element.json
Added scrollIntoView support by Edge
=> Update Edge support for Element.scrollIntoView

api/CSS.json
https://bugzilla.mozilla.org/show_bug.cgi?id=1338486
https://bugs.chromium.org/p/chromium/issues/detail?id=729403
=> Add info about CSS.supports() paren-less version

css/properties/block-size.json, css/properties/inline-size.json, css/properties/max-block-size.json, css/properties/max-inline-size.json, css/properties/min-block-size.json, css/properties/min-inline-size.json
This is a new PR for the logical properties sizing data which got into a mess here https://github.com/mdn/browser-compat-data/pull/2955#issuecomment-433038546
=> Logical Properties data for block and inline sizing

api/DOMTokenList.json, api/HTMLIFrameElement.json, api/HTMLLinkElement.json, api/HTMLOutputElement.json
https://www.chromestatus.com/feature/5720372066385920
=> Merge DOMSettableTokenList with DOMTokenList.

css/properties/scroll-margin-block-end.json, css/properties/scroll-margin-block-start.json, css/properties/scroll-margin-block.json, css/properties/scroll-margin-bottom.json, css/properties/scroll-margin-inline-end.json, css/properties/scroll-margin-inline-start.json, css/properties/scroll-margin-inline.json, css/properties/scroll-margin-left.json, css/properties/scroll-margin-right.json, css/properties/scroll-margin-top.json, css/properties/scroll-margin.json, css/properties/scroll-padding-block-end.json, css/properties/scroll-padding-block-start.json, css/properties/scroll-padding-block.json, css/properties/scroll-padding-bottom.json, css/properties/scroll-padding-inline-end.json, css/properties/scroll-padding-inline-start.json, css/properties/scroll-padding-inline.json, css/properties/scroll-padding-left.json, css/properties/scroll-padding-right.json, css/properties/scroll-padding-top.json, css/properties/scroll-padding.json, css/properties/scroll-snap-align.json, css/properties/scroll-snap-stop.json, css/properties/scroll-snap-type.json
I'm working on adding pages for the updated scroll snap spec, we don't have data for the properties so here it is.
=> Adding all the missing scroll-snap properties

css/properties/display.json
This is for the things discussed in https://github.com/mdn/sprints/issues/523
I'm not sure if the data for run-in makes sense. Let me know!
=> data for list-item and display: run-in

css/properties/align-content.json, css/properties/justify-content.json
Added up to date data for `space-evenly`, and a couple of missing IEs.
=> some missing or wrong values for the -content properties

api/WindowOrWorkerGlobalScope.json
Support data for the signal feature in browsers has been added.
=> Support data for the signal feature (from AbortController API).

css/properties/column-span.json
added with details of the preference.
=> column-span is in Nightly

css/properties/custom-property.json
See [bug&nbsp;1462233](https://bugzilla.mozilla.org/show_bug.cgi?id=1462233) and&nbsp;https://github.com/mdn/browser-compat-data/issues/3052 for details.
=> Bug 1462233: Implement CSS Environment Variables

api/Window.json
As per https://bugzilla.mozilla.org/show_bug.cgi?id=1493869
=> updating Firefox compat data for Window.event

javascript/builtins/JSON.json
Firefox 64: https://bugzilla.mozilla.org/show_bug.cgi?id=1469021
Chrome 72/Opera 59: https://www.chromestatus.com/features/5752304045129728
=> Add data for well-formed JSON.stringify

css/properties/border-end-end-radius.json, css/properties/border-end-start-radius.json, css/properties/border-start-end-radius.json, css/properties/border-start-start-radius.json
No browser support for these as yet, adding for the sake of completion as I work on the rest of the pages.
https://drafts.csswg.org/css-logical/#border-radius-properties
=> Adding data for missing border-radius logical mappings.

api/ServiceWorkerContainer.json
As per https://bugzilla.mozilla.org/show_bug.cgi?id=1263734
=> updating Fx support data for ServiceWorkerContainer.startMessages

api/HTMLMediaElement.json
As per https://bugzilla.mozilla.org/show_bug.cgi?id=934425
=> updating setSinkId compat data

css/properties/custom-property.json
=> fix(css): Correct Firefox custom properties compatibility data

api/Window.json
As per https://bugzilla.mozilla.org/show_bug.cgi?id=675574
=> adding data point about only allowing one window.open() call per event

html/elements/meter.json
https://bugs.webkit.org/show_bug.cgi?id=161714
=> Update meter information for iOS Safari

api/HTMLElement.json, api/Node.json
As per https://bugzilla.mozilla.org/show_bug.cgi?id=1505763
=> moving data for innerText from Node to HTMLElement

api/CustomElementRegistry.json, api/Element.json, api/HTMLSlotElement.json, api/ShadowRoot.json, api/Slotable.json, api/Window.json, css/selectors/host-context.json, css/selectors/host.json, css/selectors/hostfunction.json, html/elements/slot.json, html/global_attributes.json
See [bug&nbsp;1503019](https://bugzilla.mozilla.org/show_bug.cgi?id=1503019) for details.
=> Bug 1503019: Remove Shadow DOM and Custom Elements prefs

api/ServiceWorkerRegistration.json
https://www.chromestatus.com/feature/6059838387781632
=> [Chrome] Correct updateViaCache.

javascript/builtins/RegExp.json
=> Add "Experimental JavaScript Features" note for `RegExp.flags`

css/selectors/attribute.json
See [bug&nbsp;1512386](https://bugzilla.mozilla.org/show_bug.cgi?id=1512386) for details.
review?(@chrisdavidmills, @ddbeck, @Elchi3, @teoli2003)
=> feat(css): Add the attribute selector case‑sensitive modifier (`s`)

css/properties/display.json
The display property had some missing data, showing up as ? I have fixed the majority of that. Unusual display: contents elements needs some more research.
=> Fixing some missing compat data for display

css/properties/offset-path.json
https://www.chromestatus.com/features/5198375053950976
=> Add path() support to offset-path.

javascript/statements.json
- https://github.com/tc39/proposal-async-iteration
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for-await...of
=> support for await...of

css/properties/scrollbar-color.json
As per https://bugzilla.mozilla.org/show_bug.cgi?id=1513602
=> adding note about macOS scrollbar-color

api/AuthenticatorAssertionResponse.json, api/AuthenticatorAttestationResponse.json, api/HTMLInputElement.json, api/Navigator.json, api/PaymentRequest.json, api/PaymentResponse.json, api/PermissionStatus.json, api/Permissions.json, api/PresentationConnection.json, api/PresentationReceiver.json, api/PresentationRequest.json, api/PublicKeyCredential.json, api/PushSubscriptionOptions.json, api/ServiceWorkerRegistration.json, api/SharedWorker.json, api/SpeechSynthesisErrorEvent.json, api/SpeechSynthesisEvent.json, api/SpeechSynthesisUtterance.json
This is based on [this file from chromium](https://cs.chromium.org/chromium/src/android_webview/tools/system_webview_shell/test/data/webexposed/not-webview-exposed.txt). This PR merely updates existing data. Missing data will be handled in a separate entry.
=> Update items that are not in Android Webview

javascript/builtins/PluralRules.json
Related to this: https://www.chromestatus.com/features/5653874773852160
javascript/builtins/Intl.json is already up to date.
=> Add PluralRules interface.

api/HTMLMediaElement.json, api/WebGL2ComputeRenderingContext.json
https://cs.chromium.org/chromium/src/android_webview/tools/system_webview_shell/test/data/webexposed/not-webview-exposed.txt
=> More webview-related updates

api/FileReader.json
=> Mark FileReader.readAsBinaryString as removed in IE 11

api/ResizeObserver.json, api/ResizeObserverEntry.json
https://www.chromestatus.com/features/5705346022637568
=> [Chrome] Add data for ResizeObserver.

api/FetchEvent.json
As per https://bugzilla.mozilla.org/show_bug.cgi?id=1264177
The only other support info I could find about any of this was https://www.chromestatus.com/features/4846038800138240
=> updating FetchEvent data

html/elements/audio.json, html/elements/video.json
https://www.chromestatus.com/features/5682169347309568
=> [Chrome] Media preload attrib now defaults to metadata.

api/HTMLImageElement.json
https://cs.chromium.org/chromium/src/third_party/blink/renderer/core/html/html_image_element.idl
=> [Chrome] Improve HTMLImageElement data.

api/ParentNode.json
Verified on Windows 10 Edge 17.17134
=> Update ParentNode.json - lastElementChild attribute

api/Request.json
https://www.chromestatus.com/features/5166560033374208
=> [Chrome] Add data for Request.cache.

svg/elements/animateMotion.json
=> Update animateMotion.json for basic iOS compatibility

css/selectors/-webkit-resizer.json, css/selectors/-webkit-scrollbar-button.json, css/selectors/-webkit-scrollbar-corner.json, css/selectors/-webkit-scrollbar-thumb.json, css/selectors/-webkit-scrollbar-track-piece.json, css/selectors/-webkit-scrollbar-track.json, css/selectors/-webkit-scrollbar.json
I have confirmed that this works on iOS.
review?(@ddbeck, @Elchi3)
=> feat(css): Add the `::‑webkit‑scrollbar` selectors

api/Window.json
https://www.chromestatus.com/feature/5674968658477056
=> [Chrome] Add window.oninstall.

javascript/statements.json
See [bug&nbsp;1342012](https://bugzilla.mozilla.org/show_bug.cgi?id=1342012) for details.
---
review?(@chrisdavidmills, @ddbeck, @Elchi3, @wbamberg)
Closes #3246
=> Bug 1342012: Implement dynamic import behind pref

api/CredentialUserData.json
Add CredentialUserData interface.
=> Add CredentialUserData interface.

http/headers/cache-control.json
=> Add note for Cache-Control header

api/Navigator.json
Battery information comes from the history of this: https://cs.chromium.org/chromium/src/third_party/blink/renderer/modules/battery/navigator_battery.idl
=> [Chrome] Fix a few items in Navigator.

api/CSS.json
Updates the values of the CSS.supports API to the latest data.
Updated to the data available at:
https://caniuse.com/#search=css.supports
=> Updated CSS.supports value

api/Element.json
Specifically:
[innerHTML, outerHTML](https://chromium.googlesource.com/chromium/src/+/cec9407a060fee19422f54263b63505dc78c703f%5E%21/#F12)
[localName, namespaceURI, and prefix](https://chromium.googlesource.com/chromium/src/+/e25d2d37c63dd57f4b35ef11bd7096a95c31f6ae%5E%21/#F3)
=> [Chrome] Fix errors introduced by Confluence.

api/RTCPeerConnection.json
The non-Chrome changes came from Confluence. The Confluence data on this interface turned out to be really bad. You will wonder if some of these changes are correct. Here's the proof.
The webkit prefix was removed in Chrome 56. It appears that the prefix was only ever on the interface and not it’s individual members. I might have found this odd, but I’ve seen it before.
[constructor](https://chromium.googlesource.com/chromium/src/+/4426ed8c87c03f2c5d38aa75648154fc22cc564f)
Missing from IDL, not supported: [defaultIceServers, peerIdentity, sctp,onidentityresult, onidpassertionerror, onidpvalidationerror, onpeeridentity, getIdentityAssertion, setIdentityProvider, onicecandidateerror, getDefaultIceServers](https://cs.chromium.org/chromium/src/third_party/blink/renderer/modules/peerconnection/ …
=> [All] Improvements to RTCPeerConnection.json

api/Document.json, api/HTMLIFrameElement.json, http/headers/feature-policy.json
See https://bugzilla.mozilla.org/show_bug.cgi?id=1507230#c9 ff. and in particular https://searchfox.org/mozilla-central/rev/b29663c6c9c61b0bf29e8add490cbd6bad293a67/dom/security/featurepolicy/FeaturePolicyUtils.cpp#28-39
=> Feature-Policy support behind a pref in Firefox 65

http/methods.json
See https://github.com/mdn/browser-compat-data/issues/1702 and https://github.com/mdn/browser-compat-data/pull/1700#issuecomment-377171552
=> Fix issue 1702: Mark TRACE support as null

api/HTMLScriptElement.json, html/elements/script.json
As per https://bugzilla.mozilla.org/show_bug.cgi?id=1460920
=> adding referrerPolicy for script elements compat data

api/Body.json, api/ReadableStream.json, api/ReadableStreamDefaultController.json, api/ReadableStreamDefaultReader.json, api/Request.json
As per https://bugzilla.mozilla.org/show_bug.cgi?id=1505122
=> Updating Fx support data for readable streams

javascript/builtins/globals.json
Firefox 65: https://bugzilla.mozilla.org/show_bug.cgi?id=1317422
Chromiums 71: https://www.chromestatus.com/feature/6571514765770752
=> Add globalThis compat data

browsers/firefox.json, browsers/firefox_android.json
https://www.mozilla.org/en-US/firefox/65.0/releasenotes/
=> Update Firefox data as version 65.0 released

api/InputEvent.json
As per https://bugzilla.mozilla.org/show_bug.cgi?id=1447239.
=> adding Fx support data for InputEvent.inputType

api/Element.json
=> Fix typo in fullscreen API (Really!)

api/Element.json, css/properties/justify-content.json
These weren't sorted alphabetically. We will enforce this with a test going forward.
=> Sort browsers alphabetically

api/AbortController.json, api/CanvasRenderingContext2D.json, api/Console.json, api/HTMLCanvasElement.json, api/Range.json, api/URL.json, api/URLSearchParams.json, api/Window.json, api/WindowEventHandlers.json, css/at-rules/viewport.json, css/properties/background-image.json, css/properties/text-align-last.json, css/properties/text-rendering.json, css/properties/text-transform.json, css/properties/touch-action.json, css/selectors/first-line.json, css/selectors/in-range.json, css/selectors/indeterminate.json, css/types/-moz-image-rect.json, css/types/image.json, css/types/resolution.json, html/elements/applet.json, html/elements/script.json, html/elements/textarea.json, mathml/elements/maction.json, mathml/elements/math.json, mathml/elements/menclose.json, svg/elements/textpath.json, test/test-style.js
=> Enforce shorter URLs for Webkit bugs

javascript/builtins/Array.json
see https://github.com/tc39/proposal-flatMap and https://github.com/tc39/proposals/blob/master/finished-proposals.md as confirmation.
=> Update flat and flatMap to non-experimental

webextensions/api/menus.json, webextensions/manifest/incognito.json, webextensions/manifest/permissions.json
=> Fix version inconsistencies in webextensions/*

css/properties/overflow-wrap.json
Support tracked in https://bugs.chromium.org/p/chromium/issues/detail?id=905315
=>  Flag anywhere as unsupported on Google Chrome

mathml/elements/mo.json, mathml/elements/mphantom.json, mathml/elements/mroot.json, mathml/elements/mrow.json
=> Fix version inconsistencies in mathml/*

html/elements/menu.json, html/elements/menuitem.json
=> Fix version inconsistencies in html/*

svg/elements/altGlyph.json, svg/elements/animate.json, svg/elements/animateColor.json, svg/elements/animateMotion.json, svg/elements/animateTransform.json, svg/elements/color-profile.json, svg/elements/cursor.json, svg/elements/discard.json, svg/elements/feComposite.json, svg/elements/font.json, svg/elements/hatch.json, svg/elements/hatchpath.json, svg/elements/hkern.json, svg/elements/mpath.json, svg/elements/tref.json, svg/elements/view.json
=> Fix version inconsistencies in svg/*

javascript/builtins/RegExp.json
https://chromiumdash.appspot.com/commits?commit=6f890fd5b212eb441a4b87364922d5286fdc505e
=> Add unicode property escapes to regular expressions.

http/headers/x-content-type-options.json
https://storage.googleapis.com/chromium-find-releases-static/722.html#722937f7116a2c448d0700b6d90318852369c785
=> Add Chrome support for 'nosniff' directive.

schemas/compat-data-schema.md
Fixes https://github.com/mdn/browser-compat-data/issues/3410.
=> Update the documentation on required browsers

html/elements/link.json
https://storage.googleapis.com/chromium-find-releases-static/f51.html#f51545f74eba6bc1cc11a0a87453513c19b2c4a4
=> prefetch attribute is only supported on secure contexts.

api/PointerEvent.json
https://storage.googleapis.com/chromium-find-releases-static/9d5.html#9d5de00296c359ea4b91c71fffd41cc2ad28dd41
A little background: https://www.chromestatus.com/features/5117956774166528
=> Add fractional coord support for PointerEvents.

api/HTMLSlotElement.json
https://storage.googleapis.com/chromium-find-releases-static/167.html#1673861ecc8c136aad3448a0d91362f7dfc58963
=> Add assignedElement to HTMLSlotElement.

api/MediaQueryList.json
- Update Safari Desktop support for MediaQueryList
- Add Safari Mobile support for MediaQueryList
- https://developer.apple.com/documentation/webkitjs/mediaquerylist
=> Add Safari support for MediaQueryList

svg/elements/feComposite.json
The commit date for this predates Chrome 1. https://chromium.googlesource.com/chromium/src/+/e05eff9340f3b0fbe454210ce9513057f851e8ec
=> Corrections to feComposite element.

package.json
=> Add minimum required Node version

api/WindowOrWorkerGlobalScope.json
As per https://bugzilla.mozilla.org/show_bug.cgi?id=1484833
=> Firefox does not support the options parameter of createImageBitmap

api/HTMLButtonElement.json, api/HTMLFieldSetElement.json, api/HTMLInputElement.json, api/HTMLOutputElement.json, api/HTMLSelectElement.json, api/HTMLTextAreaElement.json
Updated using info from [Caniuse](https://caniuse.com/#feat=constraint-validation).
=> Add/update info for reportValidity() method

api/HTMLFormElement.json
Tested reset() in IE and Edge with input, radio, selects, and checkboxes.
=> Tested reset() in IE and Edge

webextensions/api/tabs.json
=> Mark webextensions.api.tabs.hide as non-experimental

package-lock.json, package.json
This brings in https://github.com/mdittmer/mdn-confluence/pull/31.
=> Upgrade the mdn-confluence dependency for new/better defaults

webextensions/api/tabs.json
=> Add support in Firefox for webextensions.api.tabs.sessionId

api/PerformanceObserver.json
https://storage.googleapis.com/chromium-find-releases-static/226.html#226d6541a89503346b0ba6a56b523408080c978e
=> [Chrome] Add takeRecords to PerformanceObserver.

html/elements/input/input.json, html/elements/input/input_attributes.json
As per https://bugzilla.mozilla.org/show_bug.cgi?id=1513890
I added an extra file to contain compat data for global input element attributes, as we didn't have a specific file just for general input element attributes. Let me know what you think ;-)
=> Remove x moz errormessage

api/Console.json
This adds the `debug()` method to the console interface.
=> Add debug() method to console interface

javascript/builtins/Symbol.json
This PR aims to update the compat data for `Symbol.asyncIterator`, as part of a documentation effort for async iteration by Daniel Ehrenburg, Willian Martins, and myself, based on notes by @Elchi3. We're tracking our work [here](https://github.com/tc39/proposal-async-iteration/issues/132). 
I've added versions for Node ([changelog](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V10.md)), Opera ([Chrome Platform Status](https://www.chromestatus.com/feature/5727385018171392)), Safari ([Safari 11.1 blog post](https://webkit.org/blog/8216/new-webkit-features-in-safari-11-1/), [Safari Tech Preview 40 blog post](https://webkit.org/blog/7922/release-notes-for-safari-technology-preview-40/)), and Firefox …
=> Async iterator updates

css/properties/display.json
https://storage.googleapis.com/chromium-find-releases-static/150.html#1508f4a32a3fb19d6e3599acc0bcc817ebe6c5be
=> [Chrome] Add information on display:none.

api/DocumentOrShadowRoot.json
`adoptedStyleSheets()` is a shiny new feature that no stable browser supports yet. Someone just copy-pasted everything inside DocumentOrShadowRoot...
Chrome: https://www.chromestatus.com/feature/5394843094220800
Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1520690
=> Update DocumentOrShadowRoot.adoptedStyleSheets data

html/elements/meta.json
https://storage.googleapis.com/chromium-find-releases-static/e71.html#e71f2e951038b1b204d0f35cdfee0463a63bffa1
=> [Chrome] Add removal version for set-cookie.

api/MediaRecorder.json
The change [was made here](https://storage.googleapis.com/chromium-find-releases-static/ab5.html#ab5ae32c6233fe7938b9a0b53cf1c74918310d7a).
=> [Chrome] Mark ignoreMutedMedia as removed.

api/CSSUnparsedValue.json
The [getter landed here](https://storage.googleapis.com/chromium-find-releases-static/344.html#344d72388afbace9b3ffd0f7aa4279361d7a57b4) and the [setter landed here](https://storage.googleapis.com/chromium-find-releases-static/138.html#138fde45864d92ce1315f7e0d8c907230c2ffa68). Both landed in 66.
=> Add CSSUnparsedSegment getter/setter.

api/HTMLCanvasElement.json
See https://github.com/mdn/sprints/issues/953
First commit sorts features alphabetically
Second commit migrates compat data from old legacy MDN compat tables.
=> Add WebGL events

webextensions/manifest/manifest_version.json
This adds all known `manifest_version` values.
=> feat(webext/manifest): Add `manifest_version` values

webextensions/manifest/incognito.json
See [bug&nbsp;1345474](https://bugzilla.mozilla.org/show_bug.cgi?id=1345474) for details.
=> Bug 1345474: Add support for `incognito: "not_allowed"`

webextensions/manifest/background.json, webextensions/manifest/browser_action.json, webextensions/manifest/content_scripts.json, webextensions/manifest/omnibox.json, webextensions/manifest/options_ui.json, webextensions/manifest/page_action.json, webextensions/manifest/sidebar_action.json
See&nbsp;also https://github.com/mdn/browser-compat-data/issues/3529#issuecomment-467504522
=> fix(webextensions/manifest): Un‑squash manifest.json data

html/elements/link.json
Super simple fix that adds to the efforts of #3368.
=> Fix consistency of html.elements.link for IE

api/DocumentOrShadowRoot.json
https://storage.googleapis.com/chromium-find-releases-static/bb3.html#bb3517a95aa758711ac11927e8f8ebf44f6a272b
=> Add note about bug fix to select methods.

http/headers/snapshot-content-location.json
https://storage.googleapis.com/chromium-find-releases-static/1de.html#1de0fc2dd4e605249221cc8cd11350711a71c1c4
=> [Chrome] Add Snapshot-Content-Location header.

http/headers/content-security-policy.json
Summary:
Add mdn_url for content security policy strict-dynamic
=> add mdn_url for strict-dynamic

css/at-rules/media.json, css/types/calc.json
https://storage.googleapis.com/chromium-find-releases-static/5e7.html#5e7c6952c431e507a56c7fbd9484571ff81ea4e3
=> Add calc() to @media.

http/headers/accept.json
As per https://bugzilla.mozilla.org/show_bug.cgi?id=1417463
=> Add a note to Firefox about default Accept value change

api/FetchEvent.json, api/FileSystemDirectoryReader.json, api/FileSystemEntry.json, api/Gamepad.json, api/GamepadButton.json, api/GamepadHapticActuator.json, api/GamepadPose.json, api/HTMLCanvasElement.json, api/HTMLHyperlinkElementUtils.json, api/HTMLMediaElement.json, api/HTMLOutputElement.json, api/HTMLSelectElement.json, api/HTMLSlotElement.json, api/Headers.json, api/IDBVersionChangeEvent.json, api/ImageBitmap.json, api/KeyboardEvent.json, api/KeyboardLayoutMap.json, api/KeyframeEffect.json, api/MediaDeviceInfo.json, api/MediaDevices.json, api/MediaElementAudioSourceNode.json, api/MediaSource.json, api/MediaStream.json, api/MediaStreamAudioSourceNode.json, api/MediaStreamAudioSourceOptions.json, api/MediaStreamTrack.json, api/MediaStreamTrackEvent.json, api/MerchantValidationEvent.json
=> Fix version inconsistencies in api/* (G through M)

api/Navigator.json
- https://caniuse.com/#feat=beacon
=> Update sendBeacon compatibility for iOS >11.1

css/types/image.json
updated matching https://caniuse.com/#feat=css-element-function
=> Add missing data for the element function

browsers/chrome.json, browsers/chrome_android.json, browsers/webview_android.json
Chrome 73 was released yesterday, [https://www.chromestatus.com/features/schedule](https://www.chromestatus.com/features/schedule)
Just updated the browsers data 👍
=> Update Chrome 73 release date

api/DocumentOrShadowRoot.json
Source caniuse but also prototypes I made (not public)
=> Fullscreen API only works on iOS on iPad

api/HTMLIFrameElement.json
[Microsoft does seem to have internally implemented it](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/12375527/) but it has never landed in any public versions.
=> Edge doesn't support srcdoc

css/properties/counter-increment.json, css/properties/counter-reset.json
=> Update CSS Counters data

api/SVGPathElement.json
=> Fix compat data for Safari for api.SVGPathElement

javascript/builtins/ArrayBuffer.json, javascript/builtins/AsyncFunction.json, javascript/builtins/Boolean.json, javascript/builtins/DataView.json, javascript/builtins/Date.json, javascript/builtins/Error.json, javascript/builtins/EvalError.json, javascript/builtins/Float32Array.json, javascript/builtins/Float64Array.json, javascript/builtins/Function.json
I've improved some Edge data to get more _real values_.
This PR has updates to the first 10 files in javascript/builtins and I'm curious to see how easy it is to review. Please let me know much time you spend with reviewing.
I took me about half an hour to write this PR and my sources for this were confluence and manual testing in Saucelabs.
One thing that stands out: I've folded "ordinary_object" into a note for Firefox, as I think that's what it should be. No need for collecting browser support as I think this is really a minor aspect.
=> Improve Edge JS builtins data part 1

javascript/builtins/Boolean.json
This change demonstrates the contributor workflow using the GitHub UI.
=> Demo change to show contributor workflow

api/ResizeObserver.json
=> Fix Opera data for api.ResizeObserver

README.md
Wohooo :tada: 
https://www.jetbrains.com/webstorm/whatsnew/#v2019-1-html-and-css
=> Add WebStorm as a project using the data

css/properties/list-style-type.json
=> Add additional support for css.list-style-type

api/Animation.json, api/BlobBuilder.json, api/Element.json, api/FileError.json, api/HMDVRDevice.json, api/PositionSensorVRDevice.json
Sub-PR of #3603 for the fix of the data itself.
=> Fix all relative URLs in notes

api/Event.json, api/HTMLInputElement.json
The supported browsers aren't verified
=> Added the Search event

api/HTMLSelectElement.json, api/HTMLTextAreaElement.json
This shows [where the commit landed](https://chromiumdash.appspot.com/commits?commit=e1c977ab2790547a3bab3aca362e137ab976e885).
Autocomplete and alphabetization are in separate commits to make reviewing easier.
=> Add autocomplete to HTMLSelectElement and HTMLTextAreaElement; alphabetize features

api/HTMLMediaElement.json, api/MediaSource.json, api/Navigator.json, api/Notification.json, api/SourceBuffer.json, api/SourceBufferList.json
=> Correct prefixes from -webkit- to webkit in api/ files.

api/MIDIConnectionEvent.json, api/MIDIInput.json, api/MIDIMessage.json, api/MIDIMessageEvent.json, api/MIDIOutput.json, api/MIDIPort.json
The spec author tells me [Chrome Status is correct](https://www.chromestatus.com/features/4923613069180928).
=> [Chrome] Add missing members for MIDI Interfaces.

api/Screen.json
=> [Chrome][Safari] Updates to Screen.

css/types/global_keywords.json
See [bug 1215878](https://bugzilla.mozilla.org/show_bug.cgi?id=1215878)
review?(@ddbeck, @Elchi3)
=> Bug 1215878: Implement the `revert` keyword`

api/Element.json, api/HTMLDialogElement.json
Data for another legacy table: https://developer.mozilla.org/en-US/docs/Web/API/Element/cancel_event
c.f. https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/oncancel
=> Add Element: cancel event

api/SVGAnimationElement.json
As per https://github.com/mdn/sprints/issues/954 (the first three events thereof)
=> adding SVG animation events

governance.md
Joe (@jpmedley) agrees and abides by the Mozilla Commit Access Requirements per https://github.com/mdn/mdn/issues/63
Information on the repo governance and what exactly it means to be a Peer can be found here: https://github.com/mdn/browser-compat-data/blob/master/governance.md
Requesting approval from other BCD Owners and I will give Joe write access to the repo after this PR has been merged.
=> Add Joe Medley as a BCD Peer

browsers/opera_android.json
Fixes https://github.com/mdn/browser-compat-data/issues/3783
=> Correct opera_android release_dates and release_notes

api/Navigator.json
Gang,
I apologize for this one. I clicked publish on [the MDN page](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/canShare) before I remembered I hadn't submitted any BCD for it. Not only that, it hasn't shipped in Chrome yet. (I'm having a bad day.)
Joe
=> Add Navigator.canShare().

api/GlobalEventHandlers.json
added more trues to reset - tested the code example in a bunch of bro…wsers and it worked everywhere
no ticket. just saw https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onreset looked outdated. Tested, and saw the example worked everywhere i tried (did not try IE)
=> added more trues to reset 

api/Element.json
=> Add note about api.Element.removeAttribute regarding bug in Edge

api/Window.json
for
https://developer.mozilla.org/en-US/docs/Web/API/Window/deviceorientation_event
as per
mdn/sprints#1284
=> added deviceorientation event to window

api/SVGElement.json
See top of https://github.com/mdn/sprints/issues/954#issuecomment-483510922 for problem description.
=> fixing incorrect URLs in SVGElement event data, as per wbamberg comments

html/elements/fieldset.json
=> Mention Chromium and Edge issues with fieldset element

javascript/builtins/Proxy.json
Fixes #3321.  Information derived from @jpmedley.
=> Update Chrome values for javascript.Proxy.handlers.set/getPrototypeOf

api/WorkerGlobalScope.json
For https://github.com/mdn/sprints/issues/1125#issuecomment-479207654
Edit: Data copied from the onlanguagechange event handler.
=> Add languagechange event to WorkerGlobalScope

api/ServiceWorkerContainer.json, api/ServiceWorkerGlobalScope.json
For https://github.com/mdn/sprints/issues/1125
Data copied from the event handler properties.
=> Add ServiceWorker message events

api/HTMLMediaElement.json
Fixes #2649.  This adds all of the data presented within the linked issue.
=> Add api.HTMLMediaElement.play promise-returning compat data

html/elements/script.json
=> Update html.element.script.nomodule support

css/properties/will-change.json
Fixes #2854.  More information within said issue.
=> Fix css.properties.will-change for Firefox

api/MediaRecorder.json
This has no new information. It's just fixing what's already there.
=> Make Chrome values consistent.

webextensions/api/permissions.json
Fixes #2913 (more info in issue).
=> Add webextensions.permissions.tabhide

api/HTMLObjectElement.json
In this PR:
* `contentWindow` is [in Chrome 53](https://storage.googleapis.com/chromium-find-releases-static/cc5.html#cc526ef25f0b6d2a819700ccbeac2b3acf6fab80)
* [Chrome 1 IDL](https://chromium.googlesource.com/chromium/src/+/ae284c1d71111932d56f9330b6c03d22f315bcac/third_party/WebKit/WebCore/html/HTMLObjectElement.idl)
* Remaining items are from Confluence.
=> Improve HTMLObjectElement data.

javascript/builtins/Object.json
---
Updated `Object.assign` support for IE11. Included screen shot from the dev console.
```
var _a = Object.assign({a: 1, b: 2}, {c: 3, d: 4})
```
=> IE10 supports Object.assign

api/HTMLFormElement.json
just added a description to two events as per #1122
=> Add description to reset and submit events

javascript/builtins/Array.json, javascript/builtins/ArrayBuffer.json, javascript/builtins/AsyncFunction.json, javascript/builtins/DataView.json, javascript/builtins/Date.json, javascript/builtins/Float32Array.json, javascript/builtins/Float64Array.json, javascript/builtins/Function.json, javascript/builtins/Generator.json, javascript/builtins/Int16Array.json, javascript/builtins/Int32Array.json, javascript/builtins/Int8Array.json, javascript/builtins/Intl.json, javascript/builtins/Object.json, javascript/builtins/RegExp.json, javascript/builtins/TypedArray.json, javascript/builtins/Uint16Array.json, javascript/builtins/Uint32Array.json, javascript/builtins/Uint8Array.json, javascript/builtins/Uint8ClampedArray.json, javascript/classes.json, javascript/statements.json
This PR is created by a simple script that mirrors the compatibility data of all APIs from Chrome to Webview when it is set to "null". This should help reduce inconsistencies in the browser data.
=> Mirror Chrome -> Webview for javascript/*

api/HTMLInputElement.json
Adds information related to #3995
=> [Chrome]Addition to #3995.

api/Window.json
=> [Chrome]Additions to #3997.

test/lint.js, test/test-prefix.js
=> Check `webkit` prefix format for api/css compat data.

http/headers/alt-svc.json
See&nbsp;[bug&nbsp;1003448](https://bugzil.la/1003448) and&nbsp;[bug&nbsp;1113790](https://bugzil.la/1113790) for&nbsp;details.
review?(@Elchi3, @vinyldarkscratch)
=> feat(http): Add `Alt‑Svc` header

browsers/chrome_android.json
=> Fix release dates for Chrome Android

test/lint.js, test/test-browsers.js
Opened because of #3939.
review?(@Elchi3): This doesn’t currently require rebasing.
=> test: Refactor lint script to avoid globally mutable state

api/Document.json
=> Add IE11 to Document.documentElement compatibility table

api/MIDIAccess.json, api/MIDIConnectionEvent.json, api/MIDIInput.json, api/MIDIInputMap.json, api/MIDIMessageEvent.json, api/MIDIOutput.json, api/MIDIOutputMap.json, api/MIDIPort.json
C.f. https://caniuse.com/#feat=midi 
The entire API never made it into IE.
=> Web Midi is unsupported in IE

api/Presentation.json, api/PresentationAvailability.json, api/PresentationConnection.json, api/PresentationConnectionAvailableEvent.json, api/PresentationConnectionCloseEvent.json, api/PresentationConnectionList.json, api/PresentationReceiver.json, api/PresentationRequest.json
The entire API never made it into IE.
=> Presentation API is unsupported in IE

api/PaintRenderingContext2D.json, api/PaintSize.json, api/PaintWorkletGlobalScope.json
=> Paint API is unsupported in IE

package-lock.json, package.json, scripts/release-notes.js, test/test-browsers.js, test/test-prefix.js, test/test-schema.js, test/test-style.js, test/test-versions.js
Opened because of @lahmatiy’s review in https://github.com/mdn/data/pull/362#discussion_r274075034.
---
=> test: Use chalk for output styling

api/Notification.json
As per https://bugzilla.mozilla.org/show_bug.cgi?id=1429432
=> update notifications secure context fx data

http/headers/feature-policy.json
Currently implemented only in Firefox.
Source: https://bugzilla.mozilla.org/show_bug.cgi?id=1523958
(And searches of the code and/or issue trackers for each other browser)
=> Add Feature-Policy: display-capture

html/global_attributes.json
As per https://bugzilla.mozilla.org/show_bug.cgi?id=1119063
The Chrome data came from https://www.chromestatus.com/features/5680387573415936
I couldn't find details of the other browsers.
=> adding data for the autocomplete global attribute

api/InputEvent.json
As per https://bugzilla.mozilla.org/show_bug.cgi?id=1532527
I couldn't find anything on whether other browsers support this.
=> Add insertFromPasteAsQuotation inputType value

api/PerformanceNavigationTiming.json
per my testing and as mentioned here: https://webkit.org/blog/7956/new-webkit-features-in-safari-11/
Tested using Safari Developer Tools on desktop and via connected iPhone. 
=> Update Safari (+ iOS) compatibility

test/test-versions.js
This PR is designed to standardize the version test file, letting it follow the same function structure as the browser and prefix tests.  This will help maintain consistency across our code, as well as simply global changes to error reporting that may occur in the future.
=> Refactor test-versions.js

webextensions/api/browserAction.json, webextensions/api/events.json, webextensions/api/runtime.json, webextensions/api/sidebarAction.json, webextensions/api/tabs.json, webextensions/api/webRequest.json, webextensions/api/windows.json, webextensions/manifest/chrome_url_overrides.json, webextensions/manifest/commands.json, webextensions/manifest/incognito.json, webextensions/manifest/page_action.json, webextensions/manifest/theme.json
=> Sort features alphabetically in webextensions/*

svg/elements/animate.json, svg/elements/animateMotion.json, svg/elements/cursor.json, svg/elements/feDropShadow.json, svg/elements/font.json, svg/elements/marker.json, svg/elements/mask.json, svg/elements/missing-glyph.json, svg/elements/pattern.json, svg/elements/radialGradient.json, svg/elements/style.json, svg/elements/use.json
=> Sort features alphabetically in svg/*

http/headers/cache-control.json, http/headers/set-cookie.json
=> Sort features alphabetically in http/*

html/elements/area.json, html/elements/button.json, html/elements/iframe.json, html/elements/input/color.json, html/elements/li.json, html/elements/meta.json, html/elements/style.json, html/global_attributes.json
=> Sort features alphabetically in html/*

http/headers/cross-origin-resource-policy.json
=> Note that CORP is broken in Chrome >= 73 && < 75

mathml/elements/menclose.json, mathml/elements/mmultiscripts.json, mathml/elements/mo.json, mathml/elements/mspace.json
=> Sort features alphabetically in mathml/*

css/properties/list-style-type.json
See https://developer.mozilla.org/en-US/docs/Web/CSS/list-style-type. They are around for so long now, I don't think we should mark them as experimental anymore.
=> No longer mark list-style-types as experimental

css/properties/list-style-type.json
Please see https://github.com/mdn/browser-compat-data/issues/4148 for the research that went into this and where the version numbers come from.
I've decided to split this alphabetically by features (as it will most likely avoid merge conflicts best). Let me know if you have a better idea for how to make reviewing easy.
This PR is for list-style-type types letters A to C.
=> Update list-style-type part 1 (A to C)

css/properties/list-style-type.json
Please see #4148 for the research that went into this and where the version numbers come from.
This PR is for list-style-type types letters G to K.
=> Update list-style-type part 3 (G to K)

css/properties/list-style-type.json
Please see #4148 for the research that went into this and where the version numbers come from.
This PR is for list-style-type types letters L to P.
=> Update list-style-type part 4 (L to P)

css/properties/list-style-type.json
Please see #4148 for the research that went into this and where the version numbers come from.
This PR is for list-style-type types starting with U until the end of the file.
=> Update list-style-type part 6 (U to end)

css/properties/list-style-type.json
Please see #4148 for the research that went into this and where the version numbers come from.
This PR is for list-style-type types letters D to F.
=> Update list-style-type part 2 (D to F)

css/properties/align-items.json
The version number was determined based upon manual review.
=> Add Chrome version for css.properties.align-items.grid_context.start_end

css/at-rules/media.json
Chrome: https://crrev.com/656331  
Chrome Android: Same.
=> prefers-color-scheme: Add Chrome versions

css/at-rules/counter-style.json, css/at-rules/document.json, css/at-rules/keyframes.json, css/at-rules/page.json
Edge doesn't support counter-styles, document, or the specia page descriptors.
=> Complete Edge data for a few at-rules

.github/CODEOWNERS, README.md
This seems to have been forgotten in #4161
=> Update link to GOVERNANCE.md

api/HTMLMediaElement.json
=> Correct data about HTMLMediaElement.setSinkId.

api/Notification.json
https://bugs.chromium.org/p/chromium/issues/detail?id=971422
=> [Chromium] Add Android O note to notification.vibrate.

api/History.json
=> ie version 10 added for History.state

api/VisualViewport.json
But only on Android. Huzzah!
Source:
* https://bugzilla.mozilla.org/show_bug.cgi?id=1512813
=> VisualViewport enabled by default in Firefox 68 Android

http/headers/cross-origin-resource-policy.json
https://bugzilla.mozilla.org/show_bug.cgi?id=1459573
=> CORP shipping in Firefox :tada:

api/Element.json
Added notes to these events explaining what's changed.
Source:
* https://bugzilla.mozilla.org/show_bug.cgi?id=1379466#c56
=> Update Element with changes to click/dblclick/auxclick

html/elements/html.json
https://chromestatus.com/feature/5714236168732672
- [x ] Summarize your changes
=> Chrome started requiring a secure context for AppCache v70

api/CustomEvent.json
Fixes #4151.  All data is within the issue.
=> Update Safari versions for api.CustomEvent

webextensions/api/devtools.json, webextensions/api/menus.json, webextensions/api/webNavigation.json, webextensions/api/webRequest.json, webextensions/manifest/chrome_settings_overrides.json, webextensions/manifest/commands.json, webextensions/manifest/content_scripts.json, webextensions/manifest/incognito.json, webextensions/manifest/optional_permissions.json, webextensions/manifest/options_ui.json, webextensions/manifest/page_action.json, webextensions/manifest/permissions.json, webextensions/manifest/theme.json
Sub-PR of #3427 to sort all of the features within each of the individual folders.  This is a successor to #4125 to reflect the updates to the sort script.
=> Sort features in webextensions/*

javascript/builtins/ArrayBuffer.json, javascript/builtins/DataView.json, javascript/builtins/Date.json, javascript/builtins/Error.json, javascript/builtins/Function.json, javascript/builtins/Intl.json, javascript/builtins/Map.json, javascript/builtins/Number.json, javascript/builtins/Object.json, javascript/builtins/Proxy.json, javascript/builtins/RegExp.json, javascript/builtins/Set.json, javascript/builtins/SharedArrayBuffer.json, javascript/builtins/String.json, javascript/builtins/TypedArray.json, javascript/builtins/WeakMap.json, javascript/builtins/WeakSet.json, javascript/builtins/WebAssembly.json
Although there are open PRs that modify files within `javascript/`, this PR has been adapted so that it does not conflict with any of them.
=> Sort features in javascript/* (non-conflicting)

svg/elements/altGlyph.json, svg/elements/cursor.json, svg/elements/feBlend.json, svg/elements/feComposite.json, svg/elements/feDisplacementMap.json, svg/elements/feMorphology.json, svg/elements/filter.json, svg/elements/font-face.json, svg/elements/glyph.json, svg/elements/glyphRef.json, svg/elements/hkern.json, svg/elements/image.json, svg/elements/linearGradient.json, svg/elements/pattern.json, svg/elements/use.json, svg/elements/vkern.json
Sub-PR of #3427 to sort all of the features within each of the individual folders. This is a successor to #4126 to reflect the updates to the sort script.
=> Sort features in svg/*

http/headers/accept-ch.json, http/headers/content-security-policy.json, http/headers/feature-policy.json, http/headers/set-cookie.json, http/headers/x-frame-options.json
Although there are open PRs that modify files within `http/`, this PR does not conflict with any of them.
=> Sort features in http/*

html/elements/canvas.json, html/elements/form.json, html/elements/iframe.json, html/elements/menu.json, html/elements/meta.json, html/global_attributes.json
Although there are open PRs that modify files within `html/`, this PR has been adapted so that it does not conflict with any of them.
=> Sort features in html/* (non-conflicting)

css/at-rules/counter-style.json, css/at-rules/font-feature-values.json, css/properties/-moz-user-input.json, css/properties/align-content.json, css/properties/background-attachment.json, css/properties/background-clip.json, css/properties/background-image.json, css/properties/border-radius.json, css/properties/box-shadow.json, css/properties/break-after.json, css/properties/break-before.json, css/properties/clip-path.json, css/properties/color.json, css/properties/content.json, css/properties/cursor.json, css/properties/flex-basis.json, css/properties/font-variant-alternates.json, css/properties/height.json, css/properties/hyphens.json, css/properties/justify-content.json, css/properties/list-style-type.json, css/properties/overflow-wrap.json, css/properties/shape-outside.json, css/properties/text-align.json, css/properties/text-indent.json, css/properties/text-overflow.json, css/properties/user-select.json, css/properties/width.json, css/selectors/indeterminate.json, css/types/basic-shape.json
Although there are open PRs that modify files within `css/`, this PR has been adapted so that it does not conflict with any of them.
=> Sort features in css/* (non-conflicting)

api/DocumentOrShadowRoot.json
- Fix the listed compatibility of `elementsFromPoint` in Edge and Safari.
- Add a note about a behavior difference in msElementsFromPoint that results in a `null` return value.
- Safari support was cobbled together from a couple sources. One was this comment in the caniuse repo, stating that Safari 11 did not support it: https://github.com/Fyrd/caniuse/issues/2064#issuecomment-346444182 I also observed that it worked in the latest released version of 12. Unfortunately, the official release notes for 12 do not mention this feature, although the Safari Technology Preview notes do (https://developer.apple.com/safari/technology-preview/release-notes/#r37), indicating that it probably got released to the stable version in the 2-3 years …
=> elementsFromPoint fixes

css/selectors/part.json, html/global_attributes.json
See [Firefox bug 1505489][bmo‑1505489] and [Chrome bug 805271][crbug‑805271] for details.
---
[bmo‑1505489]: https://bugzilla.mozilla.org/show_bug.cgi?id=1505489
[crbug‑805271]: https://bugs.chromium.org/p/chromium/issues/detail?id=805271
review?(@ddbeck, @emilio)
=> feat(css, html): Add CSS Shadow Parts

api/Document.json
This data was obtained from manual testing.  Closes #4207.
=> Add IE version for Document.createElement

test/test-browsers.js
Fixes https://github.com/mdn/browser-compat-data/issues/3485.
Reviewers! This will fail a few lints, I'm submitting it as-is to show what they are, they need some discussion I think.
=> Lint for multiple support statements with only `version_added`

api/Element.json
=> Add note about iOS device limitation for api.Element.requestFullscreen

docs/data-guidelines.md
I forgot to remove this dropped section from the TOC during my previous PR.
=> Fix table of contents for data guidelines

docs/data-guidelines.md
Add information explaining that events are contained within the interfaces that receive them, and must be replicated in each such interface if there's more than one.
=> Explain events go inside target interfaces

css/selectors/has.json
Note that I didn’t add the same note for Android because the linked bug is only about Windows.
=> Link to Chrome bug for CSS selector :has

css/selectors/hostfunction.json
=> Update :host() function compatibility table

api/Element.json
Reference: https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/platform-apis/ff975529(v%3Dvs.85)
=> Add IE 9 as first version that supports Element.localName

css/types/counters.json
The export was wrong here (`attr` instead of `counters`)
Real values are based on caniuse https://caniuse.com/#feat=css-counters
=> Correct css.types.counters

api/XR.json, api/XRFrame.json, api/XSLTProcessor.json
=> Alphabetize XR,  XRFrame, XSLTProcessor APIs

css/properties/user-select.json
Safari seems to not really support this. Found several bugs:
- https://bugs.webkit.org/show_bug.cgi?id=100424
- https://bugs.webkit.org/show_bug.cgi?id=187651
- https://bugs.webkit.org/show_bug.cgi?id=118740
Chrome:
- https://www.chromestatus.com/feature/5062926088011776
=> Update user-select: all data

css/properties/list-style-type.json
Tested manually in Saucelabs
Test page: https://developer.mozilla.org/en-US/docs/Web/CSS/list-style-type
=> Update Chinese list-style-type types

webextensions/manifest/theme.json
=> Update to account for the latest theme changes

http/status.json
Fixes #4315 by adding basic browser compatibility to the JSON file.
=> Add HTTP 409 Conflict status

http/headers/accept-charset.json
This PR fixes #4252.  See linked issue for more details.
=> Add version_removed for Accept-Charset header

css/properties/-webkit-mask-composite.json, css/properties/-webkit-mask-position-x.json, css/properties/-webkit-mask-position-y.json
Fixes https://github.com/mdn/browser-compat-data/issues/4649
=> Update Firefox support for webkit masks

css/properties/grid-template-columns.json, css/properties/grid-template-rows.json
Adding the `subgrid` value of `grid-template-columns` and `grid-template-rows`: https://bugzilla.mozilla.org/show_bug.cgi?id=1496502
=> Adding the subgrid value

css/properties/appearance.json
This PR adds the Chromium and Safari versions for the compatibility values of `appearance`.  Information was obtained as follows:
> Implemented in f507bb59aba5d38ad936d4fd6912b22cd0b728bf
> Safari 3 by date
> Safari 3, Chrome 1
Relevant addition within the Git commit:
```cpp
// ./WebCore/css/CSSComputedStyleDeclaration.cpp
static PassRefPtr<CSSValue> valueForAppearance(EAppearance appearance)
{
switch (appearance) {
case NoAppearance:
return new CSSPrimitiveValue(CSS_VAL_NONE);
case CheckboxAppearance:
return new CSSPrimitiveValue(CSS_VAL_CHECKBOX);
case RadioAppearance:
return new CSSPrimitiveValue(CSS_VAL_RADIO);
case PushButtonAppearance:
return new CSSPrimitiveValue(CSS_VAL_PUSH_BUTTON);
case SquareButtonAppearance:
return new CSSPrimitiveValue(CSS_VAL_SQUARE_BUTTON);
case …
```
=> Add Chrome + Safari versions for css.properties.appearance.compat

api/Screen.json
Continuation off of #4629 that applies the same changes to all other Chromium browsers, as the original PR was merged a little prematurely.  @jpmedley, since you reviewed and approved the original PR, may I request you take a look at this one as well?  Thank you in advance!
=> Correct Chrome support for Screen interface (cont.)

browsers/nodejs.json, javascript/builtins/Promise.json
=> [NodeJS] Add support for `Promise.allSettled(…)`

test/test-real-values.js
=> Disallow null and true values for Chrome and Safari in css/

html/elements/input/date.json, html/elements/input/datetime-local.json, html/elements/input/month.json, html/elements/input/time.json, html/elements/input/week.json
=> Add Safari bug ID to several fields

test/lint.js, test/linter/index.js, test/linter/test-browsers.js, test/linter/test-prefix.js, test/linter/test-real-values.js, test/linter/test-schema.js, test/linter/test-style.js, test/linter/test-versions.js
=> test: Move linter implementation into `test/linter/` subdirectory

javascript/builtins/Intl.json
See https://bugzilla.mozilla.org/show_bug.cgi?id=1473229
=> Firefox 70 implements RelativeTimeformat#formatToParts

test/linter/test-real-values.js
Fixes https://github.com/mdn/browser-compat-data/issues/3710 :tada: :tada: :tada:
=> Disallow true,null for more browsers in css/*

javascript/classes.json
This PR fixes some consistency issues between browsers within JavaScript classes by copying Chromium data and removing mention of flags from Samsung Internet and WebView.
=> Fix consistency within JavaScript classes

javascript/statements.json
Fixes #3198.  More details within the issue.
=> Behavior for let keyword does not function properly in IE/Edge 11-13

browsers/firefox.json
=> Firefox 69 release

webextensions/api/identity.json
=> Set Opera version for webextensions.api.identity.getRedirectURL

css/properties/font-size-adjust.json
This PR is created based upon https://github.com/mdn/browser-compat-data/pull/4738#discussion_r320303396.
=> Fix Chromium versions for font-size-adjust

api/Response.json
Fixes #4580, more details in the issue.
=> Fix compat data for api.Response.ok/status

css/properties/color.json
This PR fixes #4169.  Description is pretty loose, I'm open to suggestions on how to improve it!
=> Add data regarding CSS Colors Level 4 function aliases

css/types/image.json
Added paint function.
For https://developer.mozilla.org/en-US/docs/Web/CSS/paint
and
https://developer.mozilla.org/en-US/docs/Web/CSS/image
Data from 
http://ishoudinireadyyet.com/
=> added paint() function

GOVERNANCE.md
Collaboration announcement: https://hacks.mozilla.org/2019/09/caniuse-and-mdn-compat-data-collaboration/
I'd like to make @Fyrd a BCD Peer as defined here: https://github.com/mdn/browser-compat-data/blob/master/GOVERNANCE.md#peers
Alexis, can you please read our governance doc on the role of a Peer and then also read and agree to abide by the [Mozilla Commit Access Requirements](https://www.mozilla.org/en-US/about/governance/policies/commit/requirements/) and state in a comment:
> I have read, and agree to abide by, the Mozilla Commit Access Requirements.
I'm requesting approval from the other BCD Owners and then I will give @Fyrd write access to the repo after this PR has been merged :-)
=> Add Alexis Deveria as a BCD Peer

browsers/chrome.json, browsers/chrome_android.json, browsers/opera.json, browsers/webview_android.json
Adding in some new Chromiums:
* Chrome/Chrome Android/Android Webview v79
* Opera v64/65
=> adding new chromium versions as of September 2019

api/FeaturePolicy.json
See https://bugzilla.mozilla.org/show_bug.cgi?id=1514474
=> Firefox 70 implements FeaturePolicy.features()

http/headers/x-frame-options.json
See https://bugzilla.mozilla.org/show_bug.cgi?id=1301529
=> Firefox 70 removes XFO allow-from

javascript/builtins/Intl.json
Firefox 70: https://bugzilla.mozilla.org/show_bug.cgi?id=1521819
Chrome 73: https://bugs.chromium.org/p/v8/issues/detail?id=8613
=> Add numberingSystem to RelativeTimeFormat#resolvedOptions

css/properties/contain.json
Added the Samsung Internet Support for the CSS "conatin" property which is verified through mannual testing and [caniuse](https://caniuse.com/#search=contain)
=> Added Samsung Internet support for Css "contain"  property

webextensions/manifest/theme.json
Closing a code tag that was missed and causing formatting errors in the compatibility table notes.
=> Fix closing bracket

javascript/builtins/BigInt.json
Updated BigInt support for Samsung Internet Android by mannual testing
=> Updated BigInt support for samsung Internet

javascript/builtins/Date.json
This PR adds IE versions for the Date builtin for JavaScript based upon manual testing.  The data is as follows:
javascript.builtins.Date - 3
javascript.builtins.Date.UTC - 3
javascript.builtins.Date.getDate - 3
javascript.builtins.Date.getDay - 3
javascript.builtins.Date.getFullYear - 4
javascript.builtins.Date.getHours - 3
javascript.builtins.Date.getMilliseconds - 4
javascript.builtins.Date.getMinutes - 3
javascript.builtins.Date.getMonth - 3
javascript.builtins.Date.getSeconds - 3
javascript.builtins.Date.getTime - 3
javascript.builtins.Date.getUTCDate - 4
javascript.builtins.Date.getUTCDay - 4
javascript.builtins.Date.getUTCFullYear - 4
javascript.builtins.Date.getUTCHours - 4
javascript.builtins.Date.getUTCMilliseconds - 4
javascript.builtins.Date.getUTCMinutes - 4 …
=> Add IE versions for JavaScript Date builtin (JS builtins part 2)

javascript/builtins/EvalError.json, javascript/builtins/Function.json, javascript/builtins/Math.json, javascript/builtins/Number.json
This PR adds IE versions for various JavaScript builtins based upon manual testing. The data is as follows:
javascript.builtins.EvalError - 5.5
javascript.builtins.Function - 4
javascript.builtins.Function.arguments - 4
javascript.builtins.Function.call - 5.5
javascript.builtins.Function.displayName - false
javascript.builtins.Function.length - 4
javascript.builtins.Function.prototype - 4 
javascript.builtins.Math.E - 3
javascript.builtins.Math.LN2 - 3
javascript.builtins.Math.LN10 - 3
javascript.builtins.Math.LOG2E - 3
javascript.builtins.Math.LOG10E - 3
javascript.builtins.Math.PI - 3
javascript.builtins.Math.SQRT1_2 - 3
javascript.builtins.Math.SQRT2 - 3
javascript.builtins.Math.abs - 3
javascript.builtins.Math.acos - 3
javascript.builtins.Math.asin - 3
javascript.builtins.Math.atan - …
=> Add IE versions for JavaScript builtins (part 3)

javascript/builtins/Promise.json
See [bug 1549176](https://bugzilla.mozilla.org/show_bug.cgi?id=1549176) for details.
=> [Firefox] Bug 1549176: Ship `Promise.allSettled(…)`

css/properties/font-optical-sizing.json
https://chromestatus.com/feature/5685958032752640
Chrome is adding support in v79
=> Add Chrome support for font-optical-sizing

http/headers/x-xss-protection.json
https://www.chromium.org/developers/design-documents/xss-auditor
https://chromestatus.com/feature/5021976655560704
Related: #4525
=> Chrome removed support for X-XSS-Protection header

browsers/opera.json
Looks like Opera 64 is out now!
=> Opera 64 is released

javascript/statements.json
This fixes #4687.  While I have not intended to track down the version numbers in this PR, I'm open to adding them if anyone has them!
=> Add worker support for import JavaScript statement

webextensions/manifest/permissions.json
Addition of details about the search keyword, documenting its introduction in version 63 as per
https://bugzilla.mozilla.org/show_bug.cgi?id=1477271 to resolve https://github.com/mdn/sprints/issues/1740
=> Search keyword addition to permissions key

api/Clipboard.json
These numbers were previously missing, and should be the same as chrome and chrome_android.
=> Add Clipboard API version numbers for webview.

api/Navigator.json
https://www.chromestatus.com/features/4777349178458112
=> Add support for navigator.share in Android Chrome 75.

api/XRSessionEvent.json, api/XRSpace.json, api/XRView.json, api/XRViewerPose.json, api/XRViewport.json, api/XRWebGLLayer.json
My source is the WebXR product manager at Google.
=> Add XR in Chrome 79, part I.

browsers/nodejs.json
=> Add NodeJS 0.9.1

xslt/elements/stylesheet.json
This updates the xslt/ folder for #5028
=> Update Samsung Internet Data, Updating folder xslt/

api/XREnvironmentBlendMode.json
Add XREnvironmentBlendMode.json to cover this
enum type.
Source: 
* https://immersive-web.github.io/webxr-ar-module/#xrenvironmentblendmode-enum
=> Add XREnvironmentBlendMode

api/CSS.json, css/at-rules/property.json
https://www.chromestatus.com/feature/5640265926705152
=> Add items from CSS Props and Vals L1.

api/CSSVariableReferenceValue.json
The reason for this change will be obvious when you look at what I did.
=> Fix URLs in CSSVariableReferenceValue.json.

javascript/builtins/Date.json
This adds real values for the Date built-in for JavaScript for Chrome and Chrome-based browsers.  Data is as follows:
javascript.builtins.Date - 1
javascript.builtins.Date.UTC - 1
javascript.builtins.Date.getDate - 1
javascript.builtins.Date.getDay - 1
javascript.builtins.Date.getFullYear - 1
javascript.builtins.Date.getHours - 1
javascript.builtins.Date.getMilliseconds - 1
javascript.builtins.Date.getMinutes - 1
javascript.builtins.Date.getMonth - 1
javascript.builtins.Date.getSeconds - 1
javascript.builtins.Date.getTime - 1
javascript.builtins.Date.getTimezoneOffset - 1
javascript.builtins.Date.getUTCDate - 1
javascript.builtins.Date.getUTCDay - 1
javascript.builtins.Date.getUTCFullYear - 1
javascript.builtins.Date.getUTCHours - 1
javascript.builtins.Date.getUTCMilliseconds - 1 …
=> Add Chromium real values for JavaScript Date built-in

api/TransformStream.json, api/TransformStreamDefaultController.json
https://www.chromestatus.com/features/5466425791610880
=> [Chrome] Add transform streams.

http/headers/clear-site-data.json
=> Update `Clear-Site-Data` to include value descriptions

api/Element.json
As per https://bugzilla.mozilla.org/show_bug.cgi?id=1559077
This is behind a pref in Fx 71; I did some manual testing to determine support in other browsers.
=> add data for Element.part

api/WindowOrWorkerGlobalScope.json
=> Add NodeJS version for queueMicrotask

javascript/builtins/Object.json
=> Fix WebView support for Object.assign()

javascript/operators/arithmetic.json, javascript/operators/assignment.json, javascript/operators/bitwise.json, javascript/operators/comma.json, javascript/operators/comparison.json, javascript/operators/conditional.json, javascript/operators/delete.json, javascript/operators/function.json, javascript/operators/function_star.json, javascript/operators/grouping.json, javascript/operators/in.json, javascript/operators/instanceof.json, javascript/operators/logical.json, javascript/operators/new.json, javascript/operators/property_accessors.json, javascript/operators/this.json, javascript/operators/typeof.json, javascript/operators/void.json, javascript/operators/yield_star.json
This PR adds the Chromium versions for JavaScript operators based upon manual testing.  Data is as follows:
javascript.operators.arithmetic.addition - 1
javascript.operators.arithmetic.decrement - 2
javascript.operators.arithmetic.division - 1
javascript.operators.arithmetic.increment - 2
javascript.operators.arithmetic.multiplication - 1
javascript.operators.arithmetic.remainder - 1
javascript.operators.arithmetic.subtraction - 1
javascript.operators.arithmetic.unary_negation - 1
javascript.operators.arithmetic.unary_plus - 1
javascript.operators.assignment.addition - 1
javascript.operators.assignment.bitwise_and - 1
javascript.operators.assignment.bitwise_or - 1
javascript.operators.assignment.bitwise_xor - 1
javascript.operators.assignment.division - 1 …
=> Update Chromium versions for JavaScript operators

javascript/builtins/Intl.json
Added Compat-data for timeStyle DateStyle 
https://www.chromestatus.com/features/5091631933947904
=> Add dateStyle/timeStyle options for JavaScript DateTimeFormat

http/data-url.json, http/headers/accept-ch-lifetime.json, http/headers/accept-ch.json, http/headers/clear-site-data.json, http/headers/content-dpr.json, http/headers/content-security-policy.json, http/headers/device-memory.json, http/headers/downlink.json, http/headers/dpr.json, http/headers/ect.json, http/headers/expect-ct.json, http/headers/feature-policy.json, http/headers/public-key-pins-report-only.json, http/headers/public-key-pins.json, http/headers/report-to.json, http/headers/rtt.json, http/headers/save-data.json, http/headers/server-timing.json, http/headers/snapshot-content-location.json, http/headers/viewport-width.json, http/headers/width.json, http/headers/x-content-type-options.json, http/headers/x-xss-protection.json
This updates the HTTP folder for #5028
=> Update Samsung Internet Data, Updating folder http/

.github/CODEOWNERS, GOVERNANCE.md
Irene has done fantastic work looking after WebExtensions compat data. Thank you for all your work, Irene!
Richard Bloor (@rebloor) is taking over from now on. Welcome Richard!
=> Make Richard Bloor a BCD peer for WebExtensions data

package-lock.json, package.json
This&nbsp;updates **ora**&nbsp;to&nbsp;v4.
See&nbsp;[ora@v4.0.0](https://github.com/sindresorhus/ora/releases/tag/v4.0.0), [ora@v4.0.1](https://github.com/sindresorhus/ora/releases/tag/v4.0.1), [ora@v4.0.2](https://github.com/sindresorhus/ora/releases/tag/v4.0.2) and&nbsp;[ora@v4.0.3](https://github.com/sindresorhus/ora/releases/tag/v4.0.3) for&nbsp;changes.
=> chore(deps): update dependency ora to v4

css/at-rules/charset.json, css/at-rules/font-face.json, css/at-rules/media.json, css/at-rules/namespace.json, css/at-rules/page.json, css/at-rules/supports.json, css/at-rules/viewport.json
=> Update Samsung Internet Data, Updating folder css/at-rules/

package-lock.json, package.json
This&nbsp;updates **yargs**&nbsp;to&nbsp;v15.
=> chore(deps): update dependency yargs to v15

css/types/attr.json, css/types/basic-shape.json, css/types/calc.json, css/types/dimension.json, css/types/flex.json, css/types/global_keywords.json, css/types/image.json, css/types/length-percentage.json, css/types/length.json, css/types/percentage.json, css/types/position.json, css/types/resolution.json, css/types/shape.json, css/types/string.json, css/types/transform-function.json, css/types/url.json
=> Update Samsung Internet Data, Updating folder css/types/

api/OES_fbo_render_mipmap.json
See https://bugzilla.mozilla.org/show_bug.cgi?id=1584277
=> Firefox 71 ships OES_fbo_render_mipmap

css/properties/contain.json
The Containment spec is PR https://www.w3.org/TR/css-contain-1/
The `contain` property has two implementations.
=> set contain to not experimental

api/AuthenticationAssertion.json, api/Headers.json, api/MediaCapabilities.json, api/Navigator.json, api/PaymentCurrencyAmount.json, api/Response.json, api/ScopedCredential.json, api/ScopedCredentialInfo.json, api/VideoTrackList.json, api/WebAuthentication.json, css/properties/color.json, css/properties/column-gap.json, css/properties/grid-column-start.json, css/properties/grid-column.json, css/properties/line-height-step.json, css/properties/text-align-last.json, css/selectors/is.json, css/types/image.json, html/elements/img.json, html/elements/video.json, html/global_attributes.json, http/headers/feature-policy.json
This applies migration 002 to remove flagged entries for WebView.
=> Migration 002: Perform removal of WebView flagged entries

webextensions/api/captivePortal.json, webextensions/manifest/permissions.json
Includes:
* update to permissions.json to include captivePortal
* new captivePortal.json
See https://bugzilla.mozilla.org/show_bug.cgi?id=1545159
=> Data for captivePortal

css/properties/image-rendering.json
The spec is in CR and there are two implementations of these features.
=> Remove experimental flags for image-rendering

css/selectors/selection.json
selection has wide browser support, removing the experimental flag.
=> remove experimental flag from ::selection

css/selectors/placeholder-shown.json, css/selectors/placeholder.json
Removing experimental flag for placeholder and placeholder-shown as we have two implementations and the spec is stable.
=> Remove experimental flag for placeholder and placeholder-shown

css/properties/list-style-type.json
See https://github.com/mdn/browser-compat-data/pull/5198#pullrequestreview-322077062.
=> Update list-style-type.json: <string>, add Opera

test/linter/test-versions.js
This PR introduces the linter to finish up #4609.
=> Migration 002: Prevent WebView entries from containing flags

javascript/builtins/RegExp.json
Bump some RegExp methods due to symbol availability. C.f. https://github.com/babel/babel/issues/10758#issuecomment-558212778
=> chore: bump some regex builtin chrome versions

scripts/compare-features.js, scripts/fix-browser-order.js, scripts/fix-feature-order.js, scripts/fix.js, scripts/release-notes.js, scripts/statistics.js, scripts/traverse.js, test/lint.js, test/test-compare-features.js, test/test-migrations.js, test/test-regexes.js, test/test-utils.js, test/utils.js, types.d.ts
This PR applies the new Prettier styling to all files, making our styling rules consistent.
=> Apply Prettier (Migration #004)

javascript/builtins/Array.json, javascript/builtins/ArrayBuffer.json, javascript/builtins/Float32Array.json, javascript/builtins/Float64Array.json, javascript/builtins/Int16Array.json, javascript/builtins/Int32Array.json, javascript/builtins/Int8Array.json, javascript/builtins/SharedArrayBuffer.json, javascript/builtins/TypedArray.json, javascript/builtins/Uint16Array.json, javascript/builtins/Uint32Array.json, javascript/builtins/Uint8Array.json, javascript/builtins/Uint8ClampedArray.json
This PR adds the data for Safari for the Array JavaScript builtins.  Data is as follows:
javascript.builtins.Array - 1
javascript.builtins.Array.concat - 1
javascript.builtins.Array.every - 3
javascript.builtins.Array.filter - 3
javascript.builtins.Array.forEach - 3
javascript.builtins.Array.indexOf - 3
javascript.builtins.Array.join - 1
javascript.builtins.Array.lastIndexOf - 3
javascript.builtins.Array.length - 1
javascript.builtins.Array.map - 3
javascript.builtins.Array.pop - 1
javascript.builtins.Array.prototype - 3
javascript.builtins.Array.push - 1
javascript.builtins.Array.reverse - 1
javascript.builtins.Array.shift - 1
javascript.builtins.Array.slice - 1
javascript.builtins.Array.some - 3
javascript.builtins.Array.sort - 1
javascript.builtins.Array.sort.stable - (don't actually …
=> Add Safari data for Array JavaScript builtins

css/properties/offset-position.json
attempting to remove unwanted note from `offset-position`
=> Chrisdavidmills offset position

api/IDBCursor.json, api/IDBCursorWithValue.json, api/IDBDatabase.json, api/IDBEnvironment.json, api/IDBFactory.json, api/IDBIndex.json, api/IDBKeyRange.json, api/IDBObjectStore.json, api/IDBOpenDBRequest.json, api/IDBRequest.json, api/IDBTransaction.json, api/IDBVersionChangeEvent.json
=> Replace "notes": "partial" with partial implementation in IDB APIs

api/MediaKeyStatusMap.json
Remove non-existent MDN URL from `api.MediaKeyStatusMap`.
#5201
=> Remove missing MDN URL from api.MediaKeyStatusMap

api/Headers.json
Fixes URLs for Web/API/Headers.json
This was found by #5201, blocks #5273. These bugs were probably introduced in #5257.
CC @vinyldarkscratch @sideshowbarker 
=> Fixup MDN URLs: Web/API/Headers.json

api/MediaSession.json
Fixes URLs for `api/MediaSession.json`.
This was found by #5201, blocks #5273.
=> Fix MDN URL: api/MediaSession.json

css/selectors/-moz-system-metric.json
These articles have been moved to the new URLs that match the overall MDN URL convention.
These URLs fail during test with linter from #5201, so they block #5273 or require an exception.
=> Update MDN URLs: css.selectors.-moz-system-metric

webextensions/api/browserAction.json, webextensions/api/pageAction.json
Added compatibility data for both tab (retrospective) and OnClickData to OnClicked for both page and browser actions. This supports the introduction of OnClickData through [1405031](https://bugzilla.mozilla.org/show_bug.cgi?id=1405031).
=> Click events for browserAction and pageAction

index.js, scripts/migrations/001-sort-features.js, scripts/migrations/002-remove-webview-flags.js, scripts/migrations/002-remove-webview-flags.test.js, scripts/migrations/003-sort-features.js, scripts/migrations/004-prettify.js, test/linter/index.js, test/linter/test-browsers.js, test/linter/test-consistency.js, test/linter/test-descriptions.js, test/linter/test-links.js, test/linter/test-prefix.js, test/linter/test-real-values.js, test/linter/test-schema.js, test/linter/test-style.js, test/linter/test-versions.js
Apparently Prettier doesn't reach files beyond the first folders, or the root folder.  This PR applies Prettier to those files.  A fix has been implemented in #5288 (but it can be split out upon request).
=> Apply Prettier to subfolders + index.js

css/properties/display.json, css/properties/offset-path.json, css/properties/text-align-last.json
Quick follow-up to #5156 to finish up some mirroring.
=> Finish mirroring Samsung Internet in css/properties/*

api/WindowOrWorkerGlobalScope.json
As per https://bugzilla.mozilla.org/show_bug.cgi?id=1591892.
=> adding crossOriginIsolated property

html/elements/img.json
[This post](https://webkit.org/blog/8216/new-webkit-features-in-safari-11-1/) said "HTML Image Decoding" was a new feature in Safari 11.1.
=> Update "decoding" support of Safari

api/Notification.json, api/PushManager.json
As per https://bugzilla.mozilla.org/show_bug.cgi?id=1593644
The intent to ship is probably easier to understand: https://bugzilla.mozilla.org/show_bug.cgi?id=1593644
=> adding note about user gestures

webextensions/api/browserSettings.json
Update as per [1592687](https://bugzilla.mozilla.org/show_bug.cgi?id=1592687)
=> Added details for browserSettings.ftpProtocolEnabled

webextensions/api/captivePortal.json
See [Expose canonical URL in the captive portal API](https://bugzilla.mozilla.org/show_bug.cgi?id=1592932)
=> Add canonicalURL to the captivePortal API

css/at-rules/media.json
Based on the discussions in https://github.com/mdn/sprints/issues/2402 this PR updates the experimental flags on various media features.
=> update media features experimental flags

css/properties/backdrop-filter.json
As discussed in https://github.com/mdn/sprints/issues/2402 updating the experimental flag.
=> update experimental flag on backdrop-filter

css/properties/list-style-type.json, css/properties/list-style.json
As part of my work on https://github.com/mdn/sprints/issues/2402 updating `list-style` and `list-style-type` values to remove experimental flag. Spec is in CR with no issues on these.
=> updates to list-style experimental flags

css/properties/scrollbar-color.json, css/properties/scrollbar-width.json
As part of my work on https://github.com/mdn/sprints/issues/2402 updating the experimental flag on the CSS Scrollbars properties
=> CSS Scrollbars experimental flag updates

css/properties/text-indent.json
As part of my work on https://github.com/mdn/sprints/issues/2402 updating the experimental flags on the `text-indent` property values of `hanging` and `each-line`.
=> update experimental flag text-indent

css/selectors/attribute.json
As part of my work on https://github.com/mdn/sprints/issues/2402 updating the case sensitive modifier for the attribute selector.
=> change experimental flag case sensitive modifier

css/types/image.json
As part of my work on https://github.com/mdn/sprints/issues/2402 updating experimental flags in image, I have left element as this has issues in the spec.
=> updating experimental flags on image

api/CanvasPattern.json
https://html.spec.whatwg.org/multipage/#dom-canvaspattern-settransform defines CanvasPattern:setTransform as a standard feature.
=> Mark CanvasPattern:setTransform as standard

css/selectors/column.json
**Specification:** https://drafts.csswg.org/selectors-4/#the-column-combinator
=> feat(css): Add the CSS4 column combinator (`||`)

css/at-rules/page.json
As part of my work on https://github.com/mdn/sprints/issues/2402 updating experimental flags on `@page`
=> update experimental flag @page

css/at-rules/viewport.json
As part of my work on https://github.com/mdn/sprints/issues/2402 updating the `viewport-fit` and `orientation` experimental flags for `viewport`.
=> updating experimental flags viewport

package-lock.json, package.json
Title says it all; this PR updates Prettier to version 1.19.1.
=> Update Prettier to 1.19.1

api/MediaRecorder.json, api/XRWebGLLayerInit.json
Added the XRWebGLLayerInit dictionary's data to BCD.
See:
* https://immersive-web.github.io/webxr/#xrwebgllayer-interface
* https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/renderer/modules/xr/xr_webgl_layer_init.idl;bpv=1?originalUrl=https:%2F%2Fcs.chromium.org%2F
=> Add xrwebgllayerinit

javascript/operators/arithmetic.json, javascript/operators/assignment.json, javascript/operators/bitwise.json, javascript/operators/class.json, javascript/operators/comma.json, javascript/operators/comparison.json, javascript/operators/conditional.json, javascript/operators/delete.json, javascript/operators/function.json, javascript/operators/function_star.json, javascript/operators/grouping.json, javascript/operators/in.json, javascript/operators/instanceof.json, javascript/operators/logical.json, javascript/operators/new.json, javascript/operators/new_target.json, javascript/operators/property_accessors.json, javascript/operators/spread.json, javascript/operators/super.json, javascript/operators/this.json, javascript/operators/typeof.json, javascript/operators/void.json
This PR sets the Safari versions for various JavaScript operators.  Data is as follows:
javascript.operators.arithmetic.addition - 1
javascript.operators.arithmetic.decrement - 4
javascript.operators.arithmetic.division - 1
javascript.operators.arithmetic.increment - 4
javascript.operators.arithmetic.multiplication - 1
javascript.operators.arithmetic.remainder - 1
javascript.operators.arithmetic.subtraction - 1
javascript.operators.arithmetic.unary_negation - 1
javascript.operators.arithmetic.unary_plus - 1
javascript.operators.assignment.addition - 1
javascript.operators.assignment.bitwise_and - 1
javascript.operators.assignment.bitwise_or - 1
javascript.operators.assignment.bitwise_xor - 1
javascript.operators.assignment.division - 1
javascript.operators.assignment.left_shift - 1 …
=> Set Safari versions for JavaScript operators

javascript/builtins/Array.json, javascript/builtins/Boolean.json, javascript/builtins/Date.json, javascript/builtins/Function.json, javascript/builtins/Generator.json, javascript/builtins/Intl.json, javascript/builtins/Math.json, javascript/builtins/Number.json, javascript/builtins/Object.json, javascript/builtins/RegExp.json, javascript/builtins/String.json, javascript/statements.json
This PR mirrors Chrome Android to Webview for all of the remaining JavaScript entries.
=> Mirror Chrome Android -> Webview for JavaScript

GOVERNANCE.md
Estelle's contract is over unfortunately. Thanks for all the work you've contributed to MDN and mdn-browser-compat-data.
=> Remove Estelle from peer list

api/Body.json
**Summary**:
Update Safari, Safari iOS, chrome mobile support for [Body API](https://developer.mozilla.org/en-US/docs/Web/API/Body) 
**Data**:
* Apple DN: https://developer.apple.com/documentation/webkitjs/fetchbody
* Chromium commit: https://github.com/chromium/chromium/commit/651abb3f560b95d7c9748ed7b7ea1470af2a2a76, introduced in Chrome: 45.0.2454.101
**Tests**
Testing with the Page 👉: https://software.hixie.ch/utilities/js/live-dom-viewer/?saved=7648
macOS Sierra, Safari 10.2 screenshot
iOS 12.1.4, iPad Air 2 screenshot
Android 8.0.0, Motorola Moto G6, chrome screenshot:
=> add body api safari, safari mobile, chrome android support

browsers/edge.json
I couldn't find a traditional release notes page. Chatted with @MSEdgeDev on twitter and this was the closest thing we could find.
=> Add first Chromium-based Edge release

css/properties/overscroll-behavior-block.json, css/properties/overscroll-behavior-inline.json
A new PR as everything had gone the way of the pear over at #5460
=> adding overscroll-behavior-block and -inline

api/Element.json
These reflect the changes recently made in api/DOMTokenList.json
=> Updated version numbers for classList add/remove

api/HTMLVideoElement.json, api/VideoPlaybackQuality.json
See https://bugs.chromium.org/p/chromium/issues/detail?id=644731#c47 and
https://web-confluence.appspot.com/#!/catalog?q=%22getVideoPlaybackQuality%22
cc @jpmedley for review
=> Update getVideoPlaybackQuality data for Chrome etc

javascript/builtins/Promise.json
See https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/Promise
=> Correct Promise ctor mdn/spec urls

scripts/fix-format.js, test/test-format.js
Title says it all!  This PR enforces our documentation to follow our Prettier formatting.
=> Enforce Markdown Prettier formatting in linter

javascript/builtins/globals.json
=> fix(JavaScript): Correct Opera support for `globalThis`

browsers/nodejs.json
=> Add NodeJS 13.2.0

javascript/builtins/Boolean.json, javascript/builtins/Number.json, javascript/builtins/String.json, javascript/builtins/globals.json
This PR sets the version numbers for various JavaScript builtins -- specifically the basics and globals -- for Opera and Opera Android, based upon manual testing. This is a part of a personal project to eliminate as many true/null values in Opera as we can.
The versions are as follows:
javascript.builtins.Boolean - 3
javascript.builtins.Boolean.Boolean - 4
javascript.builtins.Boolean.toString - 4
javascript.builtins.Boolean.valueOf - 4
javascript.builtins.Number - 3
javascript.builtins.Number.MAX_SAFE_INTEGER - Blink
javascript.builtins.Number.MAX_VALUE - 3
javascript.builtins.Number.MIN_SAFE_INTEGER - Blink
javascript.builtins.Number.MIN_VALUE - 3
javascript.builtins.Number.NaN - 3
javascript.builtins.Number.NEGATIVE_INFINITY - 3
javascript.builtins.Number.Number - 3 …
=> Set versions for Opera for JavaScript basic + global builtins

javascript/builtins/Array.json, javascript/builtins/ArrayBuffer.json, javascript/builtins/DataView.json, javascript/builtins/Float32Array.json, javascript/builtins/Float64Array.json, javascript/builtins/Int16Array.json, javascript/builtins/Int32Array.json, javascript/builtins/Int8Array.json, javascript/builtins/TypedArray.json, javascript/builtins/Uint16Array.json, javascript/builtins/Uint32Array.json, javascript/builtins/Uint8Array.json, javascript/builtins/Uint8ClampedArray.json
This PR sets the version numbers for various JavaScript array and array-like builtins for Opera and Opera Android, based upon manual testing. This is a part of a personal project to eliminate as many true/null values in Opera as we can.
The versions are as follows:
javascript.builtins.Array - 4
javascript.builtins.Array.Array - 4
javascript.builtins.Array.concat - 4
javascript.builtins.Array.every - 9.5
javascript.builtins.Array.fill - Blink
javascript.builtins.Array.filter - 9.5
javascript.builtins.Array.forEach - 9.5
javascript.builtins.Array.from - Blink
javascript.builtins.Array.indexOf - 9.5
javascript.builtins.Array.join - 4
javascript.builtins.Array.lastIndexOf - 9.5
javascript.builtins.Array.length - 4
javascript.builtins.Array.map - 9.5
javascript.builtins.Array.of - Blink …
=> Set versions for Opera for JavaScript Array/ArrayBuffer/TypedArray builtins

javascript/builtins/Date.json
This PR sets the version numbers for the JavaScript Date builtin for Opera and Opera Android, based upon manual testing. This is a part of a personal project to eliminate as many true/null values in Opera as we can.
The versions are as follows:
javascript.builtins.Date - 3
javascript.builtins.Date.Date - 3
javascript.builtins.Date.UTC - 3
javascript.builtins.Date.getDate - 3
javascript.builtins.Date.getDay - 3
javascript.builtins.Date.getFullYear - 4
javascript.builtins.Date.getHours - 3
javascript.builtins.Date.getMilliseconds - 4
javascript.builtins.Date.getMinutes - 3
javascript.builtins.Date.getMonth - 3
javascript.builtins.Date.getSeconds - 3
javascript.builtins.Date.getTime - 3
javascript.builtins.Date.getTimezoneOffset - 3
javascript.builtins.Date.getUTCDate - 4 …
=> Set versions for Opera for JavaScript Date builtin

javascript/operators/arithmetic.json, javascript/operators/assignment.json, javascript/operators/bitwise.json, javascript/operators/class.json, javascript/operators/comma.json, javascript/operators/comparison.json, javascript/operators/conditional.json, javascript/operators/delete.json, javascript/operators/destructuring.json, javascript/operators/function.json, javascript/operators/grouping.json, javascript/operators/in.json, javascript/operators/instanceof.json, javascript/operators/logical.json, javascript/operators/new.json, javascript/operators/new_target.json, javascript/operators/object_initializer.json, javascript/operators/property_accessors.json, javascript/operators/super.json, javascript/operators/this.json, javascript/operators/typeof.json, javascript/operators/void.json, javascript/operators/yield.json
This PR sets the version numbers for various JavaScript operators for Opera and Opera Android, based upon manual testing. This is a part of a personal project to eliminate as many true/null values in Opera as we can.
The versions are as follows:
javascript.operators.arithmetic.addition - 3
javascript.operators.arithmetic.decrement - 3
javascript.operators.arithmetic.division - 3
javascript.operators.arithmetic.exponentiation - Blink
javascript.operators.arithmetic.increment - 3
javascript.operators.arithmetic.multiplication - 3
javascript.operators.arithmetic.remainder - 3
javascript.operators.arithmetic.subtraction - 3
javascript.operators.arithmetic.unary_negation - 3
javascript.operators.arithmetic.unary_plus - 4
javascript.operators.assignment.addition - 3 …
=> Set versions for Opera for JavaScript operators

javascript/builtins/Array.json, javascript/builtins/DataView.json, javascript/builtins/Date.json, javascript/builtins/Function.json, javascript/builtins/Generator.json, javascript/builtins/Intl.json, javascript/builtins/Math.json, javascript/builtins/Number.json, javascript/builtins/Promise.json, javascript/builtins/String.json, javascript/builtins/Symbol.json, javascript/builtins/TypedArray.json, javascript/builtins/WebAssembly.json, javascript/functions.json, javascript/operators/object_initializer.json, javascript/operators/spread.json, javascript/statements.json
This PR performs a mirroring (from the mirroring script) of Opera data to Opera Android for javascript/* when Opera Android is `true` or `null`.
=> Mirror Opera -> Opera Android for javascript/*

css/properties/background-image.json, css/properties/word-spacing.json
https://github.com/mdn/browser-compat-data/pull/5630 broke master. This fixes the consistency issues.
=> Fix consistency in Opera CSS compat data

css/properties/grid-template-rows.json, css/properties/perspective-origin.json, css/properties/perspective.json, css/properties/transform-style.json
This PR updates the remaining CSS data for Opera and Opera Android, letting us reach 100% completion of Opera's CSS data.
=> Update remaining CSS data for Opera

javascript/builtins/Object.json, javascript/classes.json
This PR updates the remaining JavaScript statements for Opera and Opera Android.
=> Update remaining JavaScript data for Opera

css/at-rules/media.json
This PR adds data for nested CSS media queries, and thus fixes #5550.  See the issue for more details.
=> Add data for nested media queries

css/properties/scroll-margin-bottom.json, css/properties/scroll-margin-left.json, css/properties/scroll-margin-right.json, css/properties/scroll-margin-top.json, css/properties/scroll-margin.json
This reverts commit 5b1be7539064fbd2b47e793af73e2d2a9ba4721e.
=> Revert "Safari supports scroll-margin with alt. name (#5642)"

GOVERNANCE.md
Thanks for all the work you've contributed to MDN and mdn-browser-compat-data. 
:cry: :cry: :cry:
=> Remove teoli from peer list

javascript/builtins/EvalError.json, javascript/builtins/InternalError.json, javascript/builtins/RangeError.json, javascript/builtins/ReferenceError.json, javascript/builtins/SyntaxError.json, javascript/builtins/TypeError.json, javascript/builtins/URIError.json
Background: https://github.com/mdn/sprints/issues/2571
=> Add Error constructors

api/Element.json
See https://developer.mozilla.org/fr/docs/Web/API/Element/wheel_event
https://www.quirksmode.org/dom/events/tests/scroll.html can be used to test, by changing the registration mode at the top
=> Add internet explorer version and note for wheel event

api/HTMLIFrameElement.json, html/elements/iframe.json, http/headers/feature-policy.json
Reverts mdn/browser-compat-data#5502
=> Revert "Feature Policy enabled by default on Firefox 73"

css/at-rules/media.json
I made a copy-paste error in #5720, this is a fix for it.
=> Fix bug from #5720

http/headers/cross-origin-resource-policy.json
See https://bugzilla.mozilla.org/show_bug.cgi?id=1602363#c6
=> CORP ships in Fx74

css/types/clamp.json, css/types/max.json, css/types/min.json
- [Bugzilla bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1519519)
- [Content sprint issue](https://github.com/mdn/sprints/issues/2927)
=> Add support for min(), max(), and  clamp() in Fx75

html/elements/summary.json
::-webit-details-marker –> ::-webkit-details-marker
=> HTML summary element: fix typo in notes

.github/compat-data-helper/README.md
This PR attempts to document the deployment process for the compat-data-helper.
@Elchi3, if you want to try this, that would probably be a good idea.
=> Update compat-data-helper deployment instructions

browsers/firefox.json
Firefox 74 was released last Tuesday.
=> Firefox 74 has been released

javascript/classes.json
Intent to ship https://groups.google.com/forum/#!topic/mozilla.dev.platform/mumdrb5OUqk
bug https://bugzilla.mozilla.org/show_bug.cgi?id=1535804
=> Firefox 75 supports static class fields

api/NodeList.json
=> IE versions before 8 do not support NodeList.

api/IDBCursor.json
Chromestatus:
https://chromestatus.com/feature/5432744081358848
Related: #4318
=> Add IDBCursor.request
