mdn/browser-compat-data

svg/elements/switch.json
Found by the Open Web Docs BCD collector v10.6.4.
The allowReorder attribute has been dropped everywhere for a long time and the behavior it was setting is now the default for SVG [`<switch>`](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/switch) elements.
=> Remove SVG <switch> allowReorder

svg/elements/view.json
Found by the Open Web Docs BCD collector v10.6.3
Gone long enough everywhere so it can be [considered irrelevant](https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines/index.md#removal-of-irrelevant-features).
- Firefox 61: https://bugzilla.mozilla.org/show_bug.cgi?id=1455763
- Safari end of 2019: https://bugs.webkit.org/show_bug.cgi?id=203217
- Chrome end of 2016: https://bugs.chromium.org/p/chromium/issues/detail?id=633908&q=viewTarget&can=1
=> SVG viewTarget attribute is removed everywhere

api/Bluetooth.json
Found by the Open Web Docs BCD collector v10.6.3.
Not in Chromium, confirmed by https://bugs.chromium.org/p/chromium/issues/detail?id=707640
=> Bluetooth availabilitychanged event isn't supported anywhere

css/properties/hyphens.json
In `hyphens.json`, I corrected the name of the language with language code `sk` from Czechoslovak (which is not even a language) to Slovak.
You can check the [Wikidata entry](https://www.wikidata.org/wiki/Q9058) for the Slovak language.
None.
=> Correct Czechoslovak -> Slovak in hyphens.json

svg/elements/filter.json
Found by the Open Web Docs BCD collector v10.6.4.
The filterRes attribute is gone from browsers for a long time already:
- Safari in 2018: https://bugs.webkit.org/show_bug.cgi?id=129565
- Firefox in 2014: https://bugzilla.mozilla.org/show_bug.cgi?id=979472
- Chrome in 2015: https://bugs.chromium.org/p/chromium/issues/detail?id=353272
(Plus a drive-by edit to set webview_android to mirror for the `<filter>` element itself.)
=> Remove <filter> filterRes attribute

webextensions/api/scripting.json
Update Safari's support for the `InjectionResult` for the `browser.scripting` API. Also, fix a mistake where the documentation states that Safari doesn't support the `world` property for `browser.scripting.RegisteredContentScripts`, when it added support in Safari 16.4.
=> Update scripting.json for updated Safari support

css/selectors/backdrop.json
https://chromiumdash.appspot.com/commit/14eeb1d5b6369a4fefa57973bf6b646469f72e35
The tests that were added at the time show this is the relevant commit: https://chromium-review.googlesource.com/c/chromium/src/+/1066600
=> Mark ::backdrop as supported in fullscreen since Chrome 69

css/types/color.json
Hi!
Fixed the broken mdn_url for the `light-dark` `<color>` function.
The correct url should be : [https://developer.mozilla.org/docs/Web/CSS/color_value/light-dark](https://developer.mozilla.org/docs/Web/CSS/color_value/light-dark)
- Current: [https://developer.mozilla.org/en-US/docs/Web/CSS/color/light-dark](https://developer.mozilla.org/en-US/docs/Web/CSS/color/light-dark) leads to a 404 page.
- Corrected: [https://developer.mozilla.org/docs/Web/CSS/color_value/light-dark](https://developer.mozilla.org/docs/Web/CSS/color_value/light-dark) leads to the correct page.
=> Fix(color.json): correct mdn_url for light-dark color function

api/HTMLAnchorElement.json, api/HTMLAreaElement.json, api/SVGAElement.json, html/elements/a.json, html/elements/area.json, svg/elements/a.json
Found by the Open Web Docs BCD collector v10.6.4.
The `ping` property is [exposed](https://searchfox.org/mozilla-central/source/dom/webidl/HTMLAnchorElement.webidl#24) but it has no effect. See https://bugzil.la/951104 which is about enabling this by default.
=> Update Firefox compat data for the ping attribute

html/elements/area.json
Found by the Open Web Docs BCD collector v10.6.4
See also referrerpolicy on other elements like https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#browser_compatibility which also have 14.
=> Safari supports <area> referrerpolicy attribute in version 14

api/SVGCursorElement.json, svg/elements/cursor.json
Found by the Open Web Docs BCD collector v10.6.4.
The SVG cursor element is gone everywhere. The last removal was in Safari 16.4 which was released March 27, 2023. So not long enough ago to remove the feature altogether yet.
=> Update compat data for SVG <cursor>

api/DeviceOrientationEvent.json
Found by the Open Web Docs BCD Collector v10.6.3.
See https://github.com/WebKit/WebKit/blob/7c7d82b66b438315b7182d3b460c795c18ba81d2/Source/WebCore/dom/DeviceOrientationEvent.idl#L38-L50 where it is conditionally disabled on the iOS family.
=> Safari iOS doesn't support DeviceOrientationEvent.absolute

api/Window.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `devicemotion_event` member of the `Window` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.6.3).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/Window/devicemotion_event
=> Update Safari data for api.Window.devicemotion_event

api/Window.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `deviceorientation_event` member of the `Window` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.6.3).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/Window/deviceorientation_event
=> Update Safari data for api.Window.deviceorientation_event

css/types/image.json
This PR updates and corrects version values for all browsers for the `*-gradient` member of the `image` CSS value type. This adds a `premultiplied_gradients` subfeature to all three gradient types, as all browsers (not just Firefox) had this issue in the past.  In a way, this fixes #14598.
Test Code:
```html
<div id="test"></div>
<style>
body {
background-color: black;
}
#test {
height: 100vh;
background: linear-gradient(to bottom, red, rgba(255, 255, 255, 0));
}
</style>
```
If the gradient started to transition into white, then premultiplication was not performed.  If the gradient faded perfectly to black, premultiplication was performed properly.
=> Update all browsers data for css.types.image.*-gradient

api/Navigator.json, api/Notification.json, api/NotificationEvent.json, api/PushEvent.json, api/PushManager.json, api/PushMessageData.json, api/PushSubscription.json, api/PushSubscriptionChangeEvent.json, api/PushSubscriptionOptions.json, api/ServiceWorkerGlobalScope.json, api/ServiceWorkerRegistration.json
This PR updates the notes for the features of the Badging, Notification and Push APIs in two ways:
- Statements for Safari that say `partial_impl` and supported since macOS 13 are updated to remove `partial_impl` and use the formal name of "macOS Ventura"
- Following up to #19280, adds notes to explicitly state that support is only available in web apps added to the iOS home screen
Fixes #20228.
=> Update Safari notes for Badging/Notification/Push APIs

css/at-rules/scope.json
Adds `@scope` implementation in Safari TP.
- [Activate the CSS @scope feature in stable](https://github.com/WebKit/WebKit/pull/21435)
- [Release Notes for Safari Technology Preview 185](https://www.webkit.org/blog/14885/release-notes-for-safari-technology-preview-185/)
=> Add @scope implementation in Safari

css/properties/white-space-collapse.json
I am updating the safari version to `preview`, because it was added in STP 182. I also tested in STP and according to the web inspector, it is supported.
https://developer.apple.com/documentation/safari-technology-preview-release-notes/stp-release-182
Here is the link to the implementation:
https://github.com/WebKit/WebKit/commit/30f3214ab2d13ea5977cdba2f97ea230a4d5d5d9
I also checked the layout tests in WPT, they pass:
https://wpt.fyi/results/css/css-text/white-space/white-space-collapse-000.html?label=master&label=experimental&aligned https://wpt.fyi/results/css/css-text/white-space/white-space-collapse-001.html?label=master&label=experimental&aligned
=> Update white-space-collapse.json to `preview` in safari

css/selectors/nesting.json
CSS Nesting Selectors are full supported in the 17.2 Safari: <https://developer.apple.com/documentation/safari-release-notes/safari-17_2-release-notes>.
Like this: <https://www.webkit.org/blog/14787/webkit-features-in-safari-17-2/>
=> Update Nesting selector

css/selectors/backdrop.json
This was determined via WebKit source history:
https://github.com/WebKit/WebKit/commit/c96dd4f574c01a761f875ce4222725c44693f2b1 https://github.com/WebKit/WebKit/blob/c96dd4f574c01a761f875ce4222725c44693f2b1/Configurations/Version.xcconfig
The Safari 16.4 release notes lend further support, as they say "Added support for the unprefixed Fullscreen API on macOS and iPadOS": https://developer.apple.com/documentation/safari-release-notes/safari-16_4-release-notes
=> Mark ::backdrop as supported in fullscreen since Safari 16.4

css/properties/overflow-anchor.json
`overflow-anchor` is supported in STP 185. I also tested this in the web inspector of STP: 
Release:
https://developer.apple.com/documentation/safari-technology-preview-release-notes/stp-release-185
Commit:
https://github.com/WebKit/WebKit/commit/b19a8ecd83e6c20215a86dc28725fc62fd9ca976
=> Update overflow-anchor.json to `preview` in safari

javascript/builtins/ArrayBuffer.json
FF122 ships support for [`ArrayBuffer.prototype.transfer()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer/transfer), [`ArrayBuffer.prototype.transferToFixedLength()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer/transferToFixedLength),[`ArrayBuffer.prototype.detached`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer/detached) in https://bugzilla.mozilla.org/show_bug.cgi?id=1865103
This adds a the version and changes the APIs to experimental "false"
Related docs work can be tracked in https://github.com/mdn/content/issues/31101
=> FF122 ArrayBuffer.transfer() et al

api/Navigator.json, api/WakeLock.json, api/WakeLockSentinel.json
FF122 adds support for the [Screen Wake Lock API](https://developer.mozilla.org/en-US/docs/Web/API/Screen_Wake_Lock_API) in https://bugzilla.mozilla.org/show_bug.cgi?id=1589554 in Nightly. This adds the preview to the API features/subfeatures.
Related docs work can be tracked in https://github.com/mdn/content/issues/31112
=> FF122 Screen WakeLock API in Nightly

javascript/builtins/Intl/Segmenter.json
FF122 supports the [Intl/Segmenter](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Segmenter) in nightly in https://bugzilla.mozilla.org/show_bug.cgi?id=1423593.
The APIs all appear to show up correctly in BCD collector too. This just sets the version as preview.
Related docs work can be tracked in https://github.com/mdn/content/issues/31098
=> FF122 Intl.Segmenter supported in Nightly

api/HTMLInputElement.json
`<input type="time">` implemented in Safari 16. I updated the safari version to 16 and deleted the url.
release note:
https://developer.apple.com/documentation/safari-release-notes/safari-16-release-notes
commits:
https://github.com/WebKit/WebKit/commit/87edc399776c6661db62cc09c50e3aca274af941
https://github.com/WebKit/WebKit/commit/dddc5bb328a4b8636946a735281b09101f1d3161
WPT tests pass in safari 17.2.1 in the live browser:
https://wpt.fyi/results/html/semantics/forms/the-input-element/time.html?label=master&label=experimental&aligned&q=time
https://wpt.fyi/results/html/semantics/forms/the-input-element/time-2.html?label=master&label=experimental&aligned&q=time
=> Update HTMLInputElement.json safari adds support for `<input type="time">`

api/HTMLElement.json, html/global_attributes.json
This was fixed in Firefox 110 and BCD has already been partially
updated:
https://bugzilla.mozilla.org/show_bug.cgi?id=1575154
https://github.com/mdn/browser-compat-data/pull/18856
https://github.com/mdn/browser-compat-data/pull/19482
Safari support hasn't been researched again, just made more consistent
with a previous BCD update:
https://github.com/mdn/browser-compat-data/pull/14782
=> Mark autofocus as fully support in Firefox and Safari

css/selectors/grammar-error.json
As of STP 185 supports `::grammar-error`. I updated safari to `preview`.
the release notes:
https://developer.apple.com/documentation/safari-technology-preview-release-notes/stp-release-185
the commits:
https://github.com/WebKit/WebKit/commit/bdc9c3cf0a54ccd3e90bfae34b7e5ffbb22874cd https://github.com/WebKit/WebKit/pull/21340/commits/dea7937dec2bc7d25ea94641cb60bdf586f6526e
=> Update grammar-error.json to `preview` in Safari

css/selectors/spelling-error.json
STP 185 supports `::spelling-error`. I updated safari to `preview`.
release note:
https://developer.apple.com/documentation/safari-technology-preview-release-notes/stp-release-185
commits:
https://github.com/WebKit/WebKit/commit/bdc9c3cf0a54ccd3e90bfae34b7e5ffbb22874cd https://github.com/WebKit/WebKit/pull/21340/commits/dea7937dec2bc7d25ea94641cb60bdf586f6526e
=> Update spelling-error.json to `preview` in Safari

api/AbortSignal.json
STP 184 added support for `AbortSignal.any()`
Release note:
https://developer.apple.com/documentation/safari-technology-preview-release-notes/stp-release-184
Commits:
https://github.com/WebKit/WebKit/pull/13940/files
https://github.com/WebKit/WebKit/commit/fbea645d50ed3428db7cc9a692f1898107d1666c
=> Update AbortSignal.json Safari to `"preview"` for `any`

javascript/builtins/ArrayBuffer.json
STP 184 added support for `ArrayBuffer.prototype.detached`, `ArrayBuffer.prototype.transfer`, and `ArrayBuffer.prototype.transferToFixedLength`
Release note:
https://developer.apple.com/documentation/safari-technology-preview-release-notes/stp-release-184
Commits:
https://github.com/WebKit/WebKit/commit/cbdbb78e64fdc212c8e2ed5d85003568f839783a https://github.com/WebKit/WebKit/commit/fe0aa79252484e5da584cf525ccc930e7698deef https://github.com/WebKit/WebKit/commit/1007b7a34ee9ad34c10f8032d13663567e7bdf4e
=> Update ArrayBuffer.json Safari to `"preview"` for `detached`, `transfer`, and `transferToFixedLength`

api/Element.json
STP 184 supports `Element.checkvisibility()`. I updated Safari to `"preview"`.
Release note:
https://developer.apple.com/documentation/safari-technology-preview-release-notes/stp-release-184
Commits:
https://github.com/WebKit/WebKit/commit/a884b8e751c17ed1dd2e61b0cae011581c6110b8 https://github.com/WebKit/WebKit/pull/20043/files
https://github.com/WebKit/WebKit/pull/19321/files
=> Update Element.json Safari to `"preview"` for `checkVisibility`

api/HTMLVideoElement.json
The `disablePictureInPicture` was not in WebIDL in FF116 so it basically worked, but wasn't detectable in the bcd collector or detectable to users. The "fix" was to add a note. 
In FF122 https://bugzilla.mozilla.org/show_bug.cgi?id=1863583 adds it to IDL. This updates the note to specify the version at which the problem ends. We could even remove the note altogether as it won't matter in several releases. Up to you.
=> FF122 HTMLVideoElement.disablePictureInPicture is now in WebIDL

api/HTMLInputElement.json
when the property added in #8114 , it is not added with a `spec_url`
the property is not in spec https://html.spec.whatwg.org/multipage/input.html or any part of spec yet
- in https://bugs.chromium.org/p/chromium/issues/detail?id=690143, it is considering to remove (because it is non-standard)
- it is suggested in https://lists.w3.org/Archives/Public/public-whatwg-archive/2008Nov/0403.html but was gave up later and never added to spec yet
=> mark `HTMLInputElement.incremental` as non-standard

api/SharedStorageWorkletGlobalScope.json
the `spec_url` of `SharedStorageWorkletGlobalScope.sharedStorage` seems to forget to add
see https://wicg.github.io/shared-storage/#dom-sharedstorageworkletglobalscope-sharedstorage
=> add spec_url for `SharedStorageWorkletGlobalScope.sharedStorage`

html/elements/iframe.json
see https://github.com/mdn/browser-compat-data/pull/6888 for technology detail
in that PR, `HTMLIFrameElement.allowPaymentRequest`'s status has been updated, but the similar `allowpaymentrequest` attribute in `<iframe>` element wasn't updated yet
=> update status of `allowpaymentrequest` attribute in `<iframe>` element

api/Navigator.json, api/WakeLock.json, api/WakeLockSentinel.json, http/headers/Permissions-Policy.json
Follow-up to https://github.com/mdn/browser-compat-data/pull/21710 in which we forgot the Permissions-Policy.
Introducing a group so we will not forget again :)
=> Add screen-wake-lock tag; Firefox preview for Permission Policy

.npmignore, package.json
Reinstate the option to install BCD from Git. This is useful to, for example, run analysis against the data of a BCD PR, before it's merged and released. 
1. Run `npm install git+https://github.com/mdn/browser-compat-data.git` and attempt to `import` or `require` BCD. 😢 
2. Run `npm install git+https://github.com/ddbeck/browser-compat-data.git#installable-from-HEAD` and attempt to `import` or `require` BCD. 😄
~Regress originated at https://github.com/mdn/browser-compat-data/pull/16593.~
=> Reinstate install from Git

api/PaymentManager.json
`PaymentManager.instruments` has been removed from [spec](https://w3c.github.io/payment-handler/) in https://github.com/w3c/payment-handler/pull/409
=> mark `PaymentManager.instruments` as non-standard

css/types/basic-shape.json
Safari 17.2  adds support for `rect()`, I updated Safari to `17.2`and `experimental` to false.
release note:
https://developer.apple.com/documentation/safari-release-notes/safari-17_2-release-notes
commit:
https://github.com/WebKit/WebKit/commit/60c71caf6ae8f78fcf776c5441ebdcd14f8cc5bf
blobs:
https://github.com/WebKit/WebKit/blob/92e26bad7aef126178d279d5fd326ef7bec9852b/Source/WebCore/css/Rect.h#L23
https://github.com/WebKit/WebKit/blob/92e26bad7aef126178d279d5fd326ef7bec9852b/Source/WebCore/css/RectBase.h
passes the WPT subtests in live browser in Safari 17.2.1:
https://wpt.fyi/results/css/css-contain/content-visibility/content-visibility-svg-rect.html?label=master&label=experimental&aligned&q=%2Fcss%2Fcss-contain%2Fcontent-visibility%2Fcontent-visibility-svg-rect.html
=> Update basic-shape.json in Safari to `17.2` and `"experimental"` to `false` in `rect()`

javascript/builtins/Promise.json
STP 181 added support for `Promise.withResolvers()`, I updated Safari to `"preview"`.
release note:
https://developer.apple.com/documentation/safari-technology-preview-release-notes/stp-release-181
commits:
https://github.com/WebKit/WebKit/commit/781be0233d6a2333b4673f44b5fbfa9878bfc8ce https://github.com/WebKit/WebKit/pull/15790/files
https://github.com/WebKit/WebKit/pull/15808/files
passes the WPT test:
https://wpt.fyi/results/fullscreen/api/promises-resolve.html?label=experimental&label=master&aligned
=> Update Promise.json `withResolvers` to `"preview"` in Safari

css/properties/-webkit-mask-repeat-x.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `-webkit-mask-repeat-x` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.6.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/-webkit-mask-repeat-x
=> Update Chromium data for -webkit-mask-repeat-x CSS property

css/properties/-webkit-mask-repeat-y.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `-webkit-mask-repeat-y` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.6.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/-webkit-mask-repeat-y
=> Update Chromium data for -webkit-mask-repeat-y CSS property

api/Window.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `orientationchange_event` member of the `Window` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.6.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/Window/orientationchange_event
Additional Notes: This was previously updated from collector results, but I believe there was an issue with the results used; Safari on iPadOS reports itself as Desktop Safari.
=> Update Safari data for api.Window.orientationchange_event

api/CustomElementRegistry.json
This adds an MDN URL for the built-in element support subfeature of the CustomElementRegistry API.  This will help explain what it means, as there is no explanation on the MDN page for `CustomElementRegistry` itself (only in the `define` method).
=> Add mdn_url for CustomElementRegistry built-in element support

api/MediaRecorder.json
This PR removes the `warning_event` member of the `MediaRecorder` API from BCD. Per the [data guidelines](https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines/index.md#removal-of-irrelevant-features), this feature can be considered irrelevant and may be removed from BCD accordingly. Even if the current data suggests that the feature is supported, lack of support has been confirmed by the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.6.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/MediaRecorder/warning_event
=> Remove api.MediaRecorder.warning_event from BCD

api/MediaStreamTrack.json
This PR removes the `overconstrained_event` member of the `MediaStreamTrack` API from BCD. Per the [data guidelines](https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines/index.md#removal-of-irrelevant-features), this feature can be considered irrelevant and may be removed from BCD accordingly. Even if the current data suggests that the feature is supported, lack of support has been confirmed by the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.6.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/MediaStreamTrack/overconstrained_event
=> Remove api.MediaStreamTrack.overconstrained_event from BCD

api/WorkerNavigator.json
the spec_url of `WorkerNavigator.mediaCapabilities` should link to the one of the `WorkerNavigator`, not the `Navigator`
=> fix spec_url of `WorkerNavigator.mediaCapabilities`

api/HTMLFieldSetElement.json
The _h_ is silent, so HTML starts with a vowel sound.
=> Fix typo in description (HTMLFieldSetElement)

api/RTCDtlsTransport.json
This PR updates and corrects version values for Firefox and Firefox Android for the `error_event` member of the `RTCDtlsTransport` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.6.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/RTCDtlsTransport/error_event
Additional Notes: This was updated in https://github.com/mdn/browser-compat-data/pull/19906, but the only hint about the event data was that it was guesstimated (the collector didn't update event data back then).  The bug linked in that PR doesn't have any mention of the error event either, so it's safe to assume this was incorrect data …
=> Update Firefox data for api.RTCDtlsTransport.error_event

api/Element.json
This PR updates and corrects version values for all browsers for the `focus*_event` member of the `Element` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.6.4).
Additional Notes: The [MDN documentation](https://developer.mozilla.org/en-US/docs/Web/API/Element/focusin_event) doesn't mention an `onfocusin` or `onfocusout`, and in manual testing, this event handler property was defined neither on a generic Element or an HTMLElement.
Tests Used:
https://mdn-bcd-collector.gooborg.com/tests/api/Element/focusin_event
https://mdn-bcd-collector.gooborg.com/tests/api/Element/focusout_event
=> Update all browsers data for api.Element.focus*_event

svg/elements/a.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `rel` member of the `a` SVG element. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.6.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/svg/elements/a/rel
=> Update Safari data for svg.elements.a.rel

api/WorkerGlobalScope.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `languagechange_event` member of the `WorkerGlobalScope` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.6.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/WorkerGlobalScope/languagechange_event
Additional Notes: This data came from the wiki migration as the event handler data, but I can't find any indication of support in Safari.
=> Update Safari data for api.WorkerGlobalScope.languagechange_event

css/types/basic-shape.json
Safari version 17.2 added support for `rect` and `xywh`, updating `experimental` to `false`.
Release note:
https://developer.apple.com/documentation/safari-release-notes/safari-17_2-release-notes
Commits:
https://github.com/WebKit/WebKit/commit/6dd9b4ce08d7fc1933952dfd57de080a21882127 https://github.com/WebKit/WebKit/commit/534a722e7081523b73c20634c2932ab927c499a9
WPT tests that are passing:
https://wpt.fyi/results/css/css-masking/clip-path/clip-path-xywh-001.html?label=master&label=experimental&aligned&q=%2Fcss%2Fcss-masking%2Fclip-path%2Fclip-path-xywh-001.html
https://wpt.fyi/results/css/css-masking/clip-path/clip-path-xywh-002.html?label=master&label=experimental&aligned&q=%2Fcss%2Fcss-masking%2Fclip-path%2Fclip-path-xywh-002.html …
=> Update basic-shape.json update Safari to "17.2"  for `rect` and `xywh`

api/HTMLCanvasElement.json
Update `quality` in Safari to "11".
I am addressing the following issue:
https://github.com/mdn/browser-compat-data/issues/21770
The commit which confirms implementation:
https://github.com/WebKit/WebKit/commit/d79600d2a2e805ab46022cfa1d550bc90067b01a
=> Update HTMLCanvasElement.json Safari added support for `quality` in version 11

api/HTMLVideoElement.json
Quick follow-up for #21753, which brings back a note that wasn't meant to be removed.
=> Update notes for api.HTMLVideoElement.disablePictureInPicture

html/elements/img.json
This PR removes the deprecation annotation from the `onerror` attribute of the HTML `img` tag's browser compatibility data.
* [mdn/sprints#4014](https://github.com/mdn/sprints/issues/4014) (including attempts to query @teoli2003, author of #388)
* [Stackoverflow discussion](https://stackoverflow.com/a/77278205/1204976)
* Changes made to update the `api.HtmlImageElement` reference regarding error-handling, in #4724
* #388
The `onerror` attribute to the `img` element has been marked deprecated since the table data was introduced in 061483a. However, that deprecation was never sourced to any specs or references, and multiple inquiries since have failed to uncover any explanation for it. It appears to have been a simple error.
=> html.img: Remove phantom onerror deprecation

api/Element.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `gesture*_event` member of the `Element` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.6.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/Element/gesture*_event
Additional Notes: In https://github.com/WebKit/WebKit/commit/4b98457dae18e27afae7d48138b9ec1068eb8a0c#diff-5062a30a774512ad7d02525d4670935d55330194d9ba2d9f00bdf31b83e38002R181-R183, an "IOS_GESTURE_EVENTS" was added to the Element interface (and had been present on other interfaces).
=> Update Safari data for api.Element.gesture*_event

api/ServiceWorkerGlobalScope.json
This PR updates and corrects version values for Firefox and Firefox Android for the `sync_event` member of the `ServiceWorkerGlobalScope` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.6.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/ServiceWorkerGlobalScope/sync_event
Additional Notes: The version number came from the original wiki migration, and it was for the event handler.  I can't find any indication of support when skimming the source code.
=> Update Firefox data for api.ServiceWorkerGlobalScope.sync_event

api/SVGAElement.json, api/SVGFilterElement.json, api/SVGMPathElement.json
add & fix spec_url for `href` attribute of SVG elements
the `SVGAElement` `SVGFilterElement` `SVGMPathElement` both include the `SVGURIReference` mixin, which add `href` property to those interfaces
see https://svgwg.org/svg2-draft/types.htmltypes.html#InterfaceSVGURIReference and https://drafts.fxtf.org/filter-effects/#svgfilterelement https://svgwg.org/specs/animations/#InterfaceSVGMPathElement https://svgwg.org/svg2-draft/linking.html#InterfaceSVGAElement
=> Add & fix spec_url for `href` attribute of SVG elements

api/Worker.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `messageerror_event` member of the `Worker` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.6.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/Worker/messageerror_event
Additional Notes: This data came from the wiki migration as the event handler data.  I have not been able to find any indication that it has been supported in Chrome when searching the source code.
=> Update Chromium data for api.Worker.messageerror_event

api/ReadableStream.json
normally `@@asyncIterator` or `@@iterator` will not add a special `description` key (and the link in `description` key because the `mdn_url` is specified)
see also https://github.com/mdn/browser-compat-data/issues/6367
=> Remove description for `ReadableStream[@@asyncIterator]`

api/ServiceWorkerGlobalScope.json
this event is never added to the [spec](https://w3c.github.io/payment-handler/), or any other spec (the [propersol request](https://github.com/w3c/payment-handler/pull/207) never merged to the spec)
see also `AbortPaymentEvent`, which is marked as non-standard when it was added
=> mark `ServiceWorkerGlobalScope: abortpayment event` as non-standard

api/Element.json
`Element.checkVisibility` has an `options` object parameter. In the spec this has two options, `checkOpacity` and `checkVisibilityCSS`, both of which are implemented AFAIK in Chrome (105) and Firefox (106) on first release of the method.
The spec has an unmerged PR [csswg-drafts#9549](https://github.com/w3c/csswg-drafts/pull/9549) to add three more options.
- `opacityProperty` and `visibilityProperty` are aliases for the original names with a new naming convention. The old names are not yet "deprecated" in the spec.
- `contentVisibilityAuto` allows you to check if an element is being skipped for layout because it is not in the view.
Even though the spec change hasn't merged, Chrome has implemented the [change in 121](https://groups.google.com/a/chromium.org/g/blink-dev/c/ruNqbP3wDSY/m/JZUK …
=> Ff122 Element.checkVisibily options

api/FileSystemHandle.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `move` member of the `FileSystemHandle` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.6.5).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/FileSystemHandle/move
=> Update Safari data for api.FileSystemHandle.move

html/elements/tr.json
This PR updates and corrects version values for Firefox and Firefox Android for the `valign` member of the `tr` HTML element. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.6.5).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/html/elements/tr/valign
=> Update Firefox data for html.elements.tr.valign

api/HTMLTemplateElement.json, html/elements/template.json
Declarative Shadow DOM support via the `shadowrootmode` attribute for the `<template>` element will be shipped in Firefox 122 behind the flag, disabled by default for now.
- https://bugzilla.mozilla.org/show_bug.cgi?id=1712140
=> Add shadowrootmode in Firefox preview

html/elements/form.json
The Open Web Docs BCD collector v10.6.5 says that the `accept` attribute is not supported on `<form>` and I can't find evidence that it was supported before. You can have `accept` on `<input>` but not on `<form>`. 
Further there is no `accept` in the `HTMLFormElement` data and it is not in the HTML spec either.
=> Remove accept attribute from <form>

api/WorkletSharedStorage.json
As per https://github.com/mdn/browser-compat-data/issues/21780, [`context`](https://developer.mozilla.org/en-US/docs/Web/API/WorkletSharedStorage/context) is not showing a spec table. I checked with the Google engineering folks, and it turns out they accidentally omitted it from the spec. Until they add it in, I'm setting the `context` `standards_track` field to `false`.
I also noticed that [`entries()`](https://developer.mozilla.org/en-US/docs/Web/API/WorkletSharedStorage/entries) and [`keys()`](https://developer.mozilla.org/en-US/docs/Web/API/WorkletSharedStorage/keys) are not showing a spec table. I've fixed this by adding a `spec_url` to each that just points to the main [`WorkletSharedStorage`](https://wicg.github.io/shared-storage/#worklet-shared-storage) section — they are included …
=> Fix missing spec URLs for WorkletSharedStorage

api/HTMLLinkElement.json
this PR is related to [#31517](https://github.com/mdn/content/pull/31517). Adding a new page for HTMLLinkElement.hreflang.
=> add missing mdn_url for HTMLLinkElement.hreflang

api/Navigator.json, api/WakeLock.json, api/WakeLockSentinel.json
I was building a web app during my end of year holidays and the Wake Lock API doesn't work in standalone PWAs/Home Screen Web Apps in iOS Safari. See https://bugs.webkit.org/show_bug.cgi?id=254545#c32
=> Wake Lock API doesn't work in iOS Safari Home Screen Web Apps

api/Request.json, api/_globals/fetch.json
Marked priority as being supported in fetch and request apis as of Safari 17.2.  Removed experimental flag from the features (automated test complained).
Tested (in Safari 17.2) by going to https://www.google.com and opening the network tab.  In network tab make sure to display priority of the requests being made (right click on headers to choose the priority column).
In the console run and observe the request and the priority at which it was made:
`fetch('https://www.google.com/', { priority: 'low' })`
`fetch('https://www.google.com/', { priority: 'high' })`
`fetch(new Request('https://www.google.com/', {priority: 'low'}))`
`fetch(new Request('https://www.google.com/', {priority: 'high'}))`
https://developer.apple.com/documentation/safari-release-notes/safari-17_2-release-notes
Safari …
=> Safari 17.2 supports priority in fetch and request apis

css/properties/background-position.json
This PR renames the "4_value_syntax" feature to "side-relative_values" to match similar features.
=> Rename css.properties.background-position.[4_value_syntax -> side-relative_values]

api/RTCStatsReport.json
This PR is a part of a project to add missing interfaces and interface features to BCD that are from an active spec (including WICG specs) and is supported in at least one browser. This particular PR adds the missing features of the `type_inbound-rtp` member of the `RTCStatsReport` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.6.5).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/RTCStatsReport/type_inbound-rtp
=> Add missing features for api.RTCStatsReport.type_inbound-rtp

api/RTCStatsReport.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `type_inbound-rtp.mid` member of the `RTCStatsReport` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.6.5).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/RTCStatsReport/type_inbound-rtp/mid
=> Update Safari data for api.RTCStatsReport.type_inbound-rtp.mid

api/HTMLMediaElement.json
the method is a non-standard feature, which is added in https://github.com/mdn/browser-compat-data/pull/1166 and update firefox data in https://github.com/mdn/browser-compat-data/pull/7506, also reference to firefox release note v49 and v50
related implement links https://bugzilla.mozilla.org/show_bug.cgi?id=1336404 (added to firefox) https://bugs.chromium.org/p/chromium/issues/detail?id=1065675 (will not add to chromium)
=> Mark api.HTMLMediaElement.seekToNextFrame as non-standard

css/properties/offset-path.json, css/types/ray.json
**Target release**: Firefox 122
**Release date**: Jan 23, 2024
This PR proposes changes in addition to the ones in https://github.com/mdn/browser-compat-data/pull/21678.
1. Updates to `css/types/ray.json`, which corresponds to the BCD table on the [ray()](https://developer.mozilla.org/en-US/docs/Web/CSS/ray#browser_compatibility) page:
- For all the row entries, updated firefox to `122` and experimental to `false`.
- Additionally for those rows:
- `ray()`: Updated safari to `16`
Sources: https://bugs.webkit.org/show_bug.cgi?id=233344 and in [offset-path.json](https://github.com/mdn/browser-compat-data/blob/main/css/properties/offset-path.json#L226-L228)
- `at <position>`: Updated safari to `17.2`
Sources: https://bugs.webkit.org/show_bug.cgi?id=258113 and …
=> Firefox 122: Update motion-related features

css/types/basic-shape.json
Updated the version added for ff for rect() and xywh()
Tested in Firefox Beta & Nightly
- [[CSS] Ship xywh() and rect() for basic-shape](https://github.com/mdn/content/issues/31103)
=> updated the version added for ff for rect() and xywh()

html/elements/html.json
The feature is part of App Cache and has been removed from all browsers (not quite long enough yet to remove the data altogether).
More info https://web.dev/articles/appcache-removal?hl=en
=> Update data for <html manifest>

svg/elements/use.json
For security reasons, the following is no longer allowed:
```html
<svg>
<use href="data:image/svg+xml;base64,PHN2ZyB4bWxucz0i...#x" />
</svg>
```
In Firefox, this is now behind a pref only, and disabled by default.
- **Fx:**
- intent to unship: https://groups.google.com/a/mozilla.org/g/dev-platform/c/jOd-oh6NEhs/m/2E3pqE4wAQAJ
- **Chrome:**
- blog: https://developer.chrome.com/blog/migrate-way-from-data-urls-in-svg-use
- intent to unship: https://groups.google.com/a/chromium.org/g/blink-dev/c/Q9dLyBhtZTw/m/ceirsUk7AgAJ
- https://chromestatus.com/feature/5128825141198848
__Safari:__
I can't find any evidence that Safari ever supported this.
Web search only shows bug reports of people struggling to get it to work.
I tested in Browserstack with Safari right back to the beginning of time, …
=> relnote(122): SVG use elements cannot use data URIs

api/File.json
This PR removes the `type` member of the `File` API from BCD. This is duplicate data since the `type` property is defined on `Blob` which `File` inherits from.
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/File/type
Additional Notes: Fixes #21855.
=> Remove api.File.type from BCD

css/properties/font-synthesis.json
This PR updates and corrects version values for Firefox and Firefox Android for the `font-synthesis` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.6.5).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/font-synthesis
Additional Test Code Used:
```html
<style>
p {
font-synthesis: weight style;
}
</style>
<p>This font does not support <strong>bold</strong> and <em>italic</em>.</p>
```
=> Update Firefox data for font-synthesis CSS property

.github/ISSUE_TEMPLATE/config.yml, README.md
This PR updates the readme and the issue template config to clarify where users should go for Baseline-related issues.
=> Point to Baseline in readme/issue creation

css/properties/alignment-baseline.json
This PR adds the missing features of the `alignment-baseline` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.7.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/alignment-baseline
=> Add missing features for alignment-baseline CSS property

api/HTMLVideoElement.json
I am going to document `HTMLVideoElement.requestVideoFrameCallback()` and `HTMLVideoElement.cancelVideoFrameCallback()`, but I noticed that the `mdn_url`s for these methods is missing. This PR adds those.
=> add mdn_urls for *VideoFrameCallback methods

svg/elements/feMergeNode.json
This PR updates and corrects version values for Chrome and Safari for the `in` member of the `feMergeNode` SVG element. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.6.5).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/svg/elements/feMergeNode/in
=> Update Chrome/Safari data for svg.elements.feMergeNode.in

webextensions/api/storage.json
Add a note that StorageArea.get(), set(), remove(), and clear() only support local and session storage in Firefox for Android.
Fixes #21734
=> storage.StorageArea methods support in Firefox for Android

api/SVGStyleElement.json
This PR updates and corrects version values for Chrome and Safari for the `disabled` member of the `SVGStyleElement` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.6.5).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/SVGStyleElement/disabled
=> Update Chrome/Safari data for api.SVGStyleElement.disabled

api/CustomStateSet.json, api/ElementInternals.json
Safari TP 185 supports CustomStateSet (flagged)
 
=> Safari TP 185 supports CustomStateSet (flagged)

css/properties/ruby-align.json
`ruby-align` supported by STP.
Commits:
WebKit/WebKit@5aefb40 WebKit/WebKit@9ef3ca6
Screenshot of implementation in STP:
=> Update ruby-align.json STP supports `ruby-align` updating Safari to `preview`

css/properties/outline.json
This PR removes the `invert` member of the `outline` CSS property from BCD. This is just a duplicate of `outline-color: invert`.
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/outline/invert
=> Remove css.properties.outline.invert from BCD

http/headers/Alt-Svc.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `Alt-Svc` HTTP header. The data comes from a commit in the browser's source code, mapped to a version number using available tooling or via the commit timestamp.
Commit: https://github.com/WebKit/WebKit/commit/2162ae8bd6047aced442b0d00edce9b270dec870
Additional Notes: Fixes #21845.
=> Update Safari data for Alt-Svc HTTP header

api/Directory.json
This PR is a part of a project to add missing interfaces and interface features to BCD that are from an active spec (including WICG specs) and is supported in at least one browser. This particular PR adds the missing `Directory` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.7.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/Directory
Additional Notes: https://searchfox.org/mozilla-central/source/dom/webidl/Directory.webidl
=> Add missing Directory API feature

api/RTCStatsReport.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `type_candidate-pair.priority` member of the `RTCStatsReport` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.6.5).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/RTCStatsReport/type_candidate-pair/priority
Additional Notes: Confirmed by https://github.com/WebKit/WebKit/commit/bc18af2122edaa89bbec6b93a6404c01ea626276.
=> Update Safari data for api.RTCStatsReport.type_candidate-pair.priority

api/ManagedMediaSource.json
This PR is a part of a project to add missing interfaces and interface features to BCD that are from an active spec (including WICG specs) and is supported in at least one browser. This particular PR adds the missing `ManagedMediaSource` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.6.5).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/ManagedMediaSource
=> Add missing ManagedMediaSource API feature

api/BufferedChangeEvent.json
This PR is a part of a project to add missing interfaces and interface features to BCD that are from an active spec (including WICG specs) and is supported in at least one browser. This particular PR adds the missing `BufferedChangeEvent` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.6.5).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/BufferedChangeEvent
=> Add missing BufferedChangeEvent API feature

api/ManagedSourceBuffer.json
This PR is a part of a project to add missing interfaces and interface features to BCD that are from an active spec (including WICG specs) and is supported in at least one browser. This particular PR adds the missing `ManagedSourceBuffer` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.6.5).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/ManagedSourceBuffer
=> Add missing ManagedSourceBuffer API feature

svg/elements/image.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `decoding` member of the `image` SVG element. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.6.5).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/svg/elements/image/decoding
=> Update Safari data for svg.elements.image.decoding

api/WebGL2RenderingContext.json, api/WebGLRenderingContext.json
This PR removes the `canvas.OffscreenCanvas` member of the `WebGLRenderingContext` API from BCD. This feature seems redundant, and appears to be a mirror of the `OffscreenCanvas` data.
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/WebGLRenderingContext/canvas/OffscreenCanvas
=> Remove api.WebGLRenderingContext.canvas.OffscreenCanvas from BCD

api/ServiceWorker.json
This PR updates and corrects version values for Safari for the `ecmascript_modules` member of the `ServiceWorker` API. This copies the support info from the Worker and SharedWorker APIs.
Test Code Used:
index.html
```html
<script type="module">
const reg = await navigator.serviceWorker.register('./es-module-sw.js', { type: 'module' }).then(navigator.serviceWorker.ready);
var messageChannel = new MessageChannel();
/**
* Handle the 'message' event from the message channel port.
* @param {MessageEvent} event - The message event.
*/
messageChannel.port1.onmessage = (event) => {
console.log(event.data);
};
reg.active.postMessage('foo', [messageChannel.port2]);
</script>
```
es-module-sw.js
```js
import { cacheName } from "./config.js";
self.addEventListener("install", (event) => {}); …
```
=> Update Safari data for api.ServiceWorker.ecmascript_modules

css/properties/contain.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `inline-size` member of the `contain` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.6.5).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/contain/inline-size
=> Update Safari data for css.properties.contain.inline-size

css/properties/overflow-x.json, css/properties/overflow-y.json, css/properties/overflow.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `overlay` member of the `overflow` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.6.5).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/overflow/overlay
=> Update Safari data for css.properties.overflow.overlay

javascript/builtins/Intl/NumberFormat.json
Change the Firefox version from 93 to 116 for the `Intl.NumberFormat` constructor's `options.signDisplay` parameter `negative` value.
Here is the [changeset](https://hg.mozilla.org/integration/autoland/rev/9f247edc6c08) where the support was added to Firefox.
I had originally filed this [issue](https://github.com/Fyrd/caniuse/issues/6940) to `caniuse`, but they pointed me here.
=> Fix Firefox version of NumberFormat signDisplay negative value

api/MediaStreamTrack.json
Account for [current Firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1739163) breaking support for [the `muted` property of a `MediaStreamTrack`](https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrack/muted).
See the associated [Firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1739163), including a test page, and results and [the original ticket](https://bugzilla.mozilla.org/show_bug.cgi?id=1208378), tracking implementation of the feature.
On Arch Linux (kernel 6.6.6-zen1) with Firefox (120.0.1), I visited a [small demo page](https://detect-mute.glitch.com) I created. I then toggled the muted state of the system's default microphone (by toggling "mute" on the PulseAudio source). The page shows that `mediaStream.getAudioTracks()[0].muted` is always false in …
=> update buggy support for MediaStreamTrack.muted state

api/HTMLVideoElement.json, html/elements/video.json
using data from api.HTMLVideoElement.disablePictureInPicture and assuming its data is correct
spec-url https://w3c.github.io/picture-in-picture/#dom-htmlvideoelement-disablepictureinpicture
chrome & safari data update #9438 
chrome android data update #17047 
firefox data update #21753 & #21812 
webview data update #18544
=> Add data for html.elements.video.disablepictureinpicture

html/elements/audio.json, html/elements/video.json
using data from api.HTMLMediaElement.controlsList and assume its data is correct
see the proposal link https://wicg.github.io/controls-list/ and https://wicg.github.io/controls-list/explainer.html, also the working on pull request https://github.com/whatwg/html/pull/6715
also reference to the chrome status https://chromestatus.com/feature/5737006365671424
=> Add data for html.elements.{audio,video}.controlslist

html/elements/a.json
`href_sms` reflects the `sms` value of `href` attribute, put it under `href` attribute is better
=> Move html.elements.a.href_sms to html.elements.a.href.href_sms

html/elements/button.json
as the data added in #19949 , this attribute is not supported in Firefox 121 as I test; also no info that `<button>` html element has ever supported this attribute searched in Firefox release or bugs
content update https://github.com/mdn/content/pull/31605
autocomplete attribute spec https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#attr-fe-autocomplete
form spec https://html.spec.whatwg.org/multipage/forms.html#the-form-element
input spec https://html.spec.whatwg.org/multipage/input.html#the-input-element
select spec https://html.spec.whatwg.org/multipage/form-elements.html#the-select-element
textarea spec https://html.spec.whatwg.org/multipage/form-elements.html#the-textarea-element
this also relates with https://github.com/mdn/browser-compat-data/issues/21790
--- …
=> Remove html.elements.button.autocomplete

html/elements/iframe.json
using the data from `api.HTMLIFrameElement.csp` and assume its data is correct
see https://github.com/mdn/browser-compat-data/pull/2017 and https://github.com/mdn/browser-compat-data/pull/1470, which add data for api.HTMLIFrameElement.csp
see also the spec https://w3c.github.io/webappsec-cspee/#csp-attribute
Fixes #21756
=> Add data for html.elements.iframe.csp

html/elements/img.json
~normally the attribute of html element do not add `mdn_url`~
also, the `spec_url` is not good, which should specific with a hash like attr-img-*
fix incorrect links added in https://github.com/mdn/browser-compat-data/pull/21323
=> html.elements.img.decoding update mdn_url & fix spec_url

html/elements/img.json
the `onerror` event handler attribute of `<img>` relates to the `error` event of `HTMLImageElement`, and it seems that we don't keep event handler attribute in BCD of html element (and current one is the only I find in the html part of the BCD), see also https://github.com/mdn/browser-compat-data/pull/21783
=> remove BCD of `<img>` element `onerror` event handler property

html/elements/video.json
use data from api.HTMLVideoElement.playsInline and assert the data is correct
closes #7611
=> Add data for html.elements.video.playsinline

api/Element.json, api/ShadowRoot.json
Added new attachShadow `clonable` option and ShadowRoot `clonable` attribute per updated DOM spec:
- Available since Firefox Nightly 122
- Not available in Safari (it’s complicated, see below)
- Not available in Chrome Canary
⚠️ It is available in Safari but with a different spelling:
- Since Safari 16.4 as an option
- Since Safari TP 186 as an attribute
There’s a [mistype](https://bugs.webkit.org/show_bug.cgi?id=267634) in Safari’s implementation: it should be `clonable` [per spec](https://dom.spec.whatwg.org/#dom-shadowroot-clonable), not `cloneable`, in both cases. I made it `false` for now, and I will get back once it’s fixed.
WPT agrees: [clonable.window.html](https://wpt.fyi/results/shadow-dom/declarative/clonable.window.html?label=master&label=experimental&aligned&q=clonable)
How I …
=> Firefox122: Add clonable attribute to ShadowRoot

webextensions/manifest/permissions.json
The introduction of the scripting API also included the scripting permission. This change adds that scripting permission to the permissions manifest key.
Fixes #20859
=> Adding scripting to permissions manifest key

css/properties/content.json
I am updating `alt-text` to preview, STP 187 adds support for `alt_text`.
STP 187 release notes: https://webkit.org/blog/14931/release-notes-for-safari-technology-preview-187/
Commit: https://github.com/WebKit/WebKit/commit/1b3e497426196dd3289ad58811bdb12cbaa29379
=> Update content.json- Safari `alt_text` to `"preview"`

webextensions/manifest/optional_permissions.json
Summary
The introduction of the scripting API also included the scripting optional permission. This change adds that scripting permission to the optional_permissions manifest key.
Related issues
Fixes https://github.com/mdn/browser-compat-data/issues/20859
=> Adding scripting to optional_permissions manifest key

api/CSSScopeRule.json
This PR updates and corrects version values for Microsoft Edge for the `CSSScopeRule` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.7.1).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/CSSScopeRule
=> Update Edge data for CSSScopeRule API

api/CSS.json
This PR updates and corrects version values for Microsoft Edge for the `CSS` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.7.1).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/CSS
=> Update Edge data for CSS API

api/HTMLInputElement.json, browsers/safari.json
Add Safari 17.4 support for date showPicker function
https://developer.apple.com/documentation/safari-release-notes/safari-17_4-release-notes#:~:text=support%20for%20the-,showPicker,-()%20method%20for 
Release notes say type="date" but this also applies to datetime-local too.
=> Add Safari 17.4 support for date input showPicker function

api/Document.json
This PR updates and corrects version values for Microsoft Edge for the `hasStorageAccess` member of the `Document` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.7.1).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/Document/hasStorageAccess
=> Update Edge data for api.Document.hasStorageAccess

api/Document.json
This PR adds the missing `hasPrivateToken` member of the `Document` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.7.1).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/Document/hasPrivateToken
=> Add missing api.Document.hasPrivateToken feature

api/NavigateEvent.json
This PR updates and corrects version values for Microsoft Edge for the `hasUAVisualTransition` member of the `NavigateEvent` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.7.1).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/NavigateEvent/hasUAVisualTransition
=> Update Edge data for api.NavigateEvent.hasUAVisualTransition

api/Window.json
This PR updates and corrects version values for Microsoft Edge for the `vrdisplaypresentchange_event` member of the `Window` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.7.1).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/Window/vrdisplaypresentchange_event
=> Update Edge data for api.Window.vrdisplaypresentchange_event

api/Element.json
This PR updates and corrects version values for Microsoft Edge for the `focus_event` member of the `Element` API. This copies the notes from Chrome.
=> Update Edge data for api.Element.focus_event

api/Worker.json
This PR updates and corrects version values for Microsoft Edge for the `messageerror_event` member of the `Worker` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.7.1).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/Worker/messageerror_event
=> Update Edge data for api.Worker.messageerror_event

css/properties/transform-box.json
This PR updates and corrects version values for Microsoft Edge for the `transform-box` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.7.1).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/transform-box
=> Update Edge data for transform-box CSS property

webextensions/manifest/optional_permissions.json
This change aligns the compatibility information with the [optional permission details provided by Chrome](https://developer.chrome.com/docs/extensions/reference/api/permissions#step_2_declare_optional_permissions_in_the_manifest).
It only covers common permissions e.g., those shared between Firefox, Chrome, and Safari.
Fixes  #20858
=> Chrome optional permissions update

webextensions/api/commands.json
Add a link to [Bug 1843866](https://bugzilla.mozilla.org/show_bug.cgi?id=1843866) Add tab parameter to commands.onCommand
Fixes #20913
=> commands.onCommand tab implementation link

api/NavigateEvent.json, api/Navigation.json
Added `impl_url` to:
- https://github.com/mdn/browser-compat-data/blob/main/api/Navigation.json
- https://github.com/mdn/browser-compat-data/blob/main/api/NavigateEvent.json
n/a
Fixes #21952
=> docs: added `impl_url` URLs in Navigation.json & NavigateEvent.json

api/Element.json, api/HTMLTemplateElement.json, api/ShadowRoot.json, css/properties/-moz-user-focus.json, html/elements/template.json, http/status.json
The [Open Web Docs BCD collector](https://github.com/openwebdocs/mdn-bcd-collector) v10.7.0 found new features shipping in Firefox 123 beta which was released yesterday. Currently, the collector covers about 82% of BCD, so the following list might not be exhaustive. Also, if a feature is in Firefox Nightly only, it is not considered here.
With this PR, BCD considers the following features as shipping in Firefox 123:
- `api.Element.attachShadow.init_clonable_parameter` ([Intent to ship: Declarative ShadowDOM](https://groups.google.com/a/mozilla.org/g/dev-platform/c/P-ZBI_7fEaE))
- `api.HTMLTemplateElement.shadowRootMode` ([Intent to ship: Declarative ShadowDOM](https://groups.google.com/a/mozilla.org/g/dev-platform/c/P-ZBI_7fEaE))
- `api.ShadowRoot.clonable` ([Intent to ship: Declarative …
=> Updates for Firefox 123 beta

api/IdentityCredential.json, api/Navigator.json, api/StorageBucket.json, api/StorageBucketManager.json, api/WebGL2RenderingContext.json, api/WebGLRenderingContext.json, api/WorkerNavigator.json, javascript/builtins/Iterator.json, javascript/builtins/Set.json
The [Open Web Docs BCD collector](https://github.com/openwebdocs/mdn-bcd-collector) v10.7.1 found new features shipping in Chrome 122 beta which was released yesterday. Currently, the collector covers about 82% of BCD, so the following list might not be exhaustive. Also, if a feature is in Chrome Canary/behind origin trials/enrollment, it is not considered here.
With this PR, BCD considers the following 44 features as shipping in Chrome 122:
- api.IdentityCredential.disconnect_static
- api.Navigator.storageBuckets
- api.StorageBucket
- api.StorageBucket.caches
- api.StorageBucket.estimate
- api.StorageBucket.expires
- api.StorageBucket.getDirectory
- api.StorageBucket.indexedDB
- api.StorageBucket.name
- api.StorageBucket.persist
- api.StorageBucket.persisted
- …
=> Updates for Chrome 122 beta

scripts/update-browser-releases/safari.ts
Fixes https://github.com/mdn/browser-compat-data/actions/runs/7691213976/job/20956176989
- A closing bracket was missing 
- The regex doesn't work if "Version" is omitted in the string. This is the case for 17.4 beta.
=> Fix Safari releases script

css/properties/content.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `image-set` member of the `content` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.7.1).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/content/image-set
=> Update Safari data for css.properties.content.image-set

svg/elements/image.json
This PR updates and corrects version values for Chrome and Safari for the `crossorigin` member of the `image` SVG element. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.7.1).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/svg/elements/image/crossorigin
=> Update Chrome/Safari data for svg.elements.image.crossorigin

api/DragEvent.json
This PR updates and corrects version values for Chrome and Safari for the `DragEvent` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.7.1).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/DragEvent
Additional Notes: These had been marked unsupported on mobile since the wiki era, so I don't trust the existing data much.
=> Update Chrome/Safari data for DragEvent API

api/Performance.json
This PR updates and corrects version values for Opera and Opera Android for the `Performance` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.7.1).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/Performance
=> Update Opera data for Performance API

api/MediaDevices.json
This PR updates and corrects version values for Opera and Opera Android for the `devicechange_event` member of the `MediaDevices` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.7.1).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/MediaDevices/devicechange_event
=> Update Opera data for api.MediaDevices.devicechange_event

api/MediaStream.json
This PR updates and corrects version values for Opera and Opera Android for the `MediaStream` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.7.1).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/MediaStream
=> Update Opera data for MediaStream API

api/RTCPeerConnection.json
This PR updates and corrects version values for Opera and Opera Android for the `RTCPeerConnection` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.7.1).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/RTCPeerConnection
=> Update Opera data for RTCPeerConnection API

api/SpeechGrammar.json
This PR updates and corrects version values for Opera and Opera Android for the `SpeechGrammar` API. This sets Opera to mirror from Chrome, as a discrepancy was caught by the collector.
=> Update Opera data for SpeechGrammar API

api/Worker.json
This PR updates and corrects version values for Opera and Opera Android for the `messageerror_event` member of the `Worker` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.7.1).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/Worker/messageerror_event
=> Update Opera data for api.Worker.messageerror_event

api/WorkerNavigator.json
This PR updates and corrects version values for Opera and Opera Android for the `serial` member of the `WorkerNavigator` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.7.1).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/WorkerNavigator/serial
=> Update Opera data for api.WorkerNavigator.serial

api/XRCamera.json, api/XRSession.json, api/XRView.json, api/XRWebGLBinding.json
This PR updates and corrects version values for Opera and Opera Android for the `XR*` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.7.1).
Tests Used:
https://mdn-bcd-collector.gooborg.com/tests/api/XRCamera
https://mdn-bcd-collector.gooborg.com/tests/api/XRSession
https://mdn-bcd-collector.gooborg.com/tests/api/XRView
https://mdn-bcd-collector.gooborg.com/tests/api/XRWebGLBinding
=> Update Opera data for XR* API

api/HTMLInputElement.json
Remove iOS Safari's support for the `showPicker` function in time inputs.
Manually tested using https://demo.lukewarlow.dev/showPicker/ - only the file input is supported.
=> Correct iOS Safari time input showPicker data

api/Animation.json
The section was moved in https://github.com/mdn/content/pull/26716, so the MDN URL became broken.  This fixes the link to point to the right location.
=> Correct MDN URL for api.Animation.remove_filling_animation

api/CustomStateSet.json
The custom state set links were all going to the draft spec https://wicg.github.io/custom-state-pseudo-class/#dom-customstateset-add
But this appears to all have migrated into the HTML living spec here: https://html.spec.whatwg.org/multipage/custom-elements.html#custom-state-pseudo-class
Certainly the live spec is what everyone is now targeting.
Related docs work in https://github.com/mdn/content/issues/31971
=> CustomStateSet - spec links are wrong

api/GamepadButton.json
This PR updates and corrects version values for WebView Android for the `touched` member of the `GamepadButton` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.7.1).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/GamepadButton/touched
=> Update WebView data for api.GamepadButton.touched

api/SubtleCrypto.json
Currently [the spec states](https://w3c.github.io/webcrypto/#scope-algorithms):
>Because the underlying cryptographic implementations will vary between conforming user agents... this specification does not dictate a mandatory set of algorithms that MUST be implemented. Instead, it defines a common set of bindings that can be used in an algorithm-independent manner...
There are a list of recommendations for [implementers](https://www.w3.org/TR/WebCryptoAPI/#algorithm-recommendations-implementers):
>In order to promote interoperability for developers, this specification includes a list of suggested algorithms. These are considered to be the most widely used algorithms in practice at the time of writing, and therefore provide a good starting point for initial implementations of this …
=> feat(api): Add Ed25519 sign/verify SubtleCrypto algo

webextensions/api/permissions.json
- adds a note about the inability to request permissions from devtools
- updates the note about requesting permissions from a sidebar document which was fixed in Firefox 101
Fixes #20637
=> webextensions.api.permissions.request from Devtools

api/IDBObjectStore.json
The Firefox-only `options.locale` argument to [`IDBObjectStore.createIndex()`](https://developer.mozilla.org/en-US/docs/Web/API/IDBObjectStore/createIndex) is now deprecated by https://bugzilla.mozilla.org/show_bug.cgi?id=1872675 in FF123.
This adds the option as a subfeature and marks it deprecated. This is in preparation for expected removal at some point. Either way it is more correct than having this info in the docs.
Related docs work can be tracked in https://github.com/mdn/content/issues/31915
=> FF123 IDBObjectStore.createIndex() locale option deprecated

api/URL.json
FF122 started using a different URL parser in https://bugzilla.mozilla.org/show_bug.cgi?id=1603699. Previously if you passed in an URL with an unknown scheme/protocol in [URL()](https://developer.mozilla.org/en-US/docs/Web/API/URL/URL), the host, hostname and port would be empty strings. Now these values are populated (as discussed in https://github.com/mdn/content/issues/31100#issuecomment-1907520020).
This adds a note about the change. Didn't seem worthwhile to add a completely new version for this (originally I thought this had no developer impact).
Related docs work can be tracked in https://github.com/mdn/content/issues/31100
=> FF122 URL() now parses host/hostname/port for unknown schemes

api/CredentialsContainer.json
Firefox 114+ supports residentKey in WebAuthN L2. But this is desktop only, so mobile isn't  yet  .See https://bugzilla.mozilla.org/show_bug.cgi?id=1831137 for Firefox/Android.
See https://bugzilla.mozilla.org/show_bug.cgi?id=1813282
=> Update residentKey support data

api/HTMLObjectElement.json, html/elements/object.json
these features are listed in the *Obsolete features* section
see spec https://html.spec.whatwg.org/multipage/obsolete.html#attr-object-usemap and https://html.spec.whatwg.org/multipage/obsolete.html#dom-object-usemap
=> Deprecated `usemap` attribute of `<object>` element and `useMap` property of `HTMLObjectElement` interface

css/selectors/state.json
FF121 added support for a `:state()` pseudo selector in FF121 in https://bugzilla.mozilla.org/show_bug.cgi?id=1861466
This adds a feature for `:state()`.
Note, FF adds support for `:state()` after `::part()` in FF123 in https://bugzilla.mozilla.org/show_bug.cgi?id=1866351. However as this is all behind a preference currently not much point recording this change. Note that if we want to test this stuff for compatibility on other browsers the [docs have a live example](https://pr32000.content.dev.mdn.mozit.cloud/en-US/docs/Web/API/CustomStateSet#question_box_exposing_states_in_shadow_parts).
Related docs work can be tracked in https://github.com/mdn/content/issues/31971
=> FF121 CSS :state() pseudo class

html/elements/col.json, html/elements/colgroup.json
the `bgcolor` attribute of `<col>` element and `<colgroup>` element and not in standard (not included in https://html.spec.whatwg.org/multipage/obsolete.html), and tey take not effect in browsers
use the test based on the sample of https://codepen.io/queengooborg/pen/QWrYaXg, which indicates the property takes no effect both in chrome and firefox
```html
<body bgcolor="#C0A0F0">
<table bgcolor="green">
<colgroup bgcolor="yellow">
<col>test</col>
<col bgcolor="red">test</col>
</colgroup>
<thead bgcolor="red" align="char" char=".">
<tr>
<th>hello</th>
<th bgcolor="green">farewell</th>
</tr>
</thead>
<tbody bgcolor="yellow">
<tr bgcolor="cyan">
<td>0.456</td>
<td>12439</td>
</tr>    <tr>
<td bgcolor="purple">456.0</td>
<td>869.5</td>
</tr>    <tr>
<td>1</td>
<td>5</td>
</tr>    <tr> …
```
=> Remove `bgcolor` attribute of `<col>` element and `<colgroup>` element

html/elements/meter.json
the `<meter>` element dose not has a `form` attribute, see the spec https://html.spec.whatwg.org/multipage/form-elements.html#the-meter-element
---
and per the spec of the `form` attribute:
> A [form-associated element](https://html.spec.whatwg.org/multipage/forms.html#form-associated-element) is, by default, associated with its nearest ancestor [form](https://html.spec.whatwg.org/multipage/forms.html#the-form-element) element (as described below), but, if it is [listed](https://html.spec.whatwg.org/multipage/forms.html#category-listed), may have a form attribute specified to override this.
also:
> A number of the elements are form-associated elements, which means they can have a [form owner](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#form-owner). …
=> Remove html.elements.meter.form

javascript/builtins/DataView.json
This PR removes the `buffer.sharedarraybuffer_support` member of the `DataView` JavaScript builtin from BCD. This is basically a duplicate of javascript.builtins.DataView.DataView.sharedarraybuffer_support.
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/javascript/builtins/DataView/buffer/sharedarraybuffer_support
=> Remove javascript.builtins.DataView.buffer.sharedarraybuffer_support from BCD

api/AbortSignal.json, api/CSSScopeRule.json, api/DOMMatrixReadOnly.json, api/Document.json, api/Element.json, api/PublicKeyCredential.json, api/SVGFESpecularLightingElement.json, api/SVGRenderingIntent.json, api/ShadowRoot.json, css/at-rules/scope.json, css/properties/content.json, css/properties/text-wrap-mode.json, css/properties/text-wrap.json, css/properties/transition-behavior.json, css/properties/white-space-collapse.json, css/selectors/grammar-error.json, css/selectors/spelling-error.json, javascript/builtins/ArrayBuffer.json, javascript/builtins/Map.json, javascript/builtins/Object.json, javascript/builtins/Promise.json, svg/elements/feSpecularLighting.json, webassembly/extended-constant-expressions.json
The [Open Web Docs BCD collector](https://github.com/openwebdocs/mdn-bcd-collector) v10.7.1 found new features shipping in Safari 17.4 beta (19618.1.11.11.3) which was released last week. Currently, the collector covers about 82% of BCD, so the following list might not be exhaustive. Also, if a feature is in Safari TP and/or behind flags, it is not considered here.
With this PR, BCD considers the following 35 features as shipping in Safari 17.4:
- api.AbortSignal.any_static
- api.CSSScopeRule
- api.CSSScopeRule.end
- api.CSSScopeRule.start
- api.DOMMatrixReadOnly.scaleNonUniform
- api.Document.parseHTMLUnsafe_static
- api.Element.setHTMLUnsafe
- api.HTMLInputElement.showPicker.date_input (submitted in a previous PR)
- api.HTMLInputElement.showPicker.datetime_local_input (submitted in a …
=> Updates for Safari 17.4 beta

package-lock.json, package.json, test/linter/test-spec-urls.ts
A new major of web-specs was released. Breaking change is that the presence of a `nightly` property is no longer guaranteed. This happens for specs that do not have a public URL, such as ISO specs. The test that checks spec URLs needed to be adjusted accordingly.
Also, note the new version includes the Threading proposal for the WASM JS API, which could thus be dropped from the list of exceptions.
=> Bump web-specs from v2.41.0 to v3.0.0 and adjust test accordingly

api/WebGL2RenderingContext.json, api/WebGLRenderingContext.json
This PR renames all of the `SharedArrayBuffer_as_param` subfeatures of the WebGL rendering contexts to conform to our conventions.
=> Rename WebGL "SharedArrayBuffer_as_param" subfeatures

api/Window.json
This PR removes the `open.outerwidth_outerheight` member of the `Window` API from BCD. Per the [data guidelines](https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines/index.md#removal-of-irrelevant-features), this feature can be considered irrelevant and may be removed from BCD accordingly. Even if the current data suggests that the feature is supported, lack of support has been confirmed by the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.7.2).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/Window/open/outerwidth_outerheight
=> Remove api.Window.open.outerwidth_outerheight from BCD

api/WebGL2RenderingContext.json, api/WebGLRenderingContext.json
This PR removes the `blendFuncSeparate.SharedArrayBuffer_as_param` member of the `WebGLRenderingContext` APIs from BCD. This method doesn't accept an array buffer to begin with.
=> Remove api.WebGL[2]RenderingContext.blendFuncSeparate.SharedArrayBuffer_as_param from BCD

css/properties/paint-order.json
Following recent updates in https://issues.chromium.org/issues/41372165 support for applying the CSS paint-order property to HTML text has been implemented in Blink in version 123 (current nightly).
I've updated the information link to the new issue tracker, which has more up to date and complete information, using the crbug.com redirector per discussion on #22165
=> Chrome 123 will have full support for CSS paint-order

html/elements/script.json
Chrome 121 added support for "document rules" to the Speculation Rules API. This is differentiated between the `urls` key and `where` key.
Tested locally. Working on documenting this on the developer.chrome.com as we speak which is when I noticed it needed adding here.
Test case: https://speculative-rules.glitch.me/common-fruits.html
Screenshot from DevTools->Application->Speculative loads->Rules (open DevTools before loading above page, or reload after opening DevTools):
https://developer.chrome.com/blog/new-in-chrome-121#speculation-rules-api
=> Speculation Rules add `urls` and `where` keys

http/headers/Permissions-Policy.json
FF123 supports Feature policy [`publickey-credentials-create`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Permissions-Policy/publickey-credentials-create) in https://bugzilla.mozilla.org/show_bug.cgi?id=1870863
As per usual for FF, this can't be set on the header, but only via `allow` on the frame. That is recorded as a note.
Related docs work can be track in https://github.com/mdn/content/issues/31890
=> FF123 FeaturePolicy: publickey-credentials-create supported

css/at-rules/import.json
_👋 Hi, Chrome DevRel here_
`@import … supports()` shipped in Chrome 122.
Links:
- CrBug: https://issues.chromium.org/40244647
- ChromeStatus: https://chromestatus.com/feature/5899007704694784
Note that ChromeStatus mentions it shipping in 121 but that’s not the case. The flag only got flipped in commit `6ca8ac7e347b73c62609643164a444719f9d26f7`, which is only included in M122. See https://chromiumdash.appspot.com/commit/6ca8ac7e347b73c62609643164a444719f9d26f7 for details.
=> Update `@import … supports()` support

scripts/update-browser-releases/chrome.ts
This PR fixes the script to use new Chrome release notes URL.
It doesn't update old values, we will do it in a follow-up, if all is good here.
I tested it locally.
=> Update-browser-release: New Chrome release notes

api/Window.json
The linked bug https://webkit.org/b/223860 was fixed in WebKit 614.1.20:
https://github.com/WebKit/WebKit/commit/57f8b6aa692023a6ee9e78c9d6fe73e9c571e75b
https://github.com/WebKit/WebKit/blob/57f8b6aa692023a6ee9e78c9d6fe73e9c571e75b/Source/WebCore/Configurations/Version.xcconfig
That maps to Safari 16 using WebKit 614.1.25.
The presence of the two properties on window has also been confirmed
manually in Safari 17.3 on macOS and iOS 17.2.
=> Update Safari support for ongamepadconnected + ongamepaddisconnected

api/WindowClient.json
Support in iOS 17.2 confirmed manually with this test: https://mdn-bcd-collector.gooborg.com/tests/api/WindowClient/ancestorOrigins
Support was not guarded by any kind of flag when landed in WebKit: https://github.com/WebKit/WebKit/commit/5b0f2dd5f9d48d507a63f148bdc715d876d1b3a3
=> Mirror iOS support for client.ancestorOrigins

api/SharedWorker.json, api/SharedWorkerGlobalScope.json
Confirmed in Chrome Android 120 with this test:
https://mdn-bcd-collector.gooborg.com/tests/api/SharedWorkerGlobalScope
Update the bug link to the redirected bug number.
=> Mark SharedWorkerGlobalScope as not supported on Android

css/at-rules/font-face.json
COLRv1 support is shipped in FireFox since version 107. 
Source: https://bugzilla.mozilla.org/show_bug.cgi?id=1791558
See also: See also https://caniuse.com/colr-v1
=> [font-face] COLRv1 support in FF went stable in 107

scripts/update-browser-releases/chrome.ts
Fixes the failure in https://github.com/mdn/browser-compat-data/pull/22230
=> Chrome releases script: Convert version number to string

css/properties/font-palette.json
This entry effectively represents the ability to animate font-palette.
The Chrome version is from this chromestatus entry:
https://chromestatus.com/feature/5177171439517696
BCD currently represents functions both under css.types and under
specific properties that accept those functions are values.
Since palette-mix() can so far only be used for font-palette, put it
there.
The spec URL is not ideal:
https://github.com/w3c/csswg-drafts/issues/9969
=> Add palette-mix() function as subfeature of font-palette

css/types/exp.json, css/types/hypot.json, css/types/log.json, css/types/pow.json, css/types/sqrt.json
`pow()`, `sqrt()`, `hypot()`, `log()`, `exp()` are shipped in Chromium 120.
https://developer.mozilla.org/en-US/docs/Web/CSS/pow
https://developer.mozilla.org/en-US/docs/Web/CSS/sqrt
https://developer.mozilla.org/en-US/docs/Web/CSS/hypot
https://developer.mozilla.org/en-US/docs/Web/CSS/log
https://developer.mozilla.org/en-US/docs/Web/CSS/exp
https://wpt.fyi/results/css/css-values/hypot-pow-sqrt-computed.html?label=master&label=experimental&aligned&q=hypot
https://wpt.fyi/results/css/css-values/hypot-pow-sqrt-invalid.html?label=master&label=experimental&aligned&q=hypot
https://wpt.fyi/results/css/css-values/hypot-pow-sqrt-serialize.html?label=master&label=experimental&aligned&q=hypot
https://wpt.fyi/results/css/css-values/exp-log-compute.html?label=master&label=experimental&aligned&q=log …
=> Update CSS exponential functions support in Chrome 120

css/properties/background-clip.json
This cannot be mirrored because of the pre-Chromium history.
=> Mark unprefixed background-clip:text supported in Edge

api/Document.json, api/Element.json, api/VisualViewport.json
This was shipped in Chrome together with the general support for the
event, but the event handler property was missed.
Not supported in Firefox or Safari, bugs were linked.
=> Add scrollend event to VisualViewport

api/PerformanceResourceTiming.json, api/PerformanceServerTiming.json, http/headers/Server-Timing.json
Output of `npm run traverse -- -t web-features:server-timing`:
- api.PerformanceResourceTiming.serverTiming
- api.PerformanceServerTiming
- api.PerformanceServerTiming.description
- api.PerformanceServerTiming.duration
- api.PerformanceServerTiming.name
- api.PerformanceServerTiming.toJSON
- http.headers.Server-Timing
=> Add a server-timing tag; Safari 16.4 supports Server-Timing header

api/NetworkInformation.json
mark `NetworkInformation.typechange` event as non-standard, since it is not in the spec https://wicg.github.io/netinfo/
also remove the incorrect spec_url
also remove the mdn_url since the documentation does not existed
=> Mark `NetworkInformation.typechange` event as non-standard

css/properties/transition.json
This PR fixes the identifier for the `transition-behavior` value of the `transition` CSS property to conform to our typical conventions.
=> Change identifier for transition-behavior value of transition CSS property

webextensions/api/browserAction.json
Adds details of Chrome support for webextensions.action.openpopup in 118
Removed prior details as per test:
✖ webextensions.api.browserAction.openPopup - Error → Irrelevant flag data detected for chrome. Remove statement with #extension-apis flag
◆ Tip: Run npm run fix to fix this problem automatically
Fixes #16442
=> Chrome support for webextensions.action.openpopup

browsers/opera.json
Hello everyone! 👋
Updating Opera to version 107, according to this [release note](https://blogs.opera.com/desktop/2024/02/opera-107/).
=> Updates opera browser to version 107

javascript/builtins/ArrayBuffer.json, javascript/builtins/SharedArrayBuffer.json
FF124 adds support for growable [`SharedArrayBuffer`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer)behind pref `javascript.options.experimental.sharedarraybuffer_growable`, and resizable [`ArrayBuffer`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer) behind pref 
`javascript.options.experimental.arraybuffer_resizable` in https://bugzilla.mozilla.org/show_bug.cgi?id=1842773
This PR updates the data appropriately.
Note I had to restart FF to get the BCD collector tests to work - such as https://mdn-bcd-collector.gooborg.com/tests/javascript/builtins/ArrayBuffer
Related docs work can be tracked in https://github.com/mdn/content/issues/32337
=> FF124 growable SharedArrayBuffer and resizeable ArrayBuffer behind prefs

api/Navigator.json, api/Permissions.json, api/WakeLock.json, api/WakeLockSentinel.json, http/headers/Permissions-Policy.json
FF124 supports the [Screen Wake Lock API](https://developer.mozilla.org/en-US/docs/Web/API/Screen_Wake_Lock_API) by default in https://bugzilla.mozilla.org/show_bug.cgi?id=1874849
This updates from preview to 124 for all things tagged with `web-features:screen-wake-lock`
Related docs work can be tracked in https://github.com/mdn/content/issues/32338
=> FF124 Screen Wakelock API shipped

api/AbortSignal.json
FF124 supports [AbortSignal.any()](https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal/any_static) in https://bugzilla.mozilla.org/show_bug.cgi?id=1830781 . This updates the record
Related docs work can be tracked in https://github.com/mdn/content/issues/32342
=> FF124 AbortSignal.any() static method supported

browsers/nodejs.json, javascript/builtins/WeakMap.json
Node 20.1.0 and later supports WeakMap with non-registered symbols as keys. 
[issue #49135](https://github.com/nodejs/node/issues/49135)
=> Update WeakMap.json NodeJS symbol_as_keys

browsers/opera_android.json
Adds missing release dates for Opera Android 75 to 78.
Sources (assuming release date = announcement date):
- https://forums.opera.com/topic/62482/opera-for-android-75
- https://forums.opera.com/topic/63567/opera-for-android-76
- https://forums.opera.com/topic/65830/opera-for-android-77
- https://forums.opera.com/topic/67255/opera-for-android-78
Fixes https://github.com/mdn/browser-compat-data/issues/22274.
=> fix(browsers): add release dates for Opera Android 75-78

webextensions/api/action.json, webextensions/api/browserAction.json
This fixes an error made in #22148, which updated `browserAction` not `action` compatibility data. Fixes #16442
=> Chrome support for webextensions.action.openpopup correction

browsers/edge.json
This date has a special significance for Baseline: https://github.com/web-platform-dx/web-features/issues/623
July 29 is claimed as the release date by Wikipedia: https://en.wikipedia.org/wiki/Microsoft_Edge
=> Update Edge 12 release date

css/properties/writing-mode.json
Safari 17.4 has complete support for forms in vertical writing modes.
Release notes: https://developer.apple.com/documentation/safari-release-notes/safari-17_4-release-notes
Demo: https://codepen.io/jensimmons/pen/gOEVZbw?editors=1100
Tests: https://wpt.fyi/results/css/css-writing-modes/forms?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=label%3Ainterop-2022-forms%20or%20label%3Ainterop-2023-forms
Safari passes 40/40 tests, 100%.
=> Safari 17.4 has complete support for forms in vertical writing modes

css/properties/direction.json
This was originally updated in https://github.com/mdn/browser-compat-data/pull/22179, but testing showed that Firefox only seems to support changing direction of vertical range sliders via `direction`, as per https://github.com/mdn/content/pull/32142#issuecomment-1961833182.
This PR provides an update.
=> Update Firefox support for vertical from control direction

browsers/edge.json
Not sure why the script fails https://github.com/mdn/browser-compat-data/actions/runs/8059665676
Updating the release notes manually will repair it.
=> Update Edge release notes

http/headers/Content-Encoding.json
Adds `zstd` Content-Encoding due to ship in Chrome 123
This also sets Brotli as a Standard since it's well supported in all major browsers so not sure why it was still marked as experimental.
https://wpt.fyi/results/fetch/content-encoding/zstd?label=experimental&label=master&aligned
https://chromestatus.com/feature/6186023867908096
Content PR here: https://github.com/mdn/content/pull/32465
=> Add zstd content-encoding and mark Brotli as standard

css/types/color.json
From recent testing during reviews of the related content, it is evident that Chrome 122+ supports relative `rgb()` colors correctly as per spec. This PR updates the data to suit.
See https://pr32004.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/color_value/rgb#using_relative_colors_with_rgb for a test case
=> Update Chrome data now it supports relative rgb() colors properly

javascript/builtins/Intl/DateTimeFormat.json
This PR updates and corrects the version value for Node for the `DateTimeFormat.DateTimeFormat.options_parameter.options_timeZoneName_parameter.extended_values` member of the Intl JavaScript builtin.
This properly fixes https://github.com/mdn/browser-compat-data/issues/18405, which was originally marked closed in https://github.com/mdn/browser-compat-data/pull/21470.
Supporting information is in the original issue https://github.com/mdn/browser-compat-data/issues/18405.
https://github.com/mdn/browser-compat-data/pull/21470
=> Update Node data for javascript.builtins.Intl.DateTimeFormat.DateTimeFormat.options_parameter.options_timeZoneName_parameter.extended_values

browsers/opera.json
Adds missing release dates for Opera 97 and 98.
Sources:
- https://blogs.opera.com/desktop/2023/03/opera-ai-tools/
- https://blogs.opera.com/desktop/2023/04/opera-98-stable/
Similar to https://github.com/mdn/browser-compat-data/pull/22275.
=> fix(browsers): add release dates/notes for Opera 97/98

webextensions/api/alarms.json, webextensions/api/clipboard.json, webextensions/api/commands.json, webextensions/api/contextualIdentities.json, webextensions/api/cookies.json, webextensions/api/dns.json, webextensions/api/dom.json, webextensions/api/events.json, webextensions/api/proxy.json, webextensions/api/runtime.json, webextensions/api/scripting.json, webextensions/api/tabs.json, webextensions/manifest/action.json, webextensions/manifest/background.json, webextensions/manifest/browser_action.json, webextensions/manifest/commands.json, webextensions/manifest/content_scripts.json, webextensions/manifest/content_security_policy.json, webextensions/manifest/permissions.json
Fix incorrect BCD support info, and added impl_url to some entries that have a bug tracking their implementation.
alarms: drop confusing compat info about past timers. The version_added/version_removed ranges are hard to interpret. The affected versions are ancient and the use of past timers is very unusual. Hence, the simplest way to resolve the ambiguity is to drop the note. Ref: https://bugzilla.mozilla.org/show_bug.cgi?id=1478694
clipboard API disabled in Firefox for Android:
https://searchfox.org/mozilla-central/rev/0e7394a77cdbe1df5e04a1d4171d6da67b57fa17/toolkit/components/extensions/parent/ext-clipboard.js#25-31
contextualIdentities not functional in Firefox for Android: https://bugzilla.mozilla.org/show_bug.cgi?id=1638878
cookies: partitionKey supported in Chrome 119+: …
=> Fix incorrect webextension compat info

api/RTCStatsReport.json
Partial fix for #22293
Ran a bisect using Browserstack on chrome using https://wpt.live/webrtc-stats/supported-stats.https.html to show that inbound-rtp.nackCount is supported in version 80.
Tried to do same in FF but while web test works locally does not work on browserstack. But testing on FF123 on my computer shows that it does work. So in this case I have just removed "version_removed" for FF. It might not be accurate, but it is more likely to be accurate than the current data. Also did search on the topic in bugzilla and only found a version added PR, not one for removal.
Safari doesnt allow the test to run on browserstack either. However it does work on  i15 pro max, so definitively does work. Can we at least mark this as >=17 on Safari or "true"?
=> Chrome/FF RTCStatsReport inbound-rtp.nackCount support

api/CSSKeyframesRule.json, api/Navigation.json, api/NavigationActivation.json, api/PageRevealEvent.json, api/PerformanceLongAnimationFrameTiming.json, api/PerformanceScriptTiming.json, css/properties/field-sizing.json, css/properties/text-spacing-trim.json
The [Open Web Docs BCD collector](https://github.com/openwebdocs/mdn-bcd-collector) v10.8.0 found new features shipping in Chrome 123 beta which was released yesterday. Currently, the collector covers about 88% of BCD, so the following list might not be exhaustive. Also, if a feature is in Chrome Canary/behind origin trials/enrollment, it is not considered here.
With this PR, BCD considers the following features as shipping in Chrome 123:
- ~~api.CSSKeyframesRule.length~~
- api.Navigation.activation
- api.NavigationActivation
- api.NavigationActivation.entry
- api.NavigationActivation.from
- api.NavigationActivation.navigationType
- api.PageRevealEvent
- api.PerformanceLongAnimationFrameTiming
- api.PerformanceLongAnimationFrameTiming.blockingDuration
- …
=> Updates for Chrome 123 beta

css/at-rules/media.json
Chrome 123 adds support for the [`@media` `display-mode`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/display-mode) `picture-in-picture` value. This PR adds compat data for it.
- ChromeStatus: https://chromestatus.com/feature/5198101675769856
- Spec: https://drafts.csswg.org/mediaqueries-5/#display-mode-picture-in-picture
- Demo: https://document-picture-in-picture-api.glitch.me/display-mode.html
=> Add data for display-mode picture-in-picture value

api/ContentVisibilityAutoStateChangeEvent.json, api/Element.json, css/properties/text-wrap-mode.json, css/properties/text-wrap-style.json, css/properties/text-wrap.json
The [Open Web Docs BCD collector](https://github.com/openwebdocs/mdn-bcd-collector) v10.8.0 found new features shipping in Firefox 124 beta which was released yesterday. Currently, the collector covers about 88% of BCD, so the following list might not be exhaustive. Also, if a feature is in Firefox Nightly only, it is not considered here.
With this PR, BCD considers the following features as shipping in Firefox 124:
- api.AbortSignal.any_static
- api.ContentVisibilityAutoStateChangeEvent
- api.ContentVisibilityAutoStateChangeEvent.ContentVisibilityAutoStateChangeEvent
- api.ContentVisibilityAutoStateChangeEvent.skipped
- api.Element.contentvisibilityautostatechange_event
- api.Navigator.wakeLock
- api.Permissions.permission_screen-wake-lock
- api.WakeLock
- api.WakeLock.request
- …
=> Updates for Firefox 124 beta

css/selectors/backdrop.json
_(👋 Hi, Chrome DevRel here)_
When `::backdrop` was moved from the fullscreen spec to css-position-4, it was made tree-abiding, inheriting from its originating element.
CSSWG Resolution: https://github.com/w3c/csswg-drafts/issues/7845#issuecomment-1789844429
This PR adds this information.
This feature is available in all major engines. _(I’m not sure on Safari’s specifics so I’ve marked it as preview)_
=> Add ::backdrop inheritance change info

api/HTMLButtonElement.json, api/HTMLElement.json, api/InvokeEvent.json, html/global_attributes.json
This PR drafts up the documentation for "Invokers" ([OpenUI explainer](https://open-ui.org/components/invokers.explainer/)). This is a new experimental API for enabling buttons to control interactive elements.
- [Chrome Platform Status feature](https://chromestatus.com/feature/5142517058371584)
- [WebKit PR (merged)](https://github.com/WebKit/WebKit/pull/18794)
- [Chromium PR (merged)](https://chromium-review.googlesource.com/c/chromium/src/+/4926471?usp=search)
- [Mozilla PR (merged)](https://phabricator.services.mozilla.com/D189851)
https://github.com/mdn/content/pull/30829
=> add data for Invokers (invoketarget, invokeaction, InvokeEvent)

css/selectors/disabled.json
This PR updates and corrects version values for Microsoft Edge for the `disabled` CSS selector. This fixes #22324, which contains the supporting evidence for this change.
=> Update Edge data for disabled CSS selector

css/properties/hyphens.json
This PR removes the `language_portuguese_brazilian` member of the `hyphens` CSS property from BCD. The only browser with support marked is Firefox, but the note says that it just uses the regular Portuguese dictionary, so it's basically not supported.
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/hyphens/language_portuguese_brazilian
Additional Notes: Fixes #22281.
=> Remove css.properties.hyphens.language_portuguese_brazilian from BCD

api/Element.json
This PR updates and corrects version values for Opera and Opera Android for the `beforematch_event` member of the `Element` API. This fixes #22253, which contains the supporting evidence for this change.
=> Update Opera data for api.Element.beforematch_event

api/CustomStateSet.json, api/Element.json, api/ElementInternals.json, api/ShadowRoot.json, css/selectors/state.json
The [Open Web Docs BCD collector](https://github.com/openwebdocs/mdn-bcd-collector) v10.8 found new features shipping in Safari 17.4 beta (19618.1.15) which was released yesterday. Currently, the collector covers about 88% of BCD, so the following list might not be exhaustive. Also, if a feature is in Safari TP and/or behind flags, it is not considered here.
I ran the collector previously for Safari 17.4 beta (19618.1.11.11.3). Here's the PR: https://github.com/mdn/browser-compat-data/pull/22101. This PR is about 19618.1.15 and new features from the previous beta release were found:
- api.CustomStateSet
- api.CustomStateSet.add
- api.CustomStateSet.clear
- api.CustomStateSet.delete
- api.CustomStateSet.entries
- api.CustomStateSet.forEach
- api.CustomStateSet.has
- api.CustomStateSet.keys …
=> Update for Safari 17.4 beta (19618.1.15)

api/FileSystemFileEntry.json
This PR updates and corrects version values for Opera and Opera Android for the `FileSystemFileEntry` API. This fixes #22237, which contains the supporting evidence for this change.
=> Update Opera data for FileSystemFileEntry API

css/properties/border-bottom-color.json, css/properties/border-color.json, css/properties/border-left-color.json, css/properties/border-right-color.json, css/properties/border-top-color.json
This PR updates and corrects version values for Firefox and Firefox Android for the `border-color` CSS property. This fixes #22202, which contains the supporting evidence for this change.
=> Update Firefox data for border-color CSS property

test/linter/test-browsers-data.test.ts, test/linter/test-browsers-data.ts
Ensure every retired/current browser release has a release date.
Ran `npm run unittest`.
Fixes https://github.com/mdn/browser-compat-data/issues/22278.
Avoids the issues that https://github.com/mdn/browser-compat-data/pull/22275 and https://github.com/mdn/browser-compat-data/pull/22341 fixed.
=> Ensure retired/current browser releases have release date

css/properties/z-index.json
This PR adds the missing `auto` member of the `z-index` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/z-index/auto
=> Add missing css.properties.z-index.auto feature

css/properties/word-spacing.json
This PR adds the missing `normal` member of the `word-spacing` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/word-spacing/normal
=> Add missing css.properties.word-spacing.normal feature

css/properties/background-repeat.json
This PR adds the missing features of the `background-repeat` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/background-repeat
=> Add missing features for background-repeat CSS property

css/properties/background-image.json
This PR adds the missing `none` member of the `background-image` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/background-image/none
=> Add missing css.properties.background-image.none feature

css/properties/background-clip.json
This PR adds the missing features of the `background-clip` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/background-clip
=> Add missing features for background-clip CSS property

css/properties/background-attachment.json
This PR adds the missing `scroll` member of the `background-attachment` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.8.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/background-attachment/scroll
=> Add missing css.properties.background-attachment.scroll feature

css/properties/animation-play-state.json
This PR adds the missing features of the `animation-play-state` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.8.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/animation-play-state
=> Add missing features for animation-play-state CSS property

css/properties/animation-name.json
This PR adds the missing `none` member of the `animation-name` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.8.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/animation-name/none
=> Add missing css.properties.animation-name.none feature

css/properties/animation-iteration-count.json
This PR adds the missing `infinite` member of the `animation-iteration-count` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.8.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/animation-iteration-count/infinite
=> Add missing css.properties.animation-iteration-count.infinite feature

css/properties/animation-fill-mode.json
This PR adds the missing features of the `animation-fill-mode` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.8.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/animation-fill-mode
=> Add missing features for animation-fill-mode CSS property

css/properties/animation-direction.json
This PR adds the missing features of the `animation-direction` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.8.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/animation-direction
=> Add missing features for animation-direction CSS property

http/headers/Content-Security-Policy.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `Content-Security-Policy` HTTP header. The data comes from a commit in the browser's source code, mapped to a version number using available tooling or via the commit timestamp.
Commit: https://github.com/WebKit/WebKit/commit/e6ad7c23647cc760606c1885492ba4e77ed7d986
Additional Notes: Fixes #22181.  Note: `script-src-elem` was set to 16.1 in #18911, but looking at the release notes, 16.1 fixed the CSP in workers, not that it introduced it.
=> Update Safari data for Content-Security-Policy HTTP header

css/properties/position.json
This PR adds the missing features of the `position` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/position
=> Add missing features for position CSS property

css/properties/width.json
This PR adds the missing `auto` member of the `width` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/width/auto
=> Add missing css.properties.width.auto feature

css/properties/white-space.json
This PR adds the missing `normal` member of the `white-space` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/white-space/normal
=> Add missing css.properties.white-space.normal feature

css/properties/visibility.json
This PR adds the missing `visibility` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/visibility
=> Add missing visibility CSS property feature

css/properties/vertical-align.json
This PR adds the missing features of the `vertical-align` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/vertical-align
=> Add missing features for vertical-align CSS property

css/properties/unicode-bidi.json
This PR adds the missing features of the `unicode-bidi` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/unicode-bidi
=> Add missing features for unicode-bidi CSS property

css/properties/transform-origin.json
This PR adds the missing features of the `transform-origin` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/transform-origin
=> Add missing features for transform-origin CSS property

css/properties/top.json
This PR adds the missing `auto` member of the `top` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/top/auto
=> Add missing css.properties.top.auto feature

css/properties/transition-property.json
This PR adds the missing `transition-property` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/transition-property
=> Add missing transition-property CSS property feature

css/properties/text-transform.json
This PR adds the missing features of the `text-transform` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/text-transform
=> Add missing features for text-transform CSS property

css/properties/text-overflow.json
This PR adds the missing features of the `text-overflow` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/text-overflow
=> Add missing features for text-overflow CSS property

css/properties/text-align.json
This PR adds the missing `justify` member of the `text-align` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/text-align/justify
=> Add missing css.properties.text-align.justify feature

css/properties/scroll-snap-type.json
This PR adds the missing features of the `scroll-snap-type` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/scroll-snap-type
=> Add missing features for scroll-snap-type CSS property

css/properties/right.json
This PR adds the missing `auto` member of the `right` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/right/auto
=> Add missing css.properties.right.auto feature

css/properties/text-justify.json
This PR adds the missing features of the `text-justify` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/text-justify
=> Add missing features for text-justify CSS property

css/properties/text-align-last.json
This PR adds the missing `auto` member of the `text-align-last` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/text-align-last/auto
=> Add missing css.properties.text-align-last.auto feature

css/properties/page-break-inside.json
This PR adds the missing features of the `page-break-inside` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/page-break-inside
=> Add missing features for page-break-inside CSS property

css/properties/quotes.json
This PR adds the missing `none` member of the `quotes` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/quotes/none
=> Add missing css.properties.quotes.none feature

css/properties/shape-outside.json
This PR adds the missing `none` member of the `shape-outside` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/shape-outside/none
=> Add missing css.properties.shape-outside.none feature

css/properties/perspective.json
This PR adds the missing `none` member of the `perspective` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/perspective/none
=> Add missing css.properties.perspective.none feature

css/properties/page-break-before.json
This PR adds the missing features of the `page-break-before` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/page-break-before
=> Add missing features for page-break-before CSS property

css/properties/overflow.json
This PR adds the missing features of the `overflow` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/overflow
=> Add missing features for overflow CSS property

css/properties/overflow-y.json
This PR adds the missing features of the `overflow-y` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/overflow-y
=> Add missing features for overflow-y CSS property

css/properties/page-break-after.json
This PR adds the missing features of the `page-break-after` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/page-break-after
=> Add missing features for page-break-after CSS property

css/properties/overflow-x.json
This PR adds the missing features of the `overflow-x` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/overflow-x
=> Add missing features for overflow-x CSS property

css/properties/overflow-anchor.json
This PR adds the missing features of the `overflow-anchor` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/overflow-anchor
=> Add missing features for overflow-anchor CSS property

css/properties/object-fit.json
This PR adds the missing features of the `object-fit` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/object-fit
=> Add missing features for object-fit CSS property

css/properties/max-height.json
This PR adds the missing `none` member of the `max-height` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/max-height/none
=> Add missing css.properties.max-height.none feature

css/properties/mask-type.json
This PR adds the missing features of the `mask-type` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/mask-type
=> Add missing features for mask-type CSS property

css/properties/overflow-wrap.json
This PR adds the missing `normal` member of the `overflow-wrap` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/overflow-wrap/normal
=> Add missing css.properties.overflow-wrap.normal feature

css/properties/max-width.json
This PR adds the missing `none` member of the `max-width` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/max-width/none
=> Add missing css.properties.max-width.none feature

css/properties/list-style-position.json
This PR adds the missing `list-style-position` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/list-style-position
=> Add missing list-style-position CSS property feature

css/properties/letter-spacing.json
This PR adds the missing `normal` member of the `letter-spacing` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/letter-spacing/normal
=> Add missing css.properties.letter-spacing.normal feature

css/properties/left.json
This PR adds the missing `auto` member of the `left` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/left/auto
=> Add missing css.properties.left.auto feature

css/properties/image-rendering.json
This PR adds the missing features of the `auto` member of the `image-rendering` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/image-rendering/auto
=> Add missing features for css.properties.image-rendering.auto

css/properties/image-orientation.json
This PR adds the missing features of the `image-orientation` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/image-orientation
=> Add missing features for image-orientation CSS property

css/properties/height.json
This PR adds the missing `auto` member of the `height` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/height/auto
=> Add missing css.properties.height.auto feature

css/properties/grid-template.json
This PR adds the missing `none` member of the `grid-template` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/grid-template/none
=> Add missing css.properties.grid-template.none feature

css/properties/grid-template-rows.json
This PR adds the missing features of the `grid-template-rows` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/grid-template-rows
=> Add missing features for grid-template-rows CSS property

css/properties/grid-template-columns.json
This PR adds the missing features of the `grid-template-columns` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/grid-template-columns
=> Add missing features for grid-template-columns CSS property

css/properties/grid-template-areas.json
This PR adds the missing `none` member of the `grid-template-areas` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/grid-template-areas/none
=> Add missing css.properties.grid-template-areas.none feature

css/properties/grid-auto-flow.json
This PR adds the missing features of the `grid-auto-flow` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/grid-auto-flow
=> Add missing features for grid-auto-flow CSS property

css/properties/font-weight.json
This PR adds the missing features of the `font-weight` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/font-weight
=> Add missing features for font-weight CSS property

css/properties/font-variant-numeric.json
This PR adds the missing features of the `font-variant-numeric` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/font-variant-numeric
=> Add missing features for font-variant-numeric CSS property

css/properties/font-variant-ligatures.json
This PR adds the missing features of the `font-variant-ligatures` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/font-variant-ligatures
=> Add missing features for font-variant-ligatures CSS property

css/properties/font-variant-caps.json
This PR adds the missing features of the `font-variant-caps` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/font-variant-caps
=> Add missing features for font-variant-caps CSS property

css/properties/font-optical-sizing.json
This PR adds the missing features of the `font-optical-sizing` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/font-optical-sizing
=> Add missing features for font-optical-sizing CSS property

css/properties/font-feature-settings.json
This PR adds the missing `normal` member of the `font-feature-settings` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/font-feature-settings/normal
=> Add missing css.properties.font-feature-settings.normal feature

css/properties/float.json
This PR adds the missing features of the `float` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/float
=> Add missing features for float CSS property

css/properties/flex-wrap.json
This PR adds the missing features of the `flex-wrap` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/flex-wrap
=> Add missing features for flex-wrap CSS property

css/properties/flex-direction.json
This PR adds the missing features of the `flex-direction` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/flex-direction
=> Add missing features for flex-direction CSS property

css/properties/text-decoration-thickness.json
This PR adds the missing features of the `text-decoration-thickness` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/text-decoration-thickness
=> Add missing features for text-decoration-thickness CSS property

css/properties/text-decoration-skip.json
This PR adds the missing features of the `text-decoration-skip` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/text-decoration-skip
=> Add missing features for text-decoration-skip CSS property

css/properties/text-decoration-skip-ink.json
This PR adds the missing features of the `text-decoration-skip-ink` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/text-decoration-skip-ink
=> Add missing features for text-decoration-skip-ink CSS property

css/properties/text-decoration-line.json
This PR adds the missing features of the `text-decoration-line` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/text-decoration-line
=> Add missing features for text-decoration-line CSS property

css/properties/stroke-linejoin.json
This PR adds the missing features of the `stroke-linejoin` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/stroke-linejoin
=> Add missing features for stroke-linejoin CSS property

css/properties/stroke-linecap.json
This PR adds the missing features of the `stroke-linecap` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/stroke-linecap
=> Add missing features for stroke-linecap CSS property

css/properties/text-emphasis-style.json
This PR adds the missing features of the `text-emphasis-style` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/text-emphasis-style
=> Add missing features for text-emphasis-style CSS property

css/properties/stroke-dasharray.json
This PR adds the missing `none` member of the `stroke-dasharray` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/stroke-dasharray/none
=> Add missing css.properties.stroke-dasharray.none feature

css/properties/speak-as.json
This PR adds the missing features of the `speak-as` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/speak-as
=> Add missing features for speak-as CSS property

css/properties/scrollbar-width.json
This PR adds the missing features of the `scrollbar-width` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/scrollbar-width
=> Add missing features for scrollbar-width CSS property

css/properties/scroll-padding.json
This PR adds the missing `auto` member of the `scroll-padding` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/scroll-padding/auto
=> Add missing css.properties.scroll-padding.auto feature

css/properties/scroll-padding-inline.json
This PR adds the missing `auto` member of the `scroll-padding-inline` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/scroll-padding-inline/auto
=> Add missing css.properties.scroll-padding-inline.auto feature

css/properties/scroll-padding-inline-start.json
This PR adds the missing `auto` member of the `scroll-padding-inline-start` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/scroll-padding-inline-start/auto
=> Add missing css.properties.scroll-padding-inline-start.auto feature

css/properties/scroll-padding-inline-end.json
This PR adds the missing `auto` member of the `scroll-padding-inline-end` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/scroll-padding-inline-end/auto
=> Add missing css.properties.scroll-padding-inline-end.auto feature

css/properties/scroll-padding-block-end.json
This PR adds the missing `auto` member of the `scroll-padding-block-end` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/scroll-padding-block-end/auto
=> Add missing css.properties.scroll-padding-block-end.auto feature

css/properties/ruby-align.json
This PR adds the missing features of the `ruby-align` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/ruby-align
=> Add missing features for ruby-align CSS property

css/properties/rotate.json
This PR adds the missing `none` member of the `rotate` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/rotate/none
=> Add missing css.properties.rotate.none feature

css/properties/print-color-adjust.json
This PR adds the missing features of the `print-color-adjust` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/print-color-adjust
=> Add missing features for print-color-adjust CSS property

css/properties/overscroll-behavior.json
This PR adds the missing features of the `overscroll-behavior` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/overscroll-behavior
=> Add missing features for overscroll-behavior CSS property

css/properties/overscroll-behavior-y.json
This PR adds the missing features of the `overscroll-behavior-y` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/overscroll-behavior-y
=> Add missing features for overscroll-behavior-y CSS property

css/properties/overscroll-behavior-inline.json
This PR adds the missing features of the `overscroll-behavior-inline` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/overscroll-behavior-inline
=> Add missing features for overscroll-behavior-inline CSS property

css/properties/overscroll-behavior-block.json
This PR adds the missing features of the `overscroll-behavior-block` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/overscroll-behavior-block
=> Add missing features for overscroll-behavior-block CSS property

css/properties/offset-position.json
This PR adds the missing `auto` member of the `offset-position` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/offset-position/auto
=> Add missing css.properties.offset-position.auto feature

css/properties/overflow-inline.json
This PR adds the missing `overlay` member of the `overflow-inline` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/overflow-inline/overlay
=> Add missing css.properties.overflow-inline.overlay feature

css/properties/overflow-block.json
This PR adds the missing `overlay` member of the `overflow-block` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/overflow-block/overlay
=> Add missing css.properties.overflow-block.overlay feature

css/properties/offset-rotate.json
This PR adds the missing features of the `offset-rotate` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/offset-rotate
=> Add missing features for offset-rotate CSS property

css/properties/object-view-box.json
This PR adds the missing `none` member of the `object-view-box` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/object-view-box/none
=> Add missing css.properties.object-view-box.none feature

css/properties/mask-composite.json
This PR adds the missing features of the `mask-composite` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/mask-composite
=> Add missing features for mask-composite CSS property

css/properties/inset.json
This PR adds the missing `auto` member of the `inset` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/inset/auto
=> Add missing css.properties.inset.auto feature

css/properties/inset-block-end.json
This PR adds the missing `auto` member of the `inset-block-end` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/inset-block-end/auto
=> Add missing css.properties.inset-block-end.auto feature

css/properties/clip-rule.json
This PR adds the missing features of the `clip-rule` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/clip-rule
=> Add missing features for clip-rule CSS property

css/properties/bottom.json
This PR adds the missing `auto` member of the `bottom` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/bottom/auto
=> Add missing css.properties.bottom.auto feature

css/properties/border-image-width.json
This PR adds the missing `auto` member of the `border-image-width` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/border-image-width/auto
Additional Notes: This value was not supported when the property was first introduced.
=> Add missing css.properties.border-image-width.auto feature

css/properties/border-image-repeat.json
This PR adds the missing features of the `border-image-repeat` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/border-image-repeat
=> Add missing features for border-image-repeat CSS property

css/properties/list-style-image.json
This PR adds the missing `none` member of the `list-style-image` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/list-style-image/none
=> Add missing css.properties.list-style-image.none feature

css/properties/list-style-type.json
This PR adds the missing `none` member of the `list-style-type` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/list-style-type/none
=> Add missing css.properties.list-style-type.none feature

css/properties/line-height.json
This PR adds the missing `normal` member of the `line-height` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/line-height/normal
=> Add missing css.properties.line-height.normal feature

css/properties/line-break.json
This PR adds the missing features of the `line-break` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/line-break
=> Add missing features for line-break CSS property

css/properties/font-variant-east-asian.json
This PR adds the missing features of the `font-variant-east-asian` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/font-variant-east-asian
=> Add missing features for font-variant-east-asian CSS property

css/properties/font-style.json
This PR adds the missing features of the `font-style` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/font-style
=> Add missing features for font-style CSS property

css/properties/flex.json
This PR adds the missing `none` member of the `flex` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/flex/none
=> Add missing css.properties.flex.none feature

css/properties/direction.json
This PR adds the missing features of the `direction` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/direction
=> Add missing features for direction CSS property

css/properties/cursor.json
This PR adds the missing `grabbing` member of the `cursor` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/cursor/grabbing
=> Add missing css.properties.cursor.grabbing feature

css/properties/counter-reset.json
This PR adds the missing features of the `counter-reset` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/counter-reset
=> Add missing features for counter-reset CSS property

css/properties/text-size-adjust.json
This PR adds the missing features of the `text-size-adjust` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/text-size-adjust
=> Add missing features for text-size-adjust CSS property

css/properties/perspective-origin.json
This PR adds the missing features of the `perspective-origin` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/perspective-origin
=> Add missing features for perspective-origin CSS property

css/properties/fill-rule.json
This PR adds the missing features of the `fill-rule` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/fill-rule
=> Add missing features for fill-rule CSS property

css/properties/dominant-baseline.json
This PR adds the missing features of the `dominant-baseline` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/dominant-baseline
=> Add missing features for dominant-baseline CSS property

css/properties/counter-increment.json
This PR adds the missing features of the `counter-increment` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/counter-increment
=> Add missing features for counter-increment CSS property

css/properties/content.json
This PR adds the missing features of the `content` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/content
=> Add missing features for content CSS property

css/properties/view-timeline-inset.json
This PR adds the missing `auto` member of the `view-timeline-inset` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/view-timeline-inset/auto
=> Add missing css.properties.view-timeline-inset.auto feature

css/properties/view-timeline-axis.json
This PR adds the missing features of the `view-timeline-axis` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/view-timeline-axis
=> Add missing features for view-timeline-axis CSS property

css/properties/timeline-scope.json
This PR adds the missing features of the `timeline-scope` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/timeline-scope
=> Add missing features for timeline-scope CSS property

css/properties/text-underline-offset.json
This PR adds the missing `auto` member of the `text-underline-offset` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/text-underline-offset/auto
=> Add missing css.properties.text-underline-offset.auto feature

css/properties/scrollbar-color.json
This PR adds the missing `auto` member of the `scrollbar-color` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/scrollbar-color/auto
=> Add missing css.properties.scrollbar-color.auto feature

css/properties/scroll-timeline-axis.json
This PR adds the missing features of the `scroll-timeline-axis` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/scroll-timeline-axis
=> Add missing features for scroll-timeline-axis CSS property

css/properties/scroll-snap-stop.json
This PR adds the missing features of the `scroll-snap-stop` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/scroll-snap-stop
=> Add missing features for scroll-snap-stop CSS property

css/properties/scroll-snap-align.json
This PR adds the missing `scroll-snap-align` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/scroll-snap-align
=> Add missing scroll-snap-align CSS property feature

css/properties/scroll-padding-block.json
This PR adds the missing `scroll-padding-block` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/scroll-padding-block
=> Add missing scroll-padding-block CSS property feature

css/properties/scroll-padding-block-start.json
This PR adds the missing `auto` member of the `scroll-padding-block-start` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/scroll-padding-block-start/auto
=> Add missing css.properties.scroll-padding-block-start.auto feature

css/properties/scroll-behavior.json
This PR adds the missing features of the `scroll-behavior` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/scroll-behavior
=> Add missing features for scroll-behavior CSS property

css/properties/overlay.json
This PR adds the missing features of the `overlay` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/overlay
=> Add missing features for overlay CSS property

css/properties/mix-blend-mode.json
This PR adds the missing `plus-darker` member of the `mix-blend-mode` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/mix-blend-mode/plus-darker
=> Add missing css.properties.mix-blend-mode.plus-darker feature

css/properties/mask-mode.json
This PR adds the missing features of the `mask-mode` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/mask-mode
=> Add missing features for mask-mode CSS property

css/properties/margin-trim.json
This PR adds the missing features of the `margin-trim` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/margin-trim
=> Add missing features for margin-trim CSS property

css/properties/inset-inline.json
This PR adds the missing `auto` member of the `inset-inline` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/inset-inline/auto
=> Add missing css.properties.inset-inline.auto feature

css/properties/inset-inline-start.json
This PR adds the missing `auto` member of the `inset-inline-start` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/inset-inline-start/auto
=> Add missing css.properties.inset-inline-start.auto feature

css/properties/inset-inline-end.json
This PR adds the missing `auto` member of the `inset-inline-end` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/inset-inline-end/auto
=> Add missing css.properties.inset-inline-end.auto feature

css/properties/inset-block.json
This PR adds the missing `auto` member of the `inset-block` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/inset-block/auto
=> Add missing css.properties.inset-block.auto feature

css/properties/initial-letter.json
This PR adds the missing `normal` member of the `initial-letter` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/initial-letter/normal
=> Add missing css.properties.initial-letter.normal feature

css/properties/hyphenate-limit-chars.json
This PR adds the missing `auto` member of the `hyphenate-limit-chars` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/hyphenate-limit-chars/auto
=> Add missing css.properties.hyphenate-limit-chars.auto feature

css/properties/hanging-punctuation.json
This PR adds the missing features of the `hanging-punctuation` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/hanging-punctuation
=> Add missing features for hanging-punctuation CSS property

css/properties/forced-color-adjust.json
This PR adds the missing features of the `forced-color-adjust` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/forced-color-adjust
=> Add missing features for forced-color-adjust CSS property

css/properties/font-synthesis-small-caps.json
This PR adds the missing features of the `font-synthesis-small-caps` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/font-synthesis-small-caps
=> Add missing features for font-synthesis-small-caps CSS property

css/properties/background-size.json
This PR adds the missing `auto` member of the `background-size` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/background-size/auto
=> Add missing css.properties.background-size.auto feature

css/properties/clip-path.json
This PR adds the missing `view-box` member of the `clip-path` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/clip-path/view-box
=> Add missing css.properties.clip-path.view-box feature

css/properties/text-orientation.json
This PR adds the missing features of the `text-orientation` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/text-orientation
=> Add missing features for text-orientation CSS property

css/properties/view-transition-name.json
This PR adds the missing `none` member of the `view-transition-name` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/view-transition-name/none
=> Add missing css.properties.view-transition-name.none feature

css/properties/translate.json
This PR adds the missing `none` member of the `translate` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/translate/none
=> Add missing css.properties.translate.none feature

css/properties/scale.json
This PR adds the missing `none` member of the `scale` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/scale/none
=> Add missing css.properties.scale.none feature

css/properties/overscroll-behavior-x.json
This PR adds the missing features of the `overscroll-behavior-x` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/overscroll-behavior-x
=> Add missing features for overscroll-behavior-x CSS property

css/properties/offset-anchor.json
This PR adds the missing `auto` member of the `offset-anchor` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/offset-anchor/auto
=> Add missing css.properties.offset-anchor.auto feature

css/properties/hyphenate-character.json
This PR adds the missing `auto` member of the `hyphenate-character` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/hyphenate-character/auto
=> Add missing css.properties.hyphenate-character.auto feature

css/properties/font-size-adjust.json
This PR adds the missing `none` member of the `font-size-adjust` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/font-size-adjust/none
=> Add missing css.properties.font-size-adjust.none feature

css/properties/contain.json
This PR adds the missing features of the `contain` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/contain
=> Add missing features for contain CSS property

css/properties/font-variant-position.json
This PR adds the missing features of the `font-variant-position` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/font-variant-position
=> Add missing features for font-variant-position CSS property

css/properties/font-variant-alternates.json
This PR adds the missing features of the `font-variant-alternates` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/font-variant-alternates
=> Add missing features for font-variant-alternates CSS property

css/properties/font-synthesis-weight.json
This PR adds the missing features of the `font-synthesis-weight` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/font-synthesis-weight
=> Add missing features for font-synthesis-weight CSS property

css/properties/font-synthesis-style.json
This PR adds the missing features of the `font-synthesis-style` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/font-synthesis-style
=> Add missing features for font-synthesis-style CSS property

css/properties/font-synthesis-position.json
This PR adds the missing features of the `font-synthesis-position` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/font-synthesis-position
=> Add missing features for font-synthesis-position CSS property

css/properties/font-palette.json
This PR adds the missing features of the `font-palette` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/font-palette
=> Add missing features for font-palette CSS property

css/properties/counter-set.json
This PR adds the missing features of the `counter-set` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/counter-set
=> Add missing features for counter-set CSS property

css/properties/content-visibility.json
This PR adds the missing features of the `content-visibility` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/content-visibility
=> Add missing features for content-visibility CSS property

css/properties/container-type.json
This PR adds the missing features of the `container-type` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/container-type
=> Add missing features for container-type CSS property

css/properties/container-name.json
This PR adds the missing `none` member of the `container-name` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/container-name/none
=> Add missing css.properties.container-name.none feature

css/properties/contain-intrinsic-size.json
This PR adds the missing `none` member of the `contain-intrinsic-size` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/contain-intrinsic-size/none
=> Add missing css.properties.contain-intrinsic-size.none feature

css/properties/contain-intrinsic-inline-size.json
This PR adds the missing `none` member of the `contain-intrinsic-inline-size` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/contain-intrinsic-inline-size/none
=> Add missing css.properties.contain-intrinsic-inline-size.none feature

css/properties/contain-intrinsic-height.json
This PR adds the missing `none` member of the `contain-intrinsic-height` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/contain-intrinsic-height/none
=> Add missing css.properties.contain-intrinsic-height.none feature

css/properties/contain-intrinsic-block-size.json
This PR adds the missing `none` member of the `contain-intrinsic-block-size` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/contain-intrinsic-block-size/none
=> Add missing css.properties.contain-intrinsic-block-size.none feature

css/properties/color-interpolation-filters.json
This PR adds the missing features of the `color-interpolation-filters` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/color-interpolation-filters
=> Add missing features for color-interpolation-filters CSS property

css/properties/column-fill.json
This PR adds the missing features of the `column-fill` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/column-fill
=> Add missing features for column-fill CSS property

css/properties/baseline-shift.json
This PR adds the missing features of the `baseline-shift` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/baseline-shift
=> Add missing features for baseline-shift CSS property

css/properties/background-origin.json
This PR adds the missing features of the `background-origin` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/background-origin
=> Add missing features for background-origin CSS property

css/properties/animation-range-end.json
This PR adds the missing `normal` member of the `animation-range-end` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.8.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/animation-range-end/normal
=> Add missing css.properties.animation-range-end.normal feature

css/properties/-webkit-mask-repeat-x.json
This PR updates and corrects version values for WebView Android for the `-webkit-mask-repeat-x` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.7.1).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/-webkit-mask-repeat-x
=> Update WebView data for -webkit-mask-repeat-x CSS property

css/properties/contain-intrinsic-width.json
This PR adds the missing `contain-intrinsic-width` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/contain-intrinsic-width
=> Add missing contain-intrinsic-width CSS property feature

css/properties/box-sizing.json
This PR adds the missing features of the `box-sizing` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/box-sizing
=> Add missing features for box-sizing CSS property

css/properties/baseline-source.json
This PR adds the missing features of the `baseline-source` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/baseline-source
=> Add missing features for baseline-source CSS property

css/properties/background-position.json
This PR adds the missing `background-position` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/background-position
Additional Notes: The ranges were left as-is because these values were not supported when the property was introduced.
=> Add missing background-position CSS property feature

css/properties/animation-range-start.json
This PR adds the missing `normal` member of the `animation-range-start` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.8.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/animation-range-start/normal
=> Add missing css.properties.animation-range-start.normal feature

css/properties/border-style.json
This PR is a part of a project to add missing interfaces and interface features to BCD that are from an active spec (including WICG specs) and is supported in at least one browser. This particular PR adds the missing features of the `border-style` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.6.3).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/border-style
=> Add missing features for border-style CSS property

css/properties/outline-style.json
This PR is a part of a project to add missing interfaces and interface features to BCD that are from an active spec (including WICG specs) and is supported in at least one browser. This particular PR adds the missing features of the `outline-style` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.6.3).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/outline-style
=> Add missing features for outline-style CSS property

css/properties/aspect-ratio.json
This PR adds the missing `auto` member of the `aspect-ratio` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.8.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/aspect-ratio/auto
=> Add missing css.properties.aspect-ratio.auto feature

api/RTCStatsReport.json
This PR is a part of a project to add missing interfaces and interface features to BCD that are from an active spec (including WICG specs) and is supported in at least one browser. This particular PR adds the missing features of the `type_outbound-rtp` member of the `RTCStatsReport` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.6.5).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/RTCStatsReport/type_outbound-rtp
=> Add missing features for api.RTCStatsReport.type_outbound-rtp

package.json, scripts/save-git-history.ts
`save-git-history.ts` (introduced in https://github.com/mdn/browser-compat-data/pull/22308) breaks installing BCD from Git (in a fit of irony, there won't be a `.git` if you use `npm install github:mdn/browser-compat-data` and the dev dependencies won't be installed). This PR stops the script from running if you're not in a Git repo.
While I'm here, I've stopped the script from running if you are like me and have `HUSKY=0` set.
https://github.com/mdn/browser-compat-data/pull/22308
https://github.com/mdn/browser-compat-data/pull/21656
=> Unbreak installing from Git

css/properties/background-clip.json
This PR updates and corrects version values for Firefox Android for the `background-clip` CSS property. This data came from the wiki migration, so it's likely incorrect.
=> Update Firefox Android data for background-clip CSS property

browsers/edge.json
Following the edit in https://github.com/mdn/browser-compat-data/pull/22286. The URLs have been manually tested to confirm they work.
=> Update Edge 13-18 release note URLs

css/properties/animation-direction.json, css/properties/animation-fill-mode.json, css/properties/animation-iteration-count.json, css/properties/animation-name.json, css/properties/animation-play-state.json, css/properties/background-clip.json, css/properties/background-image.json, css/properties/background-origin.json, css/properties/background-repeat.json
This PR updates instances where Firefox was set to ≤15 or ≤16 in recent PRs, correcting them to use the version number that the property was introduced.
=> Update Firefox ≤15 + ≤16 with version numbers

css/properties/position.json
This PR updates and corrects version values for Firefox and Firefox Android for the `absolute` member of the `position` CSS property. This moves the notes specific to absolute positioning from the parent to this specific feature.
Additional Notes: Addresses https://github.com/mdn/browser-compat-data/pull/22488#discussion_r1512509699.
=> Update Firefox data for css.properties.position.absolute

css/properties/max-width.json, css/properties/min-height.json, css/properties/min-width.json, css/properties/width.json
These are the min-content, max-content, and fit-content property values.
The only difference when mirroring is the prefixed variants, and the
previous data can be assumed to be wrong, because this extremely rarely
depends on the platform.
=> Mirror Chrome Android data for *-content keywords

webextensions/manifest/commands.json
The documentation for the [command manifest key](https://developer.chrome.com/docs/extensions/reference/api/commands) in Chrome doesn't include support for function keys.
Fixes #14809
=> Function key support in command manifest key

docs/contributing.md
"404 - page not found" for CODE_OF_CONDUCT.md, GOVERNANCE.md and LICENSE in contributing page, updated the paths for these links.
=> Fix links (coc, governance and license) in contributing.md

css/properties/border-style.json
This PR updates and corrects version values for all browsers for the `border-style` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/border-style
Additional Notes: This is a follow-up to #21617.
=> Update all browsers data for border-style CSS property

css/properties/outline-style.json
This PR updates and corrects version values for all browsers for the `outline-style` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/outline-style
Additional Notes: This is a follow-up to https://github.com/mdn/browser-compat-data/pull/21616.
=> Update all browsers data for outline-style CSS property

html/elements/dd.json
This PR removes the `nowrap` member of the `dd` HTML element from BCD. Per the [data guidelines](https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines/index.md#removal-of-irrelevant-features), this feature can be considered irrelevant and may be removed from BCD accordingly. Even if the current data suggests that the feature is supported, lack of support has been confirmed by the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.6.5).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/html/elements/dd/nowrap
Additional Notes: I set a `<dd>` element to `<dd nowrap="yes">`, but it still wrapped the text; no rendering changed.
=> Remove html.elements.dd.nowrap from BCD

css/properties/box-decoration-break.json
This PR adds the missing features of the `box-decoration-break` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/box-decoration-break
Additional Notes: The alternative name does not support any of the known values and isn't documented on MDN, so I have removed it.
=> Add missing features for box-decoration-break CSS property

css/properties/column-count.json
This PR updates and corrects version values for all browsers for the `column-count` CSS property. This sets derivative browsers to mirror as their data had gotten desynchronized.
=> Update all browsers data for column-count CSS property

css/properties/column-span.json
This PR adds the missing features of the `column-span` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/column-span
=> Add missing features for column-span CSS property

css/properties/column-span.json
This PR updates and corrects version values for Opera and Opera Android for the `column-span` CSS property. This sets Opera to mirror to synchronize it with Chrome results.
=> Update Opera data for column-span CSS property

css/properties/column-count.json
This PR adds the missing `auto` member of the `column-count` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/column-count/auto
=> Add missing css.properties.column-count.auto feature

css/properties/text-orientation.json
This PR removes the `sideways-right` member of the `text-orientation` CSS property from BCD. The spec (https://drafts.csswg.org/css-writing-modes/#valdef-text-orientation-sideways-right) defines this feature as an alias of `sideways`.
=> Remove css.properties.text-orientation.sideways-right from BCD

css/properties/text-justify.json
This PR removes the `distribute` member of the `text-justify` CSS property from BCD. The spec (https://drafts.csswg.org/css-text/#valdef-text-justify-distribute) defines this keyword as a legacy value alias of `inter-character`.
=> Remove css.properties.text-justify.distribute from BCD

html/manifest/shortcuts.json
Safari 17.4 adds support for web app shortcuts. 
https://developer.apple.com/documentation/safari-release-notes/safari-17_4-release-notes
=> Safari 17.4 adds support for web app shortcuts. 

css/properties/appearance.json
This PR adds the missing features of the `appearance` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/appearance
=> Add missing features for appearance CSS property

javascript/builtins/Intl/NumberFormat.json, javascript/builtins/Intl/PluralRules.json
This PR creates an `options_parameter` subfeature for the constructors of `Intl.NumberFormat` and `Intl.PluralRules`.  All of the individual options are now subfeatures of this.
Fixes #15589.
=> Intl.NumberFormat/PluralRules: create options_parameter subfeature

css/properties/direction.json, css/properties/writing-mode.json
A couple more fixes coming out of conversations and testing around my vertical form control content (see https://github.com/mdn/content/pull/32142).
Specifically:
- It looks like writing-mode for vertical sliders are not supported as far as Safari 14. It seemed more like 16.5, as it worked in that on mine, but not in 16.1 on @wbamberg's mac.
- I also added in Safari support for direction, in the same version.
=> More minor fixes for vertical slider support

css/selectors/-moz-broken.json
FF119 removes [`:-moz-broken`](https://developer.mozilla.org/en-US/docs/Web/CSS/:-moz-broken) in https://bugzilla.mozilla.org/show_bug.cgi?id=1850899 - confirmed by running the example in that doc in browserstack. Note that the issue also remove moz-loading but that doesn't have a BCD entry.
Fixes https://github.com/mdn/content/pull/32628
=> FF119 :-moz-broken removed

html/global_attributes.json
According to data the `contextmenu` attribute was removed from last browser more than two years ago, and is therefore a candidate for removal from BCD and the docs.
This removes the entry.
Confirmed by @queengooborg in https://github.com/mdn/content/issues/32448#issuecomment-1965962908
Related to https://github.com/mdn/content/issues/32448
=> HTML global attribute contextmenu removed

api/ServiceWorker.json
add es module support version for Edge
Test on BrowserStack (feature test page: https://asset.dvlp4.fun/bcd-test/service-worker-es-module/index.html)
=> fix: add es module support version for Edge

css/at-rules/starting-style.json
STP 189 added support for `starting-style`. Update `starting-style` to `"preview"` for Safari. 
Passes 14/15 [wpt.fyi tests](https://wpt.fyi/results/css/css-transitions?label=master&label=experimental&aligned&q=starting-style)
In [WebKit STP 189 release notes](https://webkit.org/blog/15050/release-notes-for-safari-technology-preview-189/)
In [Apple STP 189 release notes](https://developer.apple.com/documentation/safari-technology-preview-release-notes/stp-release-189)
[Enabled](https://github.com/WebKit/WebKit/commit/1544606a8541c44e64d73ae4693c90da45ca6402)
[Implementation](https://github.com/WebKit/WebKit/commit/bfcf9bf5da23fd0e272fa6b63fd1f6830322a576)
[Computation](https://github.com/WebKit/WebKit/commit/b28edead7c0c1615e7f7f934c475245e61742fe7)
No
=> Update starting-style.json, STP 189 added support for `starting-style`, update Safari to `"preview"`

css/types/color.json
STP 189 adds support for the 'light-dark()' function for color values. Update `light-dark` in Safari to "preview".
Attached is a test case using the playground:
Passes 5/5 of the [wpt.fyi tests](https://wpt.fyi/results/css/css-color?label=master&label=experimental&aligned&q=light-dark)
In [Webkit's STP release notes](https://webkit.org/blog/15050/release-notes-for-safari-technology-preview-189/)
In [Apple's STP release notes](https://developer.apple.com/documentation/safari-technology-preview-release-notes/stp-release-189)
[Enabling](https://github.com/WebKit/WebKit/commit/42f9569ae95a1bbef0a26f460bdaa7efdb637fff)
[Implementation](https://github.com/WebKit/WebKit/pull/22242/files)
=> Update light-dark to `"preview"` for Safari, STP 189 added support

webextensions/api/runtime.json
Adds compatibility details for the `runtime.on performance` event introduced by [Bug 1861445](https://bugzilla.mozilla.org/show_bug.cgi?id=1861445) Add new hang warning event API for WebExtensionswarning.
See https://github.com/mdn/content/pull/32222 for the MDN content update.
=> Add runtime.onPerformanceWarning

api/ServiceWorkerGlobalScope.json, api/ServiceWorkerRegistration.json, api/SyncEvent.json, api/SyncManager.json
The docs say the ServiceWorkerGlobalScope ["sync" event](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerGlobalScope/sync_event) is type [SyncEvent](https://developer.mozilla.org/en-US/docs/Web/API/SyncEvent) and depends on [SyncManager](https://developer.mozilla.org/en-US/docs/Web/API/SyncManager), and both of those are experimental technology, so the "sync" event must be experimental too.
NOTE: the script has been flipped and now `SyncEvent` and `SyncManager` are *not* experimental.  This PR reflects that change.
=> sync_event is experimental like SyncEvent and SyncManager

README.md
This PR supersedes #21599 and adds examples for importing BCD using the new import attributes (`with`) syntax.  This also adds an example for Deno using `fetch()`.
Fixes #22078.
=> Add import attributes examples to readme

webextensions/api/tabs.json
Update to tabs.Tab properties including:
- addition of `attention` - missing property supported in Firefox (could trace support back to Firefox 65 but was clearly implemented earlier, blame was failing to backtrack on show earliest version with this line.)
- addition of groupId and pendingUrl - missing properties supported in Chrome
- update to `lastAccessed` – now supported in Chrome as of 121
Fixes https://github.com/mdn/content/issues/22275
Related mdn documentation updates in https://github.com/mdn/content/pull/32279
=> tabs.Tab properties update

webextensions/api/runtime.json
Adds compatibility details for the `runtime.OnPerformanceWarningCategory` and `runtime.OnPerformanceWarningSeverity`tvpev introduced by [Bug 1861445](https://bugzilla.mozilla.org/show_bug.cgi?id=1861445) Add new hang warning event API for WebExtensionswarning.
See https://github.com/mdn/content/pull/32222 for the MDN content update.
DO NOT MERGE until related MDN content is ready to merge.
=> Add runtime.onPerformanceWarning types

api/ML.json, api/MLActivation.json, api/MLContext.json, api/MLGraph.json, api/MLGraphBuilder.json, api/MLOperand.json, api/Navigator.json, api/WorkerNavigator.json
This PR adds BCD for the [WebNN API](https://www.w3.org/TR/webnn/).
Currently the WebNN feature is behind the #web-machine-learning-neural-network flag.
=> Add BCD for the WebNN API

api/MIDIAccess.json, api/MIDIConnectionEvent.json, api/MIDIInput.json, api/MIDIInputMap.json, api/MIDIMessageEvent.json, api/MIDIOutput.json, api/MIDIOutputMap.json, api/MIDIPort.json, api/Navigator.json, api/Permissions.json, http/headers/Permissions-Policy.json
This PR adds the required `web-features` tags to the Web MIDI API features in BCD, so that they can be linked to the [web-features](https://github.com/web-platform-dx/web-features/) repository and get their baseline status computed.
=> Add the Web MIDI API web-features tag

api/MIDIAccess.json, api/MIDIConnectionEvent.json, api/MIDIInput.json, api/MIDIInputMap.json, api/MIDIMessageEvent.json, api/MIDIOutput.json, api/MIDIOutputMap.json, api/MIDIPort.json, api/Navigator.json, api/Permissions.json, http/headers/Permissions-Policy.json
This PR replaces the `web-features:midi` tag with `web-features:web-midi` in order to match the name of the WebDX feature.
We discussed about this on the topic of the Web Bluetooth API here: https://github.com/web-platform-dx/web-features/pull/691#discussion_r1525301238 and decided to also apply this to the Web MIDI API.
=> Rename midi web-feature to web-midi to match the webdx repo

api/ScrollTimeline.json, api/ViewTimeline.json, css/at-rules/keyframes.json, css/properties/animation-range-end.json, css/properties/animation-range-start.json, css/properties/animation-range.json, css/properties/animation-timeline.json, css/properties/scroll-timeline-axis.json, css/properties/scroll-timeline-name.json, css/properties/scroll-timeline.json, css/properties/timeline-scope.json, css/properties/view-timeline-axis.json, css/properties/view-timeline-inset.json, css/properties/view-timeline-name.json, css/properties/view-timeline.json
This PR adds `impl_url` entries for Safari's implementation of the Scroll-driven animation feature.
It also introduces the `web-features:scroll-driven-animations` tag to match the corresponding web-features entry: https://github.com/web-platform-dx/web-features/blob/main/feature-group-definitions/scroll-driven-animations.yml
=> Scroll-driven animation missing `impl_url` for Safari, and web-features tag

.github/labeler.yml
This PR drops the auto-labeling of any changes to `package.json` as dependency changes.  This is because `package.json` also includes scripts which can be changed without changing dependencies, and if the dependencies are updated, `package-lock.json` will also update.
=> Don't label changes to package.json as dependencies

css/properties/align-tracks.json, css/properties/grid-template-columns.json, css/properties/grid-template-rows.json, css/properties/justify-tracks.json, css/properties/masonry-auto-flow.json
This PR adds the Chrome, Safari, and Firefox bugs that track shipping Masonry layout in these 3 browsers, as `impl_url` fields.
=> `impl_url` fields for Masonry layout

javascript/builtins/Intl/Segmenter.json
FF125 supports [`Intl.Segmenter`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Segmenter) in https://bugzilla.mozilla.org/show_bug.cgi?id=1883914.
This just changes the supported version from preview to 125.
FYI I know that you would have caught this later on anyway @Elchi3 :-)
Related docs can be tracked in https://github.com/mdn/content/issues/32661
=> FF125 Intl.Segmenter

RELEASE_NOTES.md, package-lock.json, package.json
This reverts commit 5520291466ca5a5801a55d187c8b65b1d769c545.  The release had failed, and thus v5.5.17 was never actually released, so this reverts the changes to the version number and release notes.
=> "Unrelease" v5.5.17

RELEASE_NOTES.md, package-lock.json, package.json
Reverts mdn/browser-compat-data#22689.  It appears that there's an access issue with NPM.
=> Revert "Release v5.5.17" (again)

css/properties/grid-template-columns.json, css/properties/grid-template-rows.json
Support data for `grid-template-columns` and `grid-template-rows` document the properties and property values defined in CSS Grid 2: https://drafts.csswg.org/css-grid/#track-sizing
... but not to the new property value `masonry` defined in CSS Grid 3: https://drafts.csswg.org/css-grid-3/#grid-template-masonry
CSS Grid 2 is well supported across browsers. The new `masonry` value is not.
This update makes the `spec_url` property consistent with `support`.
@Elchi3 This is the mismatch I spotted while exploring web features and standardization. This is why CSS Grid 3 appears as a potentially "late incubation" with Baseline high features in the first list in https://github.com/tidoust/web-features-standardization/issues/1
=> Drop spec link to css-grid-3 from grid-template-columns|rows

webextensions/api/scripting.json
Update scripting.json with support for error property in InjectionResult
See [Safari 17.4 Release Notes](https://developer.apple.com/documentation/safari-release-notes/safari-17_4-release-notes#Resolved-Issues)
=> Update scripting.json Safari support for error property in InjectionResult

html/manifest/categories.json
Safari 17.4 adds support for web app categories.
Tested locally; https://developer.apple.com/documentation/safari-release-notes/safari-17_4-release-notes
Fixes #22564
=> Safari 17.4 adds support for web app categories

javascript/builtins/Intl/RelativeTimeFormat.json
This PR adds the missing features of the `RelativeTimeFormat.RelativeTimeFormat` member of the `Intl` JavaScript builtin. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.10.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/javascript/builtins/Intl/RelativeTimeFormat/RelativeTimeFormat
=> Add missing features for javascript.builtins.Intl.RelativeTimeFormat.RelativeTimeFormat

api/GPUCommandEncoder.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `writeTimestamp` member of the `GPUCommandEncoder` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.10.2).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/GPUCommandEncoder/writeTimestamp
=> Update Chromium data for api.GPUCommandEncoder.writeTimestamp

api/HTMLElement.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `togglePopover.returns_boolean` member of the `HTMLElement` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.10.2).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/HTMLElement/togglePopover/returns_boolean
=> Update Chromium data for api.HTMLElement.togglePopover.returns_boolean

api/NotRestoredReasonDetails.json, api/NotRestoredReasons.json, api/PerformanceNavigationTiming.json
After an [initial false start](https://github.com/mdn/browser-compat-data/pull/20361), Chrome 123 now supports the `notRestoredReasons` API. This has a bigger data footprint than before, because the `notRestoredReasons` return object is now properly defined as an interface, whereas it wasn't before.
Specifically, this PR includes data for:
- The `PerformanceNavigationTiming.notRestoredReasons` property
- The `NotRestoredReasons` interface
- The `NotRestoredReasonDetails` interface
Full disclosure — this featureset is enabled by default in Chrome 123, but it is initially being rolled out gradually to users, and ramped up to 100% provided not problems are witnessed. I wasn't sure if this should be represented somehow in the BCD, as it shouldn't be a thing for long, and it's not really …
=> Adding notRestoredReasons BCD

api/CSSKeyframesRule.json
https://chromiumdash.appspot.com/commit/a22c1207bb2c8ba2e6f88bb00c09062f980dd04f
Also confirmed by testing Chrome 123 with the collector: https://mdn-bcd-collector.gooborg.com/tests/api/CSSKeyframesRule/length
Note that the chromestatus entry is wrong:
https://chromestatus.com/feature/6289894144212992
=> Update Chrome support for CSSKeyframesRule length

javascript/builtins/WeakMap.json, javascript/builtins/WeakSet.json
https://bugzilla.mozilla.org/show_bug.cgi?id=1710433 is the tracking bug. I couldn't find a bug that is specifically about enabling this feature by default.
cc @captainbrosset
=> Add Firefox impl_url for symbols as property keys

css/properties/align-content.json
Added the browser suport for CSS property `align-content` in `display: block;`
Working on [Issue 32662](https://github.com/mdn/content/issues/32662)
Tested in:
- Firefox 125
- Chrome 123
- Edge 123
- Safari 17.4
- Content PR -  coming soon
- Firefox release note PR -  coming soon
- [data PR](https://github.com/mdn/data/pull/721)
=> added support for align-content in display block

api/GPUCommandEncoder.json
(I was a bit too quick with merging https://github.com/mdn/browser-compat-data/pull/22608)
See https://github.com/gpuweb/gpuweb/pull/4370
I think what needs to happen here is also:
- status: deprecated, non-standard and no longer experimental
- Remove web-features tag given this method is no longer needed to have a full WebGPU implementation. (cc @foolip, @ddbeck)
=> Deprecate GPUCommandEncoder.writeTimestamp

api/Document.json, api/Element.json, api/HTMLIFrameElement.json, api/HTMLImageElement.json, api/RTCIceCandidate.json, api/ReadableStream.json, api/Request.json, api/ShadowRoot.json
The [Open Web Docs BCD collector](https://github.com/openwebdocs/mdn-bcd-collector) v10.10.2 found new features shipping in Chrome 124 beta which was released yesterday. Currently, the collector covers about 90% of BCD, so the following list might not be exhaustive. Also, if a feature is in Chrome Canary/behind origin trials/enrollment, it is not considered here.
With this PR, BCD considers the following features as shipping in Chrome 124:
- api.Document.parseHTMLUnsafe_static
- api.Element.attachShadow.init_clonable_parameter
- api.Element.setHTMLUnsafe
- api.HTMLIFrameElement.sharedStorageWritable
- api.HTMLImageElement.sharedStorageWritable
- api.RTCIceCandidate.relayProtocol
- api.RTCIceCandidate.url
- api.ReadableStream.values
- api.ReadableStream.@@asyncIterator
- …
=> Updates for Chrome 124 beta

css/at-rules/property.json
Removed the note on Firefox not supporting interpolation, as Firefox supports interpolating registered custom properties now.
https://bugzilla.mozilla.org/show_bug.cgi?id=1869185
=> Remove note on Firefox not supporting interpolation

html/elements/script.json
The speculation rules `source` key is optional as of Chrome 122; its value is now implied by the presence of the `url` or `where` keys. See https://developer.chrome.com/blog/speculation-rules-improvements#optional_source.
Related content update: https://github.com/mdn/content/pull/32455
=> Speculation rule source key optional

javascript/builtins/Intl/Locale.json
`Intl.Locale#getTextInfo` uses alternative name in Deno (same as other V8-powered runtimes)
Screenshot:
Text version:
```
➜  repos deno
Deno 1.41.3
exit using ctrl+d, ctrl+c, or close()
REPL is running with all permissions allowed.
To specify permissions, run `deno repl` with allow flags.
> const locale = new Intl.Locale('ar')
undefined
> locale.textInfo
{ direction: "rtl" }
> locale.getTextInfo
undefined
> locale.getTextInfo()
Uncaught TypeError: locale.getTextInfo is not a function
at <anonymous>:1:29
>
```
=> Intl.Locale#getTextInfo uses alternative name in Deno

css/at-rules/scope.json
Added the missing mdn_url property to the css.at-rules.scope file
Functional link: [https://developer.mozilla.org/en-US/docs/Web/CSS/@scope](https://developer.mozilla.org/en-US/docs/Web/CSS/@scope)
None
=> fix(css.at-rules.scope): Add missing mdn_url to css.at-rules.scope

api/CSSImportRule.json
This PR updates and corrects version values for Microsoft Edge for the `supportsText` member of the `CSSImportRule` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.10.2).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/CSSImportRule/supportsText
=> Update Edge data for api.CSSImportRule.supportsText

api/HTMLMediaElement.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `preservesPitch` member of the `HTMLMediaElement` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.10.2).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/HTMLMediaElement/preservesPitch
=> Update Safari data for api.HTMLMediaElement.preservesPitch

api/CloseWatcher.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `CloseWatcher` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.10.2).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/CloseWatcher
Additional Notes: Fixes #22602.
=> Update Chromium data for CloseWatcher API

api/MediaSession.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `setActionHandler` member of the `MediaSession` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.10.2).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/MediaSession/setActionHandler
=> Update Chromium data for api.MediaSession.setActionHandler

api/Permissions.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `permission_notifications` member of the `Permissions` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.10.2).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/Permissions/permission_notifications
=> Update Safari data for api.Permissions.permission_notifications

api/Permissions.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `permission_push` member of the `Permissions` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.10.2).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/Permissions/permission_push
=> Update Safari data for api.Permissions.permission_push

api/GPURenderBundleEncoder.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `setVertexBuffer.unset_vertex_buffer` member of the `GPURenderBundleEncoder` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.10.2).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/GPURenderBundleEncoder/setVertexBuffer/unset_vertex_buffer
=> Update Chromium data for api.GPURenderBundleEncoder.setVertexBuffer.unset_vertex_buffer

api/GPURenderPassEncoder.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `setVertexBuffer.unset_vertex_buffer` member of the `GPURenderPassEncoder` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.10.2).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/GPURenderPassEncoder/setVertexBuffer/unset_vertex_buffer
=> Update Chromium data for api.GPURenderPassEncoder.setVertexBuffer.unset_vertex_buffer

api/GPUPipelineError.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `GPUPipelineError.message_optional` member of the `GPUPipelineError` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.10.2).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/GPUPipelineError/GPUPipelineError/message_optional
=> Update Chromium data for api.GPUPipelineError.GPUPipelineError.message_optional

api/HTMLIFrameElement.json
This PR adds the missing `adAuctionHeaders` member of the `HTMLIFrameElement` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.10.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/HTMLIFrameElement/adAuctionHeaders
=> Add missing api.HTMLIFrameElement.adAuctionHeaders feature

lint/fix.ts
This PR fixes a bad path in the fix script, following a recent file moving.
Self-merging since this is a critical bug.
=> Fix the linter fix script

api/Navigator.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `Navigator` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.10.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/Navigator
=> Update Safari data for Navigator API

api/URLSearchParams.json
This PR updates and corrects version values for Chrome and Safari for the `URLSearchParams` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.10.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/URLSearchParams
=> Update Chrome/Safari data for URLSearchParams API

api/Element.json, api/ElementInternals.json, api/HTMLButtonElement.json, api/HTMLElement.json, api/HTMLInputElement.json, api/RTCDtlsTransport.json, api/RTCIceTransport.json, api/SVGAElement.json, css/properties/transform-box.json, css/selectors/backdrop.json, css/selectors/popover-open.json, html/elements/button.json, html/elements/input.json, html/global_attributes.json, javascript/builtins/Intl/Segments.json, webassembly/multiMemory.json
The [Open Web Docs BCD collector](https://github.com/openwebdocs/mdn-bcd-collector) v10.10.2 found new features shipping in Firefox 125 beta which was released yesterday. Currently, the collector covers about 90% of BCD, so the following list might not be exhaustive. Also, if a feature is in Firefox Nightly only, it is not considered here.
With this PR, BCD considers the following 40 features as shipping in Firefox 125:
- api.Element.ariaBrailleLabel
- api.Element.ariaBrailleRoleDescription
- api.ElementInternals.ariaBrailleLabel
- api.ElementInternals.ariaBrailleRoleDescription
- api.HTMLButtonElement.popoverTargetAction
- api.HTMLButtonElement.popoverTargetElement
- api.HTMLElement.beforetoggle_event
- api.HTMLElement.hidePopover
- api.HTMLElement.popover
- api.HTMLElement.showPopover
- …
=> Updates for Firefox 125 beta

html/elements/link.json
Add preload types as suggested in https://github.com/mdn/browser-compat-data/pull/22658#pullrequestreview-1963423648
I'm not 100% sure when each of these `as` values support was added and not sure there's an easy way to check so have just copied the main `preload` values.
Currently the only difference is `track` which is unsupported by Firefox.
https://wpt.fyi/results/preload?label=experimental&label=master&aligned
Enhancement to #22658
=> Link prel preload supported as values

javascript/builtins/JSON.json
Added browser compat data for `JSON.rawJSON()` and `JSON.isRawJSON()`.
Quick Test to check if a browser supports both the functions and their integration in `JSON.stringify()`:
```ts
function testRawJSON(){
const bigInt = BigInt(Number.MAX_SAFE_INTEGER) + 20n
const bigIntString = bigInt.toString(10)
try {
const raw = JSON.rawJSON(bigIntString)
const isRaw = JSON.isRawJSON(raw)
const stringified = JSON.stringify({ number: raw })
console.info({ raw, isRaw, stringified })
console.info('Is supported: %s', isRaw === true && stringified === `{"number":${bigIntString}}`)
} catch(error) {
console.error(error)
console.info('Is supported: false')
}
}
```
[tc39.es proposal | Spec | isRawJSON](https://tc39.es/proposal-json-parse-with-source/#sec-json.israwjson)
[tc39.es proposal | Spec | …
=> Add BCD for JSON.rawJSON and JSON.isRawJSON

.github/labeler.yml, .github/workflows/labeler.yml
Bump actions/labeler from 4 to 5.
The new [input: `sync-label`](https://github.com/actions/labeler?tab=readme-ov-file#inputs) is added to automatically remove unmatched labels (which is configured in label matching entries)
We can test the matching rule with the following script:
```js
import { minimatch } from "minimatch";
const filePath = ".github/labeler.yaml";
const pattern = ".github/**";
console.log(minimatch(filePath, pattern));
```
- mdn/content: mdn/content#32644
- mdn/translated-content: mdn/translated-content#18402
=> chore(ci): Bump actions/labeler from 4 to 5

api/RTCStatsReport.json
This adds subfeatures for the fields defined in the spec [RTCVideoSourceStatus](https://w3c.github.io/webrtc-stats/#dom-rtcvideosourcestats): frames, framesPerSecond, Width, Height.
1. Used browserstack and https://wpt.live/webrtc-stats/supported-stats.https.html tests to bisect for support on Chrome.
2. FF116 added these in https://bugzilla.mozilla.org/show_bug.cgi?id=1836879
3. No idea for Safari - doesn't run in Browserstack.
=> RTCStatsReport.type_media-source for video

css/at-rules/font-face.json
The same bug is already linked for font-feature-settings.
=> Link bug for font-variation-settings descriptor

api/CharacterBoundsUpdateEvent.json, api/EditContext.json, api/HTMLElement.json, api/TextFormat.json, api/TextFormatUpdateEvent.json, api/TextUpdateEvent.json
https://chromestatus.com/feature/5041440373604352 says this is supported
in Chrome for Android, and wpt.fyi results agree:
https://wpt.fyi/results/editing/edit-context?label=master&product=chrome&product=chrome_android
This updates all features tagged with web-features:edit-context,
originally added here:
https://github.com/mdn/browser-compat-data/pull/21603
=> Mirror Chrome Android data for Edit Context API

css/properties/backdrop-filter.json
https://caniuse.com/css-backdrop-filter has a note for Edge 17-18 which
turns out to be correct. It was only supported as
-webkit-backdrop-filter, presumably due to site compat issues.
This was verified by testing https://wpt.live/css/filter-effects/backdrop-filter-basic.html
in Edge 17. The test doesn't pass as-is, but changing backdrop-filter to
-webkit-backdrop-filter and it does render as expected.
=> Update Edge data for backdrop-filter

css/properties/align-content.json
The linked bug was fixed in Chrome 108:
https://chromiumdash.appspot.com/commit/3879406517fb19168eb0944866f77f7352c05962
The other two properties were done here:
https://github.com/mdn/browser-compat-data/pull/18814
=> Update Chrome data for align-content: last baseline

api/MediaSession.json
The status of specific action handlers is already captured in subfeatures. Notes like these are hard to keep in sync, and they're in fact not in sync as nextslide/previousslide are also not supported.
Chrome also doesn't support all action handlers, and doesn't have partial impl. like this.
=> Remove setActionHandler() partial impl. + notes for Firefox/Safari

api/PushSubscriptionChangeEvent.json, api/ServiceWorkerGlobalScope.json
The Firefox data seems contradictory without these notes. It's not a
contradiction because the event is fired, but not using a
PushSubscriptionChangeEvent object.
=> Add bugs and notes for the pushsubscriptionchange event

api/Bluetooth.json, api/BluetoothCharacteristicProperties.json, api/BluetoothDevice.json, api/BluetoothRemoteGATTCharacteristic.json, api/BluetoothRemoteGATTDescriptor.json, api/BluetoothRemoteGATTServer.json, api/BluetoothRemoteGATTService.json, api/BluetoothUUID.json, api/Navigator.json, api/NetworkInformation.json
Lack of support on Linux should be considered partial implementation
according to our guidelines:
https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines/index.md#operating-system-limitations-imply-partial_implementation
This allows the Edge data to be mirrored.
Also update some "Also support on" notes to use a consistent style.
=> Turn Bluetooth partial impl with notes into multiple support statements

api/CSSContainerRule.json, api/CSSFontFeatureValuesRule.json, css/at-rules/font-feature-values.json, css/properties/animation.json, css/types/length.json, javascript/builtins/TypedArray.json, javascript/operators/super.json
These are cases where the tag already exists in BCD, but additional
entries are being tagged. This is to bring tags in sync with
web-features, so that we can remove compat_keys in most cases.
=> Tag additional entries for web-features

api/RTCRtpReceiver.json
It was enabled in Chrome 73:
https://chromiumdash.appspot.com/commit/86c8a3c5f1fee11f65b22897ef822cda7750ce23
This data was added to BCD in 2018, well before Chrome 73 was released:
https://github.com/mdn/browser-compat-data/pull/948
=> Mark getContributingSources() audioLevel property supported in Chrome

api/Headers.json
Split two wrongly combined features for iterating over `Headers` objects and update their support data.
Manually tested with something close to this (extraneous logging and such removed):
```js
var populate = [];
var abc = ["A", "B", "C", "D", "E", "F"].reverse();
for (var index = 0; index < 512; index++) {
populate[index] = ["X-" + abc[index % abc.length], "_"];
}
var headers = new Headers([
["Accept-Language", "en-US,en;q=0.5"],
["Accept-Language", "en-US,en;q=0.5"],
["Accept-Language", "en-US,en;q=0.5"],
].concat(populate));
console.log(headers);
for (var header of headers) {
console.log(header);
}
```
I was investigating this feature in the course of creating a fetch feature in web-features. The data for Safari looked dubious. I soon found out that the two parts of this (sorting and …
=> Split `api.Headers.lexicographical_sorting` in two and update the data

api/CSSImportRule.json, api/CSSStartingStyleRule.json, css/at-rules/starting-style.json, css/properties/text-wrap-style.json, css/properties/text-wrap.json, css/types/color.json
The [Open Web Docs BCD collector](https://github.com/openwebdocs/mdn-bcd-collector) v10.10.4 found new features shipping in Safari 17.5 beta (19618.2.4.11.2) which was released yesterday. Currently, the collector covers about 90% of BCD, so the following list might not be exhaustive. Also, if a feature is in Safari TP and/or behind flags, it is not considered here.
With this PR, BCD considers the following features as shipping in Safari 17.5:
- api.CSSImportRule.supportsText
- api.CSSStartingStyleRule
- css.at-rules.starting-style
- css.properties.text-wrap-style
- css.properties.text-wrap-style.auto
- css.properties.text-wrap-style.balance
- css.properties.text-wrap-style.stable
- css.properties.text-wrap.balance
- css.properties.text-wrap.stable
- css.types.color.light-dark …
=> Updates for Safari 17.5 (19618.2.4.11.2)

webextensions/api/proxy.json
Added 'proxy.ProxyInfo.proxyAuthorizationHeader' with note that it also supports settings for HTTP proxies. This change was made in [Bug 1794464](https://bugzilla.mozilla.org/show_bug.cgi?id=1794464) 
"Allow HTTP authentication in proxy.onRequest."
Related content changes in https://github.com/mdn/content/pull/32536
=> Note re proxy.ProxyInfo.proxyAuthorizationHeader HTTP support from 125

javascript/builtins/ArrayBuffer.json, javascript/builtins/DataView.json, javascript/builtins/Float32Array.json, javascript/builtins/Float64Array.json, javascript/builtins/Int16Array.json, javascript/builtins/Int32Array.json, javascript/builtins/Int8Array.json, javascript/builtins/Map.json, javascript/builtins/Set.json, javascript/builtins/TypedArray.json, javascript/builtins/Uint16Array.json, javascript/builtins/Uint32Array.json, javascript/builtins/Uint8Array.json, javascript/builtins/Uint8ClampedArray.json, javascript/builtins/WeakMap.json
These entries document the absence of a bug. If inverted, they describe
a feature which was supported, but has long been removed. Such entries
are irrelevant per this guidline:
https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines/index.md#removal-of-irrelevant-features
Another way to look at this is that the standard behavior works before
and after this bug was fixed, and the non-standard beahvior is
additional API surface which no longer exists.
=> Remove all "Thing() without new throws" entries

api/HTMLSlotElement.json
The event was implemented long before the feature was enabled: https://github.com/WebKit/WebKit/commit/96577bfd3aecc0323f15cf77e664a95294cceb05
It was only the onslotchange property that was missing: https://github.com/WebKit/WebKit/commit/3e059eef4d8b201ca9818e8e0cbe106be2aa5e73
=> Describe slotchange event in Safari 10

javascript/statements.json
The compat data for import assertions and attributes is out of date. This PR, hopefully, corrects it.
Some background info:
* `import ... from ... assert ...` is now deprecated, but still implemented in Chromium (aka import assertions).
* `import ... from ... with ...` is the new way of doing this (aka import attributes).
* Both syntax can be used with `{type: json}` or `{type: css}`. The latter is missing from BCD altogether.
* Safari 17.2 added support for import attributes in 17.2, but only for `{type: json}`. https://developer.apple.com/documentation/safari-release-notes/safari-17_2-release-notes#JavaScript
* Chromium supports import attributes for both types.
I tested with a local HTML file on Chrome, Edge, Firefox, and Safari. And checked …
=> Correct the import assertions and attributes compat table

css/properties/transition-behavior.json, css/properties/transition.json
__Description:__
By using `transition-behavior`, authors can choose to enable animations for properties with discrete values, so transitions can happen at the >50% mark, flipping between two values.
__Bugzilla:__
- impl bug [bugzilla.mozilla.org/show_bug.cgi?id=1805727](https://bugzilla.mozilla.org/show_bug.cgi?id=1805727)
- (`display` bug) https://bugzilla.mozilla.org/show_bug.cgi?id=1882408
Pref: https://searchfox.org/mozilla-central/source/modules/libpref/init/StaticPrefList.yaml#8362
__Existing docs:__
- https://developer.mozilla.org/en-US/docs/Web/CSS/transition-behavior
=> chore(relnotes): Enable CSS transition-behavior in Nightly

webextensions/api/runtime.json
Updates BCD to note that runtime.MessageSender.origin is supported in Firefox 126.
Addresses the dev-docs-needed request for [Bug 1787379](https://bugzilla.mozilla.org/show_bug.cgi?id=1787379) Support MessageSender.origin for extension messages
Release notes added in https://github.com/mdn/content/pull/33097
=> Add runtime.MessageSender.origin support in Firefox 126

webextensions/api/commands.json
- Adds Commands.on command.tab support
- Corrects Command type to list description, name. and shortcut
- removes unnecessary update.details, which will exemplify update.name etc. on MDN
Provides dev-doc-needed for [Bug 1843866](https://bugzilla.mozilla.org/show_bug.cgi?id=1843866) Add tab parameter to commands.onCommand
Fixed #22803
Release note documentation in https://github.com/mdn/content/pull/33094
=> Adds Commands.on command.tab support

http/headers/Content-Encoding.json
FF126 supports zstd encoding in the [`Content-Encoding`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Encoding#zstd) header in https://bugzilla.mozilla.org/show_bug.cgi?id=1871963
This adds BCD entry, updates the MDN URL, and marks as not experimental (chrome also supports it).
Related docs work can be tracked in https://github.com/mdn/content/issues/33086
=> FF126 HTTP Content-Encoding supports zstd encoding

html/elements/hr.json, html/elements/select.json
Android Chrome has never supported `<hr>` in `<select>`. Safari added support on iOS in Safari 17.4.
Apropos https://github.com/mdn/browser-compat-data/issues/21648 I tested https://adrianroselli.com/demos/splitting-within-selects/index.html
There, I clicked/tapped on the "Select a major" example on an iPhone 13 Pro in Safari 17.4 / iOS 17.4 and an iPad in Safari 17.4 / iPadOS 17.4.
I found that it:
* exposes the `<hr>` visually in the page.
* does not expose the `<hr>` within the accessibility tree;
* does not announce the `<hr>` when using VoiceOver.
I repeated the same test on Android 13 in Google Chrome 123, and found that there was no visual `<hr>` at all.
Fixes #22729 and #22730.
=> Update <hr> in <select>

javascript/builtins/JSON.json
Added browser compat data for `JSON.parse()` and a reviver that expects a third argument `context`, containing the parsed source text.
Quick Test to check if a browser supports the context param:
```ts
function testJSONParseWithSource() {
const unsafeInt = (BigInt(Number.MAX_SAFE_INTEGER) + 1n);
try {
const parsedInt = JSON.parse(unsafeInt.toString(10), function (key, value, context) {
return BigInt(context.source);
});
console.info({ parsedInt })
console.info('Is supported: %s', parsedInt === unsafeInt)
} catch (error) {
console.error(error)
console.info('Is supported: false')
}
}
```
[tc39.es proposal | Spec | parse](https://tc39.es/proposal-json-parse-with-source/#sec-internalizejsonproperty)
[tc39.es proposal | GitHub](https://github.com/tc39/proposal-json-parse-with-source)
[Chromium …
=> Add BCD for JSON.parse with source context

api/HTMLTemplateElement.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `shadowRootDelegatesFocus` member of the `HTMLTemplateElement` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.10.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/HTMLTemplateElement/shadowRootDelegatesFocus
=> Update Chromium data for api.HTMLTemplateElement.shadowRootDelegatesFocus

api/IntersectionObserver.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `IntersectionObserver.options_root_parameter_Document` member of the `IntersectionObserver` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.10.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/IntersectionObserver/IntersectionObserver/options_root_parameter_Document
=> Update Safari data for api.IntersectionObserver.IntersectionObserver.options_root_parameter_Document

browsers/edge.json, css/properties/align-content.json
Adds missing engine_version field for latest MS edge releases.
I believe this is the cause of issues on MDN where data isn't mirroring correctly. (e.g. https://developer.mozilla.org/en-US/docs/Web/CSS/field-sizing#browser_compatibility shows Edge as not supported)
N/A
=> Add missing engine_version field to latest edge releases

api/OffscreenCanvas.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `getContext` member of the `OffscreenCanvas` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.10.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/OffscreenCanvas/getContext
=> Update Safari data for api.OffscreenCanvas.getContext

api/Permissions.json, http/headers/Permissions-Policy.json
The ambient sensor permission API and permission policy are behind same flag as the rest of the API
Fixes #22752
=> ambient sensor permissions behind flag on chrome

api/CSS.json
There are defined by CSS Typed OM:
https://drafts.css-houdini.org/css-typed-om/#numeric-factory
In other words, these are things that a browser would support only if both the CSS units and CSS Typed OM are supported.
=> Remove web-features tags for CSS Typed OM bits

api/HTMLAnchorElement.json, api/HTMLAreaElement.json, api/HTMLIFrameElement.json, api/HTMLImageElement.json, api/HTMLLinkElement.json, api/HTMLScriptElement.json
This PR updates and corrects version values for Safari for the `referrerPolicy` member of various APIs. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.7.1).
=> Update Safari data for referrerPolicy features

api/FontFaceSetLoadEvent.json
This PR updates and corrects version values for WebView Android for the `FontFaceSetLoadEvent` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.7.1).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/FontFaceSetLoadEvent
=> Update WebView data for FontFaceSetLoadEvent API

scripts/update-browser-releases/edge.ts
The engine_version property is not added when automatically updating release info for Edge. See https://github.com/mdn/browser-compat-data/pull/22842
I think this should add it.
=> Add engine_version for Edge when automatically updating data

api/PerformanceScriptTiming.json
This was forgotten in this manually submitted PR https://github.com/mdn/browser-compat-data/pull/22758. The Open Web Docs BCD collector discovered the oversight ;)
=> Add PerformanceScriptTiming.sourceFunctionName

scripts/update-browser-releases/chrome.ts
From 124 onwards https://developer.chrome.com/release-notes/124 is the pattern for where to find Chrome release notes
ran `npm run update-browser-releases` and saw that the script corrects this for Chrome, chrome android and webview for 124 in the browser/ data
none.
=> Chrome now provides full release notes

css/types/calc-constant.json
e: https://chromiumdash.appspot.com/commit/48ec6eb35ac1dc73a2a48dd39efbc14576ba35b2
pi: https://chromiumdash.appspot.com/commit/c1490d0ec81e0ecb0aa78c6fc39be9f9f6d0ec67
These tests passing in stable show it wasn't behind a flag:
https://wpt.fyi/results/css/css-values/acos-asin-atan-atan2-computed.html?label=master&label=stable&aligned
https://wpt.fyi/results/css/css-values/sin-cos-tan-computed.html?label=stable&label=master&aligned
=> Mark calc constants e and pi supported in Chrome

html/elements/iframe.json
Follows #3303.
https://bugzilla.mozilla.org/show_bug.cgi?id=1513021
Fixes #22863
=> `sandbox=allow-storage-access-by-user-activation` is enabled by default on Firefox

javascript/builtins/ArrayBuffer.json, javascript/builtins/BigInt64Array.json, javascript/builtins/BigUint64Array.json, javascript/builtins/DataView.json, javascript/builtins/FinalizationRegistry.json, javascript/builtins/Iterator.json, javascript/builtins/WeakRef.json
https://github.com/mdn/browser-compat-data/pull/22211 included a few new tags accidentally that aren't snapshots. (I had a lot to rebase when I landed this, sorry!).
=> Revert non-snapshot additions

api/TextEvent.json
The legacy `TextEvent` interface got specified 🎉  See https://w3c.github.io/uievents/#legacy-textevent-events. This means that the @openwebdocs collector discovered this as a new standardized IDL with implementations.
- Chrome: 1
- Safari: 5 https://github.com/WebKit/WebKit/commit/c4604525bdb5d0cb901ea454bd2bff8df8987843
- Firefox: Soon in nightly, currently unsupported.
- Edge: I used mirror but maybe this was in Edge.
- IE: We default to false but maybe this was supported.
=> Add TextEvent

api/CanvasRenderingContext2D.json, api/HTMLCanvasElement.json, api/OffscreenCanvas.json, api/OffscreenCanvasRenderingContext2D.json
Firefox 125 was released and the @openwebdocs BCD Collector discovered support for context loss events for canvas. 
Can be confirmed by https://bugzilla.mozilla.org/show_bug.cgi?id=1887729 and https://www.mozilla.org/en-US/firefox/125.0.1/releasenotes/
=> Firefox 125 shipped context loss events for canvas

api/RTCRtpReceiver.json
Thanks to https://github.com/openwebdocs/mdn-bcd-collector/pull/1342 the @openwebdocs BCD collector found support for RTCRtpReceiver.jitterBufferTarget in:
- Chrome 124: https://chromestatus.com/feature/5930772496384000
- Firefox 115: https://bugzilla.mozilla.org/show_bug.cgi?id=1592988
=> Add RTCRtpReceiver.jitterBufferTarget

api/WebSocketError.json, api/WebSocketStream.json
Discovered by the @openwebdocs BCD collector thanks to https://github.com/openwebdocs/mdn-bcd-collector/pull/1341.
No spec_url yet, see https://github.com/whatwg/websockets/pull/48
Adding the "websocket-stream" tag, sounds good Philip?
=> Add WebSocketStream

api/CSSStyleSheet.json
This got out of sync in https://github.com/mdn/browser-compat-data/pull/8823.
Also update the crbug link, which applies to all Chromium-based browsers.
=> Mirror CSSStyleSheet constructor data for Chromium

api/Worker.json
It has been in WebKit source for a very long time:
https://github.com/WebKit/WebKit/commit/9fe29e5b48b64cadbaffd6385818c1a7e93b3139
https://github.com/WebKit/WebKit/commit/94f1437aa28fd1fc32fde25e8ff3224d4f712724
It was controlled by a runtime flag, which I have not researched when it was flipped. Since this is the way to use worker modules, it must be supported at least since Safari 15, and any "support" before that is a no-op since the enum only has two values: "classic" and "module".
=> Mark Worker constructor options.type supported in Safari

html/global_attributes.json
It is not shipping in Chrome 125:
https://groups.google.com/a/chromium.org/g/blink-dev/c/jGTYNuidPRs/m/qm7Z5qsrAQAJ
=> Delete anchor HTML attribute

api/CustomStateSet.json, api/Element.json, api/ElementInternals.json, api/HTMLMarqueeElement.json, api/IDBFactory.json, api/IDBTransaction.json, api/Navigator.json, api/Permissions.json, api/RTCIceCandidate.json, api/Selection.json, api/URL.json, api/WakeLock.json, api/WakeLockSentinel.json, css/properties/zoom.json, css/selectors/state.json, http/headers/Permissions-Policy.json
The @openwebdocs [BCD collector project](https://github.com/openwebdocs/mdn-bcd-collector) v10.10.5 found new features shipping in Firefox 126 beta which was released yesterday. Currently, the collector covers about 90% of BCD, so the following list might not be exhaustive. Also, if a feature is in Firefox Nightly only, it is not considered here.
With this PR, BCD considers the following 45 features as shipping in Firefox 126:
- api.CustomStateSet
- api.CustomStateSet.add
- api.CustomStateSet.clear
- api.CustomStateSet.delete
- api.CustomStateSet.entries
- api.CustomStateSet.forEach
- api.CustomStateSet.has
- api.CustomStateSet.keys
- api.CustomStateSet.size
- api.CustomStateSet.values
- api.CustomStateSet.@@iterator
- api.Element.currentCSSZoom
- api.ElementInternals.states
- …
=> Updates for Firefox 126 beta

api/Selection.json
FF126 supports `Selection.getComposedRanges()` in nightly in https://bugzilla.mozilla.org/show_bug.cgi?id=1867058
You can see this in the IDL here https://hg.mozilla.org/integration/autoland/diff/0710183c2311e1db237d1db5ff8285138ba57dc3/modules/libpref/init/StaticPrefList.yaml behind nightly-enabled pref `dom.shadowdom.selection_across_boundary.enabled`
Related docs work can be tracked in https://github.com/mdn/content/issues/33180
=> FF126 Selection.getComposedRanges() in nightly

webextensions/manifest/options_page.json, webextensions/manifest/options_ui.json
Added details of aliasing of options_ui.page to options_page.
Addresses BCD requirements of [Bug 1816960](https://bugzilla.mozilla.org/show_bug.cgi?id=1816960) Consider aliasing options_page to options_ui.page
Content updates in https://github.com/mdn/content/pull/33212
=> Adding manifest options_page support in FF126

http/methods.json
This can be done without any research, since it is a foundational
"feature" that allows a browser to show anything at all.
At least one BCD feature with real values is needed for web-features to
compute the support for HTTP/1.1.
=> Mark HTTP GET as supported since the first release of each browser

api/HTMLElement.json, html/global_attributes.json
This reverts https://github.com/mdn/browser-compat-data/pull/22910 but uses version "preview" instead of "125".
=> Add back the anchor HTML attribute

browsers/edge.json
Only cases where the URL and release date didn't match were checked. It's possible there are additional cases where the linked Edge release notes are not the earliest for that Chromium milestone.
=> Update Edge release dates to match release notes

webextensions/manifest/permissions.json
Updates BCD to note that manifest permissions.webRequestAuthProvider is supported in Firefox 126.
Addresses the dev-docs-needed request for [Bug 1820569](https://bugzilla.mozilla.org/show_bug.cgi?id=1820569) Implement webRequestAuthProvider permission for webRequest.onAuthRequired
Release notes added in https://github.com/mdn/content/pull/33151
=> Add manifest permissions.webRequestAuthProvider supported from FF126

css/properties/background-image.json, css/properties/content.json, css/types/image.json
The history of this feature is complicated, with a long history of
prefixed support and recent extened syntax which should also work with
the prefixed form because it's defined as an alias:
https://drafts.csswg.org/css-images-4/#deprecated
This would be nicer with https://github.com/mdn/browser-compat-data/issues/17857
but for now this results in split entries with duplicated notes.
The details:
-webkit-image-set() was implementated in WebKit 536.4 for Safari:
https://github.com/WebKit/WebKit/commit/63ee6e4e5f867a55faedef4a7f02fb1b9775dd7b
https://github.com/WebKit/WebKit/blob/63ee6e4e5f867a55faedef4a7f02fb1b9775dd7b/Source/WebCore/Configurations/Version.xcconfig
It was enabled in WebKit 536.8 for Chromium:
https://github.com/WebKit/WebKit/commit/68a3754b19f8e92fabfc263b17baad33a895bd35 …
=> Update Chrome/Safari data for image-set()

css/properties/font-size-adjust.json
http://software.hixie.ch/utilities/js/live-dom-viewer/?saved=12644 shows that the initial value is none in Firefox 4. In Firefox 3 there was some error running the test, but it must have been supported, as the initial value if nothing else.
=> Mark font-size-adjust:none as supported since Firefox 3

css/properties/background-image.json, css/properties/content.json, css/types/image.json
https://bugzil.la/1832901 is about `content: linear-gradient(...)`, but
`content: image-set(...)` works in Firefox 88 in this test:
https://software.hixie.ch/utilities/js/live-dom-viewer/?saved=12629
That `type()` didn't work in Firefox 88 was confirmed with this test:
https://software.hixie.ch/utilities/js/live-dom-viewer/?saved=12631
Use `partial_implementation` for that single-version issue.
Support for `content: -webkit-image-set()` starting in Firefox 90 was
confirmed with additional manual testing (tweaking above tests).
https://bugzil.la/1696314 is only about the `cursor` property, the
`content` property was fixed in Firefox 113:
https://bugzilla.mozilla.org/show_bug.cgi?id=1684958
The exact scope of the changes in Firefox 113 is hard to discern, but
since `content: image-set(...)` …
=> Correct and simplify Firefox data for image-set()

css/properties/background-image.json, css/properties/content.json, css/types/image.json
This is to be consistent with the Firefox data and with caniuse.com,
which treats Safari 14-16.6 support as partial:
https://caniuse.com/css-image-set
This was implemented in WebKit 616.1.4:
https://github.com/webkit/WebKit/commit/e3554c53fff0e1d9ed207af749cd1dbaf7853300
https://github.com/WebKit/WebKit/blob/e3554c53fff0e1d9ed207af749cd1dbaf7853300/Configurations/Version.xcconfig
That maps to Safari 17.
https://software.hixie.ch/utilities/js/live-dom-viewer/?saved=12651 was
also tested in Safari 16.5 (no support) and 17.3 (supported).
=> Mark support for image-set() in Safari as partial until 17

browsers/samsunginternet_android.json
Add samsung internet 24 and 25.
Manually tested on my phone, no available release notes that I could find.
=> Add latest samsung internet android releases

api/HTMLTemplateElement.json, html/elements/template.json
Originally added in https://github.com/mdn/browser-compat-data/pull/22768 but with Firefox marked as no support.
Per the @openwebdocs BCD collector and https://bugzilla.mozilla.org/show_bug.cgi?id=1880188 it seems to be supported in Firefox 125.
=> Firefox 125 ships shadowrootclonable

css/properties/line-clamp.json
This property is currently in an in-between state, in the progress of being standardized and implemented without a prefix, but still only supported with a prefix in all browsers.
Renaming and using `prefix` aligns with https://caniuse.com/css-line-clamp and will make it possible for web-features to use this BCD entry to represent support of the unprefixed CSS property.
=> Treat -webkit-line-clamp as a prefix of line-clamp

api/MediaDeviceInfo.json
`MediaDeviceInfo` is the type returned by `navigator.mediaDevices.enumerateDevices()`, and that is still marked as supported in Edge 12:
https://github.com/mdn/browser-compat-data/blob/37343292148ae835abff7e2cd722c385293ac784/api/MediaDevices.json#L97-L99
That is supported by this blog post which was published before the release of Edge 12:
https://blogs.windows.com/msedgedev/2015/05/13/announcing-media-capture-functionality-in-microsoft-edge/
Reverts https://github.com/mdn/browser-compat-data/pull/18592.
=> Revert "Update Edge versions for MediaDeviceInfo API"

css/properties/transform-box.json
While it can be used together with 2D transforms (and individual transform properties) it was shipped significantly later than the rest of the feature: https://developer.mozilla.org/en-US/docs/Web/CSS/transform-box#browser_compatibility
=> Remove transform-box from web-features:transforms2d

api/RTCIceCandidate.json
Two links, such as
`"mdn_url": "https://developer.mozilla.org/docs/Web/API/RTCIceCandidateStats/url",` are to wrong object - i..e the corresponding stats object.
Note that the desired object hasn't been documented yet, so I can't link to it.
Note that the stats properties are documented, but are not in BCD. So probably need to be removed from docs. But that's another story.
This came out of https://github.com/mdn/content/issues/33228
=> RTCIceCandidate - incorrect MDN urls to the Stats docs with same name

api/MathMLElement.json, mathml/elements/math.json, mathml/elements/merror.json, mathml/elements/mfrac.json, mathml/elements/mi.json, mathml/elements/mmultiscripts.json, mathml/elements/mn.json, mathml/elements/mo.json, mathml/elements/mover.json, mathml/elements/mpadded.json, mathml/elements/mphantom.json, mathml/elements/mroot.json, mathml/elements/mrow.json, mathml/elements/ms.json, mathml/elements/mspace.json, mathml/elements/msqrt.json, mathml/elements/mstyle.json, mathml/elements/msub.json, mathml/elements/msubsup.json, mathml/elements/msup.json, mathml/elements/mtable.json, mathml/elements/mtd.json, mathml/elements/mtext.json, mathml/elements/mtr.json, mathml/elements/munder.json, mathml/elements/munderover.json, mathml/elements/semantics.json, mathml/global_attributes.json
Computing the status of MathML from BCD proved impractical, and needs
much more work. To avoid confusion, remove the tags which aren't being
used by web-features right now.
=> Remove MathML web-features tags

api/ServiceWorkerGlobalScope.json
The event handler property is in WebKit source and controlled by the
same pref as PushEvent:
https://github.com/WebKit/WebKit/blob/0dd2540f475d5c11b3e0ebc6537052a3803a85b0/Source/WebCore/Modules/push-api/ServiceWorkerGlobalScope%2BPushAPI.idl
https://github.com/WebKit/WebKit/blob/0dd2540f475d5c11b3e0ebc6537052a3803a85b0/Source/WebCore/Modules/push-api/PushEvent.idl
Copy the version and note from PushEvent.
=> Mark the push event supported in Safari iOS (with notes)

api/PushManager.json
PushManager is only supported in workers, and this data should be identical to the parent feature. It's not for Safari, and that's wrong, so just remove the entry.
Note that it might be available in the window context in the future: https://github.com/w3c/push-api/pull/368
=> Remove PushManager "Available in workers"

css/properties/page-break-after.json, css/properties/page-break-before.json
This came up in the course of [defining page break features in web-features](https://github.com/web-platform-dx/web-features/pull/331). caniuse reports partial support due to lack of support in Safari and Firefox.
Tests and test results:
- https://github.com/Fyrd/caniuse/issues/7045#issuecomment-2081627762
Vendor bugs:
- https://bugzil.la/775617
- https://webkit.org/b/34155
- https://github.com/web-platform-dx/web-features/pull/331
=> `page-break-{before,after}: avoid` not supported in Safari and Firefox

api/SharedWorker.json, package-lock.json
sameSiteCookies is a new option for SharedWorker construction that allows a given worker to be restricted to `SameSite=None` cookies even when created in a first-party context. This is important as only workers without access to `SameSite=Lax` and `SameSite=Strict` cookies can be accessed via requestStorageAccess.
This only launched in Chrome: https://chromestatus.com/feature/5175585823522816
Relates to https://github.com/mdn/content/pull/33350 and https://github.com/mdn/mdn/issues/543
=> Add sameSiteCookies option to SharedWorker options

api/Document.json, package-lock.json
types is a new (optional) argument supported by requestStorageAccess to allow non-cookie unpartitioned storage to be requested.
This only launched in Chrome: https://chromestatus.com/feature/5175585823522816
Relates to https://github.com/mdn/content/pull/33391 and https://github.com/mdn/mdn/issues/543
=> Add types argument to requestStorageAccess

api/HTMLTemplateElement.json
Docs for `HTMLTemplateElement.shadowRootMode`, `HTMLTemplateElement.shadowRootDelegatesFocus`, `HTMLTemplateElement.shadowRootClonable` are coming in https://github.com/mdn/content/pull/33325 - this just adds the links.
Related docs work in https://github.com/mdn/content/issues/33160
=> HTMLTemplateElement.shadow RootMode/DelegatesFocus/Clonable link to docs

api/OffscreenCanvasRenderingContext2D.json
In https://github.com/whatwg/html/pull/9979 we removed the `commit()` method from the HTML standards, this (hopefully) marks it as such.
Might be noted that WebKit is in the process of hiding it behind a flag (https://github.com/WebKit/WebKit/pull/27196), but that can probably be handled in a follow-up when that PR is merged.
https://github.com/whatwg/html/pull/9979
=> Deprecate the commit() method

api/Element.json
This adds links to docs for `Element.currentCSSZoom` being written in https://github.com/mdn/content/pull/33427
Related docs work can be tracked in https://github.com/mdn/content/issues/33241
=> Element.currentCSSZoom - add doc link

api/PopStateEvent.json
Update "hasUAVisualTransition" in PopStateEvent to "preview" for Safari.
https://developer.apple.com/documentation/safari-technology-preview-release-notes/stp-release-193
PopStateEvent Commit(https://github.com/WebKit/WebKit/commit/f034bb9b9246d75317a80d37f3f59e6f7520938d)
Enabling Commit(https://github.com/WebKit/WebKit/commit/f876ff89c61f56e2259a2a27e8168defe01f96f8)
=> STP 193 supports api.PopStateEvent.hasUAVisualTransition

api/Window.json
This is the entry point to the API, and the rest of the API was updated in https://github.com/mdn/browser-compat-data/pull/2144.
=> Mark window.speechSynthesis supported since Firefox Android 62

api/Worker.json
This was originally added as unavailable back in 2018 (#3049).  However, testing using the android webview shell shows that it is working fine.
The test I used was:
```
new Worker(URL.createObjectURL(new Blob(["console.log('my name is ' + self.name)"], {type: 'application/javascript'})), {name: "foo"})
```
I ran this is DevTools and it printed `my name is foo`.
https://github.com/emscripten-core/emscripten/pull/21701#discussion_r1566183974
=> Mark Worker `name` option as available under android_webview

api/Worker.json
The compatibility data for the `Worker()` constructor confusingly claimed Safari supported ECMAScript modules but not the `options.type` parameter to specify that a worker is an ECMAScript module. I had a look around, and none of the documentation of Safari adding support for modules (e.g. https://webkit.org/blog/11577/release-notes-for-safari-technology-preview-122/ and https://bugs.webkit.org/show_bug.cgi?id=164860) said they had to be used some way besides `options.type`.
=> Note Safari's support for options.type parameter to Worker()

api/Document.json, api/StorageAccessHandle.json
Everything but SharedWorker is actually supported on Android (just not WebView).
This only launched in Chrome: https://chromestatus.com/feature/5175585823522816
Relates to https://github.com/mdn/content/pull/33391 and https://github.com/mdn/mdn/issues/543
=> Fix android compat for StorageAccessHandle & requestStorageAccess(types) Android compat

api/Bluetooth.json
`Bluetooth.requestDevice()` has some new options - including `options.filters.manufacturerData` and` options.exclusionFilters`. This adds these options as sub features.
There is also an event that was added in 78. There are other events and features in spec but not clear which are implemented and hard to test.
The version information comes from https://developer.chrome.com/docs/capabilities/bluetooth
I'm adding some docs to go with this here https://github.com/mdn/content/pull/32638
=> Bluetooth.requestDevice() options.filters.[manufacturerData/exclusionFilters]

javascript/builtins/FinalizationRegistry.json, javascript/builtins/WeakMap.json, javascript/builtins/WeakRef.json, javascript/builtins/WeakSet.json
Updated info about Deno and Node support for non-registered symbols as `Weak{Map,Set}` keys and as `WeakRef`/`FinalizationRegistry` targets.
I tested with the specified versions, but may well be supported by lower versions than these — not sure how important it is that the version specified is strictly the minimum requirement?
```js
function assert(cond) {
if (!cond) throw '!'
}
const tests = {
WeakMap() {
const wm = new WeakMap()
const key = Symbol()
const val = { data: 1 }
wm.set(key, val)
assert(wm.get(key) === val)
},
WeakSet() {
const ws = new WeakSet()
const key = Symbol()
ws.add(key)
assert(ws.has(key))
},
WeakRef() {
new WeakRef(Symbol())
},
FinalizationRegistry() {
new FinalizationRegistry(() => {}).register(Symbol())
},
}
for (const [name, test] of Object.entries(tests)) {
try { …
```
=> Deno and Node support for non-registered symbols in `Weak{Map,Set,Ref}` and `FinalizationRegistry`

api/RTCRtpTransceiver.json
No spec_urls because of https://github.com/w3c/browser-specs/issues/305#issuecomment-2063511127
Chrome 117: https://chromestatus.com/feature/5680189201711104
=> Add RTP header extension control methods

api/Element.json, api/Sanitizer.json
The HTML sanitizer API was added to chrome and then removed, and added to FF behind a flag. It's marked experimental, which is true, but it is more true to say that the API as documented no longer reflects the spec (non-standard) and it is deprecated. So what this does is make that very clear so that people hopefully don't use it.
Would be even better to remove altogether from BCD and docs, but given our process, this is the best thing we can do to make clear it shouldn't be used.
This came out of https://github.com/mdn/content/pull/33141
=> HTML Sanitizer API - deprecate and non-standard

api/IDBDatabase.json
As part of cleaning up docs in https://github.com/mdn/content/pull/33429 I found some very old FF40 notes. One is still valid - a behind a preference option called readwriteflush, which I have added to BCD. Removed notes are:
> **Note:** In Firefox, if you wish to ensure durability for some reason (e.g. you're storing critical data that cannot be recomputed later) you can force a transaction to flush to disk before delivering the `complete` event by creating a transaction using the experimental (non-standard) `readwriteflush` mode (see {{domxref("IDBDatabase.transaction")}}.)
> This is currently experimental, and can only be used if the `dom.indexedDB.experimental` pref is set to `true` in `about:config`.
Related docs work can be found in https://github.com/mdn/content/issues/33220
FYI …
=> IDBDatabase.transaction() has non standard FF option readwriteflush

css/types/basic-shape.json
May 14, 2024 
Firefox 126 adds support for a new function in the [`<basic-shape>`](https://developer.mozilla.org/en-US/docs/Web/CSS/basic-shape) data type: `shape()`.
The support is currently available behind the preference `layout.css.basic-shape-shape.enabled`, which is enabled by default in Nightly (https://hg.mozilla.org/integration/autoland/file/tip/modules/libpref/init/StaticPrefList.yaml#l8612).
**Related Firefox bugs:**
- [[css-shapes-2] Implement shape() function for clip-path (bug 1823463)](https://bugzilla.mozilla.org/show_bug.cgi?id=1823463)
- [[css-shapes-2] Implement shape() function for offset-path (bug 1884424)](https://bugzilla.mozilla.org/show_bug.cgi?id=1884424)
- [[css-shapes-2] Support interpolation between shape() and path() (bug …
=> [CSS] Firefox 126 adds `shape()` function support

css/properties/mask-image.json, css/properties/mask-position.json, css/properties/mask-repeat.json, css/properties/mask-size.json
This data can't be mirrored, and so was missed in https://github.com/mdn/browser-compat-data/pull/21148.
=> Mark mask-* properties supported in Edge

api/NDEFReader.json
Supporting evidence:
https://chromiumdash.appspot.com/commit/986313551faa8ed05f93296376352d14017f4b7e https://chromestatus.com/feature/5700853265596416
=> Update Chrome version for NDEFReader makeReadOnly()

api/Clipboard.json
FF125 enables [Clipboard.readText()]() in release in https://bugzilla.mozilla.org/show_bug.cgi?id=1877400
Verified using the BCD collector.
Found this as part of https://github.com/mdn/content/issues/33565. Looks like late addition to release or similar.
=> FF125 Clipboard.readText supported

api/BroadcastChannel.json
This PR updates and corrects version values for NodeJS for the `BroadcastChannel` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.10.6), using results collected via [UnJS' runtime-compat project](https://github.com/unjs/runtime-compat).
Additional Notes: Exact version collected from Node docs: https://nodejs.org/docs/v20.12.1/api/globals.html#broadcastchannel
=> Update NodeJS data for BroadcastChannel API

api/CustomEvent.json, browsers/nodejs.json
This PR updates and corrects version values for NodeJS for the `CustomEvent` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.10.6), using results collected via [UnJS' runtime-compat project](https://github.com/unjs/runtime-compat).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/CustomEvent
Additional Notes: Exact versions obtained from Node docs: https://nodejs.org/docs/latest/api/events.html#class-customevent
=> Update NodeJS data for CustomEvent API

http/headers/Attribution-Reporting-Register-Source.json, http/headers/Attribution-Reporting-Register-Trigger.json
The [Attribution Reporting API](https://wicg.github.io/attribution-reporting-api/) had BCD added a already, but we missed out on adding `spec_url`s for the `Attribution-Reporting-Register-Source` and `Attribution-Reporting-Register-Trigger` headers. This PR fixes that.
=> Add `spec_urls` for Attribution Reporting API headers

webextensions/api/management.json
Adds details in support of [Bug 1895341](https://bugzilla.mozilla.org/show_bug.cgi?id=1895341) Add install_type “admin” to the management API. Specifically, it adds BCD for the `install_type` of the management API `ExtensionInfo` type, noting that, prior to Firefox 127, the value `"admin"` wasn't set when the add-on was installed from an enterprise police.
Release notes provided in https://github.com/mdn/content/pull/33714
=> install_type added to management API

api/PerformanceResourceTiming.json
I was trying to figure out some discrepancies between caniuse and BCD on resource timing APIs and discovered some errors in BCD.
Confirmed by manual tests (i.e., comparing the results of https://mdn-bcd-collector.gooborg.com/tests/api/PerformanceResourceTiming in various versions in BrowserStack)
- https://bugzilla.mozilla.org/show_bug.cgi?id=1002855
- https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/35#interfacesapisdom
- https://github.com/web-platform-dx/web-features/pull/1083
=> PerformanceResourceTiming shipped in Firefox 35

javascript/builtins/Set.json
FF127 supports the following Set methods in https://bugzilla.mozilla.org/show_bug.cgi?id=1868423:
- [`Set.prototype.intersection()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set/intersection) 
- [`Set.prototype.union()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set/union) 
- [`Set.prototype.difference()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set/difference) 
- [`Set.prototype.symmetricDifference()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set/symmetricDifference)
- [`Set.prototype.isSubsetOf()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set/isSubsetOf)
- …
=> FF127 TC39 Set methods supported

css/properties/place-items.json, css/properties/place-self.json
[CSS Anchor Positioning](https://www.w3.org/TR/css-anchor-position-1/) is set to be released in Chrome 125 (see the associated [Chrome Status entry](https://chromestatus.com/feature/5124922471874560)).
Most of the BCD for this module has already been added, but I forgot to add data points for `anchor-center` value support on the `place-items` and `place-self` properties. This PR adds the missing data points.
=> Add anchor-center value to place-items and place-self

css/properties/d.json
Updating Safari to "preview" because STP 194 supports the d property.
https://developer.apple.com/documentation/safari-technology-preview-release-notes/stp-release-194
https://github.com/WebKit/WebKit/pull/27133
=> Update d.json STP 194 supports d property in SVG

css/properties/content-visibility.json
This PR updates and corrects version values for Firefox and Firefox Android for the `content-visibility` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.10.6).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/content-visibility
=> Update Firefox data for content-visibility CSS property

javascript/builtins/DataView.json, javascript/builtins/Float16Array.json, javascript/builtins/Math.json
FF127 adds support for [TC39 `Float16Array` proposal](https://github.com/tc39/proposal-float16array) in https://bugzilla.mozilla.org/show_bug.cgi?id=1833647.
This is behind a preference but is also only available in nightly (i.e. you need both). 
As far as I can tell this is not yet implemented by others. 
Note that Chrome clearly has intent to support the use case this was created for in https://chromestatus.com/feature/5180552617656320. Deno and Node JS point to a third party library that does this https://deno.land/x/float16@v3.6.6/index.d.ts (i.e. not yet implemented).
Related docs work can be tracked in https://github.com/mdn/content/issues/33561
=> JavaScript Float16array 

api/Element.json, api/HTMLTemplateElement.json, html/elements/template.json
Chrome 125 adds support for serialiable shadow roots in https://chromestatus.com/feature/5102952270528512 - most of this has been caught before, but we were missing some init values and values for setting this in declaratively created shadow roots.
This is part of https://github.com/mdn/content/issues/32731
=> Ff125 shadowroot serializable

api/Selection.json
FF126 adds `Selection.getComposedRanges()` in nightly, but it also adds some updates to existing APIs:
- `Selection.getComposedRanges()`
- can return multiple ranges, but only in firefox. Spec expects returning 1 range at the moment.
- Added an URL to docs (still being written)
- `Selection.setBaseAndExtent()`  - this will now accept anchorNode and focusNode arguments that reside in different shadow trees, which will set the selection accordingly. 
- `Selection.collapse()` - can now accept a node in any tree, and will collapse the range to that Node.
- `extend()` - This should work as-expected, even if the new focusNode is in a different shadow tree.
There are other features coming but that is what is in now (according to https://bugzilla.mozilla.org/show_bug.cgi?id=1867058#c31)
FYI …
=> Selection updates for parallel APIs ff125

css/types/image.json
Adds the Firefox support for colour space interpolation in gradients.
I used browserstack to find the lowest version where it works with the flag.
A dev confirmed that it will be enabled by default in 127 here: https://bugzilla.mozilla.org/show_bug.cgi?id=1899006#c2
=> Add Firefox support for gradient colour spaces

api/Clipboard.json, api/ClipboardItem.json
FF127 enables `Clipboard.read()`/`write()` and `ClipboardItem` by default in https://bugzilla.mozilla.org/show_bug.cgi?id=1887845.
This changes all the previews to "127" and removes versioning on the notes.
FF127 also enables/implements the `ClipboardItem.supports()` static method for the mandatory MIME types _only_ in https://github.com/mdn/content/issues/33564. Since Chrome supports 2 of the three optional types - `web ` custom types and `image/svg+xml` I've added subfeatures for those two (no one supports the last type, which is a list of URIs). I didn't add a subfeature for the mandatory types, since they are mandatory and should be supported by all.
Related docs work can be tracked in:
- https://github.com/mdn/content/issues/33565 (shipping the API)
- …
=> FF127 clipboard enabled

api/WebGL2RenderingContext.json, api/WebGLRenderingContext.json
The @openwebdocs [BCD collector project](https://github.com/openwebdocs/mdn-bcd-collector) v10.10.6 found new features shipping in Firefox 127 beta which was released last week. Currently, the collector covers about 90% of BCD, so the following list might not be exhaustive. Also, if a feature is in Firefox Nightly only, it is not considered here.
With this PR, BCD considers the following 21 features as shipping in Firefox 127:
- api.Clipboard.read
- api.Clipboard.write
- api.ClipboardItem
- api.ClipboardItem.ClipboardItem
- api.ClipboardItem.getType
- api.ClipboardItem.presentationStyle
- api.ClipboardItem.supports_static
- api.ClipboardItem.types
- api.WebGL2RenderingContext.drawingBufferColorSpace
- api.WebGLRenderingContext.drawingBufferColorSpace
- …
=> Updates for Firefox 127 beta / WebGL drawingBufferColorSpace

api/CountQueuingStrategy.json
This PR updates and corrects version values for Deno for the `CountQueuingStrategy` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.10.6), using results collected via [UnJS' runtime-compat project](https://github.com/unjs/runtime-compat).
Additional Notes: Exact version comes from scouring the API docs: https://deno.land/api@v1.0.0?s=CountQueuingStrategy
=> Update Deno data for CountQueuingStrategy API

api/BroadcastChannel.json
This PR updates and corrects version values for Deno for the `BroadcastChannel` API. This propagates the flag data down to children features, otherwise the collector marks these features as unsupported.
=> Update Deno data for BroadcastChannel API

html/elements/a.json
This PR adds compat data for `implicit rel=noopener on target=_blank` links. The support info comes [from chromestatus](https://chromestatus.com/feature/6140064063029248).
I wasn't able to test it.
=> Update rel=noopener compat data for android webview

api/CompressionStream.json, api/DecompressionStream.json, browsers/nodejs.json
This PR updates and corrects version values for NodeJS for the `CompressionStream.deflate-raw` member of the `CompressionStream` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.10.6), using results collected via [UnJS' runtime-compat project](https://github.com/unjs/runtime-compat).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/CompressionStream/CompressionStream/deflate-raw
Additional Notes: Exact version number was tracked down using local, manual runs.
=> Update NodeJS data for api.CompressionStream.CompressionStream.deflate-raw

docs/data-guidelines/index.md
This PR fixes an issue in the flag data removal guidelines, which is written in a way that implies all conditions must be met.  However, we have been treating the guidelines as _any_ condition may be met, both in manual reviews and in scripts.  This PR fixes the guidelines accordingly.
=> Fix data guidelines for flag data

css/selectors/state.json
Chrome is shipping the updated syntax, the old dashed ident syntax will be deprecated.
https://chromestatus.com/feature/5586433790443520
Is leaving the note the right thing to do here?
=> Adds CSS state for Chrome 125

api/FormData.json
This PR updates and corrects version values for NodeJS for the `FormData` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.10.7).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/FormData
=> Update NodeJS data for FormData API

api/DOMException.json
This PR updates and corrects version values for NodeJS for the `DOMException` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.10.6), using results collected via [UnJS' runtime-compat project](https://github.com/unjs/runtime-compat).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/DOMException
=> Update NodeJS data for DOMException API

scripts/bulk-editor/tags/remove.ts, scripts/bulk-editor/utils.ts
This changes the bulk editor's `remove` command so that specifying target feature IDs is optional. This makes it possible to delete a tag completely, without knowing which features the tag applies to.
Inspired by https://github.com/mdn/browser-compat-data/pull/23188
=> Bulk delete tags

html/elements/iframe.json
Remove allow-downloads-without-user-activation sandbox option. It is not currently supported by any browser. This was implemented in Chrome at one time, but has been removed. No browser seems to support this currently. There is an open issue with a request to implement this, but that does not seem very active.
Related to:
- https://github.com/mdn/browser-compat-data/pull/18862
- https://github.com/mdn/content/pull/33409
=> Remove allow-downloads-without-user-activation

api/BarProp.json, api/Document.json, api/HTMLDocument.json, api/Window.json, http/headers/Cross-Origin-Embedder-Policy.json, http/headers/Cross-Origin-Opener-Policy.json
These were found while trying to map spec URLs to spec in web-specs, as
these URLs aren't in there any longer.
Each URL was loaded in a browser to find the redirected URL and confirm
the target ID still exists.
=> Update HTML spec links that redirect

api/Clipboard.json
The `navigator.clipboard.read()` function accepts an optional `formats` parameter that can be used to pass mime-type which you want to read unsanitized.
Documented here: https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/read#formats
This was added by the Edge team in Chromium and shipped with Edge and Chrome 122.
Chromestatus: https://chromestatus.com/feature/5203909459312640
Bug: https://issues.chromium.org/issues/40204798
=> New unsanitized formats BCD key

api/_globals/crypto.json
This PR updates and corrects version values for NodeJS for the `crypto` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.10.7), using results collected via [UnJS' runtime-compat project](https://github.com/unjs/runtime-compat).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/crypto
Additional Notes: Version number comes from the NodeJS docs: https://nodejs.org/docs/latest/api/webcrypto.html#class-crypto
=> Update NodeJS data for crypto API

api/Performance.json, api/PerformanceResourceTiming.json, api/_globals/performance.json, browsers/nodejs.json
This PR updates and corrects version values for NodeJS for the `Performance` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.10.7), using results collected via [UnJS' runtime-compat project](https://github.com/unjs/runtime-compat).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/Performance
Additional Notes: Exact version numbers were tracked down via the NodeJS docs: https://nodejs.org/docs/v20.13.1/api/perf_hooks.html
=> Update NodeJS data for Performance API

api/SubtleCrypto.json
This PR updates and corrects version values for NodeJS for the `deriveKey` member of the `SubtleCrypto` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.10.7), using results collected via [UnJS' runtime-compat project](https://github.com/unjs/runtime-compat).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/SubtleCrypto/deriveKey
Additional Notes: The version number was obtained from the NodeJS docs: https://nodejs.org/docs/v20.13.1/api/webcrypto.html#subtlederivekeyalgorithm-basekey-derivedkeyalgorithm-extractable-keyusages
=> Update NodeJS data for api.SubtleCrypto.deriveKey

api/Response.json
This PR updates and corrects version values for NodeJS for the `Response` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.10.7), using results collected via [UnJS' runtime-compat project](https://github.com/unjs/runtime-compat).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/Response
Additional Notes: The NodeJS docs didn't include specific version numbers for subfeatures, so they were copied from their parent.
=> Update NodeJS data for Response API

api/Request.json
This PR updates and corrects version values for NodeJS for the `Request` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.10.7), using results collected via [UnJS' runtime-compat project](https://github.com/unjs/runtime-compat).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/Request
Additional Notes: The NodeJS docs don't include version numbers for the subfeatures of the API, so they were simply copied from the parent.
=> Update NodeJS data for Request API

css/types/image.json
This is a continuation of my previous PR #23176 - all the notes there apply here. In my original PR I misunderstood the file, and thought I'd added the syntax support for all gradient types, when in fact I'd only added it for one of them.
See #23176
=> Add misssing Firefox grandient colour space support

api/CSS.json, api/CSSPropertyRule.json, css/at-rules/property.json
The `@property` rule will be supported by Firefox 128 stable.
https://www.mozilla.org/en-US/firefox/128.0a1/releasenotes/
https://bugzilla.mozilla.org/show_bug.cgi?id=1864818
n/a
=> Update firefox compatibility for property at-rule

api/GeolocationPositionError.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `GeolocationPositionError` API. Discrepancies from the collector results had helped me catch these issues, where downstream browsers weren't mirroring, and the `version_removed` was improperly set to the last version of support, not the version it was removed in.
=> Update Chromium data for GeolocationPositionError API

api/GamepadHapticActuator.json
This PR updates and corrects version values for Safari iOS/iPadOS for the `GamepadHapticActuator` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.7.1).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/GamepadHapticActuator
=> Update Safari iOS data for GamepadHapticActuator API

api/WebTransportSendStream.json
This PR adds the missing `getWriter` member of the `WebTransportSendStream` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.8.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/WebTransportSendStream/getWriter
=> Add missing api.WebTransportSendStream.getWriter feature

api/File.json
This PR updates and corrects version values for Firefox Android for the `webkitRelativePath` member of the `File` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.7.1).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/File/webkitRelativePath
Additional Notes: The original data seems to come from the wiki era.
=> Update Firefox Android data for api.File.webkitRelativePath

api/Gamepad.json
This PR updates and corrects version values for Firefox Android for the `displayId` member of the `Gamepad` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.7.1).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/Gamepad/displayId
Additional Notes: Exact version number was mirrored from desktop.
=> Update Firefox Android data for api.Gamepad.displayId

api/HTMLMediaElement.json
This PR updates and corrects version values for Safari iOS/iPadOS for the `preservesPitch` member of the `HTMLMediaElement` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.7.1).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/HTMLMediaElement/preservesPitch
=> Update Safari iOS data for api.HTMLMediaElement.preservesPitch

api/IdentityCredential.json
This PR updates and corrects version values for WebView Android for the `IdentityCredential` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.7.1).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/IdentityCredential
=> Update WebView data for IdentityCredential API

api/LaunchParams.json
This PR updates and corrects version values for Chrome Android for the `LaunchParams` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.7.1).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/LaunchParams
Additional Notes: ChromeStatus doesn't mention an Android release: https://chromestatus.com/feature/5722383233056768
=> Update Chrome Android data for LaunchParams API

api/LaunchQueue.json
This PR updates and corrects version values for Chrome Android for the `LaunchQueue` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.7.1).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/LaunchQueue
Additional Notes: ChromeStatus doesn't mention an Android release: https://chromestatus.com/feature/5722383233056768
=> Update Chrome Android data for LaunchQueue API

api/MediaStream.json
This PR updates and corrects version values for Firefox Android for the `addTrack` member of the `MediaStream` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.7.1).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/MediaStream/addTrack
=> Update Firefox Android data for api.MediaStream.addTrack

api/NavigatorLogin.json
This PR updates and corrects version values for WebView Android for the `NavigatorLogin` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.7.1).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/NavigatorLogin
=> Update WebView data for NavigatorLogin API

api/Navigator.json
This PR updates and corrects version values for Firefox Android for the `Navigator` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.7.1).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/Navigator
=> Update Firefox Android data for Navigator API

api/PublicKeyCredential.json
This PR updates and corrects version values for Safari iOS/iPadOS for the `isConditionalMediationAvailable` static method of the `PublicKeyCredential` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.7.1).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/PublicKeyCredential/isConditionalMediationAvailable_static
=> Update Safari iOS data for api.PublicKeyCredential.isConditionalMediationAvailable_static

api/RTCPeerConnection.json
This PR updates and corrects version values for Safari iOS/iPadOS for the `signalingstatechange_event` member of the `RTCPeerConnection` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.7.1).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/RTCPeerConnection/signalingstatechange_event
=> Update Safari iOS data for api.RTCPeerConnection.signalingstatechange_event

api/WindowClient.json
This PR updates and corrects version values for Safari iOS/iPadOS for the `ancestorOrigins` member of the `WindowClient` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.7.1).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/WindowClient/ancestorOrigins
=> Update Safari iOS data for api.WindowClient.ancestorOrigins

api/Element.json
This PR updates and corrects version values for Safari iOS/iPadOS for the `requestFullscreen.options_navigationUI_parameter` member of the `Element` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.7.1).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/Element/requestFullscreen/options_navigationUI_parameter
Additional Notes: Both iOS and iPadOS results were collected.
=> Update Safari iOS data for api.Element.requestFullscreen.options_navigationUI_parameter

css/properties/box-sizing.json
This PR removes the `padding-box` member of the `box-sizing` CSS property from BCD. Per the [data guidelines](https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines/index.md#removal-of-irrelevant-features), this feature can be considered irrelevant and may be removed from BCD accordingly. Even if the current data suggests that the feature is supported, lack of support has been confirmed by the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.10.7).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/box-sizing/padding-box
=> Remove css.properties.box-sizing.padding-box from BCD

api/Request.json
This PR updates and corrects version values for Chrome and Safari for the `cache.only-if-cached` member of the `Request` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.10.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/Request/cache/only-if-cached
=> Update Chrome/Safari data for api.Request.cache.only-if-cached

css/properties/flex-direction.json
This PR updates and corrects version values for  for the `flex-direction` CSS property. This moves the partial implementation note into the specific values the note is referring to.
=> Update  data for flex-direction CSS property

css/properties/justify-self.json
https://web.dev/learn/css/flexbox?continue=https%3A%2F%2Fweb.dev%2Flearn%2Fcss#why_is_there_no_justify-self_in_flexbox:~:text=as%20a%20group.-,Why%20is%20there%20no%20justify%2Dself%20in%20flexbox%3F,-Flex%20items%20act
so i think here is a mistake, or maybe
=> flex has not justify-self. 

api/SharedStorageWorklet.json
Found by the @openwebdocs [BCD collector project](https://github.com/openwebdocs/mdn-bcd-collector) v10.10.6.
Probably shipped late in the 125 beta cycle and therefore not detected in https://github.com/mdn/browser-compat-data/pull/22924.
Confirmed by https://chromestatus.com/feature/5145686840705024
=> Chrome 125 supports ShareStorageWorklet.{run,selectURL}

css/properties/content.json
Added the release note for alt text of CSS `content` property for firefox
Tested in Firefox nightly 128.0a1
- [MDN Content Issue 33590](https://github.com/mdn/content/issues/33590)
- [Content PR](https://github.com/mdn/content/pull/33834)
- [Firefox Release Note PR](https://github.com/mdn/content/pull/33835)
=> added release details for content property alt text for firefox

css/properties/align-content.json
=> Mark align-content: last baseline as not supported in Chromium

javascript/classes.json
Marks Safari 14-15 as having partial support for public class fields. While they do have a basic implementation, there is a critical bug which leads to exceptions in many cases. The exceptions are especially hard to identify/debug because they are resolved when dev-tools are open.
The bug is resolved in Safari 16.
- Safari bug: https://bugs.webkit.org/show_bug.cgi?id=236843
- `babel/babel` discussion regarding adding 'bugfix' behavior for this issue: https://github.com/babel/babel/issues/14289
=> Update public_class_fields for Safari
