mdn/browser-compat-data

css/properties/initial-letter.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `normal` member of the `initial-letter` CSS property. The data comes from manual testing, running test code through BrowserStack, SauceLabs and custom VMs.
Test Code:
```
CSS.supports('-webkit-initial-letter', 'normal');
```
=> Update Safari data for css.properties.initial-letter.normal

api/SubtleCrypto.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `deriveKey` member of the `SubtleCrypto` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.10.7).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/SubtleCrypto/deriveKey
=> Update Safari data for api.SubtleCrypto.deriveKey

api/Response.json
This PR updates and corrects version values for Firefox and Firefox Android for the `Response.accept_readablestream` member of the `Response` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.10.7).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/Response/Response/accept_readablestream
=> Update Firefox data for api.Response.Response.accept_readablestream

api/Response.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `Response.accept_readablestream` member of the `Response` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.10.7).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/Response/Response/accept_readablestream
=> Update Safari data for api.Response.Response.accept_readablestream

javascript/builtins/DataView.json
This PR updates and corrects version values for Firefox and Firefox Android for the `DataView.sharedarraybuffer_support` member of the `DataView` JavaScript builtin. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.10.7).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/javascript/builtins/DataView/DataView/sharedarraybuffer_support
=> Update Firefox data for javascript.builtins.DataView.DataView.sharedarraybuffer_support

javascript/builtins/WeakMap.json, javascript/builtins/WeakRef.json, javascript/builtins/WeakSet.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `WeakMap`, `WeakRef` and `WeakSet` JavaScript builtins. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.10.7).
Tests Used:
https://mdn-bcd-collector.gooborg.com/tests/javascript/builtins/WeakMap/symbol_as_keys
https://mdn-bcd-collector.gooborg.com/tests/javascript/builtins/WeakRef/symbol_as_target
https://mdn-bcd-collector.gooborg.com/tests/javascript/builtins/WeakSet/symbol_as_keys
=> Update Chromium data for Weak[Map/Ref/Set] JavaScript builtins

javascript/builtins/FinalizationRegistry.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `symbol_as_target` member of the `FinalizationRegistry` JavaScript builtin. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.10.7).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/javascript/builtins/FinalizationRegistry/symbol_as_target
=> Update Chromium data for javascript.builtins.FinalizationRegistry.symbol_as_target

javascript/builtins/Intl/PluralRules.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `PluralRules.PluralRules.options_parameter` member of the `Intl` JavaScript builtin. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.10.7).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/javascript/builtins/Intl/PluralRules/PluralRules/options_parameter
=> Update Chromium data for javascript.builtins.Intl.PluralRules.PluralRules.options_parameter

api/ResizeObserver.json
This PR updates and corrects version values for Chrome and Safari for the `observe.options_box_parameter` member of the `ResizeObserver` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.10.7).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/ResizeObserver/observe/options_box_parameter
Additional Notes: The feature was added in #12373, but no supporting documentation was provided to show the parameter was supported in those browser versions. The collector tests with `content-box` as well.
=> Update Chrome/Safari data for api.ResizeObserver.observe.options_box_parameter

css/properties/white-space-collapse.json
This PR updates and corrects version values for Firefox and Firefox Android for the `white-space-collapse` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.10.7).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/white-space-collapse
=> Update Firefox data for white-space-collapse CSS property

css/types/length.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `cap` member of the `length` CSS value type. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.10.7).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/types/length/cap
=> Update Chromium data for css.types.length.cap

css/types/overflow.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `overlay` member of the `overflow` CSS value type. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.10.7).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/types/overflow/overlay
=> Update Safari data for css.types.overflow.overlay

api/Headers.json
This PR updates and corrects version values for NodeJS for the `iterate_lexicographically` member of the `Headers` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.10.7), using results collected via [UnJS' runtime-compat project](https://github.com/unjs/runtime-compat).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/Headers/iterate_lexicographically
Additional Notes: The exact version number could not be determined and had been guesstimated from Chrome data.
=> Update NodeJS data for api.Headers.iterate_lexicographically

css/selectors/open.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `open` CSS selector. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.10.7).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/selectors/open
=> Update Chromium data for open CSS selector

css/selectors/closed.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `closed` CSS selector. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.10.7).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/selectors/closed
=> Update Chromium data for closed CSS selector

api/Location.json
This PR updates and corrects version values for Deno for the `Location` API. The `runtime-compat-data` project's results stated that Deno did not support this API, but upon further research, it is supported as long as a runtime flag is passed (see https://docs.deno.com/runtime/manual/runtime/location_api#location-api).
=> Update Deno data for Location API

api/Event.json
This PR updates and corrects version values for Deno for the `Event` API. The data comes from manual testing, running test code through BrowserStack, SauceLabs and custom VMs.
Test Code:
```
Event.prototype.returnValue; Event.prototype.srcElement;
```
Additional Notes: These two features aren't mentioned in the Deno API documentation, so version numbers had to be manually tracked down.
=> Update Deno data for Event API

api/Performance.json
This PR updates and corrects version values for Deno for the `Performance` API. The data comes from the Deno docs: https://deno.land/api@v1.2.3?s=Performance
=> Update Deno data for Performance API

api/PerformanceObserver.json
This PR updates and corrects version values for NodeJS for the `PerformanceObserver` API. The data comes from manual testing, running test code through BrowserStack, SauceLabs and custom VMs.
Test Code:
```
const perf = require('node:perf_hooks'); perf.PerformanceObserver.prototype.takeRecords;
```
=> Update NodeJS data for PerformanceObserver API

api/ReadableStream.json
This PR updates and corrects version values for Deno for the `values` member of the `ReadableStream` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.10.7), using results collected via [UnJS' runtime-compat project](https://github.com/unjs/runtime-compat).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/ReadableStream/values
Additional Notes: Exact version was tracked down from the docs: https://deno.land/api@v1.35.0?s=ReadableStream#method_values_6
=> Update Deno data for api.ReadableStream.values

api/Response.json
This PR updates and corrects version values for Deno for the `type` member of the `Response` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.10.7), using results collected via [UnJS' runtime-compat project](https://github.com/unjs/runtime-compat).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/Response/type
Additional Notes: https://deno.land/api@v1.0.0?s=Response#prop_type
=> Update Deno data for api.Response.type

api/CSS.json, api/PaintWorkletGlobalScope.json, css/types/image.json
This PR adds links to the WebKit and Mozilla bug tracker entries for the various CSS Painting API entry points.
There aren't that many places in BCD where these links need to be added: the `CSS.paintWorklet` static property, the `paint()` CSS function, and the `PaintWorkletGlobalScope` object (which is quite limited).
The entry point to load a paint worklet module (`CSS.paintWorklet.addModule`) is not part of the CSS Painting API, it's part of the more general Worklets spec, which supports Audio as well, and which is already implemented in Safari and Firefox anyway.
And then, the directives to actually do the painting from within the worklet are canvas.
These are the bug url I found:
* Firefox: https://bugzil.la/1302328
* Safari: https://webkit.org/b/190217
=> Add Safari and Firefox bug links for the CSS Painting API

css/properties/position-anchor.json
The [CSS Anchor Positioning](https://www.w3.org/TR/css-anchor-position-1/) BCD was added a while ago, but we neglected to add a separate data point for the `auto` value, which isn't really supported right now (see the note).
Also be aware that the spec changed — the value was `implicit`, but it changed to `auto`.
=> Add compat data for position-anchor: auto value

html/elements/fieldset.json, html/elements/form.json, html/elements/li.json, html/elements/meta.json, html/elements/meter.json, html/elements/ol.json, html/elements/optgroup.json, html/elements/option.json, html/elements/output.json, html/elements/progress.json, html/elements/select.json
The URLs were found by following the spec link for the element and
clicking on the attribute.
=> Add spec links for assorted HTML attributes

webextensions/api/tabs.json
Add to note to the `tabs.captureVisibleTab` method in support of [Bug 1784920](https://bugzilla.mozilla.org/show_bug.cgi?id=1784920) Add `activeTab` as permission for `tabs.captureVisibleTab` API
Related content updates in https://github.com/mdn/content/pull/33841
=> Note about activeTab permission for tabs.captureVisibleTab

http/mixed-content.json
Mixed content is content served from a secure context (HTTPS) that references insecure content (HTTP URLs). Historically browsers did nothing. Then some started blocking active content such as scripts/stylesheets, then optionally either displaying, blocking or upgrading images, video and audio to HTTPS if they were HTTP links.
The current spec defines content as blockable and upgradable. Upgradeable is images, videos, audio and gets changed from HTTP to HTTPS urls. This list is expected to be constant or shrink. This more or less matches what Chrome has done since mid 80 versions, and FF does in 127.
This behaviour affects compatibility so belongs in the BCD. I've attempted to capture this. At high level:
- Safari in SOME version started blocking all mixed content, including from file …
=> HTTP Mixed-content - add feature

javascript/builtins/TypedArray.json
These 11 entries are changed by collector results:
https://github.com/openwebdocs/mdn-bcd-results/pull/1098
https://github.com/openwebdocs/mdn-bcd-results/pull/1099
The collector shows no support in Safari 9.1 and support in 10.1, so
source archeology was needed to decide between Safari 10 and 10.1.
The 10 methods `copyWithin()`, `entries()`, `every()`, `fill()`,
`filter()`, `find()`, `findIndex()`, `indexOf()`, `join()`, and `map()`
were added in WebKit 602.1.6:
https://github.com/WebKit/WebKit/commit/881b0bfc93b6e6394676fbf712681792d72b2afa
https://github.com/WebKit/WebKit/blob/881b0bfc93b6e6394676fbf712681792d72b2afa/Source/WebCore/Configurations/Version.xcconfig
(See `JSTypedArrayViewPrototype::finishCreation`.)
The static `of()` was added in WebKit 602.1.7: …
=> Update Safari versions for TypedArray

javascript/builtins/DataView.json, javascript/builtins/Float16Array.json, javascript/builtins/Math.json
This PR updates and corrects version values for Deno for the `getFloat16` member of the `DataView` JavaScript builtin. The data comes from manual testing, running test code through BrowserStack, SauceLabs and custom VMs.
Test Code:
```
DataView.prototype.getFloat16
```
=> Update Deno data for javascript.builtins.DataView.getFloat16

http/data-url.json
This PR updates and corrects version values for all browsers for the `data-url` HTTP feature. This replaces the `true` values with ranges inferred by when the feature was introduced in BCD (#231).
=> Update all browsers data for data-url HTTP feature

api/CSSViewTransitionRule.json, api/CloseWatcher.json, api/GamepadHapticActuator.json, api/GeolocationCoordinates.json, api/GeolocationPosition.json, api/PageSwapEvent.json, api/URL.json, api/VisualViewport.json, api/WebGLObject.json
The @openwebdocs [BCD collector project](https://github.com/openwebdocs/mdn-bcd-collector) v10.10.7 found new features shipping in Chrome 126 beta which was released last week. Currently, the collector covers about 90% of BCD, so the following list might not be exhaustive. Also, if a feature is in Chrome Canary/behind origin trials/enrollment, it is not considered here.
With this PR, BCD considers the following 19 features are marked as shipping in Chrome 126:
- api.CSSViewTransitionRule
- api.CSSViewTransitionRule.navigation
- api.CSSViewTransitionRule.types
- api.CloseWatcher
- api.CloseWatcher.CloseWatcher
- api.CloseWatcher.cancel_event
- api.CloseWatcher.close
- api.CloseWatcher.close_event
- api.CloseWatcher.destroy
- api.CloseWatcher.requestClose
- api.GamepadHapticActuator.effects …
=> Updates for Chrome 126 beta

css/properties/flood-color.json, css/properties/flood-opacity.json, css/properties/lighting-color.json
This PR replaces all instances where Internet Explorer says `true` with `≤11` for the `css/` category, so that we can forbid `true` values in the near future.
=> Set IE "true" to "≤11" for css/

api/WebGL2RenderingContext.json
Adds link in `WebGL2RenderingContext.drawingBufferSpace` entry to the `WebGLRenderingContext.drawingBufferColorSpace` doc on MDN.
Note, `WebGL2RenderingContext` is an extension of `WebGL2RenderingContext` so has all the same methods, but possibly with extra arguments. MDN does not "redocument" these so we have to link here (arguably we should at least list in the top page of `WebGL2RenderingContext` but we don't)
Follows on from #23198
Related docs work can be tracked in https://github.com/mdn/content/issues/33850
=> WebGL2RenderingContext.drawingBufferSpace - mdn link

api/_globals/atob.json, api/_globals/btoa.json, api/_globals/clearInterval.json, api/_globals/clearTimeout.json, api/_globals/setInterval.json, api/_globals/setTimeout.json
This PR adds version numbers for Deno for the `worker_support` features of all the globals.  Considering when support was added into Chrome (and other browsers), it's safe to assume that Deno supported workers since the beginning.
=> Add Deno versions for globals worker support

http/headers/Access-Control-Allow-Headers.json
This PR updates and corrects version values for all browsers for the `Access-Control-Allow-Headers` HTTP header. This sets the mobile browsers to mirror, as it's very likely Chrome Android's support was introduced from the very beginning, and Firefox Android was set to false simply due to the 69-78 release gap.
=> Update all browsers data for Access-Control-Allow-Headers HTTP header

javascript/builtins/RegExp.json
It makes no sense for this to be supported before Symbol.species, and
the collector test shows support in Chrome 51, but not in 50:
https://mdn-bcd-collector.gooborg.com/tests/javascript/builtins/RegExp/@@species
=> Fix Chrome version for RegExp @@species

http/headers/Accept-CH-Lifetime.json
This PR updates and corrects version values for Opera and Opera Android for the `Accept-CH-Lifetime` HTTP header. The entire `Accept-CH` header has Opera Android set to mirror as well, so it only makes sense for this feature to mirror as well.
=> Update Opera data for Accept-CH-Lifetime HTTP header

css/properties/flex-wrap.json, css/properties/flex.json
Firefox Android 52 is from wiki migration:
https://github.com/mdn/browser-compat-data/pull/437
It's implausible that this property alone would be different between
desktop and mobile.
The flex property can also be mirrored and will result only in minor
changes to the notes, the versions are already aligned.
=> Mirror flexbox data for Firefox Android

javascript/builtins/Map.json, javascript/builtins/Promise.json, javascript/builtins/Set.json
Symbol.species is newer than any of these features, and is probably best
thought of as a cross-cutting feature. The BCD entries for @@species on
Array, ArrayBuffer, RegExp, SharedArrayBuffer, and TypedArray aren't
assigned to any web-features feature (but are in a snapshot).
=> Remove @@species from web-features Map/Set/Promise

css/types/color.json
Added firefox support for relative color syntax
Tested in FF Nightly 128
- [Enable relative color syntax on nightly #33517](https://github.com/mdn/content/issues/33517)
- [Firefox Experimental release not PR](https://github.com/mdn/content/pull/34053)
=> added the support for firefox for relative color syntax

css/types/calc.json
CSS [`calc()`](https://developer.mozilla.org/en-US/docs/Web/CSS/calc) function can parse color components in Firefox 127 nightly (`layout.css.relative-color-syntax.enabled`).
- To test: Try the example in the [Using math functions](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_colors/Relative_colors#using_math_functions) section in Firefox 127 beta (behind perf) or in Firefox Nightly.
- Info about Chrome and Safari versions (relative colors): https://groups.google.com/a/mozilla.org/g/dev-platform/c/McZfEwrqce8/m/H_1JuPVAAQAJ
Doc issue tracker: https://github.com/mdn/content/issues/33586
Firefox release note update: https://github.com/mdn/content/pull/34042
Content update: https://github.com/mdn/content/pull/34046
=> Firefox 127: `calc()` can parse color components in Nightly

html/elements/script.json
Update Safari's status for importmap integrity, based on the [Beta announcement](https://www.webkit.org/blog/15443/news-from-wwdc24-webkit-in-safari-18-beta/#:~:text=WebKit%20for%20Safari%2018%20beta%20adds%20support%20for%20subresource%20integrity%20in%20imported%20module%20scripts%2C%20which%20gives%20cryptographic%20assurances%20about%20the%20integrity%20of%20contents%20of%20externally%2Dhosted%20module%20scripts.).
[wpt.fyi shows](https://wpt.fyi/results/import-maps?label=experimental&label=master&aligned) support in Safari Tech Preview 196.
I haven't tested Safari 18 manually, as it requires an OS install AFAICT.
=> Importmap integrity - Update Safari status based on Beta announcements

api/AudioWorkletGlobalScope.json
This PR updates and corrects version values for Firefox Android for the `AudioWorkletGlobalScope` API. Scopes themselves aren't updated by the collector, so the data was pulled from `AudioWorkletNode`.
=> Update Firefox Android data for AudioWorkletGlobalScope API

api/DOMMatrix.json, api/DOMPoint.json, api/DOMRect.json, api/DOMRectReadOnly.json, api/Element.json, api/IntersectionObserver.json, api/MediaStreamTrack.json, api/SubtleCrypto.json, api/VideoPlaybackQuality.json, http/headers/Access-Control-Allow-Methods.json, http/headers/Access-Control-Expose-Headers.json, http/headers/Cross-Origin-Resource-Policy.json, http/headers/Referer.json, svg/global_attributes.json
This PR sets Firefox Android to mirror from its desktop counterpart, when Firefox Desktop is set to 68-79.  This fixes the desync when Firefox Android releases were paused.
=> Set Firefox Android to mirror when Firefox Desktop is 69-78

html/elements/a.json, html/elements/area.json, html/elements/link.json, html/elements/meta.json, html/elements/template.json, html/elements/video.json, http/headers/Access-Control-Allow-Credentials.json, http/headers/Access-Control-Allow-Methods.json, http/headers/Access-Control-Allow-Origin.json, http/headers/Access-Control-Expose-Headers.json, http/headers/Access-Control-Max-Age.json, http/headers/Access-Control-Request-Headers.json, http/headers/Access-Control-Request-Method.json, http/headers/Authorization.json, http/headers/Content-Security-Policy-Report-Only.json, http/headers/Content-Security-Policy.json, http/headers/DNT.json, http/headers/Proxy-Authenticate.json, http/headers/Set-Cookie.json, http/headers/Strict-Transport-Security.json, http/headers/WWW-Authenticate.json, http/headers/X-Content-Type-Options.json, http/headers/X-DNS-Prefetch-Control.json, http/headers/X-Frame-Options.json, http/headers/X-XSS-Protection.json, svg/global_attributes.json
This PR updates a number of features to mirror from upstream when the downstream browsers are set to `true` or `null`, particularly for mobile browsers.  This also handles a few cases where the downstream is clearly incorrect, such as Opera or WebView data.
=> Set downstream browsers to mirror when true/null/inaccurate

css/types/color.json
Notes are originally from https://github.com/mdn/browser-compat-data/pull/21937.
=> Link Chrome and Safari bugs for relative rgb()

css/selectors/active-view-transition-type.json, css/selectors/active-view-transition.json
_(👋  Hi, Chrome DevRel here!)_
This PR introduces to new selectors introduced in View Transitions L2: the `:active-view-transition` and `:active-view-transition-types()` pseudo-class selectors.
This feature shipped to stable in Chrome 125.
There is no documentation on MDN available yet. Documentation on Chrome’s side is to be published on May 16.
Links:
- Spec: https://www.w3.org/TR/css-view-transitions-2/#the-active-view-transition-pseudo
- Spec: https://www.w3.org/TR/css-view-transitions-2/#the-active-view-transition-type-pseudo
- ChromeStatus: https://chromestatus.com/feature/5089552511533056
- CrBug: https://crbug.com/40276317
=> Add selectors introduced by view transition types

api/ChapterInformation.json, api/GPUAdapter.json, api/MediaMetadata.json, api/MutationEvent.json, api/RTCEncodedVideoFrame.json, css/properties/font-size-adjust.json
The @openwebdocs [BCD collector project](https://github.com/openwebdocs/mdn-bcd-collector) v10.10.7 found new features shipping in Chrome 127 beta which was released yesterday. Currently, the collector covers about 90% of BCD, so the following list might not be exhaustive. Also, if a feature is in Chrome Canary/behind origin trials/enrollment, it is not considered here.
With this PR, BCD considers the following 20 features are marked as shipping in Chrome 127:
- api.ChapterInformation
- api.ChapterInformation.artwork
- api.ChapterInformation.startTime
- api.ChapterInformation.title
- api.GPUAdapter.info
- api.MediaMetadata.chapterInfo
- api.MutationEvent (removal)
- api.MutationEvent.attrChange (removal)
- api.MutationEvent.attrName (removal)
- api.MutationEvent.initMutationEvent …
=> Updates for Chrome 127 beta

html/elements/img.json
This PR renames a subfeature of the `usemap` attribute of the `img` tag for clarity.  The original name was `caseless_usemap`, but this doesn't make sense based on its description, so it has been renamed to `case_sensitive`.
=> Rename html.elements.img.usemap.caseless_usemap -> case_sensitive

html/elements/img.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `usemap.caseless_usemap` member of the `img` HTML element. This sets the feature(s) to a version range based upon the date that the feature was added to BCD with the intent of replacing `true` values with ranged values to eliminate `true` values from BCD.
Commit/PR Adding the Feature: #388
=> Update Safari data for html.elements.img.usemap.caseless_usemap

api/NotRestoredReasonDetails.json, api/NotRestoredReasons.json, api/PerformanceNavigationTiming.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `NotRestoredReasons` API and related interfaces/properties/methods. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.10.7).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/NotRestoredReasons
=> Update Chromium data for NotRestoredReasons API

html/elements/input/button.json, html/elements/input/checkbox.json, html/elements/input/file.json, html/elements/input/hidden.json, html/elements/input/image.json, html/elements/input/radio.json, html/elements/input/reset.json, html/elements/input/submit.json, html/elements/input/text.json
This PR updates and corrects version values for Internet Explorer for the `input` HTML element. This sets IE to "≤11" to replace all `true` values with ranged versions.  (Apparently, this was missed in the last migration.)
=> Update IE data for input HTML element

html/elements/input/month.json
This PR updates and corrects version values for Safari iOS/iPadOS for the `type_month` member of the `input` HTML element. This sets the feature(s) to a version range based upon the date that the feature was added to BCD with the intent of replacing `true` values with ranged values to eliminate `true` values from BCD.
Commit/PR Adding the Feature: #2204
=> Update Safari iOS data for html.elements.input.type_month

api/Document.json
Fixes #23354
`Document.parseHTMLUnsafe()` is supported from FF124 but had a bug that meant it wasn't usable until 128. This adds an update to make that visible.
=> FF128 Document.parseHTMLUnsafe support

html/elements/script.json
This PR updates and corrects version values for Opera and Opera Android for the `referrerpolicy` member of the `script` HTML element. This sets the downstream browser(s) to mirror from their upstream counterpart.
=> Update Opera data for html.elements.script.referrerpolicy

html/elements/td.json
This PR updates and corrects version values for Firefox and Firefox Android for the `rowspan.rowspan_zero` member of the `td` HTML element. This sets the feature(s) to a version range based upon the date that the feature was added to BCD with the intent of replacing `true` values with ranged values to eliminate `true` values from BCD.
Commit/PR Adding the Feature: #325
=> Update Firefox data for html.elements.td.rowspan.rowspan_zero

html/elements/th.json
This PR updates and corrects version values for Firefox and Firefox Android for the `rowspan.rowspan_zero` member of the `th` HTML element. This sets the feature(s) to a version range based upon the date that the feature was added to BCD with the intent of replacing `true` values with ranged values to eliminate `true` values from BCD.
Commit/PR Adding the Feature: #325
=> Update Firefox data for html.elements.th.rowspan.rowspan_zero

html/elements/video.json
This PR updates and corrects version values for Opera and Opera Android for the `muted` member of the `video` HTML element. This sets the downstream browser(s) to mirror from their upstream counterpart.
=> Update Opera data for html.elements.video.muted

html/elements/video.json
This PR updates and corrects version values for Safari iOS/iPadOS for the `muted` member of the `video` HTML element. This sets the downstream browser(s) to mirror from their upstream counterpart.
=> Update Safari iOS data for html.elements.video.muted

html/elements/input.json
This PR removes the `x-moz-errormessage` member of the `input` HTML element from BCD. Per the [data guidelines](https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines/index.md#removal-of-irrelevant-features), this feature can be considered irrelevant and may be removed from BCD accordingly. Even if the current data suggests that the feature is supported, lack of support has been confirmed by the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.10.7).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/html/elements/input/x-moz-errormessage
Additional Notes: There is a message about this attribute in the content, but it simply states that it used to exist and was removed, so it doesn't need to be deleted.
=> Remove html.elements.input.x-moz-errormessage from BCD

html/elements/object.json
This PR updates and corrects version values for Chrome and Safari for the `classid` member of the `object` HTML element. This sets the feature(s) to a version range based upon the date that the feature was added to BCD with the intent of replacing `true` values with ranged values to eliminate `true` values from BCD.
Commit/PR Adding the Feature: 3dfd3b0d5e09f8f66d2eef2af939e820bcb1fca3
=> Update Chrome/Safari data for html.elements.object.classid

html/elements/input/range.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `type_range` member of the `input` HTML element. This sets the feature(s) to a version range based upon the date that the feature was added to BCD with the intent of replacing `true` values with ranged values to eliminate `true` values from BCD.
Commit/PR Adding the Feature: #2209
=> Update Chromium data for html.elements.input.type_range

html/elements/base.json
This PR updates and corrects version values for Chrome and Safari for the `href.relative_url` member of the `base` HTML element. This sets the version to be a range corresponding to the date the feature was first tracked in BCD (1e76c2ec4001b790ecfee95815c8b72663e47ee9).
=> Update Chrome/Safari data for html.elements.base.href.relative_url

html/elements/input/tel.json
This PR updates and corrects version values for Firefox and Firefox Android for the `type_tel` member of the `input` HTML element. This sets the feature(s) to a version range based upon the date that the feature was added to BCD with the intent of replacing `true` values with ranged values to eliminate `true` values from BCD.
Commit/PR Adding the Feature: #2226
=> Update Firefox data for html.elements.input.type_tel

html/elements/meta.json
This PR updates and corrects version values for Chrome and Safari for the `http-equiv` member of the `meta` HTML element. This sets the feature(s) to a version range based upon the date that the feature was added to BCD with the intent of replacing `true` values with ranged values to eliminate `true` values from BCD.
Commit/PR Adding the Feature: f14e41f437083c77954e8bcf481998d3c77a851a
=> Update Chrome/Safari data for html.elements.meta.http-equiv

svg/elements/textPath.json, svg/elements/tspan.json, svg/global_attributes.json
It can only be used on SVG `<text>`, `<tspan>`, and `<textPath>`, and
previously `<tref>` which has been removed now.
=> Remove textLength as a global SVG attribute

lint/fix.ts
Thanks to the recent PRs that allow us to fix descriptions automatically, we can now add descriptions automatically when running `npm run fix`. The OWD collector uses this when adding new features (`npm run add-new-bcd` in the collector)
However, the descriptions are added at the end of the support block, so I think we should run `fixPropertyOrder` at the end of the fixing process instead of the beginning to avoid this from happening.
=> Fix property order after adding a description

html/global_attributes.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `contenteditable.plaintext-only` member of the `global_attributes` HTML feature. This sets the feature(s) to a version range based upon the date that the feature was added to BCD with the intent of replacing `true` values with ranged values to eliminate `true` values from BCD.
Commit/PR Adding the Feature: #6117
=> Update Safari data for html.global_attributes.contenteditable.plaintext-only

html/global_attributes.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `global_attributes` HTML feature. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.10.8).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/html/global_attributes
=> Update Safari data for global_attributes HTML feature

html/global_attributes.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `nonce` member of the `global_attributes` HTML feature. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.10.8).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/html/global_attributes/nonce
=> Update Chromium data for html.global_attributes.nonce

html/global_attributes.json
This PR updates and corrects version values for all browsers for the `title.multi-line-support` member of the `global_attributes` HTML feature. This sets the feature(s) to a version range based upon the date that the feature was added to BCD with the intent of replacing `true` values with ranged values to eliminate `true` values from BCD.
Commit/PR Adding the Feature: #1089
=> Update all browsers data for html.global_attributes.title.multi-line-support

api/Blob.json, api/Element.json, api/HTMLMediaElement.json, api/HTMLTemplateElement.json, api/MediaKeys.json, api/PushMessageData.json, api/RTCRtpReceiver.json, api/RTCRtpSender.json, api/RTCRtpTransceiver.json, api/Request.json, api/Response.json, api/ShadowRoot.json, css/properties/align-tracks.json, css/properties/justify-tracks.json, css/types/calc.json, javascript/builtins/ArrayBuffer.json, javascript/builtins/SharedArrayBuffer.json
The @openwebdocs [BCD collector project](https://github.com/openwebdocs/mdn-bcd-collector) v10.10.7 found new features shipping in Firefox 128 beta which was released yesterday. Currently, the collector covers about 90% of BCD, so the following list might not be exhaustive. Also, if a feature is in Firefox Nightly only, it is not considered here.
With this PR, BCD considers the following 37 features as shipping in Firefox 128:
- api.Blob.bytes
- api.CSS.registerProperty_static
- api.CSSPropertyRule
- api.CSSPropertyRule.inherits
- api.CSSPropertyRule.initialValue
- api.CSSPropertyRule.name
- api.CSSPropertyRule.syntax
- api.Element.getHTML
- api.HTMLMediaElement.seekToNextFrame (removal)
- api.HTMLTemplateElement.shadowRootSerializable
- api.MediaKeys.getStatusForPolicy
- …
=> Updates for Firefox 128 beta

http/methods.json
This PR updates and corrects version values for all browsers for the `POST` member of the `methods` HTTP feature. This method comes from the HTTP/1.0 spec, so it's highly unlikely that support was added in any browser version after the first release of browsers.
=> Update all browsers data for http.methods.POST

http/methods.json
This PR updates and corrects version values for all browsers for the `HEAD` member of the `methods` HTTP feature. This method comes from the HTTP/1.0 spec, so it's highly unlikely that support was added in any browser version after the first release of browsers.
=> Update all browsers data for http.methods.HEAD

http/methods.json
This PR updates and corrects version values for all browsers for the `methods` HTTP feature. These methods all come from the HTTP/1.1 spec, so it's highly unlikely that support was introduced later than the first version of browsers.
=> Update all browsers data for methods HTTP feature

mathml/elements/annotation-xml.json, mathml/elements/annotation.json, mathml/elements/mprescripts.json
A while ago we added support for automatically collecting compat data for MathML (https://github.com/openwebdocs/mdn-bcd-collector/issues/503).
I recently fixed a bug with that compat data collection and so our tooling proposes to add these three missing MathML elements for completeness! The MDN docs are for these are inline on the https://developer.mozilla.org/en-US/docs/Web/MathML/Element/semantics and https://developer.mozilla.org/en-US/docs/Web/MathML/Element/mmultiscripts pages and I think that's fine, but having all elements in BCD makes sense to me.
cc @pepelsbey and @fred-wang for review.
=> Add three missing MathML elements

html/global_attributes.json
This PR slightly renames `html.global_attributes.title.multi-line-support` to replace a hyphen with an underscore.
=> Slightly rename html.global_attributes.title.multi-line-support

html/manifest/background_color.json, html/manifest/display.json, html/manifest/icons.json, html/manifest/name.json, html/manifest/short_name.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `manifest` member of the `html` HTML manifest property. This sets the downstream browser(s) to mirror from their upstream counterpart.
=> Update Chromium data for html.manifest

api/MouseEvent.json
This seems to be a non-feature.
I could find no reference to it in a current spec, no open Chromium bugs relating to it, and failed to find evidence of it under inspection in Chrome with the flag turned on.
The docs were removed from MDN in 2022: https://github.com/mdn/content/pull/17743.
The data for this property probably ought to have been removed alongside https://github.com/mdn/browser-compat-data/pull/8442.
=> Remove `api.MouseEvent.region`

webextensions/api/cookies.json
Fixes https://github.com/mdn/browser-compat-data/issues/20853
=> Remove Only supports explicit note on cookies.sameSiteStatus for Safari

http/mixed-content.json
This PR updates and corrects version values for Chrome and Safari for the `mixed-content` HTTP feature. This PR was intended to be a part of the true->ranged project with ranges based upon the commit the feature was added in, but the feature was first added to BCD this year (#23220), so this gives the roughest guess based upon all the sibling data.
=> Update Chrome/Safari data for mixed-content HTTP feature

svg/elements/feMorphology.json
This PR updates and corrects version values for all browsers for the `HTML_elements` member of the `feMorphology` SVG element. This sets the feature(s) to a version range based upon the date that the feature was added to BCD with the intent of replacing `true` values with ranged values to eliminate `true` values from BCD.
Commit/PR Adding the Feature: #1460
=> Update all browsers data for svg.elements.feMorphology.HTML_elements

svg/global_attributes.json
This PR updates and corrects version values for Chrome and Safari for the `svgglobal_attributestransform-origin` feature. This sets the feature(s) to a version range based upon the date that the feature was added to BCD with the intent of replacing `true` values with ranged values to eliminate `true` values from BCD.
Commit/PR Adding the Feature: #6182
=> Update Chrome/Safari data for svgglobal_attributestransform-origin feature

svg/global_attributes.json
This PR updates and corrects version values for all browsers for the `svgglobal_attributespaint-order` feature. This sets the feature(s) to a version range based upon the date that the feature was added to BCD with the intent of replacing `true` values with ranged values to eliminate `true` values from BCD.
Commit/PR Adding the Feature: #3608
=> Update all browsers data for svgglobal_attributespaint-order feature

http/status.json
This PR adds the missing `408` member of the `status` HTTP feature. This fixes #8016, which contains the supporting evidence for this change.
=> Add missing http.status.408 feature

http/headers/Access-Control-Allow-Headers.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `Access-Control-Allow-Headers` HTTP header. This fixes #11232, which contains the supporting evidence for this change.
=> Update Safari data for Access-Control-Allow-Headers HTTP header

http/headers/Access-Control-Allow-Methods.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `wildcard` member of the `Access-Control-Allow-Methods` HTTP header. This fixes #11232, which contains the supporting evidence for this change.
=> Update Safari data for http.headers.Access-Control-Allow-Methods.wildcard

html/elements/textarea.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `maxlength` member of the `textarea` HTML element. This fixes #11988, which contains the supporting evidence for this change.
=> Update Safari data for html.elements.textarea.maxlength

api/SharedWorker.json
This PR adds the missing `SharedWorker.options_type_parameter` member of the `SharedWorker` API. This data is copied from the Worker API.  This fixes #13696.
=> Add missing api.SharedWorker.SharedWorker.options_type_parameter feature

http/headers/Content-Security-Policy.json
This PR migrates the note from https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/form-action to a BCD subfeature.  Fixes #6132.
=> Add subfeature for CSP form-action blocked redirects

css/types/global_keywords.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `revert-layer` member of the `global_keywords` CSS value type. The data comes from manual testing, running test code through BrowserStack, SauceLabs, custom VMs and/or locally.
Test Code: https://wpt.live/css/css-cascade/revert-layer-001.html
Additional Notes: Fixes #16336.
=> Update Chromium data for css.types.global_keywords.revert-layer

css/properties/ruby-align.json
Safari Technology Preview does not support `ruby-align`. Not sure how that got added. Changing "preview" to false.
Here's a test: https://software.hixie.ch/utilities/js/live-dom-viewer/?%3Cstyle%3E%40supports%20(ruby-align%3A%20center)%20%7B%20html%20%7B%20background%3A%20green%3B%20%7D%20%7D%3C%2Fstyle%3E
=> Correct data error for ruby-align

css/types/global_keywords.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `revert-layer` member of the `global_keywords` CSS value type. The data comes from a commit in the browser's source code, mapped to a version number using available tooling or via the commit timestamp.
Commit: https://github.com/WebKit/WebKit/commit/4ef8a3eb4931c9905b7f3f6d4d65f40e7164d20e
Additional Notes: Fixes #20453.
=> Update Safari data for css.types.global_keywords.revert-layer

http/headers/Authorization.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `Digest.SHA-256` member of the `Authorization` HTTP header. This fixes #20812, which contains the supporting evidence for this change.
=> Update Chromium data for http.headers.Authorization.Digest.SHA-256

api/EyeDropper.json
This PR updates and corrects version values for Opera and Opera Android for the `EyeDropper` API. This fixes #16519, which contains the supporting evidence for this change.
=> Update Opera data for EyeDropper API

webextensions/manifest/incognito.json
Address browser compatibility documentation requirements for [Bug 1876924](https://bugzilla.mozilla.org/show_bug.cgi?id=1876924) Treat "incognito":"split" as a warning instead of a hard error
Related MDN changes: https://github.com/mdn/content/pull/33661
=> "incognito": "split" support

api/Navigator.json
This PR updates and corrects version values for WebView Android for the `userAgentData` member of the `Navigator` API. This fixes #22125, which contains the supporting evidence for this change.
=> Update WebView data for api.Navigator.userAgentData

api/RTCDataChannel.json
This PR updates and corrects version values for Safari iOS/iPadOS for the `transferable` member of the `RTCDataChannel` API. This fixes #21989, which contains the supporting evidence for this change.
=> Update Safari iOS data for api.RTCDataChannel.transferable

api/HTMLElement.json
This PR adds the missing `contentEditable.plaintext-only` member of the `HTMLElement` API. This fixes #21957, which contains the supporting evidence for this change.
=> Add missing api.HTMLElement.contentEditable.plaintext-only feature

webextensions/api/action.json, webextensions/api/browserAction.json, webextensions/api/cookies.json, webextensions/api/declarativeNetRequest.json, webextensions/api/extension.json, webextensions/api/extensionTypes.json, webextensions/api/i18n.json, webextensions/api/menus.json, webextensions/api/pageAction.json, webextensions/api/runtime.json, webextensions/api/scripting.json, webextensions/api/tabs.json, webextensions/api/windows.json, webextensions/manifest/action.json, webextensions/manifest/background.json, webextensions/manifest/browser_action.json, webextensions/manifest/commands.json, webextensions/manifest/content_scripts.json, webextensions/manifest/externally_connectable.json, webextensions/manifest/optional_permissions.json, webextensions/manifest/page_action.json, webextensions/manifest/permissions.json
This updates the compat data for Safari Web Extensions in Safari 18, and fixes older info for previous releases.
=> Update web extension compat data for Safari 18 and older releases

api/ChapterInformation.json, api/MediaMetadata.json
In https://github.com/mdn/content/pull/34400, I add documentation for the Media Session API `MediaMetadata` `chapterInfo` functionality.
I saw that the BCD for these features was already added, but there were no MDN URLs. This PR adds the missing MDN URLs.
One small point — the spec URLs look correct, but in the local page previews, the "No specification found" box pops up. I'm not sure what the problem is.
=> Add MDN URLs for chapterInfo features

api/MediaRecorder.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `error_event` member of the `MediaRecorder` API. This fixes #21687, which contains the supporting evidence for this change.
=> Update Chromium data for api.MediaRecorder.error_event

html/manifest/display_override.json
Chrome 126 supports the [`display_override`](https://developer.mozilla.org/en-US/docs/Web/Manifest/display_override) manifest member's [`tabbed`](https://wicg.github.io/manifest-incubations/#dfn-tabbed) value (see the [ChromeStatus emtry](https://chromestatus.com/feature/5128143454076928)).
This PR adds a separate data point for it.
=> Add display_override manifest member tabbed value

webextensions/api/cookies.json
'sameSite' is a property of [cookies.Cookie](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/cookies/Cookie) and doesn't have a dedicated page. Also the link is for the entirely separate [SameSiteStatus](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/cookies/SameSiteStatus) type.
=> Remove erroneous cookies samesite mdn_url

svg/elements/a.json, svg/elements/animate.json, svg/elements/animateMotion.json, svg/elements/animateTransform.json, svg/elements/feImage.json, svg/elements/image.json, svg/elements/linearGradient.json, svg/elements/mpath.json, svg/elements/pattern.json, svg/elements/radialGradient.json, svg/elements/script.json, svg/elements/set.json, svg/elements/textPath.json, svg/elements/use.json, svg/global_attributes.json
The SVG `href` attribute is not a global attribute, it can only be used for certain elements. Remove it from global attribute data and add it to the elements where it is still missing.
None.
- https://github.com/mdn/browser-compat-data/issues/9462
- https://github.com/openwebdocs/mdn-bcd-collector/pull/1474
=> SVG href is not a global attribute

svg/global_attributes.json
SVG presentation attributes can be used on all SVG elements and they are also CSS properties. We have compat data for all them in the css.properties.* tree already. This PR uses the compat data from the css.properties.* tree in svg.global_attributes.* as well. (A lot of them are ranged values but I think that's better than the null values we have now)
None, I'm assuming support is the same. We have always update the data later if we see discrepancies between SVG attribute and CSS property.
https://github.com/mdn/browser-compat-data/issues/9462
=> Update SVG presentation attributes

svg/global_attributes.json
Gone from SVG 2 and I don't see it implemented anywhere.
See also https://github.com/mdn/browser-compat-data/pull/10515 where this should have been deleted, too.
=> Remove SVG color-profile attribute

svg/global_attributes.json
No longer in SVG 2 and not implemented anywhere.
"The only major browser that supported it (ever) was IE10/11"
https://stackoverflow.com/questions/21354116/what-exactly-does-the-enable-background-attribute-do
=> Remove SVG enable-background attribute

svg/global_attributes.json
See https://github.com/WebKit/WebKit/commit/5bfb9619ac7bfcf219019296630a87394d78d98c
=> SVG global xml:space attribute is supported in Chrome 6 and Safari 5

svg/global_attributes.json
Not implemented anywhere (anymore)
- Gecko https://bugzilla.mozilla.org/show_bug.cgi?id=903372 (removed in v66)
- Chromium https://groups.google.com/a/chromium.org/g/blink-dev/c/ZvArHAXyAHM/m/ftybb0waCKYJ, https://issues.chromium.org/issues/40350811 (removed in 2015)
- Safari https://bugs.webkit.org/show_bug.cgi?id=17423 (was never supported)
=> Remove SVG xml:base attribute

api/_globals/createImageBitmap.json
[`createImageBitmap()`](https://developer.mozilla.org/en-US/docs/Web/API/createImageBitmap#imageorientation) takes an `options.imageOrientation` parameter that historically had values `none` and `flipY`. The `none` parameter has been renamed to `from-image` in the spec.
The complication though is that `none` is going to be reused for a different meaning in future. This is not in the spec yet, but is in deno.
What I have done is created subfeatures for `from-image` and `none`. I could also create one for `flipY` that would match the parent - I would like to if that is OK?
`from-image` supports is FF111 from https://bugzilla.mozilla.org/show_bug.cgi?id=1809740, Chrome 112 from  https://chromiumdash.appspot.com/commit/5a0ea7914545c91610c08053dd45d5d97328378a, Safari 16 from …
=> createImageBitmap imageOrientation value from-image supported

api/GPUSupportedLimits.json
The https://developer.mozilla.org/docs/Web/API/GPUSupportedLimits MDN page is not quite conventional as it doesn't create sub pages for all its properties. And that makes sense: the instance properties are more like constants and so they are just documented inline on the page. Our mdn_url linter doesn't know about this, so I'm adding the URLs manually.
=> Add mdn_urls for GPUSupportedLimits properties

api/ResizeObserver.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `observe.options_box_parameter` member of the `ResizeObserver` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.10.9).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/ResizeObserver/observe/options_box_parameter
=> Update Safari data for api.ResizeObserver.observe.options_box_parameter

css/properties/text-transform.json
This PR updates and corrects version values for Firefox and Firefox Android for the `math-auto` member of the `text-transform` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.10.9).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/text-transform/math-auto
=> Update Firefox data for css.properties.text-transform.math-auto

css/properties/white-space-collapse.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `white-space-collapse` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.10.9).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/white-space-collapse
=> Update Safari data for white-space-collapse CSS property

html/global_attributes.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `nonce` member of the `global_attributes` HTML feature. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.10.9).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/html/global_attributes/nonce
=> Update Safari data for html.global_attributes.nonce

api/Window.json
This PR updates and corrects version values for Chrome Android for the `launchQueue` member of the `Window` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.10.9).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/Window/launchQueue
Additional Notes: This fixes #23434.
=> Update Chrome Android data for api.Window.launchQueue

http/headers/Set-Cookie.json
FF128 supports [Cookies Having Independent Partitioned State (CHIPS)](https://developer.mozilla.org/en-US/docs/Web/Privacy/Privacy_sandbox/Partitioned_cookies) in Nightly in https://bugzilla.mozilla.org/show_bug.cgi?id=1898253
This updates the subfeature.
Related docs work done in https://github.com/mdn/content/issues/33996
=> FF128 Set-Cookie partitioned in preview (CHIPS)

javascript/statements.json
This PR updates and corrects version values for Firefox and Firefox Android for the `import.service_worker_support` member of the `statements` JavaScript feature. This fixes #23554 and fixes #23160, which contains the supporting evidence for this change.
Additional Notes: It is worth noting that this feature, and a subfeature of `ServiceWorker` indicating ECMAScript module support, were both added in #19835. It has been confirmed that ECMAScript modules aren't supported in Service Workers in Firefox yet.
=> Update Firefox data for javascript.statements.import.service_worker_support

css/types/image.json
Edge never appears to have never supported a prefix for any `<gradient>` CSS value type.
An abstract type having a prefix doesn't make any sense. Nevertheless, I tested gradients on Edge 18 and 15 and found that prefixes had no effect for `conic-gradient()` or `linear-conic-gradient()` and neither was supported in any case. The other gradients were supported without prefixes.
I believe this be a case of a prefix being wrongly reported, then copied, from IE data.
Discovered in the course of calculating aggregated statuses in web-features https://github.com/web-platform-dx/web-features/pull/1231/files#r1660916516
=> `css.types.image.gradient`: Remove `-ms-` prefix

html/elements/iframe.json
Originally added in 2019 in https://github.com/mdn/browser-compat-data/pull/4089.
I think we can remove this now. The `sandbox="allow-top-navigation-to-custom-protocols"` feature seems like the standardized and more relevant feature in this file.
=> Remove html.elements.iframe.external_protocol_urls_blocked

html/elements/link.json
"Other browsers like Chrome and Safari don’t do anything with the alternative stylesheets."
https://adactio.com/journal/19365
=> Update Safari data for alternate stylesheets

html/elements/track.json
There is no need for this to be its own feature. Let's make it ranged versions for Firefox. Seems to me like it was only a bug in Firefox.
=> Turn html track element settable src into a range for Firefox

http/status.json
Assuming HTTP status 103 is supported in Firefox Android the same way it is supported in Firefox.
Need this data to calculate baseline.
=> Mirror Firefox Android for HTTP 103 status

http/status.json
I'm assuming that this is also supported in the mobile browsers.
Needed to calculate baseline for HTTP status 103.
=> Add mobile browsers to HTTP 103 data

api/HTMLBaseElement.json
FF128 adds support for blocking urls in the [`target`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base#target) attribute of the `<base>` element that have newline, tab or `<` char in https://bugzilla.mozilla.org/show_bug.cgi?id=1835157 (This is to prevent dangling markdown attacks).
This is in chrome 61 (https://chromestatus.com/feature/5735596811091968) and Safari 16 (https://bugs.webkit.org/show_bug.cgi?id=257349)
Related docs work can be tracked in [#33995](https://github.com/mdn/content/issues/33995)
=> FF128 <base> target forbids tab, newline, <

webextensions/manifest/theme.json
This PR removes the unsupported subfeatures of the `theme` Web Extensions manifest property from BCD. Per the [data guidelines](https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines/index.md#removal-of-irrelevant-features), this feature can be considered irrelevant and may be removed from BCD accordingly.  Fixes #22215.
=> Remove subfeatures of theme Web Extensions manifest property from BCD

html/manifest/background_color.json, html/manifest/description.json, html/manifest/display.json, html/manifest/icons.json, html/manifest/id.json, html/manifest/name.json, html/manifest/orientation.json, html/manifest/related_applications.json, html/manifest/scope.json, html/manifest/screenshots.json, html/manifest/short_name.json, html/manifest/start_url.json, html/manifest/theme_color.json
Modified Safari support data for the following Web App Manifest members. Based on release notes and internal review:
`name`, `short_name`, `start_url`, `scope`
- Supported [since iOS 11.3](https://developer.apple.com/library/archive/releasenotes/General/WhatsNewInSafari/Articles/Safari_11_1.html#//apple_ref/doc/uid/TP40014305-CH14-SW1). Support [added for macOS in Safari 17.0.](https://developer.apple.com/videos/play/wwdc2023/10120/)
- rdar://27661063
`display`
- Partially implemented [since iOS 11.3](https://developer.apple.com/library/archive/releasenotes/General/WhatsNewInSafari/Articles/Safari_11_1.html#//apple_ref/doc/uid/TP40014305-CH14-SW1). Support [added for macOS in Safari 17.0.](https://developer.apple.com/videos/play/wwdc2023/10120/)
- rdar://35837993
`theme_color`
- Supported …
=> Updated Safari support for Web App Manifests

api/EventTarget.json
This PR updates and corrects version values for Deno/NodeJS for the `addEventListener.options_parameter.options_passive_parameter_default_true_touch` member of the `EventTarget` API. Deno and NodeJS are runtimes, not browsers, so it wouldn't make much sense for these to ever have support.
=> Remove Deno and NodeJS from api.EventTarget.addEventListener.options_parameter.options_passive_parameter_default_true_touch

css/properties/hanging-punctuation.json
This PR removes the `force-end` member of the `hanging-punctuation` CSS property from BCD. Per the [data guidelines](https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines/index.md#removal-of-irrelevant-features), this feature can be considered irrelevant and may be removed from BCD accordingly. Even if the current data suggests that the feature is supported, lack of support has been confirmed by the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.10.9).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/hanging-punctuation/force-end
=> Remove css.properties.hanging-punctuation.force-end from BCD

css/properties/image-orientation.json
This PR removes the `flip_and_angle` member of the `image-orientation` CSS property from BCD. Per the [data guidelines](https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines/index.md#removal-of-irrelevant-features), this feature can be considered irrelevant and may be removed from BCD accordingly. Even if the current data suggests that the feature is supported, lack of support has been confirmed by the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.10.9).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/image-orientation/flip_and_angle
=> Remove css.properties.image-orientation.flip_and_angle from BCD

css/properties/outline-color.json
This PR removes the `invert` member of the `outline-color` CSS property from BCD. Per the [data guidelines](https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines/index.md#removal-of-irrelevant-features), this feature can be considered irrelevant and may be removed from BCD accordingly. Even if the current data suggests that the feature is supported, lack of support has been confirmed by the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.10.9).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/outline-color/invert
=> Remove css.properties.outline-color.invert from BCD

html/global_attributes.json
This PR updates and corrects version values for Opera and Opera Android for the `spellcheck` member of the `global_attributes` HTML feature. This sets the downstream browser(s) to mirror from their upstream counterpart.
=> Update Opera data for html.global_attributes.spellcheck

svg/elements/textPath.json
This PR updates and corrects version values for IE for the `textLength` member of the `textPath` SVG element. Apparently, this one was missed in the mass conversion of IE=`true` > `≤11`.
=> Update IE data for svg.elements.textPath.textLength

css/at-rules/font-face.json
This PR updates and corrects version values for Firefox and Firefox Android for the `src.tech_keyword` member of the `font-face` CSS at-rule. This fixes #23614, which contains the supporting evidence for this change.
=> Update Firefox data for css.at-rules.font-face.src.tech_keyword

html/elements/time.json
The HTMLTimeElement data was set to 14 based on testing that included Edge 13, so 14 is likely to be correct:
https://github.com/mdn/browser-compat-data/pull/3310 https://github.com/mdn/browser-compat-data/pull/7246
Also, the test for the API creates an element, so it cannot be a dangling interface, support for the element is implied: https://mdn-bcd-collector.gooborg.com/tests/api/HTMLTimeElement
=> Update Edge versions for <time>

api/HTMLElement.json
This replaces https://github.com/mdn/browser-compat-data/pull/23613 
Safari 18.0 adds support for `writingsuggestions` HTML attribute
https://webkit.org/blog/15443/news-from-wwdc24-webkit-in-safari-18-beta/#html
(there's a test in the article)
=> Safari 18.0 adds support for writingsuggestions HTML attribute

api/Document.json, api/XPathEvaluator.json
deprecate `XPathEvaluator.createNSResolver()` and `Document.createNSResolver()`
https://dom.spec.whatwg.org/#dom-xpathevaluatorbase-creatensresolver
Fixes https://github.com/mdn/browser-compat-data/issues/23653
=> Fixes #23653 , deprecate `createNSResolver()`

css/properties/forced-color-adjust.json
This PR updates and corrects version values for Microsoft Edge for the `forced-color-adjust` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.10.9).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/forced-color-adjust
=> Update Edge data for forced-color-adjust CSS property

api/PressureObserver.json
The API was exposed on Android but didn't actually work:
https://groups.google.com/a/chromium.org/g/blink-dev/c/7leKysvPZWk/m/-0fKweJ5AQAJ
=> Mark PressureObserver as not supported on Chrome Android

css/properties/ruby-position.json
This PR removes the `inter-character` member of the `ruby-position` CSS property from BCD. Per the [data guidelines](https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines/index.md#removal-of-irrelevant-features), this feature can be considered irrelevant and may be removed from BCD accordingly. Even if the current data suggests that the feature is supported, lack of support has been confirmed by the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.10.9).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/ruby-position/inter-character
=> Remove css.properties.ruby-position.inter-character from BCD

http/headers/Accept-Encoding.json, http/headers/Accept-Language.json, http/headers/Accept.json, http/headers/Cache-Control.json, http/headers/Connection.json, http/headers/Cookie.json, http/headers/Host.json, http/headers/If-Modified-Since.json, http/headers/If-None-Match.json, http/headers/Referer.json, http/headers/User-Agent.json
This PR sets the version number of various HTTP headers that had been supported since the first versions of browsers.  Support was confirmed via manual testing in Chrome 15, Firefox 3 and Safari 4, checking the developer tools (or using applicable tools when developer tools are not available).
=> Add version numbers for HTTP headers supported since first browsers

webextensions/api/declarativeNetRequest.json
Adds browser compatibility data for the `declarativeNetRequest` type `MAX_NUMBER_OF_DISABLED_STATIC_RULES` addressing the dev–doc-needed request from [Bug 1896628](https://bugzilla.mozilla.org/show_bug.cgi?id=1896628)[DNR] Enforce a limit to the maximum number of static rules disabled individually.
Version information for Chrome and Safari based on [comments](https://github.com/w3c/webextensions/issues/162#issuecomment-2109966158) on Declarative Net Request proposal: disable individual static rules #162 and the Chrome documentation.
Related content change in PR TBC
=> Adds MAX_NUMBER_OF_DISABLED_STATIC_RULES

webextensions/api/runtime.json
Firefox does not support `PlatformNaclArch`. This is already correctly reflected on the `runtime.PlatformInfo` page but is not reflected on the `PlatformNaclArch` page.
There is only a [single occurrence](https://searchfox.org/mozilla-central/search?q=PlatformNaclArch&path=&case=false&regexp=false) of `PlatformNaclArch` in the Firefox codebase which is part of an extension schema which lists it as an unsupported feature.
=> Firefox does not support PlatformNaclArch

svg/elements/feMorphology.json
I should have proposed to delete this in https://github.com/mdn/browser-compat-data/pull/23443 already.
[SVG can be applied to HTML](https://developer.mozilla.org/en-US/docs/Web/SVG/Applying_SVG_effects_to_HTML_content) in many cases, I don't think we should be recording this here.
=> Remove svg.elements.feMorphology.HTML_elements

api/OfflineAudioContext.json
It always rejects:
https://github.com/mozilla/gecko-dev/blob/bb682ab37e12bf256f4180693568bf1325aab2be/dom/media/webaudio/AudioContext.cpp#L1062-L1066
This was first determined by simple testing in Firefox DevTools:
```js
ctx = new OfflineAudioContext(1, 480000, 48000);
ctx.resume();
```
=> Mark OfflineAudioContext resume() not really supported in Firefox

javascript/builtins/BigInt.json, javascript/builtins/Intl/DateTimeFormat.json, javascript/builtins/Intl/NumberFormat.json, javascript/builtins/Temporal.json, javascript/operators/object_initializer.json, javascript/operators/spread.json, lint/linter/test-versions.ts
This PR makes real values for Deno required for the JavaScript category, like NodeJS data.  Since some data for Deno was missing, this also adds the data, either by mirroring from child features or by mirroring loosely based on Chrome versions.
=> Require real values in JavaScript category for Deno

api/BarcodeDetector.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `BarcodeDetector` API. This fixes #22907, which contains the supporting evidence for this change.
=> Update Chromium data for BarcodeDetector API

api/BarcodeDetector.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `BarcodeDetector` API. The data comes from a commit in the browser's source code, mapped to a version number using available tooling or via the commit timestamp.
Commit: https://github.com/WebKit/WebKit/commit/ce99b4d5dd33bd28ffb58899e356841cb5ed7285
Additional Notes: This fixes #22774.
=> Update Safari data for BarcodeDetector API

lint/linter/test-obsolete.ts
This PR enables the obsolete feature linter for the WebDriver category. We have no obsolete features in the category, so this will ensure it remains that way.
=> Enable obsolete feature linter for WebDriver category

browsers/safari.json, browsers/safari_ios.json
This PR sets Safari 17.6 to beta.  This was added by the auto updater script for browser data and marked as the current browser, but it has never been released and the release notes mark it as a beta version.
=> Set Safari 17.6 to beta

api/DOMMatrix.json, api/DOMMatrixReadOnly.json
These properties are documented inline on the interface page and there is no plan to create sub pages for them. The mdn_url linter doesn't know about this, so I'm adding the mdn_urls manually.
=> Add mdn_urls for DOMMatrix properties

api/IntersectionObserverEntry.json
This PR adds the missing `isVisible` member of the `IntersectionObserverEntry` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.11.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/IntersectionObserverEntry/isVisible
=> Add missing api.IntersectionObserverEntry.isVisible feature

api/IntersectionObserver.json
This PR adds the missing features of the `IntersectionObserver` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.11.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/IntersectionObserver
=> Add missing features for IntersectionObserver API

html/elements/button.json, html/elements/link.json, html/elements/meta.json, html/elements/portal.json, html/elements/script.json, html/elements/textarea.json, html/global_attributes.json, http/headers/Accept-CH.json, http/headers/Device-Memory.json, http/status.json
This PR sets downstream browsers (such as Opera Android) to mirror from upstream when the downstream browser is `null`.
=> Mirror Chromium downstream when downstream is null

html/elements/link.json
This PR removes the `methods` member of the `link` HTML element from BCD. Per the [data guidelines](https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines/index.md#removal-of-irrelevant-features), this feature can be considered irrelevant and may be removed from BCD accordingly. Even if the current data suggests that the feature is supported, lack of support has been confirmed by the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.11.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/html/elements/link/methods
=> Remove html.elements.link.methods from BCD

api/ClipboardEvent.json, api/Permissions.json
ClipboardEvent is part of the older API:
https://w3c.github.io/clipboard-apis/#clipboard-event-api
The "clipboard-read" permission was removed from the spec:
https://github.com/w3c/clipboard-apis/pull/132
=> Remove some async clipboard web-features tags

api/Permissions.json
The "clipboard-read" permission was removed from the spec:
https://github.com/w3c/clipboard-apis/pull/132
=> Update spec link/status of clipboard permissions

http/headers/Alt-Svc.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `Alt-Svc` HTTP header. The data comes from a commit in the browser's source code, mapped to a version number using available tooling or via the commit timestamp.
Commit: https://chromiumdash.appspot.com/commit/decead7175be5101f9dbef0fdc387d8a544d299b
=> Update Chromium data for Alt-Svc HTTP header

http/headers/Age.json
This PR updates and corrects version values for all browsers for the `Age` HTTP header. This was suggested to be the first version in all browsers based on https://github.com/mdn/browser-compat-data/pull/23430#discussion_r1670240424.
=> Update all browsers data for Age HTTP header

http/headers/Accept-Ranges.json
This PR updates and corrects version values for all browsers for the `Accept-Ranges` HTTP header. This sets all browsers to their first versions as suggested in https://github.com/mdn/browser-compat-data/pull/23430#discussion_r1670233214.
=> Update all browsers data for Accept-Ranges HTTP header

http/headers/Authorization.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `Authorization` HTTP header. This mirrors Chrome down to Safari.
=> Update Safari data for Authorization HTTP header

api/VTTCue.json
FF127 supports all HTML character references in WebVTT cues in  https://bugzilla.mozilla.org/show_bug.cgi?id=1395924 (from a small subset that were formerly supported in the spec a long time ago).
Safari 17.5 supports all reference according to https://wpt.live/webvtt/parsing/cue-text-parsing/tests/entities.html (on latest iPhone). Safari 17.3 does not, so I have marked as 17.5 support.
Chrome 80 supports all char references but any earlier the tests fail.
I have marked this in VTTCue.text entry. It might also go in the constructor, which can also take the text, but I decided not to - will if you think it needed. This also applies to the WebVTT file format, but that has no BCD entry.
Related docs work tracked in https://github.com/mdn/content/issues/33589
=> FF127 WebVTT Cue text supports all character references

api/Navigator.json
This PR updates and corrects version values for Microsoft Edge for the `share` member of the `Navigator` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.11.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/Navigator/share
=> Update Edge data for api.Navigator.share

api/_globals/createImageBitmap.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `svgimageelement_as_source_image` member of the `createImageBitmap` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.11.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/createImageBitmap/svgimageelement_as_source_image
Additional Notes: The previous version number was based on commit date (https://github.com/mdn/browser-compat-data/pull/22744#discussion_r1567229731).
=> Update Safari data for api.createImageBitmap.svgimageelement_as_source_image

api/Blob.json, api/CloseWatcher.json, api/HTMLElement.json, api/HTMLLinkElement.json, api/NavigationActivation.json, api/NavigationCurrentEntryChangeEvent.json, api/PageRevealEvent.json, api/PageSwapEvent.json, api/PushMessageData.json, api/Request.json, api/Response.json, api/ScrollTimeline.json, api/ViewTimeline.json, api/Window.json, css/properties/anchor-name.json, css/properties/contain-intrinsic-block-size.json, css/properties/contain-intrinsic-inline-size.json, css/properties/inset-area.json, css/properties/position-anchor.json, css/properties/position-visibility.json, css/properties/text-spacing-trim.json, css/types/anchor-size.json, css/types/anchor.json, html/global_attributes.json, lint/linter/test-mdn-urls.ts, webextensions/api/declarativeNetRequest.json
I was wondering why all our newly written pages don't show up with inventory updates 😄 (https://github.com/mdn/browser-compat-data/pull/23723). Turns out I introduced a little bug. This PR fixes it!
=> Fix linter for new mdn_urls

http/headers/Upgrade.json
This PR updates and corrects version values for Microsoft Edge for the `Upgrade` HTTP header. This change was requested in https://github.com/mdn/browser-compat-data/pull/23725#discussion_r1670699268.
=> Update Edge data for Upgrade HTTP header

api/Window.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `scrollTo.options_behavior_parameter` member of the `Window` API. This fixes #22889, which contains the supporting evidence for this change.
=> Update Safari data for api.Window.scrollTo.options_behavior_parameter

html/elements/pre.json
This PR removes the `cols` member of the `pre` HTML element from BCD. Per the [data guidelines](https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines/index.md#removal-of-irrelevant-features), this feature can be considered irrelevant and may be removed from BCD accordingly. Even if the current data suggests that the feature is supported, lack of support has been confirmed by the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.11.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/html/elements/pre/cols
=> Remove html.elements.pre.cols from BCD

javascript/regular_expressions.json
Chrome 125: https://chromestatus.com/feature/5149208388829184
Safari 17: https://developer.apple.com/documentation/safari-release-notes/safari-17-release-notes, https://bugs.webkit.org/show_bug.cgi?id=252553
=> Chrome and Safari ship duplicate named capture groups

svg/elements/a.json, svg/elements/animate.json, svg/elements/animateMotion.json, svg/elements/animateTransform.json, svg/elements/circle.json, svg/elements/clipPath.json, svg/elements/cursor.json, svg/elements/defs.json, svg/elements/ellipse.json, svg/elements/foreignObject.json, svg/elements/g.json, svg/elements/image.json, svg/elements/line.json, svg/elements/mask.json, svg/elements/path.json, svg/elements/pattern.json, svg/elements/polygon.json, svg/elements/polyline.json, svg/elements/rect.json, svg/elements/set.json, svg/elements/svg.json, svg/elements/switch.json, svg/elements/text.json, svg/elements/textPath.json, svg/elements/tref.json, svg/elements/tspan.json, svg/elements/use.json, svg/global_attributes.json
See https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/systemLanguage for a list.
systemLanguage is not globally available to SVG elements. It can only be used with certain (many) SVG elements. The compat differs as support for the various elements on which this attribute lives differs, too.
=> SVG systemLanguage is not a global property

svg/global_attributes.json
Like `systemLanguage` (https://github.com/mdn/browser-compat-data/pull/23732) the `requireFeatures` attribute is not a global attribute. Instead it applies only to the (many) elements that `systemLanguage` applies to as well, so in theory I should have the same PR as `systemLanguage`.
However, 
- requiredFeatures is deprecated and not part of SVG2
- is going to be removed: https://bugs.webkit.org/show_bug.cgi?id=204125, https://issues.chromium.org/issues/40510937
- is already removed in Firefox 69 https://bugzilla.mozilla.org/show_bug.cgi?id=1295404
- it is unclear when or much this is really supported.
I think it is not worth the hassle, so I'm proposing to remove this and be done with this one.
=> Remove SVG requiredFeatures attribute

svg/global_attributes.json
I think this is very fundamental, so I'm making the assumption that the compatibility is the same as html.global_attributes.lang.
=> Update SVG lang, xml:lang global attributes

browsers/opera_android.json
This fixes a copy-paste error when adding Opera Android 83 to the browser data, which is causing issues with updating data from the collector results.
=> Fix engine version for Opera Android 83

api/Clipboard.json
This PR performs two things related to the Clipboard API:
- Cleans up the notes for the read and write methods
- The notes didn't fully follow conventional note style, and used a term that's not well known ("transient activation")
- Additionally, this sets numerous Chromium browsers to mirror from upstream, with the notes being the only difference from existing data
- Adds subfeatures for the various MIME types that the `read` and `write` methods could accept
- This data came straight from the notes themselves
This fixes #7991.
=> Clipboard API: clean up notes and create subfeatures for MIME types

api/Clipboard.json
The notes about version 85 appear to be about this change:
https://chromestatus.com/feature/5767075295395840
However, there is no requirement to use the feature policy or permission
policy, that is only used to constrain a page more than the default,
typically to disallow requesting a permission at all.
It was confirmed that the two permissions go back to Chrome 66, by
testing `navigator.permissions.query({name: "clipboard-read"})` and
"clipboard-write" in DevTools in Chrome 66.
The only remaining noteworthy thing is the behavior around user
activation. The existing claims in the notes weren't double checked,
just carried forward while updating permissions language.
Drive-by: fix surpressed typo in Firefox notes
=> Clarify notes about clipboard permissions

webextensions/api/tabs.json
The definition for `tabs.updated()` uses a notation which is not used anywhere else in BCD (to my knowledge). The notation is not documented in https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines/index.md#parameters-and-parameter-object-features 
This PR changes the entry for `tabs.update()` to use the suggested `<paramName>_<propName>_parameter` notation.
=> Replace propName_value notation by paramName_propName_parameter notation in `tabs.update()`

css/properties/display.json
This PR splits the `display-outside` subfeature of the `display` CSS property into the two individual values.  This is done for many reasons:
- The spec includes a `run-in` value for this type enum, which is not supported in any browsers.
- Splitting them out provides better machine readability.
- Splitting them out also provides better clarity.
=> Replace "display-outside" with individual values

webextensions/api/action.json, webextensions/api/browserAction.json
The properties of the `details` parameter of `action.setIcon()` are currently specified with mixed notations. The suggested notation for such properties is `<paramName>_<propName>_parameter`. 
The `windowId` property is specified as `details_windowId_parameter`, while `imageData` is specified as a flat entry. This is inconsistent.
This PR updates the definition for `imageData` to match the (suggested) notation used by `windowId`.
=> Fix mixed notations for parameter properties of `action.setIcon()`

webextensions/match_patterns.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `match_patterns` Web Extensions feature. This sets the feature(s) to a version range based upon the date that the feature was added to BCD with the intent of replacing `true` values with ranged values to eliminate `true` values from BCD.
Commit/PR Adding the Feature: #2135
=> Update Chromium data for match_patterns Web Extensions feature

http/headers/Downlink.json, http/headers/ECT.json, http/headers/RTT.json
These three headers had the wrong casings. Also, it doesn't look like this is supported in Firefox or Safari (or IE).
=> Rename network quality client hints and update data

http/headers/X-XSS-Protection.json
Safari 5 according to this commit https://github.com/WebKit/WebKit/commit/dcbd95b99711080d37a01ac6af076bd028e1acc6
=> Add Safari version for X-XSS-Protection

http/headers/X-Frame-Options.json
I'm assuming this directive has the same original support as the header itself. Happy to correct it to something else if anyone has further information.
=> Update X-Frame-Options: sameorigin

http/methods.json
This should have never been added IMO.
Original PR: https://github.com/mdn/browser-compat-data/pull/1700
I changed it to NULL as compromise in https://github.com/mdn/browser-compat-data/pull/3297
This also lead to a caniuse issue: https://github.com/Fyrd/caniuse/issues/5964 (I think it would be better if TRACE wasn't on caniuse either).
Fixes https://github.com/mdn/browser-compat-data/issues/1702 (for real)
Needs a content update: Other HTTP method pages also just don't use a compat table, see e.g. https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/PATCH and we should do the same for TRACE.
=> Remove HTTP TRACE method

http/headers/Origin.json
I think this seems original enough to be set to initial browser versions.
=> Update HTTP Origin header

http/headers/Link.json
So this is in Safari 17 per https://github.com/WebKit/WebKit/commit/eeb51f0ea0f0e1f38d9330d3113c5392b6dad50f and https://developer.apple.com/documentation/safari-release-notes/safari-17-release-notes
It is actually part of the Early Hints spec, so I think we want the same compat data as the 103 status. (https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/103). Updated Firefox to match that.
=> Update HTTP Link header

http/headers/Keep-Alive.json
I think this should be the same as the HTTP Connection header and use initial versions. They pretty much work together only
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Keep-Alive
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Connection
=> Update HTTP Keep-Alive header data

http/headers/Content-Disposition.json
I think it is safe to say that this header has been supported since the initial versions of browsers.
=> Update HTTP Content-Disposition header

http/headers/Content-Security-Policy.json
Gone from Safari for a long time, too.
https://bugs.webkit.org/show_bug.cgi?id=220724 
https://wpt.fyi/results/content-security-policy/plugin-types?label=master&label=experimental&aligned
=> Remove plugin-types CSP directive

http/headers/Timing-Allow-Origin.json
This header has been supported with (advanced) support for https://developer.mozilla.org/en-US/docs/Web/API/PerformanceResourceTiming.
=> Update HTTP Timing-Allow-Origin header

api/KeyboardEvent.json
Update the `KeyboardEvent.repeat` data for Chrome since as described in https://github.com/mdn/browser-compat-data/issues/23432 (and https://issues.chromium.org/issues/40940886) the implementation is broken, and can't really be used.
This needs to be updated, so web devs don't waste time on an implementation that cannot work due to well known browser bugs.
As described in the linked issue (and upstream bug), I've created a JSFiddle that shows the issue:
1. See this simple JSFiddle: https://jsfiddle.net/ys6o5tfg/5/
2. Press and hold: ArrowLeft, ArrowUp, ArrowRight (in this order)
3. Release ArrowLeft (while keeping ArrowUp and ArrowRight pressed)
4. See that KEYDOWN ArrowRight is printed in the div (i.e. a keydown event with repeat = false is emitted for ArrowRight)
Fixes #23432
=> Mark Chrome's implementation of KeyboardEvent.repeat as buggy

lint/linter/test-obsolete.ts, lint/linter/test-versions.ts
We've fixed everything up in SVG so let's not regress this. Disallow `true` and `null` values and disallow obsolete features.
=> Only allow real versions and non-obsolete features in svg/

http/headers/Content-Security-Policy.json
Gone for more than two years from all browsers.
=> Remove obsolete referrer CSP directive

http/headers/Cache-Control.json
See https://github.com/WebKit/WebKit/commit/7204cf563e4ef21a7e7b2daeb32050b58c61f05e
Drive-by: Fix a bug number for Firefox.
=> Safari 14 supports Cache-Control: stale-while-revalidate

api/Blob.json, api/PushMessageData.json, api/Request.json, api/Response.json
Not sure how I missed this in https://github.com/mdn/browser-compat-data/pull/23367 but Safari 18 supports the new bytes() methods https://developer.apple.com/documentation/safari-release-notes/safari-18-release-notes
Tested in Version 18.0 (20619.1.20.11.1)
=> Safari 18 supports bytes() method

html/manifest/background_color.json, html/manifest/categories.json, html/manifest/description.json, html/manifest/icons.json, html/manifest/id.json, html/manifest/name.json, html/manifest/orientation.json, html/manifest/prefer_related_applications.json, html/manifest/related_applications.json, html/manifest/scope.json, html/manifest/screenshots.json, html/manifest/share_target.json, html/manifest/short_name.json, html/manifest/start_url.json, html/manifest/theme_color.json
Updating the state of web manifest properties that are used by Firefox for Android.
Members that are parsed by Gecko, but not used by Firefox for Android:
- `description`
- `dir`
- `lang`
- `related_applications`
- `prefer_related_applications`
- `share_target`
Members that are parsed by Gecko, but not used in Firefox and Firefox for Android:
- `id`
- Properties parsed by Gecko and Firefox for Android: https://searchfox.org/mozilla-central/rev/ece43b04e7baa4680dac46a06d5ad42b27b124f4/mobile/android/android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/manifest/WebAppManifestParser.kt#64-78
- Properties parsed only by Gecko: https://searchfox.org/mozilla-central/rev/ece43b04e7baa4680dac46a06d5ad42b27b124f4/dom/manifest/ManifestProcessor.sys.mjs#118
- …
=> Update Firefox for Android web app manifest features

webextensions/api/permissions.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `permissions` Web Extensions interface. This sets the feature(s) to a version range based upon the date that the feature was added to BCD with the intent of replacing `true` values with ranged values to eliminate `true` values from BCD.
Commit/PR Adding the Feature: #220, #226
=> Update Chromium data for permissions Web Extensions interface

css/properties/overflow-x.json, css/properties/overflow-y.json, css/properties/overflow.json
The `overflow`, `overflow-x`, and `overflow-y` CSS properties are documented in BCD as having the `auto` value supported starting from Edge 79, by using the `mirror` keyword to match Chrome.
Knowing that this property:value pair was already supported in IE, and that other values for the same property are also supported starting with Edge 12 (the first Edge ever release), I think using the `mirror` keyword was a mistake.
I tested using `overflow:auto` on Edge 15, by using BrowserStack, and it worked fine. I don't have access to Edge 12, but again, knowing that this was already supported in IE. I'm almost certain this was supported in Edge 12, just like the rest of the `overflow` property.
#23796
=> Fix overflow CSS prop support on Edge

http/headers/Authorization.json, http/headers/WWW-Authenticate.json
For Safari, see https://github.com/WebKit/standards-positions/issues/212
SHA-512 is not supported anywhere, see discussion here: https://groups.google.com/a/chromium.org/g/blink-dev/c/cJH3JJY_tTY/m/0_uCOheRDQAJ
=> Safari doesn't support SHA-256 auth; remove SHA-512 auth

http/headers/SourceMap.json
I couldn't find bugs for Chrome but there is this blog post from 2012: https://developer.chrome.com/blog/sourcemaps. So, I've put version 18 as a guess.
For Safari, I found commits and I'm quite certain about these versions:
- Safari 6: https://github.com/WebKit/WebKit/commit/c07bb31c5c4cbee75a9d9db821554ab583c2390d
- Safari 7: https://github.com/WebKit/WebKit/commit/68ea517a8cd91ca04d7adae50b2817577cda1f0f
=> Update SourceMap HTTP header

http/headers/Retry-After.json
According to https://stackoverflow.com/questions/3764075/retry-after-http-response-header-does-it-affect-anything Chromium does something as of the end of 2012. See also https://chromiumcodereview.appspot.com/11419070. So I'm setting this to version 24 which was released early 2013.
Safari doesn't have "Retry-After" in its code base nor did I see anything on bugs.webkit.org.
=> Update Retry-After HTTP header

http/headers/Content-Security-Policy.json
Safari 11 comes from https://github.com/WebKit/WebKit/commit/ce7a29eceb9193024e3e8ffff394bb743227c880
Chrome 40 comes from the date of https://codereview.chromium.org/570563003/
Chromestatus is wrong https://chromestatus.com/feature/5679927315660800
=> Update CSP manifest-src

http/headers/Content-Security-Policy.json
I think Firefox might be the only outlier for this one and shipped support in the meta tag later. I couldn't find anything for this being the case with the other browsers, so I'm setting the version to when CSP shipped there initially.
=> Update CSP <meta> support

http/headers/Content-Security-Policy.json
It is supported at least from version 56 according to https://chromestatus.com/feature/5679844478156800. Maybe even earlier but I have no other information for now.
=> Chrome supports CSP in workers

http/headers/Content-Security-Policy.json
Firefox removal in 122: https://bugzilla.mozilla.org/show_bug.cgi?id=1806080
Chrome initial support in 44: https://groups.google.com/a/chromium.org/g/blink-dev/c/MafYMJ3zQw0/m/5VDOL9VDpAgJ, https://issues.chromium.org/issues/40398476
Chrome removal: https://issues.chromium.org/issues/40260100
Safari initial support in version 10: https://github.com/WebKit/WebKit/commit/d93030382f776750e627a2376a1c12ad47d93e94
=> Update CSP block-all-mixed-content directive

api/BeforeUnloadEvent.json
Testing of Edge 15 and 18 was done in
https://github.com/openwebdocs/mdn-bcd-collector/issues/1666. Since it's
supported in IE, assume that support goes back to Edge 12 here.
=> Mark BeforeUnloadEvent supported in Edge 12

html/elements/details.json
Support for the `name` attribute on the `<details>` element was added to Firefox 130
https://bugzilla.mozilla.org/show_bug.cgi?id=1856460#c17
=> Add Firefox version for element: details: name

html/elements/rp.json, html/elements/rt.json
They were supported in IE 5, and almost certainly weren't removed in
Edge 12-18.
https://software.hixie.ch/utilities/js/live-dom-viewer/?saved=12892 was
tested in Edge 15 to confirm it renderes as expected.
=> Mark <rp> and <rt> supported in Edge 12

api/Blob.json, browsers/deno.json
Updates `Blob.bytes` compat table to mention Deno v1.45 which ships with it
https://github.com/denoland/deno/pull/24148
https://deno.com/blog/v1.45
n/a
=> Update for Deno v1.45

html/elements/wbr.json
https://software.hixie.ch/utilities/js/live-dom-viewer/?saved=12893 was tested in Edge 15 and IE 11.
It works in Edge 15, but not IE 11.
Not knowing for sure where from Edge 12-15 this was introduced, Edge 12 is the most reasonable guess.
=> Mark <wbr> supported in Edge 12 (most likely)

css/at-rules/document.json
This PR removes the `regexp` member of the `document` CSS at-rule from BCD. Per the [data guidelines](https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines/index.md#removal-of-irrelevant-features), this feature can be considered irrelevant and may be removed from BCD accordingly.
=> Remove css.at-rules.document.regexp from BCD

css/properties/resize.json
This PR updates and corrects version values for Safari iOS/iPadOS for the `resize` CSS property. This fixes #23498, which contains the supporting evidence for this change.
=> Update Safari iOS data for resize CSS property

api/HTMLCanvasElement.json
This PR adds the missing features of the `HTMLCanvasElement` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.11.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/HTMLCanvasElement
=> Add missing features for HTMLCanvasElement API

api/BackgroundFetchRegistration.json
This was overlooked for some reason. It has the same status as the rest of the feature.
=> Tag api.BackgroundFetchRegistration for web-features

api/MediaController.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `MediaController` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.1).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/MediaController
Additional Notes: Safari 6 was confirmed via commit history: https://github.com/WebKit/WebKit/commit/d8366adb2edddfb3fe6271ae97a6524cccac091f.  While this commit includes IDL for many of the other features, the collector didn't confirm support before Safari 8.
=> Update Safari data for MediaController API

api/MIDIInput.json, api/MIDIMessageEvent.json, api/MIDIOutput.json
This PR updates and corrects version values for WebView Android for the `MIDI` APIs. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.1).
Tests Used:
https://mdn-bcd-collector.gooborg.com/tests/api/MIDIInput
https://mdn-bcd-collector.gooborg.com/tests/api/MIDIMessageEvent
https://mdn-bcd-collector.gooborg.com/tests/api/MIDIOutput
=> Update WebView data for MIDI API

api/Gamepad.json
This PR updates and corrects version values for Safari iOS/iPadOS for the `vibrationActuator` member of the `Gamepad` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.1).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/Gamepad/vibrationActuator
Additional Notes: This was confirmed via manual testing, using https://hardwaretester.com/gamepad with both a DualSense and Xbox Wireless controller.
=> Update Safari iOS data for api.Gamepad.vibrationActuator

api/BluetoothRemoteGATTCharacteristic.json
Its inclusion causes a warning in web-features dist file generation. We
cannot deal with deprecated BCD keys yet because by definition
deprecated features cannot be Baseline.
This is the only deprecated BCD key currently tagged for web-features.
=> Remove web-features tag from deprecated Bluetooth writeValue() method

lint/linter/test-links.test.ts, lint/linter/test-links.ts
This PR updates the link linter to handle links from the new Chromium bug tracker under `issues.chromium.org`, which all bugs have been migrated to.
=> Handle new Chromium bug tracker URLs in link shortener

css/properties/position-try-fallbacks.json
As of Chrome 128, the `inset-area()` function has been removed. Moving forward, `inset-area` values are just included directly in the `position-try-fallbacks` list as fallback options.
I wasn't sure of the best way to represent this; please let me know what you think.
=> Change `inset-area()` to `inset-area` in `position-try-fallbacks`

api/Directory.json
This PR updates and corrects version values for Firefox and Firefox Android for the `Directory` API. The data comes from a commit in the browser's source code, mapped to a version number using available tooling or via the commit timestamp.
Commit: https://hg.mozilla.org/mozilla-central/rev/b1c0310cdac10003943ca8f1f176bed8c85c1609, https://hg.mozilla.org/mozilla-central/rev/c050de3408c8992a07299c7da8bd8006d48f8073, https://hg.mozilla.org/mozilla-central/rev/bd1aca23aba6cc93019b9756f27b8079132f627f
=> Update Firefox data for Directory API

css/properties/perspective.json
This PR updates and corrects version values for Safari iOS/iPadOS for the `perspective` CSS property. This fixes #6637, which contains the supporting evidence for this change.
=> Update Safari iOS data for perspective CSS property

html/elements/video.json
This PR updates and corrects version values for Safari iOS/iPadOS for the `autoplay` member of the `video` HTML element. This note is redundant as no browser allows autoplaying an unmuted video.
=> Update Safari iOS data for html.elements.video.autoplay

api/AudioContext.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `AudioContext` API. This fixes #16009, which contains the supporting evidence for this change.
=> Update Safari data for AudioContext API

css/properties/text-combine-upright.json
This PR removes the `digits` member of the `text-combine-upright` CSS property from BCD. Per the [data guidelines](https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines/index.md#removal-of-irrelevant-features), this feature can be considered irrelevant and may be removed from BCD accordingly. Even if the current data suggests that the feature is supported, lack of support has been confirmed by the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.10.9).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/text-combine-upright/digits
=> Remove css.properties.text-combine-upright.digits from BCD

api/CSSPageDescriptors.json, api/CSSStartingStyleRule.json, api/GeolocationCoordinates.json, api/GeolocationPosition.json, api/Navigator.json, api/PerformanceResourceTiming.json, api/RTCDTMFSender.json, api/TextEvent.json, css/at-rules/starting-style.json, css/properties/transition-behavior.json, javascript/builtins/DataView.json, javascript/builtins/Float16Array.json, javascript/builtins/Math.json, javascript/regular_expressions.json
The @openwebdocs [BCD collector project](https://github.com/openwebdocs/mdn-bcd-collector) v10.12.1 found new features shipping in Firefox 129 beta which was released yesterday. Currently, the collector covers about 90% of BCD, so the following list might not be exhaustive. Also, if a feature is in Firefox Nightly only, it is not considered here.
With this PR, BCD considers the following 29 features as shipping in Firefox 129:
- api.CSSPageDescriptors (https://bugzil.la/1890842)
- api.CSSPageDescriptors.margin (https://bugzil.la/1890842)
- api.CSSPageDescriptors.margin-bottom (https://bugzil.la/1890842)
- api.CSSPageDescriptors.margin-left (https://bugzil.la/1890842)
- api.CSSPageDescriptors.margin-right (https://bugzil.la/1890842)
- api.CSSPageDescriptors.margin-top …
=> Updates for Firefox 129 beta

http/headers/Authorization.json, http/headers/WWW-Authenticate.json
From browsing around and reading various bug trackers and stackoverflow threads, these two auth methods are supported in browsers. I saw mentions of this from very early for Firefox and Chrome, slightly later for Safari (hence ≤7) and ≤11 for Internet Explorer because no idea when it was in IE. I'm happy to change this if anyone has better data or pointers.
=> Update HTTP Kerberos/NTLM auth data

lint/linter/test-obsolete.ts, lint/linter/test-versions.ts
We've fixed everything up in HTTP so let's not regress this. Disallow `true` and `null` values and disallow obsolete features.
I think it is okay to have these two as exceptions, but I have no strong feelings. 
'http.headers.Cache-Control.stale-if-error'
'http.headers.Permissions-Policy.battery' 
'http.headers.X-XSS-Protection' Still quite known and used, so I feel like it is important to keep this for a while still.
This PR will pass after https://github.com/mdn/browser-compat-data/pull/23819 is merged.
=> Only allow real versions and non-obsolete features in http/

api/TextEvent.json
`TextEvent` is a legacy event type that was added to the spec because for compat reasons - it predates `beforeinput` and friends which should be used instead.
The spec doesn't go into that detail, but it does state that the event and event interface is obsolete: https://w3c.github.io/uievents/event-algo.html#textevent
This just adds that information.
Related docs work https://github.com/mdn/content/issues/34705
=> TextEvent is deprecated

html/elements/data.json
Changing it to Edge 14 matches HTMLDataElement, and is the only difference between element and API for any browser.
It's not impossible that the element was recognized in some way before Edge 14, but there's no reason to suspect it and do further research.
=> Update Edge support for <data>

javascript/regular_expressions.json, lint/linter/test-spec-urls.ts
This accompanies https://github.com/mdn/content/pull/34863.
I'm unsure about the spec link: tc39 proposals only have a single source of truth at stage 3, which is the PR opened against the main repo. Everyone's using the rendered diff as the point of referenece.
=> Data for stage 3 regexp-modifiers

html/elements/br.json
This can be assumed confidently without testing.
=> Mark <br> supported in Safari 1

html/elements/h1.json, html/elements/h2.json, html/elements/h3.json, html/elements/h4.json, html/elements/h5.json, html/elements/h6.json
This can be assumed confidently without testing.
=> Mark <h1>-<h6> supported in Safari 1

html/elements/i.json, html/elements/u.json
This can be assumed confidently without testing.
=> Mark <i> and <u> supported in Safari 1

html/elements/button.json
This is to have something to pin the web-features support to: https://github.com/web-platform-dx/web-features/pull/1433
No research was done, and attributes are left as ranges since it's likely some of them are more recent.
=> Mark <button> as supported in Safari 1

webassembly/BigInt-to-i64-integration.json, webassembly/mutable-globals.json
Two WebAssembly features had no spec_urls
=> Add spec_urls to wasm features

api/PaintRenderingContext2D.json
`PaintRenderingContext2D` has the same members as https://developer.mozilla.org/docs/Web/API/CanvasRenderingContext2D and so they are all documented under `CanvasRenderingContext2D`. The mdn_url linter cannot know about this, so I'm adding these mdn_urls manually.
=> Add mdn_urls for PaintRenderingContext2D

api/Path2D.json
https://developer.mozilla.org/en-US/docs/Web/API/Path2D has all the Path members from https://developer.mozilla.org/docs/Web/API/CanvasRenderingContext2D and so they are all documented under CanvasRenderingContext2D. The mdn_url linter cannot know about this, so I'm adding these mdn_urls manually.
=> Add mdn_urls for Path2D

api/OffscreenCanvasRenderingContext2D.json
https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvasRenderingContext2D has the same members as           https://developer.mozilla.org/docs/Web/API/CanvasRenderingContext2D and so they are all documented under CanvasRenderingContext2D. The mdn_url linter cannot know about this, so I'm adding these mdn_urls manually.
=> Add mdn_urls for OffscreenCanvasRenderingContext2D

api/CSSPositionTryDescriptors.json
The mdn_url linter cannot know that there won't be no subpages here. Adding the mdn_urls manually pointing to https://developer.mozilla.org/en-US/docs/Web/API/CSSPositionTryDescriptors#instance_properties
=> Add mdn_urls for CSSPositionTryDescriptors

css/at-rules/counter-style.json
Chrome 91 is shown as shipping `api.CSSCounterStyleRule.speakAs`, but the data for `css.at-rules.counter-style.speak-as` says unsupported. This discrepancy looked weird and, upon closer investigation, turned out to be wrong.
I used the manual test (checking the accessibility inspector) and automated test below, in Browserstack.
Tests:
- https://wpt.live/css/css-counter-styles/counter-style-at-rule/speak-as-manual.html
- https://wpt.live/css/css-counter-styles/counter-style-at-rule/speak-as-syntax.html
Also this https://issues.chromium.org/issues/40164365 (unclear why it's still open though).
https://github.com/web-platform-dx/web-features/pull/1400/files#r1680603901
=> `css.at-rules.counter-style.speak-as` is supported in Chrome

html/elements/iframe.json
This was implemented in WebKit 533.3:
https://github.com/WebKit/WebKit/commit/f4228dc0076684651c8b54680db4d1d7b964a321
https://github.com/WebKit/WebKit/blob/f4228dc0076684651c8b54680db4d1d7b964a321/WebCore/Configurations/Version.xcconfig
That maps to Chrome 5 or 6, Safari 5, and iOS 4.2.
Chrome 5 or 6 is ambiguous because the engine version is 533 with no
minor version. Chrome 6 is 534.3, so it was definitely in Chrome 6.
Unlike other sandbox data, mirroring can be used for iOS, as Safari 5
does map to iOS 4.2.
=> Update Chrome/Safari versions for sandbox="allow-top-navigation"

css/properties/filter.json
This was most recently researched and updated here:
https://github.com/mdn/browser-compat-data/issues/18917
https://github.com/mdn/browser-compat-data/pull/21569
These two tests were run in Chrome 88, 89, Edge 18, and Safari 17.5:
https://codepen.io/estelle/pen/rNZNqaK
https://software.hixie.ch/utilities/js/live-dom-viewer/?saved=12923
The filter works in Chrome 89, but not in Chrome 88, Edge 18, or Safari
17.5.
Chrome 89 is confirmed by these additional sources:
https://stackoverflow.com/questions/32567156/why-dont-css-filters-work-on-svg-elements-in-chrome
https://crbug.com/40134524#comment79
Lack of support in Safari is confirmed by these sources:
https://stackoverflow.com/questions/76919922/css-filters-on-svg-elements-not-applied-in-safari …
=> Correct data for CSS filter on SVG elements

html/manifest/display.json
This is an addendum to https://github.com/mdn/browser-compat-data/pull/23661 to update the `display` member support in Firefox desktop.
https://github.com/openwebdocs/project/issues/206#issuecomment-2222830282
=> Update Firefox support for `display` manifest

html/elements/iframe.json
This was implemented in WebKit 537.6:
https://github.com/WebKit/WebKit/commit/73c18e62d7b18a7ad8c626be054f7a3845e53506
https://github.com/WebKit/WebKit/blob/73c18e62d7b18a7ad8c626be054f7a3845e53506/Source/WebCore/Configurations/Version.xcconfig
That maps to Chrome 23 and Safari 7.
Those versions need to be clamped to support for requestPointerLock(),
which is Chrome 22 and Safari 10.1. Pointer lock isn't supported on iOS.
All in all: Chrome 23 and Safari 10.1.
=> Update Chrome/Safari versions for sandbox="allow-pointer-lock"

html/elements/iframe.json
This was implemented in WebKit 535.8:
https://github.com/WebKit/WebKit/commit/78f87065d871ddf0bb9d4c77310f62ae6375df47
https://github.com/WebKit/WebKit/blob/78f87065d871ddf0bb9d4c77310f62ae6375df47/Source/WebCore/Configurations/Version.xcconfig
That maps to Chrome 17 and Safari 6.
The commit message mentions support in IE10, which is confirmed by this
proposal from the time:
https://www.w3.org/html/wg/wiki/ChangeProposals/sandbox_allow_popups
Thus it must have been in Edge 12 as well.
=> Update browser versions for sandbox="allow-popups"

css/selectors/descendant.json
Safari's `A >> B` syntax is gone for a long time and for Chrome, it looks like `A >>> B` is gone, too.
See https://groups.google.com/a/chromium.org/g/blink-dev/c/HX5Y8Ykr5Ns/m/2R_xIkOvCgAJ
=> Remove >> and >>> descendant syntax

scripts/update-browser-releases/firefox.ts
This PR updates the Firefox portion of the browser updater script to ensure that the `"esr"` status is de-prioritized against `"current"`.
=> update-browser-releases: "current" should not become "esr" for Firefox

scripts/update-browser-releases/index.ts, scripts/update-browser-releases/safari.ts
This PR updates the browser release data updater to ignore Safari 17.6.
Safari 17.6 is marked as released in Apple's data, which is causing the updater script to add 17.6 as the current version.  However, this is incorrect; Safari 17.6 has not yet released.
It's possible that we may just go straight into Safari 18, so I have opted to defer to `"preview"` for any features introduced in Safari 17.6 beta.
=> update-browser-releases: Ignore Safari 17.6

javascript/builtins/Intl/Collator.json
This PR adds the missing features of the `Collator.Collator` member of the `Intl` JavaScript builtin. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.11.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/javascript/builtins/Intl/Collator/Collator
=> Add missing features for javascript.builtins.Intl.Collator.Collator

javascript/builtins/Intl/PluralRules.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `PluralRules.PluralRules.options_parameter` member of the `Intl` JavaScript builtin. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.10.9).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/javascript/builtins/Intl/PluralRules/PluralRules/options_parameter
=> Update Safari data for javascript.builtins.Intl.PluralRules.PluralRules.options_parameter

javascript/builtins/Intl/Collator.json
Deno was forgotten in https://github.com/mdn/browser-compat-data/pull/23686 and our linter requires deno nowadays for javascript data. This should fix the failing main branch.
=> Add missing deno data to Collator options

api/SubtleCrypto.json
This PR updates and corrects version values for Firefox and Firefox Android for the `deriveKey.derivedKeyAlgorithm_option_pbkdf2` member of the `SubtleCrypto` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.1).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/SubtleCrypto/deriveKey/derivedKeyAlgorithm_option_pbkdf2
Additional Notes: The conversation in the linked bug, which is now closed as RESOLVED INVALID, confirms that the collector's results are accurate.
=> Update Firefox data for api.SubtleCrypto.deriveKey.derivedKeyAlgorithm_option_pbkdf2

api/CSSPageRule.json
FF129 Adds support for [`CSSPageRule.style`](https://developer.mozilla.org/en-US/docs/Web/API/CSSPageRule/style) being a [`CSSPageDescriptors`](https://developer.mozilla.org/en-US/docs/Web/API/CSSPageDescriptors) (as per current spec) rather than a [`CSSStyleDeclaration`](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleDeclaration).
As far as I can tell there isn't really any compatibility issue with this right now, because `CSSStyleDeclaration` has getters and setters to set the same properties. However there could well be in future, because `CSSPageDescriptors` is likely to evolve separately. Right now the only benefit I can see is that it is possible to identify the Web object that corresponds to the `@page` CSS because it has a different type.
This follows on from #23730 …
=> FF129 CSSPageRule.style derives from CSSPageDescriptors

api/Scheduler.json
Document FF bug related to enabling Task Scheduler API
https://bugzilla.mozilla.org/show_bug.cgi?id=1795625
N/A
=> Document FF bug related to enabling Task Scheduler API

html/elements/iframe.json
It landed in the WebKit main branch here:
https://github.com/WebKit/WebKit/commit/f8f6da20d5073dc5050556c3f4e1c6f8007b2b13
However, Originally-landed-as point to this commit:
https://github.com/WebKit/WebKit/commit/9d46b7777bca2b36c82f040065e3d7953f8f782d https://github.com/WebKit/WebKit/blob/9d46b7777bca2b36c82f040065e3d7953f8f782d/Configurations/Version.xcconfig
Going by the date (2023-07-13) and WebKit version (616.1.24) Safari 17 is the most likely correct version.
It's not mentioned in the release notes, and no testing was done to confirm support.
=> Mark sandbox="allow-downloads" support in Safari

api/AudioContext.json, api/CaretPosition.json, api/Document.json, api/Element.json, api/ElementInternals.json, api/MediaSession.json, api/PageRevealEvent.json, api/PageSwapEvent.json, api/PointerEvent.json, css/properties/ruby-align.json, javascript/builtins/Promise.json
The @openwebdocs [BCD collector project](https://github.com/openwebdocs/mdn-bcd-collector) v10.10.12 found new features shipping in Chrome 128 beta which was released yesterday. Currently, the collector covers about 90% of BCD, so the following list might not be exhaustive. Also, if a feature is in Chrome Canary/behind origin trials/enrollment, it is not considered here.
With this PR, BCD considers the following 20 features as shipping in Chrome 128:
- api.CaretPosition
- api.CaretPosition.getClientRect
- api.CaretPosition.offset
- api.CaretPosition.offsetNode
- api.Document.caretPositionFromPoint
- api.Element.ariaColIndexText
- api.Element.ariaRowIndexText
- api.Element.currentCSSZoom
- api.ElementInternals.ariaColIndexText
- api.ElementInternals.ariaRowIndexText
- …
=> Updates for Chrome 128 beta

html/elements/iframe.json
Even if the token is parsed, it has no effect since the pointer lock API isn't supported: https://developer.mozilla.org/en-US/docs/Web/API/Element/requestPointerLock#browser_compatibility
=> Mark sandbox="allow-pointer-lock" not supported on iOS

css/properties/hyphens.json
Update hyphens.json to indicate that Czech/Slovak hyphenation patterns are added in Firefox 130.
See https://bugzilla.mozilla.org/show_bug.cgi?id=1908931 for the Firefox bug where this change landed.
=> Update CSS `hyphens: auto` language support

api/Gamepad.json
`vibrationActuator` was added as part of https://github.com/w3c/gamepad/pull/190 and can now be found at https://w3c.github.io/gamepad/#gamepad-interface
=> `vibrationActuator` is now part of the Gamepad API spec

api/MediaCapabilities.json
FF129 Adds support for using [`MediaCapabilities.decodingInfo()`](https://developer.mozilla.org/en-US/docs/Web/API/MediaCapabilities/decodingInfo) with encoded media in https://bugzilla.mozilla.org/show_bug.cgi?id=1898344
The spec is a bit messy, but what it means is that 
- the `configuration` object passed to the `decodingInfo()` method has a new property called `keySystemConfiguration`.
- The returned promise resolves to include the property `keySystemAccess` which is a `MediaKeySystemAccess` you can use to get keys and decode the content for playback. 
What I have done is added a subfeature under `decodingInfo()`  for the `keySystemConfiguration` parameter. I haven't added another subfeature for the  `keySystemAccess` in the returned object - should I add that too, even though it …
=> FF129 MediaCapabilities.decodingInfo() - encrypted content

webextensions/api/windows.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `update` member of the `windows` Web Extensions interface. This sets the feature(s) to a version range based upon the date that the feature was added to BCD with the intent of replacing `true` values with ranged values to eliminate `true` values from BCD.
Commit/PR Adding the Feature: #262, #307
=> Update Chromium data for webextensions.api.windows.update

webextensions/api/windows.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `getAll.populate` member of the `windows` Web Extensions interface. This sets the feature(s) to a version range based upon the date that the feature was added to BCD with the intent of replacing `true` values with ranged values to eliminate `true` values from BCD.
Commit/PR Adding the Feature: #262
=> Update Chromium data for webextensions.api.windows.getAll.populate

webextensions/api/windows.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `WindowType` member of the `windows` Web Extensions interface. This sets the feature(s) to a version range based upon the date that the feature was added to BCD with the intent of replacing `true` values with ranged values to eliminate `true` values from BCD.
Commit/PR Adding the Feature: #262
=> Update Chromium data for webextensions.api.windows.WindowType

webextensions/api/windows.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `WindowState` member of the `windows` Web Extensions interface. This sets the feature(s) to a version range based upon the date that the feature was added to BCD with the intent of replacing `true` values with ranged values to eliminate `true` values from BCD.
Commit/PR Adding the Feature: #262
=> Update Chromium data for webextensions.api.windows.WindowState

webextensions/api/windows.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `Window` member of the `windows` Web Extensions interface. This sets the feature(s) to a version range based upon the date that the feature was added to BCD with the intent of replacing `true` values with ranged values to eliminate `true` values from BCD.
Commit/PR Adding the Feature: #307
=> Update Chromium data for webextensions.api.windows.Window

webextensions/api/webRequest.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `RequestFilter.windowId` member of the `webRequest` Web Extensions interface. This sets the feature(s) to a version range based upon the date that the feature was added to BCD with the intent of replacing `true` values with ranged values to eliminate `true` values from BCD.
Commit/PR Adding the Feature: #469
=> Update Chromium data for webextensions.api.webRequest.RequestFilter.windowId

webextensions/api/windows.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `Window.incognito` member of the `windows` Web Extensions interface. This sets the feature(s) to a version range based upon the date that the feature was added to BCD with the intent of replacing `true` values with ranged values to eliminate `true` values from BCD.
Commit/PR Adding the Feature: #263
=> Update Chromium data for webextensions.api.windows.Window.incognito

webextensions/api/webRequest.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `onAuthRequired.details.url` member of the `webRequest` Web Extensions interface. This sets the feature(s) to a version range based upon the date that the feature was added to BCD with the intent of replacing `true` values with ranged values to eliminate `true` values from BCD.
Commit/PR Adding the Feature: #5757
=> Update Chromium data for webextensions.api.webRequest.onAuthRequired.details.url

http/status.json
Chrome and Safari only support 103 Early Hints over HTTP/2 or above.
Firefox supports it over HTTP/1.1 as well [though say they might change that](https://github.com/whatwg/fetch/issues/1698#issuecomment-1704907061) - CC: @valenting in case any update here.
This used to be clearly defined in BCD data, but was updated in #21083 and the note about Chrome was removed, and now it only shows a note for Safari under `rel=preconnect`:
This is incorrect to me. Chrome has similar restrictions to Safari (for both preconnect and preload), and Safari restricts all of 103, and not just preconnects (though admittedly that is the only type Safari supports so they are kind of equivalent).
So I think this restriction should be under the main 103 entry (rather than just `rel=preconnect`) and should be the …
=> Note which browsers only support 103 Early Hints over HTTP/2 or above

webextensions/api/webRequest.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `RequestFilter.view-source` member of the `webRequest` Web Extensions interface. This sets the feature(s) to a version range based upon the date that the feature was added to BCD with the intent of replacing `true` values with ranged values to eliminate `true` values from BCD.
Commit/PR Adding the Feature: #8708
=> Update Chromium data for webextensions.api.webRequest.RequestFilter.view-source

webextensions/api/webRequest.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `RequestFilter.urls` member of the `webRequest` Web Extensions interface. This sets the feature(s) to a version range based upon the date that the feature was added to BCD with the intent of replacing `true` values with ranged values to eliminate `true` values from BCD.
Commit/PR Adding the Feature: #389
=> Update Chromium data for webextensions.api.webRequest.RequestFilter.urls

webextensions/api/webNavigation.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `TransitionType` member of the `webNavigation` Web Extensions interface. This sets the feature(s) to a version range based upon the date that the feature was added to BCD with the intent of replacing `true` values with ranged values to eliminate `true` values from BCD.
Commit/PR Adding the Feature: #3132
=> Update Chromium data for webextensions.api.webNavigation.TransitionType

webextensions/api/windows.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `create.createData` member of the `windows` Web Extensions interface. This sets the feature(s) to a version range based upon the date that the feature was added to BCD with the intent of replacing `true` values with ranged values to eliminate `true` values from BCD.
Commit/PR Adding the Feature: #456
=> Update Chromium data for webextensions.api.windows.create.createData

webextensions/api/privacy.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `network` member of the `privacy` Web Extensions interface. This sets the feature(s) to a version range based upon the date that the feature was added to BCD with the intent of replacing `true` values with ranged values to eliminate `true` values from BCD.
Commit/PR Adding the Feature: #364
=> Update Chromium data for webextensions.api.privacy.network

webextensions/api/privacy.json
This PR updates and corrects version values for Opera and Opera Android for the `services` member of the `privacy` Web Extensions interface. This sets the downstream browser(s) to mirror from their upstream counterpart.
=> Update Opera data for webextensions.api.privacy.services

webextensions/api/pageAction.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `onClicked.tab` member of the `pageAction` Web Extensions interface. This sets the feature(s) to a version range based upon the date that the feature was added to BCD with the intent of replacing `true` values with ranged values to eliminate `true` values from BCD.
Commit/PR Adding the Feature: #5285
=> Update Chromium data for webextensions.api.pageAction.onClicked.tab

webextensions/api/notifications.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `NotificationOptions` member of the `notifications` Web Extensions interface. This sets the feature(s) to a version range based upon the date that the feature was added to BCD with the intent of replacing `true` values with ranged values to eliminate `true` values from BCD.
Commit/PR Adding the Feature: #1631
=> Update Chromium data for webextensions.api.notifications.NotificationOptions

schemas/compat-data-schema.md, schemas/compat-data.schema.json
This PR updates the schema and docs to properly state what experimental status means in BCD.  This fixes #23968.
=> Update documentation about experimental status

.github/ISSUE_TEMPLATE/data-problem.yml
This PR adds a line item to the data problem issue template mentioning best practices for code examples.  This was primarily inspired by a recent issue where a code example was written in TypeScript rather than JavaScript, which added an extra step when assisting the reporter.
=> Mention best practices for code examples in data issues

webextensions/api/notifications.json
This PR updates and corrects version values for Opera and Opera Android for the `TemplateType` member of the `notifications` Web Extensions interface. This sets the downstream browser(s) to mirror from their upstream counterpart.
=> Update Opera data for webextensions.api.notifications.TemplateType

webextensions/api/extension.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `getViews.windowId` member of the `extension` Web Extensions interface. This sets the feature(s) to a version range based upon the date that the feature was added to BCD with the intent of replacing `true` values with ranged values to eliminate `true` values from BCD.
Commit/PR Adding the Feature: #12246
=> Update Chromium data for webextensions.api.extension.getViews.windowId

webextensions/api/i18n.json
This PR updates and corrects version values for Opera and Opera Android for the `getUILanguage` member of the `i18n` Web Extensions interface. This sets the downstream browser(s) to mirror from their upstream counterpart.
=> Update Opera data for webextensions.api.i18n.getUILanguage

webextensions/api/events.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `Event` member of the `events` Web Extensions interface. This sets the feature(s) to a version range based upon the date that the feature was added to BCD with the intent of replacing `true` values with ranged values to eliminate `true` values from BCD.
Commit/PR Adding the Feature: #1686
=> Update Chromium data for webextensions.api.events.Event

webextensions/api/devtools.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `panels.ExtensionPanel.onSearch` member of the `devtools` Web Extensions interface. This sets the feature(s) to a version range based upon the date that the feature was added to BCD with the intent of replacing `true` values with ranged values to eliminate `true` values from BCD.
Commit/PR Adding the Feature: #292
=> Update Chromium data for webextensions.api.devtools.panels.ExtensionPanel.onSearch

webextensions/api/devtools.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `network` member of the `devtools` Web Extensions interface. This sets the feature(s) to a version range based upon the date that the feature was added to BCD with the intent of replacing `true` values with ranged values to eliminate `true` values from BCD.
Commit/PR Adding the Feature: #1160, #1162
=> Update Chromium data for webextensions.api.devtools.network

webextensions/api/devtools.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `inspectedWindow.eval` member of the `devtools` Web Extensions interface. This sets the feature(s) to a version range based upon the date that the feature was added to BCD with the intent of replacing `true` values with ranged values to eliminate `true` values from BCD.
Commit/PR Adding the Feature: #271
=> Update Chromium data for webextensions.api.devtools.inspectedWindow.eval

webextensions/api/cookies.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `Cookie.sameSite` member of the `cookies` Web Extensions interface. This sets the feature(s) to a version range based upon the date that the feature was added to BCD with the intent of replacing `true` values with ranged values to eliminate `true` values from BCD.
Commit/PR Adding the Feature: #2918
=> Update Chromium data for webextensions.api.cookies.Cookie.sameSite

webextensions/api/browsingData.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `browsingData` Web Extensions interface. This sets the feature(s) to a version range based upon the date that the feature was added to BCD with the intent of replacing `true` values with ranged values to eliminate `true` values from BCD.
Commit/PR Adding the Feature: #457
=> Update Chromium data for browsingData Web Extensions interface

webextensions/api/browsingData.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `RemovalOptions.since` member of the `browsingData` Web Extensions interface. This sets the feature(s) to a version range based upon the date that the feature was added to BCD with the intent of replacing `true` values with ranged values to eliminate `true` values from BCD.
Commit/PR Adding the Feature: #333
=> Update Chromium data for webextensions.api.browsingData.RemovalOptions.since

webextensions/api/browserAction.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `setBadgeBackgroundColor.string` member of the `browserAction` Web Extensions interface. This sets the feature(s) to a version range based upon the date that the feature was added to BCD with the intent of replacing `true` values with ranged values to eliminate `true` values from BCD.
Commit/PR Adding the Feature: #859
=> Update Chromium data for webextensions.api.browserAction.setBadgeBackgroundColor.string

webextensions/api/browserAction.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `onClicked.tab` member of the `browserAction` Web Extensions interface. This sets the feature(s) to a version range based upon the date that the feature was added to BCD with the intent of replacing `true` values with ranged values to eliminate `true` values from BCD.
Commit/PR Adding the Feature: #5285
=> Update Chromium data for webextensions.api.browserAction.onClicked.tab

scripts/update-browser-releases/firefox.ts
This is a follow-up to #23928, which updates the logic to look at what _will_ be set as the current browser release, rather than what is already set as the current release, so "current" can eventually become "esr".
=> update-browser-releases: ensure "esr" is set when "current" -> "esr"

webextensions/api/webRequest.json
Documents the change made in [Bug 1909474](https://bugzilla.mozilla.org/show_bug.cgi?id=1909474) webRequest.getSecurityInfo() options parameter is documented as optional but cannot be optional
MDN content changes made in PR https://github.com/mdn/content/pull/35345
=> webRequest.getSecurityInfo options parameter optional

webextensions/api/downloads.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `downloads` Web Extensions interface. This sets the feature(s) to a version range based upon the date that the feature was added to BCD with the intent of replacing `true` values with ranged values to eliminate `true` values from BCD.
Commit/PR Adding the Feature: #421, #434, #12069
=> Update Chromium data for downloads Web Extensions interface

webextensions/api/devtools.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `panels` member of the `devtools` Web Extensions interface. This sets the feature(s) to a version range based upon the date that the feature was added to BCD with the intent of replacing `true` values with ranged values to eliminate `true` values from BCD.
Commit/PR Adding the Feature: #360, #460
=> Update Chromium data for webextensions.api.devtools.panels

webextensions/api/types.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `types` Web Extensions interface. This sets the feature(s) to a version range based upon the date that the feature was added to BCD with the intent of replacing `true` values with ranged values to eliminate `true` values from BCD.
Commit/PR Adding the Feature: #166
=> Update Chromium data for types Web Extensions interface

webextensions/api/tabs.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `tabs` Web Extensions interface. This sets the feature(s) to a version range based upon the date that the feature was added to BCD with the intent of replacing `true` values with ranged values to eliminate `true` values from BCD.
Commit/PR Adding the Feature: #512, #469, #446
=> Update Chromium data for tabs Web Extensions interface

webextensions/api/runtime.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `lastError` member of the `runtime` Web Extensions interface. This sets the feature(s) to a version range based upon the date that the feature was added to BCD with the intent of replacing `true` values with ranged values to eliminate `true` values from BCD.
Commit/PR Adding the Feature: #166
=> Update Chromium data for webextensions.api.runtime.lastError

webextensions/api/privacy.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `websites.protectedContentEnabled` member of the `privacy` Web Extensions interface. This sets the feature(s) to a version range based upon the date that the feature was added to BCD with the intent of replacing `true` values with ranged values to eliminate `true` values from BCD.
Commit/PR Adding the Feature: #166
=> Update Chromium data for webextensions.api.privacy.websites.protectedContentEnabled

webextensions/manifest/author.json, webextensions/manifest/background.json, webextensions/manifest/browser_action.json, webextensions/manifest/chrome_settings_overrides.json, webextensions/manifest/chrome_url_overrides.json, webextensions/manifest/commands.json, webextensions/manifest/content_scripts.json, webextensions/manifest/content_security_policy.json, webextensions/manifest/default_locale.json, webextensions/manifest/description.json, webextensions/manifest/devtools_page.json, webextensions/manifest/homepage_url.json, webextensions/manifest/icons.json, webextensions/manifest/incognito.json, webextensions/manifest/name.json, webextensions/manifest/omnibox.json, webextensions/manifest/optional_permissions.json, webextensions/manifest/page_action.json, webextensions/manifest/permissions.json, webextensions/manifest/short_name.json, webextensions/manifest/theme.json, webextensions/manifest/version.json, webextensions/manifest/web_accessible_resources.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `manifest` member of the `webextensions` Web Extensions manifest property. This sets the feature(s) to a version range based upon the date that the feature was added to BCD with the intent of replacing `true` values with ranged values to eliminate `true` values from BCD.
Commit/PR Adding the Feature: 2efdf62c919f260d4c5c34b6da34ff06bbd0dbc1, #189, #216, 1077f96748d869c0406a24d1c09634b91336720a, 0b6eb2ddf938be9198c000b2ad2122b3da67ec43, #219, #244, 0b6fa92b7069e470d1c8d75f57a34ebc44ba70ee, 46f9188b7962dcac6dde3dcd93a64f2f0233f705, 29ff7e9c578526a3beac1f4b65e14a6c3fe5b58d, #481, 28b3a7726786a9d1007b8be1659c6bac24311b60
=> Update Chromium data for webextensions.manifest

api/SubtleCrypto.json
FF129 supports signature algorithm Ed25519  in https://bugzilla.mozilla.org/show_bug.cgi?id=1804788 and X25519  in https://bugzilla.mozilla.org/show_bug.cgi?id=1904836
This adds FF info for Ed25519 key agreement algorithm. I also added support for X25519 in other browsers in same versions as Ed25519. This makes sense because they use the same curves and this is what the release info in those browsers indicates.
Related docs can be tracked in https://github.com/mdn/content/issues/34708 and https://github.com/mdn/content/issues/35280
=> SubtleCrypto ED25519 (FF129) X25519 (FF1300)

scripts/traverse.ts
This PR fixes an issue with the traverse script where, if filtering for `null` as a value, all webextensions features are included in the list since webextensions doesn't include all of the browsers.
Additionally, this filters server runtimes out by default, since they also are not defined everywhere.
=> Fix traverse script when traversing webextensions category

api/HTMLVideoElement.json
https://bugzilla.mozilla.org/show_bug.cgi?id=1800882#c15
Added in Firefox 130.
=> Firefox 130 adds HTMLVideoElement.requestVideoFrameCallback

api/CSPViolationReportBody.json, http/headers/Content-Security-Policy.json, http/headers/Report-To.json, http/headers/Reporting-Endpoints.json
FF130 supports the CSP [`report-to`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/report-to) directive in https://bugzilla.mozilla.org/show_bug.cgi?id=1391243 behind a preference.
in https://bugzilla.mozilla.org/show_bug.cgi?id=1860588:
There is also some Reporting API stuff that is quite related to document. I'll do that separately.
I'm confirming this in  https://bugzilla.mozilla.org/show_bug.cgi?id=1391243#c11 and some related stuff, but what I have here should be correct based on the IDL and info in bugs.
Related docs work can be tracked in https://github.com/mdn/content/issues/35279
=> Ff130 csp report to

api/DeprecationReportBody.json, api/Report.json, api/ReportBody.json, api/ReportingObserver.json
This updates FF features for the [Reporting API](https://developer.mozilla.org/en-US/docs/Web/API/Reporting_API)
Most of this was implemented in FF65 in the "legacy v0 API" in https://bugzilla.mozilla.org/show_bug.cgi?id=1492036 behind pref. Where supported, `to_JSON` and worker support added in https://bugzilla.mozilla.org/show_bug.cgi?id=1630947
Note, FF does not support:
There's a new header being added in #24047, so this is "backfilling"
Related docs work tracked in https://github.com/mdn/content/issues/35279
=> FF65 Reporting API updates 

webextensions/api/cookies.json
This PR updates and corrects version values for Safari iOS/iPadOS for the `set.partitionKey` member of the `cookies` Web Extensions interface. This sets the downstream browser(s) to mirror from their upstream counterpart.
=> Update Safari iOS data for webextensions.api.cookies.set.partitionKey

webextensions/manifest/version_name.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `version_name` Web Extensions manifest property. This sets the feature(s) to a version range based upon the date that the feature was added to BCD with the intent of replacing `true` values with ranged values to eliminate `true` values from BCD.
Commit/PR Adding the Feature: #1380
=> Update Chromium data for version_name Web Extensions manifest property

webextensions/manifest/version.json
This PR updates and corrects version values for Opera and Opera Android for the `version` Web Extensions manifest property. This sets the downstream browser(s) to mirror from their upstream counterpart.
=> Update Opera data for version Web Extensions manifest property

webextensions/manifest/user_scripts.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `user_scripts` Web Extensions manifest property. This sets the feature(s) to a version range based upon the date that the feature was added to BCD with the intent of replacing `true` values with ranged values to eliminate `true` values from BCD.
Commit/PR Adding the Feature: #5230
=> Update Chromium data for user_scripts Web Extensions manifest property

webextensions/manifest/theme.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `colors` member of the `theme` Web Extensions manifest property. This sets the feature(s) to a version range based upon the date that the feature was added to BCD with the intent of replacing `true` values with ranged values to eliminate `true` values from BCD.
Commit/PR Adding the Feature: #581, #1721
=> Update Chromium data for webextensions.manifest.theme.colors

api/HTMLDetailsElement.json, api/WebGL2RenderingContext.json, api/WebGLRenderingContext.json
The @openwebdocs [BCD collector project](https://github.com/openwebdocs/mdn-bcd-collector) v10.12.1 found new features shipping in Firefox 130 beta which was released last week. Currently, the collector covers about 90% of BCD, so the following list might not be exhaustive. Also, if a feature is in Firefox Nightly only, it is not considered here.
With this PR, BCD considers the following 12 features as shipping in Firefox 130 (most updates submitted in other PRs manually this time):
- api.HTMLDetailsElement.name
- https://github.com/mdn/content/issues/35283
- api.SubtleCrypto.deriveBits.x25519
- https://github.com/mdn/content/issues/34708 (and below)
- api.SubtleCrypto.deriveKey.x25519
- api.SubtleCrypto.exportKey.x25519
- api.SubtleCrypto.generateKey.x25519
- …
=> Updates for Firefox 130 beta

api/HTMLElement.json, html/global_attributes.json
The `writingsuggestions` global HTML attribute lets developers choose where UAs should or shouldn't propose writing suggestions in text editing regions. This was added recently to BCD only as the DOM property. This PR adds the HTML attribute too.
* https://chromestatus.com/feature/5153375153029120
* https://groups.google.com/a/chromium.org/g/blink-dev/c/NhWn64yxB5Q/m/1DnBEqxXAQAJ
* https://html.spec.whatwg.org/multipage/interaction.html#writing-suggestions
=> Add the `writingsuggestions` HTML attribute to BCD

webextensions/manifest/storage.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `storage` Web Extensions manifest property. This sets the feature(s) to a version range based upon the date that the feature was added to BCD with the intent of replacing `true` values with ranged values to eliminate `true` values from BCD.
Commit/PR Adding the Feature: #5575
=> Update Chromium data for storage Web Extensions manifest property

webextensions/manifest/permissions.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `permissions` Web Extensions manifest property. This sets the feature(s) to a version range based upon the date that the feature was added to BCD with the intent of replacing `true` values with ranged values to eliminate `true` values from BCD.
Commit/PR Adding the Feature: #928
=> Update Chromium data for permissions Web Extensions manifest property

browsers/safari.json, browsers/safari_ios.json, scripts/update-browser-releases/index.ts
See https://webkit.org/blog/15739/webkit-features-in-safari-17-6/
I guess we also need to update the data for safe alignment in flex box (search for "safe_unsafe" in css/). 
This PR fixes the browser/ release data first, though.
=> Safari 17.6 release

scripts/traverse.ts
This PR makes an update to the traverse script to introduce a `--show-count` argument, which is disabled by default if the output is being piped.  This is particularly helpful for scripting usage, such as grepping.
=> Hide traversed features count by default when output is piped

css/properties/cursor.json
I think `inherit` is a global value in CSS and `cursor` is the only property that has this as a sub feature. We should remove it.
=> Remove CSS cursor: inherit

css/selectors/buffering.json, css/selectors/muted.json, css/selectors/paused.json, css/selectors/playing.json, css/selectors/seeking.json, css/selectors/stalled.json, css/selectors/volume-locked.json
- fixes https://github.com/mdn/content/issues/31746
These media pseudo-classes have counterpart HTML standard specifications.
=> fix(css): add html standard links to media pseudo-classes

webextensions/manifest/theme.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `theme` Web Extensions manifest property. This sets the feature(s) to a version range based upon the date that the feature was added to BCD with the intent of replacing `true` values with ranged values to eliminate `true` values from BCD.
Commit/PR Adding the Feature: #2194, #4615
Additional Notes: Firefox Android is also set to mirror in this PR.
=> Update Chromium data for theme Web Extensions manifest property

api/SVGStringList.json, api/SVGTransformList.json
length is listed in the IDL
- https://svgwg.org/svg2-draft/types.html#InterfaceSVGStringList
- https://svgwg.org/svg2-draft/coords.html#InterfaceSVGTransformList
=> Mark SVG{String,Transform}List.length as standardized

browsers/nodejs.json, javascript/statements.json
- Update data about import attributes support (both `with` and `assert` syntax)
- Node.js support for import attributes: https://nodejs.org/api/esm.html#import-attributes (see "Switch from Import Assertions to Import Attributes" entry in the History table)
- chromestatus entry for removing `assert`: https://chromestatus.com/feature/4689167795879936
=> Update data about import attributes

javascript/builtins/Temporal/Calendar.json, javascript/builtins/Temporal/Duration.json, javascript/builtins/Temporal/Instant.json, javascript/builtins/Temporal/Now.json, javascript/builtins/Temporal/PlainDate.json, javascript/builtins/Temporal/PlainDateTime.json, javascript/builtins/Temporal/PlainMonthDay.json, javascript/builtins/Temporal/PlainTime.json, javascript/builtins/Temporal/PlainYearMonth.json, javascript/builtins/Temporal/TimeZone.json, javascript/builtins/Temporal/ZonedDateTime.json
This PR updates Temporal compat data.
- Remove descriptions as it is more conventional to not have them
- Update constructor descriptions to match BCD conventions
- Fix some typos in spec_url fragments
- Rename calendar properties to calendarId
- Rename timezone properties to timezoneId
- Remove properties per https://github.com/tc39/proposal-temporal/pull/2895
- Add yearOfWeek properties
- Remove TimeZone.p.getNextTransition and TimeZone.p.getPreviousTransition
- Add ZonedDateTime.p.getTimeZoneTransition
(Looks more removals will come: https://github.com/tc39/proposal-temporal/pull/2925 but thanks to the spec_url validation I'm doing in https://github.com/mdn/browser-compat-data/pull/23958 we'll be able to keep track of this going forward.)
=> Update Temporal data

html/elements/textarea.json
Support for line breaks in placeholder: add missing support information for Safari.
WebKit bug tracker: https://bugs.webkit.org/show_bug.cgi?id=235205 (fixed 2022-01)
Safari 16 was released in 2022-09
None
=> html.elements.textarea.placeholder: line breaks supported in Safari 16

api/Element.json
FF supported the  [`contentvisibilityautostatechange` event ](https://developer.mozilla.org/en-US/docs/Web/API/Element/contentvisibilityautostatechange_event and its associated interface since FF124, but the dev team just added support for the global event handler `oncontentvisibilitychanged` in https://bugzilla.mozilla.org/show_bug.cgi?id=1898833 - an omission picked up in a test. 
What I have done here is added a note to the event record that indicates support was added for this in FF130. I am not "certain" this is the right thing to do. 
1. We don't separately document the event handler in BCD or MDN - this is the record that people would see  on the MDN page, so it looks like the right thing to update.
2. A note seems more reasonable to me than a separate version record showing …
=> FF130 supports oncontentvisibilityautostatechange event handler

api/CSSPageDescriptors.json
See https://github.com/w3c/csswg-drafts/pull/10521 for the spec change. 
Looks like it made it in Firefox in 129, too. https://github.com/mdn/content/issues/34702
=> Add CSSPageDescriptors.pageOrientation/page-orientation

css/at-rules/import.json
A [new page](https://github.com/mdn/content/pull/35508) is being created for the feature so the PR adds the missing spec URL
=> css.at-rules.import.layer - add spec URL

webextensions/manifest/page_action.json
This PR updates and corrects version values for Opera and Opera Android for the `page_action` Web Extensions manifest property. This sets the downstream browser(s) to mirror from their upstream counterpart.
=> Update Opera data for page_action Web Extensions manifest property

webextensions/manifest/options_page.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `options_page` Web Extensions manifest property. This sets the feature(s) to a version range based upon the date that the feature was added to BCD with the intent of replacing `true` values with ranged values to eliminate `true` values from BCD.
Commit/PR Adding the Feature: #1267
=> Update Chromium data for options_page Web Extensions manifest property

webextensions/manifest/omnibox.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `keyword` member of the `omnibox` Web Extensions manifest property. This sets the feature(s) to a version range based upon the date that the feature was added to BCD with the intent of replacing `true` values with ranged values to eliminate `true` values from BCD.
Commit/PR Adding the Feature: #3537
Additional Notes: The key was corrected from "key" to "keyword" in #21527.
=> Update Chromium data for webextensions.manifest.omnibox.keyword

api/EventTarget.json
This PR updates and corrects version values for Deno for the `addEventListener.options_parameter.options_passive_parameter_default_true_wheel` member of the `EventTarget` API. Deno doesn't have its own mouse support as far as I can tell, so this just sets the feature to `false`.
Additional Notes: This PR removes one of the remaining `null` values in BCD.
=> Update Deno data for api.EventTarget.addEventListener.options_parameter.options_passive_parameter_default_true_wheel

webextensions/api/devtools.json
This PR updates and corrects version values for Opera and Opera Android for the `panels.ExtensionSidebarPane` member of the `devtools` Web Extensions interface. This sets the downstream browser(s) to mirror from their upstream counterpart.
=> Update Opera data for webextensions.api.devtools.panels.ExtensionSidebarPane

webextensions/api/commands.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `Command.name` member of the `commands` Web Extensions interface. This sets the feature(s) to a version range based upon the date that the feature was added to BCD with the intent of replacing `true` values with ranged values to eliminate `true` values from BCD.
Commit/PR Adding the Feature: #12512
=> Update Chromium data for webextensions.api.commands.Command.name

webextensions/api/browserAction.json
This PR updates and corrects version values for Firefox and Firefox Android for the `setBadgeBackgroundColor.string` member of the `browserAction` Web Extensions interface. This sets the feature(s) to a version range based upon the date that the feature was added to BCD with the intent of replacing `true` values with ranged values to eliminate `true` values from BCD.
Commit/PR Adding the Feature: #859
=> Update Firefox data for webextensions.api.browserAction.setBadgeBackgroundColor.string

webextensions/manifest/background.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `scripts` member of the `background` Web Extensions manifest property. This sets the feature(s) to a version range based upon the date that the feature was added to BCD with the intent of replacing `true` values with ranged values to eliminate `true` values from BCD.
Commit/PR Adding the Feature: #3537
=> Update Chromium data for webextensions.manifest.background.scripts

webextensions/api/storage.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `StorageArea.onChanged` member of the `storage` Web Extensions interface. This sets the downstream browser(s) to mirror from their upstream counterpart.
=> Update Chromium data for webextensions.api.storage.StorageArea.onChanged

webextensions/api/runtime.json
This PR updates and corrects version values for Firefox and Firefox Android for the `runtime` Web Extensions interface. This sets the feature(s) to a version range based upon the date that the feature was added to BCD with the intent of replacing `true` values with ranged values to eliminate `true` values from BCD.
Commit/PR Adding the Feature: #2927
=> Update Firefox data for runtime Web Extensions interface

webextensions/api/menus.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `menus` Web Extensions interface. This sets the feature(s) to a version range based upon the date that the feature was added to BCD with the intent of replacing `true` values with ranged values to eliminate `true` values from BCD.
Commit/PR Adding the Feature: #166, #2751, #13259
=> Update Chromium data for menus Web Extensions interface

webextensions/api/menus.json
This PR updates and corrects version values for Firefox and Firefox Android for the `ACTION_MENU_TOP_LEVEL_LIMIT` member of the `menus` Web Extensions interface. This sets the feature(s) to a version range based upon the date that the feature was added to BCD with the intent of replacing `true` values with ranged values to eliminate `true` values from BCD.
Commit/PR Adding the Feature: #166
=> Update Firefox data for webextensions.api.menus.ACTION_MENU_TOP_LEVEL_LIMIT

webextensions/api/events.json
This PR updates and corrects version values for Firefox and Firefox Android for the `events` Web Extensions interface. This sets the feature(s) to a version range based upon the date that the feature was added to BCD with the intent of replacing `true` values with ranged values to eliminate `true` values from BCD.
Commit/PR Adding the Feature: #166, #1686
Additional Notes: The "≤50" comes from a subfeature that's set as "50".
=> Update Firefox data for events Web Extensions interface

webextensions/manifest/content_scripts.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `content_scripts` Web Extensions manifest property. This sets the feature(s) to a version range based upon the date that the feature was added to BCD with the intent of replacing `true` values with ranged values to eliminate `true` values from BCD.
Commit/PR Adding the Feature: #3537
=> Update Chromium data for content_scripts Web Extensions manifest property

webextensions/manifest/developer.json
This PR updates and corrects version values for Opera and Opera Android for the `developer` Web Extensions manifest property. This sets the feature(s) to a version range based upon the date that the feature was added to BCD with the intent of replacing `true` values with ranged values to eliminate `true` values from BCD.
Commit/PR Adding the Feature: #189
Additional Notes: Honestly, this is _probably_ wrong and it's either supported in Chrome (or was supported in Opera Presto).
=> Update Opera data for developer Web Extensions manifest property

webextensions/manifest/externally_connectable.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `externally_connectable` Web Extensions manifest property. This sets the feature(s) to a version range based upon the date that the feature was added to BCD with the intent of replacing `true` values with ranged values to eliminate `true` values from BCD.
Commit/PR Adding the Feature: #2329
=> Update Chromium data for externally_connectable Web Extensions manifest property

webextensions/manifest/incognito.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `spanning` member of the `incognito` Web Extensions manifest property. This sets the feature(s) to a version range based upon the date that the feature was added to BCD with the intent of replacing `true` values with ranged values to eliminate `true` values from BCD.
Commit/PR Adding the Feature: #3535
=> Update Chromium data for webextensions.manifest.incognito.spanning

css/properties/stroke.json
The property is supported as defined in this https://svgwg.org/svg2-draft/painting.html#SpecifyingStrokePaint spec, not as a shorthand as defined in the not-updated-since-2017 drafts.fxtf.org spec
=> CSS `stroke` property spec URL

javascript/builtins/Intl/DateTimeFormat.json, javascript/builtins/Intl/NumberFormat.json, javascript/builtins/Intl/RelativeTimeFormat.json, javascript/builtins/RegExp.json, javascript/builtins/String.json
These data show up because the description is a single word without space. I fixed them by either adding `mdn_url` or changing the description
=> Fix all JS data that show up in web-docs-backlog

html/elements/form.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `form` HTML element. This copies the data from the API counterpart, which fixes #24135.
=> Update Safari data for form HTML element

css/properties/font-optical-sizing.json
Both Edge and Safari have suspicious values. `none` and `auto` support are both reported to have shipped after `font-optical-sizing` itself shipped, which doesn't make sense. What would the property do without a valid value?
I tested this manually. Edge was straight forward: the values did different things from Edge 17.
Safari was more complex. It's possible that this was implemented earlier (`CSS.supports(…)` returns true for this property from version 11) but I couldn't actually see a difference when I tested it in Safari <13.1. Given https://bugs.webkit.org/show_bug.cgi?id=197528, I think it's possible that the property didn't actually do anything before 13 or 13.1. Unfortunately, Browser Stack doesn't seem to offer Safari 13, only 13.1. I suppose it's also possible there's some other …
=> `font-optical-sizing` version range corrections

api/CSSPositionTryDescriptors.json, api/PublicKeyCredential.json, api/RTCDataChannel.json, css/properties/interpolate-size.json, css/properties/position-area.json, css/properties/position-try-fallbacks.json, css/types/calc-size.json, javascript/builtins/Intl/DurationFormat.json
The @openwebdocs [BCD collector project](https://github.com/openwebdocs/mdn-bcd-collector) v10.12.02 found new features shipping in Chrome 129 beta which was released yesterday. Currently, the collector covers about 90% of BCD, so the following list might not be exhaustive. Also, if a feature is in Chrome Canary/behind origin trials/enrollment, it is not considered here.
With this PR, BCD considers the following 52 features as shipping in Chrome 129:
- api.CSSPositionTryDescriptors.position-area
- api.CSSPositionTryDescriptors.positionArea
- api.PublicKeyCredential.parseCreationOptionsFromJSON_static
- api.PublicKeyCredential.parseRequestOptionsFromJSON_static
- api.PublicKeyCredential.toJSON
- api.RTCDataChannel.binaryType.blob_value
- css.properties.interpolate-size
- …
=> Updates for Chrome 129 beta

css/types/color.json
According to [the spec](https://drafts.csswg.org/css-color/#transparent-color), `transparent` is a value of `<named-color>` type. I thought it a bit weird that it doesn't reside with the other `<named-color>` data.
I moved the object, but did not change the underlying support information. I did drop the `description` for consistency with its sibling feature.
Discovered in the course of reviewing https://github.com/web-platform-dx/web-features/pull/1619#discussion_r1728579552
=> Move `css.types.color.transparent` to `css.types.color.named-color.transparent`

webextensions/manifest/offline_enabled.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `offline_enabled` Web Extensions manifest property. This sets the feature(s) to a version range based upon the date that the feature was added to BCD with the intent of replacing `true` values with ranged values to eliminate `true` values from BCD.
Commit/PR Adding the Feature: #3015
=> Update Chromium data for offline_enabled Web Extensions manifest property

webextensions/manifest/manifest_version.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `v2` member of the `manifest_version` Web Extensions manifest property. This version range was added based upon the removal version for Manifest v1 (see #3536).
=> Update Chromium data for webextensions.manifest.manifest_version.v2

css/properties/justify-content.json
Support for the 'safe' keyword in Flexbox was added in Safari 17.6. 
https://webkit.org/blog/15739/webkit-features-in-safari-17-6/
It was listed as "Safari 18" in MDN BCD because support was first announced in Safari 18 beta, in June. But then we shipped support in July in Safari 17.6. That's the first public release.
=> Update justify-content.json — the 'safe' keyword in Flexbox was added in Safari 17.6. 

css/properties/align-items.json
Support for the 'safe' keyword in Flexbox was added in Safari 17.6. 
https://webkit.org/blog/15739/webkit-features-in-safari-17-6/
It was listed as "Safari 18" in MDN BCD because support was first announced in Safari 18 beta, in June. But then we shipped support in July in Safari 17.6. That's the first public release.
=> Update align-items.json — the 'safe' keyword in Flexbox was added in Safari 17.6. 

css/properties/align-content.json
Support for the 'safe' keyword in Flexbox was added in Safari 17.6. 
https://webkit.org/blog/15739/webkit-features-in-safari-17-6/
It was listed as "Safari 18" in MDN BCD because support was first announced in Safari 18 beta, in June. But then we shipped support in July in Safari 17.6. That's the first public release.
=> Update align-content.json — the 'safe' keyword in Flexbox was added in Safari 17.6. 

css/properties/align-self.json
Support for the 'safe' keyword in Flexbox was added in Safari 17.6. 
https://webkit.org/blog/15739/webkit-features-in-safari-17-6/
It was listed as "Safari 18" in MDN BCD because support was first announced in Safari 18 beta, in June. But then we shipped support in July in Safari 17.6. That's the first public release.
=> Update align-self.json — the 'safe' keyword in Flexbox was added in Safari 17.6. 

api/WebSocket.json
The WebSocket spec allows http, https, relative URLs in the constructor `url` argument from https://github.com/whatwg/websockets/pull/37.
This has been implemented in 
- FF124: https://bugzilla.mozilla.org/show_bug.cgi?id=1797449
- Chrome 125: https://chromestatus.com/feature/5848709993857024
- Webkit: https://bugs.webkit.org/show_bug.cgi?id=247149 - can't work out Safari version, but first testable in 17.3 on browserstack
- Deno - https://github.com/denoland/deno/pull/16488 but I can't work out version
- Node - no evidence.
Tested on Safari using http://wpt.live/websockets/Create-http-urls.any.worker.html
Couldn't work out versions for Deno.
@queengooborg Something you could help with?
Related docs work can be tracked in https://github.com/mdn/content/issues/26731
=> WebSocket constructor support for http(s) and relative URLs

api/PaymentResponse.json
This PR updates and corrects the metadata (spec URLs, descriptions, statuses, etc.) for the `PaymentResponse` API.
Additional Notes: This fixes #24205.
=> Update metadata for PaymentResponse API

webdriver/commands/CreateVirtualPressureSource.json, webdriver/commands/DeleteVirtualPressureSource.json, webdriver/commands/UpdateVirtualPressureSource.json
Chromium 129 ships with 3 new Compute Pressure WebDriver commands.
- CreateVirtualPressureSource
- DeleteVirtualPressureSource
- UpdateVirtualPressureSource
https://chromestatus.com/feature/5130657352384512
cc @kenchris
=> Add new Compute Pressure WebDriver commands

api/HTMLDetailsElement.json
- Added to the `api.HTMLDetailsElement.name`:
- mdn_url
- spec_url
Tested in Firefox Beta 130
- [Content PR](https://github.com/mdn/content/pull/35619)
- [Automated BCD PR](https://github.com/mdn/browser-compat-data/pull/24118)
- [Firefox Release note](https://github.com/mdn/content/pull/35447)
=> added the mdn & spec urls for api.HTMLDetailsElement.name

javascript/regular_expressions.json
- `javascript.regular_expressions.modifier` for Firefox
- Added version_added 
- added flag
- tested in Firefox Nightly 131.0a1 (2024-08-28) with [this codepen](https://codepen.io/CodeRedDigital/pen/GRbEOLE?editors=0011)
- [Firefox Release PR](https://github.com/mdn/content/pull/35622)
=> added version_added and flags for reg_exp modifiers in firefox

webextensions/manifest/page_action.json
This PR updates and corrects version values for Firefox Android for the `page_action` Web Extensions manifest property. This sets the downstream browser(s) to mirror from their upstream counterpart.
=> Update Firefox Android data for page_action Web Extensions manifest property

webextensions/manifest/page_action.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `page_action` Web Extensions manifest property. This sets the feature(s) to a version range based upon the date that the feature was added to BCD with the intent of replacing `true` values with ranged values to eliminate `true` values from BCD.
Commit/PR Adding the Feature: #3537
=> Update Chromium data for page_action Web Extensions manifest property

api/PointerEvent.json
I recently added documentation for the `PointerEvent.persistentDeviceId` property (see https://github.com/mdn/content/pull/35566), but I noticed that the `spec_url` was missing from the BCD. This PR adds it.
=> Add PointerEvent.persistentDeviceId spec

webextensions/manifest/optional_permissions.json
This PR updates and corrects version values for Firefox for the `optional_permissions` Web Extensions manifest property for search with the intent of replacing `true` values with exact values to eliminate `true` values from BCD.
Commit: https://hg.mozilla.org/mozilla-central/rev/a659bb692003
Commit Date: August 2, 2018
Bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1477271
Target Milestone: mozilla63
=> Update Firefox data for optional_permissions Web Extensions manifest

webextensions/manifest/dictionaries.json
This PR updates and corrects version values for Firefox and Firefox Android for the `dictionaries` Web Extensions manifest property. The data comes from a bug in the web browser's bug tracker.
Bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1410214
=> Update Firefox data for dictionaries Web Extensions manifest property

webextensions/manifest/commands.json
This PR updates and corrects version values for Firefox and Firefox Android for the `_execute_action` member of the `commands` Web Extensions manifest property. The data comes from a bug in the web browser's bug tracker.
Bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1706398
=> Update Firefox data for webextensions.manifest.commands._execute_action

api/CSSContainerRule.json, css/at-rules/container.json, css/properties/contain.json, css/properties/container-name.json, css/properties/container-type.json, css/properties/container.json
The contents of `css-contain-3` specification [have been moved](https://drafts.csswg.org/css-contain-3/#changes-2022-08) to `css-conditional-5` . 
Refs
- https://github.com/w3c/csswg-drafts/pull/10447
- https://github.com/w3c/csswg-drafts/issues/10433#issuecomment-2165558965
=> fix(css): update container spec URLs

api/FileSystemFileHandle.json
Chrome 121 supports a `mode` property on the options objects that can be specified as arguments to  `FileSystemFileHandle.createSyncAccessHandle()` and `FileSystemFileHandle.createWritable()`. See the associated [ChromeStatus entry](https://chromestatus.com/feature/5172892632875008).
These features are not yet in the [FileSystem API](https://fs.spec.whatwg.org/) spec — see https://github.com/whatwg/fs/pull/151 for the relevant PR. Consequently, I have marked these additions as `"standard_track": false`, and will mark them as non-standard in the associated docs.
See also the [New Locking Scheme to Enable Multiple Readers and Writers](https://github.com/whatwg/fs/blob/main/proposals/MultipleReadersWriters.md) explainer for more information on how it works.
=> Add locking mode options to FileSystemFileHandle

css/properties/caption-side.json
This PR adds the missing features of the `caption-side` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.1).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/caption-side
=> Add missing features for caption-side CSS property

css/properties/color-scheme.json
This PR adds the missing features of the `color-scheme` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.1).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/color-scheme
=> Add missing features for color-scheme CSS property

css/properties/caption-side.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `caption-side` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.10.9).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/caption-side
=> Update Safari data for caption-side CSS property

css/properties/accent-color.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `accent-color` CSS property. This fixes #16367, which contains the supporting evidence for this change.
=> Update Safari data for accent-color CSS property

api/AudioData.json, api/AudioDecoder.json, api/AudioEncoder.json, api/EncodedAudioChunk.json, api/EncodedVideoChunk.json, api/VideoColorSpace.json, api/VideoDecoder.json, api/VideoEncoder.json, api/VideoFrame.json
The @openwebdocs [BCD collector project](https://github.com/openwebdocs/mdn-bcd-collector) v10.12.2 found new features shipping in Firefox 130 release which was released yesterday. Currently, the collector covers about 90% of BCD, so the following list might not be exhaustive. Also, if a feature is in Firefox Nightly only, it is not considered here.
Originally we collected compat data for Firefox 130 beta, but we have seen some uplifts into the final release of 130:
With this PR, BCD considers the following additional 93 features as shipping in Firefox 130:
1. api.AudioData
2. api.AudioData.AudioData
3. api.AudioData.allocationSize
4. api.AudioData.clone
5. api.AudioData.close
6. api.AudioData.copyTo
7. api.AudioData.duration
8. api.AudioData.format
9. api.AudioData.numberOfChannels
10. …
=> Updates for Firefox 130 release

scripts/traverse.ts
This PR adds the ability to filter for features without any tags.
=> Traverse script: allow filtering for features without tags

api/Document.json, api/FragmentDirective.json, api/Permissions.json, api/PointerEvent.json, css/selectors/target-text.json, html/elements/a.json, javascript/builtins/Iterator.json
The @openwebdocs [BCD collector project](https://github.com/openwebdocs/mdn-bcd-collector) v10.12.2 found new features shipping in Firefox 131 beta which was released yesterday. Currently, the collector covers about 90% of BCD, so the following list might not be exhaustive. Also, if a feature is in Firefox Nightly only, it is not considered here.
With this PR, BCD considers the following 21 features as shipping in Firefox 131 (most updates submitted in other PRs manually this time):
- api.Document.fragmentDirective
- api.FragmentDirective
- api.Permissions.permission_camera ([might be a beta thing only](https://bugzilla.mozilla.org/show_bug.cgi?id=1609427))
- api.Permissions.permission_microphone (dito)
- api.PointerEvent.altitudeAngle
- api.PointerEvent.azimuthAngle
- …
=> Updates for Firefox 131 beta

api/PointerEvent.json
FF131 Added support for [`PointerEvent.altitudeAngle`](https://developer.mozilla.org/en-US/docs/Web/API/PointerEvent/altitudeAngle) and `azimuthAngle` in https://bugzilla.mozilla.org/show_bug.cgi?id=1656377
We added the features for the properties themselves in #24332. This adds the same properties for the constructor argument `options`. Note I only added the new ones, not the ones that should have been there "forever".
FYI @Elchi3 Don't know if the collector can be updated to detect these being supported.
Related docs work can be tracked in https://github.com/mdn/content/issues/35721
=> FF131 PointerEvent.PointerEvent() - azimuthAngle, altitudeAngle options

svg/global_attributes.json
This PR fixes #10790.
Note: a note explaining Android 2.3's behavior was removed.  It appears that the data was copied from the CSS property.
=> SVG support was introduced in WebView Android 3

css/properties/background-clip.json
Supported since STP 202: https://webkit.org/blog/15798/release-notes-for-safari-technology-preview-202/
=> Add `background-clip: border-area`

api/WEBGL_compressed_texture_pvrtc.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `WEBGL_compressed_texture_pvrtc` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.2).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/WEBGL_compressed_texture_pvrtc
=> Update Chromium data for WEBGL_compressed_texture_pvrtc API

css/selectors/any-link.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `not_match_link` member of the `any-link` CSS selector. This fixes #22794, which contains the supporting evidence for this change.
Additional Notes: https://github.com/WebKit/WebKit/commit/fd74541ad3bb9e0c9d009e2834a4164db6747e09
=> Update Safari data for css.selectors.any-link.not_match_link

api/HTMLElement.json
This PR updates and corrects version values for Safari iOS/iPadOS for the `popover` member of the `HTMLElement` API. This fixes #22927, which contains the supporting evidence for this change.
=> Update Safari iOS data for api.HTMLElement.popover

api/ImageCapture.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `ImageCapture` API. This fixes #23727, which contains the supporting evidence for this change.
=> Update Safari data for ImageCapture API

css/properties/display.json
This PR adds the missing `table-caption` member of the `display` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.3).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/display/table-caption
Additional Notes: Fixes #24043.
=> Add missing css.properties.display.table-caption feature

http/headers/Expect-CT.json
This PR updates and corrects the metadata (spec URLs, descriptions, statuses, etc.) for the `Expect-CT` HTTP header.
Additional Notes: Fixes #24144.
=> Update metadata for Expect-CT HTTP header

css/properties/width.json
This PR updates and corrects the metadata (spec URLs, descriptions, statuses, etc.) for the `stretch` member of the `width` CSS property.
Additional Notes: Fixes #24190.
=> Update metadata for css.properties.width.stretch

html/elements/link.json
This PR updates and corrects version values for Firefox and Firefox Android for the `rel.icon` member of the `link` HTML element. This fixes #24213, which contains the supporting evidence for this change.
=> Update Firefox data for html.elements.link.rel.icon

css/properties/display.json
This PR updates and corrects the metadata (spec URLs, descriptions, statuses, etc.) for the `none` member of the `display` CSS property.
=> Update metadata for css.properties.display.none

html/elements/script.json
This PR updates and corrects version values for WebView Android for the `type.speculationrules` member of the `script` HTML element. This fixes #23213, which contains the supporting evidence for this change.
=> Update WebView Android data for html.elements.script.type.speculationrules

html/elements/datalist.json
As of Firefox 110, datalist works for range and color inputs (but date and time inputs are still not supported)
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist#examples
=> Update partial implementation note for datalist

css/types/calc-size.json
Add `impl_url` to Firefox and Safari.
=> feat(css): Update browser compatibility data for the CSS `calc-size()` function

api/Document.json
FF131 adds support for "new shadow dom behaviour" in [`Document/caretPositionFromPoint()`](https://developer.mozilla.org/en-US/docs/Web/API/Document/caretPositionFromPoint) in https://bugzilla.mozilla.org/show_bug.cgi?id=1914596
Essentially this means a new option, called `options` has been added the the api, along with `x`, `y`. The option allows a caller to supply a list of shadow roots, which allows the caret position to be resolved (or not, if not supplied). 
Chrome implemented this in their first release (128), but FF implemented the API in FF20, so this is a compatibility difference. I've added the option as a method subfeature.
Related docs work can be tracked in https://github.com/mdn/content/issues/35702
=> FF131 Document.caretPositionFromPoint() has new option

api/CSSPositionTryDescriptors.json, api/CSSPositionTryRule.json
FF131 implements [`CSSPositionTryRule`](https://developer.mozilla.org/en-US/docs/Web/API/CSSPositionTryRule) and [`CSSPositionTryDescriptors`](https://developer.mozilla.org/en-US/docs/Web/API/CSSPositionTryDescriptors) behind a preference `layout.css.anchor-positioning.enabled` in https://bugzilla.mozilla.org/show_bug.cgi?id=1909346
This updates the relevant feature.
Related docs work can be tracked in https://github.com/mdn/content/issues/35699
=> FF131 CSSPositionTryRule/TryDescriptors - behind pref

api/HTMLImageElement.json, api/HTMLLinkElement.json, api/HTMLScriptElement.json, html/elements/img.json, html/elements/link.json, html/elements/script.json
Opera was always the same as Chrome but looks like some updates were missed in #16933
This is the first result from a caniuse search so is confusing: https://caniuse.com/?search=fetchpriority
Firefox has had this behind a flag, I think since 127 (https://forums.mozillazine.org/viewtopic.php?t=3122117).
Firefox:
https://bugzilla.mozilla.org/show_bug.cgi?id=1797715
Opera:
=> Update fetchpriority support

api/RTCPeerConnection.json
Fixes #24441
This was removed from the spec in https://github.com/w3c/webrtc-pc/pull/167
=> RTCPeerConnection.createDTMFSender is non-standard

browsers/safari.json, browsers/safari_ios.json, browsers/webview_ios.json, scripts/update-browser-releases/safari.ts
This PR fixes an issue regarding the browser data, where it added "Safari 18.0" alongside "Safari 18".  This PR fixes both the browser data and the updater script.
=> Fix browser data regarding Safari 18

html/elements/area.json, html/elements/object.json, html/global_attributes.json
this can be a follow up to https://github.com/mdn/browser-compat-data/pull/7310 and part of the https://github.com/mdn/browser-compat-data/issues/21810
the attribute is defined on the global_attributes itself and should not defined on detailed html elements again
1. Remove html.elements.{area,object}.tabindex (most data are the same, except for the firefox one, assume the global one (and HTML interface one) is correct)
2. Update html.global_attributes.tabindex (opera: data taken from the same property of HTMLElement)
=> Remove html.elements.{area,object}.tabindex & Update html.global_attributes.tabindex

svg/global_attributes.json
update spec_url of `glyph-orientation-vertical` and `glyph-orientation-horizontal` to latest version
add missing spec_url for `text-overflow` and `white-space`
=> Update spec_url of svg global attributes

css/at-rules/container.json
Safari has a Style Queries bug in which they don’t work on `<body>`, which is very unfortunate.
- Bug Report: https://bugs.webkit.org/show_bug.cgi?id=271040
- Repro: https://codepen.io/bramus/pen/LYKqzob 
- The box should be green in Safari 18 / Safari Technology Preview, but it is not. Changing the `body` selector to `main` fixes the demo, confirming the bug report.
=> CSS Style Queries: Add note about Safari not supporting these on body

webextensions/api/webRequest.json
This PR updates and corrects version values for Firefox and Firefox Android for the `onBeforeSendHeaders.details.frameAncestors` member of the `webRequest` Web Extensions interface. The data comes from a bug in the web browser's bug tracker.
Bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1305237
=> Update Firefox data for webextensions.api.webRequest.onBeforeSendHeaders.details.frameAncestors

webextensions/api/declarativeNetRequest.json
This PR adds the missing `RuleCondition.initiatorDomains` member of the `declarativeNetRequest` Web Extensions interface. This fixes #23868, which contains the supporting evidence for this change.
Additional Notes: Firefox data was guesstimated using the data from `excludedInitiatorDomains`.
=> Add missing webextensions.api.declarativeNetRequest.RuleCondition.initiatorDomains feature

http/headers/X-Frame-Options.json
See https://html.spec.whatwg.org/multipage/document-lifecycle.html#x-frame-options:
> The `X-Frame-Options` HTTP response header is a legacy way of controlling whether and how a [Document](https://html.spec.whatwg.org/multipage/dom.html#document) may be loaded inside of a [child navigable](https://html.spec.whatwg.org/multipage/document-sequences.html#child-navigable). **It is obsoleted by the [frame-ancestors](https://w3c.github.io/webappsec-csp/#frame-ancestors) CSP directive**, which provides more granular control over the same situations. It was originally defined in HTTP Header Field X-Frame-Options, but the definition and processing model here supersedes that document. [[CSP]](https://html.spec.whatwg.org/multipage/references.html#refsCSP) …
=> Deprecate X-Frame-Options

api/Clipboard.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `Clipboard` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.3).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/Clipboard
Additional Notes: This effectively reverts #6302. The changes made in that PR were incorrect, and the supporting links in the description of the PR confirm it. (One says `readText` and `writeText` were introduced in 66, the other says `read` and `write` in 76, which our PR confirms.)
=> Update Chromium data for Clipboard API

api/PageRevealEvent.json
This PR updates and corrects version values for Microsoft Edge for the `PageRevealEvent` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.3).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/PageRevealEvent
=> Update Edge data for PageRevealEvent API

api/RTCPeerConnection.json
This PR updates and corrects version values for Firefox and Firefox Android for the `RTCPeerConnection` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.3).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/RTCPeerConnection
=> Update Firefox data for RTCPeerConnection API

api/ReadableStreamDefaultController.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `ReadableStreamDefaultController` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.3).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/ReadableStreamDefaultController
=> Update Chromium data for ReadableStreamDefaultController API

api/Request.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `cache.only-if-cached` member of the `Request` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.3).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/Request/cache/only-if-cached
=> Update Chromium data for api.Request.cache.only-if-cached

api/ReadableStreamDefaultReader.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `ReadableStreamDefaultReader` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.3).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/ReadableStreamDefaultReader
=> Update Chromium data for ReadableStreamDefaultReader API

api/Performance.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `measure.measureOptions_parameter` member of the `Performance` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.3).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/Performance/measure/measureOptions_parameter
=> Update Chromium data for api.Performance.measure.measureOptions_parameter

mathml/elements/mo.json
One of the `<mo>`’s attribute is called `movablelimits` [in the spec](https://w3c.github.io/mathml-core/#ref-for-dfn-movablelimits-0-1) as well as [on MDN](https://developer.mozilla.org/en-US/docs/Web/MathML/Element/mo#movablelimits).
=> Fix MathML attr mistype: moveablelimits > movablelimits

webextensions/api/contentScriptGlobalScope.json
BCD to support documentation of exportFunction and cloneInto in https://github.com/mdn/content/pull/30877
=>  Add exportFunction and cloneInto

css/properties/cursor.json
This PR updates and corrects version values for Safari iOS/iPadOS for the `cursor` CSS property. While the browser may _recognize_ the various cursor values, it has no effect on iPhones and iPads without a touchpad.  iPadOS 13.4 was the version that introduced touchpad support, so that version number was used.  Fixes #24142.
Test Code Used:
```html
<!DOCTYPE html>
<html>
<head>
<meta content="width=device-width">
<style id="persistent-style">
/* Persistent styling */
body {
background-color: black;
color: white;
margin: 0;
padding: 0;
}
canvas {
background-color: white;
}
</style>
<style id="test-style">
#alias {
cursor: alias;
}
#all-scroll {
cursor: all-scroll;
}
#auto {
cursor: auto;
}
#cell {
cursor: cell;
}
#col-resize {
cursor: col-resize;
}
#context-menu {
cursor: context-menu;
} …
```
=> Update Safari iOS data for cursor CSS property

webextensions/api/contentScriptGlobalScope.json
According to https://blog.mozilla.org/addons/2014/04/10/changes-to-unsafewindow-for-the-add-on-sdk/#comments, this was added in Firefox 30.
These newly added browser support table records were added in #22767 without a version number.
Not tested, but see the below blog which seems to indicate that this was added in Firefox 30:
https://blog.mozilla.org/addons/2014/04/10/changes-to-unsafewindow-for-the-add-on-sdk/
Requesting review from @Rob--W and/or @rebloor 
https://github.com/openwebdocs/project/issues/206
=> Use exact version for cloneInto and exportFunction

webextensions/api/contentScriptGlobalScope.json
According to https://bugzilla.mozilla.org/show_bug.cgi?id=1280482, this was added in Firefox 49
Fix for https://github.com/mdn/browser-compat-data/pull/24521 according to https://github.com/mdn/browser-compat-data/pull/24521#issuecomment-2374921466
https://bugzilla.mozilla.org/show_bug.cgi?id=1280482
https://github.com/openwebdocs/project/issues/206
=> Fix exact version for cloneInto and exportFunction

css/properties/grid-auto-flow.json
Unroll the ranged values for `css.properties.grid-auto-flow` to be the same as `grid-auto-flow`.
It's not plausible that Safari would've had support for the values after shipping the property itself—what else what would the property have done? Testing in BrowserStack confirms that they were all supported.
Completes work started in https://github.com/mdn/browser-compat-data/pull/22459.
Discovered in https://github.com/web-platform-dx/web-features/pull/1854/
Fixes https://github.com/mdn/browser-compat-data/issues/24535
=> `css.properties.grid-auto-flow.*`: remove Safari version ranges

webextensions/api/privacy.json
The privacy API, at the time already containing both services.alternateErrorPagesEnabled and services.autofillEnabled, was moved out of the experimental status in https://source.chromium.org/chromium/chromium/src/+/607e6522f841933e0d3130c09d33207876850948, which according to https://source.chromium.org/chromium/chromium/src/+/607e6522f841933e0d3130c09d33207876850948:chrome/VERSION was Chrome 18.
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `privacy` Web Extensions api property network.httpsOnlyMode. This sets the feature(s) to a version range based upon the date that the feature was added to BCD with the intent of replacing `true` values with ranged values to eliminate `true` values from BCD.
Commit/PR Adding the …
=> Update Chromium data for privacy Web Extensions api properties

svg/elements/a.json
relates to https://github.com/mdn/browser-compat-data/issues/24162
=> Add spec_url for svg <a> element

api/Document.json, api/Element.json, api/SnapEvent.json, api/Window.json
Chrome 129 supports scroll snap events — [`scrollsnapchange`](https://drafts.csswg.org/css-scroll-snap-2/#scrollsnapchange) and [`scrollsnapchanging`](https://drafts.csswg.org/css-scroll-snap-2/#scrollsnapchanging), which enable code being fired in response to a new scroll snap target being snapped to, and the browser identifying a change in the next snap target to be snapped to (if the gesture were to end).
See the associated [ChromeStatus entry](https://chromestatus.com/feature/5826089036808192) and the [Scroll Snap Events](https://developer.chrome.com/blog/scroll-snap-events) blog post for more context and a guide. 
This PR adds the new events, and the `SnapEvent` event object.
Note: The spec defines the associated event handler properties as being defined on the `GlobalEventHandlers` …
=> Add Scroll Snap events

css/properties/column-span.json
It's not plausible that Edge implemented the `column-span` values after the property itself.
I tested this manually in the oldest Edge version in BrowserStack and I'm assuming it's been supported since Edge 12.
Discovered in the course of https://github.com/web-platform-dx/web-features/pull/1819/
=> `css.properties.column-span`: set plausible Edge versions for values

api/SubtleCrypto.json
Document the fact that for the Ed25519 algorithm in Web Crypto's `crypto.subtle.sign` function, Safari generates randomized signatures as per <a href='https://datatracker.ietf.org/doc/draft-irtf-cfrg-det-sigs-with-noise/'>draft-irtf-cfrg-det-sigs-with-noise</a>, instead of deterministic signatures as per <a href='https://www.rfc-editor.org/rfc/rfc8032'>RFC 8032</a>.
There is a discussion in https://github.com/WICG/webcrypto-secure-curves/issues/28 to make this behavior legal, but as of now it isn't (although in most cases it shouldn't cause interoperability issues). Additionally, even if this becomes legal as per the Web Crypto spec, it may still be noteworthy for developers who (for some reason) require the deterministic behavior of Ed25519 as specified in RFC 8032.
This behavior can be …
=> Document that Safari generates randomized Ed25519 signatures

css/properties/column-fill.json
This corrects the initial version for `column-fill: auto` and `column-fill: balance` in Firefox. It doesn't make sense that they'd be different from the property itself.
In researching this, I found that the initial data for the property itself was incorrect. It was backed out of Firefox 13 and re-landed in Firefox 17.
- https://bugzilla.mozilla.org/show_bug.cgi?id=695222
- https://bugzilla.mozilla.org/show_bug.cgi?id=764567
I tested this manually in BrowserStack for the unprefixed property, to the values shown in the diff. I spot checked some earlier versions, but not completely to Firefox 17 for the prefixed property. Given the bug links, I don't think we need much more than that.
Discovered via https://github.com/web-platform-dx/web-features/pull/1819
=> `css.properties.column-fill`: correct Firefox versions

css/at-rules/page.json
There's some sort of feature-flagged code relating to `@page` in Safari, but actually using `@page` in Safari or Safari TP does nothing.
See https://github.com/mdn/browser-compat-data/issues/24566 and https://bugs.webkit.org/show_bug.cgi?id=15548.
Although https://webkit.org/blog/15798/release-notes-for-safari-technology-preview-202/ contradicts this, but again: test cases point the opposite direction.
Skepticism was noted originally in https://github.com/mdn/browser-compat-data/pull/20144.
Fixes https://github.com/mdn/browser-compat-data/issues/24566
Discovered via https://github.com/web-platform-dx/web-features/pull/1801
=> `css.at-rules.page`: remove erroneous Safari support

css/at-rules/media.json
Closes https://github.com/mdn/browser-compat-data/issues/24580
=> css.at-rules.media.prefers-color-scheme - safari removed "no-preference" value

css/types/resolution.json
Follows up the incomplete update to Safari's support for `resolution` media queries in https://github.com/mdn/browser-compat-data/pull/18706
Test case: https://codepen.io/fvsch/pen/Jqavor
Release notes: https://developer.apple.com/documentation/safari-release-notes/safari-16-release-notes
Resolved bug: https://bugs.webkit.org/show_bug.cgi?id=78087
Fixes https://github.com/mdn/browser-compat-data/issues/20635
Discovered via https://github.com/web-platform-dx/web-features/pull/1673
=> Update Safari support for `css.types.resolution`

css/types/basic-shape.json
`css.types.basic-shape.path` is shown as partially implemented in all browsers, but this information is a summation of the descendant features. This PR undoes this flattening, showing `path()` support commencing with the first of the subfeatures.
Since this is duplicate information, the source is BCD itself (i.e., `css.types.basic-shape.path.{clip-path,d,offset-path,shape-outside}`), though I'm just deleting data rather than introducing new facts.
The existing structure of this data—with subfeatures reiterating a partial implementation of the parent—makes actually consuming this data in web-features impossible. Because the parent feature is shown as not implemented and compute-baseline follows a feature's ancestry (e.g., to know if a feature is behind its parent's prefix), the descendants …
=> Deduplicate `css.types.basic-shape.path` and descendants

css/properties/writing-mode.json
Edge's data was mirrored, but this doesn't really make sense, since `horizontal-tb` is the default value and the parent feature predates Chromium Edge.
I tested this manually in Edge 15. I'm making an educated guess here that Edge 12 also worked.
<details>
<summary>Test code</summary>
```html
<!DOCTYPE html>
<html>
<head>
<title>css.properties.writing-mode</title>
<meta http-equiv="X-UA-Compatible" content="IE=Edge" />
<style>
#t1,
#t2,
#t3,
#t4 {
display: none;
border: 1px solid black;
}
@supports (writing-mode: horizontal-tb) {
#t1 {
display: block;
writing-mode: horizontal-tb;
}
}
@supports (writing-mode: vertical-lr) {
#t2 {
display: block;
writing-mode: vertical-lr;
}
}
@supports (writing-mode: vertical-rl) {
#t3 {
display: block;
writing-mode: vertical-rl;
}
}
@supports …
```
=> `css.properties.writing-mode`: fix faulty Edge mirroring

webextensions/api/declarativeNetRequest.json
Add new declarativeNetRequest RuleConditions responseHeaders and excludedResponseHeaders
https://issues.chromium.org/issues/40727004
https://bugzilla.mozilla.org/show_bug.cgi?id=1877486
https://bugs.webkit.org/show_bug.cgi?id=275158
https://github.com/w3c/webextensions/issues/460
https://developer.chrome.com/docs/extensions/reference/api/declarativeNetRequest#property-RuleCondition-excludedResponseHeaders
https://developer.chrome.com/docs/extensions/reference/api/declarativeNetRequest#property-RuleCondition-responseHeaders
https://developer.chrome.com/docs/extensions/reference/api/declarativeNetRequest#type-HeaderInfo.
Fixes #24186
=> Add new declarativeNetRequest RuleConditions

css/properties/column-count.json
It's not plausible that Edge shipped support for `column-count: auto` after `column-count`.
I tested this manually as far back as Edge 15, in Browser Stack.
Discovered via https://github.com/web-platform-dx/web-features/pull/1819
=> `css.properties.column-count.auto`: set plausible Edge value

svg/elements/animate.json, svg/elements/animateMotion.json, svg/elements/animateTransform.json
EdgeHTML never supported the SMIL SVG animation elements; this PR eliminates three version ranges.
I used the collector tests for these elements in BrowserStack in Edge 18. None passed.
I also spot checked `animateMotion` with an actual working animation to make sure it wasn't some issue with the element interface. It wasn't—it really didn't animate.
Discovered via https://github.com/web-platform-dx/web-features/pull/1771
=> `svg.elements.animate*`: not supported in EdgeHTML

css/properties/max-height.json, css/properties/min-height.json
Correcting some strange discrepancies found in the course of https://github.com/web-platform-dx/web-features/pull/1872.
For the Edge values, I tested with `CSS.supports()` in Edge 13. These are both pretty old and I think it makes more sense that they'd have been there from inception.
For Firefox, I tested with `CSS.supports()` in Firefox 34 and 33 to confirm the result. I assumed the existing data was true.
Fixes https://github.com/mdn/browser-compat-data/issues/24582
https://github.com/web-platform-dx/web-features/pull/1872
=> `css.properties.{min,max}-height`: clean up values for Edge and Firefox

api/AudioEncoder.json
This PR updates and corrects version values for Firefox and Firefox Android for the `AudioEncoder` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/AudioEncoder
=> Update Firefox data for AudioEncoder API

scripts/update-browser-releases/chrome.ts, scripts/update-browser-releases/index.ts
Ensures that Chrome nightly and planned versions are properly updated again.
Looking at https://chromestatus.com/api/v0/channels revealed that the "canary" branch was renamed to "dev", and this explains why nightly versions were no longer updated (and planned versions, which are based on the nightly version).
Noticed here: https://github.com/mdn/browser-compat-data/pull/24538#discussion_r1784755230
=> fix(update-browser-releases): rename Chrome nightly branch to dev

javascript/builtins/JSON.json
Firefox 132 enables the [`JSON.parse()` with source](https://github.com/tc39/proposal-json-parse-with-source) proposal by default, which specifically includes the following features:
- [The `JSON.parse()` `reviver` parameter `context` argument](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse#the_reviver_parameter)
- [`JSON.isRawJSON()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/isRawJSON)
- [`JSON.rawJSON()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/rawJSON)
This PR adds Firefox 132 support for the above features, and sets their `experimental` properties to `false`.
See also https://bugzilla.mozilla.org/show_bug.cgi?id=1913085 for the release bug.
I've …
=> Add Firefox 132 support for JSON.parse with source features

css/properties/overscroll-behavior-x.json, css/properties/overscroll-behavior-y.json, css/properties/overscroll-behavior.json
The `overscroll-behavior` data is inconsistent, with conflicting reports of partial implementation for the same issue and notes placed on the wrong features. I've made an attempt to clean it up.
See https://github.com/mdn/browser-compat-data/issues/24511
I made the assumption that EdgeHTML bugs were not reimplemented in Chromium.
Fixes https://github.com/mdn/browser-compat-data/issues/24511
Discovered via https://github.com/web-platform-dx/web-features/pull/1834/
=> `css.properties.overscroll-behavior{,-x,-y}`: fix EdgeHTML notes and partials

javascript/builtins/Promise.json
[`Promise.try()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/try) is supported in Firefox as of version 132. See https://bugzilla.mozilla.org/show_bug.cgi?id=1905364 for implementation details.
Main project issue: https://github.com/mdn/content/issues/36118
=> Add Promise.try() support for Firefox 132

api/HTMLInputElement.json
It's "supported" in that it is recognized by the browser but there is no code in the file chooser interface on mobile phones to allow selection of a directory when using it.
I tried using this option on a phone and there was no way to choose a folder to upload.
https://bugs.webkit.org/show_bug.cgi?id=271705
https://issues.chromium.org/issues/40248532
https://bugzilla.mozilla.org/show_bug.cgi?id=1887878
Fixes #24357
=> Add note about lack of proper support for webkitdirectory on mobile

api/Notification.json
Firefox 132 supports the [`Notification.silent`](https://developer.mozilla.org/en-US/docs/Web/API/Notification/silent) property.
This PR adds Fx support to that data point.
See the shipping bug at https://bugzilla.mozilla.org/show_bug.cgi?id=1809028 
I wrote a quick test case to test the property: see https://silent-notifications-test.glitch.me/.
I found the results somewhat inconclusive:
- In Firefox Nightly 133, the system notification fires _and_ `n.silent` returns `true`.
- In Firefox beta 132, the system notification doesn't fire, but `n.silent` returns `true` (it supports the property).
- In Firefox release 131, the system notification doesn't fire, and `n.silent` returns `undefined` (it doesn't support the property).
- In the last couple of versions of Chrome and Safari, it all …
=> Add Fx132 support for Notification.silent

api/_globals/createImageBitmap.json
Record a bug with Safari's `createImageBitmap()` options data
Caniuse takes this bug to make the entire feature partially implemented, so I've done the same: https://caniuse.com/createimagebitmap
- WebKit bug: https://bugs.webkit.org/show_bug.cgi?id=237082
- Safari release note: https://developer.apple.com/documentation/safari-release-notes/safari-17-release-notes#Canvas
https://github.com/web-platform-dx/web-features/pull/1707#discussion_r1771670454
=> `api.createImageBitmap.options_premultiplyAlpha_parameter`: add partial and note for `premultiplyAlpha` bug

scripts/update-browser-releases/safari.ts
Ensures that Safari patch versions (e.g. "18.0.1") are ignored when updating the browser releases.
See: https://github.com/mdn/browser-compat-data/pull/24627#discussion_r1787180387
=> enhance(update-browser-releases): ignore Safari patch versions

api/Permissions.json
The docs for `Permissions.query()` had the following string, which I am removing:
> [!NOTE]
> As of Firefox 44, the permissions for [Notifications](/en-US/docs/Web/API/Notifications_API) and [Push](/en-US/docs/Web/API/Push_API) have been merged. If permission is granted (e.g. by the user, in the relevant permissions dialog), `navigator.permissions.query()` will return `true` for both `notifications` and `push`.
Moved this info into the BCD under the respective permissions, with a note that they are aliases. The first version is 46 and not 44, so the docs were wrong "at best".
Related docs work in https://github.com/mdn/content/issues/35765
=> FF46 makes push and notifications permission aliases

api/WebGL2RenderingContext.json, api/WebGLRenderingContext.json
FF132 supports [`WebGLRenderingContext.drawingBufferColorSpace`](https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/drawingBufferColorSpace) in https://bugzilla.mozilla.org/show_bug.cgi?id=1885491
Related docs work can be tracked in https://github.com/mdn/content/issues/36112
=> FF132 WebGL drawingBufferColorSpace supported

css/properties/counter-reset.json
Add incomplete support (partial_implementation + notes) for the special `list-item` counter for the `counter-reset` CSS property in Chrome and Safari.
I'm currently unable to test it explicitly for Edge.  
I also haven't found time to test behaviors for the other `counter-*` properties.
- [Chrome bug entry](https://issues.chromium.org/issues/338233131)
- [Safari bug entry](https://bugs.webkit.org/show_bug.cgi?id=260436)
Fixes #23070
=> Chrome/Safari only partially support list-item counter

css/at-rules/media.json
According to the 2018 "[Media Queries Level 4 specification draft](https://drafts.csswg.org/mediaqueries-4/#mf-deprecated)", the `device-width`, `device-height` and `device-aspect-ratio` media features are deprecated. They are kept for backward compatibility, but should be avoided.
=> chore(css): Add `spec_url` to deprecated device-related `@media` features

css/at-rules/custom-media.json
Add "WebView on iOS" I missed on the initial PR https://github.com/mdn/browser-compat-data/pull/24338.
=> fix(css): mirror WebView support for `@custom-media`

api/HTMLImageElement.json, api/HTMLLinkElement.json, api/HTMLScriptElement.json, api/Request.json, html/elements/img.json, html/elements/link.json, html/elements/script.json, http/headers/Link.json
We're enabling `fetchpriority` by default in Fx 132
https://bugzilla.mozilla.org/show_bug.cgi?id=1854077
https://github.com/mdn/content/issues/36121
=> fetchPriority enabled by default in Firefox 132

scripts/generate-types.ts
Runs `tsc` with the `--skipLibCheck` to avoid the following error:
```
error TS2451: Cannot redeclare block-scoped variable 'TrustedHTML'.
```
Note: This option is [already set in `tsconfig.json`](https://github.com/mdn/browser-compat-data/blob/2f4e7db88bb9051db98c46df0cdc87e9f05b6b42/tsconfig.json#L16), but this isn't taken into consideration for the `tsc` call.
=> fix(generate-types): run tsc with --skipLibCheck

api/Request.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `cache.only-if-cached` member of the `Request` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/Request/cache/only-if-cached
=> Update Safari data for api.Request.cache.only-if-cached

api/SVGElement.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `className` member of the `SVGElement` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/SVGElement/className
=> Update Safari data for api.SVGElement.className

api/SVGAnimatedTransformList.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `SVGAnimatedTransformList` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/SVGAnimatedTransformList
=> Update Safari data for SVGAnimatedTransformList API

api/SVGAnimatedString.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `SVGAnimatedString` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/SVGAnimatedString
=> Safari 3 added SVGAnimatedString API support

api/SubtleCrypto.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `deriveKey` member of the `SubtleCrypto` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/SubtleCrypto/deriveKey
=> Safari 11 added api.SubtleCrypto.deriveKey support

api/Response.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `Response.accept_readablestream` member of the `Response` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/Response/Response/accept_readablestream
=> Safari 10.1 added api.Response.Response.accept_readablestream support

api/ReadableStreamDefaultReader.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `ReadableStreamDefaultReader` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/ReadableStreamDefaultReader
=> Safari 10 added ReadableStreamDefaultReader API support

api/ReadableStreamDefaultController.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `ReadableStreamDefaultController` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/ReadableStreamDefaultController
=> Safari 10 added ReadableStreamDefaultController API support

api/MediaList.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `toString` member of the `MediaList` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/MediaList/toString
=> Safari 1 supported api.MediaList.toString

api/MediaController.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `MediaController` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/MediaController
=> Safari 7 added MediaController API support

api/HTMLFormControlsCollection.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `HTMLFormControlsCollection` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/HTMLFormControlsCollection
=> Safari 3 added HTMLFormControlsCollection API support

api/Response.json
This PR updates and corrects version values for Firefox and Firefox Android for the `Response.accept_readablestream` member of the `Response` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/Response/Response/accept_readablestream
=> Safari 39 added api.Response.Response.accept_readablestream support

api/RTCStatsReport.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `type_inbound-rtp` member of the `RTCStatsReport` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/RTCStatsReport/type_inbound-rtp
=> Chromium 79 improved api.RTCStatsReport.type_inbound-rtp support

api/BaseAudioContext.json
This PR updates and corrects version values for Microsoft Edge for the `BaseAudioContext` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/BaseAudioContext
=> Edge 12 supported BaseAudioContext API

webassembly/bulk-memory-operations.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `bulk-memory-operations` WebAssembly feature. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/webassembly/bulk-memory-operations
=> Chromium 75 added bulk-memory-operations WebAssembly feature

javascript/grammar.json
This PR updates and corrects version values for Opera and Opera Android for the `numeric_separators` member of the `grammar` JavaScript feature. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/javascript/grammar/numeric_separators
=> Opera Android supports javascript.grammar.numeric_separators

javascript/builtins/Intl/DateTimeFormat.json
This PR updates and corrects version values for Opera and Opera Android for the `DateTimeFormat.DateTimeFormat.options_parameter.options_dayPeriod_parameter` member of the `Intl` JavaScript builtin. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/javascript/builtins/Intl/DateTimeFormat/DateTimeFormat/options_parameter/options_dayPeriod_parameter
=> Opera Android supports javascript.builtins.Intl.DateTimeFormat.DateTimeFormat.options_parameter.options_dayPeriod_parameter

javascript/builtins/Intl/Collator.json
This PR updates and corrects version values for Opera and Opera Android for the `Collator.Collator.options_collation_parameter` member of the `Intl` JavaScript builtin. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/javascript/builtins/Intl/Collator/Collator/options_collation_parameter
=> Opera Android supports javascript.builtins.Intl.Collator.Collator.options_collation_parameter

webassembly/mutable-globals.json
This PR updates and corrects version values for all browsers for the `mutable-globals` WebAssembly feature. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/webassembly/mutable-globals
=> Chrome 69 + Firefox 62 added mutable-globals WebAssembly feature

api/FontFaceSetLoadEvent.json
the `FontFaceSetLoadEvent` interface is not exposed to workerscope , only available in window scope; though it is still used on font-related events
see https://issues.chromium.org/issues/40498266 and https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/css/font_face_set_load_event.idl
Note per my research by view  https://github.com/chromium/chromium/blob/main/third_party/blink/renderer/core/css/font_face_set_load_event.idl history, the interface is never exposed to worker (a todo at present)
tested with https://worker-playground.glitch.me/:
For latest Chrome:
For latest Firefox:
=> Chromium doesn't support `FontFaceSetLoadEvent` in workers

api/FetchEvent.json
This PR removes the `replacesClientId` member of the `FetchEvent` API from BCD. Per the [data guidelines](https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines/index.md#removal-of-irrelevant-features), this feature can be considered irrelevant and may be removed from BCD accordingly. Even if the current data suggests that the feature is supported, lack of support has been confirmed by the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.3).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/FetchEvent/replacesClientId
=> Remove api.FetchEvent.replacesClientId from BCD

css/properties/text-emphasis-position.json
Added firefox support for `text-emphasis-position: auto` value.
Working on [#36125](https://github.com/mdn/content/issues/36125)
Tested in:
- Firefox Nightly 133.0a1 - ✅ supported
- Firefox Beta 132.0b5 - ✅ supported
- Chrome Canary 131.0.6766.0 - ❌ unsupported
- Edge Canary 131.0.2883.0 - ❌ unsupported
- Safari 17.6 - ❌ unsupported
- [RESOLVED: add `auto` value for `text-emphasis-position`](https://github.com/w3c/csswg-drafts/issues/1198#issuecomment-2358986319)
- Content PR - working on this
- Firefox Release note PR - working on this
=> Firefox 132 supports `text-emphasis-position: auto`

api/USB.json, api/USBAlternateInterface.json, api/USBConfiguration.json, api/USBConnectionEvent.json, api/USBDevice.json, api/USBEndpoint.json, api/USBInTransferResult.json, api/USBInterface.json, api/USBIsochronousInTransferPacket.json, api/USBIsochronousInTransferResult.json, api/USBIsochronousOutTransferPacket.json, api/USBIsochronousOutTransferResult.json, api/USBOutTransferResult.json, api/WorkerNavigator.json
the WebUSB API is not exposed to shared worker and service worker (except for webextension service workers) in chromium, which should be according to the [spec](https://wicg.github.io/webusb/)
no related browser issue is found
see [chromium source code](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/modules/webusb/)
this can be test using https://worker-playground.glitch.me/
~Note: I'm not sure if partial_implementation or impl_url key should be added or not~
---
so full chain is:
1. expose to dedicated worker (M70)
https://github.com/chromium/chromium/commit/841d469fc77210d9044fcaaa9acbdc1b0066de27
https://github.com/chromium/chromium/commit/3267532a0e80b0aeb73ec4e72434df630bc9ce63
https://github.com/chromium/chromium/commit/6ed4277143bc91de86dfd3df0ae …
=> Chromium only partially supports WebUSB API in web workers

api/_globals/console.json
See https://github.com/mdn/browser-compat-data/issues/19347
See https://bugzilla.mozilla.org/show_bug.cgi?id=1730896
Test: type `console.profileEnd()` in Fx's console and read the message.
Oversight in https://github.com/mdn/browser-compat-data/pull/19387 which should have updated both.
Unblocks https://github.com/web-platform-dx/web-features/pull/1839
=> Firefox 102+ doesn't support console.profileEnd

webextensions/manifest/action.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `theme_icons` member of the `action` Web Extensions manifest property. This fixes #23151, which contains the supporting evidence for this change.
=> Chromium doesn't support webextensions.manifest.action.theme_icons

api/FileSystemWritableFileStream.json
This PR updates and corrects version values for Chrome Android for the `FileSystemWritableFileStream` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.7.1).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/FileSystemWritableFileStream
=> Chrome Android 109 adds FileSystemWritableFileStream API support

api/IDBDatabase.json
This is a quick fix to resolve #23255.  This was an oversight when reviewing #23010.
Ultimately, https://github.com/openwebdocs/mdn-bcd-collector/issues/1614 will fully resolve the issue by introducing subfeatures for all of the parameters and their values.
=> Fix feature name and description for IDBDatabase.transaction subfeature

css/properties/object-position.json
This PR adds the missing `applies_to_iframe_elements` member of the `object-position` CSS property. This fixes #23586, which contains the supporting evidence for this change.
Additional Notes: The test code was copied and adapted to a local server, then manually run on Firefox 36 and old Chrome/Safari versions to confirm support.
=> Firefox 36+ applies object-position to iframes

css/properties/font-variant-position.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `font-variant-position` CSS property. This fixes #24136, which contains the supporting evidence for this change.
=> Chromium doesn't support font-variant-position

css/properties/white-space-collapse.json
This PR adds the missing `preserve-spaces` member of the `white-space-collapse` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.1).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/white-space-collapse/preserve-spaces
=> Firefox 124 added `white-space-collapse: preserve-spaces`

css/properties/border-collapse.json
This PR adds the missing features of the `border-collapse` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.1).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/border-collapse
=> Add `border-collapse: collapse` and `border-collapse: separate`

css/properties/clip.json
This PR adds the missing `auto` member of the `clip` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.1).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/clip/auto
=> Add `clip: auto`

css/properties/text-underline-position.json
https://webkit.org/blog/15790/release-notes-for-safari-technology-preview-201/
=> Safari TP 201 supports `text-underline-position: left | right`

css/properties/column-width.json
This PR adds the missing `auto` member of the `column-width` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.1).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/column-width/auto
=> Add `column-width: auto`

html/elements/meter.json
`api.HTMLMeterElement` and `css.properties.appearance.meter` say "12" for Edge which is more precise than "≤18" and so `html.elements.meter` should say the same, so this PR updates that.
Unblocks https://github.com/web-platform-dx/web-features/pull/1419
=> Sync html.elements.meter with api.HTMLMeterElement

css/properties/display.json
This PR adds the missing `none.option_is_hidden` member of the `display` CSS property. The data comes from manual testing, running test code through BrowserStack, SauceLabs, custom VMs and/or locally.
Test Code:
```html
<style id="test-style">
#hidden {
display: none;
}
</style>
<select>
<option>One</option>
<option id="hidden">Two</option>
<option>Three</option>
</select>
```
Additional Notes: This fixes #24247.
=> Add missing css.properties.display.none.option_is_hidden feature

api/GPUCanvasContext.json
This PR adds two new [WebGPU](https://gpuweb.github.io/gpuweb) features added recently in Chrome:
- The [`GPUCanvasContext.getConfiguration()`](https://gpuweb.github.io/gpuweb/#dom-gpucanvascontext-getconfiguration) method, added in Chrome 131 (see relevant [ChromeStatus](https://chromestatus.com/feature/6195110870777856) entry).
- The `GPUCanvasContext` configuration [`toneMapping`](https://gpuweb.github.io/gpuweb/#dom-gpucanvasconfiguration-tonemapping) option, added in Chrome 129 (see relevant [ChromeStatus](https://chromestatus.com/feature/6196313866895360) entry).
Features testing in Chrome 131 with the following snippet:
```js
const canvas = document.querySelector("canvas");
const context = canvas.getContext("webgpu");
async function init() {
if (!navigator.gpu) {
throw …
```
=> Add toneMapping and getConfiguration()

webassembly/non-trapping-float-to-int-conversions.json
This PR updates and corrects version values for all browsers for the `non-trapping-float-to-int-conversions` WebAssembly feature. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/webassembly/non-trapping-float-to-int-conversions
=> Update all browsers data for non-trapping-float-to-int-conversions WebAssembly feature

webassembly/sign-extension-operations.json
This PR updates and corrects version values for all browsers for the `sign-extension-operations` WebAssembly feature. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/webassembly/sign-extension-operations
=> Update all browsers data for sign-extension-operations WebAssembly feature

lint/fix.ts, lint/fixer/browser-order.ts, lint/fixer/descriptions.ts, lint/fixer/feature-order.ts, lint/fixer/flags.ts, lint/fixer/links.ts, lint/fixer/mdn-urls.ts, lint/fixer/mirror.ts, lint/fixer/property-order.ts, lint/fixer/statement-order.ts, lint/fixer/status.ts, lint/utils.ts
Allows running `npm run lint:fix -- --only=mdn_urls` to selectively only fix MDN urls.
Note: This adds the `--only` option only to the `lint:fix` script, not the `lint` script.
```
% npm run lint:fix -- --help
> @mdn/browser-compat-data@5.6.5 lint:fix
> node --loader=ts-node/esm --no-warnings=ExperimentalWarning lint/fix.ts --help
fix.ts [files..]
Positionals:
files...  The files to fix (leave blank to test everything)           [string]
Options:
--help     Show help                                                 [boolean]
--version  Show version number                                       [boolean]
--only     The checks to run
[array] [choices: "browser_order", "feature_order", "property_order", "stateme
nt_order", "descriptions", "flags", "links", "mdn_urls", "status", "mirror"]
``` …
=> enhance(lint/fix): add --only option

scripts/traverse.test.ts, scripts/traverse.ts
Adds `deprecated` to traverse. 
To limit to only deprecated files-
- `npm run traverse -- --deprecated`
- `npm run traverse -- --dp`
- `npm run traverse -- --deprecated true`
To limit to only non-deprecated files-
- `npm run traverse -- --no-deprecated`
- `npm run traverse -- --no-dp`
- `npm run traverse -- --deprecated false`
Note that if a parent key is deprecated and a child is not, running with `--no-deprecated` will not return the child. I assume non-deprecated children of deprecated parents are a result of bad data, but that could be an incorrect assumption.
Fixes #24609
=> Add deprecated, experimental and standard track flags to traverse

scripts/traverse.test.ts, scripts/traverse.ts
Combines status-related filters into a single object, and moves it to the final argument to unbreak the breaking changes.
Some examples:
```
npm run traverse -- ---status.deprecated // Only depreceated
npm run traverse -- --no-status.deprecated // Only non-deprecated
npm run traverse -- --x  // Only deprecated
npm run traverse -- --no-x // Only non-deprecated
npm run traverse -- --status.standard_track false --support.experimental // Only non-standard track experimental
npm run traverse -- --no-x --s --no-e // Only non-deprecated, standard track, non-experimental
```
Fixes #24609, unbreaks #24707
=> Combine status options in traverse

api/CloseWatcher.json
FF321 supports [`CloseWatcher`](https://developer.mozilla.org/en-US/docs/Web/API/CloseWatcher) in https://bugzilla.mozilla.org/show_bug.cgi?id=1888729 behind the pref `dom.closewatcher.enabled`.
This updates the feature.
Related docs work can be tracked in https://github.com/mdn/content/issues/36126
=> FF132 CloseWatcher behind pref

api/MediaStreamTrack.json
Firefox 132 has added support for [`MediaStreamTrack.getCapabilities()`](https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrack/getCapabilities) (and by extension, the capabilities object returned by the method).
This PR updates the Firefox support data point for this method to 132.
See https://bugzilla.mozilla.org/show_bug.cgi?id=1179084 for the implementation bug.
I tested it using the following test case found in the implementation bug:
```
(await navigator.mediaDevices.getUserMedia({video:true, audio:true})).getTracks().map(t => t.getCapabilities())
```
Main project issue: https://github.com/orgs/mdn/projects/12/views/6?pane=issue&itemId=81563838
=> Add Fx132 support for MediaStreamTrack.getCapabilities()

api/WakeLock.json
`WakeLock` is marked as partially implemented; this removes the partial implementation flag, but lets the note stand (it's accurate).
I think this is weird and noteworthy. But it's otherwise inside the behaviors permitted by the spec and broadly compatible with other browsers on other platforms, so I ultimately came to the conclusion that it should _not_ be marked as partially implemented.
First, the spec. It seems to give wide latitude to implementers to arbitrarily ignore wake lock requests. These two points specifically:
- [Auto-releasing wake locks](https://w3c.github.io/screen-wake-lock/#auto-releasing-wake-locks)
> A user agent may release a wake lock at any time.
- [A note](https://w3c.github.io/screen-wake-lock/#ref-for-dfn-acquire-a-wake-lock-2) in the [The <code>request()</code> …
=> `api.WakeLock`: remove partial from Safari on iOS

api/HTMLElement.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `contentEditable.plaintext-only` member of the `HTMLElement` API. The data comes from manual testing, running test code through BrowserStack, SauceLabs, custom VMs and/or locally.
Test Code:
```
document.body.contentEditable = 'plaintext-only'; console.log(document.body.contentEditable == 'plaintext-only');
```
=> Update Safari data for api.HTMLElement.contentEditable.plaintext-only

javascript/regular_expressions.json
- added version_added for regexp modifiers for ff
- tested with [https://codepen.io/CodeRedDigital/pen/GRbEOLE](https://codepen.io/CodeRedDigital/pen/GRbEOLE)
- Firefox Nightly 133.0a1
- Firefox Beta 132.0b7
- [Firefox Release Note PR](https://github.com/mdn/content/pull/36381)
=> Firefox 132 ships regexp modifiers

api/HTMLElement.json, html/global_attributes.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `autofocus` member of the `global_attributes` HTML feature. This fixes #23457, which contains the supporting evidence for this change.
=> Update Safari data for html.global_attributes.autofocus

api/CSSMarginRule.json, api/GPUAdapter.json, api/Request.json, api/XRFrame.json, api/XRHand.json, api/XRInputSource.json, api/XRJointPose.json, api/XRJointSpace.json, css/at-rules/page.json, css/properties/anchor-scope.json, css/properties/font-variant-emoji.json, css/selectors/details-content.json
The @openwebdocs [BCD collector project](https://github.com/openwebdocs/mdn-bcd-collector) v10.12.5 found new features shipping in Chrome 131 beta which was released last week. Currently, the collector covers about 90% of BCD, so the following list might not be exhaustive. Also, if a feature is in Chrome Canary/behind origin trials/enrollment, it is not considered here.
With this PR, BCD considers the following 53 features as shipping in Chrome 131:
- api.CSSMarginRule
- api.CSSMarginRule.name
- api.CSSMarginRule.style
- api.GPUAdapter.requestAdapterInfo (removal)
- api.GPUCanvasContext.getConfiguration
- api.HID.worker_support
- api.HIDConnectionEvent.worker_support
- api.HIDDevice.worker_support
- api.HIDInputReportEvent.worker_support
- api.Request.duplex
- api.WorkerNavigator.hid
- …
=> Updates for Chrome 131 beta

api/NavigationActivation.json
same as title (the chromium's issue has been marked as fixed)
see the proposal issue https://github.com/whatwg/html/issues/9760 and PR https://github.com/whatwg/html/pull/9856
=> Remove Chromium impl_url and add Firefox impl_url for `NavigationActivation`

.github/workflows/node.js.yml
Currently, tests run twice on every PR, once for the `push` event, and once for the `pull_request` event.
=> fix(workflows): prevent tests from running twice on every pull request

.github/workflows/update-mdn-urls.yml, api/HTMLSelectElement.json
Adds a workflow that runs on the Dependabot PRs for `ddbeck/mdn-content-inventory`, updates the MDN urls, and pushes the updates to the PR.
Used the [update-browser-releases](https://github.com/mdn/browser-compat-data/blob/main/.github/workflows/update-browser-releases.yml) workflow as a template.
Follow-up of https://github.com/mdn/browser-compat-data/pull/24669.
Unblocks https://github.com/mdn/browser-compat-data/pull/23810.
=> feat(workflows): update MDN urls in mdn-content-inventory Dependabot PR

http/headers/Clear-Site-Data.json
Evidence:
- The WPTs pass https://wpt.fyi/results/clear-site-data?label=master&label=experimental&aligned
- It looks like support was added when the header was first implemented https://github.com/WebKit/WebKit/commit/c65efd2b205ccaef913dff861a6e354dbdb9a212#diff-64f7d88a9c62e60e7e2fca2cdba58ccb1058ead7c9d205ff06625b1e0dd4552bR749 (which makes sense, these directives are quite essential for the header to work).
=> Safari 17 Clear-Site-Data supports "cache", "cookies", "storage" directives

api/NavigateEvent.json
this property is never removed from chromium implement, though the property is non-standard and deprecated
between M102 and M104, only `canTransition` is supported; M105+, both `canTransition` and `canIntercept` are supported, and the two property are the same
this is updated in https://github.com/mdn/browser-compat-data/pull/18105
but note that the property still existed in [source code](https://github.com/chromium/chromium/blob/main/third_party/blink/renderer/core/navigation_api/navigate_event.idl#L13), and it has changed to be an alias for `canIntercept` in https://github.com/chromium/chromium/commit/d53817e29d5e857782ff8d977dbc3b89eb53831b, which is landed in [M105](https://chromiumdash.appspot.com/commit/d53817e29d5e857782ff8d977dbc3b89eb53831b)
check chromium source and observe in …
=> Fix data version of `NavigateEvent.canTransition`

api/Permissions.json
the data is added in https://github.com/mdn/browser-compat-data/pull/22525, notice the chrome status says permission policy, not permission descriptor
1. if trying in to test in console (latest stable chrome), a `TypeError` will report
2. in [chromium source code](https://github.com/chromium/chromium/blob/main/third_party/blink/renderer/modules/permissions/permission_descriptor.idl#L17), there is a `bluetooth` item, but it is comment, which means it is not support in real browser (and notice that when the item added in https://github.com/chromium/chromium/commit/9e5d5b7ac865085906a106d1408e101ceefedea6#diff-8ca96e3c008c457658e681b87bade1fdf5e235e551a34c8959c79ef21a8b4489, it is already comment and no change happens after that)
also, no related info found when viewing other …
=> Remove bluetooth permission descriptor

css/properties/align-self.json, css/properties/justify-self.json, css/properties/place-self.json
There’s a new “absolutely-positioned boxes” context for box self-alignment added in Chrome 122.
[See the demo](https://codepen.io/pepelsbey/pen/xxvLBYZ).
[The spec says:](https://drafts.csswg.org/css-align/#align-self-property)
> `align-self`
> Applies to: flex items, grid items, and **absolutely-positioned boxes**
I couldn’t find anything in the [Chrome 122 release notes](https://developer.chrome.com/blog/new-in-chrome-122/), so I had to pinpoint the version.
I’m improvising here with the “positioned_boxes” key. Not sure how to properly make it work.
=> Add positioned_boxes context for align/justify/place-self

api/Navigator.json, api/WorkerNavigator.json
`hardwareConcurrency` was shipped, then unshipped, then reinstated.
See https://bugs.webkit.org/show_bug.cgi?id=233381.
I also tested this manually in BrowserStack to confirm the 4 or 8 cores limitation.
https://github.com/web-platform-dx/web-features/pull/1931#discussion_r1812881017
Fixes https://github.com/mdn/browser-compat-data/issues/20429.
=> Safari 15.4 reinstates`api.{Worker,}Navigator.hardwareConcurrency`

api/WorkerGlobalScope.json
This was probably never supported.
This is very difficult to test because it requires changing the system language settings, which I can't do in BrowserStack. And I don't have a device that I can directly test with. But I learned a few things:
- In a window, `languagechange` fires in contemporary macOS Safari.
- In a worker, `languagechange` does **not** fire in macOS Safari and `onlanguagechange` doesn't appear to be real (e.g., you can assign arbitrary types to it, unlike the window equivalent).
- Following the blames shows this data was originally migrated from the wiki. https://github.com/mdn/browser-compat-data/pull/982
- Searching webkit/webkit shows evidence of the window exposure, like tests, but I couldn't find anything even hinting at worker exposure.
Taken together, I'm rather …
=> Safari iOS doesn't support `api.WorkerGlobalScope.languagechange_event`

api/Request.json, api/_globals/fetch.json
Firefox 132 ships the [`fetch()` `keepalive`](https://developer.mozilla.org/en-US/docs/Web/API/RequestInit#keepalive) option in Nightly and early Beta builds.
This PR adds Fx `preview` support for `api.fetch` (as used for [`Window.fetch()`](https://developer.mozilla.org/en-US/docs/Web/API/Window/fetch) and [`WorkerGlobalScope.fetch()`](https://developer.mozilla.org/en-US/docs/Web/API/WorkerGlobalScope/fetch)) and `Request.keepalive` (doesn't yet have a docs page, but I'm going to change that).
It also adds a data point for the `init.keepalive` parameter of the [`Request()` constructor](https://developer.mozilla.org/en-US/docs/Web/API/Request/Request), which just copies the same data from the other places.
See https://bugzilla.mozilla.org/show_bug.cgi?id=1906952 for the shipping bug.
Docs …
=> Firefox previews fetch() keepalive support

api/Window.json
This PR updates and corrects version values for Safari iOS/iPadOS for the `open` member of the `Window` API. This fixes #21661, which contains the supporting evidence for this change.
=> Update Safari iOS data for api.Window.open

css/properties/display.json
Add a feature representing a specification change, where descendants of `display: contents` must be accessible.
`display: contents` has severe accessibility issues ([for example](https://ericwbailey.design/published/display-contents-considered-harmful/)). It's difficult for web-features to generate a status for `display: contents` without data reflecting this fact. This PR attempts to add the data needed to accurately report support for `display: contents` in a non-surprising way.
Admittedly, this is a weird feature. No browser has actually shipped this "feature" yet, though there's work in progress in Chrome ([Chrome Platform Status](https://chromestatus.com/feature/6237396851228672); [intent to ship](https://groups.google.com/a/chromium.org/g/blink-dev/c/9hvYiSZy868/m/8fJc_92wAAAJ)) and …
=> Add feature for focusable `display: contents` elements

api/HTMLAnchorElement.json, html/elements/a.json
Fix https://github.com/mdn/browser-compat-data/issues/24736
There is no specification link yet, see https://github.com/whatwg/html/pull/3870
Chrome 81 is from https://chromestatus.com/feature/6298864638230528
I2S https://groups.google.com/a/chromium.org/g/blink-dev/c/gDLl4fKCr8Y/m/35aaeQ0fAgAJ
The collector says Chrome 129 for this one. Not sure what is correct.
=> Add hrefTranslate attribute

css/properties/column-width.json
I tested this back to Edge 15. It's a pretty ancient feature and has probably been supported since the beginning.
Tested manually in BrowserStack.
Discovered via https://github.com/web-platform-dx/web-features/pull/1972.
Previously: https://github.com/mdn/browser-compat-data/pull/24587
=> `css.properties.column-width.auto`: show support in EdgeHTML

api/EventSource.json
FF133 exposes `EventSource` in ServiceWorkers in https://bugzilla.mozilla.org/show_bug.cgi?id=1681218.
The spec says that it should be in all types of workers, so added a separate version and made the old one "partial implementation".
Related work can be tracked in https://github.com/mdn/content/issues/36531
=> FF133 EventSource in ServiceWorkers

api/SharedStorage.json
From collector tests I can observe more `SharedStorage` members shipping from Chrome 126 onwards.
According to Chromestatus and I2S email, this apparently shipped in Chrome 125. Not sure who is right.
https://chromestatus.com/feature/5145686840705024
https://groups.google.com/a/chromium.org/g/blink-dev/c/JJFldgplL58/m/RrkZ-IoMAwAJ
cc @chrisdavidmills
=> Add more members to SharedStorage

api/DelegatedInkTrailPresenter.json
The `InkPresenter` interface never saw the light. Instead it has always been `DelegatedInkTrailPresenter` in implementations. The spec got corrected about this last month, see https://github.com/WICG/ink-enhancement/issues/35.
Also, `expectedImprovement` has been removed from the spec (https://github.com/WICG/ink-enhancement/pull/34) and dropped in Chrome 130 (https://chromestatus.com/feature/5194773674328064)
=> InkPresenter -> DelegatedInkTrailPresenter

api/HTMLElement.json
This fixes an error I injected in #24249 stating that the `HTMLElement.autocorrect` is a partial implementation. That was because I thought it was an error to return `true`/`false`. Actually that is what the spec states (the value should be set as `on`/`off` in HTML but returns true/false through the API).
Note that the corresponding global attribute is still partial.
This is part of https://github.com/mdn/content/pull/35692
=> HTMLElement.autocorrect full implementation

api/GPUDevice.json
Chrome 128 deprecates setting depth bias for lines and points ([Chrome issue](https://issues.chromium.org/issues/352567424), [spec change](https://github.com/gpuweb/gpuweb/pull/4743)).
This PR adds a datapoint for this change in behavior to `GPUDevice.createRenderPipeline()` and `GPUDevice.createRenderPipelineAsync()`.
See the [description and data source](https://developer.chrome.com/blog/new-in-webgpu-128#deprecate_setting_depth_bias_for_lines_and_points)
See related MDN project issue: https://github.com/mdn/content/issues/36341
=> Chromium 131 validates depth bias on line and point topologies

api/ImageDecoder.json, api/ImageTrack.json, api/ImageTrackList.json, api/Request.json, api/WorkerNavigator.json, javascript/builtins/Uint8Array.json
The @openwebdocs [BCD collector project](https://github.com/openwebdocs/mdn-bcd-collector) v10.12.5 found new features shipping in Firefox 133 beta which was released today. Currently, the collector covers about 90% of BCD, so the following list might not be exhaustive. Also, if a feature is in Firefox Nightly only, it is not considered here.
With this PR, BCD considers the following 29 features as shipping in Firefox 133:
- api.ImageDecoder
- api.ImageDecoder.ImageDecoder
- api.ImageDecoder.close
- api.ImageDecoder.complete
- api.ImageDecoder.completed
- api.ImageDecoder.decode
- api.ImageDecoder.isTypeSupported_static
- api.ImageDecoder.reset
- api.ImageDecoder.tracks
- api.ImageDecoder.type
- api.ImageTrack
- api.ImageTrack.animated
- api.ImageTrack.frameCount
- …
=> Updates for Firefox 133 beta

css/properties/align-self.json, css/properties/justify-self.json, css/properties/place-self.json
Better naming for the new context where `align/justify/place-self` now work.
```diff
- "positioned_boxes": {
+ "position_absolute_context": {
```
A follow-up for the https://github.com/mdn/browser-compat-data/pull/24789
=> Update context name for align/justify/place-self

RELEASE_NOTES.md, package-lock.json, package.json
(This release was generated by the project's release script.)
- `api.InkPresenter` ([#24856](https://github.com/mdn/browser-compat-data/pull/24856))
- `api.InkPresenter.expectedImprovement` ([#24856](https://github.com/mdn/browser-compat-data/pull/24856))
- `api.InkPresenter.presentationArea` ([#24856](https://github.com/mdn/browser-compat-data/pull/24856))
- `api.InkPresenter.updateInkTrailStartPoint` ([#24856](https://github.com/mdn/browser-compat-data/pull/24856))
- `css.properties.align-self.positioned_boxes` ([#24865](https://github.com/mdn/browser-compat-data/pull/24865))
- `css.properties.justify-self.positioned_boxes` ([#24865](https://github.com/mdn/browser-compat-data/pull/24865))
- `css.properties.place-self.positioned_boxes` …
=> Release v5.6.11

css/properties/transition.json
`css.properties.transition.transition-behavior` support should be the same as `css.properties.transition-behavior`, as it is just the shorthand version.
`CSS.supports('transition', 'allow-discrete')` passes in Safari and Firefox.
The implementing issue for Firefox- https://bugzil.la/1805727 is closed.
=> Update `transition.transition-behavior` to mirror `transition-behavior`

api/CSSViewTransitionRule.json, api/Document.json, api/PageRevealEvent.json, api/PageSwapEvent.json, api/ViewTransition.json, api/ViewTransitionTypeSet.json, api/Window.json, css/properties/view-transition-class.json, css/properties/view-transition-name.json, css/selectors/view-transition-group.json, css/selectors/view-transition-image-pair.json, css/selectors/view-transition-new.json, css/selectors/view-transition-old.json, css/selectors/view-transition.json
https://bugzilla.mozilla.org/show_bug.cgi?id=1823896 for implement CSS View Transitions 1
https://bugzilla.mozilla.org/show_bug.cgi?id=1860854 for implement CSS View Transitions 2
https://bugzilla.mozilla.org/show_bug.cgi?id=1881438 for implement `pageswap` event & `PageSwapEvent` interface
https://drafts.csswg.org/css-view-transitions-1/
https://drafts.csswg.org/css-view-transitions-2/
https://github.com/whatwg/html/pull/9818 for `pagereveal` event & `PageRevealEvent` interface
https://github.com/whatwg/html/pull/10002 for `pageswap` event & `PageSwapEvent` interface
=> Add Firefox impl_url for CSS View Transition (level 1 & level 2)

api/AbortSignal.json
Chrome 103-123 never aborted `AbortSignal.timeout()` with a `TimeoutError`.
Tested with https://developer.mozilla.org/en-US/play?id=Ully%2FbncqOhlj%2FACZTtIJLg1HtNlADkcgP4iWysbI6ercjFSzCJWkHPuAi5NNQRqGhL5ZlO5oTWm7TEr in BrowserStack Live, see [this comment](https://github.com/mdn/browser-compat-data/issues/20381#issuecomment-2405413530).
Fixes #20381.
=> Add Chromium note about `AbortSignal.timeout()` 

.github/workflows/update-mdn-urls.yml
Fixes a syntax error in the `update-mdn-urls` workflow, because `paths` and `paths-ignore` apparently cannot be used together, even if [the GitHub docs suggest otherwise](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore).
Follow-up of these:
- https://github.com/mdn/browser-compat-data/pull/24825
- https://github.com/mdn/browser-compat-data/pull/24860
- https://github.com/mdn/browser-compat-data/pull/24862
=> fix(update-mdn-urls): merge paths + paths-ignore

css/types/overflow.json
`css.types.overflow.overlay` should be marked as deprecated.
https://drafts.csswg.org/css-overflow/#valdef-overflow-overlay says:
`User agents must also support the overlay keyword as a [legacy value alias](https://drafts.csswg.org/css-cascade-5/#css-legacy-value-alias) of [auto](https://drafts.csswg.org/css-overflow/#valdef-overflow-auto).`
This meets the [criteria](https://github.com/mdn/browser-compat-data/blob/1c6a1cb16e7eeca7dc862b9ef10dd307fce8f5df/docs/data-guidelines/index.md#setting-deprecated) to mark a key as deprecated.
=> Mark overflow.overlay as deprecated

css/at-rules/media.json
Support for inherited color-scheme on SVG images was added to Chromium in https://issues.chromium.org/issues/40232082 (Chromium 111)
Support for inherited color-scheme on iframes was added to Chromium in https://issues.chromium.org/issues/40234347 (Chromium 129)
=> Chromium 129 respects inherited color-scheme on iframes

http/headers/Permissions-Policy.json
these notes in safari should link to webkit issue, not firefox issue, this might be a bug caused when working on https://github.com/mdn/browser-compat-data/pull/20729
also note that safari only support `allow` syntax at present
I think https://github.com/mdn/browser-compat-data/pull/23470 does not affect this, if not, simply close it is fine
=> Add & fix Safari notes for Permissions-Policy

docs/matching-browser-releases/index.md
the https://storage.googleapis.com/chromium-find-releases-static/index.html is deprected by google and suggest using https://chromiumdash.appspot.com/commits instead
> [!Note]
> the wiki page for [Resources for finding browser versions for features](https://github.com/mdn/browser-compat-data/wiki/Resources-for-finding-browser-versions-for-features) also need update
=> Replace Chromium Find Releases tool with ChromiumDash

webextensions/api/windows.json
api.windows.create
Browser Compatibility Data - webextensions.api.windows.create - top and left is supported in Firefox >= 109. Updated for https://github.com/mdn/browser-compat-data/issues/24827
🔨 If applicable, use "Fixes #24827"
=> Update windows.json | Add compatibility data for top & left for windows.create

webextensions/manifest/storage.json
Add impl_url for https://bugzilla.mozilla.org/show_bug.cgi?id=1771731, the bug for the implementation of storage.managed_schema.
=> Add bug for implementation of manifest storage.managed_schema

RELEASE_NOTES.md, package-lock.json, package.json
- `css.properties.-webkit-text-decoration-skip` ([#24884](https://github.com/mdn/browser-compat-data/pull/24884))
- `css.properties.-webkit-user-modify` ([#24885](https://github.com/mdn/browser-compat-data/pull/24885))
- `browsers.edge.releases.133` ([#24890](https://github.com/mdn/browser-compat-data/pull/24890))
- `browsers.firefox_android.releases.135` ([#24871](https://github.com/mdn/browser-compat-data/pull/24871))
- `browsers.firefox.releases.135` ([#24871](https://github.com/mdn/browser-compat-data/pull/24871))
- `browsers.nodejs.releases.18.13.0` ([#24797](https://github.com/mdn/browser-compat-data/pull/24797))
- `browsers.nodejs.releases.19.2.0` ([#24797](https://github.com/mdn/browser-compat-data/pull/24797))
- `browsers.safari_ios.releases.18.2` …
=> Release v5.6.12

.github/workflows/release-pr.yml
Grants the `release-pr` permissions, so that the workflow has access to secrets on Dependabot merges.
=> fix(release-pr): grant permissions

api/HTMLButtonElement.json, html/elements/button.json
`commandfor` is an HTML attribute and should not be in API data. Added the right data
=> Rename HTMLButtonElement.{command => commandForElement} + duplicate to button.{command,commandfor}

html/global_attributes.json
- Added firefox version for `plaintext-only` value of `contenteditable` global attribute
- tested in Firefox Nightly 134.0a1
- [MDN Issue #36535](https://github.com/mdn/content/issues/36535)
- Content PR
- Firefox Release Notes PR
=> Firefox Nightly supports `contenteditable="plaintext-only"`

api/WebGL2RenderingContext.json, api/WebGLRenderingContext.json
Reading the doc, I was under the impression, that Firefox on Android and Fennec support video textures, but that turned to be not the case. This was reported in https://bugzilla.mozilla.org/show_bug.cgi?id=1884282 and is unresolved for quite some time. This PR adds a compatibility note with `texImage2D` and `texSubImage2D` to indicate textures from video elements not being supported.
=> Firefox Android doesn't support textures from video elements in texImage2D/texSubImage2D

api/GPUCommandEncoder.json
Chrome 125 adds support for the [`beginRenderPass()`](https://developer.mozilla.org/en-US/docs/Web/API/GPUCommandEncoder/beginRenderPass) [`depthSlice`](https://gpuweb.github.io/gpuweb/#dom-gpurenderpasscolorattachment-depthslice) option. This PR adds a data point for this option.
See https://developer.chrome.com/blog/new-in-webgpu-125#render_to_slice_of_3d_texture for evidence of addition.
See https://github.com/mdn/content/issues/36345 for project tracking issue.
=> Chromium 125 supports depthSlice option for GPUCommandEncoder.beginComputePass()

api/HTMLLinkElement.json, api/HTMLScriptElement.json, api/HTMLStyleElement.json, html/elements/link.json, html/elements/script.json, html/elements/style.json
As part of cross-document view transitions: https://webkit.org/blog/15978/release-notes-for-safari-technology-preview-204/
=> Safari TP 204 supports Render blocking

api/GPUQueue.json
In Chrome 126, the behavior of the [`GPUQueue.submit()`](https://developer.mozilla.org/en-US/docs/Web/API/GPUQueue/submit) method has been updated to be correct as per spec — the referenced command buffers must be unique.
This PR adds a data point for this update.
See https://developer.chrome.com/blog/new-in-webgpu-126#submitted_command_buffers_must_be_unique for the information source.
project issue: https://github.com/mdn/content/issues/36344
=> Chrome 126 validates GPUQueue.submit() command buffer uniqueness

api/ByteLengthQueuingStrategy.json, api/CompressionStream.json, api/CountQueuingStrategy.json, api/DecompressionStream.json, api/ReadableByteStreamController.json, api/ReadableStream.json, api/ReadableStreamBYOBReader.json, api/ReadableStreamBYOBRequest.json, api/ReadableStreamDefaultController.json, api/ReadableStreamDefaultReader.json, api/TextDecoderStream.json, api/TextEncoderStream.json, api/TransformStream.json, api/TransformStreamDefaultController.json, api/WritableStream.json, api/WritableStreamDefaultController.json, api/WritableStreamDefaultWriter.json, browsers/nodejs.json, release_notes/v4.md
most are format update - for support via the module, remove *version_removed* field and add *partial_implementation* field
mark `ReadableStream` `WritableStream` `TransformStream` as transferable, see https://github.com/nodejs/node/pull/39062 and https://nodejs.org/en/blog/release/v16.5.0/
two implement issue as note for `ReadableByteStreamController` and `ReadableStream.tee()`
https://nodejs.org/docs/latest/api/globals.html
https://nodejs.org/docs/latest/api/webstreams.html
=> Update nodejs data for Web Stream API

css/properties/box-decoration-break.json
Safari (and older versions of Blink-based browsers) are supporting `box-decoration-break` only for inline elements. While a note was already present, this is not reported as being a partial implementation in such case.
https://web.dev/blog/web-platform-10-2024?hl=en#full_box-decoration-break_support
=> Mark box-decoration-break as partial when only inline works

api/CommandEvent.json, api/HTMLButtonElement.json, api/HTMLElement.json, javascript/builtins/Uint8Array.json
Adds missing `mdn_url`s. For some reason, the checks didn't fail on [this content-inventory Dependabot PR](https://github.com/mdn/browser-compat-data/pull/24944).
=> chore(lint): run `npm run fix`

api/CredentialsContainer.json
Firefox on mobile does not support the "direct" or "enterprise" options for [`credentialCreationData.attestationConveyancePreferenceOption`](https://www.w3.org/TR/webauthn-2/#credentialcreationdata-attestationconveyancepreferenceoption).
This PR updates the data to reflect this.
Here's the issue which explains that firefox on mobile has not yet implemented a dialog which would satisfy their _self-imposed_ privacy requirement for direct attestations, and therefore do not currently support a "direct" or "enterprise" attestation option:
https://bugzilla.mozilla.org/show_bug.cgi?id=1550164
=> Firefox Android doesn't support "direct" and "enterprise" attestation values for CredentialsContainer.create()

.github/workflows/update-mdn-urls.yml
The mdn-content-inventory PR doesn't update `package.json`, only `package-lock.json`.
=> fix(update-mdn-urls): filter on package-lock.json

api/_globals/clearInterval.json, api/_globals/clearTimeout.json, api/_globals/setInterval.json, api/_globals/setTimeout.json
the added data should be 0.0.1, not 0.10.0, per documentation
https://nodejs.org/docs/latest/api/globals.html
https://nodejs.org/docs/latest/api/timers.html
(unknown how the 0.10.0 comes in https://github.com/mdn/browser-compat-data/pull/13204)
=> Fix nodejs data of timer functions

.github/workflows/release-pr.yml, .github/workflows/release.yml
Stop running the release PR workflow on forks.
The release workflow fails on forks that don't have the `GH_TOKEN` secret set. Most forks won't ever do this or need to do this, so let's turn off the workflow by default.
=> Suppress release workflow on forks

api/Animation.json, api/DOMMatrix.json, api/DOMMatrixReadOnly.json, api/Element.json, api/FileSystem.json, api/FileSystemDirectoryEntry.json, api/Location.json, api/MediaDevices.json, api/Navigator.json, css/properties/content.json, css/types/image.json, html/elements/input/reset.json, html/elements/input/submit.json, webextensions/manifest/content_security_policy.json
This PR fixes a number of notes that have markup, formatting or other issues.  These issues were found during updates for #21495.
Fixes Performed:
- Ensure code tags are inside of anchors (`<code>(<a href='[\w:;#&/=_().-]+'>)([\w\s.,…()&:;-]+)</a></code>` -> `$1<code>$2</code></a>`)
- Removed tags (`<strong>`, `<em>`) inside of inline code blocks
- Drive-by fix: tweak Edge note for FileSystem API to state the behavior applies to previous versions of Edge
- Add `<code>` blocks to example URLs that needed them
- Set a note to mirror from upstream as needed (for accuracy)
=> Fix problematic notes

api/URL.json
Add Node.js version added for URL.parse.
`npm test` passes.
This version is from https://nodejs.org/api/url.html#urlparseinput-base
None
=> Node.js 22.1.0 supports URL.parse()

html/elements/link.json
The `<link rel=manifest>` tag is marked is unsupported in Safari desktop but that can't be right. I know that some of the members found in web app manifests _are_ used by Safari when adding an app to the Dock, namely the name and icon.
Searching through the release notes, here's the earliest mention I could find of a web app manifest member being parsed in Safari on macOS: https://developer.apple.com/documentation/safari-release-notes/safari-15_4-release-notes#New-Features
So, ever since 15.4, or earlier, manifests have been parsed, which means that they've been downloaded from `<link rel=manifest>` 
elements.
This PR therefore sets the support data for Safari to `≤15.4`.
If someone can find the exact version, that'd be great.
* Earliest release note I could find: …
=> Mark link rel=manifest as supported on Safari

html/manifest/display.json
The `display` manifest member is marked as partially implemented on Safari, which is unfortunate because it makes it impossible for it to be Baseline in the [web-features](https://github.com/web-platform-dx/web-features/) project.
This manifest member _is_ supported by Safari, but just not all display types.
So, in this PR, I'm splitting it into multiple subfeatures. The top-level feature is marked as supported on Safari, and the various display types are either supported or not supported.
=> Split the `display` manifest member into sub-features

api/_globals/crypto.json
The support for the Web Crypto API is:
in v15.0.0, the API has been shipped, but can't access globally, access via the `crypto` module with the alternative name `webcrypto`
in v17.6.0, v16.15.0, the API can be available to global context, but need to be enabled with `--experimental-global-webcrypto` CLI flag
in v19.0.0, the API is available to global context without flags, but can be disabled with `--no-experimental-global-webcrypto` CLI flag
in v23.0.0, the API is marked as not experimental
see also https://nodejs.org/docs/latest/api/crypto.html#cryptowebcrypto
=> Update nodejs data for `crypto` global property

html/elements/link.json
This is a follow-up to #24971, which I'm opening to address @jensimmons' feedback:
> `<link rel=manifest>` is supported in:
> * Safari 11.1 on iOS 11.3 or later
> * Safari 17 on macOS Sonoma or later
See https://github.com/mdn/browser-compat-data/pull/24971#issuecomment-2460519228
=> Fix Safari support for link rel=manifest

webextensions/api/cookies.json
Addresses the documentation needs for [Bug 1818968](https://bugzilla.mozilla.org/show_bug.cgi?id=1818968) cookies.get() should return the cookie with the closest matching path
MDM content changes in https://github.com/mdn/content/pull/36193
=> cookies.get orders cookies according to RFC-6265

api/ServiceWorkerContainer.json
FF133 exposes [`ServiceWorkerContainer`](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerContainer) in workers in https://bugzilla.mozilla.org/show_bug.cgi?id=1131324
This mirrors support in  [WorkerNavigator.serviceWorker](https://developer.mozilla.org/en-US/docs/Web/API/WorkerNavigator/serviceWorker) that was added by @Elchi3 in https://github.com/mdn/browser-compat-data/pull/24863 (`WorkerNavigator.serviceWorker` is a `ServiceWorkerContainer`.
Tested that this is not supported on chrome and that it is on Safari.
Related docs work can be tracked in https://github.com/mdn/content/issues/36532
=> FF133 ServiceWorkerContainer supported in workers

api/CryptoKey.json, api/SubtleCrypto.json
The support for the Web Crypto API is:
in [v15.0.0](https://nodejs.org/zh-cn/blog/release/v15.0.0), the API has been shipped, but can't access globally, access via the `crypto` module with the alternative name `webcrypto` via https://github.com/nodejs/node/pull/35093
in [v17.6.0](https://nodejs.org/zh-cn/blog/release/v17.6.0), [v16.15.0](https://nodejs.org/zh-cn/blog/release/v16.5.0), the API can be available to global context, but need to be enabled with `--experimental-global-webcrypto` CLI flag via https://github.com/nodejs/node/pull/41938
in [v19.0.0](https://nodejs.org/zh-cn/blog/release/v19.0.0), the API is available to global context without flags, but can be disabled with `--no-experimental-global-webcrypto` CLI flag via https://github.com/nodejs/node/pull/42083
in …
=> Update nodejs data for `SubtleCrypto` & `CryptoKey`

html/elements/li.json
=> Add spec_url for html.elements.li.type

api/DedicatedWorkerGlobalScope.json, api/MessagePort.json, api/ServiceWorkerContainer.json, api/Window.json, api/Worker.json
the impl url has been fixed and so can be removed
=> Remove Safari impl_url for `messageerror` event

api/DataTransferItem.json, api/DevicePosture.json, api/Navigator.json, api/PublicKeyCredential.json, api/PushMessageData.json, api/Request.json, api/Response.json, api/Window.json, css/properties/writing-mode.json
The @openwebdocs [BCD collector project](https://github.com/openwebdocs/mdn-bcd-collector) v10.12.6 found new features shipping in Chrome 132 beta which was released yesterday. Currently, the collector covers about 90% of BCD, so the following list might not be exhaustive. Also, if a feature is in Chrome Canary/behind origin trials/enrollment, it is not considered here.
With this PR, BCD considers the following 12 features as shipping in Chrome 132:
- api.DevicePosture
- api.DevicePosture.change_event
- api.DevicePosture.type
- api.Navigator.devicePosture
- api.PublicKeyCredential.signalAllAcceptedCredentials_static
- api.PublicKeyCredential.signalCurrentUserDetails_static
- api.PublicKeyCredential.signalUnknownCredential_static
- api.PushMessageData.bytes
- api.Request.bytes
- …
=> Updates for Chrome 132 beta

webextensions/manifest/optional_permissions.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `optional_permissions` Web Extensions manifest property. This sets the feature(s) to a version range based upon the date that the feature was added to BCD with the intent of replacing `true` values with ranged values to eliminate `true` values from BCD.
This PR uses the source code and commit history of Chrome to add specific version numbers, rather than just ranges.  Details for each feature and the commit the version number chosen is available in the commit messages for this PR.
=> Update Chromium data for optional_permissions Web Extensions manifest property

webextensions/api/runtime.json
Follow up to [query](https://github.com/mdn/browser-compat-data/pull/23305#issuecomment-2475898048) why BCD not showing on MDN and noted that the method was spelt incorrectly.
=> Correct spelling of runtine.getcontexts

javascript/builtins/Error.json
Chrome 125 implemented the "Cause is displayed in console" feature.
The [Chromium bug](https://issues.chromium.org/issues/40182832) has been marked as fixed and has been shipped on Chrome 125 [according to the What's new in DevTools blog](https://developer.chrome.com/blog/new-in-devtools-125#error-cause).
N/A
=> Chrome 125 supports "Cause is displayed in console" feature

api/AbortController.json
data were taken from `AbortSignal.abort()` static method `reason` parameter, and in fact it is a part of this feature
chrome data confirmed by https://github.com/chromium/chromium/commit/155b2353a12c9e0173b8d33b32b115a2406a8131 and https://issues.chromium.org/issues/40202936 (https://github.com/mdn/browser-compat-data/pull/16956)
deno data confirmed by https://docs.deno.com/api/web/~/AbortController.abort and https://github.com/denoland/deno/pull/12697 (https://github.com/mdn/browser-compat-data/pull/13380)
firefox data confirmed by https://github.com/mozilla/gecko-dev/commit/712c0d58c7e48142ceaf8d1c0356b477649f6eb3 and https://bugzilla.mozilla.org/show_bug.cgi?id=1737771 (https://github.com/mdn/browser-compat-data/pull/14418)
nodejs data confirmed by …
=> Add `AbortController.abort()` parameter `reason`

api/Request.json, api/_globals/fetch.json
Discovered some FF133 updates missed by #24863 for `fetch()` `keepalive`. This updates them to 133 and adds the tag so they are grouped.
Related docs work tracked in https://github.com/mdn/content/issues/36537
=> FF133 Request keepalive and other web-features:fetch-keepalive

api/HTMLDetailsElement.json, api/HTMLElement.json
FF133 adds support for the HTMLElement beforetoggle and toggle events that were formerly  assumed to be restricted to only being fired at popovers in https://bugzilla.mozilla.org/show_bug.cgi?id=1876762
Note, this data is confirmed by spec author/implementer in https://github.com/mdn/content/issues/36536#issuecomment-2454321830
I have added subfeatures to these events for the elements that they can be fired on. My theory being that for HTMLDialogElement I can add the particular subfeature of HTMLElement as another compat point to show the version at which the event became relevant.
I THINK this is better than trying to somehow show the events directly supported on (say) HTMLDialogElement 
It turns out though that `toggle` has been around forever on HTMLDetailsElement. However this has the …
=> HTMLElement toggle and before toggle event subfeatures

api/HTMLElement.json
Fixes a linting issue introduced in https://github.com/mdn/browser-compat-data/commit/e5698eb2d9eaaecb1c5b1cdd2b9ec655ac122bee, because the PR commit had a broken linter.
=> chore: run `npm run fix`

RELEASE_NOTES.md, package-lock.json, package.json
Reverts mdn/browser-compat-data#25053.  This release was not successful.
=> Revert "Release v5.6.16"

api/HTMLElement.json
Improves #24927
The beforetoggle fires on popovers and dialogs, while toggle first on  details elements as well. This adds the tag info
FYI @caugner
=> Add web-features tags for beforetoggle/toggle events

api/TrustedTypePolicyFactory.json
FF133 adds support for `TrustedTypePolicyFactory.getAttributeType` and `.getPropertyType` behind a pref in https://bugzilla.mozilla.org/show_bug.cgi?id=1917783 and https://bugzilla.mozilla.org/show_bug.cgi?id=1917784
Related docs work can be tracked in https://github.com/mdn/content/issues/36559
=> Firefox 133 supports TrustedTypePolicyFactory.get{Attribute,Property}Type() behind pref

mathml/elements/ms.json
Silences this warning on `main`:
`✖ mathml.elements.ms.lquote_rquote_attributes - Warning → feature was implemented and has since been removed from all browsers dating back two or more years ago.`
=> Remove an obsolete MathML feature

api/Element.json, api/Location.json, api/MediaDevices.json, api/Navigator.json, css/properties/animation-duration.json, css/properties/counter-reset.json, css/types/color.json, css/types/length.json, webextensions/manifest/chrome_url_overrides.json
This PR converts the `<em>` blocks to underscores to use Markdown formatting.
=> Convert <em> in notes to Markdown

lint/linter/test-style.ts
Now that we are using Markdown formatting, we do not need to enforce this particular styling rule.  This PR removes it accordingly.
=> Remove linter rule for link styling

RELEASE_NOTES.md, package-lock.json, package.json
Reverts mdn/browser-compat-data#25117.  Actually, upon further inspection, it appears that the release had not, in fact, failed...whoops.  There was just some leftover debugging that needed to be cleaned up.
=> Re-Release v5.6.16

api/GPU.json, api/GPUAdapter.json, api/GPUComputePassEncoder.json, api/GPUDevice.json, api/GPUPipelineError.json, api/GPUQueue.json, api/GPURenderBundleEncoder.json, api/GPURenderPassEncoder.json
Some webgpu features were missing the tag. (we usually do this in web-features but it is easier to do it here for webgpu)
=> Tag remaining WebGPU keys

svg/elements/stop.json
Part of the https://github.com/mdn/browser-compat-data/issues/24162
Relates to https://github.com/mdn/browser-compat-data/pull/25130
Relates to https://github.com/mdn/data/pull/782
=> Add missing spec_url for svg `<stop>` element

svg/global_attributes.json
`stop-color` is not a global attribute, it can only use on SVG `<stop>` elements
current data in https://github.com/mdn/browser-compat-data/blob/main/svg/elements/stop.json#L91-L133 has already covered this feature and is more detailed
https://svgwg.org/svg2-draft/pservers.html#StopColorProperty
https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stop-color
Relates to https://github.com/mdn/browser-compat-data/pull/25131
Relates to https://github.com/mdn/data/pull/782
=> Remove svg.global_attributes.stop-color

.github/workflows/labeler.yml
The `label-by-size` job is failing silently, because it doesn't have the `issues: write` permission, which it needs, because `pr-size-labeler` currently uses the issues API (`PATCH issues/{id}`) rather than the issue label API (`POST issues/{id}/labels`).
Same PR in mdn/content:
- https://github.com/mdn/content/pull/31759
Upstream PR removing the dependency on that permission:
- https://github.com/CodelyTV/pr-size-labeler/pull/89
=> fix(workflows/labeler): grant "issues: write" permission

.github/workflows/labeler.yml
Excludes the release PR from size labels, because it doesn't really make sense.
=> chore(workflows/labeler): exclude release PR from size labels

api/MLContext.json
This is deprecated and we don't yet have a way to handle deprecated keys in web-features.
N/A
Triggered by https://github.com/web-platform-dx/web-features/pull/2284#discussion_r1850289458
=> Remove `webnn` tag from `MLContext.compute`

api/ReadableStream.json
Add Safari bug url for ReadableStream @@asynciterator
https://webkit.org/b/194379
N/A
=> Add Safari bug URL for ReadableStream @@asynciterator

svg/elements/linearGradient.json, svg/elements/radialGradient.json
=> Add missing spec_url for svg `<linearGradient>` & `<radialGradient>` elements

api/Document.json
Mark `api.Document.createEvent` as deprecated.
The spec has [a note](https://dom.spec.whatwg.org/#ref-for-concept-event%E2%91%A4%E2%91%A3) that cautions developers against using the API:
> Event constructors ought to be used instead.
[MDN](https://developer.mozilla.org/en-US/docs/Web/API/Document/createEvent) also has a warning advising against using the API.
https://github.com/web-platform-dx/web-features/pull/2277
=> Mark `api.Document.createEvent` as deprecated

api/GPUDevice.json, api/GPUTexture.json
Chrome 119 (Android 121) supports the `rgb10a2uint` texture format: see https://developer.chrome.com/blog/new-in-webgpu-119#rgb10a2uint_texture_format.
I have added a sub-data point in all places where `GPUTextureFormat` is used.
Spec PR: https://github.com/gpuweb/gpuweb/pull/4245
Project issue: https://github.com/mdn/content/issues/36372
=> Add data points for rgb10a2uint format support

mathml/elements/mi.json, mathml/global_attributes.json
Given that the rest of MathML support in Opera mirrors Chrome 109 implementation, it would be fair to do this for all features.
I tested a few attributes, and they work just fine. I don’t see why the support might be different.
=> Update MathML support for Opera

mathml/elements/maction.json, mathml/elements/menclose.json
Without description, BCD tables on MDN render attribute values as `attribute.value`, which is unexpected in the markup language context.
Once merged and released, this should change to what, for example, does `<iframe>`:
I expect it might be as well fixed on the MDN side, so here’s a decision to make.
=> Add descriptions to MathML attribute values

api/MessageEvent.json, api/MessagePort.json, api/Window.json, api/Worker.json
see https://github.com/mdn/browser-compat-data/issues/24726
see https://github.com/mdn/browser-compat-data/issues/24726
fixes https://github.com/mdn/browser-compat-data/issues/24726
=> Add data for non-standard UserActivation feature

api/GPUDevice.json
Chrome 121 supports the `display-p3` color space for [`GPUDevice.importExternalTexture()`](https://developer.mozilla.org/en-US/docs/Web/API/GPUDevice/importExternalTexture) - see https://developer.chrome.com/blog/new-in-webgpu-121#support_display-p3_as_gpuexternaltexture_color_space
This PR adds a data point for it.
Project issue: https://github.com/mdn/content/issues/36353.
=> Chrome 121 supports display-p3 color space for GPUDevice.importExternalTexture()

css/selectors/highlight.json
Adds note for #25132
Tested using MDN playground link in #25132
=> Safari ignores ::highlight selector when combined with `user-select: none`

api/GPUDevice.json
Chrome 119 (Android 121) supports the `unorm10-10-10-2` vertex format: see https://developer.chrome.com/blog/new-in-webgpu-119#unorm10-10-10-2_vertex_format.
I have added a sub-data point in all places where `GPUVertexFormat` is used.
Spec PR: https://github.com/gpuweb/gpuweb/pull/4288
Project issue: https://github.com/mdn/content/issues/36373
=> Chrome 119 (Android 121) supports the unorm10-10-10-2 vertex format

api/SVGGraphicsElement.json, css/properties/font-variant-position.json
Some small typos I found while working on related docs.
=> fix(typos): 'retured' -> 'returned' and CSS 'propery'

http/headers/Server-Timing.json, http/headers/Trailer.json
The support for HTTP Trailer header is misleading, as it's removed from the Fetch spec & not accessible there anyway / XHR. As far as I can see, the only support that exists in browsers is exclusively for `Server-Timing`, and at that, it's only used for DevTools in Network -> Timing, all other headers (as trailers) are a no-op / discarded. For this reason, I've set it to partial support for `Trailer`, and full support for Server-Timing header as trailer, which no other browser appears to do.
- **Firefox** `Server-Timing` implementation bug -> https://bugzilla.mozilla.org/show_bug.cgi?id=1403051:
- Networking aspect landed in Fx59 -> https://bugzilla.mozilla.org/show_bug.cgi?id=1413999
- Exposed in DevTools in Fx71 -> https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/71#deve …
=> Firefox recognizes Server-Timing header, but only partially supports Trailer headers (DevTools only)

api/HTMLAnchorElement.json, api/HTMLImageElement.json, api/HTMLScriptElement.json, api/Request.json, api/Window.json, api/XMLHttpRequest.json, api/_globals/fetch.json, html/elements/a.json, html/elements/img.json, html/elements/script.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `attributionSrc` member of various APIs. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.10.7).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/HTMLAnchorElement/attributionSrc
=> Chromium 125 adds Attribution Reporting API support

api/WGSLLanguageFeatures.json
Chrome 123 supports the `readonly_and_readwrite_storage_textures` language extension (see [`WGSLLanguageFeatures`](https://developer.mozilla.org/en-US/docs/Web/API/WGSLLanguageFeatures)), which allows:
- 32-bit integer scalars packing 4-component vectors of 8-bit integers to be used as inputs to dot product instructions
- and packing and unpacking instructions with packed 4-component vectors of 8-bit integers to be used
In your WGSL shader code.
This PR adds a data point for the language extension.
See https://developer.chrome.com/blog/new-in-webgpu-123#dp4a_built-in_functions_support_in_wgsl for the data source.
Project issue: https://github.com/mdn/content/issues/36349
=> Chrome 123 supports packed_4x8_integer_dot_product extension in WGSL

api/WGSLLanguageFeatures.json
Chrome 123 supports the `unrestricted_pointer_parameters` language extension (see [`WGSLLanguageFeatures`](https://developer.mozilla.org/en-US/docs/Web/API/WGSLLanguageFeatures)), which loosens restrictions on pointers being passed to WGSL functions as follows:
- Parameter pointers to storage, uniform, and workgroup address spaces being passed to user-declared functions.
- Pointers to structure members and array elements being passed to user-declared functions.
This PR adds a data point for the language extension.
See https://developer.chrome.com/blog/new-in-webgpu-123#unrestricted_pointer_parameters_in_wgsl for the data source.
Spec PR: https://github.com/gpuweb/gpuweb/pull/4312
Project issue: https://github.com/mdn/content/issues/36350
=> Chrome 123 supports unrestricted_pointer_parameters extension in WGSL

api/DocumentPictureInPicture.json
…indow()
This PR adds data points for two new options available to the [`DocumentPictureInPicture.requestWindow()`](https://developer.mozilla.org/en-US/docs/Web/API/DocumentPictureInPicture/requestWindow) method:
- Chrome 124 adds the `disallowReturnToOpener` option. When set to `true`, it hides the "back to tab" button that by default appears in the top bar of the PIP window. See https://chromestatus.com/feature/6223347936657408.
- Chrome 130 adds the `preferInitialWindowPlacement` option. When set to `true`, it causes the PIP window to always appear back at its default initial position and size when closed and then reopened. By default, it will reopen at its previous position and size. See https://chromestatus.com/feature/5183881532932096.
I've tested that both features work in the …
=> Chrome 124/130 support new DocumentPictureInPicture.requestWindow() options

css/types/color.json
Adds full support for relative_syntax in:
- HSL & HWB- Chrome 125
- HSL, HWB, LCH, OKLch, RGB, color()- Safari 18.
Codepen- https://codepen.io/jamessw/pen/WNVXMLR
Fixes #24528, Fixes #22961
=> Update Color relative syntax support

css/properties/font-synthesis-position.json
the property only supported by firefox In M118, which didn't ship for more than two years
=> Mark `font-synthesis-position` as experimental

css/types/image.json
no implement by any browser, the only bug seems to be not active for a very long time
=> Remove unimplement css.types.image.image

javascript/builtins/Intl/DurationFormat.json
FF134 adds support for [`Intl.DurationFormat`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DurationFormat) in Nightly in https://bugzilla.mozilla.org/show_bug.cgi?id=1648139#c19. (note, it is not obvious it is nightly, but that link confirms it with developer.
This updates the FF versions to "preview"
Related docs work can be tracked in https://github.com/mdn/content/issues/36917
=> Firefox Nightly supports Intl.DurationFormat

api/Document.json
FF133 rolls back the shadow mode behaviour on Document.caretPositionFromPoint that was added as a parameter option in FF133 in #24405 (and originally documented in https://github.com/mdn/content/issues/35702).
The option is now behind a pref that is set to be enabled in nightly/preview, as per https://bugzilla.mozilla.org/show_bug.cgi?id=1914596#c8
=> Firefox 133 unshipped `Document.caretPositionFromPoint` shadow root behaviour

api/NavigateEvent.json
See https://github.com/WICG/navigation-api/pull/235
canTransition is now canIntercept (done in https://github.com/mdn/browser-compat-data/pull/24792)
transitionWhile is now intercept
See https://github.com/WICG/navigation-api/pull/239
restoreScroll is now scroll
=> Merge renamed NavigateEvent features `{transitionWhile => intercept}` + `{restoreScroll => scroll}`

api/PushManager.json, api/ReadableStreamBYOBReader.json, css/properties/align-self.json, css/properties/justify-self.json, css/properties/place-self.json, javascript/builtins/Promise.json, javascript/builtins/RegExp.json, lint/linter/test-spec-urls.ts, webassembly/memory64.json
The @openwebdocs [BCD collector project](https://github.com/openwebdocs/mdn-bcd-collector) v10.12.6 found new features shipping in Firefox 134 beta which was released today. Currently, the collector covers about 90% of BCD, so the following list might not be exhaustive. Also, if a feature is in Firefox Nightly only, it is not considered here.
With this PR, BCD considers the following 9 features as shipping in Firefox 134:
- api.PushManager.supportedContentEncodings_static
- api.ReadableStreamBYOBReader.read.options_min_parameter (manually added)
- css.properties.align-self.position_absolute_context (manually added)
- css.properties.justify-self.position_absolute_context (manually added)
- css.properties.place-self.position_absolute_context (manually added)
- …
=> Updates for Firefox 134 beta

api/SerialPort.json
…onected events
Chrome 130 supports the [`SerialPort.connected`](https://wicg.github.io/serial/#dom-serialport-connected) attribute, a boolean that reports whether a serial port is logically connected. This property is already represented in BCD.
However, another part of this work item is that the `SerialPort` `connect` and `disconnect` events were previously only fired by physical/wired serial ports. With this change, wireless Bluetooth RFCOMM serial ports also fire these events when they connect and disconnect.
This PR adds a data point to cover this new wireless support for the events. Note that it looks like this change is a result of a spec change (I'm not sure which exact spec change, but https://github.com/WICG/serial/pull/189 mentions adding Bluetooth support) rather than Chrome …
=> Chrome 130 supports connection events with Bluetooth RFCOMM serial ports

api/BrowserCaptureMediaStreamTrack.json, api/RestrictionTarget.json
Chrome 132 supports the [Element Capture API](https://screen-share.github.io/element-capture/); see https://chromestatus.com/feature/5198989277790208, and also see https://developer.chrome.com/blog/chrome-132-beta#element_capture.
Element Capture is an extension to the [Screen Capture API](https://developer.mozilla.org/en-US/docs/Web/API/Screen_Capture_API) that allows developers to restrict the captured stream to a particular DOM element.
Specifically, this PR adds:
- `api.BrowserCaptureMediaStreamTrack.restrictTo`
- `api.RestrictionTarget`
- `api.RestrictionTarget.fromElement_static`
I decided to add these manually because the Chrome 132 beta collector run didn't pick them up. I hope that's OK.
See also https://github.com/mdn/content/pull/36939 for the associated content addition.
=> Chrome 132 supports Element Capture API

html/elements/img.json, html/elements/source.json
Unblocks https://github.com/web-platform-dx/web-features/pull/2349
Version numbers are taken from:
- api.HTMLImageElement.srcset
- api.HTMLSourceElement.sizes
- api.HTMLSourceElement.srcset
=> Update Edge versions for srcset and sizes in <img> and <source>

api/Serial.json, api/SerialPort.json
Chrome has supported the [Web Serial API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Serial_API) for several versions now (since Chrome 89), but the MDN docs and BCD have not been updated to include support for Bluetooth RFCOMM services (originally only wired ports such as actual serial ports and USB devices were supported). 
This was added in Chrome 117 — see https://chromestatus.com/feature/5686596809523200.
This PR adds data points for Bluetooth RFCOMM support. Specially:
- `bluetoothServiceClassId` properties inside the `Serial.requestPort()` `filters` option.
- The `Serial.requestPort()` `allowedBluetoothServiceClassIds` option.
- The `bluetoothServiceClassId` property inside the object returned by the `SerialPort.getInfo()` method.
=> Chrome 117 supports Bluetooth service class IDs in Web Serial API
