css/selectors/xr-overlay.json
Data comes from the OWD collector v10.12.6.
Spec: https://immersive-web.github.io/dom-overlays/#selectordef-xr-overlay
Part of WebXR DOM overlays https://chromestatus.com/feature/6048666307526656
https://web-platform-dx.github.io/web-features-explorer/features/webxr-dom-overlays/
=> Chrome 83 added `:xr-overlay` CSS selector

.github/ISSUE_TEMPLATE/enhancement.yml, .github/issue-regex-labeler.yml, .github/labeler.yml, .github/workflows/close-incomplete-issues.yml, docs/issue-triage-checklist.md, docs/labels.md, scripts/release/semver-pulls.ts
Removes emojis from labels, as discussed in the BCD call on 2024-11-19.
Removed:
- ` :[a-z0-9_]+:`
- `%20%3A[a-z0-9_]+%3A`
- ` [\u{1F600}-\u{1F64F}\u{1F300}-\u{1F5FF}\u{1F680}-\u{1F6FF}\u{1F700}-\u{1F77F}\u{1F780}-\u{1F7FF}\u{1F800}-\u{1F8FF}\u{1F900}-\u{1F9FF}\u{1FA00}-\u{1FA6F}\u{1FA70}-\u{1FAFF}\u{1FB00}-\u{1FBFF}]` (selectively)
⚠️ The merge of this PR needs to be coordinated with updating the labels.
=> chore(labels): remove emojis

lint/fix.ts
This PR updates the order that the fix scripts are run in, so that the ordering fixes are run after all other fixes are performed.
=> Run ordering fixes after all other fixes

api/SerialPort.json
This PR updates and corrects version values for Microsoft Edge for the `connected` member of the `SerialPort` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.7).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/SerialPort/connected
=> Update Edge data for api.SerialPort.connected

api/CSSMarginRule.json
This PR updates and corrects version values for Microsoft Edge for the `CSSMarginRule` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.7).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/CSSMarginRule
=> Update Edge data for CSSMarginRule API

.github/ISSUE_TEMPLATE/data-problem.yml, .github/ISSUE_TEMPLATE/enhancement.yml, .github/ISSUE_TEMPLATE/infra-problem.yml
Add needs-triage label to new issues.
Discussed in BCD meeting on 2024-11-26.
Reverts https://github.com/mdn/browser-compat-data/pull/21503.
=> chore(issue-templates): add "needs-triage" label

webextensions/api/scripting.json
Add details of support for the `world` property in `scripting.RegisteredContentScript`. This was added in. [Bug 1736575](https://bugzilla.mozilla.org/show_bug.cgi?id=1736575) Support execution world MAIN in `scripting.executeScript()` and content_scripts (see https://hg.mozilla.org/integration/autoland/rev/d9dcbf38d3f8)
Fixes #24055
=> Bug-1736575 scripting.RegisteredContentScript supports world property

css/properties/counter-reset.json
This PR updates and corrects version values for Chrome and Safari for the `list-item` member of the `counter-reset` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.7).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/counter-reset/list-item
Additional Notes: Safari 9 was guesstimated from lack of support in Safari 8 and support in Safari 9.1.
=> Chrome 28 and Safari 9 support `list-item` in`counter-reset`

api/HTMLInputElement.json, html/elements/input.json
Add data for the alpha and colorspace attributes (and alpha and colorSpace properties).
https://webkit.org/blog/16205/release-notes-for-safari-technology-preview-207/#:~:text=color%3E%20to%20support-,alpha,-and%20colorspace%20attributes - Safari Tech Preview 207 added support for this.
https://github.com/whatwg/html/pull/10456 - added these to the spec.
https://github.com/mdn/content/issues/35953
=> Safari TP supports alpha and colorspace attributes on input

css/at-rules/page.json
The `page-orientation` descriptor was enabled in FF122 in https://bugzilla.mozilla.org/show_bug.cgi?id=1869880 - as you can see from `layout.css.page-orientation.enabled` value in https://searchfox.org/mozilla-central/source/modules/libpref/init/StaticPrefList.yaml#9475
This fell out of checks in https://github.com/mdn/content/issues/36742
=> Firefox 122 supports `page-orientation` descriptor for the `@page` at-rule

css/properties/clip-rule.json
This PR updates and corrects version values for all browsers for the `clip-rule` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.7).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/clip-rule
=> Update Chrome/Firefox/Safari data for clip-rule CSS property

api/WebGL2RenderingContext.json
part of https://github.com/openwebdocs/project/issues/214
the other properties and methods that are identical in `WebGLRenderingContext` and `WebGL2RenderingContext `  link to the `WebGLRenderingContext`  pages
=> link to WebGL2RenderingContext `linewidth()`

css/properties/counter-increment.json
This PR updates and corrects version values for Chrome and Safari for the `counter-increment` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.7).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/counter-increment
Additional Notes: Safari 9 was guesstimated from lack of support in Safari 8 and support in Safari 9.1.
=> Chrome 28 / Safari 9 support `counter-increment` CSS property

svg/elements/stop.json, svg/global_attributes.json
`stop-color,stop-opacity` are also presentation attributes and so they'd better present in global attributes (as they apply to all elements)
also including a move of `paint-order` global attribute
=> Move SVG attributes `stop-color` and `stop-opacity` to global attributes

css/properties/position-area.json
This PR reverts #24454.  The collector reports no support for the `position-area` property in Firefox, and from manual testing, the browser does not recognize the property at all.  It appears that it was only exposed early in Firefox Nightly, but not available in stable at all.
=> Firefox 131 does NOT support position-area

webassembly/typedFunctionReferences.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `typedFunctionReferences` WebAssembly feature. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.7).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/webassembly/typedFunctionReferences
=> Safari 18 supports typedFunctionReferences WebAssembly feature

css/properties/text-wrap.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `stable` member of the `text-wrap` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.7).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/text-wrap/stable
=> Chromium 130 supports `text-wrap: stable`

api/Fence.json, api/FencedFrameConfig.json, api/HTMLFencedFrameElement.json, api/Navigator.json, api/Window.json, html/elements/a.json, html/elements/fencedframe.json, http/headers/Content-Security-Policy.json, http/headers/Sec-Fetch-Dest.json
Looks like it is mentioned with the original implementation issue: https://issues.chromium.org/issues/40053214, so setting to 117. (collector says it would be 126 but I didn't find any evidence for that.)
=> Chrome 115 added HTMLFencedFrameElement.sandbox

css/properties/text-wrap-mode.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `text-wrap-mode` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.7).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/text-wrap-mode
=> Chromium 130 supports `text-wrap-mode` CSS property

css/properties/background-position.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `background-position` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.7).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/background-position
=> Chrome 1 supported `background-position: bottom/center/left/right/top`

css/selectors/attribute.json
**WebKit** now also has an open bug to implement this (and a W.I.P patch at <https://github.com/WebKit/WebKit/pull/27188>).
- <https://webkit.org/b/272573>
- <https://github.com/WebKit/WebKit/pull/27188>
- <https://github.com/mdn/browser-compat-data/pull/5472>
=> [css.selectors.attribute] Add WebKit bug for case‑sensitive modifier

css/properties/font-variant.json
This PR updates and corrects version values for all browsers for the `none` member of the `font-variant` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.7).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/font-variant/none
=> Chrome 52 / Firefox 34 / Safari 9 support `font-variant: none`

css/types/color.json
Safari now fully supports mixed types in color functions.
https://codepen.io/romainmenke/pen/wvNYKmR
https://webkit.org/blog/15865/webkit-features-in-safari-18-0/#css
> - Fixed hsl() and hsla() implementation to match the latest spec changes.
> - Fixed the implementation of rgb() and rgba() to match the latest spec.
> - Fixed the hwb() implementation to match the latest spec.
> - Fixed the remaining color types to be synced with the latest spec changes.
N/A
=> Safari 18 supports mixed type parameters in CSS color types

css/properties/object-position.json
This reverts commit 11f4a775b2bc6dc72504699b4636bb534aedf210.
#23631 was merged to address https://github.com/mdn/browser-compat-data/issues/23586, but it has been identified as needing a different approach- see [this comment](https://github.com/mdn/browser-compat-data/issues/23586#issuecomment-2425049201).
This reverts the PR, to remove the `css.properties.object-position.applies_to_iframe_elements` key, in preparation for a more thorough documenting of which replaced elements `object-position` (and `object-fit`) apply to.
=> Revert "Firefox 36+ applies object-position to iframes (#23631)"

css/properties/backface-visibility.json, css/properties/perspective-origin.json, css/properties/perspective.json, css/properties/transform-origin.json, css/properties/transform-style.json, css/properties/transform.json, css/properties/transition-delay.json, css/properties/transition-duration.json, css/properties/transition-property.json, css/properties/transition-timing-function.json
This reverts the `layout.css.prefixes.transforms` prefixed changes made in #21195 to reenable the `-moz` prefixed transforms:
- `-moz-backface-visibility`
- `-moz-perspective-origin`
- `-moz-perspective`
- `-moz-transform-origin`
- `-moz-transform-style`
- `-moz-transform`
This was done in https://bugzilla.mozilla.org/show_bug.cgi?id=1886134 - I've removed the original nightly changes invisible and replaced it with the preference, since that is what makes most sense.
FF126 also sets the following as false by default (removes the following) as part of adding CSS zoom in https://bugzilla.mozilla.org/show_bug.cgi?id=390936
- `-moz-transition-delay`
- `-moz-transition-duration`
- `-moz-transition-property`
- `-moz-transition-timing-function`
- `-moz-transition`
For those it changes preview to …
=> Firefox 126 removed / Nightly unremoved some moz-prefixed CSS properties

css/types/color.json
The `color-contrast()` CSS function is no longer part of [CSS Color Module Level 6](https://drafts.csswg.org/css-color-6/#colorcontrast). It was [renamed](https://github.com/w3c/csswg-drafts/issues/7557) to `contrast-color()`, and the spec has changed since Safari and Chrome did their experimental implementations. 
There's a few layers to this decision (renaming an experimental feature and changing the functionality), but my thought is that the cleanest would be to view `color-contrast()` and `contrast-color()` as separate types, meaning:
- Set `color-contrast` to `standard_track: false`
- Remove the `color-contrast` spec link (it links to the spec for `constrast-color`)
- Create `contrast-color` once there is implementation.
I'm open to other ideas as well.
=> Remove `css.types.color.color-contrast`

api/SVGPathElement.json
FF97 unshipped [`SVGPathElement.getPathSegAtLength()`](https://developer.mozilla.org/en-US/docs/Web/API/SVGPathElement#svgpathelement.getpathsegatlength) behind a preference. The preference was actually removed in FF129 in https://bugzilla.mozilla.org/show_bug.cgi?id=1745149 but since the feature was off since FF97, that was effectively when it was unshipped.
This removes the preference information in the feature.
This fell out of experimental features work in https://github.com/mdn/content/issues/36742
=> FF97 removes SVGPathElement.getPathSegAtLength()

api/Permissions.json
FF132 enabled the pref for camera and microphone permissions API in https://bugzilla.mozilla.org/show_bug.cgi?id=1916993. This just updates the feature.
Fell out of work done in https://github.com/mdn/content/issues/36742
=> FF132 permissions API - camera, microphone

css/properties/display.json
Firefox 1 most likely already supported `display: table-caption` (like `display: table-cell`).
Based on these searches, it is fair to assume `table-caption` has been supported as long as `table-cell` has been supported:
- https://searchfox.org/mozilla-esr17/search?q=NS_STYLE_DISPLAY_TABLE_CAPTION
- https://searchfox.org/mozilla-esr17/search?q=NS_STYLE_DISPLAY_TABLE_CELL
Relates to https://github.com/mdn/browser-compat-data/issues/25355.
=> Firefox 1 supported `display: table-caption`

css/properties/stroke-dasharray.json, css/properties/stroke-dashoffset.json, css/properties/stroke-linecap.json, css/properties/stroke-linejoin.json, css/properties/stroke-miterlimit.json, css/properties/stroke-opacity.json, css/properties/stroke-width.json, svg/global_attributes.json
Firefox 1 appears to have already supported these `stroke-*` properties:
- `stroke-dasharray`
- `stroke-dashoffset`
- `stroke-linecap`
- `stroke-linejoin`
- `stroke-miterlimit`
- `stroke-opacity`
- `stroke-width`
See:
https://searchfox.org/mozilla-central/rev/b3baf9e836ff2300c3b967a44d03b1a871c77a67/content/svg/content/src/nsSVGElement.cpp#415
Relates to https://github.com/mdn/browser-compat-data/issues/25355.
=> Firefox 1 supported `stroke-*` properties

css/properties/background-size.json
As `auto` is the initial/default value, it was very likely supported as long as `background-size` was supported.
For Firefox, implementation happened before version 3, see:
- https://bugzilla.mozilla.org/show_bug.cgi?id=189519
See also:
- [MDN page for background-size from 2013](https://web.archive.org/web/20130819235455/https://developer.mozilla.org/en-US/docs/Web/CSS/background-size)
- [CSS spec regarding background-size from 2013](https://web.archive.org/web/20130902111154/http://dev.w3.org/csswg/css-backgrounds/#background-size)
Relates to https://github.com/mdn/browser-compat-data/issues/25355.
=> Firefox 3.6 supported `background-size: auto`

html/elements/meta.json
Updates `html.elements.meta.theme-color` to show partial support for 39-91, and full support in 92.
See https://github.com/mdn/browser-compat-data/issues/25312
Closes #25312
=> Chrome Android 92+ fully supports theme-color

webextensions/api/action.json
per https://developer.chrome.com/docs/extensions/reference/api/action#method-setBadgeTextColor、https://developer.chrome.com/docs/extensions/reference/api/action#method-getBadgeTextColor、https://developer.chrome.com/docs/extensions/reference/api/action#method-isEnabled
fixes mdn/browser-compat-data#25348
also note that chrome.action have new members not included in BCD yet: `UserSettingsChanged`、`onUserSettingsChanged` added in Chrome 130; should they also be included in BCD?
=> Chrome 108/109 added `webextensions.api.action.isEnabled/{get,set}BadgeTextColor`

browsers/opera.json, browsers/opera_android.json, css/properties/box-decoration-break.json, css/properties/speak.json, html/elements/fieldset.json, http/headers/Cross-Origin-Opener-Policy.json
- Fixed compatibility details for the CSS property `box-decoration-break`
- Improved data for the CSS property `speak` with updated browser support.
- Updated the HTML `disabled` attribute compatibility for `fieldset` element.
- Refreshed version data for Opera and Opera Android.
The proposed changes do not require testing because they involve aligning compatibility data for specific browsers based on the Chromium engine version they use. These updates are sourced from vendor release notes and publicly available documentation, ensuring accuracy without requiring direct feature testing.
- https://blogs.opera.com/desktop/2024/09/opera-114/
- https://blogs.opera.com/desktop/2024/11/opera-115/
- https://blogs.opera.com/mobile/2024/10/opera-for-android-adds-image-understanding/
- …
=> Opera supports CSS `box-decoration-break`, `speak`, HTML `fieldset.disabled` and HTTP header `Cross-Origin-Opener-Policy`

css/properties/color-interpolation-filters.json
This PR updates and corrects version values for all browsers for the `color-interpolation-filters` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.7).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/color-interpolation-filters
Additional Notes: Safari 9 was guesstimated from lack of support in Safari 8 and support in Safari 9.1.
=> Chrome 1 / Firefox 3 / Safari 3 added CSS `color-interpolation-filters` support

css/properties/border-image-width.json
This PR updates and corrects version values for Firefox and Firefox Android for the `auto` member of the `border-image-width` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.7).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/border-image-width/auto
=> Firefox 15 added `border-image-width: auto` support

css/properties/text-decoration-line.json
This PR updates and corrects version values for all browsers for the `text-decoration-line` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.7).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/text-decoration-line
=> Chrome 57 / Firefox 6 / Safari 8 added support for `text-decoration-line` CSS property values

css/properties/border-image-width.json
This PR updates and corrects version values for Chrome and Safari for the `border-image-width` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.7).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/border-image-width
=> Chrome 16 / Safari 6 supported `border-image-width` CSS property

css/properties/cursor.json
This PR updates and corrects version values for all browsers for the `grabbing` member of the `cursor` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.7).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/cursor/grabbing
=> Chrome 68 / Firefox 27 / Safari 11 supported `cursor: grabbing`

css/properties/line-break.json
This PR updates and corrects version values for all browsers for the `anywhere` member of the `line-break` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.7).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/line-break/anywhere
=> Chrome 83 / Firefox 69 / Safari 13 added `line-break: anywhere` support

scripts/release/index.ts
Avoiding force-push did _not_ resolve the "checks on release PR not running" issue ([this](https://github.com/mdn/browser-compat-data/pull/25176) resolved it).
So let's revert that change to keep the commit history clean on the release PR.
Reverts mdn/browser-compat-data#25140
=> Revert "fix(scripts/release): avoid force-push"

http/headers/X-XSS-Protection.json
The feature [has been marked deprecated](https://github.com/mdn/content/pull/36862/files#diff-35a3c4188ae51e9b163064c8122d7916123841263089a1f06d74b0a554b731cfR11) in the `mdn/content`. The PR tries to reflect the same in BCD.
- https://github.com/mdn/content/pull/36862
=> http.headers.X-XSS-Protection : mark deprecated

api/Navigator.json
Unblocks https://github.com/web-platform-dx/web-features/pull/2360#discussion_r1863518542
It seems unfair to mark Chromium as partial implementation when WebKit isn't marked as partial either and when support is implemented as much as operating systems allow it.
cc @captainbrosset
=> Chromium supports setAppBadge as much as it is possible

html/elements/input/week.json
Add support for week type for calendar inputs in iOS. Ref: https://webkit.org/blog/16301/webkit-features-in-safari-18-2/#:~:text=Safari%2018.2%20adds%20support%20for%20input%20type=week%20on%20iOS%2C%20iPadOS%2C%20and%20visionOS.
=> Safari iOS 18.2 supports `input type="week"`

css/properties/text-wrap-style.json
there is no reason that the value only supported on chromium-desktop
it matches the behavior of the same value on the `text-wrap` property, which implemented in M117
it also matches other values of the `text-wrap-style` property in the same version. which all implemented in the same version
https://github.com/mdn/browser-compat-data/blob/7382003e9b32e24026ed6aa5afcc0f205e0f324d/css/properties/text-wrap.json#L117-L154
test in local mobile device and confirms its support
https://github.com/mdn/browser-compat-data/pull/24663 - the PR that add the data
https://chromestatus.com/feature/5793719555719168 - related chromium entry
https://issues.chromium.org/issues/338529223 -  related chromium bug
https://github.com/chromium/chromium/commit/ee5d3f203d98899e31221786c36baf443ea11acc - related …
=> Chrome Android 130 also supports `text-wrap-style: pretty`

webextensions/api/action.json
[Chrome documentation](https://developer.chrome.com/docs/extensions/reference/api/action#method-openPopup) indicates that `webextensions.api.action.openPopup` is generally available in Chrome 127.
Fixes #25345
=> Chrome 127 makes `webextensions.api.action.openPopup` generally available

api/SVGAnimationElement.json
Fixes https://github.com/mdn/browser-compat-data/issues/25384
=> Add spec_url for `SVGAnimationElement`

css/types/ratio.json
FF78 enabled and removed the pref  `layout.css.aspect-ratio-number.enabled` in https://bugzilla.mozilla.org/show_bug.cgi?id=1635939 (and noted in https://bugzilla.mozilla.org/show_bug.cgi?id=1621090#c2). 
This updates the associated feature accordingly.
Fell out of work done in https://github.com/mdn/content/issues/36742
=> Firefox 78 allows number values in CSS aspect ratio

css/types/calc-keyword.json
This has been renamed in the spec and on MDN. 
- https://developer.mozilla.org/en-US/docs/Web/CSS/calc-keyword
Fixes #24036
=> Rename css.types.calc-constant to css.types.calc-keyword

api/Element.json
Add link to https://bugzilla.mozilla.org/show_bug.cgi?id=403510 to the notes section for Firefox regarding the `scrollIntoViewIfNeeded` method. That bug tracks/requests implementation of that method. Firefox hasn't currently committed to implementing the method.
* https://bugzilla.mozilla.org/show_bug.cgi?id=403510
None
=> Add Firefox impl_url for `api.Element.scrollIntoViewIfNeeded`

css/properties/offset-anchor.json, css/properties/offset-path.json, css/properties/offset-position.json
Missing sub features come from the BCD collector v10.12.7. 
`coord_box` was used in offset-path but in other CSS properties we also expanded this to border-box, content-box, fill-box, stroke-box etc.
=> Add more offset-motion sub features

api/HTMLInputElement.json, html/elements/input.json
https://github.com/whatwg/html/pull/10456
https://github.com/mdn/browser-compat-data/pull/25270
=> Add Chrome and Firefox impl_url for `input.alpha` feature

webassembly/api.json, webassembly/api/Module.json
Chrome 130 supports [WebAssembly JS String builtins](https://github.com/WebAssembly/js-string-builtins/blob/main/proposals/js-string-builtins/Overview.md). Specifically, This PR adds data points for the `compileOptions` parameter used to enable these built-ins, which is added to:
- [`WebAssembly.compile()`](https://developer.mozilla.org/en-US/docs/WebAssembly/JavaScript_interface/compile_static)
- [`WebAssembly.compileStreaming()`](https://developer.mozilla.org/en-US/docs/WebAssembly/JavaScript_interface/compileStreaming_static)
- [`WebAssembly.instantiate()`](https://developer.mozilla.org/en-US/docs/WebAssembly/JavaScript_interface/instantiate_static)
- [`WebAssembly.instantiateStreaming()`](https://developer.mozilla.org/en-US/docs/WebAssembly/JavaScript_interface/instantiateStreaming_sta …
=> Chrome 130 supports WebAssemblyCompileOptions, which enable JS String Builtins

css/properties/-webkit-app-region.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `-webkit-app-region` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.8).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/-webkit-app-region
=> Chromium 24 added `-webkit-app-region` CSS property

api/MessagePort.json
It's likely that iOS should mirror desktop here, but need to verify.
Can't find anything in release notes yet.
=> Mirror Safari iOS for MessagePort worker support

css/at-rules/view-transition.json
See https://webkit.org/blog/16301/webkit-features-in-safari-18-2/
=> @view-transition now supported in Safari 18.2

http/headers/Clear-Site-Data.json
See 
- https://developer.apple.com/documentation/safari-release-notes/safari-18_3-release-notes
- https://github.com/WebKit/WebKit/pull/35724
- https://bugs.webkit.org/show_bug.cgi?id=271700
=> Safari 18.3 unshipped Clear-Site-Data: executionContext

api/Document.json
The spec discourages calling `document.write()` in very clear terms.
See this very intense warning in the spec:
> … [For all these reasons, use of this method is strongly discouraged.](https://html.spec.whatwg.org/multipage/dynamic-markup-insertion.html#document.write())
Discovered in the course of reviewing https://github.com/web-platform-dx/web-features/pull/2405.
=> Mark `api.Document.write` as deprecated

.github/workflows/close-incomplete-issues.yml
This PR updates the auto-issue closer to catch any issues that do not have body text (which means the account had bypassed the issue templates; note we do not allow the blank issue template in our configuration).
=> Close and lock issues without body text

css/properties/anchor-scope.json
#24778 added `anchor-scope`, with `chrome_android` set to false, but it should have been set to `mirror`.
https://chromestatus.com/feature/5094192052436992
=> Chrome Android also supports anchor-scope CSS property

css/properties/bottom.json, css/properties/inset-block-end.json, css/properties/inset-block-start.json, css/properties/inset-block.json, css/properties/inset-inline-end.json, css/properties/inset-inline-start.json, css/properties/inset-inline.json, css/properties/inset.json, css/properties/left.json, css/properties/margin-block-end.json, css/properties/margin-block-start.json, css/properties/margin-block.json, css/properties/margin-bottom.json, css/properties/margin-inline-end.json, css/properties/margin-inline-start.json, css/properties/margin-inline.json, css/properties/margin-left.json, css/properties/margin-right.json, css/properties/margin-top.json, css/properties/margin.json, css/properties/right.json, css/properties/top.json, css/types/anchor-size.json
Chrome 132 supports the [`anchor-size()`](https://developer.mozilla.org/en-US/docs/Web/CSS/anchor-size) function on inset (e.g. [`inset`](https://developer.mozilla.org/en-US/docs/Web/CSS/inset), [`top`](https://developer.mozilla.org/en-US/docs/Web/CSS/top), [`bottom`](https://developer.mozilla.org/en-US/docs/Web/CSS/bottom), and logical equivalents) and margin (e.g. [`margin`](https://developer.mozilla.org/en-US/docs/Web/CSS/margin), [`margin-top`](https://developer.mozilla.org/en-US/docs/Web/CSS/margin-top), [`margin-left`](https://developer.mozilla.org/en-US/docs/Web/CSS/margin-left), and logical equivalents) properties.
This PR adds a data point for `anchor-size()` to each of those properties, and a data point to `anchor-size()` itself to mention inset and margin property support.
See …
=> Chrome 132 supports anchor-size() on margin and inset properties

http/headers/SourceMap.json
You can set a source map for code via annotation (`sourceMappingURL=path/to/thing.map`) or via the HTTP header for that resource:
```
HTTP/1.1 200 OK
Content-Type: application/javascript
SourceMap: /path/to/file.js.map
<my js>
```
This appears to be broken in Chrome for the following case:
```html
<script type="module">
import { thing } from '/file.esm.js';
…
</script>
```
* Bug: https://issues.chromium.org/issues/40854862
* Reproducer: https://test-esm-sourcemap.vercel.app/hidden-sourcemap/esm.html  
Firefox and Safari both show source files in the debugger ("original file" below):
Fixes #18183
=> Chrome not detecting sourcemap set by HTTP header only for ESM JS

html/global_attributes.json
Safari shipped this feature in 15.5. I've also added a specification URL.
- [Safari 15.5 release notes](https://developer.apple.com/documentation/safari-release-notes/safari-15_5-release-notes#:~:text=Fixed%20nonce%20hiding%20from%20the%20DOM)
- Resolved [Webkit bug 179728](https://bugs.webkit.org/show_bug.cgi?id=179728)
- Confirmed [`content-security-policy/nonce-hiding/nonces.html`](https://wpt.live/content-security-policy/nonce-hiding/nonces.html) passed in contemporary browser
Discovered reviewing https://github.com/web-platform-dx/web-features/pull/2423
=> Safari 15.5 shipped `html.global_attributes.a.nonce_hiding`

api/MLContext.json
Not in the spec anymore https://github.com/webmachinelearning/webnn/pull/795
(Discovered by https://github.com/mdn/browser-compat-data/pull/23958)
Also tested in Canary with flag enabled and `compute` is not there anymore.
=> Remove MLContext.compute

api/DedicatedWorkerGlobalScope.json
Found by https://github.com/mdn/browser-compat-data/pull/23958
=> Fix spec urls for DedicatedWorkerGlobalScope message events

api/GPUSupportedLimits.json
Will probably be removed in Chrome 135 https://chromestatus.com/feature/4853767735083008, https://issues.chromium.org/issues/364338810
Gone from the spec: https://github.com/gpuweb/gpuweb/pull/4783
Discovered by https://github.com/mdn/browser-compat-data/pull/23958
=> GPUSupportedLimits.maxInterStageShaderComponents no longer standard

css/properties/-webkit-text-zoom.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `-webkit-text-zoom` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.8).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/-webkit-text-zoom
=> Safari 10 added `-webkit-text-zoom` CSS property

css/properties/-webkit-mask-source-type.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `-webkit-mask-source-type` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.8).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/-webkit-mask-source-type
=> Update Safari data for -webkit-mask-source-type CSS property

css/properties/-webkit-mask-box-image.json
This PR updates and corrects version values for Microsoft Edge for the `-webkit-mask-box-image` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.8).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/-webkit-mask-box-image
=> Edge Legacy did not support `-webkit-mask-box-image` CSS property

css/properties/-webkit-cursor-visibility.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `-webkit-cursor-visibility` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.8).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/-webkit-cursor-visibility
=> Update Safari data for -webkit-cursor-visibility CSS property

css/at-rules/font-face.json
unlike `font-variant` property, `@font-face/font-variant` descriptor has removed from spec for a long time, see https://github.com/w3c/csswg-drafts/issues/2531
https://drafts.csswg.org/css-fonts/#at-font-face-rule
https://drafts.csswg.org/css-fonts-5/#at-font-face-rule
https://github.com/mdn/content/pull/21481 for mdn docs update
https://developer.mozilla.org/en-US/docs/Web/API/FontFace/variant for the similar case
=> Mark `@font-face/font-variant` descriptor as non-standard

http/headers/Upgrade.json
Protocol upgrade was specd in early HTTP versions (https://datatracker.ietf.org/doc/html/rfc2616#section-14.42), but first implemented for WebSocket opening handshakes:
https://www.rfc-editor.org/rfc/rfc6455#section-1.3
- Firefox:
- https://hg.mozilla.org/mozilla-central/rev/9197b91fd9f4
- relnotes: https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/6#networking
- bug: https://bugzilla.mozilla.org/show_bug.cgi?id=640213
- Safari:
- https://github.com/WebKit/WebKit/commit/0410f28cb701a9cca89b035d74ef8ae427cfc3d5
- tagged [Safari-533.9](https://github.com/WebKit/WebKit/releases/tag/Safari-533.9) which is v5
- Chrome:
- https://codereview.chromium.org/155079/
Fixes #25152
=> Chrome 5, Firefox 6, Safari 5 supporting HTTP Upgrade

css/properties/-webkit-hyphenate-limit-before.json
This PR updates and corrects version values for Chrome and Safari for the `-webkit-hyphenate-limit-before` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.8).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/-webkit-hyphenate-limit-before
=> Update Chrome/Safari data for -webkit-hyphenate-limit-before CSS property

html/global_attributes.json
This PR aligns the naming conventions for HTML attribute values, specifically removing the `_value` suffix from `hidden="until-found"` to maintain consistency with other attribute values like `contenteditable="plaintext-only"`. Additionally, compatibility details for the `hidden="until-found"` attribute in Opera have been updated.
Compatibility for Opera was tested as follows:
- Opera 87 (via BrowserStack) — attribute `hidden="until-found"` does not work
- Opera 88 (via BrowserStack) — attribute `hidden="until-found"` works
- Opera 115 (tested on a physical device) — attribute `hidden="until-found"` works
=> Opera supports `hidden="until-found"` + rename `until-found_value` to `until-found`

css/properties/-webkit-hyphenate-limit-lines.json
This PR updates and corrects version values for Chrome and Safari for the `-webkit-hyphenate-limit-lines` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.8).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/-webkit-hyphenate-limit-lines
=> Chrome 16-29 / Safari 6+ support `-webkit-hyphenate-limit-lines` CSS property

css/properties/-webkit-column-progression.json
This PR updates and corrects version values for Chrome and Safari for the `-webkit-column-progression` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.8).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/-webkit-column-progression
=> Chrome 22-34 / Safari 7+ support `-webkit-column-progression` CSS property

css/properties/-webkit-column-axis.json
This PR updates and corrects version values for Chrome and Safari for the `-webkit-column-axis` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.8).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/-webkit-column-axis
=> Chrome 17-34 / Safari 6+ support `-webkit-column-axis` CSS property

css/properties/-webkit-nbsp-mode.json
This PR updates and corrects version values for Chrome and Safari for the `-webkit-nbsp-mode` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.8).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/-webkit-nbsp-mode
=> Chrome 1-27 / Safari support `-webkit-nbsp-mode` CSS property

css/properties/-webkit-line-box-contain.json
This PR updates and corrects version values for Chrome and Safari for the `-webkit-line-box-contain` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.8).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/-webkit-line-box-contain
=> Chrome 12-46 / Safari support `-webkit-line-box-contain` CSS property

css/properties/-webkit-line-snap.json
This PR updates and corrects version values for Chrome and Safari for the `-webkit-line-snap` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.8).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/-webkit-line-snap
=> Chrome 19-33 / Safari 6+ support `-webkit-line-snap` CSS property

css/properties/-webkit-line-grid.json
This PR updates and corrects version values for Chrome and Safari for the `-webkit-line-grid` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.8).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/-webkit-line-grid
=> Chrome 17-33 / Safari 6+ support `-webkit-line-grid` CSS property

css/properties/-webkit-line-align.json
This PR updates and corrects version values for Chrome and Safari for the `-webkit-line-align` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.8).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/-webkit-line-align
=> Chrome 19-33 / Safari 6+ supports `-webkit-line-align` CSS property

css/properties/alignment-baseline.json
This PR updates and corrects version values for Chrome and Safari for the `alignment-baseline` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.8).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/alignment-baseline
=> Chrome 1 / Safari 5.1 add `alignment-baseline` CSS property

css/properties/-webkit-hyphenate-limit-after.json
This PR updates and corrects version values for Chrome and Safari for the `-webkit-hyphenate-limit-after` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.8).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/-webkit-hyphenate-limit-after
=> Chrome 11-29 / Safari support `-webkit-hyphenate-limit-after` CSS property

http/headers/Content-Disposition.json
Adding a note about behavior that deviates in Chrome in the following condition:
```http
Content-Disposition: inline; filename="something"
```
__background:__
Usually, the `filename` parameter is used to prefill the file name for `attachment` types -> this triggers a save-as dialog immediately on navigation:
```http
Content-Disposition: attachment; filename=example.html
```
`inline` means the user agent is supposed to render the document "as usual" instead of prompting the user to download. In this case, adding a filename is allowed for cases where the user saves the document at a later stage. I've added some more details in the linked issue.
__actual behavior:__
Chrome uses the document title (PDF / HTML) instead of the `filename` parameter, which may be unexpected for some developers. …
=> Chrome/Safari ignore Content-Disposition filename on save if disposition type is inline

.github/workflows/update-mdn-urls.yml
Fix the check on dependabot by verifying the user instead of the actor 
Fixes: https://bugzilla.mozilla.org/show_bug.cgi?id=1937337
=> fix: check on user instead of actor in dependabot check

svg/elements/script.json
Marks `svg.elements.script.xlink_href` as deprecated. This is in line with the other SVG elements.
SVG 2 deprecated `xlink:href` in favor of `href` without a namespace. 
https://svgwg.org/svg2-draft/changes.html#linking
https://svgwg.org/svg2-draft/linking.html#XLinkTitleAttribute
=> Mark svg.elements.script.xlink_href as deprecated

api/Request.json, api/Response.json
the feature is added in https://github.com/nodejs/node/commit/4d7706676bd98ceaede12f68e0386645049a03b6 (https://github.com/nodejs/node/pull/53034) 
spec proposal link at https://github.com/whatwg/fetch/issues/1732, feature issue at https://github.com/nodejs/undici/issues/3256
=> Node.js 20.16/22.3 supports `{Request,Response}.bytes()`

api/Request.json, api/_globals/fetch.json
`Request.mode` `navigate` value - not supported by nodejs, like deno
```js
new Request('https://developer.mozilla.org/en-US/docs/Web/API/Request', { mode: 'navigate' }).mode
// Uncaught TypeError: Request constructor: invalid request mode navigate.
//     at webidl.errors.exception (node:internal/deps/undici/undici:3564:14)
//     at new Request (node:internal/deps/undici/undici:9586:31)
```
`Request.targetAddressSpace` - not supported by nodejs and deno, checked in source code for [nodejs](https://github.com/nodejs/node/blob/main/deps/undici/src/lib/web/fetch/request.js) and [deno](https://github.com/denoland/deno/blob/main/ext/fetch/23_request.js)
`RequestInit.attributionReporting` and `RequestInit.browsingTopics` - surely not supported by nodejs and deno
=> Add Node/Deno info for some request features

browsers/deno.json, javascript/builtins/Promise.json
- Adds browser information for Deno 1.46
- Adds Promise.try compatibility information for node and deno, the versions correspond to v8 version 12.8 (Chrome 128) which is the first version that has Promise.try
node - https://github.com/nodejs/node/releases/tag/v23.0.0 - "deps: update V8 to 12.8.374.13"
deno - https://github.com/denoland/deno/releases/tag/v1.46.0 - "feat: upgrade V8 to 12.8"
=> Deno 1.46 / Node 23 support `Promise.try()`

http/headers/Cache-Control.json, lint/linter/test-obsolete.ts
the feature is not supported by any browsers per the bcd entry
it is in https://httpwg.org/specs/rfc5861.html, along with `stale-while-revalidate`, which has been shipped for a long time
per https://issues.chromium.org/issues/40354106 and https://bugzilla.mozilla.org/show_bug.cgi?id=1547587, chrome and firefox seems not to implement this feature
=> Remove never-supported http.headers.Cache-Control.stale-if-error

css/properties/grid-template-columns.json, css/properties/grid-template-rows.json
It's better to point to the Grid Layout module. The entire [fit-content() MDN page](https://developer.mozilla.org/en-US/docs/Web/CSS/fit-content_function) is about the Grid layout and not the box-sizing.
=> Update spec url for `grid-template-{columns,rows}.fit-content()`

css/selectors/active.json, css/selectors/autofill.json, css/selectors/checked.json, css/selectors/defined.json, css/selectors/dir.json, css/selectors/disabled.json, css/selectors/enabled.json, css/selectors/hover.json, css/selectors/indeterminate.json, css/selectors/invalid.json, css/selectors/link.json, css/selectors/modal.json, css/selectors/open.json, css/selectors/optional.json, css/selectors/placeholder-shown.json, css/selectors/popover-open.json, css/selectors/read-only.json, css/selectors/read-write.json, css/selectors/required.json, css/selectors/target.json, css/selectors/user-invalid.json, css/selectors/user-valid.json, css/selectors/valid.json, css/selectors/visited.json
for some pseudo classes, only one spec is added (either the whatwg one, or the csswg one)
for others, the csswg one link to the paragraph title, rather than the link directly to that feature
=> Update spec urls of CSS pseudo classes

api/TransformStream.json, browsers/nodejs.json
The transformer object passed to the `TransformStream` constructor can now also have a `cancel` method, which is called whenever the readable side is cancelled or when the writable side is aborted. See [the specification](https://streams.spec.whatwg.org/#dom-transformer-cancel) and [the spec change](https://github.com/whatwg/streams/pull/1283) for context.
This method is not yet supported in any browser. However, server runtimes such as Node.js and Deno already support it:
* Node.js: implemented in https://github.com/nodejs/node/commit/3dd96f1fabf39661dcebd4f3677c76d9a670e04e, shipped in [version 20.14.0](https://nodejs.org/en/blog/release/v20.14.0)
* Deno: implemented in https://github.com/denoland/deno/commit/6450334f5bbb059b55005cebfef57fa7969b625e, shipped in [version …
=> Add `transformer.cancel` method to `TransformStream` constructor

css/properties/position-area.json
Chrome 131 removed `inset-area`, the old name of `position-area`.
This commit mentions it: https://github.com/chromium/chromium/commit/36e8cecee4e2b221a8117f330567f91cd65532c5
Computed properties no longer returns it: https://github.com/caugner/css-properties/commit/7f36097f36c02253b09fd04592fdb1dfff752176
=> Chrome 131 removed inset-area

css/properties/-webkit-border-horizontal-spacing.json, css/properties/-webkit-border-vertical-spacing.json, css/properties/-webkit-column-break-after.json, css/properties/-webkit-column-break-before.json, css/properties/-webkit-column-break-inside.json, css/properties/-webkit-locale.json, css/properties/-webkit-logical-height.json, css/properties/-webkit-logical-width.json, css/properties/-webkit-margin-after.json, css/properties/-webkit-margin-before.json, css/properties/-webkit-max-logical-height.json, css/properties/-webkit-max-logical-width.json, css/properties/-webkit-min-logical-height.json, css/properties/-webkit-min-logical-width.json, css/properties/-webkit-perspective-origin-x.json, css/properties/-webkit-perspective-origin-y.json, css/properties/-webkit-rtl-ordering.json, css/properties/-webkit-text-combine.json, css/properties/-webkit-text-decorations-in-effect.json, css/properties/-webkit-transform-origin-x.json, css/properties/-webkit-transform-origin-y.json, css/properties/-webkit-transform-origin-z.json, css/properties/-webkit-user-drag.json
This PR updates and corrects version values for Chrome and Safari for various `-webkit-*` CSS properties. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.8).
=> Update Chrome/Safari data for -webkit-* CSS property

css/properties/line-break.json
This PR updates and corrects version values for all browsers for the `line-break` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.7).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/line-break
=> Update all browsers data for line-break CSS property

css/properties/white-space.json
see https://github.com/mdn/content/pull/37494 for details
https://drafts.csswg.org/css-text-4/#propdef-white-space for spec
=> Update Chrome note for `white-space` to new syntax

css/at-rules/charset.json
=> Update spec_url of `@charset` from css2 to css3

api/ReadableStreamBYOBReader.json, api/ReadableStreamDefaultReader.json, browsers/nodejs.json
Update the compatibility data for `reject_pending_read_request` in both `ReadableStreamDefaultReader` and `ReadableStreamBYOBReader`. See https://github.com/whatwg/streams/pull/1168 for context. All major browsers now implement the new behavior.
* Chrome added support in version 105. See [the Chromium bug](https://issues.chromium.org/issues/40211172) and [the diff between Chrome 104 and 105 on wpt.fyi](https://wpt.fyi/results/streams/readable-streams/templated.any.html?label=master&product=chrome-104&product=chrome-105).
* Edge added support in version 105, mirroring Chrome. See [the diff on wpt.fyi](https://wpt.fyi/results/streams/readable-streams/templated.any.html?label=master&product=edge-104&product=edge-105).
* Safari added support in version 17.0. See [the Webkit …
=> Chrome/Deno/Node/Safari started rejecting `ReadableStream*Reader.releaseLock()` with pending read requests

api/CSS.json
Extracts `optional_parens` sub-feature of `CSS.supports()`.
Spec change from July 2016: https://github.com/w3c/csswg-drafts/commit/042f955362de14e1601af8d072c9c211a9024fb6
=> Extract CSS.supports() sub-feature `optional_parens`

html/elements/script.json, http/headers/No-Vary-Search.json
`No-Vary-Search` and `expects_no_vary_search` where originally implemented for `prefetch` only  but as of Chrome 127 also support prerender.
Demo site used to test:
https://speculation-rules-no-vary-search.glitch.me/prerender.html
Details of when it was added:
https://chromestatus.com/feature/5099218903760896
=> No-Vary-Search and expects_no_vary_search are now supported for prerender

http/headers/No-Vary-Search.json
Add link to No-Vary-Search spec. Currently this shows like below on [the MDN page](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/No-Vary-Search#specifications):
It is also the old WICG link, but this has since [been accepted into the IETF HTTP Working group](https://lists.w3.org/Archives/Public/ietf-http-wg/2024JulSep/0301.html) (hence the new URL for the spec).
Note the old link (https://wicg.github.io/nav-speculation/no-vary-search.html) redirects to the link proposed in this PR (https://httpwg.org/http-extensions/draft-ietf-httpbis-no-vary-search.html).
=> No-Vary-Search spec

api/PublicKeyCredential.json, api/RTCStatsReport.json, css/properties/-moz-user-input.json, javascript/builtins/JSON.json
The @openwebdocs [BCD collector project](https://github.com/openwebdocs/mdn-bcd-collector) v10.12.8 found new features shipping in Firefox 135 beta which was released yesterday. Currently, the collector covers about 90% of BCD, so the following list might not be exhaustive. Also, if a feature is in Firefox Nightly only, it is not considered here.
With this PR, BCD considers the following 10 features as shipping in Firefox 135:
- api.PublicKeyCredential.getClientCapabilities_static
- api.RTCStatsReport.type_inbound-rtp.mid (manually added)
- api.RTCStatsReport.type_outbound-rtp.mid (manually added)
- api.RTCStatsReport.type_outbound-rtp.rid (manually added)
- css.properties.-moz-user-input (removal)
- css.properties.-moz-user-input.auto (removal)
- css.properties.-moz-user-input.none …
=> Updates for Firefox 135 beta

api/PublicKeyCredential.json
While documenting some new methods on the [`PublicKeyCredential`](https://developer.mozilla.org/en-US/docs/Web/API/PublicKeyCredential) interface, it struck me how the BCD table doesn't look great, especially the static methods that are just showing `methodName_static` for the label.
This PR adds `description` fields to the methods to make them more consistent and improve the rendering.
see https://github.com/mdn/content/pull/37557 for the new method documentation.
=> Add publicKeyCredential method descriptions

api/Request.json, api/WebSocketError.json, api/WebSocketStream.json, html/elements/script.json, lint/linter/test-tags.test.ts, lint/linter/test-tags.ts, package-lock.json, package.json
Prevent BCD authors from creating new web-features tags (i.e., BCD uses web-features IDs as an allowlist for tags)
Updated test files so that `'web-features:foo'` fails and `'web-features:javascript'` passes.
@ddbeck, Kadir and I talked about the entire workflow yesterday and while want BCD authors to use and apply existing web-feature IDs to BCD features (useful for when BCD features are renamed, or when existing features get additions), we want to prevent that entirely new feature IDs are created in BCD. Instead they should be created in web-features.
For more details, see https://github.com/web-platform-dx/web-features/issues/1672#issuecomment-2578098349
=> Allowlist web-feature tags

api/Window.json
WebVR has been removed. Fix this for some events on window.
Discovered when grouping the feature keys in https://github.com/web-platform-dx/web-features/pull/2512
=> Mark remaining WebVR features as removed

api/HTMLCanvasElement.json, api/Navigator.json, api/OffscreenCanvas.json, api/WorkerNavigator.json
Chrome Android supports `Navigator.gpu`.
All GPU features that were first supported in Chrome Desktop 113, appear to be supported in Chrome Android 121, so I have set the value accordingly.
Checked with Chrome Android 128 via BrowserStack Live.
Fixes https://github.com/mdn/browser-compat-data/issues/22159, complementing https://github.com/mdn/browser-compat-data/pull/23493.
=> Chrome Android 121 supports Navigator.gpu + Canvas webgpu_context

api/Document.json
For every `Document` member that, in some Firefox versions, is only exposed to `HTMLDocument` (and not also to `SVGDocument` and `XMLDocument`), ensures that there is a corresponding note.
Source: https://github.com/caugner/document-members/blob/main/SUMMARY.md#firefox
Part of https://github.com/mdn/browser-compat-data/issues/10682.
=> Add Document member support notes for Firefox

api/Document.json
For every `Document` member that, in some Chrome versions, is only exposed to `HTMLDocument` (and not also to `SVGDocument` and `XMLDocument`), ensures that there is a corresponding note.
Source: https://github.com/caugner/document-members/blob/main/SUMMARY.md#chrome
Part of https://github.com/mdn/browser-compat-data/issues/10682.
=> Add Document member support notes for Chrome

api/Document.json
For every `Document` member that, in some Safari versions, is only exposed to `HTMLDocument` (and not also to `SVGDocument` and `XMLDocument`), ensures that there is a corresponding note.
Source: https://github.com/caugner/document-members/blob/main/SUMMARY.md#safari
This includes some fixes where current data was wrong:
- `alinkColor`, `designMode`, `scripts` were already added in Safari 1.
- `write` was only fixed in Safari 11.
Part of https://github.com/mdn/browser-compat-data/issues/10682.
=> Add Document member support notes for Safari

api/Request.json, api/_globals/fetch.json
Add subfeature for [the fetch spec change allowing `ReadableStream` as `fetch()` body in 2017](https://github.com/whatwg/fetch/pull/425).
- Chrome ✅ - see https://issues.chromium.org/issues/40505032 / https://chromiumdash.appspot.com/commit/9bbd1d6504a1d63d1b409e696c522497b111a572
- Deno ✅ - see https://deno.com/blog/v1.7#support-for-fetch-request-body-streaming
- Firefox ❌ - see https://bugzilla.mozilla.org/show_bug.cgi?id=1387483
- Node.js ✅ - see https://github.com/nodejs/undici/commit/95c82ab48758f5ec6aa566b2d8fb0adaa6e8430f#diff-bd6db9a8bceb4e9fce3f93ba5284c81f46a44a1187909e8609006e1efeab2570R20
- Safari ❌ - see https://searchfox.org/wubkat/rev/aff26e20aa2d3bdc4f9666b090b8f912c0a3deec/Source/WebCore/Modules/fetch/FetchResponse.cpp#274
Test case:
```js
// Create a simple …
```
=> Chrome 105 / Deno 1.7 / Node 18 support `fetch()` with `ReadableStream` body

html/elements/input/number.json
Add notes for the way Chrome and Firefox/Safari behave differently to non-numeric user input.
Using BrowserStack Live and local installs, I verified the behavior
- in the current browser versions, and
- in the earliest versions that support `<input type="number">`.
Fixes #13403.
=> Chrome prevents + Firefox/Safari allow non-numeric user input to number fields

api/KeyboardEvent.json
The `KeyboardEvent.code` appears to be always empty on Android.
Fixes #13807.
=> KeyboardEvent.code is always empty on Android

css/properties/overflow.json, css/types/overflow.json
Before `overflow: overlay` became a standardized legacy alias, it had non-standard behavior in Chrome and Safari.
The data already existed for the standard behavior. For the non-standard behavior, I relied mostly on:
- https://chromestatus.com/feature/5194091479957504
- https://bugs.webkit.org/show_bug.cgi?id=189811
- https://caniuse.com/css-overflow-overlay
I didn't actually test the introduction of the non-standard behavior, figuring that it's the boundary between standard and non-standard that was most interesting. That said, the version numbers involved look plausible based on commit dates.
- Needed for https://github.com/web-platform-dx/web-features/pull/2486/
- Previously:
- https://github.com/mdn/browser-compat-data/pull/15834
- …
=> `overflow: overlay`: add pre-standardization compat details

api/ClipboardItem.json
Chrome 133 now supports using item data of type string or a promise that resolves to a string when constructing a [`ClipboardItem`](https://developer.mozilla.org/en-US/docs/Web/API/ClipboardItem/ClipboardItem) object. Previously, Chrome only supported item data of type `Blob`, or a promise that resolves to a `Blob`, but this change brings it up to full standards support and parity with Firefox and Safari.
I've tested it to verify it works in Chrome 133 and can confirm also that it doesn't work in Chrome 132.
See https://chromestatus.com/feature/4926138582040576 for the data source.
The example I used for testing can be found at https://clipboard-api-string-test.glitch.me/.
=> Chrome 133 supports string data for ClipboardItem

html/manifest/share_target.json
See https://github.com/w3c/browser-specs/pull/1646 where the standing was put back to "good".
=> Re-add web share target specification

api/Animation.json, api/Document.json, api/DocumentFragment.json, api/Element.json, api/FileSystemObserver.json, api/HTMLAreaElement.json, api/PerformanceResourceTiming.json, api/PublicKeyCredential.json, api/SubtleCrypto.json, css/properties/container-type.json, css/properties/scroll-initial-target.json, css/selectors/open.json, css/types/attr.json, javascript/builtins/Atomics.json, webassembly/memory64.json
The @openwebdocs [BCD collector project](https://github.com/openwebdocs/mdn-bcd-collector) v10.12.8 found new features shipping in Chrome 133 beta which was released yesterday. Currently, the collector covers about 90% of BCD, so the following list might not be exhaustive. Also, if a feature is in Chrome Canary/behind origin trials/enrollment, it is not considered here.
With this PR, BCD considers the following 41 features as shipping in Chrome 133:
- api.Animation.overallProgress
- api.ClipboardItem.ClipboardItem
- api.Document.moveBefore
- api.DocumentFragment.moveBefore
- api.Element.moveBefore
- api.FileSystemObserver
- api.FileSystemObserver.FileSystemObserver
- api.FileSystemObserver.disconnect
- api.FileSystemObserver.observe
- api.HTMLAreaElement.attributionSrc
- …
=> Updates for Chrome 133 beta

api/SubtleCrypto.json
Chrome 37-40 supported `SubtleCrypto.digest()` only partially, because it expected the `algorithm` parameter to be an object rather than a string.
Verified with BrowserStack Live, see: https://github.com/mdn/browser-compat-data/issues/14804#issuecomment-2596082365
Fixes https://github.com/mdn/browser-compat-data/issues/14804.
=> Chrome 37-40 partially implemented SubtleCrypto.digest()

scripts/diff-features.ts
Makes the `diff-features` script more resilient to missing refs.
In our case, the GitHub API returns the wrong merge commit, which is not in the `main` branch.
As a workaround, let's fall back to fetching the missing commit.
Fixes https://github.com/mdn/browser-compat-data/issues/25678.
=> fix(scripts/diff-features): fetch missing ref

http/headers/Sec-CH-Prefers-Color-Scheme.json, http/headers/Sec-CH-Prefers-Reduced-Motion.json, http/headers/Sec-CH-Prefers-Reduced-Transparency.json, http/headers/Sec-CH-UA-Arch.json, http/headers/Sec-CH-UA-Bitness.json, http/headers/Sec-CH-UA-Full-Version-List.json, http/headers/Sec-CH-UA-Full-Version.json, http/headers/Sec-CH-UA-Mobile.json, http/headers/Sec-CH-UA-Model.json, http/headers/Sec-CH-UA-Platform-Version.json, http/headers/Sec-CH-UA-Platform.json, http/headers/Sec-CH-UA.json
`Sec-CH-Prefers-Reduced-Transparency` is not sent.
Samsung Internet added support for Client Hints only in 23.0, not in 15.0.
Tested locally using https://browserleaks.com/client-hints with an Android phone:
- :x: 21.0.3.6
- :x: 22.0.6.9
- ✅ 23.0.8.2
- ✅ 24.0.7.1
Fixes https://github.com/mdn/browser-compat-data/issues/15821.
=> Samsung Internet 23.0 supports most Client Hints

api/GPUDevice.json, api/IdentityProvider.json, api/Navigator.json
I just ran the collector on the release version of Chrome 132 and here are three new APIs that are reported as shipping. Maybe they came late in the 132 beta cycle.
I will have a PR for the fresh Chrome 133 beta later today.
=> Updates for Chrome 132 release (late additions)

api/ScreenOrientation.json
Replicates the support statements from `ScreenOrientation.lock()`.
_Note_: It is somewhat surprising that the feature was supposedly already added in Firefox Android 43 and removed in Firefox Android 79, but this is harder to research and definitely less severe than saying Firefox Android supports `unlock()`.
Firefox doesn't support `ScreenOrientation.{lock,unlock}()` yet, so Firefox Android cannot support it either, see: https://bugzilla.mozilla.org/show_bug.cgi?id=1744125
Fixes #15919.
=> Firefox Android doesn't support ScreenOrientation.unlock() yet

scripts/diff-features.ts
Replaces the wrong merge commit hash with the correct one.
The previous workaround didn't work, because fetching the wrong merge commit fails: https://github.com/mdn/browser-compat-data/actions/runs/12830337479/job/35778298222#step:6:32
Ran `npm run release` locally on this branch, and it worked.
Fixes #25678.
=> fix(script/diff-features): replace wrong merge commit ref

html/elements/a.json
Firefox Android only partially supports the `download` attribute on an `<a>` element.
Tested myself with BrowserStack Live and BrowserStack Local, see: https://github.com/mdn/browser-compat-data/issues/16069#issuecomment-2598340070
Fixes https://github.com/mdn/browser-compat-data/issues/16069.
=> Firefox Android only supports `a[download]` for `blob:`/`data:` URI schemes

css/types/gradient.json
Removes irrelevant `impl_url` and flag data for CSS gradient subfeatures.
1. We don't usually record commits as `impl_url`.
2. See Guidelines about [Removal of irrelevant flag data](https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines/index.md#removal-of-irrelevant-flag-data).
See https://github.com/mdn/browser-compat-data/issues/16598#issuecomment-2598805316.
=> Remove irrelevant CSS gradient impl_url and flag data

webassembly/api.json, webassembly/api/Module.json
Firefox appears to support all of the WebAssembly JS String builtins proposal, but keys added later weren't updated to reflect this. This PR corrects the issue.
Reading across the following links, it appears that Firefox fully implemented wasm JavaScript String builtins, initially represented by `webassembly.jsStringBuiltins` only; when Chris added the `compile_options` keys, they weren't reconciled with the existing Firefox data.
- https://bugzilla.mozilla.org/show_bug.cgi?id=1863794
- https://github.com/mdn/browser-compat-data/pull/25230
- https://github.com/mdn/browser-compat-data/pull/25391
Discovered in the course of https://github.com/web-platform-dx/web-features/pull/2549.
=> Show Firefox support across all of WebAssembly JS String builtins

api/SpeechSynthesisEvent.json
Safari iOS 16 added `SpeechSynthesisEvent.utterance`, not Safari iOS 7.
See: https://github.com/mdn/browser-compat-data/issues/16864#issuecomment-2599248183
Fixes https://github.com/mdn/browser-compat-data/issues/16864.
=> Safari iOS 16 added `SpeechSynthesisEvent.utterance`

api/RTCPeerConnection.json
Fixes Chrome support data for the following `RTCPeerConnection` parameters:
- `iceCandidatePoolSize`
- `iceServers`
- `iceTransportPolicy` (aka `iceTransports`)
See https://github.com/mdn/browser-compat-data/issues/16595#issuecomment-2598717595 for the evidence.
Fixes https://github.com/mdn/browser-compat-data/issues/16595.
=> Fix Chrome support for RTCPeerConnection parameters

javascript/builtins/Date.json
Everything for Temporal has been added under ./javascript/builtins/Temporal
This seems to be missed because it's exposed under Date instead:
>Use this method to convert legacy Date values to the Temporal API, then further convert it to other Temporal classes as necessary.
Spec: https://tc39.es/proposal-temporal/#sec-date.prototype.totemporalinstant
Incoming docs: https://github.com/mdn/content/blob/1a21ed666271ebd4ed404ab009f4410d2e047e9f/files/en-us/web/javascript/reference/global_objects/date/totemporalinstant/index.md?plain=1
Example:
```js
const legacyDate = new Date("2021-07-01T12:34:56.789Z");
const instant = legacyDate.toTemporalInstant();
console.log(instant);
// Further convert to other objects
const zdt = instant.toZonedDateTimeISO("UTC");
const date = zdt.toPlainDate(); …
```
=> Add Date.toTemporalInstant

javascript/builtins/Temporal/Instant.json, javascript/builtins/Temporal/Now.json
I'm going through Temporal entries and fixing a few oddities.
__Changes:__
- Rename `timeZoneID` -> `timeZoneId` 
- typo in Temporal Instant; `zoneddatetime` -> `instant`
=> Rename Temporal timeZoneID -> timeZoneId, typo

css/properties/font-family.json
- Adds support info for the generic font families: `ui-serif`, `ui-sans-serif`, `ui-monospace`, and `ui-rounded`.
- Links to MDN docs per value
These are supported [since Safari 13.1](https://webkit.org/blog/10247/new-webkit-features-in-safari-13-1/#:~:text=new%20font%20keywords%20are%20available%20for%20using%20platform-specific%20fonts)
Tests show that Chrome and Firefox don’t support those.
=> Safari 13.1 supports `font-family` values for ui-families

api/CanvasRenderingContext2D.json
Firefox doesn't support `createPattern()` values `repeat-{x,y}` with `fill()`.
See: https://bugzilla.mozilla.org/show_bug.cgi?id=468358#c10
Fixes https://github.com/mdn/browser-compat-data/issues/16460.
=> Firefox doesn't support `createPattern()` values `repeat-{x,y}` with `fill()`

html/elements/link.json
Firefox 127 supports `dns-prefetch` on HTTPS pages. Before that, only HTTP pages were supported.
Source: https://bugzilla.mozilla.org/show_bug.cgi?id=1596935
See #16299.
=> Firefox 127 supports `dns-prefetch` on HTTPS pages

browsers/deno.json
Updates the releases data for Deno to include the missing releases of v2.0, and v2.1
Information validated against the Deno release notes available:
- https://github.com/denoland/deno/releases
- https://deno.com/blog/v2.0
- https://deno.com/blog/v2.1
=> Add Deno 2.0/2.1 releases

css/properties/column-gap.json
Safari supports `column-gap` with percentages (since 12) and `calc()` values (since 12.1).
See: https://github.com/mdn/browser-compat-data/issues/16972#issuecomment-2602948836
Fixes https://github.com/mdn/browser-compat-data/issues/16972.
=> Safari supports CSS column-gap with percentages and `calc()` values

css/properties/page-break-after.json, css/properties/page-break-before.json, css/properties/page-break-inside.json
CSS Fragmentation Module Level 3 calls these "legacy shorthands", which implies their deprecation.
See:
- https://drafts.csswg.org/css-break/#page-break-properties
- https://drafts.csswg.org/css-cascade-5/#legacy-shorthand
See also: https://github.com/mdn/browser-compat-data/issues/21233#issuecomment-2607918760
Fixes https://github.com/mdn/browser-compat-data/issues/21233.
=> Deprecate `page-break-{after,before,inside}`

api/FileSystemSync.json, api/Window.json
Safari 6 added and Safari 8 removed FileSystemSync and webkitRequestFileSystem
See: https://github.com/mdn/browser-compat-data/issues/20811#issuecomment-2605926666
> The [commit](https://github.com/WebKit/WebKit/commit/f28579c215697ad52dd3d8182322c0174d0925f7) landed in [WebKit 538.2.0](https://github.com/WebKit/WebKit/blob/f28579c215697ad52dd3d8182322c0174d0925f7/Source/WebCore/Configurations/Version.xcconfig#L24-L26) before Safari 8/538.35.
> 
> It looks like webkitRequestFileSystem() was originally implemented in https://github.com/WebKit/WebKit/commit/b90d4ad935235d029997db77bb3b314579a00f4b in [WebKit 534.7.0](https://github.com/WebKit/WebKit/blob/b90d4ad935235d029997db77bb3b314579a00f4b/WebCore/Configurations/Version.xcconfig#L24-L26) before Safari 5.1/534.48.
> 
> FileSystemSync …
=> Safari 6 added and Safari 8 removed `FileSystemSync` and `webkitRequestFileSystem`

css/properties/block-size.json, css/properties/inline-size.json
…al-*`
Chrome and Safari already supported the new `block-size` and `inline-size` properties as `-webkit-logical-width` and `-webkit-logical-height` before they were standardized.
See:
- https://github.com/WebKit/WebKit/commit/d2ecf440f5acbcd9d38ca461822e29ca42769366
Fixes https://github.com/mdn/browser-compat-data/issues/17724.
=> Chrome 8 + Safari 5.1 supported {block,inline}-size via `-webkit-logical-*`

api/DragEvent.json, api/MouseEvent.json
Chrome 60 and Firefox 59 set `relatedTarget` on `DragEvent`, but Safari doesn't.
Bugs:
- https://bugs.chromium.org/p/chromium/issues/detail?id=159534
- https://bugzilla.mozilla.org/show_bug.cgi?id=1420590
- https://bugs.webkit.org/show_bug.cgi?id=66547
Fixes https://github.com/mdn/browser-compat-data/issues/16871.
=> Chrome 60 and Firefox 59 set `relatedTarget` on `DragEvent`

api/HTMLInputElement.json
Chrome for Android 132 fully supports webkitdirectory. Thinking about it, I don't remember why this wasn't added as part of #25036
Used webkitdirectory on the latest Chrome for Android.
=> Chrome for Android 132 fully supports webkitdirectory

http/headers/X-Frame-Options.json
Unmark X-Frame-Options as deprecated
This was added in https://github.com/mdn/browser-compat-data/pull/24466
When people view the X-Frame-Options page they're presented with:
A warning that says this feature may be removed from browsers isn't helpful for a security feature that we realistically cannot remove from browsers.
By all means MDN can and should (and does per https://github.com/mdn/content/pull/35942) point to CSP frame-ancestors as a (more powerful) alternative, this is deprecation warning isn't useful nor accurate.
=> Undeprecate X-Frame-Options

css/properties/box-shadow.json
Subfeatures of `box-shadow` have some misleading `prefix` statements (which is misleading, because the prefix applies to the parent feature) and some unnecessarily `notes` (duplicated from the parent).
=> Remove unnecessary prefixes/notes from `box-shadow` subfeatures

javascript/builtins/Intl/DateTimeFormat.json, javascript/builtins/Intl/NumberFormat.json
The spec doesn't appear to discourage these features.
These features are specified as a "Normative Optional" but not "Normative Optional, Legacy" behavior. Given [the distinction that the spec makes between legacy and non-legacy](https://tc39.es/ecma262/#sec-conformance) parts of the language, "[Normative optional](https://tc39.es/ecma402/#sec-chaindatetimeformat)" should not be marked as deprecated.
Confusingly, the symbol's description contains the substring `Legacy`. This was [a later addition to the spec](https://github.com/tc39/ecma402/commit/44107b64949017960c905ebb876216a2075973e7) that doesn't have much of a paper trail (and is older than the contemporary specification's "legacy" terminology—that is, it didn't have a defined meaning at the time). I think we should weigh the spec's …
=> Set `IntlLegacyConstructedSymbol` to non-deprecated

package.json, scripts/tag-web-features.ts
The new GitHub Action to tag web-features [fails](https://github.com/mdn/browser-compat-data/actions/runs/12943342712/job/36113877559) and I realize it makes no sense to broadly run `npm run fix` here. Instead the tags should be inserted to the JSON files properly from the beginning. We have `stringifyAndOrderProperties` for that purpose. Also adding JSDocs because there was a warning about this.
Followup to https://github.com/mdn/browser-compat-data/pull/25704
=> Order tagged features properly and not with fix linter

webassembly/jsStringBuiltins.json
This shows Chrome for Android as supporting wasm JS string builtins.
This data was untouched in the course of https://github.com/mdn/browser-compat-data/pull/25391; I believe it was error rather than an intentional omission, given the reported [support in Chrome Platform Status](https://chromestatus.com/feature/6695587390423040). See https://github.com/mdn/browser-compat-data/pull/25706 for past errors along these lines.
- https://github.com/mdn/browser-compat-data/pull/25391
- https://github.com/mdn/browser-compat-data/pull/25706
- Discovered in the course of https://github.com/web-platform-dx/web-features/pull/2579/
=> `webassembly.jsStringBuiltins`: show support in Chrome for Android

api/HTMLMeterElement.json, html/elements/meter.json
This makes the data for the `<meter>` element and API more consistent for Edge.
I was able to make an educated guess on the starting version 13 from these [release highlights](https://blogs.windows.com/msedgedev/2015/11/16/introducing-edgehtml-13-our-first-platform-update-for-microsoft-edge/) from Microsoft. Manual testing in Edge 18, 17, and 14 showed that the `labels` API was the only part that landed later.
This will make things make more sense for https://github.com/web-platform-dx/web-features/pull/1419.
=> `<meter>` element: update Edge support data

webextensions/api/webRequest.json
Adding the `"__compat"` directive to the `details` object for all the events in the `webRequest` API. Without this these details are not presented on MDN.
Undertaken to support [Bug 1602005](https://bugzilla.mozilla.org/show_bug.cgi?id=1602005) webRequest.onHeadersReceived: more object "details" properties than in the documentation
=> Add `details` support data for webextensions.api.webRequest

css/properties/content-visibility.json
Safari does not fully implement [`content-visibility: auto` according to the spec](https://drafts.csswg.org/css-contain/#valdef-content-visibility-auto):
> Unlike [hidden](https://drafts.csswg.org/css-contain/#valdef-content-visibility-hidden), the [skipped contents](https://drafts.csswg.org/css-contain/#skips-its-contents) _must_ still be available as normal to user-agent features such as find-in-page, tab order navigation, etc., and must be focusable and selectable as normal.
Since [Safari 18 introduced this feature](https://webkit.org/blog/15865/webkit-features-in-safari-18-0/#content-visibility), any website that already use `content-visibility: auto` as a progressive enhancement are broken for find-in-page.
It doesn’t seem possible to automate testing of the find-in-page feature of …
=> Safari 18 only partially implements `content-visibility: auto`

api/HTMLElement.json
The major bug with light dismiss has been addressed.
Popover attribute is now fully supported on iOS Safari as of 18.3.
See https://developer.apple.com/documentation/safari-release-notes/safari-18_3-release-notes#Web-API
=> Safari iOS 18.3. fully supports popover

api/HTMLElement.json
Safari Tech Preview supports the focusVisible option of the focus method.
See https://webkit.org/blog/16445/release-notes-for-safari-technology-preview-212/
Fixes #25765
=> Safari TP supports focus with focusVisible parameter

api/Request.json, api/_globals/fetch.json, browsers/nodejs.json
data taken from `Request.duplex`
Spec proposal change at https://github.com/whatwg/fetch/pull/1493
Relates to https://github.com/mdn/content/issues/31735
Depends on https://github.com/mdn/browser-compat-data/pull/25486 and https://github.com/mdn/browser-compat-data/pull/25487
=> Add `Request()` constructor `init.duplex` parameter

javascript/builtins/AggregateError.json
Note: This PR is somewhat incomplete. Please read fully before merging.
`AggregateError`'s serialization is potentially standard track, depending on how you look at it. I'm opening this to settle the question. After some head scratching, I'm proposing that `AggregateError`'s serialization be marked as standard track, with _all_ implementations being marked as partial, but I'm open to other views.
The HTML spec is somewhat odd when it comes to the serialization of errors. Note step 17 in section [<span class="secno">2.7.3</span> <dfn>StructuredSerializeInternal</dfn> ( <var>value</var>, <var>forStorage</var> [ , <var>memory</var> ] )](https://html.spec.whatwg.org/multipage/structured-data.html#structuredserializeinternal).
There are two noteworthy things here:
- It describes handling for …
=> `AggregateError` serialization is standard track

html/elements/meta.json
Edge just shipped, in Chromium, a new name that can be used with `<meta>` tags. This name is `application-title` and is used to provide text content (via the `content` attribute) that should be displayed in an installed application's title bar.
Installed application: a web app that's been installed as a standalone app on desktop operating systems that support it. For example, when installing a PWA from Microsoft Edge, on Windows.
This new meta tag makes it easy for developers to control the content that appears in the standalone app window's title bar. Developers can still use the `<title>` element (still works), but using `<meta name="application-title" content="...">` provides an additional mechanism just for when the app is installed, which can help avoid UX issues (learn more from the …
=> Chrome/Edge 134 support experimental `<meta name="application-title">`

schemas/browsers.schema.json
Makes the `engine_version` required if `engine` is set.
It does not seem to change the build output, so I don't think this is a breaking change.
Fixes https://github.com/mdn/browser-compat-data/issues/22843.
=> chore(schemas/browsers): make engine_version required if engine is set

css/at-rules/page.json
these css features are also supported in Edge & Chrome Android & Webview Android
https://github.com/mdn/browser-compat-data/issues/25799
https://chromestatus.com/feature/5195769732923392
https://learn.microsoft.com/en-us/deployedge/microsoft-edge-relnote-stable-channel#version-1310290348-november-14-2024
Fixes https://github.com/mdn/browser-compat-data/issues/25799
=> Edge & Chrome/Webview Android also support `@page` margin at-rules

webextensions/api/menus.json
Addresses the dev-docs-needed requirements of [Bug 1688743](https://bugzilla.mozilla.org/show_bug.cgi?id=1688743) menus.remove doesn't return an error when removing a non-existing menu item by adding a note about the `update` and `remove` methods returning an error message.
Related to release note added in https://github.com/mdn/content/pull/37720
=> Menu update and remove error message support note

.github/workflows/close-incomplete-issues.yml, .github/workflows/issue-regex-labeler.yml, .github/workflows/labeler.yml, .github/workflows/ping-other-repos.yml, .github/workflows/pr-reviewdog.yml, .github/workflows/release-pr.yml, .github/workflows/update-browser-releases.yml, .github/workflows/update-mdn-urls.yml, .github/workflows/update-web-features.yml
Assign explicit workflow permissions, and pin 3rd party actions.
This resolves 12 CodeQL alerts of medium severity (see [here](https://github.com/mdn/browser-compat-data/security/code-scanning?query=pr%3A25793+tool%3ACodeQL+is%3Aopen) for those with access).
=> fix(workflows): assign explicit permissions + pin 3rd party actions

javascript/builtins/AggregateError.json
I wasn't super satisfied with merging https://github.com/mdn/browser-compat-data/pull/25744 as is. This completes the work I suggested in the original description, following the discussion.
I tested this manually in BrowserStack, with the test code mentioned in the previous PR.
https://github.com/mdn/browser-compat-data/pull/25744
=> Chrome 98 / Firefox 103 / Safari 17 support `AggregateError` serialization

api/ReadableStreamDefaultReader.json
The compat data was updated in #24553, but we forgot to also update the constructor's data.
=> Safari 10 also supports `ReadableStreamDefaultReader` constructor

html/elements/script.json
This PR adds a data point for multiple import maps support, which was documented by @yoavweiss in https://github.com/mdn/content/pull/37739.
It has the following support:
- Chrome 133+: https://chromestatus.com/feature/5121916248260608
- WebKit Nightly branch: https://bugs.webkit.org/show_bug.cgi?id=279025
Spec PR: https://github.com/whatwg/html/pull/10528
=> Chrome 133 + Safari TP support multiple import maps

.github/ISSUE_TEMPLATE/data-problem.yml, .github/ISSUE_TEMPLATE/enhancement.yml, .github/ISSUE_TEMPLATE/infra-problem.yml
Updates the issue templates to use the correct `needs triage` label, which is the one we use in the MDN org across repos ( `needs-triage` doesn't exist).
=> fix(issue-templates): use correct "needs triage" label

lint/fixer/property-order.ts
Ensures that property order issues in browser files are not only reported by `npm run lint`, but also fixed by `npm run lint:fix`.
Fixes #25826.
=> fix(linter): fix property order issues in browser files

api/AmbientLightSensor.json
Fixes #25832 
More info:
https://developer.chrome.com/docs/capabilities/web-apis/generic-sensor
=> Chrome 67 enables AmbientLightSensor via `#enable-generic-sensor-extra-classes`

css/properties/font-variant-emoji.json
This PR tries to fix the strange behavior of the compatibility table, which shows that Chrome Android supports this CSS property, but does not support any value of the property (which makes no sense).
The same error happens with WebView Android and Opera Android, but in this case, I have no idea how to fix it (this is my first PR on mdn).
**Reference:**
https://chromestatus.com/feature/6566092561973248
=> Chrome Android also supports CSS font-variant-emoji values

api/CookieChangeEvent.json, api/CookieStore.json, api/HTMLElement.json, api/SVGDiscardElement.json, api/ServiceWorkerGlobalScope.json, api/Window.json, css/selectors/open.json, html/global_attributes.json, javascript/builtins/Intl/DurationFormat.json, svg/elements/discard.json
The @openwebdocs [BCD collector project](https://github.com/openwebdocs/mdn-bcd-collector) v10.12.8 found new features shipping in Firefox 136 beta which was released yesterday. Currently, the collector covers about 90% of BCD, so the following list might not be exhaustive. Also, if a feature is in Firefox Nightly only, it is not considered here.
With this PR, BCD considers the following 28 features as shipping in Firefox 136:
- api.CookieChangeEvent
- api.CookieChangeEvent.CookieChangeEvent
- api.CookieChangeEvent.changed
- api.CookieChangeEvent.deleted
- api.CookieStore
- api.CookieStore.change_event
- api.CookieStore.delete
- api.CookieStore.delete.partitioned_option
- api.CookieStore.get
- api.CookieStore.getAll
- api.CookieStore.set
- api.CookieStore.set.partitioned_option
- …
=> Updates for Firefox 136 beta

api/HTMLAnchorElement.json, html/elements/a.json
`hreftranslate` is not part of the HTML spec and has been stuck that way for half a decade.
https://github.com/whatwg/html/pull/3870 was last (meaningfully) updated over 5 years ago; this shows no signs of being imminently (or ever) becoming part of the spec.
Discovered in the course of https://github.com/web-platform-dx/web-features/pull/2616.
=> Mark `<a hreftranslate>` as non-standard

api/Permissions.json
This updates the status for `api.Permissions.permission_accessibility-events` and shows its removal from Chrome.
Thanks to help from @dontcallmedom in the WebDX chat, I learned that this permission was part of a now-deprecated [Accessibility Object Model (AOM) Phase 2 specification](https://wicg.github.io/aom/spec/phase2.html#privacy-concerns). This is no longer the case; see the [contemporary AOM spec](https://wicg.github.io/aom/spec) and [its phase 2 specification](https://wicg.github.io/aom/spec/input-events.html#privacy) for comparison. 
Because the originating spec is not in good standing, I wasn't able to add it to `spec_url`. I've still marked this feature as deprecated and non-standard track. The linter obliges us to set it to non-experimental, too.
Thanks to @caugner in …
=> Update `api.Permissions.permission_accessibility-events` status and Chrome 131 removal

api/HTMLElement.json, html/global_attributes.json
Chrome 133 supports the `popover` attribute `hint` value, which creates popovers that do not light-dismiss `auto` popovers when shown. This is useful for situations where, for example, you have toolbar buttons that can be pressed to show UI popovers, but you also want to reveal tooltips when the buttons are hovered, without dismissing the UI popovers.
This PR adds data points for the HTML `popover` attribute `hint` value and the `hint` value of the `HTMLElement.popover` DOM API equivalent.
See https://chromestatus.com/feature/5073251081912320 for the data source.
=> Chrome 133 supports HTML `popover="hint"` attribute value

api/SpeechRecognition.json
The `continuous` property of `SpeechRecognition` can be set on Chrome Android, but it has no effect.
See:
- https://github.com/mdn/browser-compat-data/issues/25794#issuecomment-2619493257
- https://issues.chromium.org/issues/41297427
Fixes https://github.com/mdn/browser-compat-data/issues/25794#issuecomment-2642818996.
=> Chrome Android doesn't support SpeechRecognition.continuous

api/SharedStorageWorkletGlobalScope.json
Chrome 134 supports SharedStorageWorkletGlobalScope.interestGroup. (The collector doesn't support these worklets yet.)
https://chromestatus.com/feature/5074536530444288
https://github.com/mdn/browser-compat-data/pull/25866#issuecomment-2640832400
=> Chrome 134 adds SharedStorageWorkletGlobalScope.interestGroups

api/PerformanceResourceTiming.json
This reverts most of #25733 
The aim of that PR (as well as adding `finalResponseHeadersStart`) was to try to explain that Chrome diverged in it's definition of `responseStart` for sites using Early Hints. However, in hindsight, I think the updates are causing more confusion than help.
MDN currently shows this:
This suggests the header was only added in 133 (it wasn't it was supported since 85 with a slight change in definition for some sites).
It also suggests it's not supported yet in Opera, Opera Android, and Samsung internet when that's not the case.
All in all, I think my intent to help developers has caused more issues than it solved, and we should instead treat this as a small oddity in Chrome 115-132 that doesn't require documenting in BCD (like some bugs aren't unless major …
=> Revert ResponseStart updates

api/SpeechRecognition.json
The `continuous` property of `SpeechRecognition` can be set on Chrome Android, but it has no effect.
(Missed a local change in the previous PR.)
Fixup for:
- https://github.com/mdn/browser-compat-data/pull/25878
=> Chrome Android doesn't really partially support SpeechRecognition.continuous

api/Permissions.json, html/elements/iframe.json
The rest of Magnetometer API is behind a flag in Chromium; these features would have no effect without the flag turned on.
via @foolip in https://github.com/web-platform-dx/web-features/issues/2631
> In Chromium the features is controlled by a flag which is off by default: https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/platform/runtime_enabled_features.json5;l=3940-3943;drc=bdbfc851687b28b24b80bccbc4c027bfe05a701b
I didn't check the version numbers—I figured it doesn't matter that much, but plausible that these things appeared after the initial `Magnetometer` API.
- https://github.com/web-platform-dx/web-features/pull/2614/
=> Magnetometer: entire API is behind a flag in Chromium

http/headers/Permissions-Policy.json
I missed a key in https://github.com/mdn/browser-compat-data/pull/25897. This fixes the omission.
As before:
> In Chromium the features is controlled by a flag which is off by default: https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/platform/runtime_enabled_features.json5;l=3940-3943;drc=bdbfc851687b28b24b80bccbc4c027bfe05a701b
- Previously: https://github.com/mdn/browser-compat-data/pull/25897
- Previously: https://github.com/web-platform-dx/web-features/pull/2614
- Discovered in: https://github.com/web-platform-dx/web-features/pull/2639
=> Magnetometer: entire API is behind a flag in Chromium (again)

package-lock.json, package.json, scripts/update-browser-releases/index.ts, scripts/update-browser-releases/opera.ts, scripts/update-browser-releases/utils.ts
Adds an Opera release update script based on these RSS feeds:
1. https://blogs.opera.com/desktop/category/stable-2/feed/ (for Desktop)
2. https://forums.opera.com/category/20.rss (for Mobile)
Ran `npm run update-browser-releases -- --opera` on this branch (which intentionally doesn't include 12cf843e27d9439f0b024062fce93b0718c2df06):
- ✅ It updated the Opera release.
- :x: Currently, it doesn't update the Opera Android release, because the [corresponding announcement post](https://forums.opera.com/topic/75836/opera-for-android-87) has an additional comment, which is returned in the RSS feed **instead** of the original post (but it worked 1h ago, probably due to caching).
=> enhance(scripts/update-browser-releases): update Opera releases

api/CookieChangeEvent.json, api/CookieStore.json
[`CookieStore`](https://developer.mozilla.org/en-US/docs/Web/API/CookieStore) provides methods to get and set cookie properties in an [`options`](https://developer.mozilla.org/en-US/docs/Web/API/CookieStore/set#options) object with values like `name`, `value`, `domain`, `partitioned`, `path` and so on.
Chrome supports all of the options on release of the methods, except `partitioned`, which came later, and which hence has a subfeature.
Firefox 134 adds support for this API. The setter supports all the properties from release. BUT the getters only supports `name` and `value`.
To report this I have added subfeatures for all the properties in `get()` and `getAll()` 
- Chrome sets all of the new values to the release
- Firefox sets `name` and `value` to the release version for the method, and …
=> CookieStore.get()/getAll() don't return all types in FF

http/headers/Refresh.json
FF136 adds support for sending the HTTP `Referer` header (if permitted by the referrer policy) on page refresh caused by `Refresh` header or equivalent `<meta>` in https://bugzilla.mozilla.org/show_bug.cgi?id=1928291#c9
This matches spec, and also chrome and Safari behaviour. It matters because some sites rely on it - specifically Twitch.
I have chosen to add as a note to the `Refresh`, because that is where the behaviour that is relied upon is changed (i.e. where you might look). It could be a subfeature.. But I think it this is the right place.
Happy to change that if you have another opinion.
Related docs work tracked in https://github.com/mdn/content/issues/37944
=> FF136 HTTP Referer sent on page refresh

javascript/builtins/Error.json
`Error.captureStackTrace()` and `Error.stackTraceLimit` are defacto standard method/property, along with Error.stack. They are not yet standardized, but are planned to be. 
This adds subfeatures for each of them.
Should we add a spec link for Error.stack to https://github.com/tc39/proposal-error-stacks ?
Related docs work can be tracked in https://github.com/mdn/content/issues/37930
=> Ff136 Error.captureStackTrace() and Error.stackTraceLimit

api/Document.json, api/Element.json, api/HTMLElement.json, api/HTMLScriptElement.json, api/Node.json, api/ShadowRoot.json, api/_globals/setInterval.json, api/_globals/setTimeout.json, api/_globals/trustedTypes.json
FF has added more support for trusted types behind a flag. This adds those updates.
Also it adds some missing entries, primarily for the methods and properties that will now _accept_ trusted types. Some of this is a bit weird so I've added comments inline explaining how/why I did stuff.
- FF135 The `Document.write()` and `writeln()` accept {{domxref("TrustedHTML")}} objects as parameters, in addition to strings. https://bugzilla.mozilla.org/show_bug.cgi?id=1906301 - I tested version support for Chrome using https://wpt.live/trusted-types/Document-write.html
- The `HTMLScriptElement.text`, `innerText`, and `textContent`  properties now accept `TrustedScript` as a setter,  while `HTMLScriptElement.src` accepts `TrustedScriptURL` in https://bugzilla.mozilla.org/show_bug.cgi?id=1905706
- …
=> Trusted Types - FF updates and missing entries in TT spec

api/HTMLButtonElement.json, api/HTMLElement.json, api/HTMLInputElement.json, html/elements/button.json, html/elements/input.json
Chrome 133 adds support for:
- The `source` option of the `HTMLElement.showPopover()` and `HTMLElement.togglePopover()` methods, which allow you to programmatically set the invoker (e.g. a button) of the popover the methods are being called on.
- New behavior whereby when you create an association between a popover and an invoker (using the above methods, or `popovertarget`/`popoverTargetElement`), an implicit anchor reference is created between the two, so they can be positioned via CSS anchor positioning.
This PR adds data points for the above.
- ChromeStatus entry: https://chromestatus.com/feature/5120638407409664
- Spec PR: https://github.com/whatwg/html/pull/10728
- MDN issue: https://github.com/mdn/mdn/issues/598
- Associated MDN documentation: …
=> Chromium 133 support for source property and implicit anchor references

api/_globals/fetch.json
fetchPriority was enabled in FF 132, but this option on the fetch global was missed
https://bugzilla.mozilla.org/show_bug.cgi?id=1854077
Other APIs were updated in https://github.com/mdn/browser-compat-data/pull/24518, including RequestInit which Fetch uses
=> Update init.priority in fetch global for Firefox 132

lint/linter/test-versions.ts, lint/utils.ts
This PR shifts the range cutoff date from two years to three years, as we are able to do so.  In the process, this PR also performs some slight refactoring to move the related variable from another file (since it's not used anywhere else), as well as updating the message to improve the date displayed and make future updating easier.
=> Shift the range cutoff to three years back

api/PublicKeyCredential.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `PublicKeyCredential` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.10).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/PublicKeyCredential
=> Chrome Android also supports PublicKeyCredential API, but WebView Android doesn't

css/at-rules/container.json
Chrome 133 supports scroll-state container queries. See https://chromestatus.com/feature/5072263730167808.
A data point for the `container-type` property `scroll-state` value has already been added previously.
This PR adds data for `@container` at-rule support for scroll-state queries. I've added a separate sub-data point for the `scrollable`, `snapped`, and `stuck` features. Even though they are all implemented in Chrome at the same time, I think it is a good reminder of the available subfeatures, and other browsers could easily implement them at different rates.
I used the following demos to test the different types of scroll-state container query:
- `scrollable`: https://scroll-state-scrollable-container-query.glitch.me/ (when the document is scrolled downwards (so it able to be …
=> Chrome 133 supports scroll-state container queries

http/headers/Clear-Site-Data.json
FF136 supports [`Clear-Site-Data: cache`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Clear-Site-Data#cache) in nightly in https://bugzilla.mozilla.org/show_bug.cgi?id=1942272 (and also clearing of cache in the `*` wildcard).
This adds preview feature to the `cache` subfeature. No need to update the `*` wildcard - the expectation is that will clear everything based on the other features that are supported.
Related docs work can be tracked in https://github.com/mdn/content/issues/37946
=> Firefox Nightly supports `Clear-Site-Data: cache`

api/PublicKeyCredential.json, css/properties/hyphenate-limit-chars.json
- added bcd for hyphenate-limit-chars for firefox
- tested in FF Nightly
- tested in FF Developer edition
- tested in FF Beta
- [Firefox release PR](https://github.com/mdn/content/pull/38212)
=> Firefox 136 supports `hyphenate-limit-chars` CSS property behind pref

api/HTMLDialogElement.json
Add Safari Tech Preview support for dialog.requestClose()
Not in release notes but it's in Safari TP 213 see the commit range at https://webkit.org/blog/16461/release-notes-for-safari-technology-preview-213/
https://commits.webkit.org/289352@main
I also tested manually by running the relevant WPTs in STP 213.
=> Mark Safari Tech Preview as supporting dialog.requestClose()

css/properties/backdrop-filter.json
Adds note about Firefox 103 to 122 not supporting `backdrop-filter` on systems with unknown GPU vendor.
See: https://bugzilla.mozilla.org/show_bug.cgi?id=1868737#c12
Fixes https://github.com/mdn/browser-compat-data/issues/19052.
=> Firefox 103-122 didn't support `backdrop-filter` with some GPUs

css/properties/max-height.json
Chrome 1 already supported `max-height`
See evidence in [this comment](https://github.com/mdn/browser-compat-data/issues/19302#issuecomment-2666514782).
Fixes https://github.com/mdn/browser-compat-data/issues/19302.
=> Chrome 1 already supported `max-height`

webextensions/api/menus.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `OnClickData.srcUrl` member of the `menus` Web Extensions interface. The data comes from a commit in the browser's source code, mapped to a version number using available tooling or via the commit timestamp.
Commit: https://source.chromium.org/chromium/chromium/src/+/641efff1566c569f02d395f872d4c4f5c965d217
Additional Notes: This commit does not seem to add the feature itself, but it provides evidence that the feature was around during that time.
=> Update Chromium data for `webextensions.api.menus` (esp. `OnClickData.srcUrl`)

docs/publishing.md
Documents the new-ish release process using the automated release PR.
Relevant PRs:
- https://github.com/mdn/browser-compat-data/pull/24805
- https://github.com/mdn/browser-compat-data/pull/24914
- https://github.com/mdn/browser-compat-data/pull/24935
- https://github.com/mdn/browser-compat-data/pull/24950
- https://github.com/mdn/browser-compat-data/pull/25052
- https://github.com/mdn/browser-compat-data/pull/25100
- https://github.com/mdn/browser-compat-data/pull/25102
- https://github.com/mdn/browser-compat-data/pull/25114
- https://github.com/mdn/browser-compat-data/pull/25176
- https://github.com/mdn/browser-compat-data/pull/25661
Fixes https://github.com/mdn/browser-compat-data/issues/25145.
=> docs: new release process

api/CSSNestedDeclarations.json
This PR updates and corrects version values for Firefox Android for the `CSSNestedDeclarations` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.10).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/CSSNestedDeclarations
=> Update Firefox Android data for CSSNestedDeclarations API

api/FileSystemObserver.json
This PR updates and corrects version values for Chrome Android for the `FileSystemObserver` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.10).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/FileSystemObserver
=> Update Chrome Android data for FileSystemObserver API

javascript/statements.json
Spec PR: https://github.com/tc39/ecma262/pull/2154
- V8 in 8.8.152 (https://github.com/v8/v8/commit/81d168d0125a7ba2e94bf69df9cecf3e99290572)
- Chrome 88
- Deno 1.6 (https://github.com/denoland/deno/commit/cf7949db2feced61dfb4a7bc2a56ee72515394a3)
- Node.js 16 (https://github.com/nodejs/node/pull/36139)
- WebKit 611.1.10 (https://github.com/WebKit/WebKit/commit/e7c8ad2d221d97666c5a0fddcd85c466ae60d5ed)
- Chromium: https://issues.chromium.org/issues/42200949
- Firefox 87: https://bugzilla.mozilla.org/show_bug.cgi?id=1670044#c1
- Safari: https://bugs.webkit.org/show_bug.cgi?id=217576
Fixes #18152.
=> Add arbitrary module namespace identfier names

api/GeolocationCoordinates.json
This PR updates and corrects version values for Samsung Internet for the `GeolocationCoordinates` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.10).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/GeolocationCoordinates
=> Update Samsung Internet / WebView Android data for GeolocationCoordinates API

api/MediaSource.json
This PR updates and corrects version values for Safari iOS/iPadOS for the `MediaSource` API. This propogates the note to the newly-supported features, as well as corrects the data for WebView iOS (which was collected with the collector using only an iPhone).
=> MediaSource API is not available in Safari iOS on iPhone

api/FileSystemObserver.json
The `FileSystemObserver` interface has been implemented in Chromium 133+ (desktop-only) and is already included in the BCD. However, it is not yet merged into the File System standard (see https://github.com/whatwg/fs/pull/165), so I'm setting it to `standard_track: false` for now in this PR, to avoid confusion. I'll set it back again when it is merged.
=> FileSystemObserver is not yet part of File System standard

webextensions/api/commands.json
Addresses the dev-docs needed request for [Bug 1538451](https://bugzilla.mozilla.org/show_bug.cgi?id=1538451) _Make extension shortcut management page accessible by a link/URL for a WebExtension_ by adding `commands.openShortcutSettings`.
Related MDN documentation changes in https://github.com/mdn/content/pull/38234
=> Bug-1538451 add `commands.openShortcutSettings`

api/HTMLElement.json
This PR updates and corrects version values for WebView iOS/iPadOS for the `autocorrect` member of the `HTMLElement` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.10).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/HTMLElement/autocorrect
=> WebView iOS also supports api.HTMLElement.autocorrect

api/OffscreenCanvas.json
This PR updates and corrects version values for WebView Android for the `OffscreenCanvas` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.10).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/OffscreenCanvas
=> WebView Android also supports OffscreenCanvas API

api/VideoColorSpace.json
This PR updates and corrects version values for Firefox Android for the `VideoColorSpace` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.10).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/VideoColorSpace
=> Firefox Android also supports VideoColorSpace API

javascript/grammar.json, javascript/operators/import.json
The options argument for `import()` is just as standardized as the rest of import attributes.
https://tc39.es/ecma262/multipage/ecmascript-language-expressions.html#sec-import-call-runtime-semantics-evaluation
- Discovered via https://github.com/web-platform-dx/web-features/pull/2564
=> `import(…, { with: { type: "json" } })` is standard track

api/VideoFrame.json
This PR updates and corrects version values for Firefox Android for the `VideoFrame` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.10).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/VideoFrame
=> Firefox Android also supports VideoFrame API

css/properties/column-width.json
This PR updates and corrects version values for WebView iOS/iPadOS for the `auto` member of the `column-width` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.10).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/column-width/auto
=> WebView iOS also supports `column-width: auto`

css/properties/border-collapse.json
This PR updates and corrects version values for WebView iOS/iPadOS for the `border-collapse` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.10).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/border-collapse
=> WebView iOS also supports border-collapse CSS property

css/properties/mask-border-outset.json, css/properties/mask-border-repeat.json, css/properties/mask-border-slice.json, css/properties/mask-border-source.json, css/properties/mask-border-width.json, css/properties/mask-border.json
This PR updates and corrects version values for Safari iOS/iPadOS for the `mask-border` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.10).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/mask-border
=> Safari iOS data also supports unprefixed mask-border CSS property

css/properties/mask-clip.json
This PR updates and corrects version values for WebView Android for the `mask-clip` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.10).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/mask-clip
=> WebView Android 120 also supports unprefixed mask-clip CSS property

css/properties/mask-image.json
This PR updates and corrects version values for Chrome Android for the `mask-image` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.10).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/mask-image
=> Opera Android / Samsung Internet / WebView Android also support unprefixed mask-image CSS property

css/properties/mask-origin.json
This PR updates and corrects version values for WebView Android for the `mask-origin` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.10).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/mask-origin
=> WebView Android also supports unprefixed mask-origin CSS property

css/properties/mask-position.json
This PR updates and corrects version values for WebView Android for the `mask-position` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.10).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/mask-position
=> WebView Android also supports unprefixed mask-position CSS property

css/properties/mask-repeat.json
This PR updates and corrects version values for WebView Android for the `mask-repeat` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.10).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/mask-repeat
=> WebView Android also supports unprefixed mask-repeat CSS property

webextensions/api/userScripts_legacy.json, webextensions/manifest/user_scripts.json
Initial PR for addressing the compatibility data needs of [Bug 1943050](https://bugzilla.mozilla.org/show_bug.cgi?id=1943050) Enable userScripts API by default. This PR creates the compatibility data to complement the documentation changes in https://github.com/mdn/content/pull/37975:
- addition of a userScripts_legacy.json file (being a copy of the original userScripts.json with a note about the legacy version availability in Manifest V2 only)
- update to user_scripts.json to note its applicability to Manifest V2 only.
=> Data for legacy version of webextension.api.userScripts

css/properties/min-width.json
This PR updates and corrects version values for Samsung Internet for the `fit-content` member of the `min-width` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.10).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/min-width/fit-content
=> Samsung Internet also supports unprefixed `min-width: fit-content`

css/properties/mix-blend-mode.json
This PR updates and corrects version values for Opera and Opera Android for the `plus-lighter` member of the `mix-blend-mode` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.10).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/mix-blend-mode/plus-lighter
=> Opera also supports CSS `mix-blend-mode: plus-lighter`

css/properties/text-align.json
This PR updates and corrects version values for WebView Android for the `text-align` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.10).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/text-align
=> WebView Android also supports unprefixed text-align CSS property values

css/selectors/-webkit-inner-spin-button.json
This PR updates and corrects version values for WebView iOS/iPadOS for the `-webkit-inner-spin-button` CSS selector. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.10).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/selectors/-webkit-inner-spin-button
=> WebView iOS also supports `-webkit-inner-spin-button` CSS selector

css/selectors/-webkit-meter-bar.json, css/selectors/-webkit-meter-even-less-good-value.json, css/selectors/-webkit-meter-inner-element.json, css/selectors/-webkit-meter-optimum-value.json, css/selectors/-webkit-meter-suboptimum-value.json, css/selectors/-webkit-progress-bar.json, css/selectors/-webkit-progress-inner-element.json, css/selectors/-webkit-progress-value.json, css/selectors/-webkit-search-cancel-button.json
This PR updates and corrects version values for WebView iOS/iPadOS for the `-webkit-*` CSS selector. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.10).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/selectors/-webkit-*
=> WebView iOS also supports several `-webkit-*` CSS selectors

css/selectors/-webkit-slider-runnable-track.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `-webkit-slider-runnable-track` CSS selector. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.10).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/selectors/-webkit-slider-runnable-track
=> Safari 18 supports `-webkit-slider-runnable-track` CSS selector

css/selectors/-webkit-slider-thumb.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `-webkit-slider-thumb` CSS selector. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.10).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/selectors/-webkit-slider-thumb
=> Safari also supports `-webkit-slider-thumb` CSS selector

html/elements/ul.json
This PR updates and corrects version values for WebView iOS/iPadOS for the `compact` member of the `ul` HTML element. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.10).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/html/elements/ul/compact
=> WebView iOS also supports HTML ul compact attribute

javascript/builtins/Error.json
`javascript.builtins.Error.cause.displayed_in_console` can never be incompatible because the contents of the console aren't inspectable.
This is a weird thing. The appearance of the console is [implementation-defined](https://infra.spec.whatwg.org/#implementation-defined) by specification. Arguably, the console _output_ can look however a vendor wants it to look and it'd be standard behavior.
But unlike, say, the default stylesheet or a sensitive feature's permissions UI, the output of the console is not inspectable by a web page in any browser in any case. That is to say, there are no methods to _read_ the console, only to write to it. You could never build a web application that depends on the output of the console. It's definitionally compatible because no browser exposes it to …
=> Remove `javascript.builtins.Error.cause.displayed_in_console`

css/at-rules/font-face.json, css/properties/font-stretch.json, css/properties/font.json, svg/global_attributes.json
The spec calls this a "legacy" alias, so I took this to mean it's now deprecated.
https://drafts.csswg.org/css-fonts-4/#font-stretch-prop
It feels a little weird to mark this up, given the strong support for the old name. But given our guidelines, that's how this ought to be.
I didn't make the change for the SVG attribute or `css.properties.font.font_stretch_support`, since I was less clear on how to handle those based on the spec. Guidance or suggestions welcome.
See the corresponding change in web-features: https://github.com/web-platform-dx/web-features/pull/2707.
=> Mark `font-stretch` as deprecated

webextensions/api/storage.json
Corrects a Firefox bug number in the notes about `StorageArea.getBytesInUse()` support.
:x: Wrong bug: 138583
> Profile cannot be found if Drive was mounted after starting Mozilla
✅ Correct bug: 1385832
> getBytesInUse() is not supported in `local` and `managed` storage areas
Fixes https://github.com/mdn/browser-compat-data/issues/26010.
=> Fix typo in Firefox notes about `StorageArea.getBytesInUse()`

api/MouseEvent.json
Before, these properties were not exposed.
Safari iOS only exposed `MouseEvent.movement{X,Y}` from version 17.
See:
- https://bugs.webkit.org/show_bug.cgi?id=255207
- https://github.com/mdn/browser-compat-data/issues/19339#issuecomment-1772432594
The v17 change log mentions:
> Fixed missing movementX and movementY in pointermove events. (108112600)
Fixes https://github.com/mdn/browser-compat-data/issues/19339.
=> Safari iOS 17 supports MouseEvent.movement{X,Y}

api/Window.json
Safari iOS doesn't support the `beforeunload` event.
Evidence is in https://github.com/mdn/browser-compat-data/issues/24394.
Fixes https://github.com/mdn/browser-compat-data/issues/24394.
=> Safari iOS lacks support for beforeunload event

css/properties/transform-style.json
Safari 17 fixed a bug with pseudo elements in the 3D rendering context
- BCD issue: https://github.com/mdn/browser-compat-data/issues/19472
- WebKit bug: https://bugs.webkit.org/show_bug.cgi?id=256430
Fixes https://github.com/mdn/browser-compat-data/issues/19472.
=> Safari 17 fixed a bug with pseudo elements in the 3D rendering context

scripts/tag-web-features.ts
Improves the `tag-web-features` script output by printing a patch code block, instead of structured prose.
The PRs (like [this one](https://github.com/mdn/browser-compat-data/pull/26047)) are cumbersome to review manually.
Compare [the OP](https://github.com/mdn/browser-compat-data/pull/26047#issue-2876922444) with [this comment](https://github.com/mdn/browser-compat-data/pull/26047#issuecomment-2681876654) (created via this branch).
=> enhance(scripts/tag-web-features): print changes as patch code block

api/CanvasRenderingContext2D.json, api/OffscreenCanvasRenderingContext2D.json
The font-weight can be set on the `font` property, but it doesn't reflect back.
- WebKit bug: https://github.com/mdn/browser-compat-data/issues/19348
- BCD issue: https://bugs.webkit.org/show_bug.cgi?id=288486
Fixes https://github.com/mdn/browser-compat-data/issues/19348.
=> Safari doesn't reflect the font-weight of the Canvas context font

css/types/gradient.json
- Added BCD for single color stop with 0-1 positions for:
- `linear-gradient()`
- `conic-gradient()`
- `radial-gradient()`
- used https://codepen.io/CodeRedDigital/pen/qEBaeav to test, tested in:
- Firefox Beta - passed
- Chrome:
- Beta - failed
- Dev - failed
- Canary - passed
- Edge:
- Beta - failed
- Dev - failed
- Canary - passed
- Safari - failed
- Safari TP - passed
- Samsung internet - failed
- [Allow gradients with a single color stop and 0-1 positions](https://github.com/mdn/content/issues/37937)
- [Content PR](https://github.com/mdn/content/pull/38343)
- [Firefox Release PR](https://github.com/mdn/content/pull/38342)
=> Firefox 136 & Chrome/Safari Preview support gradients with single color stop and 0-1 positions

api/SVGDiscardElement.json, svg/elements/discard.json
SVG `<discard>` element is present in FF136, but behind a nightly-enabled pref `svg.discard.enabled` - see https://bugzilla.mozilla.org/show_bug.cgi?id=1069931. Ditto corresponding API `SVGDiscardElement`
This modifies the feature to preview.
Related docs work can be tracked in https://github.com/mdn/content/issues/37939
=> FF137 SVG <discard> element

api/CredentialsContainer.json, css/properties/display.json, css/properties/ruby-position.json, css/properties/white-space-collapse.json, html/elements/col.json, html/elements/colgroup.json, html/elements/del.json, html/elements/fieldset.json, html/elements/iframe.json, html/elements/ins.json, html/elements/link.json, html/elements/meta.json, html/elements/ol.json, html/elements/pre.json, html/elements/video.json, html/global_attributes.json
This PR adds the missing WebView iOS statements throughout BCD and sets them to mirror.
=> Add mirroring statements for all missing WebView iOS statements

api/ImageData.json
This PR adds the missing `ImageData.settings_parameter` member of the `ImageData` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.10).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/ImageData/ImageData/settings_parameter
=> Add missing api.ImageData.ImageData.settings_parameter feature

api/Window.json
This PR adds the missing `postMessage.options_delegate_parameter` member of the `Window` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.10).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/Window/postMessage/options_delegate_parameter
=> Add missing api.Window.postMessage.options_delegate_parameter feature

api/AudioParam.json
This PR updates and corrects version values for Firefox and Firefox Android for the `AudioParam` API. This fixes #25748, which contains the supporting evidence for this change.
=> Firefox 134 supports `AudioParam.{exponential,linear}RampToValueAtTime`

css/types/color.json
This PR updates and corrects version values for WebView iOS/iPadOS for the `color-mix` member of the `color` CSS value type. This fixes #25451, which contains the supporting evidence for this change.
Additional Notes: The collector has a typo which is causing the test to not pass.  This will be fixed.
=> WebView iOS also supports css.types.color.color-mix

html/global_attributes.json
Adds subfeature `ignores_find_in_page` to `html.global_attributes.inert`, duplicated from `api.HTMLElement.inert`.
Fixes #25983.
=> Add `ignores_find_in_page` to `inert` global attribute

api/CanvasRenderingContext2D.json, api/OffscreenCanvasRenderingContext2D.json
Add BCD info for the newly added HTML CanvasRenderingContext2D lang attribute (and also OffscreenCanvasRenderingContext2D).
Spec PR: https://github.com/whatwg/html/pull/10873
Chrome Intent: https://chromestatus.com/feature/5066778773028864
WPT Tests:
* https://wpt.fyi/results/html/canvas/element/manual/text?label=master&label=experimental
* canvas.2d.lang.dynamic.html
* canvas.2d.lang.empty.canvas.tentative.html
* canvas.2d.lang.inherit.canvas.tentative.html
* canvas.2d.lang.inherit.disconnected.canvas.tentative.html
* canvas.2d.lang.inherit.document.disconnected.canvas.tentative.html
* canvas.2d.lang.inherit.document.tentative.html
* canvas.2d.lang.tentative.html
* https://wpt.fyi/results/html/canvas/offscreen/manual/text?label=master&label=experimental
* …
=> Info for the new HTML CanvasRenderingContext2D lang attribute

api/HTMLElement.json
Also mark Chrome support as partial due to missing focus behavior
Mark Safari Tech Preview as partially supporting source option for popover API
Also mark Chrome support as partial due to missing focus behavior
Manually tested STP support by running https://wpt.live/html/semantics/popovers/imperative-invokers.html
=> Chrome/Safari only partially support source option for popover API

javascript/builtins/Intl/Locale.json
This PR updates and corrects version values for Deno for the `Locale.getWeekInfo` member of the `Intl` JavaScript builtin. The data comes from manual testing, running test code through BrowserStack, SauceLabs, custom VMs and/or locally.
Test Code:
```
const he = new Intl.Locale("he"); he.getWeekInfo();
```
Additional Notes: This fixes #24459, fixes #22134.
=> Deno 2.1 supports javascript.builtins.Intl.Locale.getWeekInfo

api/Document.json, api/Element.json
FF137 is adding deprecation warnings for [`Document.afterscriptexecute` event](https://developer.mozilla.org/en-US/docs/Web/API/Document/afterscriptexecute_event), [`Document.beforescriptexecute` event](https://developer.mozilla.org/en-US/docs/Web/API/Document/beforescriptexecute_event), [`Element.afterscriptexecute` event](https://developer.mozilla.org/en-US/docs/Web/API/Element/afterscriptexecute_event), and [`Element.beforescriptexecute` event](https://developer.mozilla.org/en-US/docs/Web/API/Element/beforescriptexecute_event), in https://bugzilla.mozilla.org/show_bug.cgi?id=1949373
This is part of a usage test, on the way to unimplementation in https://bugzilla.mozilla.org/show_bug.cgi?id=1584269
This PR just marks the APIs as deprecated.
=> Firefox 137 deprecates afterscriptexecute and beforescriptexecute events

api/MouseEvent.json
Fixes a mistake in https://github.com/mdn/browser-compat-data/pull/26053, which accidentally updated `MouseEvent.clientX` instead of `MouseEvent.movementX`.
Reverts the `clientX` changes, and applies them to `movementX` instead.
Fixes https://github.com/mdn/browser-compat-data/issues/26103.
=> Fix Safari iOS data for MouseEvent.{client,movement}X

javascript/builtins/Array.json, javascript/builtins/Object.json, javascript/builtins/String.json
This PR updates JavaScript builtins support version of Webview Android. Most changes are changing `≤37` or `mirror` to `≤4`.
I wrote a simple tool to determine if the value is `undefined` to check if the browser supports this feature (only implemented 3 checks so far). Which is available at [SessionHu/check-js-feat](https://github.com/SessionHu/check-js-feat).
Then I run the server on my another device and open the page on the old Android 4.2 TV with an browser which using Android System Webview.
Here is the result photo (UserAgent on the top, support features in green background, unsupport in red. And I cannot take screenshot on that device):
<details><summary>here 3 photos shot on phone camera</summary>
</details>
Although the system version is `4.2.1` instead of `4` according to the …
=> Update Webview Android data for JS builtins

scripts/update-browser-releases/index.ts, scripts/update-browser-releases/opera.ts
Updates all browsers in parallel (using `Promise.all()`), and separates the update outputs by two new lines, separating them in paragraphs, so that the `[!NOTE]` blocks (returned by the Opera updater) are properly displayed.
See https://github.com/mdn/browser-compat-data/pull/26120.
=> enhance(scripts/update-browser-releases): update in parallel + separate sections

.github/workflows/pr-reviewdog.yml
Run `npm run fix` on the PR head, not on main.
This explains two things:
1. Since introducing reviewdog in BCD, it didn't actually comment on any PR, even when it was expected.
2. Today, it posted unrelated review comments like [this one](https://github.com/mdn/browser-compat-data/pull/26135#discussion_r1983666659), suggesting to add an `mdn_url` where the PR already included it.
=> fix(workflows/pr-reviewdog): run fix on PR head, not main

api/MLOperand.json
This PR removes the `MLNumber` member of the `MLOperand` API from BCD. This feature is a type (ex. a dictionary, enum, mixin, constant or WebIDL typedef) that we have explicitly stated not to document separately from the feature(s) that depend on it, as they are virtually invisible to the end developer.
=> Remove api.MLOperand.MLNumber from BCD

api/SpeechGrammar.json
This PR updates and corrects the metadata (spec URLs, descriptions, statuses, etc.) for the `SpeechGrammar` API.
Additional Notes: Removed from spec in https://github.com/WebAudio/web-speech-api/pull/117.
=> Update metadata for SpeechGrammar API

api/HTMLDialogElement.json
Mark dialog.requestClose() as supported in Safari 18.4
Unmark as experimental now it has 2 implementations.
https://developer.apple.com/documentation/safari-release-notes/safari-18_4-release-notes#:~:text=for%20dialog.-,requestClose,-().%20(143388390)
=> Mark dialog.requestClose() as supported in Safari 18.4

scripts/update-browser-releases/chrome.ts, scripts/update-browser-releases/opera.ts, scripts/update-browser-releases/utils.ts
Prevents the `update-browser-releases` script from advancing the Chrome Stable release before it's actually released.
(A few days before the Chrome Stable release, Chrome Status already returns it as the stable release.)
See: https://github.com/mdn/browser-compat-data/commit/fb16a4c36926ab1ec4b6aa6e284740a53ccf3851
=> fix(scripts/update-browser-releases): avoid unreleased Chrome Stable

api/HTMLElement.json
Adds `api.HTMLElement.load_event`.
Copied from `api.Window.load_event`.
Fixes https://github.com/mdn/browser-compat-data/issues/19595.
=> Add load_event on HTMLElement

api/Element.json, api/ElementInternals.json
According to https://bugzilla.mozilla.org/show_bug.cgi?id=1919102#c9 and other posts the aria reflected elements that appeared in the 137 release note were either added or pushed back into 136. This changes the items that were updated in #26118:
api.Element.ariaActiveDescendantElement
api.Element.ariaControlsElements
api.Element.ariaDescribedByElements
api.Element.ariaDetailsElements
api.Element.ariaErrorMessageElements
api.Element.ariaFlowToElements
api.Element.ariaLabelledByElements
api.Element.ariaOwnsElements
api.ElementInternals.ariaActiveDescendantElement
api.ElementInternals.ariaControlsElements
api.ElementInternals.ariaDescribedByElements
api.ElementInternals.ariaDetailsElements
api.ElementInternals.ariaErrorMessageElements
api.ElementInternals.ariaFlowToElements …
=> Firefox 136 already supports ARIA Attribute Reflection

api/GPUSupportedFeatures.json
Chrome 132 supports the `float32-blendable` WebGPU feature — see https://chromestatus.com/feature/5173655901044736, and see https://developer.chrome.com/blog/new-in-webgpu-132#32-bit_float_textures_blending for more details.
This PR updates the data point for that feature.
=> Chrome 132 support for WebGPU float32-blendable feature

html/manifest/protocol_handlers.json
Updates `protocol_handlers` compat data to reflect reality. It's only supported on Chrome desktop, Edge desktop and desktop derivatives (Opera untested).
I think it's a mistake to mark this API as "mirrored" on `webview_android`, but the pre-commit scripts and `npm test` say it's an error not to do so. It doesn't make sense for this API to ever be supported on Android webview as it relates to installing progressive web apps, which requires a standalone browser. I hope your tooling and `not-webview-exposed.txt` will properly mark this API as not available if it ever does get added to Chrome Android.
I tested the API on the following platforms:
- Chrome desktop – works
- Edge desktop – works
- Firefox desktop – doesn't work
- Chrome Android – doesn't work
- Samsung Internet Android – …
=> Chrome Android doesn't support PWA `protocol_handlers`

css/properties/appearance.json, css/selectors/checkmark.json, css/selectors/picker-icon.json, css/selectors/picker.json, html/elements/selectedcontent.json
Chrome 134 supports customizable `<select>` elements (see https://chromestatus.com/feature/5737365999976448).
This includes a multitude of sub-features; this PR adds data for the new ones we haven't already got data for, which are as follows:
- The `<selectedcontent>` element
- The `::picker()` pseudo-element
- The `::picker-icon` pseudo-element
- The `::checkmark` pseudo-element
- The `appearance` property `base-select` value (which is currently specified as `base`, but I think this might change soon).
<s>I'm setting this as a draft for now because BCD doesn't recognize the [CSS Form Control Styling Level 1](https://drafts.csswg.org/css-forms-1/) as a valid spec. I've filed an issue to ask if I can get it added to `browser-specs`: see https://github.com/w3c/browser-specs/issues/1723</s> …
=> Chrome 134 supports customizable `<select>` element

css/properties/color-interpolation.json
This PR removes the partial implementation flags for the color-interpolation CSS property, for both Chrome and Safari. 
The reason for this is:
1. The property _is_ supported on those browsers.
2. Not all values are supported though, but the supported/unsupported values are already tracked in the same BCD file as sub-features. So there's no need to show the parent feature as partially supported when that information is already tracked elsewhere.
Fixes #26198.
=> Remove color-interpolation partial implementation flag

html/elements/form.json
Firefox 122 supports `webauthn` token in `autocomplete` attr in forms, e.g.,
```html
<input type="text" name="username" autocomplete="username webauthn" ...>
```
- https://bugzilla.mozilla.org/show_bug.cgi?id=1824215
- https://wpt.fyi/results/html/semantics/forms/the-form-element/form-autocomplete.html?label=master&label=stable&product=chrome&product=firefox&product=safari&aligned
- https://wpt.live/html/semantics/forms/the-form-element/form-autocomplete.html
Fixes #26176
=> Firefox 122 supports webauthn value in HTML form autocomplete attr

javascript/builtins/Atomics.json
This wasn't previously detected as shipping in the first Firefox 137 beta, we reported the issue, and now it has been fixed to ship for real: https://bugzilla.mozilla.org/show_bug.cgi?id=1937805#c8
Yay, we're doing QA for web platform features!
=> Firefox 137 ships Atomics.pause

api/SVGPathElement.json
The https://svgwg.org/specs/paths spec wasn't in browser-specs so far but has been added now. As a consequence, I ran the OWD BCD collector again to get features from that spec into BCD. Some ship in the new Firefox 137 beta, some are apparently around cross-browser for longer.
=> Add features from SVG Path spec

javascript/builtins/Date.json, javascript/builtins/Temporal.json, javascript/builtins/Temporal/Duration.json, javascript/builtins/Temporal/Instant.json, javascript/builtins/Temporal/Now.json, javascript/builtins/Temporal/PlainDate.json, javascript/builtins/Temporal/PlainDateTime.json, javascript/builtins/Temporal/PlainMonthDay.json, javascript/builtins/Temporal/PlainTime.json, javascript/builtins/Temporal/PlainYearMonth.json, javascript/builtins/Temporal/ZonedDateTime.json
- Removed Flag for Firefox Nightly and updated the `imp_url` for:
- `Temporal` API
- `Temporal.Duration`
- `Temporal.Instant`
- `Temporal.Now`
- `Temporal.PlainDate`
- `Temporal.PlainDateTime`
- `Temporal.PlainMonthDay`
- `Temporal.PlainTime`
- `Temporal.PlainYearMonth`
- `Temporal.ZonedDateTime`
- `Date.toTemporalInstant`
- Tested in Firefox Nightly with the flag: `javascript.options.experimental.temporal`, using the following test codepens:
- [`Temporal.Duration`](https://codepen.io/CodeRedDigital/pen/jENvKmd)
- [`Temporal.Instant`](https://codepen.io/CodeRedDigital/pen/qEWMKPq)
- [`Temporal.Now`](https://codepen.io/CodeRedDigital/pen/EaYeRQK)
- [`Temporal.PlainDate`](https://codepen.io/CodeRedDigital/pen/RNbYrEK)
- [`Temporal.PlainDateTime`](https://codepen.io/CodeRedDigital/pen/vEBzrQd …
=> Firefox Nightly now supports Temporal by default

api/GPUSupportedFeatures.json
Chrome 134 supports the WebGPU subgroups feature — see https://developer.chrome.com/blog/new-in-webgpu-134#improve_machine-learning_workloads_with_subgroups and https://chromestatus.com/feature/5126409856221184 for full details.
This PR adds a data point for the `subgroups` feature under `GPUSupportedFeatures`.
=> Chrome 134 WebGPU subgroups feature support

webextensions/api/menus.json
Added a note to indicate the availability of `page_action` as a `ContextType` in the `menus` API from Firefox 138 (to address the dev-doc-needed requirement of [Bug 1951166](https://bugzilla.mozilla.org/show_bug.cgi?id=1951166) page_action missing from MV3 menus.json)
Corresponding release note added in https://github.com/mdn/content/pull/38674
=> Bug-1951166 `page_action` support in `menus` API for MV3

webextensions/api/userScripts.json
Update the version added information for Firefox for Android to indicate the availability of the userScripts API in version 138 (to address the dev-doc-needed requirement of [Bug 1949955](https://bugzilla.mozilla.org/show_bug.cgi?id=1949955) Enable userScripts API by default on mobile)
Corresponding release note added in https://github.com/mdn/content/pull/38672
=> Bug 1949955 userScripts API enabled on mobile

api/Document.json, api/Element.json, api/HTMLElement.json, api/HTMLScriptElement.json, api/Node.json, api/ShadowRoot.json, api/TrustedHTML.json, api/TrustedScript.json, api/TrustedScriptURL.json, api/TrustedTypePolicy.json, api/TrustedTypePolicyFactory.json, api/_globals/setInterval.json, api/_globals/setTimeout.json, api/_globals/trustedTypes.json, http/headers/Content-Security-Policy.json
Mark Trusted Types as supported in Safari TP
https://webkit.org/blog/16523/release-notes-for-safari-technology-preview-215/#:~:text=Added%20support%20for%20Trusted%20Types.
=> Safari TP supports Trusted Types

javascript/builtins/Iterator.json
This PR updates and corrects version values for NodeJS for the `from` member of the `Iterator` JavaScript builtin. This fixes #26210, which contains the supporting evidence for this change.
=> NodeJS 22 supports javascript.builtins.Iterator.from

javascript/builtins/Intl/DurationFormat.json
This PR updates and corrects version values for NodeJS for the `DurationFormat` member of the `Intl` JavaScript builtin. This fixes #26249, which contains the supporting evidence for this change.
=> NodeJS 23 supports javascript.builtins.Intl.DurationFormat

lint/linter/test-schema.ts, lint/linter/test-spec-urls.ts
This PR switches our import assertions with import attributes.  Since we have our `.nvmrc` set to NodeJS v20 and require 20+, we are already requiring only NodeJS versions that support import attributes.
=> chore: migrate to import attributes

css/properties/content.json, css/properties/list-style-type.json, css/types/url.json
Changes the description of `css.types.url` from `<url>` (type) to `url()` (function), and links `css.types.url` and `css.properties.content.url` to [Web/CSS/url_function](https://developer.mozilla.org/en-US/docs/Web/CSS/url_function).
Also adds a missing description to `css.properties.list-style-type.symbols`.
Fixes https://github.com/mdn/browser-compat-data/issues/25413.
=> Change `<url>` to `url()` and link to Web/CSS/url_function

css/at-rules/media.json
Add a note about samsung devices incorrectly matching `(hover: hover)`.
fixes #21515
=> On Chrome Android, the `(hover: hover)` media query sometimes matches incorrectly

javascript/builtins/Error.json
Updates the Node.js support statement for Error.captureStackTrace()`.
See https://github.com/mdn/browser-compat-data/issues/26271#issuecomment-2747643056 for the evidence.
Fixes https://github.com/mdn/browser-compat-data/issues/26271.
=> Node.js 0.10.0 already supported `Error.captureStackTrace()`

javascript/builtins/Iterator.json
This PR updates and corrects version values for NodeJS for the `Iterator` JavaScript builtin constructor. This fixes #26210, which contains the supporting evidence for this change (but was closed accidentally when a partial fix was merged).
#26210
Fixes #26210
=> NodeJS 22 supports `Iterator()` constructor

css/selectors/active-view-transition-type.json
...along with other View Transition types features.
=> Safari 18.2 added `:active-view-transition-type()`

javascript/builtins/ArrayBuffer.json
NodeJS 21 supports javascript.builtins.ArrayBuffer.{detached,transfer,transferToFixedLength}
This PR updates and corrects version values for NodeJS for the members `detached`, `transfer`, `transferToFixedLength` of `ArrayBuffer` JavaScript instances. This fixes #26213, which contains the supporting evidence for this change.
#26213
Fixes #26213
=> NodeJS 21 supports transferable ArrayBuffer

lint/fixer/flags.ts, schemas/compat-data.schema.json, scripts/build/mirror.ts, scripts/migrations/002-remove-webview-flags.ts, scripts/traverse.ts
Refines our TypeScript array types to account for `minItems`.
E.g. `string | [string, string, ...string[]]` guarantees that if the value is an array, then the first two values are `string`, rather than `string | undefined`.
> [!IMPORTANT]
> This is a **breaking change**.
=> feat(schemas)!: improve TypeScript definitions for array values

javascript/statements.json
Adds links to import attributes e.g. `with {type: 'css'}`
These bugs are identical to those added in #22881 when the specification was not yet settled
cc @jogibear9988 @captainbrosset
=> Add Firefox/Safari impl_url for import attribute with `{type: 'css'}`

api/CookieChangeEvent.json, api/CookieStore.json, api/ServiceWorkerGlobalScope.json, api/Window.json
Firefox Nightly supports Cookie Store API, i.e. the feature is not enabled in stable.
This partially reverts commit c04c5b51405486a780d78fa1c43b473f5214c6da.
Fixes https://github.com/mdn/browser-compat-data/issues/26301.
=> Firefox Nightly supports Cookie Store API

.github/workflows/issue-regex-labeler.yml
Configures the `github/issue-labeler` action to [include the title in the regex target](https://github.com/github/issue-labeler?tab=readme-ov-file#example-including-the-issue-title-in-the-regex-target).
This should help issues to get labeled correctly.
=> ci(issue-regex-labeler): include title

scripts/release/index.ts, scripts/release/notes.ts
Fixes the following issues related to major releases, observed in https://github.com/mdn/browser-compat-data/commit/3d5d48bb33ff0879ca1883db4eb8392d40bf5c88:
1. The "Older releases" section referred to `vv5` instead of `v5`.
2. The previous release notes (`release_notes/v5.md`) were not included in the release commit.
3. The section was called "Notable changes" instead of "Breaking changes".
See:
- https://github.com/mdn/browser-compat-data/pull/26291
=> fix(scripts/release): improve major release handling

css/properties/d.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `d` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.11).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/d
=> Chrome 52 supports `d` CSS property

css/properties/caption-side.json
This PR updates and corrects version values for all browsers for the `caption-side` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.11).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/caption-side
=> Chrome/Firefox/Safari always supported `caption-side` CSS property

css/properties/cx.json
This PR updates and corrects version values for all browsers for the `cx` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.11).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/cx
=> Chrome 43 / Firefox 69 / Safari 9 added `cx` CSS property

css/properties/cy.json
This PR updates and corrects version values for all browsers for the `cy` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.11).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/cy
=> Chrome 43 / Firefox 69 / Safari 9 added `cy` CSS property

css/properties/overscroll-behavior-y.json
This PR updates and corrects version values for all browsers for the `overscroll-behavior-y` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.11).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/overscroll-behavior-y
=> Update Chrome/Edge data for overscroll-behavior-y CSS property

css/properties/x.json
This PR updates and corrects version values for all browsers for the `x` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.11).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/x
=> Chrome 42 / Firefox 69 / Safari 9 added `x` CSS property

css/properties/y.json
This PR updates and corrects version values for all browsers for the `y` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.11).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/y
=> Chrome 42 / Firefox 69 / Safari 9 added `y` CSS property

css/properties/break-before.json
This PR updates and corrects version values for all browsers for the `break-before` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.11).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/break-before
=> Update Chrome/Firefox/Safari data for `break-before` CSS property

api/HTMLCanvasElement.json
This PR updates and corrects version values for Microsoft Edge for the `HTMLCanvasElement` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.11).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/HTMLCanvasElement
=> Update Edge data for HTMLCanvasElement API

api/SVGElement.json
This PR updates and corrects version values for Microsoft Edge for the `focus.options_preventScroll_parameter` member of the `SVGElement` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.11).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/SVGElement/focus/options_preventScroll_parameter
=> Update Edge data for api.SVGElement.focus.options_preventScroll_parameter

api/WebGLRenderingContext.json
This PR updates and corrects version values for Microsoft Edge for the `WebGLRenderingContext` API. Since SharedArrayBuffer wasn't supported before Edge 79, so features that depend on it can't be supported.
=> Update Edge data for WebGLRenderingContext API

api/HTMLElement.json, html/global_attributes.json
This PR updates and corrects version values for Microsoft Edge for the `contentEditable.plaintext-only` member of the `HTMLElement` API. The data comes from manual testing, running test code through BrowserStack, SauceLabs, custom VMs and/or locally.
Test Code: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/contenteditable#pasting_content_into_contenteditable
=> Update Edge data for api.HTMLElement.contentEditable.plaintext-only

api/Selection.json
This PR updates and corrects version values for Microsoft Edge for the `Selection` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.11).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/Selection
=> Update Edge data for Selection API

http/headers/Clear-Site-Data.json
Add Chrome notes about issues with `Clear-Site-Data: cache`.
Also reflects that Chrome 63 temporarily [disabled the feature](https://chromiumdash.appspot.com/commit/63d6097e91187b1f6cb171b7e44d88ab0a91124c), before [re-enabling it](https://chromiumdash.appspot.com/commit/d0976380e9c7cbf22f4689b640d1e260b10daddc) in Chrome 65.
See Chrome bugs:
- [Clear-Site-Data cache deletion can be slow and break loading](https://crbug.com/41343050)
- [Clear-Site-Data cache deletion is still slow](https://crbug.com/40233601)
Fixes #26268.
=> Add Chrome notes about `Clear-Site-Data: cache` issues

css/properties/border-collapse.json
This PR updates and corrects version values for all browsers for the `border-collapse` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.11).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/border-collapse
=> Chrome 1 / Safari 1.1 added `border-collapse` CSS property

css/properties/break-after.json
This PR updates and corrects version values for all browsers for the `break-after` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.11).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/break-after
=> Update Chrome/Firefox/Safari data for `break-after` CSS property

css/properties/break-inside.json
This PR updates and corrects version values for all browsers for the `break-inside` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.11).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/break-inside
=> Update Chrome/Firefox/Safari data for `break-inside` CSS property

css/properties/color-interpolation.json
This PR updates and corrects version values for all browsers for the `color-interpolation` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.11).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/color-interpolation
=> Chrome 1 / Firefox 3 / Safari 4 added `color-interpolation` CSS property

css/properties/dominant-baseline.json
This PR updates and corrects version values for Chrome and Safari for the `dominant-baseline` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.11).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/dominant-baseline
=> Chrome 1 / Safari 4 added `dominant-baseline` CSS property

css/properties/fill-rule.json
This PR updates and corrects version values for all browsers for the `fill-rule` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.11).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/fill-rule
=> Chrome 1 / Edge ≤15 / Firefox 3 / Safari 4 added `fill-rule` CSS property

css/properties/fill.json
This PR updates and corrects version values for all browsers for the `fill` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.11).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/fill
=> Chrome 1 / Edge ≤15 / Firefox 3 / Safari 4 added `fill` CSS property

css/properties/marker-end.json, css/properties/marker-mid.json, css/properties/marker-start.json, css/properties/marker.json
This PR updates and corrects version values for all browsers for the `marker` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.11).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/marker
=> Chrome 1 / Edge ≤15 / Firefox 3 / Safari 4 added marker CSS properties

css/properties/shape-rendering.json
This PR updates and corrects version values for all browsers for the `shape-rendering` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.11).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/shape-rendering
=> Chrome 1 / Firefox 3 / Safari 4 added `shape-rendering` CSS property

css/properties/stop-color.json
This PR updates and corrects version values for all browsers for the `stop-color` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.11).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/stop-color
=> Chrome 1 / Edge ≤15 / Firefox 3 / Safari 4 added `stop-color` CSS property

css/properties/stop-opacity.json
This PR updates and corrects version values for all browsers for the `stop-opacity` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.11).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/stop-opacity
=> Chrome 1 / Edge ≤15 / Firefox 3 / Safari 4 added `stop-opacity` CSS property

css/properties/stroke-color.json, css/properties/stroke-dasharray.json, css/properties/stroke-dashoffset.json, css/properties/stroke-linecap.json, css/properties/stroke-linejoin.json, css/properties/stroke-miterlimit.json, css/properties/stroke-opacity.json, css/properties/stroke-width.json, css/properties/stroke.json
This PR updates and corrects version values for all browsers for the `stroke` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.11).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/stroke
=> Chrome 1 / Edge ≤15 / Firefox 1.5 / Safari 4 added stroke CSS properties

css/properties/display.json
This PR updates and corrects version values for all browsers for the `table-caption` member of the `display` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.11).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/display/table-caption
=> Chrome 1 / Edge ≤15 / Safari ≤4 added `display: table-caption`

css/properties/text-anchor.json
This PR updates and corrects version values for all browsers for the `text-anchor` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.11).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/text-anchor
=> Chrome 1 / Edge ≤14 / Firefox 3 / Safari 4 added `text-anchor` CSS property

css/properties/text-orientation.json
This PR updates and corrects version values for all browsers for the `text-orientation` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.11).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/text-orientation
=> Update Chrome/Firefox data for `text-orientation` CSS property

api/Range.json
This PR updates and corrects version values for Microsoft Edge for the `collapse.toStart_parameter_optional` member of the `Range` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.11).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/Range/collapse/toStart_parameter_optional
=> Update Edge data for api.Range.collapse.toStart_parameter_optional

css/properties/clip.json
This PR updates and corrects version values for all browsers for the `auto` member of the `clip` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.11).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/clip/auto
=> Chrome/Firefox/Safari 1 added CSS `clip: auto`

docs/faq.md
Removes a FAQ item regarding outdated BCD tables.
Since the tables now get automatically updated typically within 2 hours (incl. cache expiration) after a BCD release, this question should no longer arise frequently.
=> docs(faq): remove question about outdated tables

api/SVGDiscardElement.json, svg/elements/discard.json
FF has disabled the [`<discard>`](https://developer.mozilla.org/en-US/docs/Web/SVG/Reference/Element/discard) element behind a pref in https://bugzilla.mozilla.org/show_bug.cgi?id=1954608
This was supposed to be added in 137 nightly and release in 138 but is still in discussion specification wise.
=> FF137 SVG discard element disabled behind pref

css/selectors/details-content.json
- added release note for `::details-content` in:
- Firefox experimental releases
- Firefox 138 release in experimental section
- Tested with the flag: `layout.css.details-content.enabled` in:
- Nightly
- Developer edition
- Beta
- [Content PR](https://github.com/mdn/content/pull/38953)
- [Firefox Release PR](https://github.com/mdn/content/pull/38954)
=> added release note for ::details-content to experimental and 138

css/at-rules/starting-style.json
See https://github.com/web-platform-dx/web-features/issues/2839
This feature is supported in Firefox, and we don't believe the noted missing functionality is sufficient to make it unusable for authors. In addition the transition from `display:none` is already covered by the `is_transitionable` key: https://github.com/mdn/browser-compat-data/blob/e8988baea037d5a8be014a60d9d928cf7e899f81/css/properties/display.json#L618-L655 so we have an existing record of the gap.
=> Mark Firefox as fully supporting `@starting-style`

css/types/abs.json, css/types/sign.json
Fix https://github.com/mdn/browser-compat-data/issues/26396
See https://issues.chromium.org/issues/40253181#comment12
"Turned out we still have some places of math mess left to fix."
=> Chrome 135 doesn't ship abs() and sign()

api/Document.json, api/DocumentFragment.json, api/Element.json
The `moveBefore()` method (available on `Document`, `DocumentFragment`, and `Element`) was already added to BCD, but the `spec_url` field was missing. This PR adds the `spec_url` in.
=> Add spec urls for moveBefore()

api/CanvasRenderingContext2D.json, api/CaptureController.json, api/GPUAdapterInfo.json, api/IdentityCredential.json, api/OffscreenCanvasRenderingContext2D.json, api/SVGAElement.json, api/SVGGeometryElement.json, css/properties/dynamic-range-limit.json, css/properties/print-color-adjust.json, javascript/builtins/RegExp.json
The @openwebdocs [BCD collector project](https://github.com/openwebdocs/mdn-bcd-collector) v10.12.11 found new features shipping in Chrome 136 beta which was released yesterday. Currently, the collector covers about 90% of BCD, so the following list might not be exhaustive. Also, if a feature is in Chrome Canary/behind origin trials/enrollment, it is not considered here.
With this PR, BCD considers the following 23 features as shipping in Chrome 136:
- api.CanvasRenderingContext2D.lang
- api.CaptureController.decreaseZoomLevel
- api.CaptureController.forwardWheel
- api.CaptureController.getSupportedZoomLevels
- api.CaptureController.increaseZoomLevel
- api.CaptureController.resetZoomLevel
- api.CaptureController.zoomLevel
- api.CaptureController.zoomlevelchange_event
- …
=> Updates for Chrome 136 beta

css/selectors/hover.json
these two entries are marked as non-standard since it is originally added via https://github.com/mdn/browser-compat-data/pull/783, however, this should regard as standard
also remove a not-existed edge's issue link
https://developer.mozilla.org/en-US/docs/Web/CSS/:hover
=> Mark `:hover`'s element support as standard

api/_globals/console.json
these methods are added in v1.28.2, via https://github.com/denoland/deno/pull/16724
see https://github.com/denoland/deno/releases/tag/v1.28.2
manually test for v1.28.0 and v1.29.0:
Fixes https://github.com/mdn/browser-compat-data/issues/25022
=> Add deno data for `console.{profile,profileEnd,timeStamp}`

javascript/builtins/Error.json
Update Error.isError with Deno info.
```sh
deno upgrade --version 2.1.10
deno eval "console.log(Error.isError(new Error()))" # TypeError: Error.isError is not a function
deno upgrade --version 2.2.0
deno eval "console.log(Error.isError(new Error()))" # true
```
N/A
=> Update Error.isError with Deno info

api/RTCRtpSender.json
FF138 adds support for `degradationPreference` in [`RTCRtpSender.setParameters()`](https://developer.mozilla.org/en-US/docs/Web/API/RTCRtpSender/setParameters#degradationpreference) and [`RTCRtpSender.getParameters()`](https://developer.mozilla.org/en-US/docs/Web/API/RTCRtpSender/getParameters#degradationpreference).
This adds a spec_url, and marks this `"deprecated": false`. As noted in https://bugzilla.mozilla.org/show_bug.cgi?id=1329847#c7 that is wrong - the spec moved, and probably this was assumed to be deprecated due to that fact.
Related docs work can be tracked in https://github.com/mdn/content/issues/38880
=> RTCRtpSender degradationPreference not deprecated

http/headers/Reporting-Endpoints.json
Fix https://github.com/mdn/browser-compat-data/issues/26361
See https://github.com/WebKit/WebKit/pull/3613
=> Safari 16.4 supports Reporting-Endpoints header

css/properties/background-position.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `background-position` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.11).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/background-position
=> Safari 1 added `background-position` CSS property

.github/workflows/release.yml
Comment in the release PR after release is published, pinging `@mdn/bcd-releasers` (@caugner + @Elchi3) in case of a failure.
Ensures that a failed BCD release gets noticed right away.
(Tested locally [here](https://github.com/mdn/browser-compat-data/pull/26313#issuecomment-2776220172).)
Fixes https://github.com/mdn/browser-compat-data/issues/26382.
=> ci(release): comment in release PR after publish

http/headers/Set-Login.json
FF138 adds support for the [`Set-Login`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/Set-Login) HTTP response header in https://bugzilla.mozilla.org/show_bug.cgi?id=1945573.
This adds a subfeature. Note that this is part of the `NavigatorLogin` additions that were done in https://github.com/mdn/browser-compat-data/pull/26371
Related docs work can be tracked in https://github.com/mdn/content/issues/38949
=> FF138 Set-Login HTTP header

api/Notification.json
FF138 supports [`Notification.actions`](https://developer.mozilla.org/en-US/docs/Web/API/Notification/actions) in nightly in https://bugzilla.mozilla.org/show_bug.cgi?id=1225110
This adds the feature. Note that `maxActions` was also part of above issue, but feature for that was added in  #26371
Related docs can be tracked in https://github.com/mdn/content/issues/38886
=> FF138 Notification.actions in nightly

api/EventTarget.json, api/Observable.json, api/Subscriber.json
I re-ran the collector for Chrome 135 release channel and the Observable API can now be observed as shipping :)
https://wicg.github.io/observable/
https://chromestatus.com/feature/5154593776599040
https://developer.chrome.com/release-notes/135#observable_api
=> Chrome 135 supports Observable API

api/Navigator.json
Fix https://github.com/mdn/browser-compat-data/issues/26397
=> Chrome 129 supports Web Share on macOS

css/properties/border-image-repeat.json
This PR updates and corrects version values for Firefox and Firefox Android for the `border-image-repeat` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.11).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/border-image-repeat
=> Firefox 15 added `border-image-repeat` CSS property

css/properties/color-adjust.json
This PR updates and corrects version values for Firefox and Firefox Android for the `color-adjust` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.11).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/color-adjust
=> Firefox 48 added `color-adjust` CSS property

css/properties/font-synthesis.json
This PR updates and corrects version values for Firefox and Firefox Android for the `font-synthesis` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.11).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/font-synthesis
=> Firefox 34 added `font-synthesis` CSS property

css/properties/font-variant-alternates.json
This PR updates and corrects version values for Firefox and Firefox Android for the `font-variant-alternates` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.11).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/font-variant-alternates
=> Firefox 34 added `font-variant-alternates` CSS property

css/properties/font-variant-position.json
This PR updates and corrects version values for Firefox and Firefox Android for the `font-variant-position` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.11).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/font-variant-position
=> Firefox 34 added `font-variant-position` CSS property

css/properties/inset-block-end.json, css/properties/inset-block-start.json, css/properties/inset-block.json, css/properties/inset-inline-end.json, css/properties/inset-inline-start.json, css/properties/inset-inline.json, css/properties/inset.json
This PR updates and corrects version values for Firefox and Firefox Android for the `auto` member of the `inset` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.11).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/inset/auto
=> Firefox 41/66 added CSS `inset*: auto`

css/properties/list-style-type.json
This PR updates and corrects version values for Firefox and Firefox Android for the `none` member of the `list-style-type` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.11).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/list-style-type/none
=> Firefox 1 supported CSS `list-style-type: none`

css/properties/ruby-position.json
This PR updates and corrects version values for Firefox and Firefox Android for the `ruby-position` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.11).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/ruby-position
=> Firefox 38 added `ruby-position` CSS property

css/properties/clip-path.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `view-box` member of the `clip-path` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.11).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/clip-path/view-box
=> Safari 13.1 added CSS `clip-path: view-box`

css/properties/font-variant-alternates.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `font-variant-alternates` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.11).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/font-variant-alternates
=> Safari 9.1 added CSS `font-variant-alternates: {historical-forms,normal}`

css/properties/font-variant-position.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `font-variant-position` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.11).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/font-variant-position
=> Safari 9.1 added CSS `font-variant-position: {normal,sub,super}`

css/properties/hanging-punctuation.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `hanging-punctuation` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.11).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/hanging-punctuation
=> Safari 10 added `hanging-punctuation` CSS property

css/properties/mix-blend-mode.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `plus-darker` member of the `mix-blend-mode` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.11).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/mix-blend-mode/plus-darker
=> Safari 9 added CSS `mix-blend-mode: plus-darker`

css/properties/scroll-snap-type.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `scroll-snap-type` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.11).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/scroll-snap-type
=> Safari 11 added `scroll-snap-type` CSS property

css/properties/text-wrap.json
See https://webkit.org/blog/16547/better-typography-with-text-wrap-pretty/
=> Safari TP 216 supports `text-wrap: pretty`

css/properties/text-emphasis-position.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `text-emphasis-position` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.11).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/text-emphasis-position
=> Safari 7 added `text-emphasis-position` CSS property

css/properties/text-emphasis-style.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `text-emphasis-style` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.11).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/text-emphasis-style
=> Safari 7 added `text-emphasis-style` CSS property

css/properties/page.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `page` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.11).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/page
=> Safari 1 added `page` CSS property

css/properties/text-decoration-skip.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `text-decoration-skip` CSS property. This fixes the data based upon the notes.
=> Safari 7 supported CSS `-webkit-text-decoration-skip: {auto,none}`

css/selectors/column.json
BCD already contains support data for the `::column` pseudo-element, but we couldn't find the spec initially, so we thought it was non-standard. We've now found it in the multi-col level 2 spec, so this PR adds the `spec_url` and updates the `standard_track` appropriately.
=> Add spec for CSS `::column` pseudo-element

.github/workflows/release-pr.yml, .github/workflows/update-mdn-urls.yml, .github/workflows/update-web-features.yml, .github/workflows/update-webdriver-bidi-data.yml
Ensures that the pre-commit hook runs in CI, which they no longer do since migrating from husky to lefthook (d3183ea0cc3290c141289d4e3b93db38bafc6e64).
The verbose alternative would be to explicitly run:
```
git add .
npx lefthook run pre-commit
```
See:
- https://github.com/evilmartians/lefthook/pull/1001
=> ci(workflows): install lefthook hooks via CI=false

api/CommandEvent.json, api/HTMLButtonElement.json, api/HTMLElement.json, html/elements/button.json
Safari TP 216 supports command/commandfor
Not in release notes but manually checked. 
See https://wpt.fyi/results/html/semantics/the-button-element/command-and-commandfor?label=master&label=experimental&aligned&q=not%28is%3Atentative%29
=> Safari TP 216 supports command/commandfor

api/EXT_frag_depth.json, api/EXT_shader_texture_lod.json
Edge 93 supports `EXT_frag_depth` + `EXT_shader_texture_lod`.
Tested with BrowserStack Live on Windows 11:
- ✅ Edge 93
- :x: Edge 92
Fixes https://github.com/mdn/browser-compat-data/issues/26484.
=> Edge 93 supports `EXT_frag_depth` + `EXT_shader_texture_lod`

browsers/edge.json, scripts/update-browser-releases/edge.ts, scripts/update-browser-releases/index.ts, scripts/update-browser-releases/utils.ts
Updates the Edge release update script to account for the new release note URLs.
Fixes #26477.
=> feat(update-browser-releases): use new Edge release note urls

.github/dependabot.yml
We removed emojis from labels, but the Dependabot config still referenced a label with an emoji.
Dependabot [posts a warning](https://github.com/mdn/browser-compat-data/pull/26251#issuecomment-2735096730) about the missing label in every Dependabot PRs for GitHub Actions.
=> fix(dependabot): remove emoji from label

api/PerformanceEventTiming.json
FF138 added support for [`PerformanceEventTiming.interactionId`](https://developer.mozilla.org/en-US/docs/Web/API/PerformanceEventTiming/interactionId) behind a pref in https://bugzilla.mozilla.org/show_bug.cgi?id=1934683
This adds the subfeature. 
Related docs work can be tracked in https://github.com/mdn/content/issues/38885
=> Firefox Nightly supports `PerformanceEventTiming.interactionId`

css/types/gradient.json
- Chrome 135: https://chromiumdash.appspot.com/commit/de30a22358e9ae8d4688d0e51de8d27c69cc4f91
- Safari 18.4: https://developer.apple.com/documentation/safari-release-notes/safari-18_4-release-notes#CSS:~:text=Added%20support%20for%20gradients%20with%20only%20one%20stop
=> Update the browser version of the CSS gradient `single_color_stop` feature

css/properties/accent-color.json
Adds a subfeature `maintains_contrast` to CSS `accent-color`, which is only supported by Firefox.
Tested with https://accent-color.glitch.me/ in Firefox 92 using BrowserStack Live.
Bugs:
- Chrome: [Checkbox's checkmark doesn't invert in response to accent-color on android](https://crbug.com/343503163)
- Safari: [accent-color: white makes checkbox checkmark invisible](https://webkit.org/b/244233)
Fixes https://github.com/mdn/browser-compat-data/issues/26073.
Fixes https://github.com/mdn/browser-compat-data/issues/26381.
=> Firefox 92 maintains CSS `accent-color` contrast for legibility

docs/contributing.md
Removes the link to the `not-webview-exposed.txt` file in the Chromium repo, which was deleted in https://source.chromium.org/chromium/chromium/src/+/d83e960b676d9b7761163445d6e514f70dcf2719.
Instead, adds a link to the `android_webview/…/global-interface-listing-expected.txt` file, which lists exposed interfaces (rather than _not_ exposed features).
=> docs(contributing): update WebView Android interface exposure link

javascript/builtins/FinalizationRegistry.json, javascript/builtins/WeakRef.json
Moves the `Non-registered symbol as target` subfeatures:
- from `WeakRef` to the constructor (`WeakRef.WeakRef`)
- from `FinalizationRegistry` to the methods (`FinalizationRegistry.{register,unregister}`)
Also adds the [Firefox impl_url](https://bugzilla.mozilla.org/show_bug.cgi?id=1863140).
Fixes https://github.com/mdn/browser-compat-data/issues/26132.
=> Move symbol support subfeatures into constructor/methods

css/properties/accent-color.json
Chrome 93 also supports the subfeature introduced in https://github.com/mdn/browser-compat-data/pull/26493, just not on Android.
See [this comment](https://github.com/mdn/browser-compat-data/pull/26493#discussion_r2044226952) by @lukewarlow.
Verified in Chrome 93, and latest Chrome Android version.
Follow-up to:
- https://github.com/mdn/browser-compat-data/pull/26493
=> Chrome 93 also maintains CSS `accent-color` contrast for legibility

webextensions/api/tabs.json
Data for `tab.group`, `tab.unGroup`, and additions of `groupId` to `tab.query`, `tab.Tab`, and `tab.onUpdated`.
Addresses the changes implemented in:
- [Bug 1959713](https://bugzilla.mozilla.org/show_bug.cgi?id=1959713) - Implement tabs.Tab.groupId (this bug)
- [Bug 1959715](https://bugzilla.mozilla.org/show_bug.cgi?id=1959715) - Support groupId in tabs.query
- [Bug 1959714](https://bugzilla.mozilla.org/show_bug.cgi?id=1959714) - Implement tabs.group() and tabs.ungroup()
- [Bug 1959716](https://bugzilla.mozilla.org/show_bug.cgi?id=1959716) - Implement groupId in tabs.onUpdated
Related content changes on MDN made in https://github.com/mdn/content/pull/39145
=> Data for `tab.group`, `tab.unGroup`, and additions of `groupId`

api/CSPViolationReportBody.json
#26380 by @Elchi3  added support for Reporting API for Safari 18.4 for #26361 for @yoavweiss 
But that PR didn't include the CSP Reporting that this was implemented for so this is still marked as "preview" instead of 18.4.
See https://github.com/WebKit/WebKit/pull/3613
and
https://wpt.fyi/results/content-security-policy/reporting-api?label=stable&label=master&aligned
#26380
#26361
=> Safari 18.4 supports CSP Reporting API

webextensions/api/browserAction.json, webextensions/api/pageAction.json
https://github.com/mdn/browser-compat-data/pull/22081 accidentally added the data to `pageAction` instead of `browserAction`.
Fixes #26522
=> Correctly attribute `getUserSettings` to `browserAction`

http/headers/Origin.json
Firefox data considers the implementation without POST partial, while Edge data didn't.
It's a little better to do it like the Firefox one because this way the web UI will annotate the Edge version with the release date.
=> Edge Legacy only partially supported HTTP `Origin` header

webextensions/api/browsingData.json
Adds browser compatibility data for the `origin` and `excludeOrigin` properties of `browsingData.RemovalOptions` introduced into Chrome in release 74.
Provides for the browser compatibility data requirements of https://github.com/mdn/content/issues/27629. Related documentation changes in https://github.com/mdn/content/pull/38902
=> Additional Chrome `browsingData.RemovalOptions` properties

css/properties/text-wrap-style.json
`text-wrap-style: pretty` is supported in Safari Technology Preview. 
See: https://webkit.org/blog/16547/better-typography-with-text-wrap-pretty/
(`text-wrap: pretty` was [updated previously](https://github.com/mdn/browser-compat-data/pull/26473), but this was missed.)
=> text-wrap-style: pretty is supported in Safari Technology Preview 

.github/workflows/pr-rebase-needed.yml
Tweaks the "PR Needs Rebase" job id for consistency.
When externalizing the workflow to org reusables, the "idle" job key got in most likely via copypasta from unrelated action boilerplate.
> ![Screenshot 2025-04-19 at 18 04 00](https://github.com/user-attachments/assets/7d3c681c-7086-4cc5-a1ab-95b43de4742c)
~Not calling it `pr-rebase-needed` or `label-rebase-needed` from the source files as that seems too long and already repetitive (esp. for the check summary previews around the UI), and also skipping `dirty` nomenclature from the marketplace action used as that may mean more than just a conflict — instead went with GH's own API terminology and picked "mergeable", which sounds reasonably concise.~
=> ci(pr-rebase-needed): update job name

css/types/color.json
For consistency with the other similar partial support bugs in relative color syntax in Chrome, this adds crbug links to the notes on the relative `hsl()`/`hwb()` features.
Found using chromium bisect after documenting #26551.
Chromium bisect points to https://chromium.googlesource.com/chromium/src/+/37587902e6a31e47b8a9493e430ed06393a93e8a, which mentions bug 330096624.
n/a
=> Add Chrome bug for partial relative `hsl()`/`hwb()` support

api/MediaStreamTrack.json
Fixes https://github.com/mdn/browser-compat-data/issues/21991
=> Safari doesn't support MediaTrackConstraints.{latency,channelCount}

api/Document.json
This PR updates and corrects version values for Microsoft Edge for the `hasUnpartitionedCookieAccess` member of the `Document` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.11).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/Document/hasUnpartitionedCookieAccess
=> Edge also supports `Document.hasUnpartitionedCookieAccess`

api/Element.json
This PR updates and corrects version values for Firefox and Firefox Android for the `attachShadow.options_serializable_parameter` member of the `Element` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.11).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/Element/attachShadow/options_serializable_parameter
=> Firefox 128 added api.Element.attachShadow.options_serializable_parameter

api/Navigator.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `deprecatedReplaceInURN` member of the `Navigator` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.11).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/Navigator/deprecatedReplaceInURN
=> Chromium 128 enabled api.Navigator.deprecatedReplaceInURN

api/Window.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `sharedStorage` member of the `Window` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.11).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/Window/sharedStorage
=> Chrome 126 added api.Window.sharedStorage

javascript/statements.json
[Bug 1950836](https://bugzilla.mozilla.org/show_bug.cgi?id=1950836) adds support for `import...with { type: "json" }`.
This PR updates the BCD entries for the `with` attribute to reflect support in Nightly.
Tested in Firefox Nightly 130.0a1:
- `with { type: "json" }` is working as expected: The imported json module loads and logs correctly.
- `with { type: "css" }` is not supported: Importing a css module throws an "invalid module type" error. (tbd in [Bug 1720570](https://bugzilla.mozilla.org/show_bug.cgi?id=1720570))
Doc issue tracker: https://github.com/mdn/content/issues/38878
[Firefox Nightly Release Notes 138.0a1](https://www.mozilla.org/en-US/firefox/138.0a1/releasenotes/) > Web Platform section
=> Firefox Nightly supports import attributes with `with` syntax for json modules

api/CookieChangeEvent.json, api/CookieStore.json, api/ServiceWorkerGlobalScope.json, api/Window.json
This PR updates and corrects version values for Firefox and Firefox Android for the `CookieStore` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.11).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/CookieStore
=> Firefox 136 adds CookieStore API

api/CookieChangeEvent.json, api/CookieStore.json, api/ServiceWorkerGlobalScope.json, api/Window.json
Reverts mdn/browser-compat-data#26556
Fixes https://github.com/mdn/browser-compat-data/issues/26600.
=> Revert "Firefox 136 adds CookieStore API"

.github/workflows/pr-review-companion.yml
Adds a new experimental `pr-review-companion` workflow that (for now) runs the `diff:flat` script from the [`flat-diff`](https://github.com/mdn/browser-compat-data/compare/main...flat-diff) branch (see https://github.com/mdn/browser-compat-data/pull/25352), and posts a comment in the PR, to make it easier for reviewers to understand the changes.
Initial work for https://github.com/mdn/browser-compat-data/issues/26517.
=> ci(workflows): add initial pr-review-companion

css/types/color.json
As noted in the linked issue, this mostly copies the partial support notes for relative `rgb()`, `hsl()`, and `hwb()` in certain Chrome versions to document a very similar incorrect channel serialization range in relative `oklab()`/`oklch()`.
Code used and per-browser-version results are commented in the linked issue: https://github.com/mdn/browser-compat-data/issues/26041#issuecomment-2684039848. I observed the erroneous behavior in Chromium 121, but not 122.
~~I'm not familiar enough with the Chromium bug tracker to find if there's a bug that should be linked here. (I wouldn't be surprised if it was fixed with the relative `rgb()` bug, which links to https://crbug.com/41490327.)~~ Found using bisect-builds.py; will update link.
Resolves #26041.
=> Chrome 119-121 had partial relative `oklab()`/`oklch()` support

api/CSSFontFeatureValuesRule.json
https://drafts.csswg.org/css-fonts/#cssfontfeaturevaluesrule-dfn
https://issues.chromium.org/issues/385925149
https://chromiumdash.appspot.com/commit/9d821a1e08753f8ec3c389e3bc8014f28595c90a
Fixes https://github.com/mdn/browser-compat-data/issues/25611
=> Chrome 111-133 doesn't expose CSSFontFeatureValuesRule

javascript/statements.json
This is a follow-up to https://github.com/mdn/browser-compat-data/pull/26583.
The feature is confirmed to be available in all trains: https://groups.google.com/a/mozilla.org/g/dev-platform/c/segjV77p6k0/m/A3ikPo1cAwAJ
- Tested in 138.01a Nightly and 138.0b9 Beta
- Confirmed with the Firefox engineer
Doc issue tracker: https://github.com/mdn/content/issues/38878
- [Firefox Nightly Release Notes 138.0a1](https://www.mozilla.org/en-US/firefox/138.0a1/releasenotes/) > Web Platform section
- [Firefox Beta and Developer Edition Release Notes](https://www.mozilla.org/en-US/firefox/138.0beta/releasenotes/) > Web Platform section
=> Firefox 138 supports `import` attribute for JSON modules

api/DOMTokenList.json, api/Element.json, api/MediaDevices.json, api/RTCStatsReport.json, api/Window.json, api/XMLHttpRequest.json, css/at-rules/media.json, css/properties/animation-duration.json, css/properties/font-variant-alternates.json, css/properties/shape-outside.json, css/properties/zoom.json, css/selectors/is.json, css/selectors/where.json, css/types/basic-shape.json, css/types/color.json, html/elements/input.json, javascript/builtins/JSON.json, javascript/builtins/Promise.json, javascript/builtins/Symbol.json, javascript/grammar.json, javascript/operators/spread.json, lint/linter/test-mdn-urls.ts, scripts/check-mdn-url-anchors.ts, webextensions/manifest/content_security_policy.json, webextensions/manifest/theme_experiment.json, webextensions/manifest/web_accessible_resources.json
Adds a lint that checks the hash of `mdn_url`s to ensure they're lowercase.
Fixes all errors, and removes some no-longer existing anchors.
Also adds a `check-mdn-url-anchors` script that fetches all MDN urls with a fragment, and checks whether the page contains the anchor.
Fixes https://github.com/mdn/browser-compat-data/issues/26597.
=> feat(lint): check + fix hash of MDN urls

browsers/opera.json, scripts/update-browser-releases/index.ts, scripts/update-browser-releases/opera.ts
Updates the update-browser-releases script for Opera to look for the Chromium version in the actual blog post content, if the description doesn't contain it.
Also updates the Opera release data, by running the script (`npm run update-browser-releases -- --opera`), and applying manual fixes.
Fixes https://github.com/mdn/browser-compat-data/issues/26584.
=> fix(update-browser-releases): find Opera engine version in content

api/AudioWorkletGlobalScope.json
Assuming we need an entry for this, not picked up in https://github.com/mdn/browser-compat-data/pull/26371
- __Spec:__ https://webaudio.github.io/web-audio-api/#dom-audioworklet-port
- __WPT:__ https://wpt.fyi/results/webaudio/the-audio-api/the-audioworklet-interface/audioworklet-messageport.https.html?label=experimental&label=master&aligned
- __Bugzilla:__ [1861363](https://bugzilla.mozilla.org/show_bug.cgi?id=1951240)
=> Firefox 138 supports AudioWorkletGlobalScope.port

css/properties/mask-clip.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `mask-clip` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.12).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/mask-clip
=> Chromium doesn't support `mask-clip: {border,content,padding,text}` without prefix

css/selectors/picker-icon.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `picker-icon` CSS selector. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.12).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/selectors/picker-icon
=> Chrome 133 added `::picker-icon` CSS selector

webextensions/api/webRequest.json
Replaces 105 Chrome ranges in `webextensions.api.webRequest`.
Sources:
- Chrome 18: https://github.com/caugner/chromium-releases/blame/v18/chrome/common/extensions/api/webRequest.json
- Chrome 23: https://github.com/caugner/chromium-releases/blame/v23/chrome/common/extensions/api/web_request.json
- Chrome 43: https://github.com/caugner/chromium-releases/blame/v43/extensions/common/api/web_request.json
Fixes https://github.com/mdn/browser-compat-data/issues/25797.
=> Replace Chrome ranges in `webextensions.api.webRequest`

css/properties/white-space.json
see https://bugzilla.mozilla.org/show_bug.cgi?id=1852478, also notice like chrome, `white-space-trim` value is not supported
Fixes https://github.com/mdn/browser-compat-data/issues/25215
=> Firefox 124 partially supports `white-space` shorthand values like Chrome

html/elements/script.json
Given https://wpt.fyi/results/import-maps/multiple-import-maps?label=stable&label=master&aligned, this changes the support matrix for multiple import maps to include Safari 18.4
[https://wpt.fyi/results/import-maps/multiple-import-maps?label=stable&label=master&aligned](WPT tests) show that's the case.
=> Safari 18.4 supports multiple import maps

.github/workflows/pr-review-companion.yml, .github/workflows/update-browser-releases.yml, .github/workflows/update-web-features.yml
Ensures workflows pass data between steps via `GITHUB_OUTPUT`.
Avoids unintended side-effects of using `GITHUB_ENV`.
See also:
- https://github.com/mdn/content/pull/38702
- https://github.com/mdn/translated-content/pull/26462
=> ci: pass data between steps via GITHUB_OUTPUT

webextensions/api/webRequest.json
Add a note that Safari provided for support for `webRequest` use in MV3 in Safari 18.
Fixes https://github.com/mdn/browser-compat-data/issues/24571
=> Safari 18 supports `webextensions.api.webRequest` in MV3

api/Document.json, api/HTMLIFrameElement.json, api/Request.json, api/_globals/fetch.json, html/elements/iframe.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `browsingTopics` member of the `Document` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.11).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/Document/browsingTopics
=> Chrome 126 added Topics API (`browsingTopics`)

api/Scheduler.json, api/TaskController.json, api/TaskPriorityChangeEvent.json, api/TaskSignal.json, api/_globals/scheduler.json
FF139 enables the Prioritized Scheduling API in Nightly in https://bugzilla.mozilla.org/show_bug.cgi?id=1958943 (sets `dom.enable_web_task_scheduling` to `true`, and also adds support for the `scheduler.yield()` method in https://bugzilla.mozilla.org/show_bug.cgi?id=1920115
This changes all the features to indicate their support in preview.
Related docs work can be tracked in https://github.com/mdn/content/issues/39310
=> FF139 Prioritize Scheduler API enabled Nightly

webextensions/api/declarativeNetRequest.json, webextensions/api/webRequest.json
This adds `json` to `webextensions.api.webRequest.ResourceType`.
The test code is defined in Firefox source-code: https://phabricator.services.mozilla.com/D230563, but import attribution support on Firefox is blocking this.
Also, `declarativeNetRequest.ResourceType` should be confirmed in the future.
fixes #26016
refs https://github.com/mdn/content/pull/38305
=> Firefox 138 adds `webextensions.api.webRequest.ResourceType.json`

css/properties/reading-flow.json, css/properties/reading-order.json
The `reading-flow` and `reading-order` CSS properties are enabled by default in Chrome 137 onwards (see https://chromestatus.com/feature/5113638848561152).
This PR updates the existing `reading-flow` data to just show the release version, and adds a sub-data point for each of the keyword values. It also adds a new data point for `reading-order`.
=> Data update for reading-flow and reading-order

api/Fence.json, api/FencedFrameConfig.json, api/HTMLFencedFrameElement.json, api/Window.json, html/elements/a.json, html/elements/fencedframe.json, http/headers/Content-Security-Policy.json, http/headers/Sec-Fetch-Dest.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `Fence` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.11).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/Fence
=> Chrome 126 added Fence API

api/HTMLIFrameElement.json, api/HTMLImageElement.json, api/SharedStorage.json, api/SharedStorageWorklet.json, api/SharedStorageWorkletGlobalScope.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `SharedStorage` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.11).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/SharedStorage
=> Chrome 126 added SharedStorage API

api/HTMLCanvasElement.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `contextrestored_event` member of the `HTMLCanvasElement` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.13).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/HTMLCanvasElement/contextrestored_event
=> Chromium 99 added `HTMLCanvasElement.contextrestored_event`

api/SVGDiscardElement.json
This PR updates and corrects version values for Firefox and Firefox Android for the `SVGDiscardElement` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.13).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/SVGDiscardElement
Additional Notes: It looks like in the stable release, the flag was enabled by default.
=> Firefox 136 exposes SVGDiscardElement API

api/Element.json
Previously `click`, `auxclick`, `contextmenu` events were not a `PointerEvent` in Firefox and Safari. But it seems like that's changed. This patch updates the "Is a `PointerEvent`" subfeatures to reflect their correct implementation status.
These events were made PointerEvents in this bug in Firefox: https://bugzil.la/1675847
These events were made PointerEvents in this bug in Safari: https://webkit.org/b/218665
Rel notes for Safari: https://developer.apple.com/documentation/safari-release-notes/safari-18_2-release-notes#New-Features
Fixes #25566.
=> Firefox 129 + Safari 18.2 implemented `api.Element.{click,auxclick,contextmenu}_event` as `PointerEvent`

css/properties/font-synthesis-style.json
Found by the collector (might be forgotten earlier or the spec was just updated recently for this new value to be picked up)
Evidence: https://bugzilla.mozilla.org/show_bug.cgi?id=1945641
=> Firefox 137 supports `font-synthesis-style: oblique-only`

api/CredentialsContainer.json, api/Element.json, api/HTMLDialogElement.json, html/global_attributes.json, javascript/builtins/Date.json, javascript/builtins/Temporal.json, javascript/builtins/Temporal/Duration.json, javascript/builtins/Temporal/Instant.json, javascript/builtins/Temporal/Now.json, javascript/builtins/Temporal/PlainDate.json, javascript/builtins/Temporal/PlainMonthDay.json, javascript/builtins/Temporal/PlainTime.json, javascript/builtins/Temporal/PlainYearMonth.json, javascript/builtins/Temporal/ZonedDateTime.json
The @openwebdocs [BCD collector project](https://github.com/openwebdocs/mdn-bcd-collector) v10.12.13 found new features shipping in Firefox 139 beta which was released this week. Currently, the collector covers about 90% of BCD, so the following list might not be exhaustive. Also, if a feature is in Firefox Nightly only, it is not considered here.
With this PR, BCD considers the following 208 features as shipping in Firefox 139:
- api.CredentialsContainer.create.publicKey_option.extensions.largeBlob
- api.CredentialsContainer.get.publicKey_option.extensions.largeBlob
- api.Element.beforematch_event
- api.HTMLDialogElement.requestClose
- html.global_attributes.hidden.until-found
- javascript.builtins.Date.toTemporalInstant
- javascript.builtins.Temporal
- …
=> Updates for Firefox 139 beta

api/ImageData.json, api/Selection.json, css/properties/reading-flow.json, css/properties/reading-order.json, lint/linter/test-spec-urls.ts, webassembly/jspi.json
The @openwebdocs [BCD collector project](https://github.com/openwebdocs/mdn-bcd-collector) v10.12.13 found new features shipping in Chrome 137 beta which was released last week. Currently, the collector covers about 90% of BCD, so the following list might not be exhaustive. Also, if a feature is in Chrome Canary/behind origin trials/enrollment, it is not considered here.
With this PR, BCD considers the following 13 features as shipping in Chrome 137:
- api.ImageData.pixelFormat
- api.Selection.direction
- api.Selection.getComposedRanges
- css.properties.reading-flow
- css.properties.reading-flow.flex-flow
- css.properties.reading-flow.flex-visual
- css.properties.reading-flow.grid-columns
- css.properties.reading-flow.grid-order
- css.properties.reading-flow.grid-rows
- …
=> Updates for Chrome 137 beta

http/headers/Expect-CT.json
Chromium 107 disabled Expect-CT header by default. All Chromium-based browsers followed the removal too.
[Chrome Platform status](https://chromestatus.com/feature/6244547273687040) lists `Expect-CT` as removed in Chrome 107.[Chromium issue 40780328](http://crbug.com/40780328) list most of the relevant CLs/PRs. Notably, [this commit](https://github.com/chromium/chromium/commit/ac7ca3a50ee55112ade8b41aa1999c32fc391014) disables this header in Chromium 107.
N/A
=> Chromium 107 removed `Expect-CT` response header

api/HTMLInputElement.json, api/HTMLTextAreaElement.json
+ `selectionchange` event is available in Chrome since version 127 and in Safari since version 18 (specifically Webkit [619.1.6](https://github.com/WebKit/WebKit/blob/0a064d401bd0a68d148be77d03cb3c157188c04b/Configurations/Version.xcconfig#L24-L26)).
+ Also, the feature is now no longer in experimental status, as it's supported by the three major browser engines.
See:
Description | Link
-------------|-----
Webkit bug tracker | https://bugs.webkit.org/show_bug.cgi?id=271033
Chrome bug tracker | https://issues.chromium.org/issues/40840956
Automated test cases | https://wpt.fyi/results/selection/textcontrols/selectionchange.html?label=experimental&label=master&aligned
JSFiddle by @caugner | https://jsfiddle.net/jx6gakhb/
+ Fixes #25672
=> Chrome 127 + Safari 18 add `selectionchange` event on `HTMLInputElement` + `HTMLTextAreaElement`

api/PushSubscriptionChangeEvent.json
This PR updates and corrects version values for Firefox and Firefox Android for the `PushSubscriptionChangeEvent` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.13).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/PushSubscriptionChangeEvent
=> Firefox 137 adds PushSubscriptionChangeEvent API

api/CanvasRenderingContext2D.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `drawImage.ImageBitmap_source_image` member of the `CanvasRenderingContext2D` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.13).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/CanvasRenderingContext2D/drawImage/ImageBitmap_source_image
Additional Notes: ImageBitmap wasn't available in Chrome before Chrome 50.
=> Update Chromium data for api.CanvasRenderingContext2D.drawImage.ImageBitmap_source_image

api/EventTarget.json
This PR updates and corrects version values for Microsoft Edge for the `EventTarget` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.13).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/EventTarget
=> Update Edge data for EventTarget API

api/MediaStreamTrackProcessor.json
- Have MediaStreamTrackProcessor members inherit partial support in chrome, for visibility
- ~Add mdn links to VideoTrackGenerator~
`npm test` verified JSON, but complains of missing mdn links for VideoTrackGenerator (coming in https://github.com/mdn/content/pull/39124).
couldn't get `npm run stats` to work, so hopefully things look OK.
Spec: https://w3c.github.io/mediacapture-transform/
=> Update MediaStreamTrackProcessor spec_url and mark Chrome constructor support as partial

browsers/webview_android.json
The release date of two releases in Android Webview are wrong. They have year 2017, but they were released in 2018. The date is correct otherwise.
Announcements for `65` and `66` respectively:
* https://chromereleases.googleblog.com/2018/03/chrome-for-android-update.html
* https://chromereleases.googleblog.com/2018/04/chrome-for-android-update.html
N/A
=> Fix release years for Android Webview 65 and 66

webassembly/api.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `api` member of the `webassembly` WebAssembly interface. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.12.13).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/webassembly/api
=> Update Chromium data for webassembly.api

css/properties/max-height.json, css/properties/max-width.json, css/properties/min-height.json, css/properties/min-width.json
Updates Safari data for `{min,max}-{height,width}: stretch`.
See: https://github.com/mdn/browser-compat-data/issues/24190#issuecomment-2858357934 (and previous comments)
Safari 7 added support for `{min,max}-height: -webkit-fill-available`.
Safari 9 added support for `{min,max}-width: -webkit-fill-available`.
- Fixes https://github.com/mdn/browser-compat-data/issues/24190.
=> Update Safari data for `{min,max}-{height,width}: stretch`

html/elements/script.json
Adds several `mdn_url` and `spec_url` values for  `<script type="speculationrules">` subfeatures.
- Related to: https://github.com/mdn/browser-compat-data/pull/26485
=> Adds MDN urls and spec urls for `<script type="speculationrules">` subfeatures

api/Gamepad.json, api/Navigator.json, api/VRDisplay.json, api/VRDisplayCapabilities.json, api/VRDisplayEvent.json, api/VREyeParameters.json, api/VRFieldOfView.json, api/VRFrameData.json, api/VRPose.json, api/VRStageParameters.json, api/Window.json
Fixes several overlapping support statements for Firefox related to VR features.
Before, there were _distinct_ statements for
1. Windows support (added 55, removed 98), and
2. macOS support (added 64, removed 98).
After, there are _cumulative_ statements for
1. Windows support (added 55, removed 64), and
2. macOS **and** Windows support (added 64, removed 98).
Extracted from https://github.com/mdn/browser-compat-data/pull/26544.
Part of https://github.com/mdn/browser-compat-data/issues/26543.
=> Fix overlapping VR support statements for Firefox

webextensions/manifest/dark_theme.json
Adds browser compatibility data for the dark_theme manifest key introduced in Firefox 68 ([Bug 1525762](https://bugzilla.mozilla.org/show_bug.cgi?id=1525762)) response to comment on [Comment 15](https://bugzilla.mozilla.org/show_bug.cgi?id=1958596#c15)  on [Bug 1958596](https://bugzilla.mozilla.org/show_bug.cgi?id=1958596)
- related developer documentation in https://github.com/mdn/content/pull/39122
- related extension workshop theme documentation in https://github.com/mozilla/extension-workshop/pull/2050
=> Bug-1958596 `dark_theme` manifest key support

api/CreateMonitor.json, api/Summarizer.json, http/headers/Permissions-Policy.json
In discussions with Google devrel, I learned that the Summarizer API is only supported on Windows/macOS/Linux, not Android (or ChromeOS). This PR updates our data to suit.
=> Chrome Android doesn't support Summarizer API

api/CookieStore.json
The entries for Safari in the CookieStore API compat table were incorrect, this change modifies {get, set, delete}.partitioned to be labelled as unsupported and get.name, get.value to be labelled as supported as of 18.4. 
Tested against document.cookie/inspector panel, used the data on https://mdn-bcd-collector.gooborg.com/tests/api/CookieStore
Fixes #26717
=> Safari 18.4 doesn't support `partitioned`, but returns `name/value` in CookieStore API

javascript/builtins/JSON.json
Update Safari data for context parameter on reviver function of `JSON.parse` feature
* How
Running on below script on `Console` tab on `Developer Tool` of `Safari 18.4` directly.
```
var json = '{"test":"abc","test2":"def","test3":{"test4":"ghi"}}'
JSON.parse(json, (key, value, context) => {
console.log({ key, value, context })
return value
})
```
* Result
* Fixes #26720
=> Safari 18.4 supports `context` parameter in `JSON.parse()` reviver

api/AudioContext.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `outputLatency` member of the `AudioContext` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.13.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/AudioContext/outputLatency
=> Safari 18.4 adds `AudioContext.outputLatency`

api/CaretPosition.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `CaretPosition` API. A previous update with collector data said this was supported, but this was from the beta version of Safari 18.4, which appears to have had the flag enabled.
=> Safari 18.4 supports CaretPosition API only behind flag

webassembly/api/Memory.json
Update Node.js data for `webassembly.api.Memory.Memory.shared`.
Note: This makes the previous statement obsolete, because it has `flags`.
The flag was enabled in V8 9.2.45, see: https://github.com/v8/v8/commit/be9ff65a06963f9326756c056a338e1b9e07499c
Node.js 16.5 used V8 9.1, and Node.js used V8 9.2.230, see: https://nodejs.org/dist/index.json
See also: https://github.com/nodejs/node/pull/45074
=> Node.js 16.6 shipped `shared` flag on WebAssembly `Memory()` constructor

javascript/builtins/Error.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `captureStackTrace` member of the `Error` JavaScript builtin. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.13.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/javascript/builtins/Error/captureStackTrace
=> Safari 17.2 added `Error.captureStackTrace()`

javascript/builtins/Temporal/PlainDateTime.json
Follow-up to https://github.com/mdn/browser-compat-data/pull/26693. I seem to have simply forgotten to add this file to my previous PR. Sorry!
=> Firefox 139 supports Temporal.PlainDateTime

api/Element.json, api/ShadowRoot.json
FF139 adds support for escaping `<` and `>` to `&lt;` and `&gt;` in attributes when serializing HTML in https://bugzilla.mozilla.org/show_bug.cgi?id=1941347. This affects all the obvious methods like innerHTML, outerHTML, getHTML.
This is enabled in nightly from FF139 (associated pref is `dom.security.html_serialization_escape_lt_gt`)
Some questions inline.
Related docs work can be tracked in https://github.com/mdn/content/issues/39309
=> Firefox Nightly escapes `<` and `>` in attributes when serializing HTML

browsers/nodejs.json, javascript/builtins/Error.json, javascript/builtins/Float16Array.json, javascript/builtins/RegExp.json, javascript/builtins/Symbol.json, webassembly/memory64.json
RegExp.escape added to nodejs v24
https://nodejs.org/en/blog/release/v24.0.0
=> Updates for Node.js 24.0

api/Document.json, api/Element.json, api/Sanitizer.json
⚠️ Work in progress
- Reverts Sanitizer API deletion in https://github.com/mdn/browser-compat-data/pull/23989
EDIT.
- Undid reversion of API as per https://github.com/mdn/browser-compat-data/pull/26659#discussion_r2071110958 - not planning to redo unless you insist.
- Have not added tags
- FF139 `Document.parseHTML()` : https://bugzilla.mozilla.org/show_bug.cgi?id=1959725
-  FF138 Implement an unoptimized Sanitizer prototype https://bugzilla.mozilla.org/show_bug.cgi?id=1950605
- `Sanitizer`, `Element.setHTML()`
- FF138 Implement the `Sanitizer.removeUnsafe()` method - https://bugzilla.mozilla.org/show_bug.cgi?id=1952250
Not yet implemented "Add a sanitizer option to Element/Shadowroot `setHTMLUnsafe()` and `Document.parseHTMLUnsafe()`" - see …
=> Firefox 138/139 adds new Sanitizer API behind flag

javascript/builtins/Intl/NumberFormat.json
Deno 1.25 supports decimal string number format
Tested: https://github.com/mdn/browser-compat-data/issues/25128#issuecomment-2871722504
https://github.com/mdn/browser-compat-data/issues/25128
=> Deno 1.25 supports `NumberFormat.format` decimal string

css/properties/text-combine-upright.json
Add all,none values to text-combine-upright
None.
=> Add CSS `text-combine-upright: {all,none}`

css/properties/accent-color.json
This undoes the structural changes represented by https://github.com/mdn/browser-compat-data/pull/26493 and the follow-up https://github.com/mdn/browser-compat-data/pull/26518, but keeps the data as `partial_implementation`.
I suspect we'll wish to discuss this at the next BCD meeting—before merging—since it touches on (so far minimal) guidelines for `partial_implementation` and when to use it.
Roughly, the support details _are_ the previous two PRs.
I think there was perhaps a case to be made for Safari being alone as a weird, but mostly functional outlier. But the sum of the two PRs are such that we have this story:
1. `accent-color` has 3 distinct behaviors for certain color values (Firefox and deskop Chrome; Chrome for Android; Safari).
2. Two of those behaviors (Chrome for Android …
=> Roll up `css.properties.accent-color.maintains_contrast` into parent

css/properties/font-kerning.json
The font-kerning CSS property was missing its values.
None.
=> Add CSS `font-kerning: {auto,none,normal}`

css/properties/empty-cells.json
Add the missing values `hide` and `show` to` empty-cells`.
And these values are essential for the property and likely supported from the start.
None.
=> Add CSS `empty-cells: {hide,show}`

css/types/if.json
The CSS [`if()`](https://drafts.csswg.org/css-values-5/#if-notation) function is supported in Chrome from version 137. See https://chromestatus.com/feature/6313805904347136.
This PR adds a data point for it.
=> Chrome 137 adds CSS `if()` function

css/properties/text-autospace.json
Safari iOS 18.4 supported CSS property `text-autospace`.
Tested in [https://mdn-bcd-collector.gooborg.com/tests/css/properties/text-autospace](https://mdn-bcd-collector.gooborg.com/tests/css/properties/text-autospace):
Description from webkit blog: [https://webkit.org/blog/16574/webkit-features-in-safari-18-4/](https://webkit.org/blog/16574/webkit-features-in-safari-18-4/)
Fix #26696
=> Safari iOS 18.4 also supports `text-autospace`

css/properties/text-underline-position.json
The auto value was missing from text-underline-position. Also, add spec_urls.
None.
=> Add CSS `text-underline-position: auto` and other values' specs

javascript/builtins/Intl/Locale.json
Adds behavioral subfeature for `Intl.Locale.getWeekInfo()` returning `minimalDays`.
Fixes https://github.com/mdn/browser-compat-data/issues/26766.
=> Add `Intl.Locale.getWeekInfo()` returns `minimalDays` data

html/elements/textarea.json, html/global_attributes.json
Merges `html.elements.textarea.spellcheck` into `html.global_attributes.spellcheck`.
> [!NOTE]
> This PR only merges the data, without updating it, although the existing data may not be 100% accurate.
Fixes https://github.com/mdn/browser-compat-data/issues/21810
=> Deduplicate spellcheck attribute

scripts/update-browser-releases/opera.ts, scripts/update-browser-releases/utils.ts
Improves the `update-browser-releases` script by falling back to the incremented engine version if the Opera release notes don't mention the Chrome version.
Fixes https://github.com/mdn/browser-compat-data/issues/26797.
=> fix(update-browser-releases): handle Opera release note without Engine version

scripts/update-browser-releases/chrome.ts, scripts/update-browser-releases/edge.ts, scripts/update-browser-releases/firefox.ts, scripts/update-browser-releases/opera.ts, scripts/update-browser-releases/safari.ts, scripts/update-browser-releases/utils.ts
This PR is a quick follow-up to #26801 to fix the formatting in two ways:
- The GFM noteblock is 'WARNING', not 'WARN'
- The first line was rendered onto the same line as the title, so a newline is always added to prevent that from occurring
=> Fix formatting in update-browser-releases script

scripts/update-browser-releases/index.ts
Generalize the pattern to extract the Chromium version from the Opera release notes blog post.
Originally, the blog post was not mentioning the Chromium version, but after reaching out, this was added:
> Chromium version bumped to 134.0.6998.205.
However, our pattern was expecting either `Chromium 134` or `Chromium to version 134`.
Now, we're basically accepting any text between "Chromium" and the version number, except dots, digits, and if the version number is followed by a dot.
Follow-up of https://github.com/mdn/browser-compat-data/pull/26801.
Part of resolving https://github.com/mdn/browser-compat-data/issues/26797.
=> fix(update-browser-releases): generalize Opera engine version pattern

javascript/grammar.json, javascript/operators/import.json
Marks `javascript.grammar.trailing_commas.trailing_commas_in_dynamic_import` and `javascript.operators.import.options_parameter` as supported in Firefox 138
https://brassy-sly-storm.glitch.me/
https://developer.mozilla.org/en-US/play?id=7R3devH9%2FzJfqyok61KERDbVW4tQY7KqsunVc7zUesJUcA5PpokTG8DLzPbseMOzzqnIoP2cdzijhTMt
https://bugzilla.mozilla.org/show_bug.cgi?id=1950836
Fixes #26811
=> Firefox 138 supports dynamic import features

api/Navigator.json, javascript/builtins/Symbol.json
Fixes overlapping version ranges.
Follow-up of: https://github.com/mdn/browser-compat-data/pull/26544
=> Fix newly overlapping version ranges

api/FontFace.json, api/FontFaceSet.json
Adds `worker_support` for WebKit on both FontFace and FontFaceSet interfaces.
Quoting https://github.com/mdn/browser-compat-data/issues/26816#issuecomment-2886551788
> Based on [that commit](https://github.com/WebKit/WebKit/commit/792fde69d188dc5b10a7a09372bee06931dd9bac), which landed in [WebKit 612.1.12](https://github.com/WebKit/WebKit/blob/792fde69d188dc5b10a7a09372bee06931dd9bac/Source/WebCore/Configurations/Version.xcconfig#L24-L26), and the [corresponding bug 224178](https://bugs.webkit.org/show_bug.cgi?id=224178), worker support for FontFace, and FontFaceSet landed in [Safari 15 (WebKit 612.1.27)](https://github.com/mdn/browser-compat-data/blob/b57256ae8ac7f29be2eb59a8e6be5be2d24d2b9f/browsers/safari.json#L176-L182).
>
> The MDN BCD Collector currently doesn't test this, as they …
=> Safari 15 supports `FontFace` and `FontFaceSet` in workers

.github/workflows/pr-review-companion.yml, .github/workflows/release-pr.yml, .github/workflows/release.yml, .github/workflows/update-browser-releases.yml, .github/workflows/update-mdn-urls.yml, .github/workflows/update-web-features.yml, .github/workflows/update-webdriver-bidi-data.yml
Disables the cache (used by `actions/setup-node`) in privileged workflows.
This limits the impact of less-privileged workflows that may be vulnerable to code injection.
=> fix(workflows): disable cache in privileged workflows

webextensions/api/storage.json
As per feedback provided in [webextensions.api.storage.session - setAccessLevel doesn't seem to be actually supported](https://github.com/mdn/browser-compat-data/issues/26694#top) #26694 and supported by [comment 8](https://bugzilla.mozilla.org/show_bug.cgi?id=1687778#c8) on [Bug 1687778](https://bugzilla.mozilla.org/show_bug.cgi?id=1687778) MV3 in-memory storage API (storage.session)
=> Correct Firefox support for `webextensions.api.storage.session.setAccessLevel`

http/headers/Permissions-Policy.json
Remove data about the obsolete HTTP header `Permissions-Policy` directive `document-domain`.
Permissions-Policy directive `document-domain` was removed from spec[1]. It was only ever implemented in Chromium behind a flag, never enabled by default and was removed entirely in Chromium 110[2].
[1] https://github.com/whatwg/html/pull/8549
[2] https://github.com/chromium/chromium/commit/09ae39cb337e46a2f97a763e57986154b8af91eb
- https://github.com/mdn/content/issues/22732
- https://github.com/mdn/content/pull/39575
=> Remove HTTP `Permissions-Policy` directive `document-domain`

css/types/ratio.json
Updates support for ratios with single values, which preceded the `aspect-ratio` property, and was used by the aspect ratio media query features.
See #25034 
Fixes #25034
=> Chrome 87 + Safari 14.1 supported single `<number>` as `<ratio>`

css/at-rules/import.json
Changing `preview` to `17.5` was missed for `css.at-rules.import.supports` in #22765.
Fixes #24842
=> Safari 17.5 added `supports()` as import condition

css/selectors/marker.json
The Safari bug which tracks full support of the `:marker` pseudo is already mentioned in the notes, but having it in the `impl_url` field makes it better for scripts which use the data.
See https://bugs.webkit.org/show_bug.cgi?id=204163
=> Add Safari impl_url for CSS `::marker` selector

package.json, scripts/split.ts, scripts/split/index.ts
Adds a `split` script that makes it easy to split up BCD JSON files.
Example:
```
% npm run split -- webdriver/bidi.json
> @mdn/browser-compat-data@6.0.16 split
> tsx scripts/split.ts webdriver/bidi.json
✔ Created: webdriver/bidi/browser.json
✔ Created: webdriver/bidi/browsingContext.json
✔ Created: webdriver/bidi/emulation.json
✔ Created: webdriver/bidi/input.json
✔ Created: webdriver/bidi/log.json
✔ Created: webdriver/bidi/network.json
✔ Created: webdriver/bidi/permission.json
✔ Created: webdriver/bidi/script.json
✔ Created: webdriver/bidi/session.json
✔ Created: webdriver/bidi/storage.json
✔ Created: webdriver/bidi/webExtension.json
✔ Deleted: webdriver/bidi.json
```
=> feat(scripts): add split script

api/CreateMonitor.json, api/Summarizer.json
The Summarizer API BCD needed corrections — the Edge version is 138, but it is currently supported behind a developer flag. This PR corrects that. cc @captainbrosset.
<s>I am going to leave it as a draft for now; hopefully I can get in some more accurate Chrome support data too.</s>
I checked, and 138 is the correct shipping version for Chrome. I'm not sure of the available version with flags, so I'm just going to leave that for now.
=> Edge 138 supports Summarizer API behind pref

api/Element.json, api/ShadowRoot.json
FF140 ships support for escaping `<` and `>` to `&lt;` and `&gt;` in attributes when serializing HTML in https://bugzilla.mozilla.org/show_bug.cgi?id=1962084. This affects all the obvious methods like innerHTML, outerHTML, getHTML.
This was implemented in FF139 last month and added to BCD in https://github.com/mdn/content/issues/39309.
All this does is change the items updated in that PR from preview to 140
Related docs work can be tracked in https://github.com/mdn/content/issues/39628
=> FF140 serializes `<` and `>` in attributes

manifests/webapp/scope_extensions.json
Chrome 138 supports the `scope_extensions` webapp manifest member; see https://chromestatus.com/feature/5746537956114432 for details.
This PR adds a data point for that feature. Note that the PR to add it to the spec isn't merged yet, so I've marked it as non-standard for now.
=> Chrome 138 support for scope_extensions manifest member

api/ViewTransition.json, css/properties/view-transition-class.json, css/properties/view-transition-name.json, css/selectors/view-transition-group.json, css/selectors/view-transition-image-pair.json, css/selectors/view-transition-new.json, css/selectors/view-transition-old.json, css/selectors/view-transition.json
- Added `view-transition` support for Firefox nightly
- Only works for parts and only for SPA (Single Page Applications) and not cross-document
- Tested with the following:
- https://view-transitions.chrome.dev/
- https://codepen.io/CodeRedDigital/pen/WbbBRJr?editors=0011
- [Mozilla MDN Issue #39305](https://github.com/mdn/content/issues/39305)
- [Content PR](https://github.com/mdn/content/pull/39593)
- [Firefox Release Note PR](https://github.com/mdn/content/pull/39588)
=> Firefox Nightly supports View Transitions

api/LanguageDetector.json, api/Translator.json
Chrome 138 supports the [Translator and Language Detector APIs](https://webmachinelearning.github.io/translation-api/): see the relevant ChromeStatus entries: https://chromestatus.com/feature/6494349985841152 and https://chromestatus.com/feature/5172811302961152.
This PR adds data for the `Translator` and `LanguageDetector` interfaces.
=> Chrome 138 adds Translator and Language Detector APIs

api/PerformancePaintTiming.json
Updates Chrome's support for `PerformancePaintTiming`, whose named entries appear to have been placed behind a launch flag since version 114.
`All matched files use Prettier code style!`  
`All data passed linting!`  
Fixes #26857
=> Chrome 116 moved `first-contentful-paint` and `first-paint` timings behind flag

api/Navigator.json
Although the Badging API is not supported on most Linux systems it is supported on ChromeOS since version 91: [Badging for Chrome OS: API usage overrides notifications · chromium/chromium@5399308](https://github.com/chromium/chromium/commit/539930833a2f4df4d163211834fe530974520e05)
Various blog posts, personal usage on Chromebooks in the past, etc. I did not attempt to find and run ChromeOS 90 and 91 to confirm personally when the feature was made available.
#26869
=> Chrome 91 added ChromeOS support for Badging API

api/TaskSignal.json
FF140 supports [`TaskSignal.any()`](https://developer.mozilla.org/en-US/docs/Web/API/TaskSignal/any_static) in nightly in https://bugzilla.mozilla.org/show_bug.cgi?id=1964407
This adds the preview version.
Related work can be tracked in https://github.com/mdn/content/issues/39627
=> Firefox Nightly adds `TaskSignal.any()`

api/PointerEvent.json
Firefox 135 added fractional coordinates for pointer events
The linked `impl_url` was marked as resolved / fixed.
=> Firefox 135 added fractional coordinates for pointer events

README.md, docs/index.md
Adds an alphabetical index of keywords covered by the BCD project docs.
Goals:
- Make it easier to quickly find frequently consulted sections.
- Provide an overview of what's currently covered by the docs.
- Making it easier to spot what's currently _not_ covered by the docs.
=> docs: add alphabetical index

api/Document.json, api/Element.json, api/ShadowRoot.json
FF140 adds remaining sanitizer method/options behind flag in https://bugzilla.mozilla.org/show_bug.cgi?id=1959727
Once FF140 becomes nightly, these would change to "preview".
Changes are:
- `ShadowRoot.setHTML()] - new method
- `options.sanitizer` added to param to `ShadowRoot.setHTMLUnsafe()` and `Document.parseHTMLUnsafe()`
This follows on from #26659
FYI @evilpie I was "somewhat wrong" in #26659. I can add them, just not as a "preview" release. I didn't think of this properly because I was so focused on FF139.
Related docs work being done in https://github.com/mdn/content/issues/38890
=> Firefox Nightly adds `ShadowRoot.setHTML()` and sanitizer parameter

api/HTMLDialogElement.json, html/elements/dialog.json
FF140 enables the [`HTMLDialogElement.closedBy`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLDialogElement/closedBy) property and `<dialog>` [`closedby`](https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/dialog#closedby) attribute in Nightly (pref `dom.dialog.light-dismiss.enabled` ) in https://bugzilla.mozilla.org/show_bug.cgi?id=1964077
This updates both of those with the attribute and the impl url in which the related pref was enabled.
Related docs work can be tracked in https://github.com/mdn/content/issues/39621
=> Firefox Nightly adds `HTMLDialogElement.closeBy`

api/CSS.json, api/CookieChangeEvent.json, api/CookieStore.json, api/CookieStoreManager.json, api/ExtendableCookieChangeEvent.json, api/Highlight.json, api/HighlightRegistry.json, api/LargestContentfulPaint.json, api/PerformancePaintTiming.json, api/ServiceWorkerGlobalScope.json, api/ServiceWorkerRegistration.json, api/Window.json, css/selectors/highlight.json
The @openwebdocs [BCD collector project](https://github.com/openwebdocs/mdn-bcd-collector) v10.13.1 found new features shipping in Firefox 140 beta which was released today. Currently, the collector covers about 90% of BCD, so the following list might not be exhaustive. Also, if a feature is in Firefox Nightly only, it is not considered here.
With this PR, BCD considers the following 66 features as shipping in Firefox 140:
- api.CSS.highlights_static
- api.CookieChangeEvent
- api.CookieChangeEvent.CookieChangeEvent
- api.CookieChangeEvent.changed
- api.CookieChangeEvent.deleted
- api.CookieStore
- api.CookieStore.change_event
- api.CookieStore.delete
- api.CookieStore.delete.partitioned_option
- api.CookieStore.get
- api.CookieStore.get.name_return_property
- …
=> Updates for Firefox 140 beta

api/PushSubscriptionChangeEvent.json, api/ServiceWorkerGlobalScope.json, api/VideoFrame.json, api/Viewport.json, api/Window.json, css/properties/height.json, css/properties/max-height.json, css/properties/max-width.json, css/properties/min-height.json, css/properties/min-width.json, css/properties/width.json, css/types/abs.json
The @openwebdocs [BCD collector project](https://github.com/openwebdocs/mdn-bcd-collector) v10.13.1 found new features shipping in Chrome 138 beta which was released yesterday. Currently, the collector covers about 90% of BCD, so the following list might not be exhaustive. Also, if a feature is in Chrome Canary/behind origin trials/enrollment, it is not considered here.
With this PR, BCD considers the following 57 features as shipping in Chrome 138:
- api.CreateMonitor
- api.CreateMonitor.downloadprogress_event
- api.LanguageDetector
- api.LanguageDetector.availability_static
- api.LanguageDetector.create_static
- api.LanguageDetector.destroy
- api.LanguageDetector.detect
- api.LanguageDetector.expectedInputLanguages
- api.LanguageDetector.inputQuota
- …
=> Updates for Chrome 138 beta

webextensions/api/cookies.json
Provide the updates necessary for [Bug 1550032](https://bugzilla.mozilla.org/show_bug.cgi?id=1550032) Change cookie API to explicitly support sameSite=none. Specifically:
- To note the introduction of `unspecified` to `cookie.SameSiteStatus`
- That `unspecified` is now the default value for `sameSite` in `cookies.set()`.
MDN documentation changes made in https://github.com/mdn/content/pull/39512.
Release note update made in https://github.com/mdn/content/pull/39513.
=> Bug-1550032 addition of unspecified to webextension.api.cookie.SameSiteStatus

api/GPUCommandEncoder.json, api/GPUDevice.json
Chrome 137 supports the following WebGPU updates:
- When using [copyBufferToBuffer()](https://developer.mozilla.org/en-US/docs/Web/API/GPUCommandEncoder/copyBufferToBuffer), you can omit the offsets and the `size` parameter when copying the entire buffer. See https://developer.chrome.com/blog/new-in-webgpu-137?hl=en#buffers_copy_without_specifying_offsets_and_size.
- When creating a `GPUBindGroup` using [`createBindGroup()`](https://developer.mozilla.org/en-US/docs/Web/API/GPUDevice/createBindGroup), you can specify a `GPUTextureView` in place of a `GPUExternalTexture`. See https://developer.chrome.com/blog/new-in-webgpu-137?hl=en#use_texture_view_for_externaltexture_binding
This PR adds data point for both those features.
- Spec PR: https://github.com/gpuweb/gpuweb/pull/5098
=> Add data points for Chrome 137 WebGPU additions

css/properties/print-color-adjust.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `print-color-adjust` CSS property. This sets the downstream browser(s) to mirror from their upstream counterpart.
=> Update Chromium data for print-color-adjust CSS property

css/properties/view-transition-name.json
Chrome 137 supports the `view-transition-name` property's `match-element` value. See https://chromestatus.com/feature/5098745710247936.
This PR adds a data point for the new value.
=> Chrome 137 supports CSS `view-transition-name: match-element`

css/selectors/marker.json
Safari has supported animatable `::marker` since Safari 14.1.
- https://developer.apple.com/documentation/safari-release-notes/safari-14_1-release-notes#CSS-and-Web-Animations
- https://trac.webkit.org/changeset/269813/webkit
=> Safari 14.1 adds support for animatable `::marker`

javascript/builtins/Math.json
Safari has supported `Math.sumPrecise()` since Safari 18.4.
- https://developer.apple.com/documentation/safari-release-notes/safari-18_4-release-notes#JavaScript
- https://commits.webkit.org/283774@main
=> Safari 18.4 adds `Math.sumPrecise()`

lint/fix.ts, lint/fixer/browser-order.ts, lint/fixer/common-errors.ts, lint/fixer/descriptions.ts, lint/fixer/feature-order.ts, lint/fixer/flags.ts, lint/fixer/links.ts, lint/fixer/mdn-urls.ts, lint/fixer/mirror.ts, lint/fixer/overlap.ts, lint/fixer/property-order.ts, lint/fixer/statement-order.ts, lint/fixer/status.ts
Reads and writes files at most once when running `lint:fix`.
```console
$ git checkout main
$ time npm run lint:fix --silent
npm run lint:fix --silent  7.02s user 0.56s system 108% cpu 6.967 total
$ git checkout read-write-files-once-in-lint-fix
$ time npm run lint:fix --silent
npm run lint:fix --silent  6.39s user 0.36s system 112% cpu 6.018 total
```
=> fix(lint/fix): read/write files only once

api/PerformanceObserver.json, api/PerformanceObserverEntryList.json, api/PerformanceResourceTiming.json
Deno doesn't support `PerformanceObserver`, `PerformanceObserverEntryList`, and `PerformanceResourceTiming`.
Noticed as part of triaging https://github.com/mdn/browser-compat-data/issues/24584.
Verified locally with Deno v2.3.2, and confirmed with GitHub search:
- `PerformanceObserver` ([denoland/deno](https://github.com/search?q=repo%3Adenoland%2Fdeno+%2FPerformanceObserver%2F&type=code) | [v8/v8](https://github.com/search?q=repo%3Av8%2Fv8%20%2FPerformanceObserver%2F&type=code))
- `PerformanceObserverEntryList` ([denoland/deno](https://github.com/search?q=repo%3Adenoland%2Fdeno+%2FPerformanceObserverEntryList%2F&type=code) | [v8/v8](https://github.com/search?q=repo%3Av8%2Fv8%20%2FPerformanceObserveEntryListr%2F&type=code))
- `PerformanceResourceTiming` …
=> Deno doesn't support Performance{Observer*,ResourceTiming}

svg/elements/tspan.json
Fixes https://github.com/mdn/browser-compat-data/issues/26945.
=> Firefox doesn't support `tspan` attrs`lengthAdjust/textLength`

api/Window.json
This PR updates and corrects version values for Microsoft Edge for the `getDigitalGoodsService` member of the `Window` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.13.2).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/Window/getDigitalGoodsService
=> Edge 134 added `api.Window.getDigitalGoodsService`

css/properties/clip-path.json
Safari supported animating clip paths (`-webkit-clip-path` at the time) in Safari 12.1.
Documentation for this change doesn't explicitly exist in [Safari 12.1 release notes](https://developer.apple.com/documentation/safari-release-notes/safari-12_1-release-notes).
However, the change to enable this functionality has been traced to here which I can confirm our records show shipped with Safari 12.1: 
https://trac.webkit.org/changeset/236541
=> Safari 12.1 added support for animated `clip-path`

css/properties/rx.json, css/properties/ry.json
Update version for rx and ry css properties 
fixes https://github.com/mdn/browser-compat-data/issues/25021
=> Safari 17.4 added CSS `rx` and `ry` properties

api/CloseWatcher.json
FF140 enables `dom.closewatcher.enabled` in Nightly for desktop only (not android) in https://bugzilla.mozilla.org/show_bug.cgi?id=1966459
Note that Android is behind  `dom.closewatcher.enabled` which is set false.
This updates the associated features.
Docs work done in https://github.com/mdn/content/pull/39862
=> Firefox 140 Nightly enables `CloseWatcher` on Desktop

api/MutationEvent.json
FF140 removes the [`MutationEvent`](https://developer.mozilla.org/en-US/docs/Web/API/MutationEvent) and associated events such as `DOMAttrModified`, `DOMCharacterDataModified` ... in https://bugzilla.mozilla.org/show_bug.cgi?id=1963043
(These are behind a pref that is now false).
This marks the API as removed. The events do not appear to have any BCD entries so no changes there.
Related docs work can be tracked in https://github.com/mdn/content/issues/39825
=> Firefox 140 removes `MutationEvent`

css/types/sibling-count.json, css/types/sibling-index.json
The data was collected from Chrome 137 (stable) and 138 (beta) using new
tests in the collector:
https://github.com/openwebdocs/mdn-bcd-collector/pull/2453
=> Chrome 138 adds CSS `sibling-count()` and `sibling-index()`

http/headers/Set-Cookie.json
Added  version_removed: "18.5" in browser-compat-data/http/headers/Set-Cookie.json for Safari based on issue #27023
=> Safari 18.5 disabled Partitioned Cookies (CHIPS)

html/elements/select.json
Fixes `<hr>` in `<select>`  has no support in firefox android and added the bugzilla tracking issue link.
https://bugzil.la/1867045
fixes #27040
=> Firefox Android doesn't render `<hr>` in `<select>`

css/properties/field-sizing.json
`field-sizing`-CSS-property has been added to Safari Technology Preview 220 according to issue <https://webkit.org/b/264720>, which has been confirmed manually.
ran `npm i && npm run test` on my localhost
=> Safari TP supports `field-sizing` CSS property

lint/linter/test-versions.ts
Extends the cut off date range from 4 to 5 years ago.
Fixes https://github.com/mdn/browser-compat-data/issues/23991.
Similar to:
- https://github.com/mdn/browser-compat-data/pull/25963
=> Bump range cutoff date to five years ago

css/properties/break-after.json, css/properties/break-before.json
Mark `break-before/after: avoid` as not supported by Firefox and Safari, like `page-break-before/after: avoid`.
The MDN BCD Collector tests are passing, but these are false positives.
See:
- https://bugzilla.mozilla.org/show_bug.cgi?id=1972340
- https://bugs.webkit.org/show_bug.cgi?id=294559
Fixes https://github.com/mdn/browser-compat-data/issues/22723.
Collector PR:
- https://github.com/openwebdocs/mdn-bcd-collector/pull/2476
=> Firefox/Safari don't support `break-before/after: avoid`

webextensions/api/action.json, webextensions/api/browserAction.json, webextensions/api/commands.json, webextensions/api/declarativeNetRequest.json, webextensions/api/dom.json, webextensions/api/i18n.json, webextensions/api/runtime.json, webextensions/api/scripting.json, webextensions/api/storage.json, webextensions/api/tabs.json, webextensions/api/webRequest.json, webextensions/manifest/commands.json, webextensions/manifest/content_scripts.json, webextensions/manifest/externally_connectable.json, webextensions/manifest/incognito.json, webextensions/manifest/optional_permissions.json, webextensions/manifest/options_ui.json, webextensions/manifest/permissions.json, webextensions/manifest/web_accessible_resources.json
Went through and updated all web extension BCD data for Safari, adding new Safari 26 release support and correcting items for older releases that were wrong or missing.
Cross-referenced Safari release notes and bugs.
None
=> Update web extension data for Safari 26 and correct versioning for some older releases.

api/Document.json
`Document.writeln()` is `Document.write()` with a line break added to the end of the input string. Since `Document.write()` is deprecated for a whole bunch of reasons in the spec, the same status should apply to `writeln()`.
Fell out of docs work in https://github.com/mdn/content/pull/37952
=> Mark `Document.writeln()` as deprecated

svg/global_attributes.json
Chrome 137+ supports setting an SVG `transform` attribute on the root `<svg>` element. See https://chromestatus.com/feature/6129368025530368 for details.
This PR adds a data point for the new support.
BTW, from tests it looks like Firefox supports this as well, but I don't know the version number, so I've left it as `false` for now.
=> Chrome 137 support for SVG transform on `<svg>` root

api/XMLSerializer.json
The interface has been removed from the DOMParsing spec in https://github.com/w3c/DOM-Parsing/commit/91273610d3bb07dd555dcc84a49e2e4d0ef12851 and moved to the html standard (https://github.com/whatwg/html/pull/11077).
=> XMLSerializer moved into HTML spec

css/properties/field-sizing.json, svg/elements/feImage.json, svg/elements/image.json, svg/elements/script.json
- Added `fetchpriority` support for the foillowing SVG elements:
- `<feimage>`
- `<image>`
- `<script>`
- Firefox is the first browser to support this feature, I have tested in:
- Firefox Beta 140
- Firefox nightly 141.0a1 (2025-06-17)
- Tested with the following code pens:
- [svg feimage element priority](https://codepen.io/CodeRedDigital/pen/jEPpowN)
- [svg image element priority](https://codepen.io/CodeRedDigital/pen/KwpBYYY)
- [SVG Script priority](https://cdpn.io/pen/debug/YPXjWwb)
- [Bugzill issue #1847712](https://bugzil.la/1847712)
- [Content PR]()
- [Firefox Release note PR](https://github.com/mdn/content/pull/39981)
=> Firefox 140 beta adds `fetchpriority` for some SVG elements

javascript/builtins/Math.json
I don't see it working in Safari 26 beta or in Safari TP. I think it is not enabled by default yet.
=> Safari doesn't support Math.sumPrecise

api/GPUOutOfMemoryError.json
The collector updates for Safari 26 were a bit tricky because the beta version doesn't yet present itself as version 26. I missed this file to correct the version to 26. Follow up to https://github.com/mdn/browser-compat-data/pull/27087
=> Safari 26 adds `GPUOutOfMemoryError`, not Safari 18.5

api/HTMLInputElement.json, html/elements/input.json
Firefox 141 supports webkitdirectory
https://bugzilla.mozilla.org/show_bug.cgi?id=1887878
=> Firefox Android 141 supports `webkitdirectory` on `<input>`

http/headers/Content-Security-Policy.json
Add support data for CSP script-src trusted-types-eval keyword
Manually tested in iOS 26 beta using a WPT https://wpt.live/content-security-policy/script-src/script-src-trusted_types_eval_with_require_trusted_types_eval.html
=> Add support data for CSP script-src trusted-types-eval keyword

api/SnapEvent.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `SnapEvent` member of the `SnapEvent` API. Data comes from https://github.com/mdn/browser-compat-data/pull/26687#discussion_r2142486603.
=> Chrome 138 supports SnapEvent constructor behind pref

.github/workflows/system-file-changes.yml
Fixes the `system-file-changes` workflow to use a fine-grained access token (PAT) to read the team membership.
Noticed in https://github.com/mdn/browser-compat-data/actions/runs/15910632781/job/44876768775?pr=23958 that it fails, although the PR creator is BCD owner.
=> ci(system-file-changes): use PAT to read team membership

http/headers/Link.json
Chrome 105 removed http.headers.Link.blocking
Once this lands, the BCD feature will be removed in https://github.com/mdn/browser-compat-data/pull/27145.
See: https://github.com/mdn/browser-compat-data/pull/27145#discussion_r2167768759
=> Chrome 105 removed http.headers.Link.blocking

.github/workflows/pr-rebase-needed.yml
Improves the `pr-rebase-needed` workflow by separating workflow runs triggered by push events into different concurrency groups per branch.
Previously, any push to any origin branch was cancelling the current workflow run for the main branch.
=> ci(pr-rebase-needed): use branch for push concurrency group

scripts/update-browser-releases/edge.ts, scripts/update-browser-releases/utils.ts
Derive Edge beta/nightly/planned release from stable version, to avoid a stable release without a beta release:
- Beta version = Stable version + 1
- Nightly version = Stable version + 2
- Planned version = Stable version + 3
See: https://github.com/mdn/browser-compat-data/pull/27158#discussion_r2171109673
When the Edge Beta release is promoted to Stable, the Edge Dev release is not necessarily promoted to Beta yet.
=> Derive Edge beta/nightly/planned release from stable version

css/types/progress.json
Chrome 138 adds the CSS [`progress()`](https://drafts.csswg.org/css-values-5/#progress) function — see https://chromestatus.com/feature/5112558941634560.
This PR adds a data point for the `progress()` function.
=> Chrome 138 adds CSS `progress()` function

http/headers/Link.json
This removes `http.headers.Link.blocking`.
Unfortunately the tests for this were removed from WPT in https://github.com/web-platform-tests/wpt/pull/34083. I've filed a draft PR with these reverted in https://github.com/web-platform-tests/wpt/pull/53403 to demonstrate lack of support, but results are yet to appear on wpt.fyi as of writing.
Support for `render=blocking` on a `link` element was removed in https://github.com/whatwg/html/commit/448f240bb8a9af2cab512e6bdee8662f185b97ae, and https://github.com/whatwg/html/commit/0ea88cf472012c7f59dc9a836da1382567a5b13e clarified which `link` things were also valid in the `Link` header.
These were both removed from Chromium in https://github.com/chromium/chromium/commit/1372f2379a46b86177b5537b5be77a00c83c6bda, and the earliest tag containing …
=> Remove http.headers.Link.blocking

lint/linter/test-versions.ts
Bump range cutoff date to 2025-05-19, which is the earliest date possible, due to [these Chrome 83 ranges](https://github.com/search?q=repo%3Amdn%2Fbrowser-compat-data+%2F%22chrome%22%3A+%5C%7B%5Cn%5Cs*%22version_added%22%3A+%22%E2%89%A483%22%2F&type=code) (released 2025-05-19).
=> Bump range cutoff date to 2020-05-19

api/WGSLLanguageFeatures.json
Chrome 123 adds support for the `pointer_composite_access` WGSL extension. See https://developer.chrome.com/blog/new-in-webgpu-123#syntax_sugar_for_dereferencing_composites_in_wgsl.
This PR adds a data point for this support.
=> Chrome 123 supports `pointer_composite_access` WGSL extension

api/HTMLElement.json
FF141 supports the `source` option to [`HTMLElement.showPopover()`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/showPopover) and [`HTMLElement.togglePopover()`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/togglePopover), and the `force` option to  [`HTMLElement.togglePopover()`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/togglePopover) in https://bugzilla.mozilla.org/show_bug.cgi?id=1936411
This adds the features.
Related docs work can be tracked in https://github.com/mdn/content/issues/40027
=> FF141 adds HTML popover source + force option

api/HTMLElement.json
This was the commit that added support for them: https://github.com/WebKit/WebKit/commit/bd7649ea03d308c55de707c6cf8488dc552d43f9
Manually tested here: https://jsfiddle.net/ktmfjn97/1/
=> Safari 26 adds beforetoggle / toggle events on dialog elements

webextensions/api/bookmarks.json, webextensions/api/browsingData.json, webextensions/api/cookies.json, webextensions/api/devtools.json, webextensions/api/downloads.json, webextensions/api/runtime.json, webextensions/api/sidebarAction.json, webextensions/api/tabs.json, webextensions/api/windows.json
This change adds missing `__compat` objects to the path of several web extension API features. 
This was done for two reasons:
- The definition of the scheme of states that "identifiers without __compat aren't necessarily features". The items affected in this PR are features.
- It resolves some presentation issues. For example, take the example of `browsingData.DataTypeSet`:
- In the BCD data presented about [`browsingData`,](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browsingData#browser_compatibility) `DataTypeSet` is not listed.
- In the BCD about [`DataTypeSet`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browsingData/DataTypeSet#browser_compatibility) the properties are listed, however, the first property has a link back …
=> webextension.api add missing `__compat` objects

api/URLPattern.json
https://github.com/denoland/deno/releases/tag/v1.46.0
=> Deno 1.46 supports URLPattern.hasRegExpGroups and ignoreCase option

webextensions/api/downloads.json
The initial implementation contained an error, resulting in the two properties being returned as undefined. This issue was fixed in [Bug 1305663](https://bugzilla.mozilla.org/show_bug.cgi?id=1305663) Support downloadItem.byExtensionId
Fixes #27210
=> webextensions.api.downloads.DownloadItem byExtensionId and byExtensionName fixed in FF 69

api/VideoDecoder.json, api/VideoFrame.json
Chrome 138 adds support for the WebCodecs API `flip` and `rotate` options. See https://chromestatus.com/feature/5128855343595520
@Elchi3 already added docs for these features, and the BCD for `VideoFrame.flip` and `VideoFrame.rotation` was added in https://github.com/mdn/browser-compat-data/pull/26937.
However, I thought it might be helpful to add data points for those options being available in the `VideoFrame()` constructor, `VideoDecoder.configure()`, and `VideoDecoder.isConfigSupported()`. This PR adds those things.
=> Chrome 138 data for Web Codecs flip and rotate options

api/MediaStreamTrack.json
…ettings subfeature
Previously, I tried to add data for `MediaTrackSettings.screenPixelRatio` in its own `MediaTrackSettings` file, but then learned that we don't do BCD for dictionaries only. You can see the following for the backstory:
- https://github.com/mdn/browser-compat-data/pull/27092
- https://github.com/mdn/browser-compat-data/issues/27119
This PR takes a different approach, suggested by @wbamberg, which instead adds a sub-data point to `MediaStreamTrack.getSettings()` to represent `screenPixelRatio`. This makes sense, as `getSettings()` returns a `MediaTrackSettings` object.
What do we think of this approach?
=> Chrome 136 returns MediaTrackSettings.screenPixelRatio

svg/elements/svg.json
This PR updates and corrects version values for Microsoft Edge for the `svg` SVG element. https://github.com/mdn/browser-compat-data/pull/27177/files/61f57ef4e859ed2652834f6a49d194a4611e1204#r2178277143
=> Update Edge data for svg SVG element

css/properties/flex-direction.json
This PR updates and corrects version values for Firefox and Firefox Android for the `flex-direction` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.13.3).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/flex-direction
=> Firefox 22 added `flex-direction` CSS property

css/selectors/-moz-list-bullet.json
This PR updates and corrects version values for Firefox and Firefox Android for the `-moz-list-bullet` CSS selector. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.13.3).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/selectors/-moz-list-bullet
=> Firefox 1 added `::-moz-list-bullet` CSS pseudo-element

css/selectors/-moz-list-number.json
This PR updates and corrects version values for Firefox and Firefox Android for the `-moz-list-number` CSS selector. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.13.3).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/selectors/-moz-list-number
=> Firefox 1 added `::-moz-list-number` CSS pseudo-element

css/selectors/-moz-first-node.json
This PR updates and corrects version values for Firefox and Firefox Android for the `-moz-first-node` CSS selector. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.13.3).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/selectors/-moz-first-node
=> Firefox 55 added `:-moz-first-node` CSS pseudo-class

css/selectors/-moz-last-node.json
This PR updates and corrects version values for Firefox and Firefox Android for the `-moz-last-node` CSS selector. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.13.3).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/selectors/-moz-last-node
=> Firefox 55 added `:-moz-last-node` CSS pseudo-class

api/RTCStatsReport.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `RTCStatsReport` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.13.3).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/RTCStatsReport
=> Safari 11 added `frames{De,En}coded` to RTCStatsReport API

webassembly/jspi.json
This PR updates and corrects version values for Microsoft Edge for the `jspi` WebAssembly feature. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.13.4).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/webassembly/jspi
=> Edge 137 also supports `jspi` WebAssembly feature

webassembly/mutable-globals.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `mutable-globals` WebAssembly feature. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.13.3).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/webassembly/mutable-globals
=> Safari 13.1 added `mutable-globals` WebAssembly feature

html/elements/rtc.json
This PR updates and corrects version values for Chrome and Safari for the `rtc` HTML element. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.13.3).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/html/elements/rtc
=> Chrome 47 / Safari 8 added `<rtc>` HTML element

css/properties/color-interpolation.json
This PR updates and corrects version values for all browsers for the `sRGB` member of the `color-interpolation` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.13.3).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/color-interpolation/sRGB
=> Chrome 1 / Firefox 3 / Safari 4 added CSS `color-interpolation: sRGB`

svg/elements/view.json
I identified an inconsistency in our BCD status for `svg.elements.svg.zoomAndPan` and that of the `view` element. In fact, both are standardized [SVG 1.1](https://www.w3.org/TR/SVG11/linking.html#ViewElement) and removed in [SVG 2](https://svgwg.org/svg2-draft/linking.html#ViewElement), so they should either be both standard or non-standard.
=> Mark svg.elements.view.zoomAndPan as standard track

api/WebTransport.json, api/WebTransportBidirectionalStream.json, api/WebTransportDatagramDuplexStream.json, api/WebTransportError.json, api/WebTransportReceiveStream.json, api/WebTransportSendStream.json
Notes Safari 18.3.1ish's support for WebTransport behind its "WebTransport" Feature Flag.
- Unfortunately, https://wpt.fyi/results/webtransport?label=experimental&label=master&aligned doesn't appear to be running Safari with the WebTransport Feature Flag set yet, so I had to get creative to test support
- Tested Safari 18.5 (not TP) functionality with https://wt-ord.akaleapi.net/echo/ and https://wt-ord.akaleapi.net/webcodecs-echo/ (minus visual frames for unrelated reasons), as well as a [custom fiddle](https://jsfiddle.net/jib1/2p6jceq4/) for a few details
- Relied on 18.3.1 BCD collector data in https://github.com/mdn/browser-compat-data/issues/26151#issuecomment-2801690212
Fixes #26151. cc @ekinnear
=> Safari 18.4 supports WebTransport behind a flag

html/elements/input/range.json
This PR updates and corrects version values for Firefox and Firefox Android for the `type_range.vertical_orientation` member of the `input` HTML element. The data comes from manual testing, running test code through BrowserStack, SauceLabs, custom VMs and/or locally.
Test Code:
```
<input id="foo" type="range" orient="vertical" />
```
=> Firefox 23 started supporting vertical HTML range inputs

css/properties/overflow-y.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `auto` member of the `overflow-y` CSS property. This sets the downstream browser(s) to mirror from their upstream counterpart.
=> Safari 6 supported CSS `overflow-y: auto` with alt name

css/properties/transform-box.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `transform-box` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.13.3).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/transform-box
=> Safari 11 added CSS `transform-box: {border,fill,view}-box`

http/headers/Set-Cookie.json
Noting the Partitioned Set-Cookie attribute is enabled in the next version of Firefox.
https://bugzilla.mozilla.org/show_bug.cgi?id=1931488
=> Add support for Partitioned cookie attribute in upcoming Firefox 

css/properties/resize.json
Currently, Firefox/Android shows resizable control with the `resize` property, but it doesn't work well due to bug 1618678 and bug 1776834.
So this PR updates the `resize` property support in Firefox/Android.
=> Update CSS resize support for Firefox/Android

api/HighlightRegistry.json
Chrome 140 adds support for the [`HighlightRegisty.highlightsFromPoint()`](https://drafts.csswg.org/css-highlight-api-1/#dom-highlightregistry-highlightsfrompoint) method; see https://chromestatus.com/feature/4552801607483392.
I've tested it in Chrome 140, and it works fine; Chrome 139 throws `Uncaught TypeError: CSS.highlights.highlightsFromPoint is not a function`.
=> Chrome 140 support for HighlightRegisty.highlightsFromPoint()

api/CredentialsContainer.json
Chrome has added several [FedCM](https://developer.mozilla.org/en-US/docs/Web/API/FedCM_API) features that we are missing from BCD and/or MDN. This PR adds BCD for the features we were missing compat data for.
The features are:
- Support for multiple IdPs in a single `get()` call, as specified inside the `providers` array, added in Chrome 136: https://chromestatus.com/feature/5067784766095360. I've added a data point for this.
- The above ChromeStatus entry also includes the `IdentityCredential.configURL` (if you look at the [associated spec changes](https://github.com/w3c-fedid/FedCM/pull/686/files#diff-40cc3a1ba233cc3ca7b6d5873260da9676f6ae20bb897b62f7871c80d0bda4e9R445)), but this is already in BCD.
- `IdentityCredential.disconnect()`, added in Chrome 122: …
=> Chrome 122-136 FedCM features

api/BaseAudioContext.json
I recently [documented](https://github.com/mdn/content/pull/40379) the `BaseAudioContext.state` property `interrupted` value, and [added a data point](https://github.com/mdn/browser-compat-data/pull/27304) for it to BCD.
During the docs review, @Elchi3 noticed that Safari already supported this value, from Version 9. 
This PR updates the support data to reflect that.
=> Safari 9 support for BaseAudioContext.state interrupted value

javascript/builtins/Intl/Locale.json
Now supported:
```js
const ja = new Intl.Locale("ja-Jpan-JP-hepburn");
console.log(ja.variants);
// hepburn
```
- __Spec:__ https://tc39.es/ecma402/#sec-Intl.Locale.prototype.variants
- __Bugzilla:__ [1970161](https://bugzilla.mozilla.org/show_bug.cgi?id=1970161)
- __Pen:__ https://codepen.io/bsmth/pen/gbarbKd?editors=0011
Tested `false` entries manually.
=> Firefox 141 supports Intl.Locale.prototype.variants

docs/data-guidelines/browsers.md
This adds some details that reflects contemporary considerations, especially the increasing automation of browser and support data.
This came up in today's BCD call in regards to how or whether Bun qualifies for inclusion. The current guideline doesn't really reflect, for example, how we scrape release information or rely on the collector for accuracy.
- https://github.com/mdn/browser-compat-data/issues/18484
- https://github.com/mdn/browser-compat-data/pull/23440
- https://github.com/mdn/browser-compat-data/issues/7238
- https://github.com/mdn/browser-compat-data/pull/7244
=> Revise "Addition of browsers" data guideline

css/types/anchor-size.json, css/types/anchor.json
Fixes https://github.com/mdn/browser-compat-data/issues/27332
=> Safari 26 supports anchor() + anchor-size()

api/RTCStatsReport.json
FF144 adds support for the following `inbound-rtp` stats in https://bugzilla.mozilla.org/show_bug.cgi?id=1926622:
- (new features) pauseCount, totalPausesDuration, freezeCount, totalFreezesDuration, estimatedPlayoutTimestamp, framesAssembledFromMultiplePackets, totalAssemblyTime
- (Existing features) keyFramesDecoded, jitterBufferTargetDelay/jitterBufferMinimumDelay
This adds the features.
Related docs work can be tracked in https://github.com/mdn/content/issues/40478
=> Ff142 inbound-rtp stats

api/ToggleEvent.json
Chrome 140 adds support for the `ToggleEvent.source` property. See https://github.com/mdn/content/issues/39723 for details.
This PR adds a data point for it. I appreciate it'll probably be added in a Chrome beta collection run soon, but I wanted to get it added as I am about to document it.
=> Chrome 140 ToggleEvent.source

api/Selection.json
As discussed in https://github.com/mdn/browser-compat-data/pull/27369/#discussion_r2229826145 and https://bugzilla.mozilla.org/show_bug.cgi?id=1903870#c13 
These two tests show that Chrome supports accepts_nodes_in_shadow_trees for collapse, extend, setBaseAndExtent of the selection API (I bisected to v137):
- https://wpt.live/selection/shadow-dom/tentative/Selection-collapse-and-extend.html - Chrome 137
- https://wpt.live/selection/shadow-dom/tentative/Selection-getComposedRanges-range-update.html - Chrome 137
=> Chrome 137 supports accepts_nodes_in_shadow_trees for associated methods (setBaseAndExtent, collapse etc)

html/elements/object.json
- Added `version_removed` for the `codebase` attribute of the `<object>` element in Firefox 142
- Tested with this [code pen](https://codepen.io/CodeRedDigital/pen/GgpNgbM?editors=1000) in:
- Firefox Stable (141) - works
- Firefox Beta (142.0b3) - does not work as expected
- Firefox Developer (142.0b3) - does not work as expected
- Firefox Nightly (143.0a1) - does not work as expected
- Via Browserstack:
- Chrome (62) - does not work as expected
- Safari (13.1) - does not work as expected
- Edge (80) - does not work as expected
- Opera (25) - does not work as expected
- [Firefox Release PR](https://github.com/mdn/content/pull/40557)
=> added version_removed for FF codebase attr for object element

api/Animation.json
[`Animation.commitStyles()`](https://developer.mozilla.org/en-US/docs/Web/API/Animation/commitStyles#examples) was modified in spec https://github.com/w3c/csswg-drafts/pull/11881 as a result of this discussion https://github.com/w3c/csswg-drafts/issues/5394#issuecomment-2954654330
I'm [clarifying](https://bugzilla.mozilla.org/show_bug.cgi?id=1973203#c8) but my understanding is that that the impact of the change is that you no longer need to specify a `fill: 'forwards'` on your animation in order to be able to commit the style after the animation has finished or been removed; instead the styles are captured at the end of the active stage.
My belief is that this is due to the first note in the spec https://drafts.csswg.org/web-animations-1/#dom-animation-commitstyles - essentially he …
=> FF142 Animation.commitStyles() - does not require fill: forwards

scripts/build/mirror.ts
This PR updates the mirroring script to check if the end result of `version_removed` is `false`, and if so, delete the key so that it is not generated in the final build output.  Fixes #27437.
=> Ensure that version_removed: false does not get generated by mirroring

api/RTCRtpSender.json
FF142 adds support for the dictionary property `RTCRtpEncodingParameters.codec` in https://bugzilla.mozilla.org/show_bug.cgi?id=1894137
This is used when setting encodings in [`RTCRtpSender.setParameters(parameter.encodings)`](https://developer.mozilla.org/en-US/docs/Web/API/RTCRtpSender/setParameters#encodings) and [`RTCPeerConnection.addTransceiver(sendencodings)`](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/addTransceiver#sendencodings), and returned in [`RTCRtpSender/getParameters()`](https://developer.mozilla.org/en-US/docs/Web/API/RTCRtpSender/getParameters#encodings) (`encodings.codec`).
This updates the `setParameters()`  - encodings - subfeature on the sender. The `getParameters()` and `RTCPeerConnection.addTransceiver` features don't go down to the same …
=> FF142 RTCRtpSender.setParameters() encodings.codec param supported

css/properties/alignment-baseline.json
Two missing sub features for the alignment-baseline property as discovered by the mdn-bcd-collector. Assuming the support for these is the same as the existing sub features. 
Spec: https://svgwg.org/svg2-draft/text.html#AlignmentBaselineProperty
=> Add missing sub features for alignment-baseline

css/properties/hyphens.json
Adds missing sub features for the CSS hyphens property as found by the mdn-bcd-collector. Assumes support shipped with the initial implementation.
=> Add missing sub features for CSS hyphens property

css/properties/color-scheme.json
We only need one sub feature for the `only` keyword here.
=> Consolidate `only`  keyword into a single sub feature of color-scheme

package.json, scripts/build/index.ts
This PR adds a new `./types` subpath export to the generated manifest. It separates the `types` and default fields to better support tools and consumers that reference type definitions directly.
See Node.js package exports documentation: https://nodejs.org/api/packages.html#exports
Fixes failing tests at https://github.com/microsoft/TypeScript-DOM-lib-generator/pull/2104
=> feat(manifest): add ./types export with separate type and default entries

api/HTMLDialogElement.json
the "dialog light dismiss behavior" (aka [`closedby` property](https://developer.mozilla.org/en-US/docs/Web/API/HTMLDialogElement/closedBy)) has a Webkit Bugzilla URL implementation URL.
=> docs: added Safari implementation bugzilla URL

api/Element.json
Added `Element.scrollIntoView()` `container` option
Chrome 140 : https://cr-status.appspot.com/feature/5100036528275456?gate=5140738792488960
No tracking issues for other browser for now
=> Add scrollIntoView container option

api/Document.json, api/Element.json, api/ShadowRoot.json
In https://github.com/mdn/browser-compat-data/pull/27522, I overstated the context in which the bug applies. This corrects the scope of the note.
- A correction to https://github.com/mdn/browser-compat-data/pull/27522
- https://github.com/mdn/browser-compat-data/pull/27392
- https://github.com/web-platform-dx/web-features/pull/3200
=> Further clarify notes for Safari `setHTMLUnsafe()` and friends

css/types/corner-shape-value.json, css/types/superellipse.json
Chrome 139 adds support for the [`corner-shape`](https://drafts.csswg.org/css-borders-4/#corner-shaping) property, and its related shorthands and longhands. See https://chromestatus.com/feature/5357329815699456.
The properties have already been added to BCD by the collector, but the types that it can take as values have not.
This PR adds data for the types.
Note that I have included two data points for `superellipse()` — one for the function itself, and one for the use of `superellipse()` as a `<corner-shape-value>`. I thought this was a good idea in case `superellipse()` has more parameter options added, or is used as a possible value for other properties in the future.
=> Chrome 139 corner-shape types

webextensions/api/action.json, webextensions/api/browserAction.json
Adds details for the addition of the `browser_action.onUserSettingsChanged` event. Addresses the dev-doc-needed requirements of [Bug 1828220](https://bugzilla.mozilla.org/show_bug.cgi?id=1828220) Implement onUserSettingsChanged event.
See https://github.com/mdn/content/pull/40488 for details of the documentation changes.
=> Bug-1828220 add browser_action.onUserSettingsChanged event

scripts/diff-flat.ts
Changes the `diff:flat` script to fetch the `/merge` tip of the PR, rather than the `/head` tip.
After merging https://github.com/mdn/browser-compat-data/pull/25352, the PR Review Companion started failing most of the time.
The workflow uses `diff:flat` to compare the PR tip with the `main` branch. For this, it needs the merge base, **but** the checkout by default doesn't fetch any history, so the merge base was likely not fetched unless the PR was based on the latest `main` commit.
Compare the _result_ of merging the PR into the `main` branch, with the `main` branch.
Note: Tested this with a local shallow clone of BCD.
=> fix(scripts/diff-flat): fetch `pull/*/merge`, not `pull/*/head`

http/headers/Integrity-Policy-Report-Only.json, http/headers/Integrity-Policy.json
This follows on from #27530, adding new information from developers.
FF142 adds support for [Integrity-Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/Integrity-Policy) and [Integrity-Policy-Report-Only](https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/Integrity-Policy-Report-Only) on nightly in https://bugzilla.mozilla.org/show_bug.cgi?id=1976656 [behind pref `security.integrity_policy.enabled` enabled in nightly).
BUT, reporting endpoints are not plugged in as per https://bugzilla.mozilla.org/show_bug.cgi?id=1976656#c14 - so I have marked the support as partial and added a note.
In addition, this is only in one proper release so it is experimental still. 
In addition, Firefox has implemented support for `style` as a blocked-destination …
=> FF142 Integrity-Policy support partial and style

api/CompositionEvent.json, css/selectors/details-content.json
The @openwebdocs [BCD collector project](https://github.com/openwebdocs/mdn-bcd-collector) v10.14.0 found new features shipping in Firefox 143 beta which was released today. Currently, the collector covers about 90% of BCD, so the following list might not be exhaustive. Also, if a feature is in Firefox Nightly only, it is not considered here.
With this PR, BCD considers the following 18 features as shipping in Firefox 143:
- api.CompositionEvent.locale ([removal](https://bugzilla.mozilla.org/show_bug.cgi?id=1700969))
- css.selectors.details-content ([bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1941406))
Updated in other PRs:
- webdriver.bidi.network.addDataCollector
- webdriver.bidi.network.addDataCollector.collectorType_parameter
- …
=> Updates for Firefox 143 beta

css/types/sibling-count.json, css/types/sibling-index.json
CSS `sibling-count()` and `sibling-index()` is missing the webkit `impl_url`. This PR adds this link.
=> Add webkit impl_url to `sibling-count()` and `sibling-index()`

css/properties/white-space.json
=> Add Chrome/Safari impl url for CSS `white-space` in SVG

api/KeyboardEvent.json
Updated KeyboardEvent.repeat support on chrome: previously was partial support, now full support.
Tested in Chrome on Windows, could not replicate stated bug.
Ref [bug 40940886](https://crbug.com/40940886)
Fixes #27634
=> Update `KeyboardEvent.repeat` compat on chrome

css/selectors/closed.json
This was dropped from the specification. Developers shouldn't use it and it has unshipped from all browsers anyway.
- https://github.com/w3c/csswg-drafts/pull/11326
- https://github.com/web-platform-dx/web-features/pull/3238
=> De-standardize `:closed` pseudo-class

api/Document.json
It is defined by HTML and is related to contenteditable: https://html.spec.whatwg.org/multipage/interaction.html#making-entire-documents-editable:-the-designmode-idl-attribute
It's not clear if it should be part of the contenteditable feature, so just untag it for now.
=> Remove `document.designMode` from the DOM feature

css/selectors/details-content.json
Mark safari support for `::details-content` as partial.
https://wpt.live/html/rendering/the-details-element/details-pseudo-elements-004.html - Tested using this
Fixes #27620
=> Mark Safari `::details-content` support as partial

javascript/statements.json
Set the compatibility data for NodeJS to `24.0.0` in the `using` statement section.
1. https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V24.md#v8-136
2. https://github.com/nodejs/node/pull/58154
3. https://github.com/nodejs/node/pull/58296
Closes #27631
=> NodeJS 24+ supports `using` statement

api/Document.json
Add compatibility data of mutable `api.Document.adoptedStyleSheets`
Compatibility info for Opera Android is unknown. (Removing the property can't pass test)
Compatibility info for Safari < 16.5 is unknown.
Fixes #26918
=> Chrome 99 allowed mutating `Document.adoptedStyleSheets`

css/properties/overlay.json
This PR adds a link point to tracking ticket on Bugzilla within `css/properties/overlay.json`.
No tests have done; discussed in the issue.
Fixes mdn#27678 .
=> Add FF impl_url for CSS `overlay` property

browsers/bun.json, scripts/update-browser-releases/bun.ts
This PR makes changes to the scripts/update-browser-releases/bun.ts file as per comments here: https://github.com/mdn/browser-compat-data/pull/27682#discussion_r2303425469
Exact changes:
- Bun's release notes URL should be our blog
- Remove unnecessary/spammy console.logs which pollute the output in automated pull request comments
The `release_notes` values were automatically updated without changes to this script, because I made changes to https://bun.com/versions.json
=> Bun's release notes should come from the blog, not GitHub

css/selectors/host-context.json
- fix https://github.com/mdn/content/issues/38960
Spec guys have dropped the `:host-context()`.
- https://github.com/w3c/csswg-drafts/issues/1914#issuecomment-2737310093
=> Mark css.selectors.host-context deprecated

webextensions/api/browserSettings.json
Add to the browser compatibility data for `browserSetting.verticalTabs` introduced by [Bug 1946600](https://bugzilla.mozilla.org/show_bug.cgi?id=1946600) Add a new browserSetting property that determines whether vertical tabs are enabled.
Related MDN content changes in TBC
=> Bug-1946600 addition of webextension.api.browserSetting.verticalTabs

webextensions/api/scripting.json
Update webextensions.api.scripting.executeScript - injectImmediately support re [Chrome documentation](https://developer.chrome.com/docs/extensions/reference/api/scripting#type-ScriptInjection).
See issue #27539
Fixes #27539
=> Issue 27539 webextensions.api.scripting.executeScript - injectImmediately requires Chromium >= 102

webextensions/api/tabs.json
Documents that change is made in [Bug 1960011](https://bugzilla.mozilla.org/show_bug.cgi?id=1960011) Filter tabs.onUpdated events by cookieStoreId.
Related content changes in https://github.com/mdn/content/pull/40838.
=> Bug-1960011 adds tabs.onUpdated.filter.cookieStoreId

html/elements/template.json
According to Apple's bug tracking system, this is when the content attributes landed.
The JS properties were added afterwards in Safari 18 (which MDN correctly reflects).
* shadowrootdelegatesfocus content attribute was added with the initial implementation of declarative shadow DOM in 16.4: https://github.com/WebKit/WebKit/commit/46837e56d6f57f7e52bf92c9534cc7683909eee5
* shadowrootclonable content attribute: https://github.com/WebKit/WebKit/commit/79d2dec92caef6f7df33125ab34bd70e36c982c2
* shadowrootserializable content attribute & JS property: https://github.com/WebKit/WebKit/commit/de64e62a2a5041b0d59b985feba7e080993c36b8
* shadowrootdelegatesfocus & shadowrootclonable JS properties: https://github.com/WebKit/WebKit/commit/db0669a6fa034ab98e120208f72fd232948b1fcc
=> Fix shadowrootclonable, shadowrootdelegatesfocus & shadowrootserializable Safari compat data

api/CredentialsContainer.json
This was added in https://github.com/mdn/browser-compat-data/pull/21721 
> The Error API, which mainly manifests as useful properties of the return error object when a FedCM get() call rejects.
What the FedCM Error API really is, though, is `IdentityCredentialError` and we already have compat data for that.
Remove this entry is it only appears without further explanation on https://developer.mozilla.org/en-US/docs/Web/API/CredentialsContainer/get#browser_compatibility. It's not even in web-features yet, either.
I'm creating MDN docs for `IdentityCredentialError` in https://github.com/mdn/content/pull/40986.
=> Remove 'Error API' feature from `CredentialsContainer.get`

webextensions/api/types.json
Adds data for the clear, get, and set methods of webextensions.api.types.BrowserSetting. This enables compatibility data to be correctly displayed on MDN.
Fixes #26521
Related MDN content change in https://github.com/mdn/content/pull/40989.
=> Add member data to webextensions.api.types.BrowserSetting for Issue 26521

webextensions/api/contentScripts.json, webextensions/api/scripting.json, webextensions/manifest/content_scripts.json
Add details of support added in Firefox 144 for the ability to determine the precedence of injected CSS through the  [`"content_scripts"` manifest key](http://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/content_scripts), in [scripting.registerContentScripts()](http://developer.mozilla.orgdeveloper.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/scripting/registerContentScripts) with the `cssOrigin` property on [scripting.RegisteredContentScript](http://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/scripting/RegisteredContentScript), and the `cssOrigin` property in [contentScripts.register](http://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/contentScripts/register). 
Addresses the dev-docs-needed …
=> Bug-1679997 CSS origin for registered content scripts

api/LargestContentfulPaint.json
Originally, cross-origin Largest Contentful Paint (LCP) images did not provide a `renderTime` and fell back to `loadTime` unless an HTTP `Timing-Allow-Origin` header was present.
This [was changed](https://github.com/w3c/largest-contentful-paint/issues/91) later to allow a coarsened-time cross-origin time and [Chrome implemented this in 133](https://github.com/mdn/browser-compat-data/pull/25735).
Since then Firefox added support for LCP with this addition, but this attributed was not updated at the same time despite Firefox supporting it.
Test case:
https://www.tunetheweb.com/experiments/lcp-cross-origin/
Note Firefox (like Chrome) returns a renderTime:
Cross-origin added: https://github.com/mdn/browser-compat-data/pull/225735
Firefox LCP added: …
=> Firefox 141 supports cross-origin LCP render time

.github/CODEOWNERS
Updates the (empty) `CODEOWNERS` file, establishing the following ownerships:
1. `/schemas/` is owned by BCD owners,
2. `/.github/workflows/` is owned by the MDN Engineering team.
The most important change is (2), which ensures that workflow changes undergo review by the team that is responsible for keeping our GitHub Actions secure.
=> chore(github): add code owners for schema/workflows

webextensions/api/storage.json
Fixes incorrect version number from https://github.com/mdn/browser-compat-data/pull/27442
=> Bug-1910669 fix to StorageArea.getKeys() Firefox implementation version

css/selectors/after.json, css/selectors/before.json
- Added firefox support for `::before::marker` and removed experimental
- Added firefox support for `::after::marker` and removed experimental
- Tested using the [`::before::marker`](https://developer.mozilla.org/en-US/docs/Web/CSS/::before#beforemarker_nested_pseudo-elements) and [`::after::marker`](https://developer.mozilla.org/en-US/docs/Web/CSS/::after#aftermarker_nested_pseudo-elements) examples in:
- Firefox Beta (143.0)
- Firefox Deveoper Edition (143.0b9)
- Firefox Nightly (144.0a1)
- [MDN Issue #40779](https://github.com/mdn/content/issues/40779)
- [Firefox Release note PR](https://github.com/mdn/content/pull/41146)
=> Firefox 143 adds `::{before,after}::marker` nested pseudo-elements

api/RTCDataChannel.json
FF144 makes [`RTCDataChannel`](https://developer.mozilla.org/en-US/docs/Web/API/RTCDataChannel) transferrable in https://bugzilla.mozilla.org/show_bug.cgi?id=1209163. This updates the feature.
Related docs work can be tracked in https://github.com/mdn/content/issues/41135
=> Firefox 144 makes `RTCDataChannel` transferable

api/Permissions.json
This PR updates and corrects version values for Safari (Desktop and iOS/iPadOS) for the `permission_push` member of the `Permissions` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.14.1).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/Permissions/permission_push
=> Safari 17 added `push` permission

api/FederatedCredential.json
Reverts mdn/browser-compat-data#27733
My fault. I didn't see that this comes via a mixin. 
If it had spec_urls I would have seen this.
=> Revert "Remove `iconURL` and `name` from `FederatedCredential`"

api/Fence.json
I don't think we need this sub feature.
The method itself has the same compatibility data. This new behavior might have come late but it shipped at the same time as the method itself. The spec for `setReportEventDataForAutomaticBeacons` describes the behavior already.
=> Remove `Fence.setReportEventDataForAutomaticBeacons.start_commit_eventType`

api/CSSStyleProperties.json, api/CommandEvent.json, api/Document.json, api/DocumentFragment.json, api/Element.json, api/GPUDevice.json, api/GPUQueue.json, api/HTMLButtonElement.json, api/Performance.json, api/PerformanceEventTiming.json, api/ViewTransition.json, css/properties/view-transition-class.json, css/properties/view-transition-name.json, css/selectors/view-transition-group.json, css/selectors/view-transition-image-pair.json, css/selectors/view-transition-new.json, css/selectors/view-transition-old.json, css/selectors/view-transition.json, javascript/builtins/Map.json, javascript/builtins/WeakMap.json
The @openwebdocs [BCD collector project](https://github.com/openwebdocs/mdn-bcd-collector) v10.15.0 found new features shipping in Firefox 144 beta which was released today. Currently, the collector covers about 90% of BCD, so the following list might not be exhaustive. Also, if a feature is in Firefox Nightly only, it is not considered here.
With this PR, BCD considers the following 47 features as shipping in Firefox 144:
- api.CSSStyleProperties
- api.CSSStyleProperties.cssFloat
- api.CommandEvent
- api.CommandEvent.CommandEvent
- api.CommandEvent.command
- api.CommandEvent.source
- api.Document.moveBefore
- api.Document.startViewTransition
- api.DocumentFragment.moveBefore
- api.Element.moveBefore
- api.GPUDevice.importExternalTexture.videoframe_source
- …
=> Updates for Firefox 144 beta

browsers/deno.json, javascript/builtins/AsyncDisposableStack.json, javascript/builtins/DisposableStack.json
Added missed supported versions for `DisposableStack` and `AsyncDisposableStack`
Node.js - https://github.com/nodejs/node/pull/58070
Deno - https://github.com/denoland/deno/issues/20821
=> Deno 2.2.10 + Node.js 24 support `DisposableStack`/`AsyncDisposableStack`

api/GPUDevice.json, api/GPUExternalTexture.json
We indicated that support for `GPUDevice.importExternalTexture()` and `GPUExternalTexture` was in FF141 in #27372.
According to https://bugzilla.mozilla.org/show_bug.cgi?id=1979100#c12 these were implemented behind a preference in 143, and shipped in FF144 in https://bugzilla.mozilla.org/show_bug.cgi?id=1983594. Given that FF144 is now in beta I've skipped the 143 and pref feature and just updated these two as released in FF144.
Related docs work can be tracked in https://github.com/mdn/content/issues/40774
=> Firefox 144 added `GPUDevice.importExternalTextures()`

css/properties/text-autospace.json
Discovered in the latest collector run.
See also https://groups.google.com/a/chromium.org/g/blink-dev/c/gwRvkPJ5pws/m/F3r-VeGoBAAJ where this talk about only shipping a subset.
=> Chrome doesn't support `text-autospace: {punctuation,replace}`

api/GPUQueue.json
Corrects the Firefox statement for `GPUQueue.onSubmittedWorkDone()`.
Support was set to 144 in https://github.com/mdn/browser-compat-data/pull/27902, but this was likely due to a newly introduced collector test, and the method was already supported from Firefox 141 (together with `GPUQueue` itself), as [confirmed by a Firefox developer](https://github.com/mdn/browser-compat-data/pull/27902#issuecomment-3299803882).
=> Firefox 141 supported `GPUQueue.onSubmittedWorkDone()`

api/HTMLElement.json, api/HTMLScriptElement.json, api/Node.json
On `HTMLScriptElement` you can access the `innerText` and `textContent` properties. We had documented these as inherited, but in fact they are duplicated and have their own IDL https://w3c.github.io/trusted-types/dist/spec/#dom-htmlscriptelement-innertext
This change makes that more clear, and makes the data more usable.
I'll be adding new docs for these too.
Related work can be tracked in https://github.com/mdn/content/issues/37518
=> Move Trusted Types subfeatures into `HTMLScriptElement`

api/ScreenOrientation.json
FF144 supports [`ScreenOrientation.lock()`](https://developer.mozilla.org/en-US/docs/Web/API/ScreenOrientation/lock) and [`ScreenOrientation.unlock()`](https://developer.mozilla.org/en-US/docs/Web/API/ScreenOrientation/unlock) in https://bugzilla.mozilla.org/show_bug.cgi?id=1983483
This updates the feature. 
Related docs work can be tracked in https://github.com/mdn/content/issues/41142
=> Firefox 144 ships `ScreenOrientation.{lock,unlock}()`

http/headers/Set-Cookie.json
FF142 added support for  `__Http-` and `__HostHttp-` cookie prefixes in https://bugzilla.mozilla.org/show_bug.cgi?id=1974979. FF143 renamed `__HostHttp-`  to  `__Host-Http-` in https://bugzilla.mozilla.org/show_bug.cgi?id=1982555.
This updates the subfeature twice, once with a partial implementation.
=> Firefox 143 supports `Set-Cookie` Http prefixes

css/properties/display.json, css/properties/transition-behavior.json
Duplicates `{content-visibility,display}.is_transitionable` subfeatures into `transition-behavior`.
Fixes https://github.com/mdn/browser-compat-data/issues/26155.
=> Duplicate `is_transitionable` features to `transition-behavior`

api/Document.json, api/Element.json, http/headers/Permissions-Policy.json
Following on from https://github.com/mdn/browser-compat-data/pull/27819, I'm editing the `ariaNotify()` data to make it clear that it is supported on Linux, but not on ChromeOS.
I've also added a data point for the related `aria-notify` Permissions Policy descriptor.
=> Chrome 141 adds `aria-notify` permission (also updates notes)

api/SpeechGrammar.json, api/SpeechGrammarList.json, api/SpeechRecognition.json, api/SpeechRecognitionPhrase.json, http/headers/Permissions-Policy.json
This PR makes several changes to the Web Speech API data:
- On-device speech recognition (https://chromestatus.com/feature/6090916291674112). The ChromeStatus entry says 139, but the engineer said it has been slipped to a 142 release because of some bugs. It is also only supported on Chrome desktop for now, not Android/WebView
- The on-device-speech-recognition Permissions-Policy directive - newly added
- SpeechRecognition.processLocally - already in, but updated Chrome support from 139 to 142 and set Android support to false
- SpeechRecognition.available() - already in, but updated Chrome support from 139 to 142 and set Android support to false
- SpeechRecognition.install() - already in, but updated Chrome support from 139 to 142 and set Android support to false
- Web speech API …
=> Updates to Web Speech API data

webextensions/api/cookies.json
Addresses the dev-docs-needed requirement of [Bug 1986688](https://bugzilla.mozilla.org/show_bug.cgi?id=1986688) Cookies are returned with a fractional expirationDate for the change made in [Bug 1972757](https://bugzilla.mozilla.org/show_bug.cgi?id=1972757) Store cookie expiry value as msec.
Related MDN changes in https://github.com/mdn/content/pull/41097.
=> Bug-1986688 Cookies expirationDate includes milliseconds

api/Element.json, api/ShadowRoot.json
According to the [Safari 26.0 release notes](https://webkit.org/blog/17333/webkit-features-in-safari-26-0/#:~:text=escaping):
> `Fixed escaping < and > when serializing HTML attribute values. (150520333)`
Fixes https://github.com/mdn/browser-compat-data/issues/27943.
=> Safari 26 escapes `<` and `>` in attributes

api/CookieStore.json
Marks several `CookieStore.get()` return values (only supported by Chrome/Edge) as experimental/non-standard.
Fixes https://github.com/mdn/browser-compat-data/issues/27529.
=> Mark `CookieStore.get()` return values as experimental/non-standard

html/elements/col.json, html/elements/colgroup.json, html/elements/tbody.json, html/elements/td.json, html/elements/tfoot.json, html/elements/th.json, html/elements/thead.json, html/elements/tr.json
Marks the `char` and `charoff` HTML attributes as unsupported in Chrome, Firefox, and Safari, because they no longer have any specified behavior, and they (most likely) never had any visually observable effect in these browsers.
Fixes https://github.com/mdn/browser-compat-data/issues/15657.
=> Mark `char`/`charoff` HTML attrs as unsupported in all browsers

api/PerformancePaintTiming.json
Fixes: #28052
Reverts #26858 for incorrect issues #26857
The [commit it refers to](https://chromiumdash.appspot.com/commit/a2ef10dead3b21a1409e6be64f60b6a870306058) was specifically for the Soft Navigations version of FP and FCP (which are very experimental):
https://issues.chromium.org/issues/40280852
If you run the test suggested in issue #26857 then you see it:
> For any loaded webpage in Chrome, performance.getEntriesByType("paint") will always return an empty array.
> When Chrome is launched with the aforementioned flag, the array will contain the aforementioned named paint entries.
I'm not sure why these tests were not run to prove this Issue was wrong when they listed it? @whalderman
Reverts PR #26858 
Issue #26857
=> Chrome does support FCP and FCP

css/properties/background-repeat-y.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `background-repeat-y` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.15.0).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/background-repeat-y
=> Chrome 5-120 supported `background-repeat-y` CSS property

css/at-rules/position-try.json
I believe this was missed in #27087. This was implemented in Safari 26 as part of the anchor positioning work.
I tested adding a `@position-try` rule to a CSS file on a website I built and it showed up as a valid rule in Safari 26:
See the WPT tests for @position-try in Safari: 
- [WPT tests for allowed declarations](https://wpt.fyi/results/css/css-anchor-position/at-position-try-allowed-declarations.html?label=master&product=chrome%5Bexperimental%5D&product=edge%5Bexperimental%5D&product=firefox%5Bexperimental%5D&product=safari%5Bstable%5D&aligned)
- [WPT tests for anchor positioning overall, including many for "at-position-try"](https://wpt.fyi/results/css/css-anchor-position?label=master&label=stable&product=safari&aligned)
=> Safari 26 supports CSS `@position-try`

api/CSSStyleDeclaration.json, api/CSSStyleProperties.json, api/CSSStyleRule.json, api/HTMLElement.json, api/MathMLElement.json, api/SVGElement.json, api/Window.json
FF144 added support for `CSSStyleProperties` in https://bugzilla.mozilla.org/show_bug.cgi?id=1919582 , as updated in #27902
However as explained in https://bugzilla.mozilla.org/show_bug.cgi?id=1919582#c30 the  `CSSStyleProperties` was renamed from a preexisting `CSS2Properties`. This adds the alternative name to the feature for Firefox. Note that the developer indicates this was from version 2 (checked) but might have been version 1.
FF145 added support for returning this from `.style` in elements (HTML, SVG, MathML) and also in `getComputedStyle()` in https://bugzilla.mozilla.org/show_bug.cgi?id=1989925. I have set these to have a subfeature indicating the new return type.
It is not clear if FF returns it from `CSSStyleRule.style` - I am asking in …
=> Firefox 144 adds `CSSStyleProperties` (aka `CSS2Properties`)

webassembly/api.json
This PR adds the missing `JSTag_static` WebAssembly interface. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.15.1).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/webassembly/api/JSTag_static
=> Chrome 115 / Firefox 131 added `WebAssembly.JSTag` attribute

css/types/mod.json, css/types/rem.json, css/types/round.json
Adds subfeatures `css.types.{mod,rem,round}.percentages` to record the partial support in Safari before 17.2.
Fixes https://github.com/mdn/browser-compat-data/issues/27862.
=> Safari 17.2 allowed mixing percentages in `round/mod/rem()`

api/SubtleCrypto.json
Removes obsolete Node.js notes for `SubtleCrypto` algorithms.
As of Node 20, those are no longer experimental.
Fixes https://github.com/mdn/browser-compat-data/issues/27964.
=> Remove experimental Node.js notes for `SubtleCrypto`

css/properties/dynamic-range-limit.json, css/types/dynamic-range-limit-mix.json
Chrome 136 introduces the CSS [`dynamic-range-limit`](https://drafts.csswg.org/css-color-hdr/#the-dynamic-range-limit-property) property; see https://chromestatus.com/feature/5146250411769856. This already had BCD.
<s>I'm pretty sure this support also includes the `dynamic-range-limit-mix()` function, but I've asked Chrome engineering to clarify.</s> UPDATE: Yes, it does.
I've already been told that the function is Chrome-only at the moment.
=> Chrome 136 adds CSS `dynamic-range-limit` + `dynamic-range-limit-mix()`

html/elements/input/datetime-local.json
- Added flag for `datetime-local` input field
- Added note about timepicker values
- Tested using [datetime-local test code pen](https://codepen.io/CodeRedDigital/pen/qEbdpOw?editors=1100) using the flag `dom.forms.datetime.timepicker`, in:
- Firefox beta 144
- Firefox Developer Edition 144
- Firefox Nightly 145
- [MDN issue #41140](https://github.com/mdn/content/issues/41140)
- [Firefox release note PR](https://github.com/mdn/content/pull/41346)
=> Add Firefox bug about `datetime-local` input behaviour

api/IDBIndex.json, api/IDBObjectStore.json
Chromium 141 adds support for the following features in `IDBIndex` and `IDBObjectStore`:
1. The new `getAllRecords()` method.
2. The `direction` option in the `getAll()` and `getAllKeys()` methods.
See https://chromestatus.com/feature/5124331450138624, and also see https://patrickbrosset.com/articles/2024-11-19-even-faster-indexeddb-reads-with-getallrecords/ for the context behind the additions.
This PR:
- Updates the existing data points for `getAllRecords()` to mark Edge as mirroring Chrome. It was previously set to `false`, but I've confirmed that it works in tests, and I don't see why it would be enabled in a different version. I tested it using @captainbrosset's demo at https://microsoftedge.github.io/Demos/idb-getallrecords/.
- Adds data points for the `direction` option in …
=> Chromium 141 IDB getAll() and getAllKeys() direction option

api/GPUAdapter.json
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `isFallbackAdapter` member of the `GPUAdapter` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.15.1).
Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/GPUAdapter/isFallbackAdapter
=> Chrome 140 unships `GPUAdapter.isFallbackAdapter`

api/URL.json
Adds a `api.URL.pathname` subfeature `encodes_trailing_space_in_opaque_path` to document a spec evolution that is now implemented in Safari TP.
See:
- https://github.com/whatwg/url/pull/844
Fixes https://github.com/mdn/browser-compat-data/issues/27856.
=> Safari TP percent-encodes trailing space in pathname
