- api/Permissions.json
Some Permissions had wrong descriptions (copy-paste errors. may be?). This PR fixes these.
May be, there should be a linter for Permissions descriptions?
I didn't check any data, just copy-pasted from the data key, since this looked like a few trivial copy-paste errors. If needed, I'll find data to make sure keys and data were not accidentally switched based on descriptions.
> Fix api.Permissions.*.__compat.description

- javascript/builtins/RegExp.json
Seems like #5735 didn't do this correctly. @a2sheppy
> Mark RegExp.prototype.toSource as removed in Firefox

- api/PerformanceObserver.json
- api/PerformancePaintTiming.json
- api/PerformanceResourceTiming.json
I've done some manual testing and dug through Safari release notes to update the status on PerformanceObserver and PerformanceTiming API.
[Release notes for Safari 11](https://webkit.org/blog/7956/new-webkit-features-in-safari-11/): Key takeaway it includes Safari technology preview 21-36.
[Release notes for Safari 12.1](https://webkit.org/blog/8718/new-webkit-features-in-safari-12-1/): Key takeaway it includes Safari technology preview 59-76.
I couldn't find the blog post for Safari 12, but I'm guessing it includes Safari technology preview 37-58.
[Technology preview release notes](https://developer.apple.com/safari/technology-preview/release-notes/)
* PerformanceObserver. supportedEntryTypes was added in tech preview 75, hence Safari 12.1 (note that because of #5776 that's actually a …
> Update some Safari performance related API

- api/Response.json
> Response headers works on Chrome on Android

- css/properties/grid-template-columns.json
The subgrid feature is nested wrongly. Thus it is not appearing in the rendering correctly. Compare:
https://developer.mozilla.org/de/docs/Web/CSS/grid-template-rows#Browser_compatibility vs.
https://developer.mozilla.org/en-US/docs/Web/CSS/grid-template-columns#Browser_compatibility
> Move subgrid to correct sub feature position

- api/ResizeObserver.json
Source: https://webkit.org/blog/10247/new-webkit-features-in-safari-13-1/
> Added Safari version for ResizeObserver

- html/elements/a.json
- html/elements/area.json
- html/elements/link.json
https://html.spec.whatwg.org/multipage/#link-type-noopener
> Move rel=noopener out of <link>, into <area> & <a>

- html/elements/link.json
This change adds `mdn_url` values for several `link[rel]` keywords.
> Add mdn_url values for link[rel] keywords

- html/global_attributes.json
https://www.chromestatus.com/features/5654529808793600
> Add WebView number for enterkeyhint

- javascript/statements.json
I've archived the MDN page. Not implemented anywhere in current browsers. Not in any spec.
> Remove for-each-in data

- javascript/builtins/Number.json
MDN page now archived. Not supported anywhere. No spec.
> Remove Number.toInteger

- javascript/builtins/Function.json
MDN pages archived. No support and no spec.
> Remove obsolete Function methods

- css/at-rules/font-face.json
In the 20 September 2018 draft of CSS Fonts Module Level 4, the [src parsing rules](https://www.w3.org/TR/2018/WD-css-fonts-4-20180920/#font-format-values) were updated to [allow keywords in `format()` hints](https://www.w3.org/TR/2018/WD-css-fonts-4-20180920/#changes-2018-04-10).
I tested this feature with locally installed browsers and many others provided by [Cross Browser Testing](https://crossbrowsertesting.com/). The following [visual test](https://codepen.io/jonneal/full/MWawJMN) was used:
```html
<p id="as-string">If you see this, string format hints are not supported.</p>
<p id="as-keyword">If you see this, keyword format hints are not supported.</p>
<style>
p {
background-color: #f5f5f5;
color: #900;
font: 900 100%/1 sans-serif;
padding: .25em;
}
#as-string {
font-family: …
```
> Add compat data for @font-face format descriptor

- javascript/builtins/Proxy.json
- javascript/builtins/Reflect.json
MDN pages are archived now and this meets the removal criteria.
> Remove obsolete enumerate methods

- javascript/builtins/Object.json
These MDN pages have been archived and data can be removed.
> Remove obsolete Object members

- api/LayoutShift.json
- api/LayoutShiftAttribution.json
- api/Window.json
https://www.chromestatus.com/features/5110682739539968
http://web-confluence.appspot.com/#!/catalog?releases=%5B%22Edge_18.17763_Windows_10.0%22,%22Safari_13.0.2_OSX_10.15%22,%22Chrome_78.0.3904.70_Windows_10.0%22,%22Firefox_70.0_Windows_10.0%22%5D&q=%22LayoutShift%22
> Layoutshift

- api/LargestContentfulPaint.json
https://www.chromestatus.com/features/5666250908762112
http://web-confluence.appspot.com/#!/catalog?releases=%5B%22Edge_18.17763_Windows_10.0%22,%22Safari_13.0.2_OSX_10.15%22,%22Chrome_78.0.3904.70_Windows_10.0%22,%22Firefox_70.0_Windows_10.0%22%5D&q=%22LargestContentfulPaint%22
> Add data for LargestContentfulPaint.

- browsers/opera_android.json
Fixes #6047.  This PR adds Opera Android 57 to our data.
> Add Opera Android 57

- browsers/opera_android.json
Corrects the engine version in the additions of #6092.
> Fix engine version in Opera Android 57

- api/Gamepad.json
- api/VRStageParameters.json
- api/Window.json
> Handle final VR removals. 

- webextensions/api/webRequest.json
This PR includes the following changes:
* the addition of fromCache, ip, and frameAncestors to webRequest.onHeadersReceived as per the information on https://bugzilla.mozilla.org/show_bug.cgi?id=1602005
* the addition of incognito to all webRequest events as per https://bugzilla.mozilla.org/show_bug.cgi?id=1545163
* the addition of cookieStoreID to all webRequest events as per https://bugzilla.mozilla.org/show_bug.cgi?id=1391992
Note that the linter produce errors relating to formatting in several JavaScript files, unrelated to these changes. Issue https://github.com/mdn/browser-compat-data/issues/6088 has been raised for this.
> More object details properties for webRequest.onHeadersReceived

- api/AudioParamMap.json
- api/AudioWorklet.json
- api/AudioWorkletGlobalScope.json
- api/AudioWorkletNode.json
- api/AudioWorkletProcessor.json
Source:
https://developer.microsoft.com/en-us/microsoft-edge/status/webaudioapi/
> Internet Explorer does not support Web Audio API

- api/HTMLInputElement.json
The information is based on:
manual testing of modern browers;
searching in bug trackers of webkit and mozilla;
https://bugzilla.mozilla.org/show_bug.cgi?id=850364
https://bugs.webkit.org/show_bug.cgi?id=91907
https://en.wikipedia.org/wiki/Safari_version_history#Safari_7 and https://trac.webkit.org/browser/webkit/branches#safari-537.73-branch
> addition of HTMLInputElement#setRangeText

- api/MediaMetadata.json
- api/MediaSession.json
- api/Navigator.json
Source:
https://developer.microsoft.com/en-us/microsoft-edge/status/mediasession/
> IE does not support Media Session API

- api/SubmitEvent.json
Supersedes #5882 given no response from the PR author.
See https://bugzilla.mozilla.org/show_bug.cgi?id=1588715
> Firefox 75 supports SubmitEvent

- http/headers/feature-policy.json
Chromium Platform Status:
https://chromestatus.com/feature/5736091539734528
Chromium bug:
https://crbug.com/993007
> Chrome/ium 84 ships FP publickey-credentials-get

- javascript/builtins/String.json
Page got archived https://wiki.developer.mozilla.org/en-US/docs/Archive/Web/JavaScript/String.quote
Qualifies as irrelevant feature: https://github.com/mdn/browser-compat-data/blob/master/docs/data-guidelines.md#removal-of-irrelevant-features
> Remove data for String.quote

- api/ReportingObserver.json
On workers: https://www.chromestatus.com/feature/6310316751192064
Initial support: https://www.chromestatus.com/feature/4691191559880704
What I can determine of other browsers: https://web-confluence.appspot.com/#!/catalog?releases=%5B%22Edge_18.17763_Windows_10.0%22,%22Safari_13.0.2_OSX_10.15%22,%22Chrome_78.0.3904.70_Windows_10.0%22,%22Firefox_70.0_Windows_10.0%22%5D&q=%22ReportingOb%22
> Add ReportingObserver API.

- api/Window.json
Addition to #6187. 
Here's the commit that landed these: https://source.chromium.org/chromium/chromium/src/+/b74de5a09c2a9e851cc0ac1a02f7cd963cd39a03?originalUrl=https%2F:%2F%2F%2Fcs.chromium.org%2F
> Add Chromium numbers for pagehide and pageshow.

- .github/workflows/node.js.yml
Fixes #5276.
Tests every push and pull request with GitHub Actions. See #5276 for background and rationale.
> Enable testing with GitHub Actions

- browsers/firefox.json
Today is Firefox release day :)
> Firefox 77 release

- javascript/builtins/intl/ListFormat.json
https://bugzilla.mozilla.org/show_bug.cgi?id=1589095
> Firefox 78 ships Intl.ListFormat

- api/Node.json
> Update previousSibling IE compatability

- javascript/builtins/intl/DisplayNames.json
Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1557727
Node: https://nodejs.org/en/blog/release/v14.0.0/
Chromiums: https://www.chromestatus.com/features/4965112605573120
Safari: https://bugs.webkit.org/show_bug.cgi?id=209779
> Add Intl.DisplayNames

- api/WakeLock.json
- api/WakeLockSentinel.json
https://www.chromestatus.com/feature/4636879949398016
> Add Screen Wake Lock API.

- api/BarcodeDetector.json
https://www.chromestatus.com/features/4757990523535360
> Add BarcodeDector data.

- css/properties/appearance.json
- <https://github.com/mdn/data/pull/419>
- <https://github.com/w3c/csswg-drafts/pull/3574>
> feat(css): Update `appearance` data for `menulist‑button` changes

- api/ContactsManager.json
https://www.chromestatus.com/features/6316401599971328
> Add ContactsManager.json.

- api/CSSPropertyRule.json
https://www.chromestatus.com/feature/5640265926705152
> Add CSSPropertyRule.json.

- css/at-rules/viewport.json
https://storage.googleapis.com/chromium-find-releases-static/37a.html#37aaaed4e1e12d7e05ddb898acc43c1abb56a24c
> Remove flag from viewport.

- GOVERNANCE.md
Thanks for all the work you've contributed to MDN and mdn-browser-compat-data.
> Remove Richard from peer list; Add peers and owners emeriti section

- api/Clipboard.json
https://www.chromestatus.com/feature/5074658793619456
https://www.chromestatus.com/feature/5861289330999296
> Correct clipboard read/write version numbers.

- api/Cache.json
- api/CacheStorage.json
- api/Client.json
- api/Clients.json
- api/ExtendableEvent.json
- api/ExtendableMessageEvent.json
- api/FetchEvent.json
- api/InstallEvent.json
- api/Navigator.json
- api/NotificationEvent.json
- api/PushEvent.json
- api/PushManager.json
- api/PushMessageData.json
- api/PushSubscription.json
- api/ServiceWorker.json
- api/ServiceWorkerContainer.json
- api/ServiceWorkerGlobalScope.json
- api/ServiceWorkerMessageEvent.json
- api/ServiceWorkerRegistration.json
- api/WindowClient.json
Fixes https://github.com/mdn/browser-compat-data/issues/6161
> Firefox 78esr ships Service Worker and Push

- browsers/safari_ios.json
Here is the release information: https://developer.apple.com/documentation/ios-ipados-release-notes/ios-ipados-13_3-release-notes.
> Add an entry for iOS Safari 13.3

- api/Navigator.json
https://www.chromestatus.com/features/5756636801007616
https://www.chromestatus.com/features/5066079862784000
> Add implementation details to registerProtocolHandler().

- browsers/firefox.json
Today is Firefox release day :)
> Firefox 78 release

- javascript/builtins/AggregateError.json
- javascript/builtins/Promise.json
Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1599769
Chromiums: https://www.chromestatus.com/features/5574922384441344
Safari: https://bugs.webkit.org/show_bug.cgi?id=202566
MDN:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/any
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/AggregateError
> Add Promise.any and AggregateError

- javascript/builtins/intl/DateTimeFormat.json
Bug https://bugzilla.mozilla.org/show_bug.cgi?id=1557718
> Firefox 79 supports dateStyle and timeStyle

- http/headers/cross-origin-embedder-policy.json
- http/headers/cross-origin-opener-policy.json
Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1619649#c0
Chromium COEP: https://www.chromestatus.com/features#Cross-Origin-Embedder-Policy
> Firefox 79 ships COOP+COEP

- javascript/operators/logical_and_assignment.json
- javascript/operators/logical_nullish_assignment.json
- javascript/operators/logical_or_assignment.json
Spec: https://tc39.es/proposal-logical-assignment/#sec-assignment-operators
Firefox 79: https://bugzilla.mozilla.org/show_bug.cgi?id=1639591
Safari 14: https://developer.apple.com/documentation/safari-release-notes/safari-14-beta-release-notes#JavaScript
Chromium 85 : https://www.chromestatus.com/feature/4592855228088320
> Add logical assignment operators

- css/at-rules/media.json
https://www.chromestatus.com/feature/5719782840074240
> Correct version number for 'no-preference' removal.

- css/at-rules/media.json
Chromium code merged to enable prototyping with this media query: see https://crbug.com/1051189 status
> add supported version for prefers-reduced-data

- http/headers/cross-origin-embedder-policy.json
- http/headers/cross-origin-opener-policy.json
https://www.chromestatus.com/feature/5642721685405696
> Correct values for COOP/COEP in WebView.

- docs/publishing.md
Per https://github.com/mdn/browser-compat-data/issues/6369#issuecomment-660160696
> Add a reminder to update tracking issues to publishing docs

- webextensions/api/tabs.json
I missed this in my review in https://github.com/mdn/browser-compat-data/pull/6397
> Nest tabs.warmup correctly

- README.md
Added my project `hexo-compat-table` to README.md: https://github.com/TimDaub/hexo-compat-report
> Add hexo-compat-table to README.md

- browsers/chrome.json
- browsers/chrome_android.json
- browsers/webview_android.json
In that PR, I updated the documentation for release 84 of Chrome.
:)
> Update chrome to release 84

- css/properties/appearance.json
https://www.chromestatus.com/feature/4715298156445696
https://www.chromestatus.com/feature/5913213940006912
> Update supports CSS property appearance

- javascript/functions.json
Computed names https://trac.webkit.org/changeset/189504/webkit
Generator construct-ability https://trac.webkit.org/changeset/194435/webkit
> Fix functions.json for Safari

- javascript/builtins/Function.json
They are supported in Safari 10. https://trac.webkit.org/changeset/197205/webkit
> Fix javascript/builtins/Function.json for Safari

- javascript/builtins/String.json
It is added in https://trac.webkit.org/changeset/181084/webkit
> String[@@iterator] is added in Safari 9

- css/at-rules/media.json
Refer to https://bugzilla.mozilla.org/show_bug.cgi?id=1506364
> Fx80 adds prefers-contrast with pref

- css/at-rules/font-face.json
This PR adds mdn_url to @font-face/font-weight
https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-weight
> Add mdn_url to @font-face/font-weight

- api/PeriodicSyncEvent.json
- api/PeriodicSyncManager.json
https://www.chromestatus.com/feature/5689383275462656
> Add data for Periodic Background Sync

- api/CSSRule.json
> Make note about how IE normalizes rules in cssText

- api/Document.json
Fixes https://github.com/mdn/browser-compat-data/issues/6510
JsBin to test this: https://jsbin.com/wizuwejocu/1/edit?html,js,output
> Fix IE 11 fullscreen api docs

- css/selectors/marker.json
- Refer to https://bugzilla.mozilla.org/show_bug.cgi?id=1637532
- Blink already supports these properties. (https://groups.google.com/a/chromium.org/g/blink-dev/c/80j6AEWI-_s?pli=1)
> Fx80 adds animation & transition support on ::marker

- api/XMLHttpRequest.json
Add XMLHttpRequestion#responseType === 'json' support info in Opera 12:
See http://www.oldversion.com/windows/opera-12-00-beta-1
Tested manually.
> Update XMLHttpRequest.responseType for Opera

- css/properties/appearance.json
Refer to https://bugzilla.mozilla.org/show_bug.cgi?id=1620467
> Std `appearance` added in Fx80

- GOVERNANCE.md
I'm pleased to invite @foolip to join [the list of Peers](https://github.com/mdn/browser-compat-data/blob/master/GOVERNANCE.md#list-of-current-peers). I've reached out to the active Owners, who have approved this nomination.
@foolip has already accepted the Mozilla Commit Access Requirements (see https://github.com/mdn/mdn/issues/101).
Please join me in welcoming Philip to the team. 🎉
> Add Philip Jägenstedt as a BCD Peer

- browsers/chrome.json
- browsers/chrome_android.json
- browsers/webview_android.json
In that PR, I updated the documentation for release 85 of Chrome. 
:wink:
> Updates chrome to version 85

- api/ResizeObserverEntry.json
- api/ResizeObserverSize.json
From [this status entry](https://www.chromestatus.com/feature/4966068076412928) this fixes #6537.
> Correct ResizeObserverEntry and add ResizeObserverSize.

- webextensions/api/tabs.json
https://bugzilla.mozilla.org/show_bug.cgi?id=1653354#c7
> tabs.saveAsPDF() is now supported on maOS

- css/properties/column-gap.json
- css/properties/row-gap.json
Tested with https://codepen.io/kripod97/pen/Rwageze on [BrowserStack](https://www.browserstack.com/).
> feat(css): unprefixed grid gap props for Safari

- http/headers/feature-policy.json
As per https://bugzilla.mozilla.org/show_bug.cgi?id=1608358
> adding note about the fullscreen directive bug

- api/AudioBuffer.json
- api/AudioBufferSourceNode.json
- api/AudioParam.json
- api/AudioParamMap.json
- api/AudioProcessingEvent.json
- api/AudioScheduledSourceNode.json
- api/AudioTrack.json
- api/AudioTrackList.json
- api/IIRFilterNode.json
- api/MediaCapabilities.json
- api/MediaDevices.json
- api/MediaEncryptedEvent.json
- api/MediaError.json
- api/MediaKeyMessageEvent.json
- api/MediaKeySession.json
- api/MediaKeyStatusMap.json
- api/MediaKeySystemAccess.json
- api/MediaKeys.json
- api/MediaSession.json
- api/Navigator.json
- api/OscillatorNode.json
- api/VideoTrack.json
This PR provides results collected from [mdn-bcd-collector](https://github.com/foolip/mdn-bcd-collector) for various Multimedia APIs.  All versions have been verified manually in SauceLabs and through searching Chromium Code Search to verify the commits.  (All invalid data was removed from this PR and either corrected on the collector or separated into a new PR.)
Another PR will be coming later to cover the rest of the changes.
> Results from mdn-bcd-collector for various Multimedia APIs

- css/selectors/indeterminate.json
- css/selectors/invalid.json
- css/selectors/valid.json
This PR supersedes #6354.  This is a cherry-pick of the description updates from that PR, with the changes requested.  (This new PR was opened due to lack of response from the original author.)
> Update descriptions for indeterminate/valid/invalid CSS selectors

- README.md
I signed up for SauceLabs's open source program for BCD and we're supposed to credit them with this badge. As soon as I figure out how it works, I'll be reaching out to Peers and Owners with info to get access to this tool.
cc: @foolip
> Credit SauceLabs and BrowserStack open source programs

- browsers/firefox_android.json
- webextensions/api/tabs.json
Landed in https://bugzilla.mozilla.org/show_bug.cgi?id=1664522
> Support for tabs.captureTab for Firefox for Android 82

- api/Window.json
> Add compatibility notes about reported viewport values on iOS

- api/Window.json
This PR updates the Firefox data for the Window API based upon manual testing to achieve more real data for the Window API.
Tests used: https://mdn-bcd-collector.appspot.com/tests/api/Window
> Add/update Firefox data for Window API

- api/Console.json
This PR uses the data collected from the mdn-bcd-collector project to fix a few data inaccuracies in the Console API.  Results were manually verified for accuracy.
Tests used: https://mdn-bcd-collector.appspot.com/tests/api/Console
> Fix data in Console API using mdn-bcd-collector

- test/linter/test-browsers.js
- test/linter/test-descriptions.js
- test/linter/test-links.js
- test/linter/test-real-values.js
- test/linter/test-style.js
- test/linter/test-versions.js
- test/linter/utils.js
- test/utils.js
Linters have duplications in error logging logic, and this patch tries to reduce it.
> Add Logger class for linters

- api/Document.json
- api/Node.json
Fixes https://github.com/mdn/browser-compat-data/issues/6832.
> Remove api.Document.contains and clarify IE support is just HTMLElement

- api/Window.json
This PR updates the Safari data for the Window API based upon a combination of manual testing and collector results to achieve more real data for the Window API.
Tests used: https://mdn-bcd-collector.appspot.com/tests/api/Window
> Add/update Safari data for Window API

- .gitattributes
This prevents prettier failure in environments where CRLF checkout is the default.
> Force LF line ending for all text files

- api/AuthenticationAssertion.json
- api/Credential.json
- api/CredentialUserData.json
- api/CryptoKey.json
- api/CryptoKeyPair.json
- api/FederatedCredential.json
- api/PasswordCredential.json
- api/PublicKeyCredentialCreationOptions.json
- api/PublicKeyCredentialRequestOptions.json
- api/ScopedCredential.json
- api/ScopedCredentialInfo.json
- api/WebAuthentication.json
This PR uses the mirroring script to mirror Chrome Desktop/Android to Opera Desktop/Android for Web Authentication APIs.
> Mirror Chrome -> Opera for Authentication APIs

- webextensions/api/extensionTypes.json
> Add note for two new tabs.captureTab options

- css/types/image.json
According
- https://github.com/Fyrd/caniuse/blob/master/features-json/css-conic-gradients.json
- https://bugzilla.mozilla.org/show_bug.cgi?id=1175958
> add conic-gradient support data for Firefox

- api/CSSConditionRule.json
This PR updates the `CSSConditionRule` API data based upon results from the mdn-bcd-collector project.
> Update CSSConditionRule API data

- api/CSSPageRule.json
This PR updates the compat data for the `CSSPageRule` API based upon a combination of results from the mdn-bcd-collector, as well as manual testing.
> Update data for CSSPageRule

- api/CSSRule.json
- api/CSSRuleList.json
This PR updates the compat data for the `CSSRule` and `CSSRuleList` APIs based upon a combination of results from the mdn-bcd-collector, as well as manual testing.
> Update data for CSSRule[List] API

- api/CSSStyleDeclaration.json
This PR updates the compat data for the `CSSStyleDeclaration` API based upon a combination of results from the mdn-bcd-collector, as well as manual testing.
> Update data for CSSStyleDeclaration API

- api/CSSStyleRule.json
This PR updates the compat data for the `CSSStyleRule` API based upon a combination of results from the mdn-bcd-collector, as well as manual testing.
> Update data for CSSStyleRule API

- browsers/nodejs.json
See https://nodejs.org/en/blog/release/v15.0.0/
> Add node 15.0.0 release to browser data

- browsers/chrome.json
- browsers/chrome_android.json
- browsers/webview_android.json
Hello everyone, everything good?
In that PR, I updated the docs to version 86 of Chrome. 
😉
> Updates chrome to version 86

- javascript/builtins/AggregateError.json
- javascript/builtins/Promise.json
- javascript/builtins/String.json
- javascript/operators/logical_and_assignment.json
- javascript/operators/logical_nullish_assignment.json
- javascript/operators/logical_or_assignment.json
[Node v15.0.0 release](https://nodejs.org/en/blog/release/v15.0.0/)
> New features support added to Nodejs 15.0.0

- css/selectors/checked.json
> Correct invalid character reference sequence in css/selectors/checked.json

- browsers/edge.json
In that PR, I updated the docs to version 86 of Edge.
> Updates Edge to version 86

- api/Element.json
- webextensions/api/webRequest.json
Those versions simply don't exist.
> Remove invalid notes about Edge

- api/Location.json
This PR updates the Internet Explorer data for the Location API based upon manual testing.
> Update IE data for Location API

- api/Location.json
This PR updates the Chrome data for the Location API using results from the mdn-bcd-collector project.
> Update Chrome data for Location API

- api/Location.json
This PR updates the Firefox data for the Location API using results from the mdn-bcd-collector project.
> Update Firefox data for Location API

- package.json
> Add "bcd" to package keyword list

- api/Location.json
This PR updates the Opera data for the Location API using results from the mdn-bcd-collector project.
> Update Opera data for Location API

- browsers/opera.json
There is a new Opera :) 
https://blogs.opera.com/desktop/2020/10/opera-72-update/
> Add Opera 72 release

- api/MediaMetadata.json
- api/MediaSession.json
- api/MediaSessionAction.json
- api/MediaSessionActionDetails.json
- api/Navigator.json
https://bugzilla.mozilla.org/show_bug.cgi?id=1665496
https://www.mozilla.org/en-US/firefox/82.0/releasenotes/
Firefox desktop now supports the MediaSession api without any flags
> Updated MediaSession support data for Firefox

- api/HTMLCanvasElement.json
- api/HTMLImageElement.json
- api/PushManager.json
- api/PushSubscription.json
- api/Screen.json
- api/Window.json
Generated from https://github.com/saschanaz/browser-compat-data/compare/deprecated-fetch
We also need to check they still exists in browsers, and if not remove the items.
> Sync deprecated flag with MDN

- css/properties/content-visibility.json
New CSS property.
**Required for:**
https://developer.mozilla.org/en-US/docs/Web/CSS/content-visibility
**Resources:**
https://www.chromestatus.com/feature/4613920211861504
https://developers.google.com/web/updates/2020/08/nic85#content-visibility
https://web.dev/content-visibility/
https://caniuse.com/css-content-visibility
> CSS "content-visibility" property

- api/MediaKeyStatusMap.json
This PR renames the "iterator" feature of the MediaKeyStatusMap API to the proper "@@iterator".
> Rename api.MediaKeyStatusMap.iterator to @@iterator

- css/properties/contain-intrinsic-size.json
New CSS property.
**Required for:**
https://developer.mozilla.org/en-US/docs/Web/CSS/contain-intrinsic-size
**Resources:**
https://web.dev/content-visibility/
> CSS "contain-intrinsic-size" property

- api/Window.json
Fixes https://github.com/mdn/browser-compat-data/issues/6761
> Mark window.status deprecated

- .npmignore
Do not publish the following files to npm which dependents don't need:
- .gitattributes
- .prettierignore
- .prettierrc
> Do not publish unnecessary files to npm

- api/MediaCapabilities.json
- api/MediaElementAudioSourceNode.json
- api/MediaError.json
- api/MediaKeySession.json
- api/MediaKeyStatusMap.json
- api/MediaKeySystemAccess.json
- api/MediaKeys.json
- api/MediaStream.json
- api/MediaStreamAudioDestinationNode.json
- api/MediaStreamAudioSourceNode.json
- api/MediaStreamTrack.json
This PR adds real values for Safari for various Media APIs based upon results from the mdn-bcd-collector project.
> Add Safari real values for Media APIs

- browsers/chrome.json
- browsers/chrome_android.json
- browsers/webview_android.json
Chrome 87 is now out as a stable release.
> Chrome 87 is released

- api/DOMImplementation.json
This PR adds real values for Safari for the DOMImplementation API based upon results from the mdn-bcd-collector project.
> Add real Safari values for DOMImplementation API

- api/CanvasRenderingContext2D.json
This PR adds Internet Explorer data for the CanvasRenderingContext2D API based upon results from the mdn-bcd-collector project.
> Add IE data for CanvasRenderingContext2D API

- api/Performance.json
This PR updates the Internet Explorer data for the Performance API based upon results from the mdn-bcd-collector project. Results were manually verified for confirmation.
> Add IE data for Performance API

- api/Selection.json
This PR updates the Internet Explorer data for the Selection API based upon results from the mdn-bcd-collector project. Results were manually verified for confirmation.
> Update IE data for Selection API

- css/properties/quotes.json
https://www.chromestatus.com/feature/4922661488558080
> CSS Quotes Chromium Based Update

- api/TextTrack.json
- api/TextTrackCue.json
- api/TextTrackList.json
This PR updates the Internet Explorer data for the TextTrack, TextTrackCue, and TextTrackList APIs based upon results from the mdn-bcd-collector project.  Results were manually verified for confirmation.
> Update IE data for TextTrack[Cue/List] API

- api/Document.json
This PR updates the Safari and Safari iOS data for various features of the Document API based upon results from the mdn-bcd-collector project.
> Update Safari data for Document API

- css/selectors/target-within.json
This is a level 4 selector which I am documenting for https://github.com/mdn/sprints/issues/836 and https://github.com/mdn/sprints/issues/1686
I can't find any support as yet, but it's an active spec and a recently added feature.
> target-within

- docs/data-guidelines.md
I've received some good feedback on #6906. This PR fixes #6906, with a very slight revision of the wording from the original issue.
> Document how to note operating system limitations with "partial_implementation"

- api/FileList.json
- api/FileReaderSync.json
This PR updates the Internet Explorer data for the FileList and FileReaderSync APIs based upon data from the mdn-bcd-collector project.
> Update IE data for FileList/FileReaderSync API

- api/Node.json
- api/NodeList.json
This PR updates the Internet Explorer data for the Node and NodeList APIs based upon results from the mdn-bcd-collector project.  Results were manually verified for confirmation.
> Update IE data for Node[List] API

- javascript/builtins/String.json
This PR addresses issue #6178 by updating the version number in the String.json file as addressed in the issue.
> Fix for issue #6178

- api/AudioBufferSourceNode.json
Reverts mdn/browser-compat-data#7490
> Revert "Remove the api.AudioBufferSourceNode.start entry"

- api/Selection.json
This PR adds real values for Firefox for the Selection API based upon results from the mdn-bcd-collector project.
> Add real values for Firefox for Selection API

- api/Node.json
- api/NodeList.json
This PR adds real values for the Node and NodeList APIs for Firefox, based upon results from the mdn-bcd-collector project.
> Add real values for Firefox for Node/NodeList API

- css/types/image.json
Adds double-position entry for Firefox 83 (see #7467)
> Conic-gradient support update

- api/KeyboardEvent.json
Updated deprecation information on `KeyboardEvent.getModifierState()` to match the spec
https://www.w3.org/TR/uievents-key/#keys-modifier
mdn/sprints/issues/3587
> Update modifier keys

- browsers/samsunginternet_android.json
https://news.samsung.com/global/samsung-internet-13-0-takes-your-browsing-experience-to-the-next-level
> Update SamsungInternet 13

- javascript/builtins/globals.json
I'm not sure if this is the optimal phrasing, but I think it's an improvement.
- Minor string update
- N/A
- N/A
- N/A
- N/A
> Update description for leading_zero_strings_as_decimal

- javascript/builtins/Object.json
This PR is for the Objects portion of issue #6249. The `true` and `null` values were updated to version numbers. 
I did have problems finding the value for `javascript.builtins.Object.preventExtensions.ES2015_behavior` (line `1474` in `javascript/builtins/Object.json`). Perhaps someone can point me in the right direction for finding that information, after which I can do another commit to this branch with the fix.
> Complete nodejs data for objects

- css/properties/align-self.json
https://bugs.webkit.org/show_bug.cgi?id=170235
https://trac.webkit.org/changeset/214564/webkit
> Update CSS AlignSelf For Safari

- api/Window.json
This PR adds real values for Firefox for the Window API based upon results from the mdn-bcd-collector project.
> Add real values for Firefox for Window API

- api/HTMLHRElement.json
- html/elements/hr.json
This PR is a part of a project to add missing interfaces and interface features to BCD that are from a spec in Editor's Draft or more and is supported in at least one browser.  This particular PR adds missing features, populating the results using data from the [mdn-bcd-collector](https://mdn-bcd-collector.appspot.com) project (v1.1.6), for the HTMLHRElement API.
Spec: https://html.spec.whatwg.org/multipage/semantics.html#htmlhrelement
IDL: https://github.com/w3c/webref/blob/master/ed/idl/html.idl
> Add missing features for HTMLHRElement

- api/PictureInPictureWindow.json
This PR is a part of a project to add missing interfaces and interface features to BCD that are from a spec in Editor's Draft or more and is supported in at least one browser.  This particular PR adds missing features, populating the results using data from the [mdn-bcd-collector](https://mdn-bcd-collector.appspot.com) project (v1.1.6), for the PictureInPicture API.
Spec: https://w3c.github.io/picture-in-picture/
IDL: https://github.com/w3c/webref/blob/master/ed/idl/picture-in-picture.idl
> Add PictureInPictureWindow

- api/LocalMediaStream.json
This PR updates the data for the LocalMediaStream API based upon results from the mdn-bcd-collector project.
> Update Chromium data for LocalMediaStream

- api/NamedNodeMap.json
This PR adds real values for Chromium for the NamedNodeMap API based upon results from the mdn-bcd-collector project.
> Add real values for Chromium for NamedNodeMap API

- api/Node.json
This PR adds real values for Chromium for the Node API based upon results from the mdn-bcd-collector project.
> Add Chromium real values for Node API

- api/MediaList.json
This PR updates the Chromium data for the MediaList API based upon results from the mdn-bcd-collector project.
> Add Chromium real values for MediaList API

- api/EventCounts.json
This PR is a part of a project to add missing interfaces and interface features to BCD that are from a spec in Editor's Draft or more and is supported in at least one browser.  This particular PR adds missing features, populating the results using data from the [mdn-bcd-collector](https://mdn-bcd-collector.appspot.com) project (v1.1.6), for the EventCounts API.
Spec: https://wicg.github.io/event-timing/
IDL: https://github.com/w3c/webref/blob/master/ed/idl/event-timing.idl
> Add EventCounts API

- api/Range.json
This PR adds and corrects the Opera Presto data for the Range API based upon results from the mdn-bcd-collector project.
> Add/correct Opera data for Range API

- api/Selection.json
This PR adds real values for Chrome and Opera for the Selection API, based upon results from the [mdn-bcd-collector](https://mdn-bcd-collector.appspot.com) project (v1.1.6).
> Add real values for Chrome + Opera for Selection API

- api/HTMLIFrameElement.json
- html/elements/iframe.json
> Mark allowPaymentRequest as removed from Firefox

- browsers/firefox.json
- browsers/firefox_android.json
I've updated both the `firefox` and `firefox_android` data
> updating fx status now current is 84

- webextensions/api/browsingData.json
- webextensions/manifest/permissions.json
We just added support for browsingData in Firefox for Android.
Code landed in https://bugzilla.mozilla.org/show_bug.cgi?id=1625233.
> Update Firefox Android support for browsingData.

- api/UIEvent.json
Per https://w3c.github.io/uievents/#legacy-interface-UIEvent
> Mark UIEvent#which as deprecated

- api/DOMMatrixReadOnly.json
Per https://drafts.fxtf.org/geometry/#dom-dommatrixreadonly-scalenonuniform
> Mark scaleNonUniform() as deprecated

- api/PannerNode.json
Per https://webaudio.github.io/web-audio-api/#PannerNode-methods
> Mark PannerNode#setPosition and setOrientation as deprecated

- api/SVGAnimationElement.json
This PR is a part of a project to add missing interfaces and interface features to BCD that are from an active spec (including WICG specs) and is supported in at least one browser.  This particular PR adds missing features, populating the results using data from the [mdn-bcd-collector](https://mdn-bcd-collector.appspot.com) project (v1.1.8), for the `SVGAnimationElement` API.
Spec: https://svgwg.org/specs/animations/
IDL: https://github.com/w3c/webref/blob/master/ed/idl/svg-animations.idl
Tests Used: https://mdn-bcd-collector.appspot.com/tests/api/SVGAnimationElement
> Add missing features for SVGAnimationElement API

- api/SVGTransform.json
This PR is a part of a project to add missing interfaces and interface features to BCD that are from an active spec (including WICG specs) and is supported in at least one browser.  This particular PR adds missing features, populating the results using data from the [mdn-bcd-collector](https://mdn-bcd-collector.appspot.com) project (v1.1.8), for the `SVGTransform` API.
Spec: https://svgwg.org/svg2-draft/
IDL: https://github.com/w3c/webref/blob/master/ed/idl/SVG.idl
Tests Used: https://mdn-bcd-collector.appspot.com/tests/api/SVGTransform
> Add missing features for SVGTransform API

- api/ByteLengthQueuingStrategy.json
- api/CountQueuingStrategy.json
This follows other Streams related APIs (#3307).
> Mark *QueueingStrategy as supported on Firefox 

- README.md
I've taken it offline and archived the repository, so it shouldn't be listed anymore. Sorry :)
> Remove my mdn-browser-compat-data-explorer

- api/PaintRenderingContext2D.json
This PR adds real values for Opera and Opera Android for the `PaintRenderingContext2D` API by mirroring the data from Chrome and Chrome Android.
> Add Opera versions for PaintRenderingContext2D API

- api/Window.json
This matches the desktop support.
> Mark mozPaintCount as removed from Firefox for Android

- api/ServiceWorkerRegistration.json
These are sub-features of showNotification. None of the pages that
should exist for these do exist, so just remove the links.
> Remove incorrect mdn_url links to showNotification

- browsers/opera.json
Hello everyone, everything good?
In this PR, I update the version of Opera to 73.
More information on this link: https://blogs.opera.com/desktop/2020/12/opera-73-update/
> Updates the version of Opera to 73

- api/NDEFReader.json
This PR updates Web NFC API to reflect latest spec changes.
See https://github.com/w3c/web-nfc/blob/gh-pages/EXPLAINER.md#changes-done-after-origin-trial-ot and https://web.dev/nfc/
Disclaimer: I'm an editor of the spec.
> s/onread/onreading/g & add write()

- api/WebGL2RenderingContext.json
Reverts mdn/browser-compat-data#8183.
> Revert "Add missing features for WebGL2RenderingContext API"

- schemas/compat-data.schema.json
> simplify support block definition

- html/manifest/shortcuts.json
Spec: https://w3c.github.io/manifest/#shortcuts-member
Chromiums: https://www.chromestatus.com/features/5059438092222464
Gecko: https://bugzilla.mozilla.org/show_bug.cgi?id=1582341
Webkit: https://bugs.webkit.org/show_bug.cgi?id=201964
I wasn't sure about Samsung, I will ask if someone knows.
> Add App shortcuts

- webextensions/api/webRequest.json
Based on [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1657916). 
> Adds view-source to WebRequest API

- api/HTMLElement.json
Although this isn't shipped on release channel yet, but this is implemented by
https://bugzilla.mozilla.org/show_bug.cgi?id=1425291 (Gecko 83).
> Update autocapitazlie support for Firefox

- javascript/statements.json
Update Android Webview data for JavaScript export statement, Issue #7571
> Update JavaScript export statement for Android Webview

- api/WindowOrWorkerGlobalScope.json
See: https://www.chromestatus.com/feature/5690888397258752
> Fix crossOriginIsolated status for Chrome

- browsers/chrome.json
- browsers/chrome_android.json
- browsers/webview_android.json
Hello everyone, everything good?
In that PR, I updated the docs to version 88 of Chrome.
According to https://www.chromestatus.com/features/schedule, 90 is the nightly version.
😉
> Updates chrome to version 88

- browsers/edge.json
https://docs.microsoft.com/en-us/deployedge/microsoft-edge-relnote-stable-channel#version-88070550-january-21
> Browser Edge 88 Release

- javascript/builtins/FinalizationRegistry.json
> Fix inaccuracy in Opera support for FinalizationRegistry 

- javascript/builtins/intl/DisplayNames.json
Updating data to reflect FF86
https://bugzilla.mozilla.org/show_bug.cgi?id=1654116
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DisplayNames
> Intl.DisplayNames has been added to FF86

- api/ServiceWorkerGlobalScope.json
> Add Safari and Safari iOS versions for skipWaiting

- api/Clients.json
> Add Safari and Safari iOS versions for Clients

- html/manifest/description.json
- html/manifest/display.json
- html/manifest/icons.json
- html/manifest/name.json
- html/manifest/orientation.json
- html/manifest/scope.json
- html/manifest/short_name.json
- html/manifest/start_url.json
- html/manifest/theme_color.json
Look at the commit messages for sources
> Added in manifest info

- api/Window.json
> fix: window.scrollTo safari compatibility

- api/Cache.json
Fixes https://github.com/mdn/sprints/issues/3991
> Mark Cache API + methods non-experimental

- svg/elements/textPath.json
> Remove never-supported SVG textPath method

- api/NavigatorLanguage.json
See https://github.com/mdn/browser-compat-data/pull/8035#discussion_r546213534
> Remove Chromium notes for navigator.language/languages

- css/selectors/first-letter.json
Working on https://github.com/mdn/content/issues/2512
FF87 includes support for this feature, it still appears unsupported anywhere else.
> Adding FF87 support for digraphs

- api/XMLHttpRequest.json
This qualifies as an irrelevant feature:
https://github.com/mdn/browser-compat-data/blob/master/docs/data-guidelines.md#removal-of-irrelevant-features
> Remove XMLHttpRequest.sendAsBinary entry

- api/AuthenticatorAssertionResponse.json
- api/AuthenticatorAttestationResponse.json
- api/AuthenticatorResponse.json
- api/Credential.json
- api/HTMLMediaElement.json
- api/PublicKeyCredential.json
- api/PublicKeyCredentialCreationOptions.json
- api/PublicKeyCredentialRequestOptions.json
- browsers/safari_ios.json
As discussed when considering adding 14.3:
https://github.com/mdn/browser-compat-data/pull/8838#discussion_r563202188
> Merge Safari iOS 13.3 into 13

- api/Document.json
- api/HTMLIFrameElement.json
I have edited the chromestatus.com entry to fix the mistake.
> Remove notes about an error on chromestatus.com

- html/elements/iframe.json
According to the description of https://github.com/mdn/browser-compat-data/pull/7153#issuecomment-786367842
> Update note of sandbox="allow-same-origin"

- browsers/safari_ios.json
https://developer.apple.com/documentation/ios-ipados-release-notes/ios-ipados-14_5-beta-release-notes
> Add entry for iOS 14.5 beta

- api/Animation.json
- api/AnimationPlaybackEvent.json
- api/AnimationTimeline.json
https://storage.googleapis.com/chromium-find-releases-static/9cd.html#9cdcb106b0bcfee75cf3e94576fd48c055cc4bd6
There is no Samsung Internet based on M84 yet.
> Mark parts of the Web Animations API shipped in Chromium 84

- api/PerformancePaintTiming.json
Tested with BrowsterStack
Release docs:
https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/84#apis
> PerformancePaintTiming in Firefox

- api/MimeType.json
- api/MimeTypeArray.json
- api/NavigatorPlugins.json
- api/Plugin.json
- api/PluginArray.json
https://html.spec.whatwg.org/multipage/obsolete.html#navigatorplugins
Related mdn/content change: https://github.com/mdn/content/pull/2869
> Deprecate NavigatorPlugins, its subfeatures, and related objects

- css/selectors/any-link.json
- css/selectors/link.json
- css/selectors/visited.json
Second attempt at fixing the issue discussed here: https://github.com/mdn/content/issues/2506
Follow up to: https://github.com/mdn/browser-compat-data/pull/9305
> updating link pseudos

- browsers/safari_ios.json
As requested in https://github.com/mdn/browser-compat-data/issues/7328#issuecomment-799594426
> iOS Safari -> Safari on iOS

- api/Permissions.json
https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/renderer/modules/permissions/permissions.idl;l=14;drc=83361f47040ea6253ee1b528160a6af03309ab24
Mirror the Opera data.
Samsung Internet doesn't do flags, so mark that as false.
> Put navigator.permissions.request/requestAll/revoke behind a flag

- api/AuthenticatorAttestationResponse.json
Thanks to #9491, this was a simple effort to fix #6922.
> Mirror api.AuthenticatorAttestationResponse.getTransports

- browsers/firefox_android.json
Closes https://github.com/mdn/yari/issues/1672
See also https://github.com/mdn/browser-compat-data/issues/7328
> Firefox Android -> Firefox for Android

- GOVERNANCE.md
- docs/contributing.md
- docs/publishing.md
- docs/using-confluence.md
Related: https://github.com/mdn/browser-compat-data/issues/6292
> Change branch name in docs to "main"

- api/Window.json
Follow-up to a simple oversight in https://github.com/mdn/browser-compat-data/pull/9601.
Part of https://github.com/mdn/browser-compat-data/pull/9610.
> Update webkitConvertPointFromNodeToPage/PageToNode again

- css/at-rules/media.json
judging from the references given in #9171 this was implemented in `firefox preview` later released as `firefox 79 daylight`
> css.at-rules.media.prefers-color-scheme - Firefox Android fixes #9171

- api/FormData.json
> Update api.FormData.get support for Safari

- api/WorkerNavigator.json
This fixes an URL first added in #9199.
> Fix api.WorkerNavigator.serial.mdn_url

- browsers/chrome.json
- browsers/chrome_android.json
- browsers/webview_android.json
Hello everyone, everything good?
In that PR, I updated the docs to version 90 of Chrome.
According to [Chrome Status](https://www.chromestatus.com/features/schedule), 92 is the nightly version.
😉
> Updates chrome to version 90

- javascript/builtins/FinalizationRegistry.json
- javascript/builtins/WeakRef.json
This is now in the main ECMA-262 spec
> Update spec URLs for WeakRef

- javascript/builtins/AggregateError.json
- javascript/builtins/Promise.json
- javascript/builtins/String.json
- javascript/operators/logical_and_assignment.json
- javascript/operators/logical_nullish_assignment.json
- javascript/operators/logical_or_assignment.json
- javascript/operators/optional_chaining.json
- javascript/statements.json
All these proposals are merged into the main spec.
> Update proposal URLs to main ECMA-262 spec

- javascript/builtins/intl/DateTimeFormat.json
- javascript/builtins/intl/DisplayNames.json
- javascript/builtins/intl/ListFormat.json
All these proposals are merged into the main spec.
> Update intl proposal URLs to main ECMA 402 spec

- api/AbstractWorker.json
- api/AudioTrack.json
- api/AudioTrackList.json
- api/BroadcastChannel.json
- api/CanvasGradient.json
- api/CanvasPattern.json
- api/CloseEvent.json
- api/CustomElementRegistry.json
> Spec URL normalization: AbstractWorker to CustomElementRegistry

- api/CanvasRenderingContext2D.json
> Spec URL normalization: CanvasRenderingContext2D

- api/Document.json
> Spec URL normalization: Document object

- api/DOMParser.json
- api/DataTransfer.json
- api/DataTransferItem.json
- api/DataTransferItemList.json
- api/DedicatedWorkerGlobalScope.json
- api/DragEvent.json
> Spec URL normalization: DOMParser to DragEvent

- api/EventSource.json
- api/FileList.json
- api/FormDataEvent.json
- api/GlobalEventHandlers.json
> Spec URL normalization: EventSource to GlobalEventHandlers

- api/HTMLAnchorElement.json
- api/HTMLAreaElement.json
- api/HTMLAudioElement.json
- api/HTMLButtonElement.json
- api/HTMLCanvasElement.json
- api/HTMLDialogElement.json
- api/HTMLElement.json
- api/HTMLFormControlsCollection.json
- api/HTMLFormElement.json
> Spec URL normalization: HTMLAnchorElement to HTMLFormElement

- api/HTMLImageElement.json
- api/HTMLInputElement.json
- api/HTMLLabelElement.json
- api/HTMLMediaElement.json
- api/HTMLMeterElement.json
> Spec URL normalization: HTMLImageElement to HTMLMeterElement

- api/HTMLObjectElement.json
- api/HTMLOptionElement.json
- api/HTMLOutputElement.json
- api/HTMLProgressElement.json
- api/HTMLSelectElement.json
- api/HTMLSlotElement.json
- api/HTMLTableElement.json
- api/HTMLTableRowElement.json
> Spec URL normalization: HTMLObjectElement to HTMLTableRowElement

- css/selectors/active.json
- css/selectors/autofill.json
- css/selectors/checked.json
- css/selectors/default.json
- css/selectors/dir.json
- css/selectors/disabled.json
- css/selectors/enabled.json
- css/selectors/focus.json
- css/selectors/in-range.json
- css/selectors/indeterminate.json
- css/selectors/invalid.json
- css/selectors/link.json
- css/selectors/optional.json
- css/selectors/out-of-range.json
- css/selectors/read-only.json
- css/selectors/read-write.json
- css/selectors/required.json
- css/selectors/target.json
- css/selectors/valid.json
- css/selectors/visited.json
- html/elements/dd.json
- html/elements/footer.json
- html/elements/legend.json
- html/elements/link.json
- html/global_attributes.json
- http/headers/cross-origin-embedder-policy.json
- http/headers/cross-origin-opener-policy.json
- http/headers/feature-policy.json
- javascript/builtins/Promise.json
> Spec URL normalization: css, html, http, javascript

- api/Element.json
See https://github.com/mdn/browser-compat-data/issues/10136
> Normalize DOM spec URLs: Element object

- api/Document.json
- api/DocumentFragment.json
- api/DocumentType.json
See https://github.com/mdn/browser-compat-data/issues/10136
> Normalize DOM spec URLs: Document* objects

- api/Event.json
- api/EventTarget.json
See https://github.com/mdn/browser-compat-data/issues/10136
> Normalize DOM spec URLs: Event* objects

- api/HID.json
Add browser support data for HID.
Later I'll also do a pull request about the corresponding page.
data source: https://caniuse.com/webhid
> compat data for HID 

- api/Request.json
While working on #9916, a number of interesting issues were found with the Chrome Android (and related browsers).  This PR aims to correct them, based upon the results manually from the mdn-bcd-collector project.
> Fix mobile Chromium data for Request API

- api/Response.json
Tested with https://mdn-bcd-collector.appspot.com/tests/api/Response/redirected
Fixes #9595
> Update api.Response.redirected for Safari

- api/WorkerNavigator.json
This PR adds real values for Internet Explorer for the `WorkerNavigator` API, based upon results from the [mdn-bcd-collector](https://mdn-bcd-collector.appspot.com) project (v3.0.2).  Results are manually confirmed for accuracy.
Tests Used: https://mdn-bcd-collector.appspot.com/tests/api/WorkerNavigator
> Add IE versions for WorkerNavigator API

- api/WebGL2RenderingContext.json
Heads-up: This one adds 100 spec URLs.
> Add WebGL2RenderingContext spec URLs

- api/Window.json
Heads-up: This one adds 114 URLs.
> Add Window object spec URLs

- api/WindowClient.json
- api/WindowEventHandlers.json
- api/WindowOrWorkerGlobalScope.json
This change adds spec URL for WindowClient, WindowEventHandlers, and WindowOrWorkerGlobalScope.
> Add various Window* objects spec URLs

- css/properties/list-style-type.json
https://bugs.webkit.org/show_bug.cgi?id=167729
> Added list-style-type string support for Safari 14.1/iOS 14.5

- javascript/statements.json
Just adds a link the Firefox bug for implementing worker modules.
> Add a link to worker modules bug

- api/PaymentRequest.json
Copied from onpaymentmethodchange.
I think there should be a linter for this 🤔
A simple data copy.
> Update data for paymentmethodchange event

- api/SVGUseElement.json
These features are irrelevant per this guideline:
Spec issue: https://github.com/w3c/svgwg/issues/852
> Remove instanceRoot and animatedInstanceRoot entries

- api/SVGGraphicsElement.json
Add mdn link for SVGGraphicsElement.getBBox
> Add mdn link for SVGGraphicsElement.getBBox

- api/ElementInternals.json
Another API I will be working on, adds the spec and MDN URLs.
> Adds spec and MDN URLs for ElementInternals

- api/Request.json
MDN removal: https://github.com/mdn/content/pull/5757
> Remove api.Request.context as irrelevant

- api/SVGSVGElement.json
MDN removal: https://github.com/mdn/content/pull/5758
> Remove api.SVGSVGElement.viewport as irrelevant

- browsers/firefox.json
- browsers/firefox_android.json
Set Firefox and Firefox Android 89 as stable release.
https://www.mozilla.org/en-US/firefox/89.0/releasenotes/
https://www.mozilla.org/en-US/firefox/android/89.0/releasenotes/
> Set Firefox 89 as stable

- api/Element.json
> Remove Element's currentStyle and runtimeStyle as irrelevant

- api/InputDeviceCapabilities.json
Added spec_url to InputDeviceCapabilities()
> Add spec_url to InputDeviceCapabilities constructor

- api/InputDeviceInfo.json
On both InputDeviceInfo and InputDeviceInfo.getCapabilities
> Add spec_url to InputDeviceInfo(.*)

- api/FileSystemWritableFileStream.json
FileSystemWritaleFileStream.json had no mdn_url and spec_url entries. This PR fixes it.
> Add spec_url  and mdn_url to FileSystemWritableFileStream.json

- css/properties/inset-block-end.json
- css/properties/inset-block-start.json
- css/properties/inset-block.json
- css/properties/inset-inline-end.json
- css/properties/inset-inline-start.json
- css/properties/inset-inline.json
- css/properties/inset.json
Updated browser support for the inset css properties.
Chrome 87 added support, this MR just mirrors this to other chromium based browsers.
> Update browser support for inset css properties

- api/FetchEvent.json
Add spec_url  and mdn_url to FetchEvent.preloadResponse
> Add spec_url  and mdn_url to FetchEvent.preloadResponse

- api/Navigator.json
Add the two fields to the two entries documented on MDN and bcd for the Badging API.
> Add mdn_url and spec_url for Navigator.{clear,set}AppBadge

- api/RTCError.json
Add missing mdn_url and spec_url that does exists.
> Fix RTCError 

- api/RTCRtpSender.json
A mdn_url and a spec_url were missing
> Add mdn_url et spec_url to RTCRtpSender.setStreams

- api/ValidityState.json
Add mdn_url and spec_url to several properties of ValidityState
> Add mdn_url to spec_url to more properties of ValidityState

- api/VTTRegion.json
Added mdn_url and spec_url to VTTRegion and children
> Add mdn_url and spec_url to VTTRegion and children

- javascript/classes.json
Private methods and the `in` ergonomic brand check have been (or will be) added to browsers at different times than private class fields, so I added them.
> Added private class methods and 'in' to classes.json

- api/TextTrackCueList.json
- api/TextTrackList.json
A few spec_url and mdn_url were missing.
> Add missing spec_url & mdn_url to TextTrack*.json

- api/Window.json
These three methods are on the standard track and documented on mdn.
> Add (mdn|spec)_url for show*FilePicker on Window

- html/manifest/background_color.json
- html/manifest/display.json
- html/manifest/icons.json
- html/manifest/orientation.json
- html/manifest/scope.json
- html/manifest/screenshots.json
- html/manifest/short_name.json
- html/manifest/start_url.json
Each commit message has links to the data source, but the majority of data came from https://github.com/WebKit/WebKit/commit/ca1e8ed90d104c96f3949d250d442b317ea279b6 and https://firt.dev/ios-14/#web-app-manifest-support
> Update Safari iOS data in Web App Manifest

- api/Element.json
See https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines.md#parameters-and-parameter-object-features
> Fix the name, description and status of element.attachShadow subfeature

- docs/testing.md
A new contributor ran into some difficulty with dependencies, in part thanks to some unclear language in `testing.md`. This is a very quick rewrite of that document, to be a bit more task oriented.
> Revise testing docs

- css/at-rules/page.json
- css/at-rules/property.json
Some CSS features got missed last time Samsung Internet was updated here
Generated from the Mirror Script
#11181
> Add missed CSS features from Samsung Internet 14

- css/properties/grid-template-columns.json
- css/properties/grid-template-rows.json
Fixes https://github.com/mdn/content/issues/6238
Related MDN change: https://github.com/mdn/content/pull/6239
> Fix MDN url for css/properties/grid-template-columns|rows

- css/types/basic-shape.json
Some got their own mdn web docs pages (but not path()!) and I added the spec_url
> Fixes/Adds mdn_url and spec_url in css basic-shape values.

- css/types/image.json
Children already had them (and from the same spec)
> Add mdn_url and spec_url to <gradient>

- css/properties/place-content.json
- css/properties/place-items.json
- css/properties/place-self.json
These 3 properties had no bcd directly on them, but only on their subfeatures. I added it (taking the earliest one). That way mdn_url and spec_url are at the right level.
> Fix place-* css properties

- api/ServiceWorkerRegistration.json
ServiceWorkerRegistration.index was missing both the mdn_url and spec_url values.
> Add mdn & spec_url to ServiceWorkerRegistration.index

- test/spec-urls.test.js
Add comments to the spec exception list so that it becomes more clear why the exceptions exists and how they can be resolved in the future.
https://github.com/mdn/browser-compat-data/issues/11216#issuecomment-866918467
> Add comments to spec exception list

- api/DOMTokenList.json
- api/HTMLTableRowElement.json
- api/RTCPeerConnection.json
- api/URL.json
- api/Window.json
- javascript/builtins/Float32Array.json
- javascript/builtins/Float64Array.json
- javascript/builtins/Int16Array.json
- javascript/builtins/Int32Array.json
- javascript/builtins/Int8Array.json
- javascript/builtins/TypedArray.json
- javascript/builtins/Uint16Array.json
- javascript/builtins/Uint32Array.json
- javascript/builtins/Uint8Array.json
- javascript/builtins/Uint8ClampedArray.json
See https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines.md#parameters-and-parameter-object-features
> Rename argument to parameter in context of methods/constructors

- api/SVGAltGlyphElement.json
SVGAltGlyphElement.format spec_url was missing
> Add spec_url for SVGAltGlyphElement.format

- api/Worker.json
https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines.md#parameters-and-parameter-object-features
> Rename entries for Worker constructor parameters

- .github/workflows/ping-other-repos.yml
@sideshowbarker and I are debugging https://github.com/mdn/browser-compat-data/pull/11360. This is going to be merged momentarily.
> Debug ping workflow

- api/BluetoothRemoteGATTCharacteristic.json
Add spec URLs for the writeValueWithResponse and writeValueWithoutResponse methods that were added to MDN [here](https://github.com/mdn/content/pull/6436)
> Add spec URLs for BluetoothRemoteGattCharacteristic methods

- css/types/basic-shape.json
Add data for`ellipse()`.
Fixes: #11208
> Add data for CSS ellipse() method

- api/TransformStreamDefaultController.json
spec_url were missing on interface and children
> Add spec_url to TransformStreamDefaultController

- webextensions/manifest/protocol_handlers.json
Adding `matrix` URL scheme to web extensions manifest - see https://bugzilla.mozilla.org/show_bug.cgi?id=1688030#c14
Tests are actually failing my end - but due to a spec url issue which I _believe_ is unrelated to this PR (it doesn't contain any spec mods or additions)
https://github.com/mdn/content/issues/5377
> Adding matrix protocol to web extensions manifest

- api/LayoutShift.json
- api/LayoutShiftAttribution.json
Adds missing spec URLs for Layout Instability API interfaces https://wicg.github.io/layout-instability
> Spec URLs for layout instability API

- api/VisualViewport.json
Changed experimental to false as this API has at least 2 implementations.
> Removed experimental flag from VisualViewport data

- css/properties/user-select.json
Updates the support data for the `user-select` css property.
Mostly just copying Chrome data across to other blink browsers. And Firefox to Firefox android.
> Fix browser support data for `user-select` property

- css/properties/text-orientation.json
Added Opera and Opera Android support for unprefixed `text-orientation`
Copies blink support data across to Opera
> Added Opera support for unprefixed `text-orientation`

- browsers/firefox.json
- browsers/firefox_android.json
Update Firefox and Firefox Android to version 90
https://www.mozilla.org/en-US/firefox/90.0/releasenotes/
https://www.mozilla.org/en-US/firefox/android/90.0/releasenotes/
> Set Firefox 90 as release version

- css/types/basic-shape.json
> `clip-path` works from FF 54

- api/CSSTransformValue.json
- api/CSSUnparsedValue.json
- api/CustomStateSet.json
- api/DOMTokenList.json
- api/FileSystemDirectoryHandle.json
- api/FormData.json
- api/Headers.json
- api/KeyboardLayoutMap.json
- api/MediaKeyStatusMap.json
- api/NodeList.json
- api/StylePropertyMapReadOnly.json
- api/URLSearchParams.json
- api/XRInputSourceArray.json
Fixes https://github.com/mdn/browser-compat-data/issues/11426.
> Remove spec_urls to Web IDL iterable/maplike/setlike declarations

- api/XRSession.json
Content PR: https://github.com/mdn/content/pull/6961
> Add spec/mdn urls to XRSession.interactionMode

- api/SVGTransformList.json
This PR is a part of a project to add missing interfaces and interface features to BCD that are from an active spec (including WICG specs) and is supported in at least one browser.  This particular PR adds the missing features of the SVGTransformList API, populating the results using data from the [mdn-bcd-collector](https://mdn-bcd-collector.appspot.com) project (v3.2.1).
Tests Used: https://mdn-bcd-collector.appspot.com/tests/api/SVGTransformList
> Add missing features for SVGTransformList API

- api/XRSession.json
Content PR https://github.com/mdn/content/pull/7067
> Add mdn/spec urls to XRSession.domOverlayState

- api/XRView.json
Content work: https://github.com/mdn/content/pull/7153
> Add mdn/spec urls to XRView.isFirstPersonObserver

- api/Window.json
Follow-up to https://github.com/mdn/browser-compat-data/pull/11690.
> Add clientInformation (alias of navigator) for all browsers

- javascript/operators/logical_and_assignment.json
- javascript/operators/logical_nullish_assignment.json
- javascript/operators/logical_or_assignment.json
Update support for logical assignment operators in Opera
Just copies blink support across to Opera and Opera Android
> Update support for logical assignment operators in opera

- css/at-rules/media.json
See: https://bugs.webkit.org/show_bug.cgi?id=215507
Test: https://codepen.io/danrichman/pen/wvdyjbo
> Add Safari 14.1 support of prefers-contrast

- css/properties/block-size.json
- css/properties/height.json
- css/properties/inline-size.json
- css/properties/max-block-size.json
- css/properties/max-height.json
- css/properties/max-inline-size.json
- css/properties/max-width.json
- css/properties/min-block-size.json
- css/properties/min-height.json
- css/properties/min-inline-size.json
- css/properties/min-width.json
- css/properties/width.json
Working on https://github.com/mdn/content/issues/6715
Adding the information about `fit-content()` to relevant properties.
> Add fit-content function

- javascript/builtins/Error.json
Adding cause option to Error constructor.
https://v8.dev/features/error-cause
> Adding cause option to Error constructor

- api/CustomEvent.json
- api/EventSource.json
- api/FileReader.json
- api/FormData.json
- api/IDBCursorWithValue.json
- api/IDBFactory.json
- api/IDBIndex.json
- api/IDBKeyRange.json
- api/IDBObjectStore.json
- api/IDBOpenDBRequest.json
- api/IDBRequest.json
- api/IDBTransaction.json
- api/IDBVersionChangeEvent.json
- api/MessagePort.json
- api/PerformanceEntry.json
- api/SecurityPolicyViolationEvent.json
- api/WindowOrWorkerGlobalScope.json
This PR sets real values for worker support across various PRs.  The results were collected using tests from the mdn-bcd-collector project.
> Add/correct data for worker support for various APIs

- api/XRCPUDepthInformation.json
- api/XRDepthInformation.json
- api/XRFrame.json
- api/XRSession.json
- api/XRWebGLBinding.json
- api/XRWebGLDepthInformation.json
> Add mdn_urls for WebXR Depth Sensing features

- css/types/transform-function.json
> Typo in css.types.transform-function.translate3d

- api/Bluetooth.json
- api/BluetoothCharacteristicProperties.json
- api/BluetoothDevice.json
- api/BluetoothRemoteGATTCharacteristic.json
- api/BluetoothRemoteGATTDescriptor.json
- api/BluetoothRemoteGATTServer.json
- api/BluetoothRemoteGATTService.json
- api/BluetoothUUID.json
- api/Navigator.json
Link to https://crbug.com/1100993 for all interfaces and navigator.bluetooth.
> Link WebView bug for Web Bluetooth support

- css/types/filter-function.json
> Fix typo constrast->contrast

- api/Request.json
Deno supports fetch upload streaming.
https://deno.com/blog/v1.7#support-for-fetch-request-body-streaming
> Deno supports fetch upload streaming

- api/XRFrame.json
- api/XRHitTestResult.json
- api/XRHitTestSource.json
- api/XRRay.json
- api/XRSession.json
- api/XRTransientInputHitTestResult.json
- api/XRTransientInputHitTestSource.json
I'm documenting all of this on MDN.
> Add urls for WebXR Hit Test features

- javascript/builtins/webassembly/WebAssembly.json
https://deno.com/blog/v1.12#streaming-instantiation-and-async-compilation-support-for-webassembly
> Deno supports WebAssembly.compileStreaming

- api/AbortController.json
Implemented in all browsers + Deno + Node.
> AbortController is not experimental

- css/properties/border-block-color.json
- css/properties/border-block-style.json
- css/properties/border-block-width.json
- css/properties/border-block.json
- css/properties/border-inline-color.json
- css/properties/border-inline-style.json
- css/properties/border-inline-width.json
- css/properties/border-inline.json
- css/properties/margin-block.json
- css/properties/margin-inline.json
- css/properties/padding-block.json
Fixes https://github.com/mdn/browser-compat-data/issues/11383.
> Mirror Chrome to Edge for CSS features shipped in Chrome 87

- api/UIEvent.json
MDN removal: https://github.com/mdn/content/pull/8350
> Remove UIEvent.isChar as irrelevant

- api/XRView.json
I'm going to write docs for these.
> Add mdn_urls for XRView.{recommendedViewportScale,requestViewportScale}

- api/_globals/atob.json
- api/_globals/btoa.json
- api/_globals/caches.json
- api/_globals/clearInterval.json
- api/_globals/clearTimeout.json
- api/_globals/createImageBitmap.json
- api/_globals/fetch.json
- api/_globals/isSecureContext.json
- api/_globals/origin.json
- api/_globals/queueMicrotask.json
- api/_globals/setInterval.json
- api/_globals/setTimeout.json
- api/_globals/trustedTypes.json
This PR updates the data for the API globals, specifically the worker support data.  Some of these features needed to be changed for consistency as well.  All data comes from the mdn-bcd-collector project v3.1.12.
> Update data for API globals

- api/IDBTransaction.json
- api/MediaError.json
- api/Performance.json
- api/SubmitEvent.json
- css/properties/overflow.json
- css/selectors/autofill.json
- http/headers/cross-origin-embedder-policy.json
- http/headers/cross-origin-opener-policy.json
Added preview entries for recent Safari TP additions.
https://webkit.org/blog/11962/release-notes-for-safari-technology-preview-131/
https://webkit.org/blog/11958/release-notes-for-safari-technology-preview-130
https://webkit.org/blog/11951/release-notes-for-safari-technology-preview-129/#:~:text=Unprefixed%20%3Aautofill%20pseudo-class
https://webkit.org/blog/11925/release-notes-for-safari-technology-preview-128/#:~:text=in%20SourceBuffer%20(r278603)-,Performance%20API,-Implemented%20performance.timeOrigin
> Updated support data to include recent Safari TP versions

- css/properties/appearance.json
Corrected the Samsung Internet support data for the `appearance` property.
Just copied across blink support data.
> Correct Samsung Internet support for `appearance`

- api/Selection.json
Related MDN PR: https://github.com/mdn/content/pull/8767
> Selection»selectAllChildren isn’t experimental

- GOVERNANCE.md
Primarily for branding purposes, I have renamed myself and switched my username.  This PR is to update my name and username accordingly in the governance document.
> Update my name + username in governance doc

- api/BluetoothCharacteristicProperties.json
> Add spec_url to writableAuxiliaries

- api/ResizeObserver.json
As discussed in https://github.com/mdn/content/issues/8622
> Adding options parameter to ResizeObserver

- scripts/fix-browser-order.js
- scripts/fix-feature-order.js
- scripts/migrations/002-remove-webview-flags.js
- scripts/migrations/002-remove-webview-flags.test.js
- scripts/release-pulls.js
- scripts/release-stats.js
- scripts/release-utils.js
> Misc cleanup in scripts/

- api/MediaSource.json
Media source should no longer be marked as experimental so I've set it to false.
Based on existing data.
> Unmark Media Source as experimental

- api/DeviceMotionEvent.json
- api/DeviceMotionEventAcceleration.json
- api/DeviceMotionEventRotationRate.json
- api/DeviceOrientationEvent.json
- api/Window.json
This is all standards track and no longer experimental.
> Update statuses for devicemotion and deviceorientaton(absolute) events

- GOVERNANCE.md
Recently, the currently active owners of BCD decided to invite Luca Casonato (from the Deno project) to become a peer on the project. We're pleased to announce that Luca has accepted the invitation. Thank you, Luca!
@lucacasonato do let me know if you want any changes to the way you appear in the peers list. Thank you again!
Tasks:
Luca has already accepted the Mozilla Commit Access Requirements, so this closes https://github.com/mdn/mdn/issues/124.
> Add Luca Casonato to peers

- api/Window.json
This is an irrelevant feature per guideline:
> Remove window.pkcs11 entry

- api/GlobalEventHandlers.json
#12078 copy-pasted them in a wrong way 😛
> Fix wrong alternative_name for onanimation* events

- api/CompositionEvent.json
- api/MessageEvent.json
- api/MouseEvent.json
- api/StorageEvent.json
- api/UIEvent.json
Add missing spec_url and also `standard_track: true` (there is no linter for this 🤔, they should always coexist, no? Filed #12685 for this)
> Add spec_url for init*Event()

- api/URLPattern.json
I added MDN pages for URLPattern the other day. This adds links to those to the
BCD.
> URLPattern: add mdn urls

- api/CanvasRenderingContext2D.json
- api/EXT_color_buffer_float.json
- api/EXT_float_blend.json
- api/EXT_frag_depth.json
- api/HTMLSourceElement.json
- api/IDBCursor.json
- api/IDBTransaction.json
- api/ImageBitmapRenderingContext.json
- api/MediaError.json
- api/Performance.json
- api/PerformanceNavigationTiming.json
- api/PerformanceObserver.json
- api/SecurityPolicyViolationEvent.json
- api/SubmitEvent.json
- api/WEBGL_color_buffer_float.json
- api/WEBGL_draw_buffers.json
- api/WEBGL_multi_draw.json
- api/_globals/createImageBitmap.json
- browsers/safari.json
- browsers/safari_ios.json
- css/properties/list-style-type.json
This PR largely is based on mdn-results-collector, plus additions to list-style-type.
See mdn-results-collector. list-style-type is documented in release notes and per https://github.com/WebKit/WebKit/commit/20df2033c26bc4f5e4c78572259f3e46335d307d appears in the release tags.
Most of these are changes that landed in Safari after #10898 was submitted.
> Further Safari 15 updates

- api/Crypto.json
Support for method added in https://bugzilla.mozilla.org/show_bug.cgi?id=1723674
Other docs work being tracked in https://github.com/mdn/content/issues/10143
> FF95 supports Crypto.randomUUID

- api/Element.json
Quote the strings, and add the first argument for the NS variant.
> Improve descriptions of all_elements_selector entries

- api/MouseEvent.json
Mark offsetX and offsetY as not experimental.
These are almost universally supported.
https://github.com/mdn/content/issues/10120
> Mark offsetX and offsetY as not experimental

- http/headers/feature-policy.json
Remove `vr` directive of `Feature-Policy` as "obsolete" feature since it was never supported in any release builds.
> Remove http.headers.vr

- api/Crypto.json
Fix for Node.js  version for crypto.randomUUID.
Function randomUUID was tested on v.14.7.0, here's results
Issue #12574.
> Update Node.js version for Crypto.randomUUID API(mdn#12574)

- api/AudioContext.json
- api/AudioDestinationNode.json
- api/AudioListener.json
- api/AudioProcessingEvent.json
- api/BiquadFilterNode.json
- api/CSS.json
- api/CSSStyleDeclaration.json
- api/CacheStorage.json
- api/ChannelMergerNode.json
- api/ChannelSplitterNode.json
- api/ConvolverNode.json
- api/DelayNode.json
- api/DynamicsCompressorNode.json
- api/Element.json
- api/FontFaceSet.json
- api/GainNode.json
- api/GeolocationPositionError.json
- api/HTMLAllCollection.json
- api/HTMLMediaElement.json
- api/Range.json
- api/ServiceWorkerRegistration.json
- api/URL.json
- api/WaveShaperNode.json
- api/XMLHttpRequest.json
This PR mirrors Safari to Safari iOS, focusing on the straightforward changes.
> Mirror Safari to Safari iOS

- api/Navigator.json
- api/Serial.json
Adds Opera version for Web Serial API
Just copies Chrome support across to Opera
Closes https://github.com/mdn/browser-compat-data/issues/13386
> Set Opera as supporting Web Serial API

- browsers/opera_android.json
Hello guys!
In this PR includes the release notes for Opera Android 65.
> Include release notes for Opera Android 65

- api/CSS.json
Somehow it currently points to CSS Conditional Rules.
> `namespace CSS` is defined in CSSOM, set `spec_url` as such

- css/properties/font-variation-settings.json
The spec url for css property `font-variation-settings` is incorrect. This updates it.
Fixes https://github.com/mdn/content/issues/10535
> Updating font-variation-settings property spec url

- .github/workflows/release.yml
Make sure every step in the release workflow actually runs a command.
Fixes a typo caught by https://github.com/mdn/browser-compat-data/actions/runs/1499363355
Follow up to https://github.com/mdn/browser-compat-data/pull/13714.
> Fix syntax error in release workflow

- .github/workflows/release.yml
Fix an error in our release GitHub Actions workflow, as reported in https://github.com/mdn/browser-compat-data/actions/runs/1499388115.
Follow ups to https://github.com/mdn/browser-compat-data/pull/13714 and https://github.com/mdn/browser-compat-data/pull/13715.
> Fix improperly nested name in release GitHub Actions workflow

- api/PermissionStatus.json
Adds MDN URL for recently created page at:
https://developer.mozilla.org/en-US/docs/Web/API/PermissionStatus/name
N/A
N/A
> Add PermissionStatus.name MDN URL

- .github/workflows/release.yml
- docs/publishing.md
Speed up the release process by automatically posting data quality stats to relevant issues.
I'm all GitHub Actions PRs all the time now, apparently.
> Comment with updated data stats automatically

- html/manifest/share_target.json
https://www.chromestatus.com/feature/6124071381106688
> Add share_target compat data.

- api/XRSession.json
See https://github.com/mdn/browser-compat-data/pull/13595 for the proposed guideline.
> XRSession: Use single entry for events

- api/XRSystem.json
Use a single entry for the devicechange event.
Content work https://github.com/mdn/content/pull/10474
> XRSystem: Use single entry for event

- api/XRReferenceSpace.json
Use a single entry for this event.
Content work: https://github.com/mdn/content/pull/10473
> XRReferenceSpace: Use single entry for event

- api/AudioContext.json
- api/CanvasRenderingContext2D.json
- api/Comment.json
- api/DOMParser.json
- api/DragEvent.json
- api/Element.json
- api/FetchEvent.json
- api/FormData.json
- api/HashChangeEvent.json
- api/IDBCursor.json
- api/IDBIndex.json
- api/IDBKeyRange.json
- api/MediaDevices.json
- api/MediaRecorder.json
- api/MediaStreamTrack.json
- api/MessageEvent.json
- api/Navigator.json
- api/RTCIceCandidate.json
- api/RTCPeerConnection.json
- api/Request.json
- api/Response.json
- api/SVGSVGElement.json
- api/SubmitEvent.json
- api/WebGL2RenderingContext.json
- api/Window.json
- api/WindowEventHandlers.json
- api/_globals/createImageBitmap.json
This PR mirrors the data from Firefox to Firefox Android for the API data.  This PR focuses on changes where Firefox Android is true/null and the resulting value is truthy.
> Mirror Firefox Android data (nonreal to version) for api/

- css/properties/initial-letter.json
This was copypasta in https://github.com/mdn/browser-compat-data/pull/13879.
> Fix WebKit bug URLs for initial-letter

- api/AbortSignal.json
- api/Blob.json
- api/BroadcastChannel.json
- api/ByteLengthQueuingStrategy.json
- api/CompressionStream.json
- api/CountQueuingStrategy.json
- api/DecompressionStream.json
- api/ReadableByteStreamController.json
- api/ReadableStream.json
- api/ReadableStreamBYOBReader.json
- api/ReadableStreamBYOBRequest.json
- api/ReadableStreamDefaultController.json
- api/ReadableStreamDefaultReader.json
- api/SubtleCrypto.json
- api/TextDecoderStream.json
- api/TextEncoderStream.json
- api/TransformStream.json
- api/TransformStreamDefaultController.json
- api/URL.json
- api/WritableStream.json
- api/WritableStreamDefaultController.json
- api/WritableStreamDefaultWriter.json
- browsers/nodejs.json
Updates various Node.js Web API compatibilities
> Update Node.js details

- api/Blob.json
- api/BroadcastChannel.json
- api/ByteLengthQueuingStrategy.json
- api/CountQueuingStrategy.json
- api/ReadableByteStreamController.json
- api/ReadableStream.json
- api/ReadableStreamBYOBReader.json
- api/ReadableStreamBYOBRequest.json
- api/ReadableStreamDefaultController.json
- api/ReadableStreamDefaultReader.json
- api/TextDecoderStream.json
- api/TextEncoderStream.json
- api/TransformStream.json
- api/WritableStream.json
- api/WritableStreamDefaultController.json
- api/WritableStreamDefaultWriter.json
Make notes on certain Node APIs more consistent, with code formatting and separate notes for separate topics.
Follow up to https://github.com/mdn/browser-compat-data/pull/12154, where I got a little merge happy.
> Separate and code format certain Node.js notes

- .github/workflows/release.yml
The API real values goal was reached and the issue has been closed.
We no longer need to produce comments like this one: https://github.com/mdn/browser-compat-data/issues/6369#issuecomment-988155412
> No longer comment on API statistic issue

- api/VirtualKeyboard.json
Update per new events guideline.
No content update needed because the docs aren't written yet.
> VirtualKeyboard: ongeometrychange -> geometrychange_event

- browsers/firefox.json
- browsers/firefox_android.json
Hey guys!
The current version of firefox was updated on December 7th.
> Update firefox to current version

- javascript/operators/await.json
Link to the relevant section on the page.
N/A
N/A
> Link to relevant section on the page

- css/types/length.json
> Remove mozmm CSS unit

- api/_globals/crossOriginIsolated.json
crossOriginIsolated is no longer experimental, this PR updates the data to reflect that.
Based on existing support data it's available in all three browser engines.
> Unmark crossOriginIsolated as experimental

- browsers/deno.json
> Update browsers for Deno 1.17 release

- api/SubtleCrypto.json
https://deno.com/blog/v1.17#improvements-to-the-web-cryptography-api
> SublteCrypto updates for Deno 1.17

- api/SVGGraphicsElement.json
> Add note regarding api.SVGGraphicsElement.getScreenCTM() issue

- api/AnimationTimeline.json
This PR updates and corrects the real values for WebView Android for the `AnimationTimeline` API, based upon results from the [mdn-bcd-collector](https://mdn-bcd-collector.appspot.com) project (v4.0.0).
Tests Used: https://mdn-bcd-collector.appspot.com/tests/api/AnimationTimeline
> Update WebView versions for AnimationTimeline API

- css/at-rules/font-face.json
Adds browser support information for using `format("*-variations")` in the `src` property of the `@font-face` rule. Also rewords the `format(keyword)` entry for brevity and symmetry.
I was unsure what to do about mobile browsers for which I can't identify the initial version that supports the feature...
Used information from [Can I Use](https://caniuse.com/variable-fonts) and confirmed in Browserstack with [this test case](https://danburzo.ro/demos/font-face-src.html), reproduced below:
<details>
<summary>font-face-src.html</summary>
```html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>@font-face/src syntax test</title>
<style type='text/css'>
/*
AdobeBlank font licensed under OFL 1.1.
A copy of the …
```
> css.at-rules.font-face.src: add browser support for format("*-variations")

- api/Crypto.json
This PR updates and corrects the real values for Opera and Opera Android for the `randomUUID` member of the `Crypto` API, based upon results from the [mdn-bcd-collector](https://mdn-bcd-collector.appspot.com) project (v4.0.0).
Tests Used: https://mdn-bcd-collector.appspot.com/tests/api/Crypto/randomUUID
> Update Opera versions for api.Crypto.randomUUID

- api/Window.json
This PR updates and corrects the real values for all browsers for the `Window` API, based upon results from the [mdn-bcd-collector](https://mdn-bcd-collector.appspot.com) project (v4.0.0).
Tests Used: https://mdn-bcd-collector.appspot.com/tests/api/Window
> Update all browsers versions for Window API

- api/SharedWorkerGlobalScope.json
This PR updates and corrects the real values for Firefox and Firefox Android for the `name` member of the `SharedWorkerGlobalScope` API, based upon results from the [mdn-bcd-collector](https://mdn-bcd-collector.appspot.com) project (v4.0.0).
Tests Used: https://mdn-bcd-collector.appspot.com/tests/api/SharedWorkerGlobalScope/name
> Update Firefox versions for api.SharedWorkerGlobalScope.name

- api/EventSource.json
This PR updates and corrects the real values for Firefox and Firefox Android for the `EventSource` member of the `EventSource` API, based upon results from the [mdn-bcd-collector](https://mdn-bcd-collector.appspot.com) project (v4.0.0).
Tests Used: https://mdn-bcd-collector.appspot.com/tests/api/EventSource/EventSource
> Update Firefox versions for api.EventSource.EventSource

- api/GamepadHapticActuator.json
This PR updates and corrects the real values for WebView Android for the `GamepadHapticActuator` API, based upon results from the [mdn-bcd-collector](https://mdn-bcd-collector.appspot.com) project (v4.0.0).
Tests Used: https://mdn-bcd-collector.appspot.com/tests/api/GamepadHapticActuator
> Update WebView versions for GamepadHapticActuator API

- browsers/edge.json
This PR adds the version 99 of the Edge browser.
@foolip Please review.
> Add edge 99

- html/manifest/protocol_handlers.json
https://chromestatus.com/feature/5151703944921088
cc: @tomayac
> Adds member for protocol_handler to manifest section.

- api/Document.json
This also can't be considered experimental, since it is shipping in
Edge, Firefox and Safari.
> Link Chromium bug for Storage Access API

- api/SVGElement.json
This PR updates and corrects the real values for all browsers for the `className` member of the `SVGElement` API, based upon results from the [mdn-bcd-collector](https://mdn-bcd-collector.appspot.com) project (v4.0.0).
Tests Used: https://mdn-bcd-collector.appspot.com/tests/api/SVGElement/className
> Update all browsers versions for api.SVGElement.className

- api/SVGAnimatedTransformList.json
This PR updates and corrects the real values for all browsers for the `SVGAnimatedTransformList` API, based upon results from the [mdn-bcd-collector](https://mdn-bcd-collector.appspot.com) project (v4.0.0).
Tests Used: https://mdn-bcd-collector.appspot.com/tests/api/SVGAnimatedTransformList
> Update all browsers versions for SVGAnimatedTransformList API

- api/HTMLInputElement.json
- Fixes `mdn_url` those lead to 404
Fixes mdn/content#11248
> Update mdn_urls for HTMLInputElement api

- api/_globals/fetch.json
Unmarks certain fetch features as experimental as they have large browser support.
Based on existing data. Also copies a Blink number across to opera android.
> Unmark certain fetch features as experimental

- RELEASE_NOTES.md
I got a little ahead of myself with https://github.com/mdn/browser-compat-data/pull/14580.
> Add release stats v4.1.4

- api/SubtleCrypto.json
This release finalizes our Web Crypto implementation.
https://wpt.fyi/results/?label=master&label=experimental&product=chrome&product=deno&product=firefox&product=safari&aligned
> Update SubtleCrypto for Deno 1.18

- javascript/builtins/Function.json
> Mention NodeJS' behavior when running Function.call()

- browsers/safari.json
- browsers/safari_ios.json
Adds Safari 15.3, not aware of the particular changes atm so just adding the browser versions for now.
> Marked Safari 15.3 as current

- api/Sensor.json
Per the new events guideline.
Content work needed.
> Sensor: onxxx events -> xxx_events

- api/VideoTrackList.json
Per the new guideline: https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines.md#dom-events-eventname_event
Content work to be done.
> Single event entries for VideoTrackList

- css/at-rules/scroll-timeline.json
This is available in Firefox 97 - see https://bugzilla.mozilla.org/show_bug.cgi?id=1676791 or/and https://bugzilla.mozilla.org/show_bug.cgi?id=1676782 
This is available in Chrome, but I'm unsure of the version it was first available in. If anyone points me in the right direction I'm happy to add
Passes tests
Part of https://github.com/mdn/content/issues/9368
> Adding scroll-timeline css at rule

- api/AbortSignal.json
- api/BackgroundFetchRegistration.json
Per the new events guideline (Part of https://github.com/mdn/browser-compat-data/issues/14578).
Content work: https://github.com/mdn/content/pull/12865
> Events abort signal

- api/Animation.json
Per the new events guideline (Part of https://github.com/mdn/browser-compat-data/issues/14578).
Content work: https://github.com/mdn/content/pull/12882
> Adapt Animation events to new structure

- api/Worker.json
See https://github.com/mdn/content/pull/12899 for discussion about updating the BCD first
> Add mozilla bug for Worker modules

- svg/attributes/paint-order.json
Update svg: paint-order support in firefox
reference: https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/21#svg
> Update svg: paint-order support in firefox

- api/AudioTrackList.json
This PR adapts the AudioTrackList API to conform to the new events structure.  Part of work for #14578.
> Adapt AudioTrackList API to new events structure

- html/elements/output.json
This isn't right. There are `form` and `name` attributes for `<output>`, but no `for.form` and `form.name` something.
> Fix incorrectly nested attributes of <output>

- css/properties/animation-timeline.json
Adding the `animation-timeline` css property (take two)
Tests pass
https://bugzilla.mozilla.org/show_bug.cgi?id=1676791
I think there's quite a few issues that mention this, so I'll try to collate them here
https://github.com/mdn/content/issues/9368
https://github.com/mdn/content/issues/12942
https://github.com/mdn/content/issues/12903
> adding animation timeline

- css/properties/scroll-snap-type.json
https://bugzil.la/1737820 was marked as a duplicate of https://bugzil.la/1749352. I've changed the link in BCD (and added the dev-doc-needed flag to the open bug).
A continuation of https://github.com/mdn/browser-compat-data/pull/13654.
> Update scroll-snap-type bug link

- api/FileReader.json
This PR adapts the FileReader API to conform to the new events structure.
> Adapt FileReader API to new events structure

- api/FontFaceSet.json
This PR adapts the FontFaceSet API to conform to the new events structure.
> Adapt FontFaceSet API to new events structure

- api/OfflineAudioContext.json
This PR adapts the complete event of the OfflineAudioContext API to conform to the new events structure.
> Adapt api.OfflineAudioContext.oncomplete to new events structure

- api/Window.json
This PR adapts the appinstalled event of the Window API to conform to the new events structure.
> Adapt api.Window.onappinstalled to new events structure

- api/PictureInPictureWindow.json
This PR adapts the resize event of the PictureInPictureWindow API to conform to the new events structure.
> Adapt api.PictureInPictureWindow.onresize to new events structure

- javascript/builtins/TypedArray.json
Fixes https://github.com/mdn/content/issues/13815
> Update the TypedArray.prototype.set() spec URL

- api/EventSource.json
This PR adapts the EventSource API to conform to the new events structure.
> Adapt EventSource API to new events structure

- api/PresentationRequest.json
This PR adapts the connectionavailable event of the PresentationRequest API to conform to the new events structure.
> Adapt api.PresentationRequest.onconnectionavailable to new events structure

- api/Worker.json
This PR adapts the error event of the Worker API to conform to the new events structure.
> Adapt api.Worker.onerror to new events structure

- api/HTMLVideoElement.json
This PR adapts the HTMLVideoElement API to conform to the new events structure.
> Adapt HTMLVideoElement API to new events structure

- api/MediaRecorder.json
This PR adapts the MediaRecorder API to conform to the new events structure.
> Adapt MediaRecorder API to new events structure

- api/RTCIceTransport.json
This PR adapts the RTCIceTransport API to conform to the new events structure.
> Adapt RTCIceTransport API to new events structure

- api/HTMLMediaElement.json
This PR adapts the HTMLMediaElement API to conform to the new events structure.
> Adapt HTMLMediaElement API to new events structure

- api/MediaStreamTrack.json
This PR adapts the MediaStreamTrack API to conform to the new events structure.
> Adapt MediaStreamTrack API to new events structure

- api/RTCPeerConnection.json
This PR adapts the RTCPeerConnection API to conform to the new events structure.
> Adapt RTCPeerConnection API to new events structure

- api/MediaStream.json
This PR adapts the MediaStream API to conform to the new events structure.
> Adapt MediaStream API to new events structure

- css/types/image.json
Current URL points to draft that doesn't have conic gradients. I fixed link to be the same as conic-gradient().
> Fix spec URL of repeating-conic-gradient

- api/NavigationPreloadManager.json
As noted by @queengooborg ! This is in Safari and Chromium. FYI https://webkit.org/blog/12445/new-webkit-features-in-safari-15-4/
> NavigationPreloadManager - not experimental

- api/RemotePlayback.json
This PR adapts the RemotePlayback API to conform to the new events structure.
> Adapt RemotePlayback API to new events structure

- api/WindowClient.json
> Fix Safari support for api.WindowClient.navigate

- html/elements/meta.json
- http/headers/referrer-policy.json
Update for "Safari on iOS", Safari and IE.
The "notes" in IE is reprinted from https://caniuse.com/referrer-policy
see #14675
Fixes #14675
> Referrer-Policy - Update for "Safari on iOS", Safari and IE (#14675)

- api/MessagePort.json
This PR adapts the MessagePort API to conform to the new events structure.
> Adapt MessagePort API to new events structure

- api/HTMLElement.json
This PR adapts the HTMLElement API to conform to the new events structure.
> Adapt HTMLElement API to new events structure

- api/NDEFReader.json
This PR adapts the NDEFReader API to conform to the new events structure.
> Adapt NDEFReader API to new events structure

- api/Notification.json
This PR adapts the Notification API to conform to the new events structure.
> Adapt Notification API to new events structure

- api/WorkerGlobalScope.json
This PR adapts the WorkerGlobalScope API to conform to the new events structure.
> Adapt WorkerGlobalScope API to new events structure

- api/IDBRequest.json
This PR adapts the IDBRequest API to conform to the new events structure.
> Adapt IDBRequest API to new events structure

- api/Navigator.json
Fix https://github.com/mdn/browser-compat-data/issues/15441
> Fix duplicate news scheme label in registerProtocolHandler

- api/ServiceWorkerGlobalScope.json
This PR adapts the ServiceWorkerGlobalScope API to conform to the new events structure.
> Adapt ServiceWorkerGlobalScope API to new events structure

- css/types/global_keywords.json
Minor post-merge review fix for https://github.com/mdn/browser-compat-data/pull/15524.
https://github.com/mdn/browser-compat-data/pull/15524
> Update standad track for `revert-layer`

- css/properties/outline.json
Status of "invert" keyword of outline-color was copied to outline property.
> Copied "invert" status to outline

- javascript/operators/nullish_coalescing.json
Fixes missing Opera Android data for nullish coalescing
Just copies chromium data across
Fixes https://github.com/mdn/browser-compat-data/issues/15591
> Fix opera android data for nullish coalescing

- webextensions/api/contentScripts.json
- webextensions/api/permissions.json
This PR fixes #6762 by removing the remaining notes linking to polyfills.
> Remove notes linking to polyfills

- browsers/deno.json
> Update browsers/ for Deno 1.20

- css/properties/align-content.json
- css/properties/align-items.json
- css/properties/align-self.json
This PR reverts some unrelated changes that were made in #15475, seemingly unintentionally.
> Revert unrelated changes made in #15475

- GOVERNANCE.md
Daniel and I always worked this way, but we never made it explicit in the governance doc.
> Clarify owner behavior for semver major/minor changes

- .github/CODEOWNERS
Drop myself from automatic review assignment, since this is no longer my actual job and I'm taking some weeks off (in which I definitely won't be doing any volunteer work).
@Elchi3, @queengooborg, and @Rumyra: y'all might want to consider setting up a team for the BCD owners group instead, but I'll leave question (and the implementation details) to you.
> Remove myself from CODEOWNERS review assignment

- css/types/color.json
This is the reorganization associated with #15646.
One page doesn't exist yet in content, here is the PR: mdn/content#14813
> Reorganization of css.types.color

- test/compare-features.test.js
- test/lint.js
This PR moves a unit test out of [linter](https://github.com/mdn/browser-compat-data/blob/master/test/lint.js#L161) and into a separate mocha test file similar to [`utils.test.js`](https://github.com/mdn/browser-compat-data/blob/master/test/utils.test.js). This unit test is still called by `npm run test`, since [`test`](https://github.com/mdn/browser-compat-data/blob/master/package.json#L52) script includes `npm run mocha`.
For reviewer convenience, I split it up into two commits: the actual change is in the first commit and the second commit is just `npm run fix`.
```
$ npm run test
> @mdn/browser-compat-data@3.1.1 test
> npm run mocha && npm run lint
> @mdn/browser-compat-data@3.1.1 mocha
> mocha "test/**.test.js"
utils
√ `escapeInvisibles()` works correctly
1 passing (3ms)
> …
```
> Refactor: move compare-features script test out of linter

- docs/contributing.md
This PR adds a section that describes using the mdn-bcd-collector to update BCD's data.
> Mention mdn-bcd-collector in contributing doc

- schemas/browsers.schema.json
- schemas/compat-data.schema.json
- scripts/fix-format.js
- test/test-format.js
This PR adds the missing JSON files to the Prettier commmands to ensure that our schema JSON are formatted as well.
> Format JSON files with Prettier

- javascript/builtins/intl/Intl.json
This is supported by at least two browser engines so per the guidelines is no longer experimental.
Based off existing data
> Unmark Intl.supportedValuesOf as experimental

- api/DataTransferItem.json
- api/FileSystemHandle.json
- api/Window.json
Marks the 6 remaining WICG File System Access API entries as standard track.
> Mark remaining WICG File System Access API entries as standard track

- api/HTMLElement.json
- browsers/safari.json
- browsers/safari_ios.json
- http/headers/content-security-policy.json
Adds support data for Safari 15.5 Beta
See https://developer.apple.com/documentation/safari-release-notes/safari-15_5-release-notes
> Add Safari 15.5 Beta

- api/Navigation.json
- api/NavigationCurrentEntryChangeEvent.json
- api/NavigationDestination.json
- api/NavigationEvent.json
- api/NavigationHistoryEntry.json
- api/NavigationTransition.json
- api/Window.json
Add data and entries for Navigation API
https://wicg.github.io/navigation-api
https://chromestatus.com/feature/6232287446302720
> Add Navigation API

- api/Navigator.json
- css/properties/transition.json
- css/types/image.json
- javascript/statements.json
- webextensions/api/menus.json
This PR fixes the HTML within the notes we have.
> Fix HTML within notes

- api/Bluetooth.json
- api/BluetoothCharacteristicProperties.json
- api/BluetoothDevice.json
- api/BluetoothRemoteGATTCharacteristic.json
- api/BluetoothRemoteGATTDescriptor.json
- api/BluetoothRemoteGATTServer.json
- api/BluetoothRemoteGATTService.json
- api/BluetoothUUID.json
- api/Navigator.json
- css/properties/grid-auto-columns.json
- css/properties/grid-auto-rows.json
- html/global_attributes.json
- javascript/builtins/Object.json
This PR replaces all double spaces from our notes.
> Remove double spaces from notes

- api/Navigation.json
- api/NavigationHistoryEntry.json
This PR is a quick follow-up to #15951 which restructures the event handlers that were added to the new events structure.
CC @Elchi3
> Restructure events for Navigation APIs to new structure

- api/Geolocation.json
Replace redirected link.
fix: #16030
> api.Geolocation - Update link to GPSd

- api/HTMLElement.json
- html/global_attributes.json
Updating `HTMLElement.inert` as Chrome is shipping in 102. Also added `inert` as a global attribute. 
https://chromestatus.com/feature/5703266176335872
> updating inert

- .github/ISSUE_TEMPLATE/data-problem.yml
Quick fix to the new issue template.  (Would be very nice if GitHub had a validation tool available...)
> Fix issue template

- .github/ISSUE_TEMPLATE/data-problem.yml
I know I'm self-merging a lot of these quick fixes that end up not working out right...urgh, I so wish there was a way to double-check the template before merging.
> Fix indentation in issue template

- browsers/firefox.json
- browsers/firefox_android.json
Hello everyone!
I updated Firefox browser to version 100, according to [this release note](https://developer.mozilla.org/docs/Mozilla/Firefox/Releases/100).
 😉
> Updates firefox to version 100

- api/HTMLInputElement.json
- api/HTMLTextAreaElement.json
Adding a few spec links to properties.
> Add some spec_url for input/textarea properties

- api/FeaturePolicy.json
This PR updates and corrects the real values for Opera and Opera Android for the `features` member of the `FeaturePolicy` API, based upon results from the [mdn-bcd-collector](https://mdn-bcd-collector.appspot.com) project (v6.0.1).
Tests Used: https://mdn-bcd-collector.appspot.com/tests/api/FeaturePolicy/features
> Update Opera versions for api.FeaturePolicy.features

- api/MediaKeyMessageEvent.json
- api/MediaKeySession.json
- api/MediaKeyStatusMap.json
- api/MediaKeySystemAccess.json
- api/MediaKeys.json
- api/Notification.json
- api/NotificationEvent.json
- api/ServiceWorkerRegistration.json
Supported by every browser but IE -> no more experimental.
> EME not experimental

- docs/publishing.md
This PR updates the publishing release steps slightly to reflect the order of steps I had taken in the most recent release, as well as provide additional wording.
> Update release publishing document

- api/PresentationConnectionCloseEvent.json
- api/PresentationConnectionList.json
- api/PresentationReceiver.json
This PR is a subset of #16051 that adds spec URLs for the presentation APIs.
> Add spec URLs for presentation APIs

- api/DOMMatrix.json
- api/DOMMatrixReadOnly.json
- api/DOMPointReadOnly.json
- api/DOMQuad.json
- api/DOMRectReadOnly.json
- api/DOMStringList.json
This PR is a subset of #16051 that adds spec URLs for the geometry APIs.
> Add spec URLs for geometry APIs

- api/USBAlternateInterface.json
- api/USBEndpoint.json
- api/USBInTransferResult.json
- api/USBInterface.json
- api/USBIsochronousInTransferPacket.json
- api/USBIsochronousInTransferResult.json
- api/USBIsochronousOutTransferPacket.json
- api/USBIsochronousOutTransferResult.json
- api/USBOutTransferResult.json
- api/USBPermissionResult.json
This PR is a subset of #16051 that adds spec URLs for the USB APIs.
> Add spec URLs for USB APIs

- api/ServiceWorker.json
- api/ServiceWorkerGlobalScope.json
- api/ServiceWorkerRegistration.json
This PR is a subset of #16051 that adds spec URLs for the service worker APIs.
> Add spec URLs for service worker APIs

- api/AudioListener.json
- api/AudioParam.json
- api/AudioProcessingEvent.json
- api/AudioWorkletGlobalScope.json
- api/MediaDeviceInfo.json
- api/MediaEncryptedEvent.json
- api/MediaList.json
- api/MediaStream.json
- api/MediaStreamTrack.json
- api/MediaStreamTrackEvent.json
- api/MediaStreamTrackProcessor.json
This PR is a subset of #16051 that adds spec URLs for the various media APIs.
> Add spec URLs for media APIs

- api/RTCCertificate.json
- api/RTCDTMFSender.json
- api/RTCDtlsTransport.json
- api/RTCEncodedAudioFrame.json
- api/RTCEncodedVideoFrame.json
- api/RTCError.json
- api/RTCIceTransport.json
- api/RTCIdentityProviderGlobalScope.json
- api/RTCIdentityProviderRegistrar.json
- api/RTCPeerConnectionIceErrorEvent.json
- api/RTCPeerConnectionIceEvent.json
- api/RTCSctpTransport.json
This PR is a subset of #16051 that adds spec URLs for the RTC APIs.
> Add spec URLs for RTC APIs

- webextensions/manifest/web_accessible_resources.json
MV3 web_accessible_resource key changes adding `resources`, `matches`, `extension_ids`, and `use_dynamic_url`.
Tested and passed `npm test`.
> MV3 web_accessible_resources

- webextensions/manifest/host_permissions.json
Adds compatibility data for host_permissions. 
Corresponding documentation changes in https://github.com/mdn/content/pull/15183
> Compatibility data for host_permissions

- api/ServiceWorkerRegistration.json
This per our guideline:
https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines.md#parameters-and-parameter-object-features
> Fix names and descriptions of showNotification() parameter entries

- webextensions/api/action.json
MV3 Action API.
Tested and passed `npm test`.
> MV3 Action API

- webextensions/manifest/content_security_policy.json
MV3 Content Security Policy key changes:
- updated `extension_pages`
- added `sandbox`
Tested and passed `npm test`.
> MV3 Content Security Policy

- api/Accelerometer.json
`Accelerometer` is supported only by Chromium -> experimental
> Set experimental flags on Accelerometer.*

- css/properties/scrollbar-color.json
- css/selectors/hostfunction.json
This PR replaces some of our angle brackets in notes with HTML-formatted entities to ensure valid HTML throughout our notes.
> Ensure our notes are HTML-formatted

- .github/workflows/add-push-artifacts.yml
- .github/workflows/node.js.yml
- .github/workflows/pr-rebase-needed.yml
- .github/workflows/release.yml
This PR runs Prettier on the GitHub Actions workflow files, making my editor happy!
> Run Prettier on GitHub actions files

- api/Performance.json
- api/PerformanceEventTiming.json
- api/PerformanceLongTaskTiming.json
- api/PerformanceMark.json
- api/PerformanceMeasure.json
- api/PerformanceNavigation.json
- api/PerformanceTiming.json
This PR is a subset of #16051 that adds spec URLs for the various performance APIs.
> Add spec URLs for Performance APIs

- javascript/statements.json
Fixes https://github.com/mdn/content/pull/14037
> Add an additional spec URL for javascript.statements.import

- scripts/diff.js
- scripts/lib/git.js
- scripts/migrations/006-sort-features.js
- test/linter/test-notes.js
This PR ensures that all of our files contain the copyright notice and `use strict`.
> Ensure copyright notice is applied to all files

- scripts/migrations/007-experimental-false.js
This PR fixes the ESLint errors in the script for migration 007.
> Fix ESLint errors for migration 007

- scripts/fix/index.js
- scripts/traverse.js
- test/lint.js
This PR fixes all the errors reported by ESLint.
> Fix ESLint errors

- scripts/release/notes.js
This PR fixes imports in the release notes script.
> Fix release notes script

- docs/contributing.md
- scripts/mirror.js
Reverts mdn/browser-compat-data#6582.  The PR was accidentally merged before it was ready.
> Revert "Mirroring script: Edge mirrors from both IE AND Chrome at the same time"

- scripts/mirror.js
This PR de-duplicates code used for generic bumping in the mirroring script.
> Mirroring script: de-duplicate code

- http/headers/sourcemap.json
- test/spec-urls.test.js
Related MDN PR: https://github.com/mdn/content/pull/16225
> Add SourceMap spec URL

- svg/elements/a.json
Related MDN PR: https://github.com/mdn/content/pull/16313
> Add spec_url and mdn_url for SVG “a” xlink_href

- scripts/mirror.js
- scripts/mirror.test.js
This PR fixes the failing tests.
> Fix unittests

- scripts/mirror.js
This PR updates the mirroring script to update notes within arrays, as well as update the version numbers within notes.
> Mirroring script: improve note mirroring

- scripts/mirror.js
This PR fixes the ESLint error in the note mirroring.
> Fix note mirroring

- scripts/statistics.js
This PR fixes a typo in the statistics script.
> Fix issue in statistics script

- api/AudioContext.json
- api/GamepadHapticActuator.json
This is the result of running scripts/migrations/007-experimental-false.js
with no manual changes.
> Set more experimental statuses to false

- docs/testing.md
- scripts/traverse.js
This PR fixes the arguments passed into the traverse script.  Fixes #16505.
> Fix arguments passed into traverse script

- api/HTMLAnchorElement.json
- api/HTMLAreaElement.json
- api/HTMLLinkElement.json
- api/HTMLStyleElement.json
- api/ProcessingInstruction.json
Follow up to https://github.com/mdn/browser-compat-data/pull/16509.
> Fix Safari 3 versions that were in Safari 1

- api/DOMException.json
Node.js has already supported DOMException since v17.0.0.
https://nodejs.org/api/globals.html#domexception
> Node.js supports DOMException

- http/headers/public-key-pins-report-only.json
- http/headers/public-key-pins.json
Remove two comments reading "See bug ***".
HPKP was deprecated and removed from the Web Platform. Linked issues were closed with explicit statements that these features will not be implemented:
https://bugzilla.mozilla.org/show_bug.cgi?id=1091177#c1
https://bugzilla.mozilla.org/show_bug.cgi?id=1091176#c21
N/A
> HPKP: remove irrelevant notes

- scripts/generate-types.js
This PR fixes the bad typedef that was introduced in #16497.
> Fix typedef for Identifier

- test/lint.js
This PR fixes a typo in #16535.
> Fix a typo in the main linter

- test/lint.js
> Fix linter output

- test/utils.js
- test/utils.test.js
- utils/walkingUtils.js
- utils/walkingUtils.test.js
Minor bug fixes and tests.
N/A
Part of this PR was split out from #16574.
> Tests: minor bug fix and tests

- browsers/opera.json
This PR updates the Opera release data per the Opera blog.
> Update Opera release data

- css/properties/page-break-inside.json
Also mirror the Firefox Android entry to simplify.
> Simplify </code><code> in note for page-break-inside

- schemas/compat-data.schema.json
- scripts/generate-types.js
This PR updates the typedef generation to fix some issues as well as prepare for TypeScript migration.
> Update typedef generation

- .prettierignore
- scripts/enumerate-features.js
- utils/walk.js
This PR updates the feature enumeration to include browser releases.  Browser releases will now be included in the release notes.
> Include browser releases in feature enumeration

- test/lint.js
This PR fixes #16572 by converting the linter into an asynchronous script.
> Make linter asynchronous

- api/MediaMetadata.json
- api/Worker.json
- javascript/statements.json
This fixes consistency errors found by #16614.
This is simple mirroring based on parent feature support.
This blocks #16614 which in turn blocks #16593.
> Fix: cleanup Consistency errors

- .github/labeler.yml
> Label utils/ as infra

- css/types/color.json
This PR fixes the property sorting from #16526.
> Fix property sorting

- scripts/migrations/009-mirror.ts
This PR converts the mirroring migration script to TypeScript.
> Convert mirroring migration script to TypeScript

- scripts/enumerate-features.ts
This PR fixes the `enumerate-features` script.
> Fix feature enumeration script

- css/at-rules/media.json
Added "mdn_url" links for `dynamic-range` and `video-dynamic-range`
> Add MDN URLs for dynamic-range and video-dynamic-range

- scripts/release/build.test.ts
- scripts/release/build.ts
- scripts/release/mirror.test.ts
- scripts/release/mirror.ts
This PR adds additional `build` and `mirror` tests, as well as performs a few quick fixes to the mirroring script.
> Update mirroring script; add build/mirror tests

- scripts/release/build.ts
This PR fixes all of the paths throughout the build script to ensure that the correct files are copied and created.
> Fix paths in build script

- scripts/release/build.ts
This PR removes a few unused imports from the build script.
> Remove unused imports

- test/lint.ts
Add a nice linter message.
This is entirely a cosmetic change, it just adds a message to the test output after `All data passed linting!`:
```
Loading and checking files...
Testing browser data...
Testing feature data...
Testing all features together...
All data passed linting!
Linters have some exceptions, please help us remove them!
Obsolete has 10 exceptions.
- css.types.length.lh
- css.types.length.rlh
- http.headers.Cache-Control.stale-if-error
- http.headers.Feature-Policy.layout-animations
- http.headers.Feature-Policy.legacy-image-formats
- http.headers.Feature-Policy.oversized-images
- http.headers.Feature-Policy.unoptimized-images
- http.headers.Feature-Policy.unsized-media
- svg.attributes.presentation.color-rendering
- svg.elements.view.zoomAndPan
```
This message increases …
> Linter: add message about exceptions

- javascript/operators/import.json
- javascript/statements.json
In accordance with https://github.com/mdn/content/pull/17402
> Split dynamic import into operators

- http/status.json
- test/linter/test-spec-urls.ts
Added link to spec on semantics: https://html.spec.whatwg.org/multipage/semantics.html#early-hints
See https://github.com/mdn/content/issues/17374
> HTTP status code 103 early hint, add spec on semantics of this status code

- browsers/deno.json
Deno 1.23 was released a couple weeks ago, with support for some new web features. Adding this version unblocks documenting those with the correct version.
Related to #16791 
Related to mdn/content#17331
> Update deno.json with v1.23

- javascript/builtins/globals.json
- javascript/operators/null.json
In accordance with https://github.com/mdn/content/pull/17546
> Move null from Global Objects to Operators/Expressions

- api/DOMQuad.json
- api/HTMLAllCollection.json
- api/MediaEncryptedEvent.json
- api/NDEFMessage.json
- api/PaintRenderingContext2D.json
- api/PaymentInstruments.json
- api/PaymentManager.json
- api/PerformanceMark.json
- api/PresentationConnectionCloseEvent.json
- api/PushSubscriptionChangeEvent.json
- api/SpeechRecognitionEvent.json
- api/TextDecoder.json
- api/XMLHttpRequestUpload.json
- api/XPathEvaluator.json
- api/XSLTProcessor.json
These were found in an exercise of grouping features by spec, and these
entries were not put in the expected group because of the missing URLs.
> Add some missing spec URLs

- css/properties/rotate.json
- css/properties/scale.json
- css/properties/translate.json
Chrome 104 has support for individual transform properties
ChromeStatus Entry: https://chromestatus.com/feature/5705698193178624
Chrome Tracking Bug: https://bugs.chromium.org/p/chromium/issues/detail?id=496550
> Chrome 104 has support for individual transform properties

- api/_globals/fetch.json
Per our guidelines:
https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines.md#parameters-and-parameter-object-features
> Fix names and description of fetch parameters

- webextensions/api/storage.json
Corrected wrong path for mdn_url
> mdn_url: wrong path

- docs/data-guidelines.md
This PR updates the irrelevant feature guidelines to reflect our intent to remove all unsupported features.
> Update irrelevant feature guidelines

- api/CacheStorage.json
This follows the structure of Request and allow more of the data to be
mirrored.
> Improve structure of CacheStorage entries for Chromium

- javascript/operators/spread.json
This PR adds a `__compat` object to the spread operator itself.
> Add __compat to spread operator

- scripts/release/mirror.ts
This PR replaces the `combineStatements` function in the mirroring script with a simplified `flattenStatements`.  Combining statements is not needed in mirroring since mirroring from multiple sources had been abandoned.
> Don't combine statements in mirroring

- scripts/release/mirror.ts
No special case for changes before Edge 79 is not needed, it is handled
by the version_added === version_removed check.
This does not result in any changes to the built data.
> Simplify mirroring for Edge

- javascript/operators/destructuring.json
Destructuring comes in two distinct kinds: binding and assignment. Even some proposal authors [are not aware of that](https://github.com/tc39/proposal-destructuring-private/issues/3). Adding a spec URL would help. This accompanies https://github.com/mdn/content/pull/18495
> Add a destructuring spec URL

- api/HTMLIFrameElement.json
- html/elements/iframe.json
Turns out this isn't supported yet.
> Mark <iframe fetchpriority> as not supported and link bug

- scripts/fix/status.ts
- scripts/migrations/010-set-oculus-to-mirror.ts
- scripts/release/mirror.ts
This PR removes unused variables and functions throughout BCD's scripts.
> Remove unused variables and functions

- scripts/release/mirror.ts
In the recursive call to `bumpSupport`, the result can only be a
`SimpleSupportStatement`. This allows simplifying `flattenStatements` and it
won't actually do any flattening. Instead inline the little that remains
into `bumpSupport`.
This does not result in any changes to `build/data.json`.
> Simplify mirroring code around flattening statements

- css/properties/clip-path.json
> Fix: #17015

- api/Clients.json
- api/Console.json
- api/RTCRtpSender.json
- api/_globals/atob.json
- css/properties/border-bottom-left-radius.json
- css/properties/border-bottom-right-radius.json
- css/properties/border-top-left-radius.json
- css/properties/border-top-right-radius.json
This PR is a cherry-pick of #17006 that only includes the already-reviewed changes from that PR (hence the quick merge).
> Simplify multiple support statements with just notes (redo reviewed parts)

- api/GlobalEventHandlers.json
This PR demixes the `error` event from the GlobalEventHandlers mixin.
> Demix error event from GlobalEventHandlers

- css/selectors/buffering.json
- css/selectors/muted.json
- css/selectors/paused.json
- css/selectors/playing.json
- css/selectors/seeking.json
- css/selectors/stalled.json
- css/selectors/volume-locked.json
Fixes https://github.com/mdn/content/issues/10035. See https://drafts.csswg.org/selectors/#video-state and https://github.com/WebKit/WebKit/commit/b64b4d1 and note the `releases/Apple/Safari-15.4-macOS-12.3.1` tag
> Add CSS :playing/:paused/:seeking/:buffering/:stalled/:muted/:volume-locked

- css/properties/offset-path.json
Fix Safari version.
This fixes: #17112
> Fix: #17112

- api/Event.json
- api/EventTarget.json
- api/MediaDevices.json
- api/MessageChannel.json
- api/Navigator.json
- api/Request.json
- api/TextDecoder.json
- api/TextEncoder.json
- api/URL.json
- api/URLSearchParams.json
- api/Window.json
- api/XMLHttpRequest.json
This PR is a cherry-pick of #17006 for unreviewed portions of the `api/` folder.
> Simplify multiple support statements with just notes for api/

- webextensions/api/extension.json
- webextensions/api/identity.json
- webextensions/api/tabs.json
- webextensions/api/topSites.json
- webextensions/manifest/page_action.json
This PR is a cherry-pick of #17006 for the unreviewed parts of the `webextensions/` folder.
> Simplify multiple support statements with just notes for webextensions/

- javascript/builtins/Function.json
Correct version.
Fixes #16901
(Sorry about to commit messages I mis-clicked and hit the semicolon and the commit button 🤦‍♂️)
> Update Chromium data for javascript.builtins.Function.toString

- api/BlobBuilder.json
- api/Crypto.json
- api/CryptoKey.json
- api/FetchEvent.json
- api/LayoutShiftAttribution.json
- api/Navigator.json
- api/SubtleCrypto.json
- api/TransitionEvent.json
- api/WebGL2RenderingContext.json
- css/properties/backdrop-filter.json
- css/selectors/autofill.json
- css/selectors/buffering.json
- css/selectors/muted.json
- css/selectors/paused.json
- css/selectors/playing.json
- css/selectors/seeking.json
- css/selectors/stalled.json
- css/selectors/volume-locked.json
- http/headers/Content-Security-Policy.json
- mathml/global_attributes.json
Some more data is possible to mirror with recent changes.
The resulting build/data.json is unchanged.
> Run scripts/migrations/009-mirror once more

- api/BluetoothRemoteGATTCharacteristic.json
- api/BluetoothUUID.json
Resolves https://github.com/mdn/content/pull/19340#issuecomment-1210188399
> api.Bluetooth: fix 'experimental' statuses

- scripts/diff-features.ts
- scripts/diff.ts
- scripts/enumerate-features.ts
- scripts/fix/links.ts
- scripts/fix/property-order.ts
- scripts/fix/statement-order.ts
- scripts/fix/status.ts
- scripts/generate-types.ts
- scripts/lib/compare-statements.test.ts
- scripts/lib/extend.ts
- scripts/lib/git.ts
- scripts/lib/pluralize.ts
- scripts/migrations/007-experimental-false.ts
- scripts/migrations/009-mirror.ts
- scripts/migrations/010-set-oculus-to-mirror.ts
- scripts/release/build.ts
- scripts/release/changes.ts
- scripts/remove-redundant-flags.ts
This PR is the first part to add JSDoc descriptions to the various script files throughout BCD.
> Add JSDoc descriptions to all files (part 1)

- scripts/release/mirror.ts
This PR updates the mirroring script to add JSDoc comments and remove a redundant additional function.
> Update mirroring script to simplify statements

- scripts/release/changes.ts
- scripts/release/index.ts
- scripts/release/mirror.ts
- scripts/release/semver-pulls.ts
- scripts/release/stats.ts
- scripts/release/utils.ts
- scripts/statistics.ts
- scripts/traverse.ts
- test/lint.ts
This PR is the second part to add JSDoc descriptions to the various script files throughout BCD.
> Add JSDoc descriptions to all files (part 2)

- test/linter/test-browsers-data.ts
- test/linter/test-browsers-presence.ts
- test/linter/test-consistency.ts
- test/linter/test-descriptions.ts
- test/linter/test-filename.ts
- test/linter/test-links.ts
- test/linter/test-multiple-statements.ts
- test/linter/test-notes.ts
- test/linter/test-obsolete.ts
- test/linter/test-prefix.ts
- test/linter/test-schema.ts
- test/linter/test-spec-urls.ts
- test/linter/test-status.ts
- test/linter/test-style.ts
- test/linter/test-versions.ts
This PR is the third part to add JSDoc descriptions to the various script files throughout BCD.
> Add JSDoc descriptions to all files (part 3)

- test/utils.ts
- utils/iter-support.ts
- utils/normalize-path.ts
- utils/walk.ts
- utils/walkingUtils.ts
This PR is the fourth and final part to add JSDoc descriptions to the various script files throughout BCD.
> Add JSDoc descriptions to all files (part 4)

- browsers/firefox.json
- browsers/firefox_android.json
This PR adds additional planned releases for Firefox to the browser compat data.
> Add planned Firefox releases

- browsers/chrome.json
- browsers/chrome_android.json
- browsers/webview_android.json
This PR adds additional planned Chrome releases to BCD.
> Add planned Chrome releases

- scripts/release/changes.ts
This PR improves the console output for feature diffs while generating the changelog, to better clarify feature addition and removal at a glance.
> Improve release changelog console output

- http/headers/Origin.json
Fix sentence `this header was not sent with sent with` => `this header was not sent with`
> Fix incorrect sentence

- test/linter/test-status.ts
This PR fixes and improves the status test function.
> Fix and improve test-status

- css/at-rules/property.json
Adding notes for Safari and Firefox with (shortened) links to respective issues:
- https://bugs.webkit.org/show_bug.cgi?id=189692 
- https://bugzilla.mozilla.org/show_bug.cgi?id=1684605
> Add tracking bugs for @property in WK and Fx

- webextensions/manifest/permissions.json
Updates the unlimitedStorage documentation to acknowledge truly unlimited storage availability in Safari 16.
- [What’s new in Safari Web Extensions](https://developer.apple.com/videos/play/wwdc2022/10099/)
> Update unlimitedStorage note for Safari 16

- javascript/builtins/Array.json
- javascript/builtins/TypedArray.json
The findLast* proposal has been merged into the ES spec itself.
> Update the (Typed)Array.p.findLast* spec URLs

- api/XRRenderState.json
> Add XRRenderState.layers

- api/XRLayerEvent.json
> Add XRLayerEvent

- api/XRMediaBinding.json
> Add XRMediaBinding

- api/XRWebGLBinding.json
> Add layer features to XRWebGLBinding

- api/XRWebGLSubImage.json
> Add XRWebGLSubImage

- api/XRSubImage.json
> Add XRSubImage

- api/XRCubeLayer.json
> Add XRCubeLayer

- api/XREquirectLayer.json
> Add XREquirectLayer

- api/XRCylinderLayer.json
> Add XRCylinderLayer

- api/XRQuadLayer.json
> Add XRQuadLayer

- api/XRProjectionLayer.json
> Add XRProjectionLayer

- api/XRCompositionLayer.json
> Add XRCompositionLayer

- api/XRWebGLLayer.json
Ships in Oculus 8.0 https://developer.oculus.com/documentation/web/browser-release-notes/#oculus-browser-80
> Add XRWebGLLayer.fixedFoveation

- api/XRFrame.json
- api/XRHand.json
- api/XRInputSource.json
- api/XRJointPose.json
- api/XRJointSpace.json
Ships in Oculus 15.1 https://developer.oculus.com/documentation/web/browser-release-notes/
Spec: https://immersive-web.github.io/webxr-hand-input/
> Add WebXR Hand Input API

- RELEASE_NOTES.md
- api/Element.json
- api/Event.json
- api/FileSystem.json
- api/HTMLMediaElement.json
- api/MouseEvent.json
- api/Request.json
- api/SVGGraphicsElement.json
- api/TextTrack.json
- css/at-rules/media.json
- css/properties/hyphens.json
- css/types/image.json
- docs/data-guidelines/api.md
- docs/data-guidelines/index.md
- docs/faq.md
- docs/testing.md
- javascript/builtins/Intl/NumberFormat.json
- schemas/compat-data-schema.md
- scripts/diff-features.ts
- scripts/release/index.ts
- scripts/release/mirror.test.ts
- scripts/remove-redundant-flags.ts
- test/utils.ts
- webdriver/commands/CloseWindow.json
- webextensions/api/omnibox.json
Ran Vale to find duplicates, then cSpell for typos
> fix: various typos

- api/XRQuadLayer.json
Typo: s/xrprojectionlayer/xrquadlayer/ in fragment IDs
> Update XRQuadLayer spec URLs

- javascript/builtins/Intl/DateTimeFormat.json
- javascript/builtins/Intl/NumberFormat.json
This is something I wish to document. To do this we first need compat data.
I shamelessly stole the data from here: https://github.com/ljharb/intl-fallback-symbol
I've confirmed the Node versions myself.
I think the description looks a bit awful. Let me know if there're any concerns.
> Add data for Intl.[[FallbackSymbol]]

- api/BeforeInstallPromptEvent.json
This pairs with [this content update](https://github.com/mdn/content/pull/19927). Here's [where the mistake was corrected](https://storage.googleapis.com/chromium-find-releases-static/69e.html#69eeb5b901d805ec2411212d52f1e8d935d58092).
> Make note about return value of prompt()

- css/at-rules/page.json
The spec listed only added new descriptors for @page. I added the main spec for it, that was mssing.
> Add main spec for @page

- CODE_OF_CONDUCT.md
- docs/data-guidelines/api.md
- schemas/compat-data-schema.md
This PR performs a couple of tweaks to the Markdown docs to improve formatting.
> Update Markdown formatting

- docs/matching-browser-releases/index.md
> Correct typos

- css/at-rules/font-palette-values.json
These can all use un-leveled https://drafts.csswg.org/css-fonts/ URLs
> Update CSS @font-palette-values spec URLs

- css/at-rules/container.json
Shipped in Chrome 105, and also in Safari 16 beta,
> Adds the @container rule

- .github/ISSUE_TEMPLATE/data-problem.yml
- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/add-push-artifacts.yml
- .github/workflows/close-incomplete-issues.yml
- .github/workflows/labeler.yml
- .github/workflows/node.js.yml
- .github/workflows/ping-other-repos.yml
- .github/workflows/pr-rebase-needed.yml
- .github/workflows/release.yml
- .prettierignore
- .prettierrc
- Remove empty arrays
- Remove unessessary quoting
- Rename and remove default values from Node.js action template
> Format .github folder

- .github/workflows/pr-rebase-needed.yml
This PR is a second attempt to fix the permissions for the rebase-needed PR.
> Fix permissions for pr-rebase-needed workflow

- test/linter/test-spec-urls.ts
Follow-up to https://github.com/mdn/browser-compat-data/pull/17546
> Remove hashbang spec exception

- test/linter/test-descriptions.ts
This PR updates the descriptions test to prepare for an eventual fix script.
> Update descriptions test to prepare for fix list

- browsers/chrome.json
- browsers/chrome_android.json
- browsers/webview_android.json
Hello! 
This PR updates Chrome to version 105.
> Updates chrome browser to version 105

- api/Element.json
- api/ElementInternals.json
Seems like these two were forgotten. The MDN pages exist but render without compat table.
This PR fixes it.
> Add Element(Internals).ariaColIndexText/ariaRowIndexText

- api/HID.json
See https://github.com/mdn/content/pull/20478 for the content work.
> Add mdn_urls for HID events

- docs/data-guidelines/browsers.md
The browser data guidelines' links are broken (I suppose because they're nested on level deeper than before).
I clicked on them and 💔 
#17519
> Fix broken links in browser data guidelines

- webextensions/api/devtools.json
Fix `mdn_url`s for `webextensions.api.devtools.*` entries.
N/A
Corresponding MDN content PR landed in January 2021: https://github.com/mdn/content/pull/598
> Fix: update webextensions.api.devtools MDN URLs

- .github/workflows/release.yml
This PR fixes the release script's permissions.
> Fix release script permissions

- css/properties/container-name.json
- css/properties/container-type.json
- css/properties/container.json
The data was filled in by the mdn-bcd-collector, and matches the other
data for Container Queries.
> Add CSS container-* properties and shorthand

- api/WebGLRenderingContext.json
Content written in https://github.com/mdn/content/pull/21021
> Add mdn_urls for drawingBufferColorSpace & unpackColorSpace

- browsers/firefox.json
- browsers/firefox_android.json
Hi!
Updating firefox browser data 😉
> Updates firefox browser to version 105

- docs/contributing.md
- docs/matching-browser-releases/index.md
Add some guidance for contributors looking to submit support data for the Meta Quest browser.
n/a
https://github.com/mdn/browser-compat-data/pull/17521
https://github.com/mdn/browser-compat-data/pull/17916
> Extend contribution guidelines with info on Quest

- browsers/chrome.json
- browsers/chrome_android.json
- browsers/webview_android.json
Hello!
This PR updates Chrome to version 106. 😉
> Updates chrome browser to version 106

- api/Navigator.json
- api/UserActivation.json
This was added to the HTML spec recently: https://github.com/whatwg/html/pull/8254
In Chromiums for a while already: https://chromestatus.com/feature/5131233151418368
> Add UserActivation Query API

- api/XRWebGLSubImage.json
https://immersive-web.github.io/layers/#xrwebglsubimagetype
Related MDN PR: https://github.com/mdn/content/pull/21508
> XRWebGLSubImage/textureHeight|Width → colorTextureHeight|Width

- css/properties/scroll-timeline-axis.json
- css/properties/scroll-timeline-name.json
- css/properties/scroll-timeline.json
The should use the un-leveled URLs.
> Update scroll-timeline spec URLs

- browsers/firefox.json
- browsers/firefox_android.json
Hello all!
Updating firefox browser to version 106 😉👋
> Updates firefox browser to version 106

- api/Navigator.json
- browsers/deno.json
Updates list of supported APIs in Deno v1.27
> Update data for Deno v1.27

- html/elements/select.json
This PR just adds links to `<select>` attributes which have MDN pages.
> Add urls to attributes in HTML element select

- browsers/chrome.json
- browsers/chrome_android.json
- browsers/webview_android.json
Hi!
This PR updates Chrome to version 107. 
😉
> Updates chrome browser to version 107

- css/properties/object-view-box.json
Adds BCD for the `object-view-box` property.
https://chromestatus.com/feature/5213032857731072
> Add object-view-box

- api/FontFaceSet.json
Related to https://github.com/mdn/content/pull/21328
> Note the deviant behavior of Chrome for check()

- css/types/calc-constant.json
Update constants in `<calc-constant>` data type.
Related: #17828
> Update descriptions for `<calc-constant>` CSS type

- api/Cache.json
Updates compat table for "Cache" API for Deno
> Update Cache API for Deno

- browsers/edge.json
Edge 107 was released last week. This PR updates the edge.json file based on the latest release note links and dates.
> New Edge browser release data

- browsers/opera.json
Hi all!
Updating opera to version 92.
> Include new opera release (v92)

- javascript/builtins/Intl.json
Intl.supportedValuesOf was added to node.js v18
> Intl.supportedValuesOf was added to node.js v18

- browsers/firefox.json
- browsers/firefox_android.json
Hello all!
Updating firefox browser to version 107 😉👋
> Updates firefox browser to version 107

- api/PerformanceObserver.json
Fixes https://github.com/mdn/browser-compat-data/issues/12733 
Content PR: https://github.com/mdn/content/pull/22318
> Add droppedEntriesCount to PerformanceObserver

- http/headers/Sec-CH-Prefers-Reduced-Motion.json
This PR adds BCD for the `Sec-CH-Prefers-Reduced-Motion` header; see my research document for more details: https://docs.google.com/document/d/1ENCgZ66Jsf40iMK1yatqQLeEHu9NC07Fhd6tKlgj_Bs/edit
I tested a demo in multiple browsers; only supported in Chrome at the moment.
> add data for Sec-CH-Prefers-Reduced-Motion header

- html/manifest/id.json
Fixes mdn/browser-compat-data#18192
> Add html.manifest.id BCD

- docs/contributing.md
- docs/issue-triage-checklist.md
This PR updates links to the collector with a new deployment hosted by Gooborg Studios (my company), which has been done for a couple of reasons.
> Point to new collector repository

- .github/workflows/close-incomplete-issues.yml
- .github/workflows/ping-other-repos.yml
This PR sets workflow permissions for the remaining two workflows.
> Set permissions for remaining GitHub actions

- .lintstagedrc
This PR fixes the .lintstagedrc config.
> Fix lintstagedrc config

- api/HTMLFontElement.json
- api/MediaStreamTrackProcessor.json
- api/RTCIceCredentialType.json
- api/Scheduling.json
- api/SpeechRecognitionEvent.json
- api/XRFrame.json
> Fix status inheritance inconsistency, round 2
